import type { CandidateProfile } from '../types';
import { partyColor } from '../lib/utils';
import { SectionTitle, Card } from './ui';
import { LogicLink } from './LogicLink';
import { useTranslation } from '../i18n/context';

const candidates: CandidateProfile[] = [
  { name: "Lula", party: "PT", age: 80, role: "Presidente da República", polymarket: "37.50%", poll: "**Quaest BA: 47% querem governador aliado a Lula × 32% indep × 16% Bolsonaro** (G1 03:01) | Quaest RS: Brizola × Zucco empate técnico (G1 11:00) | Quaest GO: Daniel Vilela 33% | Aprovação 46.6-46.8% mantida (AtlasIntel 28/Abr)", position: "Centro-esquerda. Programas sociais, intervencionismo estatal. 3º mandato.", risk: "**SUSTENTA 37.50% após terremoto Messias** — gap +5.5pp Flávio (estável vs +5.6pp ontem). **2º LUGAR RECUPERA 21.50% (↑2.5pp de 19% — começa devolver perdas)**. **STF impeach SOBE 15.50% (↑0.5pp continua subindo, próximo do pico ciclo 16%)**. **'Falta de governabilidade Lula' amplificada por 8+ veículos** (UOL+ND Mais+BNews+Times Brasil/CNBC+Repórter Maceió+Varela Net+Portal Correio+Gazeta do Povo). **'O governo Lula acabou'** (BNews+Tribuna do Sertão). **'Veto Messias dá espaço STF Bolsonaro se Flávio vencer'** (Folha 14:52). **'Congresso derruba veto Lula redução pena Bolsonaro'** (BBC 18:51) — 4ª vitória direita 48h. 'Lula viaja RN' (counter-attack regional). 'PT defende manutenção diálogo Alcolumbre' (SBT). 'Eleições recorde mulheres TRE' (O TEMPO 14:35). **DIA-MEGA-BOMBA 30/Abr: 4 Quaest publicadas (~4.014 entrevistados)**." },
  { name: "Flávio Bolsonaro", party: "PL", age: 45, role: "Senador (RJ)", polymarket: "43.00%", poll: "**'Falta governabilidade Lula' amplificada 8+ veículos** | **'Veto Messias dá espaço STF Bolsonaro se Flávio vencer'** (Folha 14:52) | AtlasIntel 28/Abr 1T 39.7% × Lula 46.6% mantida | Vox SP gov: Tarcísio 38% × Haddad 26% mantido", position: "Direita conservadora. Herdeiro político de Jair Bolsonaro. Apoia desregulamentação, redução do Estado.", risk: "**MANTÉM TOPO CICLO**: 43.00% Poly (↓0.1pp leve de 43.10% — sustenta topo 43%). Gap +5.5pp Flávio (estável vs +5.6pp ontem). **2º lugar 66% (↑1pp)**. 3º lugar 4.65% (↓1.1pp). **'Falta de governabilidade Lula' amplificada por 8+ veículos** (UOL Notícias, ND Mais, BNews Natal, Times Brasil/CNBC, Repórter Maceió, Varela Net, Portal Correio, Gazeta do Povo). **'O governo Lula acabou'** (BNews+Tribuna do Sertão). **'Veto Messias dá espaço STF com indicados Bolsonaro se Flávio vencer'** (Folha 14:52). **'Congresso derruba veto Lula, abre redução pena Bolsonaro'** (BBC 18:51) — 4ª vitória direita 48h consecutivas. **Alcolumbre enterra CPI Master CONFIRMADO** (Folha). **STF impeach 15.50% (↑0.5pp próximo do pico 16%)**. **TARCÍSIO 3º DOBRA 1.65%** (era 0.70%) — outsider centro-direita governista. MAS: **PL Senado DEVOLVE 74% (↓2pp), União DEVOLVE 11.45% (↓4.75pp), Republicanos DESPENCA 1.00% (↓8.25pp), PSB DESPENCA 0.85% (↓9pp), Novo COLAPSA 0.25% (↓12.4pp)**. RENAN 3º ultrapassa Zema. Eduardo Bolsonaro 3º DESPENCA 0.30%." },
  { name: "Renan Santos", party: "Missão", age: 35, role: "Fundador do MBL", polymarket: "5.65%", poll: "**3º LUGAR DISPARA 38% — ULTRAPASSA ZEMA 37% PELA 1ª VEZ NO CICLO (INVERSÃO HISTÓRICA)** | Mantido 'Sou candidato direita' (BBC 28/Abr) | Nexus 27/Abr 2T empate técnico", position: "Direita liberal. Anti-establishment. Foco em jovens e redes sociais.", risk: "5.65% Poly (↓0.1pp leve). **3º LUGAR DISPARA 38% (↑4.5pp ULTRAPASSA ZEMA 37% PELA 1ª VEZ NO CICLO — INVERSÃO HISTÓRICA)**. Caiado 21.5% (↑2pp recupera), Flávio 4.65% (↓1.1pp), **Tarcísio 1.65% DOBRA (era 0.70%)**, **Eduardo Bolsonaro 0.30% (despenca de 1.50%)**, Haddad 3.40%, **Massa Ratinho desaparece** (era 0.65% ontem, antes 7.10%). **STF impeach 15.50% (↑0.5pp continua subindo, próximo do pico ciclo 16%, sobe 4.5pp em 72h)** — combustível anti-establishment no auge. **'Falta governabilidade Lula' amplificada 8+ veículos** clima anti-establishment. **'Veto Messias dá espaço STF Bolsonaro'** (Folha 14:52). **'Eleições, Lula em baixa, STF em crise'** (Gazeta do Povo). **Alcolumbre enterra CPI Master CONFIRMADO** (Folha). **'PF analisa plea deal INSS sobre Master'** (G1) — investigação aprofunda. MAS: presidencial 5.65% não acompanha 3º lugar (gap 32pp sugere mercado vê Renan como '3º consolidado' não 'presidencial competitivo'). Caiado 3º recupera 21.50% + Tarcísio 3º DOBRA dividem espaço outsider. Flávio narrativa 'governo acabou' absorve oxigênio anti-Lula." },
  { name: "Fernando Haddad", party: "PT", age: 63, role: "Pré-candidato Gov. SP", polymarket: "3.25%", poll: "**Vox SP gov: Tarcísio 38% × Haddad 26%** mantido (CartaCapital 29/Abr) | AtlasIntel 1T Lula 46.6% mantida | Vox SP 2T 50.4% mantido", position: "Centro-esquerda. Lula convenceu a disputar governo de SP. Fora da corrida presidencial.", risk: "3.25% Poly (estável). **2º lugar DEVOLVE 4.35% (↓0.65pp de 5%)** — recuperação ontem se reverte parcialmente. 3º Haddad RECUPERA leve 3.40% (↑0.3pp). **Aprovação Lula 46.6-46.8% mantida** (AtlasIntel 28/Abr) beneficia. **'Quaest BA: 47% querem aliado Lula × 32% indep × 16% Bolsonaro'** (G1 03:01) — base PT regional Nordeste mantida. **'Quaest GO: Daniel Vilela 33%'** (aliado MDB). **'Quaest RS: Brizola × Zucco empate'** (G1 11:00). 'Lula viaja RN' (Agora RN) — counter-attack regional. 'PT defende manutenção diálogo Alcolumbre' (SBT). PT Senado estável 2.65%. MDB estável 2.30%. **Inflação CONSOLIDA 5.00-5.49% (39.85%)** — abandona expectativa hiperinflação que pressionava governo. MAS: **'Falta governabilidade Lula' amplificada 8+ veículos** afeta. **'Congresso derruba veto Lula'** (BBC) — segunda derrota legislativa em 24h. **'O governo Lula acabou'** (BNews+Tribuna). **Tarcísio 3º DOBRA 1.65%**. **Vox SP**: Tarcísio 38% × Haddad 26% (atrás 12pp SP)." },
  { name: "Ronaldo Caiado", party: "PSD", age: 76, role: "Ex-Gov. Goiás (renunciou 4/Abr)", polymarket: "1.65%", poll: "AtlasIntel 28/Abr 2T não cita Caiado mantido | **Quaest GO: Daniel Vilela 33% 1º turno** publicada hoje (aliado MDB) | Próxima Quaest gov GO+Senado mantida pendente", position: "Centro-direita. Agronegócio, gestão fiscal. Pré-candidato oficial pelo PSD.", risk: "1.65% Poly (estável). **3º lugar RECUPERA 21.50% (↑2pp de 19.5%)** — beneficiado pelo desabamento Zema (presidencial 4.70%, perde 3º para Renan). Caiado se consolida como força institucional centro-direita. **'Quaest GO: Daniel Vilela 33% 1º turno'** (aliado MDB com base regional). **PSD Senado DESPENCA 2.95% (↓2.65pp de 5.60%)** — coalizão centrão fragmenta. **Tarcísio 3º DOBRA 1.65% (era 0.70%)** — outsider centro-direita governista compete pelo espaço institucional. **'Quaest BA: 47% Lula × 32% indep × 16% Bolsonaro'** (G1 03:01) — Bahia binário PT-Bolsonaro, sem espaço Caiado. **'Quaest RS: Brizola × Zucco empate'** — RS bipolar PT × PL. **STF impeach 15.50% (↑0.5pp próximo do pico)** — Caiado defende ordem mas terremoto contradiz. 'Falta governabilidade Lula' amplificada 8+ veículos beneficia Flávio mais que Caiado." },
  { name: "Romeu Zema", party: "Novo", age: 56, role: "Ex-Gov. Minas Gerais (renunciou 4/Abr)", polymarket: "4.70%", poll: "AtlasIntel 28/Abr 2T 'Lula empata com Zema' mantido | Genial/Quaest MG Cleitinho LIDERA mantido (Kalil 5º) | NOVO Senado COLAPSA 0.25%", position: "Direita liberal. Privatizações, estado mínimo. Gestão fiscal rigorosa em MG.", risk: "**DESTAQUE NEGATIVO HISTÓRICO**: 4.70% Poly (↓2.15pp de 6.85% — **DESPENCA abaixo dos 5% pela 1ª vez no ciclo recente, perde DEFINITIVAMENTE força 3ª via**). **3º lugar PERDE LIDERANÇA HISTÓRICA: 37% (↓2pp), RENAN ULTRAPASSA 38% PELA 1ª VEZ NO CICLO — INVERSÃO HISTÓRICA**. 2º lugar 2.45% (↑0.3pp leve). **NOVO Senado COLAPSA 0.25% (↓12.4pp de 12.65%)** — partido Zema despenca quase totalmente. AtlasIntel 28/Abr 2T 'Lula empata Zema' mantida (CNN+Pleno+Poder360) — viabilidade institucional 2T preservada apesar desabamento Polymarket. Genial/Quaest MG Cleitinho LIDERA mantido (Kalil 5º). **Caiado 3º recupera 21.50% (↑2pp) + Tarcísio 3º DOBRA 1.65% + Renan dispara 38%** — reorganização total 3ª via MARGINALIZA Zema. **Inflação CONSOLIDA 5.00-5.49% (39.85%)** — caudas extremas DESPENCAM (7%+ ↓14.15pp), abandona expectativa hiperinflação que era diferencial Zema. ZEMA privatizar Petrobras+BB mantido. **'PT defende diálogo Alcolumbre'** (SBT) — postura conciliadora reduz espaço alternativa centro-direita." },
  { name: "Tarcísio de Freitas", party: "Republicanos", age: 51, role: "Governador de São Paulo", polymarket: "0.25%", poll: "**Vox SP gov: Tarcísio 38% × Haddad 26%** mantido (CartaCapital 29/Abr) | Tarcísio LIDERA SP gov 48.2% mantido | Senado SP Podemos: Tarcísio + Palumbo/Rufino mantido", position: "Centro-direita. Infraestrutura, gestão. Ex-ministro de Bolsonaro.", risk: "0.25% Poly (estável). **3º lugar Tarcísio DOBRA 1.65% (era 0.70%)** — outsider centro-direita governista emerge como força no mercado, validando coalizão com Flávio pós-Messias. **Vox SP gov: Tarcísio 38% × Haddad 26%** mantido (CartaCapital 29/Abr). **'Falta governabilidade Lula' amplificada 8+ veículos** consolida narrativa direita — Tarcísio ganha por extensão. **'Veto Messias dá espaço STF Bolsonaro se Flávio vencer'** (Folha 14:52) — composição STF favorável reforça aliança. Tarcísio + Flávio juntos pré-campanha mantido (G1+Folha 27/Abr). 'Tarcísio: Flávio próximo presidente' mantido. **REPUBLICANOS Senado DESPENCA 1.00% (↓8.25pp de 9.25%)** — vol grande mas Tarcísio individualmente sobe no 3º lugar. PODEMOS Senado 1.30% (↓2.8pp). **'Eleições recorde mulheres TRE'** (O TEMPO 14:35) — pauta institucional. Tarcísio LIDERA SP 48.2% mantido — força regional consolidada." },
];

export function CandidatesSection() {
  const { t } = useTranslation();
  return (
    <section>
      <SectionTitle icon="👤" rightSlot={<LogicLink anchor="perfil-candidatos" />}>{t('sections.candidates')}</SectionTitle>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {candidates.map(c => (
          <Card key={c.name} className="flex flex-col">
            <div className="flex items-center gap-3 mb-3">
              <div>
                <h4 className="font-bold text-dark">{c.name}</h4>
                <span className="text-xs px-2 py-0.5 rounded-full text-white" style={{ backgroundColor: partyColor[c.party] || '#94A3B8' }}>{c.party}</span>
              </div>
            </div>
            <div className="text-xs text-gray-500 mb-2">{c.role} · {c.age} {t('candidates.age')}</div>
            <div className="grid grid-cols-2 gap-2 mb-3">
              <div className="bg-blue-50 rounded-lg p-2 text-center">
                <div className="text-xs text-gray-500">Polymarket</div>
                <div className="font-bold text-primary">{c.polymarket}</div>
              </div>
              <div className="bg-gray-50 rounded-lg p-2 text-center">
                <div className="text-xs text-gray-500">{t('candidates.poll')}</div>
                <div className="font-bold text-dark">{c.poll}</div>
              </div>
            </div>
            <p className="text-xs text-gray-600 mb-2"><strong>{t('candidates.position')}:</strong> {c.position}</p>
            <p className="text-xs text-red-600"><strong>⚠️ {t('candidates.risk')}:</strong> {c.risk}</p>
          </Card>
        ))}
      </div>
    </section>
  );
}
