/** Mapa EN de 02/Set/2026: analysis-data. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of Sep 2, 8:26 PM BRT (11:26 PM UTC)'
const QUAEST = 'Genial/Quaest of Sep 2 (BR-07065/2026, fieldwork Aug 30 to Sep 1, n=2,004, margin of 2pp)'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book holds USD 141.85M and the price on this page comes from the ${S}. ONE NATIONAL POLL WAS RELEASED THIS WEDNESDAY, ${QUAEST}, commissioned by Editora Globo, and its release was already listed in the TSE registry the panel ingested on the morning of Sep 2 itself, with the scheduled date and the registration number matching what was published.`,
  'cards.sentimento.text2': `On price, the leader did not move and stands at 55.50% for the fifth day running. The runner-up rose 1.70pp, to 40.65%, and the distance between the two fell from 16.55pp to 14.85pp. In the daily closes of the series that distance has already been at 14.3pp on Aug 30 and at 16.5pp on Sep 1, so today's value sits inside the range of the week itself.`,
  'cards.sentimento.text3': `Quaest published TWO ${G('first round', 'primeiro-turno')} scenarios, and the direction of the Marçal effect is the reverse of what was measured the day before. With Pablo Marçal on the list, the runner-up has 30% and Augusto Cury 10%. Without Marçal, the runner-up has 29% and Cury stays at 10%. In Real Time Big Data of Sep 1 it was the other way round, with 29% in the scenario with Marçal and 30% in the scenario without. Both Quaest scenarios close at exactly 100 once blanks, spoiled ballots and undecided voters are counted.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 40.65% (vol USD 9.48M accumulated) in the presidential contract, up 1.70pp, and 85.50% in the second-place contract for the first round, down 0.50pp. Quaest puts him at 30% in the scenario with Marçal and at 29% in the scenario without. In the ${G('runoff', 'segundo-turno')} he sits 1 point from the leader, 41% against 42%, and within the same house that distance was 5pp on Aug 5 and 3pp on Aug 14. Rejection of 55%, the highest among the thirteen names tested.`,
  'cards.sentimento.esquerda': `Lula at 55.50% (vol USD 9.59M accumulated), unchanged for the fifth day. Quaest puts him at 37% in both first-round scenarios and at 42% in a runoff against the runner-up, who has 41%. ⚠️ AND THE RUNOFF AGAINST RONALDO CAIADO REVERSES THE ONE FROM THE DAY BEFORE: here he wins 42% to 37%, whereas Real Time Big Data of Sep 1, whose fieldwork overlaps this one, put Caiado ahead 45% to 43%. That is 7pp of difference in the margin between two houses that measured the same week. Rejection of 53%.`,
  'cards.sentimento.terceiraVia': `Augusto Cury has 10% in both first-round scenarios from Quaest, against 2% in the same house's round of Aug 14 and 1% in the one from Aug 5. On price the move goes both ways: in the winner contract he FELL to 1.60% (vol USD 3.59M), down 0.75pp, and in the third-place contract for the first round he ROSE to 52.40% (vol USD 103 thousand), up 5.75pp. These are different questions: one is winning the election, the other is finishing third. His rejection is 25%, the lowest among the seven names with double-digit rejection on the table. Renan Santos has 3% in the poll and 2.20% (vol USD 12.36M) in the winner contract, down 0.35pp, and fell to 28.00% in the third-place contract.`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 point. This round publishes no new price for the Senate majority contract. The presidential book holds USD 141.85M.`,

  'cards.inss.text1': `The INSS case and the Banco Master case remain crossed at the Supreme Court, and the point of contact is still the same: the report from the INSS parliamentary inquiry asked for an investigation into the wife of Justice Alexandre de Moraes, according to PE Notícias.`,
  'cards.inss.text2': `What belongs to Sep 2 on the pension side is administrative, not political: a committee of Congress approved a provisional measure expanding a programme to cut INSS queues, according to G1, and the government announced it had cleared the queue, according to Folha de S.Paulo.`,
  'cards.inss.text3': `On the institutional front, Renan Santos filed an impeachment request against Moraes and against Dias Toffoli, according to G1. The president of the Senate cited money from the Dark Horse case when responding to pressure for the impeachment of Moraes, according to Folha de S.Paulo, and his position of not bringing the requests to the floor, recorded on Sep 1, did not change this Wednesday.`,
  'cards.inss.text4': `The case is still live and still without an outcome. The distinction the panel has kept from the start still holds: the effect on the government's approval rating is one thing, the effect on voting intention is another, and the two do not add up.`,
  'cards.inss.impactoLula': `Quaest of Sep 2 brings a fresh reading of government evaluation, with fieldwork from Aug 30 to Sep 1, already after the free electoral airtime debuted on Aug 28: 45% approve and 48% disapprove, with 7% giving no answer. On voting intention he stands at 37% in both first-round scenarios.`,
  'cards.inss.impactoGestao': `Within Quaest itself the picture is one of immobility. On Aug 5 it was 48% approval against 47% disapproval, on Aug 14 it was 46% against 48% and now it is 45% against 48%. Disapproval repeats the same figure for the third round running in that house. On the management scale, 35% rate it excellent or good, 25% average and 37% poor or terrible, against 36%, 25% and 37% on Aug 14.`,
  'cards.inss.conclusao': `On Sep 2 the axis of the news moved off the INSS and settled entirely on the Supreme Court. The panel does not attribute the change in the presidential price to that move: the leader did not budge for the fifth day and the runner-up rose 1.70pp on the same day the round's poll showed the runoff between the two one point apart.`,

  'cards.bancoMaster.text1': `IT IS THE STORY OF THE DAY FOR THE SECOND DAY, AND WHAT CHANGED ON SEPTEMBER 2 WAS THE CONFIRMATION, NOT THE FACT. The office of Justice André Mendonça confirmed in a statement that he met Daniel Vorcaro once, and the meeting took place on March 14, 2025, at the Iter Institute in São Paulo, according to Poder360 and O Globo. He took over the Banco Master case in February 2026, almost a year after that meeting.`,
  'cards.bancoMaster.text2': `It was also confirmed that Vorcaro gave a statement to an assistant judge in Mendonça's office, with a public prosecutor present and WITHOUT the Federal Police, according to Poder360 and O Globo. The statement was taken on August 27, 2026, on Thursday morning, inside the prison where the businessman has been held since November 17, 2025. The office cites a National Justice Council resolution to justify the absence of the Federal Police.`,
  'cards.bancoMaster.text3': `On September 2 the Supreme Court held its first session after the Federal Police report, with Moraes and Mendonça sitting side by side, and the Master case was not put on the agenda, according to O Globo and Folha de S.Paulo. The court's president, Edson Fachin, said justices must have limits and that he will announce the appropriate measures, according to Folha de S.Paulo and O Globo, and began talks with the other justices.`,
  'cards.bancoMaster.conclusao': `The chronology is the information, and it has five distinct dates: the meeting between the justice and the businessman is from March 14, 2025; the messages are from November 16, 2025; the arrest is from November 17, 2025; the Federal Police report was delivered on August 27, 2026, the same day as the statement taken without the Federal Police; and the seal was lifted on September 1. What belongs to September 2 is the public confirmation by the office itself and the court's first session after the report. ⚠️ AND WHAT HAS NOT HAPPENED YET IS ON THE CALENDAR: Mendonça's report on Moraes is expected on September 7 or 8, and the court's president will hold a session next week, according to Poder360.`,

  'cards.stf.toffoli': `No new individual act on Sep 2. His decision releasing Renan Santos's digital campaign is from Sep 1, and this Wednesday the candidate's social media accounts came back online, according to G1. He became the target of an impeachment request filed by Renan Santos himself, alongside Moraes, according to G1.`,
  'cards.stf.moraes': `HE IS STILL THE NAME OF THE DAY, AND AGAIN NOT THROUGH AN ACT OF HIS OWN. He took part in the court's first session after the Federal Police report, seated beside André Mendonça, and the Master case was not put on the agenda, according to O Globo and Folha de S.Paulo. He is the target of an impeachment request filed by Renan Santos, according to G1. The wing of the court that favours him accuses Mendonça of political motivation, according to O Globo.`,
  'cards.stf.gilmar': `Approached Lula to press for government support for the Federal Police leadership in the clash between Moraes and Mendonça, according to Folha de S.Paulo. Lula spoke with Fachin, Dino and Gilmar about the crisis, according to O Globo.`,
  'cards.stf.dino': `No new individual act captured on Sep 2. He was one of the justices Lula spoke to about the crisis, according to O Globo.`,
  'cards.stf.mendonca': `CONFIRMED IN A STATEMENT the meeting with Daniel Vorcaro, held on March 14, 2025 at the Iter Institute in São Paulo, almost a year before he took over the Banco Master case, according to Poder360 and O Globo. He also confirmed Vorcaro's statement to his office on August 27, 2026, with the public prosecutor's office and without the Federal Police, and said Moraes was not a topic at the 2025 meeting. His report on Moraes is expected on September 7 or 8, according to Poder360.`,
  'cards.stf.nexo': `THE COURT IS STILL THE STORY, AND THE NEW ELEMENT OF THE DAY IS ITS PRESIDENT STEPPING IN. Edson Fachin said justices must have limits, announced he will take the appropriate measures and began talks with the others, according to Folha de S.Paulo and O Globo. On the same Wednesday the court held its first session after the report without putting the case on the agenda, one justice publicly confirmed a meeting and a statement, and a presidential candidate filed an impeachment request against two justices. The TSE began ruling on the candidacy registrations of Lula, Flávio Bolsonaro, Zema and Renan Santos, according to Rádio Itatiaia.`,
  'cards.stf.analise': `The contract on a Supreme Court justice leaving through impeachment before 2027 stands at 6.35% (vol USD 87 thousand) in the ${S}, down 4.50pp against the 10.85% published on Sep 1. ⚠️ AND YESTERDAY'S READING HOLDS AGAIN, NOW IN THE OPPOSITE DIRECTION: this is the smallest book on the panel, and accumulated volume went from USD 86 thousand to USD 87 thousand, meaning roughly USD 1.3 thousand of fresh trading accompanies a fall of four and a half points. A price that moves a lot on little money does not describe a change in expectations of the same size. The contract measures a justice leaving; it does not measure whether the investigation prospers or whether the Senate brings the request to the floor.`,
})
