/** Mapa ES de 02/Set/2026: analysis-criteriosa. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 02/Set, 20:26 BRT (23:26 UTC)'
const QUAEST = 'Genial/Quaest del 02/Set (BR-07065/2026, campo del 30/Ago al 01/Set, n=2.004, margen de 2pp)'
const PISO = 'por debajo del piso de 0,5% de la doble lectura'
const SEM = 'esta ronda no publica precio nuevo para él'
const RT = 'la Real Time Big Data del 01/Set, con campo que se superpone a este'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 2 de septiembre de 2026: precio de Polymarket en la ${S}, libro presidencial en USD 141,85M, contra la ${QUAEST}, la única encuesta nacional divulgada este miércoles. Su divulgación ya constaba en el registro del TSE que el panel ingirió en la mañana del mismo día. La casa publicó DOS escenarios de ${G('primera vuelta', 'primeiro-turno')}, uno con Pablo Marçal y otro sin él, además de un escenario espontáneo. ⚠️ Y LA ${G('SEGUNDA VUELTA', 'segundo-turno')} CONTRA RONALDO CAIADO INVIERTE LA DE LA VÍSPERA: la Quaest da al líder adelante por 42% a 37%, y la Real Time Big Data del 01/Set, con campo que se superpone, daba a Caiado adelante por 45% a 43%.`,

  // ── Lula ────────────────────────────────────────────────────────────────────
  'candidates[0].header': `PRECIO: 55,50% (vol USD 9,59M acumulado), ${S}. Sin variación en el día, y su precio no sale de 55,50% por quinto día seguido. ENCUESTA: la ${QUAEST} lo da en 37% en los dos escenarios de primera vuelta y en 42% en una segunda vuelta contra el segundo colocado, que tiene 41%. Contra Ronaldo Caiado gana por 42% a 37%, lo opuesto de lo que midió la ronda de la víspera.`,
  'candidates[0].fortes[0]': `Sigue adelante en la primera vuelta, con 37% en los dos escenarios, y la distancia hacia el segundo es de 7 puntos en el escenario con Marçal y de 8 en el escenario sin él.`,
  'candidates[0].fortes[1]': `En el precio, es el quinto día seguido en 55,50%, y llegó hasta aquí sin moverse en ninguno de los cinco.`,
  'candidates[0].fortes[2]': `Gana los cinco escenarios de segunda vuelta probados por la Quaest: 42% a 41% contra el segundo colocado, 42% a 37% contra Ronaldo Caiado, 44% a 33% contra Romeu Zema, 43% a 36% contra Renan Santos y 40% a 34% contra Augusto Cury.`,
  'candidates[0].fortes[3]': `En el escenario de segunda vuelta contra Caiado la Quaest lo coloca adelante por 5 puntos, mientras la Real Time Big Data del 01/Set lo colocaba atrás por 2. Las dos casas midieron semanas que se superponen.`,
  'candidates[0].fortes[4]': `Su rechazo es de 53%, dos puntos por debajo del segundo colocado, y no es el mayor de la tabla.`,
  'candidates[0].fracos[0]': `La distancia en la segunda vuelta contra el segundo colocado cayó a 1 punto, 42% a 41%. En la propia Quaest esa distancia era de 5pp el 05/Ago y de 3pp el 14/Ago, es decir, encogió en tres rondas seguidas de la casa.`,
  'candidates[0].fracos[1]': `En la primera vuelta cedió 1 punto dentro de la propia casa, de 38% el 14/Ago a 37%, y en el escenario sin Marçal la distancia hacia el segundo se abrió de 7pp a 8pp por caída mayor del adversario, no por alza suya.`,
  'candidates[0].fracos[2]': `En el contrato de 2º lugar de la primera vuelta cayó 1,20pp, a 8,00%.`,
  'candidates[0].fracos[3]': `La aprobación del gobierno cayó 1 punto dentro de la propia Quaest, de 46% el 14/Ago a 45%, con la desaprobación estancada en 48% por tercera ronda seguida de la casa.`,
  'candidates[0].fracos[4]': `En el escenario espontáneo, sin nombres mostrados, tiene 28%, y 42% de los entrevistados no supieron decir por quién votarían.`,
  'candidates[0].analise': `El miércoles trajo una sola encuesta nacional, y mide la misma semana que la del martes, con un día de desplazamiento. En la primera vuelta su cuadro casi no cambia: 37% en los dos escenarios, adelante. Lo que cambia es la lectura de la segunda vuelta, y cambia en los dos sentidos. Contra el segundo colocado la distancia cayó a 1 punto, el menor valor de las tres rondas de la propia Quaest. Contra Ronaldo Caiado aparece adelante por 42% a 37%, cuando la ronda de la víspera, de otra casa, lo daba atrás por 45% a 43%. El panel no dice cuál de las dos está en lo cierto: registra que dos casas midieron la misma semana y llegaron a resultados de signo opuesto en el mismo par, con 7pp de diferencia en el margen. En el precio nada de eso apareció de su lado: 55,50% por quinto día. Quien se movió fue el otro lado, y por eso la distancia cayó de 16,55pp a 14,85pp.`,

  // ── Flávio Bolsonaro ────────────────────────────────────────────────────────
  'candidates[1].header': `PRECIO: 40,65% (vol USD 9,48M acumulado), ${S}. Alza de 1,70pp en el día, y la distancia hacia el líder cayó de 16,55pp a 14,85pp. ENCUESTA: la ${QUAEST} lo da en 30% en el escenario con Pablo Marçal y en 29% en el escenario sin él. En la segunda vuelta queda a 1 punto del líder, 41% contra 42%.`,
  'candidates[1].fortes[0]': `Subió 1,70pp en el contrato de ganador, hasta 40,65%, y fue el único movimiento de alza entre los cuatro nombres del presidencial con precio por encima del piso.`,
  'candidates[1].fortes[1]': `En la segunda vuelta se acercó: 41% contra 42%, distancia de 1 punto. En la propia Quaest esa distancia era de 5pp el 05/Ago y de 3pp el 14/Ago.`,
  'candidates[1].fortes[2]': `En el contrato de 2º lugar de la primera vuelta sigue dominante, con 85,50%.`,
  'candidates[1].fortes[3]': `La distancia hacia el líder en el precio cayó 1,70pp en un día en que el líder no se movió, es decir, la compresión vino entera de su lado.`,
  'candidates[1].fracos[0]': `En la primera vuelta cedió dentro de la propia casa: de 31% el 14/Ago a 29% en el escenario sin Marçal, y a 30% en el escenario con él. La distancia hacia el líder en el escenario sin Marçal se abrió de 7pp a 8pp.`,
  'candidates[1].fracos[1]': `Su rechazo es de 55%, el mayor entre los trece nombres probados por la Quaest, y subió 1 punto contra el 54% de la ronda de la casa del 14/Ago.`,
  'candidates[1].fracos[2]': `En el contrato de 2º lugar de la primera vuelta cedió 0,50pp, a 85,50%.`,
  'candidates[1].fracos[3]': `La encuesta muestra 60% diciendo que no lo ven como el mejor candidato de la derecha, según G1, el mismo día en que el tercer colocado triplicó.`,
  'candidates[1].analise': `Su día separa las dos mediciones con nitidez poco común. En la urna declarada cedió en la primera vuelta, de 31% a 29% o 30% dentro de la propia casa, y la distancia hacia el líder se abrió en el escenario sin Marçal. En la segunda vuelta, que es el escenario que decide la elección, hizo lo contrario y se acercó a 1 punto, cerrando una secuencia de tres rondas de la misma casa en que esa distancia solo encogió. En el precio el mercado anduvo en la dirección de la segunda vuelta: subió 1,70pp, hasta 40,65%, y como el líder quedó quieto la distancia cayó a 14,85pp. El contrato pregunta quién gana la elección, no quién lidera la primera vuelta, y este miércoles las dos cosas apuntaron hacia lados distintos.`,

  // ── Renan Santos ────────────────────────────────────────────────────────────
  'candidates[2].header': `PRECIO: 2,20% (vol USD 12,36M acumulado), ${S}. Caída de 0,35pp. En el contrato de 3º lugar de la primera vuelta cayó a 28,00%. ENCUESTA: la ${QUAEST} lo da en 3% en la primera vuelta, contra 4% en la ronda de la misma casa del 14/Ago. En una segunda vuelta pierde ante el líder por 43% a 36%.`,
  'candidates[2].fortes[0]': `Sus redes volvieron a estar en línea este miércoles, después de que la decisión que trababa la campaña digital fuera revisada el 01/Set, según G1.`,
  'candidates[2].fortes[1]': `Su rechazo es de 28%, el segundo menor entre los siete nombres de mayor proyección probados, detrás solo de Augusto Cury.`,
  'candidates[2].fortes[2]': `En la segunda vuelta contra el líder, el margen de 7 puntos que mide la Quaest es exactamente el mismo que midió la Real Time Big Data la víspera, y es el único nombre en que las dos casas coinciden en el par.`,
  'candidates[2].fortes[3]': `Presentó pedido de juicio político contra dos ministros del Supremo, según G1, y con eso entró en el asunto que domina las noticias de la semana.`,
  'candidates[2].fracos[0]': `En el precio cayó 0,35pp, a 2,20%, y perdió 2,00pp en el contrato de 3º lugar de la primera vuelta, donde está en 28,00% contra 52,40% del primero.`,
  'candidates[2].fracos[1]': `En la primera vuelta cedió dentro de la propia casa, de 4% el 14/Ago a 3%, en el mismo intervalo en que el tercer colocado pasó de 2% a 10%.`,
  'candidates[2].fracos[2]': `Su volumen acumulado en el contrato de ganador es el mayor entre los nombres de abajo, con USD 12,36M, y aun así el precio está en 2,20%.`,
  'candidates[2].fracos[3]': `Perdió el liderazgo del contrato de 3º lugar el 01/Set y este miércoles la distancia hacia el primero se duplicó.`,
  'candidates[2].analise': `La semana empezó con su campaña digital trabada y destrabada en dos días, y el miércoles trajo la consecuencia práctica, con las redes de vuelta en línea. En la urna declarada, sin embargo, cedió: 3% en la primera vuelta de la Quaest contra 4% en la ronda de la misma casa del 14/Ago, en el mismo intervalo en que Augusto Cury pasó de 2% a 10%. El precio acompañó en los dos contratos, con caída de 0,35pp en el de ganador y de 2,00pp en el de 3º lugar. El único lugar en que aparece estable es la segunda vuelta contra el líder, donde las dos casas que midieron esta semana llegan al mismo margen de 7 puntos.`,

  // ── Caiado / Haddad / Zema ──────────────────────────────────────────────────
  'candidates[3].header': `PRECIO: Caiado en 0,25%, Zema en 0,15% y Haddad en 0,05% en el contrato de GANADOR, los tres por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para ninguno de ellos en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, Caiado cayó 4,50pp y está en 8,50%, y Zema está en 0,80%. ENCUESTA: la ${QUAEST} da 1% a Ronaldo Caiado y 1% a Romeu Zema en la primera vuelta. ⚠️ Y LA SEGUNDA VUELTA CONTRA CAIADO INVIERTE LA DE LA VÍSPERA: aquí el líder gana por 42% a 37%.`,
  'candidates[3].subtitle': `Pelotón de atrás en la ${S}, y este miércoles lo que cambia es la lectura del propio pelotón. Ronaldo Caiado pasó de 4% a 1% dentro de la propia Quaest, entre el 14/Ago y ahora, y el escenario de segunda vuelta en que aparecía adelante del líder la víspera, por 45% a 43%, aparece invertido aquí, con el líder adelante por 42% a 37%. Son dos casas midiendo semanas que se superponen, con 7pp de diferencia en el margen del mismo par.`,
  'candidates[3].caiado.label': `CAIADO (PSD), 0,25% (vol USD 7,05M) en el contrato de GANADOR, ${PISO}, y ${SEM} en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cayó 4,50pp y está en 8,50% (vol USD 110 mil). EN LA URNA DECLARADA DE ESTE MIÉRCOLES PIERDE LA SEGUNDA VUELTA ANTE EL LÍDER, POR 42% A 37%, lo opuesto de lo que midió la ronda de la víspera.`,
  'candidates[3].caiado.fortes': `Su rechazo es de 40%, trece puntos por debajo del líder y quince por debajo del segundo colocado. Reaccionó públicamente al 1% de la encuesta diciendo que el electorado todavía está conociendo a los candidatos, según O Globo, y sigue con el tercer mayor precio en el contrato de 3º lugar de la primera vuelta.`,
  'candidates[3].caiado.fracos': `En la primera vuelta cayó de 4% a 1% dentro de la propia Quaest, entre el 14/Ago y ahora. En el contrato de 3º lugar de la primera vuelta perdió 4,50pp en un día, a 8,50%. Y el escenario de segunda vuelta que lo colocaba adelante del líder la víspera lo coloca 5 puntos atrás aquí, lo que muestra que aquel resultado no se reprodujo en la casa siguiente con campo superpuesto.`,
  'candidates[3].haddad.label': `HADDAD (PT), 0,05% (vol USD 7,42M) en el contrato de GANADOR, ${PISO}, y ${SEM}. No es candidato a la Presidencia: disputa el gobierno de São Paulo.`,
  'candidates[3].haddad.fortes': `No es probado como candidato presidencial en las nacionales de la ventana, así que no hay lectura de urna para cruzar con el precio.`,
  'candidates[3].haddad.fracos': `El contrato sigue abierto con su nombre por herencia del diseño del mercado, no por candidatura declarada, y el panel mantiene la línea solo para que el precio residual no sea leído como señal.`,
  'candidates[3].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,47M) en el contrato de GANADOR, ${PISO}, y ${SEM} en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, está en 0,80% (vol USD 49 mil).`,
  'candidates[3].zema.fortes': `Su rechazo es de 38%, el tercero menor entre los nombres de mayor proyección probados por la Quaest.`,
  'candidates[3].zema.fracos': `Tiene 1% en la primera vuelta, contra 2% en la ronda de la misma casa del 14/Ago. Y la segunda vuelta contra el líder es el escenario en que las dos casas de esta semana más discrepan: la Quaest da 44% a 33%, un margen de 11 puntos, y la Real Time Big Data del 01/Set dio 43% a 40%, un margen de 3. Son 8pp de diferencia en el mismo par.`,
  'candidates[3].fortes': `El rechazo de los tres nombres de fuera del tope es menor que el de los dos primeros: Caiado 40%, Zema 38% y, entre los probados, Augusto Cury con 25% contra 55% del segundo colocado y 53% del líder.`,
  'candidates[3].fracos': `Ninguno de los tres llega a 2% en la primera vuelta de la Quaest, y los dos que la casa probó en la segunda vuelta pierden ante el líder, por 42% a 37% y por 44% a 33%.`,
  'candidates[3].analise': `La ronda de la víspera había colocado a Ronaldo Caiado adelante del líder en una segunda vuelta, algo que no existía en la base para ningún nombre fuera del segundo colocado. Veinticuatro horas después, otra casa midió el mismo par con campo que se superpone y llegó al signo contrario, con el líder adelante por 42% a 37%. El panel registra las dos lecturas, no elige entre ellas, y llama la atención sobre el tamaño de la diferencia: 7pp en el margen del par con Caiado y 8pp en el margen del par con Zema, contra 0pp en el par con Renan Santos, en que las dos casas coinciden. En el precio, los tres siguen por debajo del piso de 0,5% en el contrato de ganador, y el único movimiento publicable es el de Caiado en el contrato de 3º lugar, que cayó 4,50pp a 8,50%.`,

  // ── Cuadro comparativo ──────────────────────────────────────────────────────
  'quadroComparativo[0].p': `La ${QUAEST} lo da en 37% en los dos escenarios de primera vuelta. En la segunda vuelta gana los cinco pares probados: 42% a 41% contra el segundo colocado, 42% a 37% contra Ronaldo Caiado, 44% a 33% contra Romeu Zema, 43% a 36% contra Renan Santos y 40% a 34% contra Augusto Cury. Rechazo de 53%. En el espontáneo tiene 28%, con 42% de indecisos.`,
  'quadroComparativo[0].m': `55,50% (vol USD 9,59M), ${S}. Sin variación en el día, y su precio no sale de 55,50% por quinto día seguido. La distancia hacia el segundo cayó a 14,85pp, contra 16,55pp de ayer. En el contrato de 2º lugar de la primera vuelta cayó 1,20pp, a 8,00%.`,
  'quadroComparativo[0].t': `quieto en el precio por quinto día, y la distancia hacia el segundo encoge por movimiento del otro lado`,
  'quadroComparativo[0].s': `Conversó con Fachin, Dino y Gilmar sobre la crisis en el Supremo, se distanció de Moraes y definió el discurso de que nadie está por encima de la ley, según Folha de S.Paulo y O Globo. El gobierno anunció que dejó en cero la fila del INSS, según Folha de S.Paulo.`,
  'quadroComparativo[1].p': `La misma Quaest lo da en 30% en el escenario con Pablo Marçal y en 29% en el escenario sin él, contra 31% en la ronda de la casa del 14/Ago. En la segunda vuelta queda a 1 punto del líder, 41% contra 42%, y esa distancia era de 5pp el 05/Ago y de 3pp el 14/Ago en la misma casa. Rechazo de 55%, el mayor de los trece nombres probados.`,
  'quadroComparativo[1].m': `40,65% (vol USD 9,48M), ${S}. Alza de 1,70pp, el único movimiento de alza entre los nombres del presidencial por encima del piso. En el contrato de 2º lugar de la primera vuelta cedió 0,50pp, a 85,50%.`,
  'quadroComparativo[1].t': `cede en la primera vuelta, se acerca a 1 punto en la segunda, y el precio anda en la dirección de la segunda vuelta`,
  'quadroComparativo[1].s': `Llamó cortina de humo al encuentro de André Mendonça con Daniel Vorcaro y defendió al ministro, según Poder360, Folha de S.Paulo y O Globo. Su registro de candidatura fue llevado a juicio en el TSE junto con otros tres nombres, según Rádio Itatiaia.`,
  'quadroComparativo[2].p': `La Quaest lo mide en 10% en los dos escenarios de primera vuelta, contra 2% en la ronda de la misma casa del 14/Ago y 1% en la del 05/Ago. Es la primera encuesta de la base en probar una segunda vuelta con él, y en ese escenario pierde ante el líder por 40% a 34%. Rechazo de 25%, el menor entre los siete nombres de mayor proyección. En el espontáneo tiene 4%.`,
  'quadroComparativo[2].m': `1,60% (vol USD 3,59M), ${S}. CAÍDA de 0,75pp en el contrato de ganador, y ALZA de 5,75pp en el contrato de 3º lugar de la primera vuelta, donde está en 52,40% (vol USD 103 mil).`,
  'quadroComparativo[2].t': `triplica en la urna declarada y el precio se mueve en las dos direcciones, hacia abajo en el contrato de ganador y hacia arriba en el de 3º lugar`,
  'quadroComparativo[2].s': `Publicó un video con críticas al líder, al segundo colocado y a Pablo Marçal después del salto en la encuesta, según O Globo, y usó el horario electoral gratuito para criticar la polarización, según UOL. Las campañas de los competidores de fuera del tope subieron el tono contra él, según O Globo.`,
  'quadroComparativo[3].p': `La Quaest lo da en 3% en la primera vuelta, contra 4% en la ronda de la misma casa del 14/Ago. En una segunda vuelta pierde ante el líder por 43% a 36%, margen de 7 puntos que es exactamente el mismo medido por la Real Time Big Data la víspera. Rechazo de 28%.`,
  'quadroComparativo[3].m': `2,20% (vol USD 12,36M), ${S}. Caída de 0,35pp. En el contrato de 3º lugar de la primera vuelta cayó 2,00pp, a 28,00%.`,
  'quadroComparativo[3].t': `cede en los dos contratos y en la urna, y es el único par en que las dos casas de la semana coinciden`,
  'quadroComparativo[3].s': `Sus redes volvieron a estar en línea después de la liberación de la campaña digital el 01/Set, según G1. Presentó pedido de juicio político contra Alexandre de Moraes y Dias Toffoli, según G1.`,
  'quadroComparativo[4].p': `La Quaest lo coloca en 1% en la primera vuelta, contra 4% en la ronda de la misma casa del 14/Ago. ⚠️ EN UNA SEGUNDA VUELTA PIERDE ANTE EL LÍDER, POR 42% A 37%, y ${RT}, lo daba adelante por 45% a 43%. Son 7pp de diferencia en el margen del mismo par entre dos casas que midieron la misma semana. Rechazo de 40%.`,
  'quadroComparativo[4].m': `0,25% (vol USD 7,05M) en el contrato de GANADOR, ${PISO}, y ${SEM} en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cayó 4,50pp y está en 8,50% (vol USD 110 mil).`,
  'quadroComparativo[4].t': `el escenario que lo colocaba adelante la víspera no se reprodujo en la casa siguiente`,
  'quadroComparativo[4].s': `Reaccionó al 1% de la encuesta diciendo que el electorado todavía está conociendo a los candidatos, según O Globo. El tribunal electoral regional de Goiás determinó que el candidato al gobierno del estado lo retire de los programas electorales, según CBN Goiânia.`,
  'quadroComparativo[5].p': `La Quaest lo trae en 1% en el escenario con él en la lista, y es su presencia la que separa los dos escenarios publicados por la casa. ⚠️ LA DIRECCIÓN DEL EFECTO ES LA INVERSA DE LA MEDIDA LA VÍSPERA: aquí el segundo colocado tiene 30% con Marçal y 29% sin él, y en la Real Time Big Data del 01/Set tenía 29% con y 30% sin. Rechazo de 44%, el tercero mayor de la tabla.`,
  'quadroComparativo[5].m': `0,25% (vol USD 3,29M) en el contrato de GANADOR, ${PISO}, y ${SEM}.`,
  'quadroComparativo[5].t': `su presencia cambia el número del segundo colocado, y las dos casas discrepan del signo de ese cambio`,
  'quadroComparativo[5].s': `No aparece en las noticias de este miércoles con un hecho propio.`,
  'quadroComparativo[6].m': `6,35% (vol USD 87 mil), ${S}. Caída de 4,50pp contra el 10,85% publicado el 01/Set. ⚠️ ES EL MENOR LIBRO DEL PANEL: el volumen acumulado pasó de USD 86 mil a USD 87 mil, es decir, cerca de USD 1,3 mil de negocio nuevo acompañan la caída de cuatro puntos y medio. Es la misma lectura de ayer en la dirección opuesta.`,
  'quadroComparativo[6].t': `deshace en un día dos tercios del alza de la víspera, con dinero nuevo del orden de mil dólares`,
  'quadroComparativo[6].s': `El despacho de André Mendonça confirmó un encuentro con Daniel Vorcaro el 14 de marzo de 2025, casi un año antes de asumir el caso, y una declaración del empresario ante el despacho el 27 de agosto de 2026 sin la Policía Federal, según Poder360 y O Globo. El tribunal hizo la primera sesión después del informe sin poner el caso en el orden del día, según O Globo y Folha de S.Paulo. El presidente del tribunal, Edson Fachin, dijo que los ministros deben tener límites y que anunciará las medidas que correspondan, y comenzó conversaciones con los demás. Renan Santos presentó pedido de juicio político contra Moraes y Toffoli, según G1. El informe de Mendonça sobre Moraes está previsto para el 7 o el 8 de septiembre, según Poder360.`,

  cruzamento: `El 2 de septiembre es la ronda en que dos casas midieron la misma semana y discreparon sobre quién gana una segunda vuelta. En la urna declarada, la ${QUAEST} trae cuatro cosas. Augusto Cury saltó de 2% a 10% dentro de la propia casa desde el 14/Ago, y la Quaest es la primera encuesta de la base en probar una segunda vuelta con él, escenario en que pierde ante el líder por 40% a 34%. La segunda vuelta entre los dos primeros encogió a 1 punto, 42% a 41%, cerrando tres rondas seguidas de la casa en que esa distancia solo disminuyó, de 5pp el 05/Ago a 3pp el 14/Ago. En la primera vuelta, al contrario, la distancia se abrió de 7pp a 8pp en el escenario sin Marçal, por caída del segundo colocado. Y el escenario de segunda vuelta contra Ronaldo Caiado invirtió el de la víspera: aquí el líder gana por 42% a 37%, mientras la Real Time Big Data del 01/Set lo daba atrás por 45% a 43%. Son 7pp de diferencia en el margen del mismo par, y en el par contra Romeu Zema la diferencia entre las dos casas es de 8pp. En el par contra Renan Santos las dos coinciden exactamente, con 7 puntos. El panel no elige entre las dos lecturas: registra que la discrepancia se concentra en los nombres de fuera del tope y desaparece donde las dos casas miden lo mismo. En el precio, el líder quedó en 55,50% por quinto día seguido y el segundo colocado subió 1,70pp, hasta 40,65%, de modo que la distancia cayó de 16,55pp a 14,85pp, y la compresión vino de un solo lado. Augusto Cury es el caso más claro de contratos distintos respondiendo preguntas distintas: en el contrato de ganador cayó 0,75pp, a 1,60%, y en el de 3º lugar de la primera vuelta subió 5,75pp, a 52,40%. El contrato de salida de ministro del Supremo por juicio político antes de 2027 cayó de 10,85% a 6,35%, y vale repetir lo que la ronda de ayer ya mostraba en la dirección contraria: el libro es de USD 87 mil acumulados, el menor del panel, y cerca de USD 1,3 mil de negocio nuevo acompañan la variación. Un precio que anda mucho con dinero de poco no describe un cambio de expectativa del mismo tamaño.`,
})
