/** Mapa ES de 02/Set/2026: polls-data. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 02/Set, 20:26 BRT (23:26 UTC)'
const QUAEST = 'Genial/Quaest del 02/Set (BR-07065/2026, campo del 30/Ago al 01/Set, n=2.004)'
const PISO = 'por debajo del piso de 0,5% en que la doble lectura certifica movimiento'
const SEM = 'esta ronda no publica precio nuevo para él'

construir('polls-data', 'es', {
  'polls[0].note': `Encuesta nacional Genial/Quaest divulgada el 02/Set (G1, O Globo, Folha de S.Paulo, Estadão, Valor Econômico, CartaCapital, Poder360, Gazeta do Povo, CBN y JOTA). ⚠️ LA CASA PUBLICÓ DOS ESCENARIOS DE ${G('PRIMERA VUELTA', 'primeiro-turno')} Y LA DIRECCIÓN DEL EFECTO MARÇAL ES LA INVERSA DE LA MEDIDA LA VÍSPERA. Con Pablo Marçal en la lista, Lula 37%, Flávio Bolsonaro 30% y Augusto Cury 10%. Sin Marçal, Lula 37%, Flávio 29% y Cury 10%. En la Real Time Big Data del 01/Set era al revés, con el segundo colocado en 29% en el escenario con Marçal y en 30% en el escenario sin él. Los dos escenarios de la Quaest cierran en 100 exactos con blancos, nulos e indecisos. En el espontáneo, sin nombres mostrados, Lula 28%, Flávio 20% y Cury 4%, con 42% de indecisos. ⭐ EL SALTO DEL DÍA ES EL DE AUGUSTO CURY DENTRO DE LA PROPIA CASA: 1% el 05/Ago, 2% el 14/Ago y 10% ahora. En el mismo intervalo Ronaldo Caiado pasó de 4% a 1%, Renan Santos de 4% a 3% y Romeu Zema de 2% a 1%. ⭐ Y LA ${G('SEGUNDA VUELTA', 'segundo-turno')} CONTRA RONALDO CAIADO CONTRADICE LA RONDA DE LA VÍSPERA. Aquí Lula gana por 42% a 37%, y la Real Time Big Data del 01/Set, con campo que se superpone a este, daba a Caiado adelante por 45% a 43%. Son 7pp de diferencia en el margen entre dos casas que midieron la misma semana. Contra Romeu Zema la diferencia entre las dos es todavía mayor, de 8pp: la Quaest da Lula 44% a 33% y la Real Time dio 43% a 40%. Contra Renan Santos las dos casas llegan exactamente al mismo margen de 7pp. ⭐ ES LA PRIMERA ENCUESTA DE LA BASE EN PROBAR UNA SEGUNDA VUELTA CON AUGUSTO CURY: Lula 40% x Cury 34%. COMPARACIÓN DENTRO DE LA CASA, que es la única válida. En la primera vuelta sin Marçal la distancia entre los dos primeros pasó de 7pp el 14/Ago (38% x 31%) a 8pp ahora (37% x 29%), y en las rondas anteriores de la casa venía encogiendo, de 9pp el 05/Ago a 7pp el 14/Ago. En la segunda vuelta contra Flávio la distancia siguió encogiendo: 5pp el 05/Ago (44% x 39%), 3pp el 14/Ago (43% x 40%) y 1pp ahora (42% x 41%). RECHAZO, trece nombres probados: Flávio Bolsonaro 55%, Lula 53%, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28%, Augusto Cury 25%, Rui Costa Pimenta 23%, Samara Martins 11%, Edmilson Costa 11%, Wilson Grassi 10%, Hertz Dias 10% y Clariana Barão 7%. APROBACIÓN DEL GOBIERNO: 45% aprueban y 48% desaprueban, con 7% sin respuesta. En la regla de gestión, 35% de excelente o bueno, 25% de regular y 37% de malo o pésimo, con 3% sin respuesta. Campo del 30/Ago al 01/Set, n=2.004, margen de 2pp, 95% de confianza, contratante Editora Globo y Globo Comunicação e Participações, registro TSE BR-07065/2026, costo declarado de R$ 314.628. 📅 LA DIVULGACIÓN DE ESTE MIÉRCOLES YA ESTABA EN EL REGISTRO DEL TSE ingerido por el panel en la propia mañana del 02/Set, con la fecha prevista y el número de registro coincidiendo con lo publicado.`,
  'polls[0].source': `Genial/Quaest, divulgada el 02/Set/2026 (campo del 30/Ago al 01/Set, n=2.004, margen de 2pp, 95% de confianza, contratante Editora Globo, registro TSE BR-07065/2026). Tabla completa de los tres escenarios de primera vuelta y de los cinco de segunda vuelta verificada en Gazeta do Povo; rechazo de los trece nombres y evaluación del gobierno verificados en Poder360; números de la primera y de la segunda vuelta verificados también en G1, Folha de S.Paulo, Estadão, Valor Econômico y CartaCapital.`,

  'approvalData.note': `🏷️ LOS NÚMEROS ESTRUCTURADOS DE ESTE BLOQUE SON DE LA GENIAL/QUAEST DEL 02/Set, y son estos: 45% de aprobación contra 48% de desaprobación, con 7% de no sabe, y 35% de excelente o bueno, 25% de regular y 37% de malo o pésimo, con 3% sin respuesta. El panel mantiene UNA casa por bloque a propósito, para no sumar reglas de institutos distintos. ⭐ DENTRO DE LA PROPIA QUAEST EL CUADRO ES DE INMOVILIDAD. El 05/Ago eran 48% de aprobación contra 47% de desaprobación, el 14/Ago 46% contra 48% y ahora 45% contra 48%. La desaprobación está en el mismo número por tercera ronda seguida de la casa, y la aprobación cedió 1pp en cada una de las dos últimas. En la regla de gestión, el excelente o bueno pasó de 36% el 14/Ago a 35%, con regular y malo o pésimo estancados en 25% y 37%. 📌 RECHAZO, también de la ronda del 02/Set y de la misma casa: Flávio Bolsonaro 55% y Lula 53%, contra 54% y 52% en la ronda del 14/Ago. Los dos subieron 1pp y la distancia entre ellos no cambió. En la misma ronda, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28% y Augusto Cury 25%. ℹ️ Las lecturas de otras casas siguen declaradas aquí y NO mezcladas arriba. Las dos del 31/Ago, las dos con campo cerrado el 30/Ago: la BTG/Nexus trae 46% de aprobación contra 51% de desaprobación (Poder360) y la AtlasIntel/Bloomberg trae desaprobación de 52,9% (InfoMoney). Antes de ellas, PoderData/Aya del 27/Ago con 42% contra 50%, Indexa/Broadcast del 26/Ago con 46% contra 50% y Gerp del 26/Ago con 43% contra 51%. ⚠️ Cada casa usa regla propia de aprobación, así que la comparación que vale es de cada instituto consigo mismo, nunca entre institutos.`,
  'approvalData.source': `Aprobación, desaprobación y evaluación de la gestión: Genial/Quaest 02/Set/2026 (campo del 30/Ago al 01/Set, n=2.004, presencial, margen 2,0pp, 95% de confianza, registro TSE BR-07065/2026), divulgada por Poder360, G1, O Globo, CartaCapital y Valor Econômico. Rechazo: misma ronda, vía Poder360 y Valor Econômico. Serie de la propia casa: rondas del 05/Ago y del 14/Ago, ya registradas en el panel.`,

  'polymarketComparison.note': `Precios de Polymarket en la ${S}, con el libro presidencial en USD 141,85M. UNA ENCUESTA NACIONAL FUE DIVULGADA ESTE MIÉRCOLES, la ${QUAEST}, margen de 2pp, y su divulgación ya constaba en el registro del TSE ingerido por el panel en la mañana del mismo día. ⚠️ LA CASA PUBLICÓ DOS ESCENARIOS DE PRIMERA VUELTA y la dirección del efecto Marçal es la inversa de la medida la víspera: con Marçal, 37% a 30% y Augusto Cury en 10%; sin Marçal, 37% a 29% y Cury también en 10%. Los números estructurados del panel usan el escenario SIN Marçal, que es el mismo criterio de la ronda anterior. ⭐ EL SALTO DEL DÍA ES EL DE AUGUSTO CURY DENTRO DE LA PROPIA CASA: 1% el 05/Ago, 2% el 14/Ago y 10% ahora, y la Quaest es la primera encuesta de la base en probar una segunda vuelta con él, escenario en que pierde por 40% a 34%. ⚠️ Y LA SEGUNDA VUELTA CONTRA RONALDO CAIADO INVIERTE LA DE LA VÍSPERA: aquí el líder gana por 42% a 37%, y la Real Time Big Data del 01/Set, con campo que se superpone, daba a Caiado adelante por 45% a 43%. Son 7pp de diferencia en el margen del mismo par entre dos casas que midieron la misma semana; en el par contra Romeu Zema la diferencia es de 8pp; y en el par contra Renan Santos las dos coinciden exactamente, con 7 puntos. En la segunda vuelta entre los dos primeros la distancia encogió a 1 punto, 42% a 41%, después de 5pp el 05/Ago y 3pp el 14/Ago en la misma casa. En el precio, el líder no sale de 55,50% por quinto día seguido y el segundo colocado subió 1,70pp, hasta 40,65%, de modo que la distancia cayó de 16,55pp a 14,85pp y la compresión vino entera de un solo lado. Augusto Cury cayó 0,75pp en el contrato de ganador, a 1,60%, y subió 5,75pp en el de 3º lugar de la primera vuelta, a 52,40%: son preguntas distintas. Renan Santos cayó 0,35pp, a 2,20%. Esta ronda no publica precio nuevo para el contrato de mayoría en el Senado.`,

  'polymarketComparison.candidates[0].pesquisaRange': `37%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `La ${QUAEST} lo da en 37% en los dos escenarios de primera vuelta, contra 38% en la ronda de la misma casa del 14/Ago. Gana los cinco escenarios de segunda vuelta: 42% a 41% contra el segundo colocado, 42% a 37% contra Ronaldo Caiado, 44% a 33% contra Romeu Zema, 43% a 36% contra Renan Santos y 40% a 34% contra Augusto Cury. Rechazo de 53%. En el espontáneo tiene 28%, con 42% de indecisos.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55,50% (vol USD 9,59M), ${S}. Sin variación en el día, y su precio no sale de 55,50% por quinto día seguido. La distancia hacia el segundo cayó a 14,85pp. En el contrato de 2º lugar de la primera vuelta cedió 1,20pp, a 8,00%.`,

  'polymarketComparison.candidates[1].polymarket': `40,65%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `La misma Quaest lo da en 30% en el escenario con Pablo Marçal y en 29% en el escenario sin él, contra 31% en la ronda de la casa del 14/Ago. En la segunda vuelta queda a 1 punto del líder, 41% contra 42%, y esa distancia era de 5pp el 05/Ago y de 3pp el 14/Ago en la misma casa. Rechazo de 55%, el mayor entre los trece nombres probados.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40,65% (vol USD 9,48M), ${S}. Alza de 1,70pp, el único movimiento de alza entre los nombres del presidencial por encima del piso. En el contrato de 2º lugar de la primera vuelta cedió 0,50pp, a 85,50%.`,

  'polymarketComparison.candidates[2].polymarket': `1,60%`,
  'polymarketComparison.candidates[2].pesquisaRange': `10%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `La Quaest lo mide en 10% en los dos escenarios de primera vuelta, contra 2% en la ronda de la misma casa del 14/Ago y 1% en la del 05/Ago. Es la primera encuesta de la base en probar una segunda vuelta con él, y en ese escenario pierde ante el líder por 40% a 34%. Rechazo de 25%, el menor entre los siete nombres de mayor proyección. En el espontáneo tiene 4%.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,60% (vol USD 3,59M), ${S}. CAÍDA de 0,75pp en el contrato de ganador y ALZA de 5,75pp en el contrato de 3º lugar de la primera vuelta, donde está en 52,40% (vol USD 103 mil). Son preguntas distintas: una es ganar la elección, la otra es terminar tercero.`,

  'polymarketComparison.candidates[3].polymarket': `2,20%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La Quaest lo da en 3% en la primera vuelta, contra 4% el 14/Ago en la misma casa. En una segunda vuelta pierde ante el líder por 43% a 36%, margen de 7 puntos que es exactamente el mismo medido por la Real Time Big Data la víspera, y es el único par en que las dos casas de la semana coinciden. Rechazo de 28%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `2,20% (vol USD 12,36M), ${S}. Caída de 0,35pp. En el contrato de 3º lugar de la primera vuelta cayó 2,00pp, a 28,00%.`,

  'polymarketComparison.candidates[4].pesquisaRange': `1%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `La Quaest lo coloca en 1% en la primera vuelta, contra 4% en la ronda de la misma casa del 14/Ago. ⚠️ EN UNA SEGUNDA VUELTA PIERDE ANTE EL LÍDER, POR 42% A 37%, y la Real Time Big Data del 01/Set, con campo que se superpone, lo daba adelante por 45% a 43%. Son 7pp de diferencia en el margen del mismo par entre dos casas que midieron la misma semana. Rechazo de 40%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,25% (vol USD 7,05M) en el contrato de GANADOR, ${PISO}, y ${SEM} en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cayó 4,50pp y está en 8,50% (vol USD 110 mil).`,

  'polymarketComparison.candidates[5].pesquisaRange': `1%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `La Quaest lo trae en 1% en el escenario con él en la lista, y es su presencia la que separa los dos escenarios publicados por la casa. ⚠️ LA DIRECCIÓN DEL EFECTO ES LA INVERSA DE LA MEDIDA LA VÍSPERA: aquí el segundo colocado tiene 30% con Marçal y 29% sin él, y en la Real Time Big Data del 01/Set tenía 29% con y 30% sin. Rechazo de 44%, el tercero mayor de la tabla.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,25% (vol USD 3,29M) en el contrato de GANADOR, ${PISO}, y ${SEM}.`,

  'polymarketComparison.candidates[6].pesquisaRange': `1%`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La Quaest lo mide en 1% en la primera vuelta, contra 2% en la ronda de la misma casa del 14/Ago. En una segunda vuelta pierde ante el líder por 44% a 33%, margen de 11 puntos, y la Real Time Big Data del 01/Set midió el mismo par en 43% a 40%, margen de 3. Son 8pp de diferencia, la mayor entre los pares que las dos casas probaron. Rechazo de 38%.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,15% (vol USD 6,47M) en el contrato de GANADOR, ${PISO}, y ${SEM} en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, está en 0,80% (vol USD 49 mil).`,
})
