/** Mapa EN de 02/Set/2026: polls-data. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of Sep 2, 8:26 PM BRT (11:26 PM UTC)'
const QUAEST = 'Genial/Quaest of Sep 2 (BR-07065/2026, fieldwork Aug 30 to Sep 1, n=2,004)'
const PISO = 'below the 0.5% floor at which the double reading certifies movement'
const SEM = 'this round publishes no new price for him'

construir('polls-data', 'en', {
  'polls[0].note': `Genial/Quaest national poll released on Sep 2 (G1, O Globo, Folha de S.Paulo, Estadão, Valor Econômico, CartaCapital, Poder360, Gazeta do Povo, CBN and JOTA). ⚠️ THE HOUSE PUBLISHED TWO ${G('FIRST ROUND', 'primeiro-turno')} SCENARIOS AND THE DIRECTION OF THE MARÇAL EFFECT IS THE REVERSE OF THE ONE MEASURED THE DAY BEFORE. With Pablo Marçal on the list, Lula 37%, Flávio Bolsonaro 30% and Augusto Cury 10%. Without Marçal, Lula 37%, Flávio 29% and Cury 10%. In Real Time Big Data of Sep 1 it was the other way round, with the runner-up at 29% in the scenario with Marçal and at 30% in the scenario without. Both Quaest scenarios close at exactly 100 once blanks, spoiled ballots and undecided voters are counted. In the unprompted scenario, with no names shown, Lula 28%, Flávio 20% and Cury 4%, with 42% undecided. ⭐ THE JUMP OF THE DAY IS AUGUSTO CURY'S WITHIN THE HOUSE ITSELF: 1% on Aug 5, 2% on Aug 14 and 10% now. Over the same span Ronaldo Caiado went from 4% to 1%, Renan Santos from 4% to 3% and Romeu Zema from 2% to 1%. ⭐ AND THE ${G('RUNOFF', 'segundo-turno')} AGAINST RONALDO CAIADO CONTRADICTS THE ROUND FROM THE DAY BEFORE. Here Lula wins 42% to 37%, and Real Time Big Data of Sep 1, whose fieldwork overlaps this one, put Caiado ahead 45% to 43%. That is 7pp of difference in the margin between two houses that measured the same week. Against Romeu Zema the difference between the two is larger still, 8pp: Quaest gives Lula 44% to 33% and Real Time gave 43% to 40%. Against Renan Santos the two houses land on exactly the same 7pp margin. ⭐ IT IS THE FIRST POLL IN THE BASE TO TEST A RUNOFF WITH AUGUSTO CURY: Lula 40% x Cury 34%. COMPARISON WITHIN THE HOUSE, which is the only valid one. In the first round without Marçal the distance between the top two went from 7pp on Aug 14 (38% x 31%) to 8pp now (37% x 29%), and in the house's earlier rounds it had been shrinking, from 9pp on Aug 5 to 7pp on Aug 14. In the runoff against Flávio the distance kept shrinking: 5pp on Aug 5 (44% x 39%), 3pp on Aug 14 (43% x 40%) and 1pp now (42% x 41%). REJECTION, thirteen names tested: Flávio Bolsonaro 55%, Lula 53%, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28%, Augusto Cury 25%, Rui Costa Pimenta 23%, Samara Martins 11%, Edmilson Costa 11%, Wilson Grassi 10%, Hertz Dias 10% and Clariana Barão 7%. GOVERNMENT APPROVAL: 45% approve and 48% disapprove, with 7% giving no answer. On the management scale, 35% rate it excellent or good, 25% average and 37% poor or terrible, with 3% giving no answer. Fieldwork Aug 30 to Sep 1, n=2,004, margin of 2pp, 95% confidence, commissioned by Editora Globo and Globo Comunicação e Participações, TSE registration BR-07065/2026, declared cost of R$ 314,628. 📅 THIS WEDNESDAY'S RELEASE WAS ALREADY IN THE TSE REGISTRY ingested by the panel on the morning of Sep 2 itself, with the scheduled date and the registration number matching what was published.`,
  'polls[0].source': `Genial/Quaest, released on Sep 2, 2026 (fieldwork Aug 30 to Sep 1, n=2,004, margin of 2pp, 95% confidence, commissioned by Editora Globo, TSE registration BR-07065/2026). Full table of the three first-round scenarios and the five runoff scenarios checked in Gazeta do Povo; rejection of the thirteen names and government evaluation checked in Poder360; first-round and runoff figures also checked in G1, Folha de S.Paulo, Estadão, Valor Econômico and CartaCapital.`,

  'approvalData.note': `🏷️ THE STRUCTURED FIGURES IN THIS BLOCK COME FROM GENIAL/QUAEST OF SEP 2, and they are these: 45% approval against 48% disapproval, with 7% saying they do not know, and 35% excellent or good, 25% average and 37% poor or terrible, with 3% giving no answer. The panel deliberately keeps ONE house per block, so as not to add up scales from different pollsters. ⭐ WITHIN QUAEST ITSELF THE PICTURE IS ONE OF IMMOBILITY. On Aug 5 it was 48% approval against 47% disapproval, on Aug 14 it was 46% against 48% and now it is 45% against 48%. Disapproval sits at the same figure for the third round running in that house, and approval gave up 1pp in each of the last two. On the management scale, excellent or good went from 36% on Aug 14 to 35%, with average and poor or terrible stuck at 25% and 37%. 📌 REJECTION, also from the Sep 2 round and the same house: Flávio Bolsonaro 55% and Lula 53%, against 54% and 52% in the Aug 14 round. Both rose 1pp and the distance between them did not change. In the same round, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28% and Augusto Cury 25%. ℹ️ Readings from other houses remain declared here and NOT mixed in above. The two from Aug 31, both with fieldwork closing on Aug 30: BTG/Nexus gives 46% approval against 51% disapproval (Poder360) and AtlasIntel/Bloomberg gives 52.9% disapproval (InfoMoney). Before them, PoderData/Aya of Aug 27 with 42% against 50%, Indexa/Broadcast of Aug 26 with 46% against 50% and Gerp of Aug 26 with 43% against 51%. ⚠️ Each house uses its own approval scale, so the comparison that counts is each pollster against itself, never one pollster against another.`,
  'approvalData.source': `Approval, disapproval and management evaluation: Genial/Quaest Sep 2, 2026 (fieldwork Aug 30 to Sep 1, n=2,004, in person, margin 2.0pp, 95% confidence, TSE registration BR-07065/2026), released by Poder360, G1, O Globo, CartaCapital and Valor Econômico. Rejection: same round, via Poder360 and Valor Econômico. Series from the house itself: rounds of Aug 5 and Aug 14, already recorded on the panel.`,

  'polymarketComparison.note': `Polymarket prices in the ${S}, with the presidential book at USD 141.85M. ONE NATIONAL POLL WAS RELEASED THIS WEDNESDAY, ${QUAEST}, margin of 2pp, and its release was already in the TSE registry ingested by the panel on the morning of the same day. ⚠️ THE HOUSE PUBLISHED TWO FIRST-ROUND SCENARIOS and the direction of the Marçal effect is the reverse of the one measured the day before: with Marçal, 37% to 30% and Augusto Cury at 10%; without Marçal, 37% to 29% and Cury also at 10%. The panel's structured figures use the scenario WITHOUT Marçal, which is the same criterion as the previous round. ⭐ THE JUMP OF THE DAY IS AUGUSTO CURY'S WITHIN THE HOUSE ITSELF: 1% on Aug 5, 2% on Aug 14 and 10% now, and Quaest is the first poll in the base to test a runoff with him, a scenario he loses 40% to 34%. ⚠️ AND THE RUNOFF AGAINST RONALDO CAIADO REVERSES THE ONE FROM THE DAY BEFORE: here the leader wins 42% to 37%, and Real Time Big Data of Sep 1, whose fieldwork overlaps, put Caiado ahead 45% to 43%. That is 7pp of difference in the margin of the same pair between two houses that measured the same week; against Romeu Zema the difference is 8pp; and against Renan Santos the two land on exactly the same 7 points. In the runoff between the top two the distance shrank to 1 point, 42% to 41%, after 5pp on Aug 5 and 3pp on Aug 14 in the same house. On price, the leader does not move off 55.50% for the fifth day running and the runner-up rose 1.70pp, to 40.65%, so the distance fell from 16.55pp to 14.85pp and the compression came entirely from one side. Augusto Cury fell 0.75pp in the winner contract, to 1.60%, and rose 5.75pp in the third-place contract for the first round, to 52.40%: these are different questions. Renan Santos fell 0.35pp, to 2.20%. This round publishes no new price for the Senate majority contract.`,

  'polymarketComparison.candidates[0].pesquisaRange': `37%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `${QUAEST} puts him at 37% in both first-round scenarios, against 38% in the same house's round of Aug 14. He wins the five runoff scenarios: 42% to 41% against the runner-up, 42% to 37% against Ronaldo Caiado, 44% to 33% against Romeu Zema, 43% to 36% against Renan Santos and 40% to 34% against Augusto Cury. Rejection of 53%. In the unprompted scenario he has 28%, with 42% undecided.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55.50% (vol USD 9.59M), ${S}. No change on the day, and his price has not moved off 55.50% for the fifth day running. The distance to the runner-up fell to 14.85pp. In the second-place contract for the first round he gave up 1.20pp, to 8.00%.`,

  'polymarketComparison.candidates[1].polymarket': `40.65%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `The same Quaest puts him at 30% in the scenario with Pablo Marçal and at 29% in the scenario without, against 31% in the house's round of Aug 14. In the runoff he sits 1 point from the leader, 41% against 42%, and that distance was 5pp on Aug 5 and 3pp on Aug 14 in the same house. Rejection of 55%, the highest among the thirteen names tested.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40.65% (vol USD 9.48M), ${S}. Up 1.70pp, the only upward move among the presidential names above the floor. In the second-place contract for the first round he gave up 0.50pp, to 85.50%.`,

  'polymarketComparison.candidates[2].polymarket': `1.60%`,
  'polymarketComparison.candidates[2].pesquisaRange': `10%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `Quaest measures him at 10% in both first-round scenarios, against 2% in the same house's round of Aug 14 and 1% in the one from Aug 5. It is the first poll in the base to test a runoff with him, and in that scenario he loses to the leader 40% to 34%. Rejection of 25%, the lowest among the seven most prominent names. In the unprompted scenario he has 4%.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.60% (vol USD 3.59M), ${S}. DOWN 0.75pp in the winner contract and UP 5.75pp in the third-place contract for the first round, where he stands at 52.40% (vol USD 103 thousand). These are different questions: one is winning the election, the other is finishing third.`,

  'polymarketComparison.candidates[3].polymarket': `2.20%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `Quaest puts him at 3% in the first round, against 4% on Aug 14 in the same house. In a runoff he loses to the leader 43% to 36%, a 7-point margin that is exactly the one measured by Real Time Big Data the day before, and it is the only pair where the two houses of the week agree. Rejection of 28%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `2.20% (vol USD 12.36M), ${S}. Down 0.35pp. In the third-place contract for the first round he fell 2.00pp, to 28.00%.`,

  'polymarketComparison.candidates[4].pesquisaRange': `1%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `Quaest puts him at 1% in the first round, against 4% in the same house's round of Aug 14. ⚠️ IN A RUNOFF HE LOSES TO THE LEADER, 42% TO 37%, and Real Time Big Data of Sep 1, whose fieldwork overlaps, put him ahead 45% to 43%. That is 7pp of difference in the margin of the same pair between two houses that measured the same week. Rejection of 40%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.25% (vol USD 7.05M) in the WINNER contract, ${PISO}, and ${SEM} in that contract. In the THIRD-PLACE contract for the first round, which is a different market, he fell 4.50pp and stands at 8.50% (vol USD 110 thousand).`,

  'polymarketComparison.candidates[5].pesquisaRange': `1%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `Quaest brings him at 1% in the scenario with him on the list, and it is his presence that separates the two scenarios published by the house. ⚠️ THE DIRECTION OF THE EFFECT IS THE REVERSE OF THE ONE MEASURED THE DAY BEFORE: here the runner-up has 30% with Marçal and 29% without, and in Real Time Big Data of Sep 1 he had 29% with and 30% without. Rejection of 44%, the third highest on the table.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.25% (vol USD 3.29M) in the WINNER contract, ${PISO}, and ${SEM}.`,

  'polymarketComparison.candidates[6].pesquisaRange': `1%`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `Quaest measures him at 1% in the first round, against 2% in the same house's round of Aug 14. In a runoff he loses to the leader 44% to 33%, an 11-point margin, and Real Time Big Data of Sep 1 measured the same pair at 43% to 40%, a margin of 3. That is 8pp of difference, the largest among the pairs the two houses tested. Rejection of 38%.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.15% (vol USD 6.47M) in the WINNER contract, ${PISO}, and ${SEM} in that contract. In the THIRD-PLACE contract for the first round, which is a different market, he stands at 0.80% (vol USD 49 thousand).`,
})
