/** Mapa ES de 03/Set/2026: analysis-data. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 03/Set, 15:22 BRT (18:22 UTC)'
const PD = 'PoderData del 03/Set (BR-07561/2026, campo del 30/Ago al 02/Set, n=3.000, margen de 2pp)'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 142,35M y el precio de esta página es de la ${S}. UNA ENCUESTA NACIONAL FUE DIVULGADA ESTE JUEVES, la ${PD}, contratada por el propio instituto, y su divulgación ya constaba en el registro del ${G('TSE', 'tse')} que el panel ingirió esa misma mañana, con la fecha prevista y el número de registro coincidiendo con lo publicado. Otras dos nacionales tenían divulgación marcada para este jueves, la ${G('Datafolha', 'datafolha')} (BR-03669/2026, n=2.002, campo del 01 al 03/Set) y la 100 Cidades (BR-02793/2026, n=2.000, campo del 28/Ago al 01/Set), y ninguna de las dos tenía números publicados al momento de esta lectura.`,
  'cards.sentimento.text2': `LOS DOS PRIMEROS CAYERON EL MISMO DÍA, y eso separa esta ronda de la anterior. El líder cedió 1,00pp y está en 54,50%, después de cinco días parado en 55,50%. El segundo colocado cedió 0,30pp y está en 40,35%. La distancia entre los dos se achicó por segundo día seguido, de 16,55pp el 01/Set a 14,85pp el 02/Set y 14,15pp ahora, pero por un motivo distinto al de ayer: ayer se achicó porque el segundo subió 1,70pp, y hoy se achica porque el líder cayó más que él. La suma de las puntas SÍ del libro presidencial está en 99,20%, es decir, el precio que salió de los dos primeros no apareció en otro nombre.`,
  'cards.sentimento.text3': `La PoderData INVIERTE LA ${G('SEGUNDA VUELTA', 'segundo-turno')} DENTRO DE LA PROPIA CASA. El segundo colocado tiene 45% contra 44% del líder, y en las dos rondas anteriores del mismo instituto era el líder adelante, por 46% a 45% el 13/Ago y por 45% a 44% el 27/Ago. Es la primera vez que la serie de la casa pone al segundo numéricamente adelante en ese par. En la ${G('primera vuelta', 'primeiro-turno')} la casa da al líder en 37% y al segundo en 34%. ⚠️ Y LA CASA DE LA VÍSPERA MIDIÓ LO CONTRARIO: la Genial/${G('Quaest', 'quaest')} del 02/Set, con campo del 30/Ago al 01/Set que se superpone casi entero a este, dio al líder adelante por 42% a 41%. Los dos márgenes son de 1 punto y apuntan a lados opuestos, y las dos casas declaran margen de error de 2pp.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 40,35% (vol USD 9,59M acumulado) en el presidencial, caída de 0,30pp, y 85,50% en el contrato de 2º lugar de la primera vuelta (vol USD 519 mil), sin variación en el día. La PoderData del 03/Set lo da en 34% en la primera vuelta y en 45% en una segunda vuelta contra el líder, que tiene 44%, el primer resultado de la casa en que aparece numéricamente adelante en ese par. Dentro de la propia PoderData salió de 35% el 13/Ago y 35% el 27/Ago a 34% ahora, con la distancia hacia el líder yendo de 6pp a 3pp y quedando en 3pp. Usó la crisis en el Supremo para intentar impulsar el acto del 7 de Septiembre, según Folha de S.Paulo.`,
  'cards.sentimento.esquerda': `Lula en 54,50% (vol USD 9,63M acumulado), caída de 1,00pp que cierra cinco días parado en 55,50%, y 8,75% en el contrato de 2º lugar de la primera vuelta (vol USD 437 mil), alza de 0,75pp. La PoderData lo da en 37% en la primera vuelta y en 44% en una segunda vuelta en que el segundo colocado tiene 45%. Dentro de la casa salió de 41% el 13/Ago a 38% el 27/Ago y 37% ahora. En los otros tres pares de segunda vuelta probados por la casa gana: 44% a 42% contra Ronaldo Caiado, 44% a 42% contra Romeu Zema y 44% a 39% contra Renan Santos. Hizo este jueves, a las 15h en el Planalto, la ceremonia en que declaró en cero la fila del ${G('INSS', 'inss')}, según Poder360 y O Globo.`,
  'cards.sentimento.terceiraVia': `Augusto Cury tiene 10% en la primera vuelta de la PoderData, contra 4% en la ronda de la misma casa del 27/Ago, el mismo salto que la Genial/Quaest midió la víspera yendo de 2% a 10%. En el precio el movimiento sigue yendo hacia los dos lados: en el contrato de ganador CAYÓ a 1,35% (vol USD 3,64M), caída de 0,25pp, y en el contrato de 3º lugar de la primera vuelta SUBIÓ a 55,85% (vol USD 108 mil), alza de 3,45pp, que es el segundo día seguido de alza en ese contrato. Son preguntas distintas: una es ganar la elección, la otra es terminar tercero. Renan Santos tiene 3% en la encuesta y 1,75% (vol USD 12,48M) en el contrato de ganador, caída de 0,45pp, y bajó a 27,00% en el contrato de 3º lugar. Ronaldo Caiado tiene 2% en la encuesta, sigue debajo del piso de 0,5% en el contrato de ganador, y SUBIÓ 2,50pp en el contrato de 3º lugar, donde está en 11,00% (vol USD 111 mil).`,
  'cards.sentimento.polymarket': `Precios de la ${S}. AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20 punto. Esta ronda no publica precio nuevo para Ronaldo Caiado ni para Pablo Marçal en el contrato de ganador, porque los dos están debajo del piso de 0,5%. El libro presidencial acumula USD 142,35M.`,

  'cards.inss.text1': `EL ACTO DEL ${G('INSS', 'inss')} OCURRIÓ ESTE JUEVES, y la fecha importa porque el panel lo registró la víspera como anuncio ya hecho. Lula hizo a las 15h en el Palacio del Planalto la ceremonia "Atención Sin Fila en la Previsión Social", a poco más de un mes de la primera vuelta, según Poder360.`,
  'cards.inss.text2': `⚠️ Y EL CRITERIO DE LA CUENTA ESTÁ DECLARADO EN LA PROPIA FUENTE: el gobierno considera la fila en cero cuando las solicitudes dentro del plazo legal de análisis dejan de contarse como pendientes, lo que no quiere decir que nadie esté esperando. La cuenta no incluye a quien aguarda fuera de ese criterio, según O Globo. Las solicitudes iniciales eran 1,55 millones en julio de 2026, contra 3,07 millones en enero del mismo año.`,
  'cards.inss.text3': `El caso del INSS y el caso del ${G('Banco Master', 'banco-master')} siguen cruzados en el Supremo, y el punto de contacto sigue siendo el mismo: la investigación que alcanzó al ministro Alexandre de Moraes comenzó en la comisión parlamentaria del INSS, según RepórterMT. Ronaldo Caiado defendió este jueves que el Supremo levante el secreto de todas las investigaciones sobre Banco Master, INSS y Dark Horse, según Estadão.`,
  'cards.inss.text4': `El caso sigue vivo y sin desenlace. La distinción que el panel mantiene desde el inicio sigue valiendo: una cosa es el efecto sobre la evaluación del gobierno, otra es el efecto sobre la intención de voto, y las dos no se suman.`,
  'cards.inss.impactoLula': `La lectura estructurada de evaluación del gobierno sigue siendo la de la Genial/Quaest del 02/Set, con campo del 30/Ago al 01/Set: 45% aprueban y 48% desaprueban, con 7% sin respuesta. La PoderData del 03/Set no publicó evaluación de gobierno en la tabla verificada. En la intención de voto de primera vuelta la PoderData pone al presidente en 37%, el mismo número de la Quaest de la víspera.`,
  'cards.inss.impactoGestao': `Dentro de la propia Quaest el cuadro es de inmovilidad. El 05/Ago eran 48% de aprobación contra 47% de desaprobación, el 14/Ago 46% contra 48% y el 02/Set 45% contra 48%. La desaprobación repite el mismo número por tercera ronda seguida de la casa. En la regla de gestión, 35% de excelente o bueno, 25% de regular y 37% de malo o pésimo, contra 36%, 25% y 37% el 14/Ago. El panel mantiene una casa por bloque a propósito, para no sumar reglas de institutos distintos.`,
  'cards.inss.conclusao': `El 03/Set el eje de las noticias quedó dividido entre el Planalto y el Supremo, y el panel no atribuye a ninguno de los dos la variación del precio presidencial. Lo que la serie registra es que los dos primeros cayeron el mismo día, el líder más que el segundo, el mismo día en que una encuesta nacional mostró la segunda vuelta entre ellos invertida en relación con la casa de la víspera.`,

  'cards.bancoMaster.text1': `LO QUE CAMBIÓ EL 3 DE SEPTIEMBRE ES UNA DELACIÓN NUEVA, Y ES LA PRIMERA LIGADA DIRECTAMENTE AL CASO DARK HORSE. La Procuraduría General de la República cerró un acuerdo de colaboración con el empresario Antonio Carlos Freixo Júnior, dueño de Entre Investimentos, según Folha de S.Paulo y O Globo. Su empresa habría viabilizado transferencias de Daniel Vorcaro al fondo estadounidense Havengate Development Fund, que administraba recursos de la película y enviaba valores a la productora. ⚠️ EL ACUERDO ESTÁ CERRADO Y NO ESTÁ HOMOLOGADO: el paso siguiente es el envío al ministro relator.`,
  'cards.bancoMaster.text2': `LA SEGUNDA DELACIÓN ES DEL 2 DE SEPTIEMBRE, NO DE HOY, y la distinción es la misma. La Procuraduría firmó el acuerdo de João Carlos Mansur, fundador de la gestora Reag, y envió el material al despacho del ministro André Mendonça, según Poder360 y G1. La propuesta había sido entregada el 26 de agosto. Mendonça todavía tiene que citar al colaborador a una audiencia y decidir si homologa, y sin homologación el acuerdo no vale como prueba.`,
  'cards.bancoMaster.text3': `En el tribunal, Gilmar Mendes propuso a Edson Fachin vetar delegados de la ${G('Policía Federal', 'pf')} en despachos del Supremo, según Folha de S.Paulo, y en una reunión con Lula orientó a la Policía Federal a reaccionar ante órdenes de Mendonça que considere ilegales, según Estadão. El Colegio de Abogados de Paraná pidió el apartamiento de Moraes y la recusación del procurador general, según Folha de S.Paulo. Poder360 publicó que el instituto ligado a Mendonça tenía 55 contratos con órganos públicos.`,
  'cards.bancoMaster.conclusao': `La cronología es la información, y ahora tiene siete fechas distintas: el encuentro entre el ministro y el empresario es del 14 de marzo de 2025; los mensajes son del 16 de noviembre de 2025; la prisión es del 17 de noviembre de 2025; el informe de la Policía Federal fue entregado el 27 de agosto de 2026, el mismo día de la declaración sin la PF; el secreto cayó el 1º de septiembre; la delación del fundador de Reag fue firmada el 2 de septiembre y siguió a homologación; y la delación del empresario ligado a Dark Horse fue cerrada el 3 de septiembre. ⚠️ NINGUNA DE LAS DOS DELACIONES ESTÁ HOMOLOGADA. Y lo que todavía no ocurrió sigue agendado: el informe de Mendonça sobre Moraes está previsto para el 7 o el 8 de septiembre, según Poder360.`,

  'cards.stf.toffoli': `Sin acto individual nuevo el 03/Set. Su decisión que liberó la campaña digital de Renan Santos es del 01/Set. Sigue siendo blanco del pedido de juicio político presentado por Renan Santos, junto con Moraes, según G1 y Poder360.`,
  'cards.stf.moraes': `SIGUE SIENDO EL NOMBRE DEL DÍA, Y DE NUEVO NO POR ACTO PROPIO. El Colegio de Abogados de Paraná pidió su apartamiento y la recusación del procurador general, según Folha de S.Paulo. Ronaldo Caiado defendió su apartamiento y el juicio político en el Senado, según Valor Econômico. Un ex procurador general dijo que él necesita ser investigado y que el actual debería apartarse del caso Master, según Folha de S.Paulo y BBC.`,
  'cards.stf.gilmar': `PROPUSO A FACHIN VETAR DELEGADOS DE LA POLICÍA FEDERAL EN DESPACHOS DEL SUPREMO, según Folha de S.Paulo, medida que responde directamente a la declaración tomada en el despacho de Mendonça sin la PF. En una reunión con Lula, orientó a la Policía Federal a reaccionar ante órdenes de Mendonça cuando las considere ilegales, según Estadão.`,
  'cards.stf.dino': `Sin acto individual nuevo capturado el 03/Set.`,
  'cards.stf.mendonca': `Recibió de la Procuraduría General de la República el acuerdo de delación del fundador de Reag para decidir sobre la homologación, según Poder360 y G1. Es él quien cita al colaborador a la audiencia y decide si el acuerdo vale como prueba. Poder360 publicó que el instituto ligado a él tenía 55 contratos con órganos públicos. Su informe sobre Moraes sigue previsto para el 7 o el 8 de septiembre.`,
  'cards.stf.nexo': `LA CRISIS PASÓ A PRODUCIR PROPUESTA DE REGLA, Y NO SOLO REACCIÓN. Gilmar Mendes propuso vetar delegados de la Policía Federal en despachos del tribunal, el presidente Edson Fachin siguió las conversaciones con los demás ministros y habló de diálogo y tolerancia para fortalecer la democracia en las elecciones, y Lula se reunió con Fachin y con Gilmar, según Poder360, Folha de S.Paulo y Estadão. El mismo día la Procuraduría cerró la primera delación ligada al caso Dark Horse y entregó al relator la delación del fundador de Reag.`,
  'cards.stf.analise': `El contrato de salida de ministro del Supremo por juicio político antes de 2027 está en 7,40% (vol USD 87 mil) en la ${S}, alza de 1,05pp contra el 6,35% publicado el 02/Set. ⚠️ Y LA SALVEDAD DE AYER VALE OTRA VEZ, AHORA EN LA TERCERA DIRECCIÓN SEGUIDA: este es el menor libro del panel y el volumen acumulado sigue en USD 87 mil, es decir, el dinero nuevo del día es despreciable. En tres días el contrato fue a 10,85%, cayó a 6,35% y subió a 7,40%, y el libro entero negociado desde la apertura cabe en menos de una centésima del libro presidencial. Un precio que anda mucho con dinero de poco no describe un cambio de expectativa del mismo tamaño. El contrato mide la salida de un ministro, no mide si la investigación prospera ni si el Senado lleva el pedido al pleno.`,
})
