/** Mapa EN de 03/Set/2026: card do Augusto Cury em analysis-criteriosa. Ponto decimal. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const LEITURA = 'confirmed reading of 03/Sep, 15:22 BRT (18:22 UTC)'

construir('analysis-criteriosa', 'en', {
  'candidates[2].header': `PRICE: 1.35% (vol USD 3.64M accumulated) in the WINNER contract, ${LEITURA}, down 0.25pp. In the ${G('first round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he rose 3.45pp and stands at 55.85%, in a book of 108 thousand dollars accumulated. POLL: the PoderData poll of 03/Sep (BR-07561/2026, field 30/Aug to 02/Sep, n=3,000, margin of 2pp) measures him at 10% in the first round, against 4% in the same house's round of 27/Aug. It is the second house to measure the jump, after Genial/${G('Quaest', 'quaest')} of 02/Sep, which took him from 2% on 14/Aug to 10%.`,
  'candidates[2].fortes[0]': `⭐ TWO INDEPENDENT HOUSES MEASURED THE SAME JUMP WITHIN THEIR OWN SERIES. At PoderData he went from 4% on 27/Aug to 10% now, and at Genial/Quaest from 1% on 05/Aug to 2% on 14/Aug and 10% on 02/Sep. One house alone would be an isolated reading; two, with field windows in different weeks, is the same direction measured by different instruments.`,
  'candidates[2].fortes[1]': `In the first-round third-place contract he leads with 55.85% and is rising for the second day running, up 3.45pp this round. He took that lead on 01/Sep and the gap to second has doubled since.`,
  'candidates[2].fortes[2]': `His rejection rate is 25% in the Genial/Quaest poll of 02/Sep, the lowest among the seven most prominent names tested, against 55% for the runner-up and 53% for the leader.`,
  'candidates[2].fortes[3]': `He is the only name outside the top two who rose at PoderData between 27/Aug and now: over the same interval Renan Santos went from 4% to 3%, Ronaldo Caiado from 4% to 2% and Romeu Zema from 2% to 1%.`,
  'candidates[2].fortes[4]': `The BBC published an analysis arguing that the Vorcaro and Moraes case could feed an anti-politics wave and favour him and Renan Santos.`,
  'candidates[2].fracos[0]': `⚠️ THE TWO CONTRACTS POINT IN OPPOSITE DIRECTIONS, AND THAT IS THE HEART OF HIS CASE. In the winner contract he FELL 0.25pp and stands at 1.35%, and in the first-round third-place contract he ROSE 3.45pp. These are different questions: one is winning the election, the other is finishing third, and the market is buying the second while selling the first.`,
  'candidates[2].fracos[1]': `The 1.35% in the winner contract sits alongside 10% in declared voting intention. It is the widest gap between poll and price in the table, and it did not narrow with the jump: the price fell on the same day the second house confirmed the 10%.`,
  'candidates[2].fracos[2]': `The PoderData poll of 03/Sep did NOT test a ${G('second round', 'segundo-turno')} with him, so the only second-round reading in the base is still the Genial/Quaest one of 02/Sep, in which he loses to the leader by 40% to 34%.`,
  'candidates[2].fracos[3]': `Accumulated volume in his winner contract is USD 3.64M, the smallest among the seven names in the table, meaning the price that moves there moves on very little money.`,
  'candidates[2].fracos[4]': `The campaigns of the other candidates outside the top two sharpened their tone against him after the jump, according to O Globo, and he became a declared target in a space that was not being contested before.`,
  'candidates[2].analise': `His case is the clearest on the panel for separating two questions that tend to be read as one. In declared voting intention the jump is confirmed by two independent houses, each within its own series, and the second confirmation arrived this Thursday. In the price, the two contracts he appears in moved in opposite directions on the same day: the winner contract gave up 0.25pp and the first-round third-place contract rose 3.45pp, a second straight day of gains. The reading the panel records is that the market priced the jump in where it fits, which is the contest for third place, and not where it does not fit, which is the contest for the election. Neither move says who is right: they only say that the question changes the answer. And the base still has a single second-round reading with him, the Genial/Quaest one of 02/Sep, which makes any claim about how he behaves in a runoff premature.`,
})
