/** Mapa EN, 2a rodada de 03/Set/2026: analysis-criteriosa. Ponto decimal. Tudo ou nada. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 03/Sep, 17:28 BRT (20:28 UTC)'
const PD = 'the PoderData poll of 03/Sep (BR-07561/2026, field 30/Aug to 02/Sep, n=3,000, margin of 2pp)'
const F4 =
  'BTG/Nexus on 31/Aug at 11%, against 2% in the same house’s round of 24/Aug; Real Time Big Data on 01/Sep at 11%; Genial/Quaest on 02/Sep at 10%, against 2% on 14/Aug and 1% on 05/Aug; and PoderData on 03/Sep at 10%, against 4% on 27/Aug'

construir('analysis-criteriosa', 'en', {
  subtitle: `Cross-reading for 3 September 2026, the day's second reading: ${G('Polymarket', 'polymarket')} price from the ${S}, presidential book at USD 142.36M, against ${PD}, the only national poll with published figures this Thursday. ⭐ A SINGLE CONTRACT MOVED SINCE THE 15:22 READING, and it moved 2.15pp: the runner-up went from 40.35% to 42.50% and the other eighteen stayed flat, with the gap to the leader falling to 12.00pp. 🔴 AND THIS ROUND CORRECTS THE PREVIOUS ONE on Augusto Cury's jump: he was measured into double digits by FOUR houses since 31/Aug, not two, and the first was BTG/${G('Nexus', 'nexus-btg')}, not Genial/${G('Quaest', 'quaest')}.`,

  cruzamento: `The day's second reading measures two things, and the first is a correction of our own. 🔴 AUGUSTO CURY'S JUMP INTO DOUBLE DIGITS WAS MEASURED BY FOUR HOUSES, NOT TWO, and it began on 31/Aug and not this Thursday. In the panel's base: ${F4}. AtlasIntel on 31/Aug measured him at 7.8%. This page's 15:22 reading said two houses and named Genial/Quaest as the first, and both claims were wrong: all four readings were already in our own file, and the within-house comparison shows the jump in three of them, with BTG/Nexus going from 2% to 11% in seven days. The second thing is the price. ⭐ A SINGLE CONTRACT IN THE PRESIDENTIAL BOOK MOVED IN TWO HOURS. The runner-up rose 2.15pp, from 40.35% to 42.50%, and the other eighteen names stayed flat, the leader included, who is still at 54.50%. The gap between the two fell to 12.00pp, against 14.15pp in today's 15:22 reading, 14.85pp on 02/Sep and 16.55pp on 01/Sep. ⚠️ AND THE MONEY BEHIND IT IS SMALL: between today's two readings the runner-up's contract took in about USD 5.8 thousand of new business and the leader's took in about USD 7.0 thousand without moving, in a book that has accumulated USD 142.36M. Because the runner-up rose and no one else gave ground, the sum of the YES legs went from 99.20% to 101.35%. The rule the panel already applies to the ${G('Supreme Court', 'stf')} contract applies here in the same way: a price that moves a lot on very little money does not describe a shift in expectations of the same size. In the polls nothing changed since 15:22, and ${G('Datafolha', 'datafolha')}, scheduled for release today on the ${G('TSE', 'tse')} register, still had no figures at the time of this reading.`,

  // Lula
  'candidates[0].header': `PRICE: 54.50% (vol USD 9.63M accumulated), ${S}, unchanged since today's 15:22 reading. His contract took in about USD 7.0 thousand of new business over that stretch and did not move. POLL: ${PD} gives him 37% in the ${G('first round', 'primeiro-turno')} and 44% in a ${G('second round', 'segundo-turno')} in which the runner-up has 45%. He wins the other three pairings the house tested: 44% to 42% against Ronaldo Caiado, 44% to 42% against Romeu Zema and 44% to 39% against Renan Santos.`,
  'candidates[0].fortes[2]': `His price did not give ground in the two hours in which the runner-up's rose 2.15pp.`,
  'candidates[0].fortes[3]': `He declared the ${G('INSS', 'inss')} queue cleared at a ceremony at the Planalto Palace, and requests running more than 45 days late fell 86% since January, from 1.88 million to 261 thousand in August, according to Metrópoles and Poder360.`,
  'candidates[0].fortes[4]': `The lower house approved a provisional measure this Thursday to speed up INSS benefit reviews, according to Metrópoles.`,
  'candidates[0].fracos[0]': `⚠️ IN PODERDATA'S SECOND ROUND HE APPEARS BEHIND, 44% to 45%, for the first time in the three rounds from this house since 13/Aug.`,
  'candidates[0].fracos[1]': `His gap to the runner-up in the price fell to 12.00pp, against 16.55pp on 01/Sep, and it narrowed without him moving in this reading.`,
  'candidates[0].fracos[3]': `⚠️ THE INSS ANNOUNCEMENT COMES WITH A STATED CRITERION THAT NARROWS WHAT IT MEANS: according to the social security minister, the queue counts as cleared when fewer people are waiting than the number who filed the previous month, and 261 thousand requests past 45 days remain open in August, alongside 1.2 million applications still in progress.`,
  'candidates[0].fracos[4]': `In the first-round runner-up contract he gave up 0.05pp and stands at 8.70%.`,
  'candidates[0].analise': `Between today's two readings he did not move, and he still lost ground. His contract took in more new money than his opponent's, about USD 7.0 thousand against about USD 5.8 thousand, and stayed flat at 54.50% while the other rose 2.15pp. The gap between the two fell to 12.00pp, the fourth consecutive timestamp in which it narrows, counting 16.55pp on 01/Sep, 14.85pp on 02/Sep and 14.15pp at 15:22 today. In declared voting intention the picture has not changed since the morning, because there was no new national poll. What changes on his side is the INSS: the ceremony took place, and the definition the government uses to say the queue is cleared is the minister's, with 261 thousand requests past 45 days still open in August.`,

  // Flávio
  'candidates[1].header': `PRICE: 42.50% (vol USD 9.59M accumulated), ${S}, up 2.15pp on today's 15:22 reading, and it is the ONLY move in the presidential book across the two hours between the readings. The gap to the leader fell to 12.00pp. POLL: ${PD} gives him 34% in the first round and 45% in a second round against the leader, who has 44%.`,
  'candidates[1].fortes[0]': `⭐ HE WAS THE ONLY NAME IN THE PRESIDENTIAL BOOK TO MOVE BETWEEN TODAY'S TWO READINGS, up 2.15pp, while the other eighteen stayed flat.`,
  'candidates[1].fortes[1]': `The gap to the leader fell to 12.00pp, against 14.15pp at 15:22 today, 14.85pp on 02/Sep and 16.55pp on 01/Sep.`,
  'candidates[1].fortes[2]': `In PoderData's second round he appears numerically ahead, 45% to 44%, for the first time in the three rounds from this house since 13/Aug.`,
  'candidates[1].fortes[3]': `The stock exchange rose 3.06% on 02/Sep after the Genial/Quaest release, according to Metrópoles, and the panel records the sequence without assigning it a cause.`,
  'candidates[1].fracos[0]': `⚠️ THE MONEY BEHIND THE RISE IS SMALL: his contract took in about USD 5.8 thousand of new business between today's two readings, less than the roughly USD 7.0 thousand that went into the leader's contract, which did not move.`,
  'candidates[1].fracos[1]': `In the first round he gave ground within PoderData itself, from 35% on 13/Aug and 35% on 27/Aug to 34% now.`,
  'candidates[1].fracos[2]': `The 1-point lead in the second round sits inside the declared margin of 2pp, and the house from the day before measured the same pairing the other way, 41% to 42%.`,
  'candidates[1].fracos[3]': `In the first-round runner-up contract he did not move and is still at 85.50%, meaning the rise stayed entirely in the winner contract.`,
  'candidates[1].analise': `The 17:28 reading belongs to him and to nobody else. Between today's two captures the presidential book had a single contract in motion, and it was his, up 2.15pp. What qualifies that move is the money: about USD 5.8 thousand of new business, less than went into the leader's contract, which stayed flat. It is the same caveat the panel applies to the Supreme Court contract, and it applies here because the magnitude is the same. In declared voting intention nothing changed since the morning, and what supports his reading is still PoderData, which puts him numerically ahead in the second round for the first time in the house's three rounds. In the first round, at the same time, he gave up 1 point within that same house.`,

  // Cury
  'candidates[2].header': `PRICE: 1.35% (vol USD 3.64M accumulated) in the WINNER contract, ${S}, unchanged since today's 15:22 reading. In the first-round THIRD-PLACE contract, which is a different market, he rose 0.05pp and stands at 55.90%, in a book of 108 thousand dollars accumulated. POLL: 🔴 THIS ROUND CORRECTS THE PREVIOUS ONE. His jump into double digits was measured by FOUR houses since 31/Aug, not two: ${F4}.`,
  'candidates[2].fortes[0]': `⭐ FOUR HOUSES MEASURED HIM IN DOUBLE DIGITS SINCE 31/Aug, and three of them have their own series showing the jump: ${F4}. AtlasIntel on 31/Aug measured him at 7.8%.`,
  'candidates[2].fortes[1]': `The largest jump between two consecutive rounds of the same house, in this window, is BTG/Nexus: from 2% on 24/Aug to 11% on 31/Aug, seven days between the two rounds.`,
  'candidates[2].fortes[2]': `In the first-round third-place contract he leads with 55.90% and rose 0.05pp in this reading, after 3.45pp in the previous one.`,
  'candidates[2].fortes[4]': `In the first-round runner-up contract he rose 0.30pp and stands at 2.45% (vol USD 124 thousand).`,
  'candidates[2].fracos[0]': `⚠️ THE TWO CONTRACTS STILL POINT IN OPPOSITE DIRECTIONS, and the winner contract did not react to the jump: it stands at 1.35% and has not moved since the 15:22 reading, while declared voting intention puts him at 10% or 11% across four houses.`,
  'candidates[2].fracos[1]': `The 1.35% in the winner contract sits alongside double digits in declared voting intention. It is the widest gap between poll and price in the table.`,
  'candidates[2].fracos[3]': `Accumulated volume in his winner contract is USD 3.64M, the smallest among the seven names in the table.`,
  'candidates[2].fracos[4]': `The campaigns of the other candidates outside the top two sharpened their tone against him after the jump, according to O Globo.`,
  'candidates[2].analise': `His case changed size in this round, and through an error of ours. The 15:22 reading said the jump had been measured by two houses and that Genial/Quaest of 02/Sep was the first. Both claims were wrong, and the readings that disprove them were already in the panel's file: four houses measured him in double digits, and the first was BTG/Nexus on 31/Aug, four days earlier. With the base corrected, the reading gets firmer rather than weaker: three houses show the jump within their own series, and the largest jump between consecutive rounds is from 2% to 11% in seven days. In the price, none of that showed up in the winner contract, which is still at 1.35% and did not move in the two hours between today's readings. The market priced the jump into the third-place contract, where he leads with 55.90%, and not into the winner contract. They are different questions, and the answer changes with the question.`,

  // Renan
  'candidates[3].header': `PRICE: 1.75% (vol USD 12.48M accumulated), ${S}, unchanged since today's 15:22 reading. In the first-round third-place contract he gave up 0.50pp and now stands at 26.50% in a contract of USD 266 thousand. POLL: ${PD} gives him 3% in the first round, against 4% in the same house's round of 27/Aug. In a second round he loses to the leader by 44% to 39%.`,
  'candidates[3].fortes[2]': `He said Alexandre de Moraes's rulings should not be recognised, according to Poder360, and remains inside the story dominating the week's news.`,
  'candidates[3].fortes[3]': `The spread between houses works in his favour in some readings: AtlasIntel on 31/Aug measured him at 7.6% and Real Time on 01/Sep at 6%, against 3% at Quaest and PoderData.`,
  'candidates[3].fracos[0]': `In the first-round third-place contract he gave up 0.50pp and now stands at 26.50%, against 55.90% for the leader, and the gap keeps widening.`,
  'candidates[3].fracos[3]': `⚠️ THE SPREAD BETWEEN HOUSES IS ALSO A READING PROBLEM: his figures in the window run from 3% to 7.6%, and a range that wide makes any claim about a trend from a single house fragile.`,
  'candidates[3].analise': `He is the name the houses disagree on most in this window, and that matters more than any single reading of him: in the panel's base the figures run from 3% at Genial/Quaest and PoderData to 6% at Real Time and 7.6% at AtlasIntel. Within PoderData, which is the valid comparison, he gave ground from 4% to 3% over the same interval in which Augusto Cury went from 4% to 10%. In the second round against the leader, though, the margin against him narrowed from 7 to 5 points within the house. In the price this round reads as stillness in the winner contract and a 0.50pp fall in the third-place contract, where he was overtaken on 01/Sep and the gap to the leader keeps widening.`,

  // Trailing pack
  'candidates[4].header': `PRICE: Caiado at 0.25%, Zema at 0.15% and Haddad at 0.05% in the WINNER contract, all three below the 0.5% floor of the double reading, and this round does not publish a new price for any of them in that contract. In the first-round THIRD-PLACE contract, which is a different market, Caiado gave up 0.50pp and stands at 10.50%, and Zema is still at 0.80%. POLL: ${PD} gives 2% to Ronaldo Caiado and 1% to Romeu Zema in the first round. In a second round the leader beats both, by 44% to 42% in each case.`,
  'candidates[4].subtitle': `Trailing pack at the ${S}, and in this second reading of the day none of the three moved in the winner contract. What changes is the third-place contract, in which Ronaldo Caiado handed back 0.50pp of the 2.50pp rise recorded at 15:22. The second-round pairing against him still carries three results in the same week, all with overlapping field windows: 45% to 43% in his favour at Real Time Big Data on 01/Sep, 42% to 37% against him at Genial/Quaest on 02/Sep and 44% to 42% against him at PoderData on 03/Sep.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0.25% (vol USD 7.11M) in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him in that contract. In the first-round THIRD-PLACE contract, which is a different market, he gave up 0.50pp and stands at 10.50%, in a book of 111 thousand dollars accumulated. IN THIS THURSDAY'S DECLARED VOTING INTENTION HE LOSES THE SECOND ROUND TO THE LEADER BY 44% TO 42%, the smallest margin against him among the week's three houses.`,
  'candidates[4].caiado.fortes': `In PoderData's second round he sits 2 points behind the leader, 44% to 42%, against 3 points in the same house's round of 27/Aug. In the first-round third-place contract he remains above the 8.50% he stood at on 02/Sep, even after handing back 0.50pp in this reading. He argued for Alexandre de Moraes to be removed from the case and for impeachment in the Senate, according to Valor Econômico, and for the Supreme Court to lift secrecy on every investigation into Banco Master, INSS and Dark Horse, according to Estadão.`,
  'candidates[4].caiado.fracos': `In the first round he fell from 4% to 2% within PoderData itself, between 27/Aug and now. In the winner contract he remains below the 0.5% floor. And in the third-place contract he handed back 0.50pp of the 2.50pp rise the 15:22 reading recorded, meaning the morning's move did not hold in full over the following two hours.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0.15% (vol USD 6.51M) in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him in that contract. In the first-round THIRD-PLACE contract, which is a different market, he is still at 0.80%, in a book of 49 thousand dollars accumulated.`,
  'candidates[4].zema.fracos': `He has 1% in the first round, against 2% in the same house's round of 27/Aug. And the second round against the leader is the scenario in which the week's three houses disagree most: Genial/Quaest of 02/Sep gave 44% to 33%, a margin of 11 points, Real Time Big Data of 01/Sep gave 43% to 40%, a margin of 3, and PoderData now gives 44% to 42%, a margin of 2.`,
  'candidates[4].analise': `The second-round pairing against Ronaldo Caiado is still the portrait of the week: three houses, three results, all with overlapping field windows, with margins ranging from 2 points behind the leader to 5 points. The panel records all three and does not choose between them. In this second reading of the day none of the three moved in the winner contract, where all three remain below the 0.5% floor. The only move is Caiado handing back 0.50pp in the third-place contract, which at 15:22 had been the panel's largest upward move. In the first round, at the same time, he gave ground within PoderData itself, from 4% on 27/Aug to 2%.`,
  'candidates[4].fortes': `Ronaldo Caiado sits 2 points behind the leader in PoderData's second round, the smallest margin against him among the week's three houses, and remains above his 02/Sep level in the third-place contract even after handing back 0.50pp in this reading.`,

  // Comparison table
  'quadroComparativo[0].m': `54.50% (vol USD 9.63M), ${S}. Unchanged since today's 15:22 reading, and the contract took in about USD 7.0 thousand of new business over that stretch. The gap to the runner-up fell to 12.00pp, against 14.15pp at 15:22 and 14.85pp on 02/Sep. In the first-round runner-up contract he gave up 0.05pp and stands at 8.70%.`,
  'quadroComparativo[0].t': `stays flat and loses ground anyway, because the day's move is all on the other side`,
  'quadroComparativo[0].s': `He declared the INSS queue cleared at a ceremony at the Planalto Palace. By the social security minister's definition, the queue counts as cleared when fewer people are waiting than the number who filed the previous month, and 261 thousand requests past 45 days remain open in August, according to Metrópoles and Poder360. The lower house approved a provisional measure to speed up benefit reviews, according to Metrópoles.`,
  'quadroComparativo[1].m': `42.50% (vol USD 9.59M), ${S}. Up 2.15pp on today's 15:22 reading, and it is the ONLY move in the presidential book between the two readings. ⚠️ The contract took in about USD 5.8 thousand of new business over that stretch, less than went into the leader's contract, which did not move. In the first-round runner-up contract he is still flat at 85.50%.`,
  'quadroComparativo[1].t': `the only name in the book to move in two hours, and the money behind it is smaller than that of the opponent standing still`,
  'quadroComparativo[1].s': `He used the crisis at the Supreme Court to try to build momentum for the 7 September rally, according to Folha de S.Paulo. The stock exchange rose 3.06% on 02/Sep after the Genial/Quaest release, according to Metrópoles.`,
  'quadroComparativo[2].p': `🔴 CORRECTION OF THE 15:22 READING: his jump into double digits was measured by FOUR houses since 31/Aug, not two, and the first was BTG/Nexus, not Genial/Quaest. In the panel's base: ${F4}. AtlasIntel on 31/Aug measured him at 7.8%. PoderData did not test a second round with him.`,
  'quadroComparativo[2].m': `1.35% (vol USD 3.64M), ${S}. Unchanged in the winner contract since today's 15:22 reading. In the first-round third-place contract he rose 0.05pp and stands at 55.90% (vol USD 108 thousand), and in the runner-up contract he rose 0.30pp, to 2.45%.`,
  'quadroComparativo[2].t': `four houses put him in double digits and the winner contract does not move`,
  'quadroComparativo[3].p': `${PD} gives him 3% in the first round, against 4% in the same house's round of 27/Aug. ⚠️ HE IS THE NAME THE HOUSES DISAGREE ON MOST IN THIS WINDOW: 3% at Genial/Quaest and PoderData, 6% at Real Time Big Data on 01/Sep and 7.6% at AtlasIntel on 31/Aug. In a second round he loses to the leader by 44% to 39%, and the same house measured 44% to 37% on 27/Aug.`,
  'quadroComparativo[3].m': `1.75% (vol USD 12.48M), ${S}. Unchanged in the winner contract since today's 15:22 reading. In the first-round third-place contract he gave up 0.50pp and now stands at 26.50% in a contract of USD 266 thousand.`,
  'quadroComparativo[3].t': `flat in the winner contract, giving ground in the third-place one, and with the widest spread between houses in the table`,
  'quadroComparativo[3].s': `He said Alexandre de Moraes's rulings should not be recognised, according to Poder360.`,
  'quadroComparativo[4].m': `0.25% (vol USD 7.11M) in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him in that contract. In the first-round THIRD-PLACE contract, which is a different market, he gave up 0.50pp and stands at 10.50% (vol USD 111 thousand), handing back part of the 2.50pp rise from the 15:22 reading.`,
  'quadroComparativo[4].t': `hands back part of the morning's rise in the third-place contract, and the second-round pairing against him still carries three different readings`,
  'quadroComparativo[6].m': `7.40% (vol USD 87 thousand), ${S}. Unchanged since today's 15:22 reading. ⚠️ IT IS THE SMALLEST BOOK ON THE PANEL and accumulated volume is still USD 87 thousand. Over three days the contract went to 10.85%, fell to 6.35% and rose to 7.40%.`,
  'quadroComparativo[6].t': `flat in this reading, after three directions in three days with accumulated volume all but motionless`,
  'quadroComparativo[6].s': `Gilmar Mendes proposed removing Federal Police officers from the court's chambers, according to Folha de S.Paulo and Poder360. Daniel Vorcaro said in his testimony that he was pressured not to implicate a Federal Police director and members of the government, according to Gazeta do Povo, and the Prosecutor General's Office asked on 02/Sep for that complaint to be shelved, according to Folha de S.Paulo, O Globo and G1. The Reag founder's plea deal advanced at the court, according to Metrópoles, and remains unratified. Cristiano Zanin was elected to a second term as a substitute justice on the electoral court, according to CartaCapital.`,
})
