/** Mapa EN de 03/Set/2026: polls-data. Ponto decimal e vírgula de milhar. Tudo ou nada. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 03/Sep, 15:22 BRT (18:22 UTC)'
const PD = 'PoderData poll of 03/Sep (BR-07561/2026, field 30/Aug to 02/Sep, n=3,000)'

construir('polls-data', 'en', {
  'polls[0].note': `PoderData national poll released on 03/Sep (Gazeta do Povo). ⭐ IT FLIPS THE ${G('SECOND ROUND', 'segundo-turno')} WITHIN ITS OWN HOUSE. Flávio Bolsonaro has 45% against 44% for Lula, with 8% blank or spoiled and 3% don't know. In the institute's two previous rounds it was Lula ahead, by 46% to 45% on 13/Aug and by 45% to 44% on 27/Aug, and this is the first in the house series in which the runner-up appears numerically ahead in that pairing. The gap is 1 point and the declared margin is 2pp, meaning a ${G('statistical tie', 'empate-tecnico')} by the house's own yardstick. ⚠️ AND THE HOUSE FROM THE DAY BEFORE MEASURED THE OPPOSITE IN THE SAME PAIRING: Genial/${G('Quaest', 'quaest')} of 02/Sep, with a field window of 30/Aug to 01/Sep that overlaps almost entirely with this one, gave Lula ahead by 42% to 41%. Both margins are 1 point and they point in opposite directions. COMPARISON WITHIN THE HOUSE, which is the only valid one. In the ${G('first round', 'primeiro-turno')} Lula went from 41% on 13/Aug to 38% on 27/Aug and 37% now, and Flávio from 35% to 35% and 34%, so the gap between them went from 6pp to 3pp and stayed at 3pp. ⭐ AUGUSTO CURY JUMPS FROM 4% TO 10% WITHIN PODERDATA between 27/Aug and now, the same jump Genial/Quaest measured the day before going from 2% to 10%. Over the same interval Renan Santos went from 4% to 3%, Ronaldo Caiado from 4% to 2% and Romeu Zema from 2% to 1%. In the other three second-round pairings tested Lula wins: 44% to 42% against Caiado, 44% to 42% against Zema and 44% to 39% against Renan Santos. Against Caiado the house measured 44% to 43% on 27/Aug, and Real Time Big Data of 01/Sep gave Caiado ahead by 45% to 43%, meaning three houses and three different results in the same pairing in the same week. The first-round scenario closes at exactly 100 with 5% blank or spoiled and 2% undecided. Field 30/Aug to 02/Sep, n=3,000, margin of 2pp, 95% confidence, commissioned by the institute itself, ${G('TSE', 'tse')} registration BR-07561/2026. 📅 THIS THURSDAY'S RELEASE WAS ALREADY IN THE TSE REGISTER ingested by the panel that same morning, with the scheduled date and the registration number matching what was published. ℹ️ The house did not publish government approval or rejection figures in the table that was checked.`,
  'polls[0].source': `PoderData, released on 03/Sep/2026 (field 30/Aug to 02/Sep, n=3,000, margin of 2pp, 95% confidence, commissioned by the institute itself, TSE registration BR-07561/2026). Full table of the first round and of the four second-round scenarios checked in Gazeta do Povo.`,

  'approvalData.note': `🏷️ THE STRUCTURED FIGURES IN THIS BLOCK COME FROM GENIAL/QUAEST OF 02/Sep, and they are these: 45% approval against 48% disapproval, with 7% don't know, and 35% excellent or good, 25% fair and 37% poor or very poor, with 3% giving no answer. ℹ️ THE PODERDATA POLL OF 03/Sep DID NOT PUBLISH GOVERNMENT APPROVAL OR REJECTION in the table that was checked, so this block does not change in this round. The panel deliberately keeps ONE house per block, so as not to add up yardsticks from different institutes. ⭐ WITHIN QUAEST ITSELF THE PICTURE IS ONE OF STILLNESS. On 05/Aug it was 48% approval against 47% disapproval, on 14/Aug 46% against 48% and on 02/Sep 45% against 48%. Disapproval has held the same figure for the house's third round running, and approval gave up 1pp in each of the last two. On the performance scale, excellent or good went from 36% on 14/Aug to 35%, with fair and poor or very poor flat at 25% and 37%. 📌 REJECTION, also from the 02/Sep round and the same house: Flávio Bolsonaro 55% and Lula 53%, against 54% and 52% in the 14/Aug round. Both rose 1pp and the gap between them did not change. In the same round, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28% and Augusto Cury 25%.`,

  'polymarketComparison.note': `${G('Polymarket', 'polymarket')} prices from the ${S}, with the presidential book at USD 142.35M. ONE NATIONAL POLL WAS RELEASED THIS THURSDAY, PoderData (BR-07561/2026, field 30/Aug to 02/Sep, n=3,000, margin of 2pp, commissioned by the institute itself), and its release was already on the TSE register ingested by the panel that same morning. ⭐ IT FLIPS THE SECOND ROUND WITHIN ITS OWN HOUSE: Flávio Bolsonaro 45% and Lula 44%, after Lula 46% to 45% on 13/Aug and Lula 45% to 44% on 27/Aug. It is the first in the house series in which the runner-up appears numerically ahead in that pairing, and the 1-point gap sits inside the declared margin of 2pp. ⚠️ THE HOUSE FROM THE DAY BEFORE MEASURED THE OPPOSITE: Genial/Quaest of 02/Sep, with an overlapping field window, gave Lula ahead by 42% to 41%. The panel records the divergence and does not arbitrate between the two. ⭐ IN THE PRICE, THE TOP TWO BOTH FELL ON THE SAME DAY: the leader gave up 1.00pp, to 54.50%, ending five days flat, and the runner-up gave up 0.30pp, to 40.35%. The gap between them narrowed for the second day running, from 16.55pp on 01/Sep to 14.85pp on 02/Sep and 14.15pp now, but for a different reason than yesterday, when the runner-up rose. The sum of the YES legs in the presidential book stands at 99.20%. ⏳ TWO OTHER NATIONAL POLLS HAD RELEASES SCHEDULED FOR THIS THURSDAY on the TSE register, ${G('Datafolha', 'datafolha')} (BR-03669/2026, n=2,002, field 01 to 03/Sep) and 100 Cidades (BR-02793/2026, n=2,000, field 28/Aug to 01/Sep), and neither had published figures at the time of this reading. 📅 THE CALENDAR AHEAD, already stripped of the registrations that have left the TSE file: Veritá on 06/Sep (BR-09426/2026, n=3,840), Genial/Quaest on 07/Sep (BR-01720/2026, n=2,004), and Gerp (BR-00251/2026, n=2,400) and ${G('Nexus', 'nexus-btg')} (BR-06790/2026, n=2,000) on 08/Sep.`,

  // Lula
  'polymarketComparison.candidates[0].polymarket': `54.50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `The ${PD} gives him 37% in the first round, against 38% in the same house's round of 27/Aug and 41% in the one of 13/Aug. ⚠️ IN A SECOND ROUND AGAINST THE RUNNER-UP HE FALLS BEHIND FOR THE FIRST TIME IN THE THREE ROUNDS FROM THIS HOUSE SINCE 13/Aug, 44% to 45%, after 46% to 45% on 13/Aug and 45% to 44% on 27/Aug. Genial/Quaest the day before measured the same pairing the other way, 42% to 41% in his favour. He wins the other three pairings PoderData tested: 44% to 42% against Ronaldo Caiado, 44% to 42% against Romeu Zema and 44% to 39% against Renan Santos.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `54.50% (vol USD 9.63M), ${S}. Down 1.00pp, after five days flat at 55.50%. The gap to the runner-up fell to 14.15pp, against 14.85pp on 02/Sep and 16.55pp on 01/Sep, and this time it narrows because he fell further, not because the runner-up rose. In the first-round runner-up contract he rose 0.75pp, to 8.75%.`,

  // Flávio
  'polymarketComparison.candidates[1].polymarket': `40.35%`,
  'polymarketComparison.candidates[1].pesquisaRange': `34%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `PoderData gives him 34% in the first round, against 35% in the same house's two previous rounds, of 13/Aug and 27/Aug. ⭐ IN THE SECOND ROUND HE APPEARS NUMERICALLY AHEAD FOR THE FIRST TIME IN THE THREE ROUNDS FROM THIS HOUSE SINCE 13/Aug, 45% to 44%, and the gap within the house went from 1 point behind on 13/Aug and 27/Aug to 1 point ahead now. The declared margin is 2pp, so it is a statistical tie by the house's own yardstick. Genial/Quaest the day before measured the same pairing the other way, 41% to 42%.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40.35% (vol USD 9.59M), ${S}. Down 0.30pp, on the same day the leader also fell, and that is what separates this round from the previous one. In the first-round runner-up contract he held flat at 85.50% (vol USD 519 thousand).`,

  // Cury
  'polymarketComparison.candidates[2].polymarket': `1.35%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `PoderData measures him at 10% in the first round, against 4% in the same house's round of 27/Aug. It is the same jump Genial/Quaest measured the day before, from 2% on 14/Aug to 10% on 02/Sep, and now two independent houses are measuring the same direction within their own series. PoderData did not test a second round with him.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.35% (vol USD 3.64M), ${S}. DOWN 0.25pp in the winner contract and UP 3.45pp in the first-round third-place contract, where he stands at 55.85% (vol USD 108 thousand) and is rising for the second day running. These are different questions: one is winning the election, the other is finishing third.`,

  // Renan
  'polymarketComparison.candidates[3].polymarket': `1.75%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `PoderData gives him 3% in the first round, against 4% in the same house's round of 27/Aug. In a second round he loses to the leader by 44% to 39%, a margin of 5 points, and the same house measured 44% to 37% on 27/Aug, meaning the margin narrowed by 2 points within the house. Genial/Quaest the day before measured that pairing at 43% to 36%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.75% (vol USD 12.48M), ${S}. Down 0.45pp. In the first-round third-place contract he fell 1.00pp and now stands at 27.00% in a contract of USD 266 thousand.`,

  // Caiado
  'polymarketComparison.candidates[4].pesquisaRange': `2%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `PoderData puts him at 2% in the first round, against 4% in the same house's round of 27/Aug. ⚠️ THE SECOND ROUND AGAINST HIM ALREADY HAS THREE DIFFERENT RESULTS IN THE SAME WEEK: PoderData gives the leader ahead by 44% to 42%, Genial/Quaest of 02/Sep gave 42% to 37% and Real Time Big Data of 01/Sep gave him ahead by 45% to 43%. All three houses had overlapping field windows.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.25% (vol USD 7.11M) in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him in that contract. In the first-round THIRD-PLACE contract, which is a different market, he ROSE 2.50pp and stands at 11.00% (vol USD 111 thousand), confirmed reading of 03/Sep, 15:22 BRT.`,

  // Marçal
  'polymarketComparison.candidates[5].pesquisaRange': `2%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `PoderData measures him at 2% in the first round, against 3% in the same house's round of 27/Aug. Unlike Genial/Quaest the day before, this house published a single first-round scenario, with him on the list, so this round does not measure the effect of his presence on the runner-up's figure.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.34M) in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him.`,

  // Zema
  'polymarketComparison.candidates[6].tendenciaPesquisa': `PoderData measures him at 1% in the first round, against 2% in the same house's round of 27/Aug. In a second round he loses to the leader by 44% to 42%, a margin of 2 points. Genial/Quaest of 02/Sep measured the same pairing at 44% to 33%, a margin of 11, and Real Time Big Data of 01/Sep at 43% to 40%, a margin of 3. That is three houses and three margins, of 2, 3 and 11 points, in the same week.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.15% in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him in that contract. In the first-round THIRD-PLACE contract, which is a different market, he stands at 0.80% (vol USD 49 thousand), confirmed reading of 03/Sep, 15:22 BRT.`,
})
