/** Mapa ES da rodada de fechamento de 03/Set/2026, carimbo 23:45. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 03/Set, 23:45 BRT (04/Set, 02:45 UTC)'
const DF = 'la Datafolha del 03/Set (BR-03669/2026, campo del 01 al 03/Set, n=2.002, margen de 2pp)'
const TRES = 'la Genial/Quaest del 02/Set dio al líder adelante por 42% a 41%, la PoderData del 03/Set dio al segundo adelante por 45% a 44%, y la Datafolha del 03/Set da al líder adelante por 46% a 44%'
const QUATRO = 'BTG/Nexus 11% el 31/Ago, Real Time Big Data 11% el 01/Set, Genial/Quaest 10% el 02/Set y PoderData 10% el 03/Set'
const CINCO = 'BTG/Nexus 11% el 31/Ago, Real Time Big Data 11% el 01/Set, Genial/Quaest 10% el 02/Set, PoderData 10% el 03/Set y Datafolha 7% y 8% en los dos escenarios del mismo día'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 142,61M y el precio de esta página es de la ${S}. ⭐ LA ${G('DATAFOLHA', 'datafolha')} SALIÓ CERCA DE LAS 20H20 y es la tercera nacional en 48 horas, después de la Genial/${G('Quaest', 'quaest')} del 02/Set y de la PoderData de este mismo jueves.`,
  'cards.sentimento.text2': `⭐ LAS TRES DISCREPAN EN EL SIGNO DE LA ${G('SEGUNDA VUELTA', 'segundo-turno')} entre los dos primeros: ${TRES}. Los tres márgenes son de 1 o 2 puntos y las tres casas declaran margen de error de 2pp, así que ninguna de ellas afirma ventaja fuera del margen. El panel registra las tres y no elige entre ellas.`,
  'cards.sentimento.text3': `En el precio, un único nombre de los diecinueve del libro presidencial se movió desde la lectura de las 17:28: el segundo colocado, con alza de 0,35pp, hasta 42,85%. El líder sigue en 54,50% y no se mueve hace más de ocho horas. La distancia entre los dos cayó a 11,65pp, contra 12,00pp a las 17:28, 14,85pp el 02/Set y 16,55pp el 01/Set, y se achicó en las cuatro lecturas seguidas.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 42,85% (vol USD 9,64M acumulado), ${S}, alza de 0,35pp y único movimiento del libro en el intervalo. En el contrato de 2º lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 2,00pp y está en 83,50% (vol USD 527 mil). ${DF} lo da en 32% en el escenario con Pablo Marçal y en 33% en el escenario sin él, los mismos números de la ronda de la casa del 21/Ago, y en 44% en una segunda vuelta en que el líder tiene 46%. Usó la crisis en el Supremo para intentar impulsar el acto del 7 de Septiembre, según Folha de S.Paulo.`,
  'cards.sentimento.esquerda': `Lula en 54,50% (vol USD 9,67M acumulado), ${S}, sin variación desde la lectura de las 15:22. En el contrato de 2º lugar de la primera vuelta subió 1,80pp y está en 10,50% (vol USD 439 mil). La Datafolha lo da en 39% y 38% en los dos escenarios de primera vuelta, y gana los tres pares de segunda vuelta con número publicado. ⚠️ PERO LA DISTANCIA DEL PAR PRINCIPAL CAYÓ A LA MITAD DENTRO DE LA PROPIA CASA: 46% a 44%, contra 47% a 43% el 21/Ago. Evaluación del gobierno por la misma casa: 45% aprueban y 51% desaprueban.`,
  'cards.sentimento.terceiraVia': `⭐ LA DATAFOLHA ES LA CUARTA CASA DE PRIMERA LÍNEA EN MEDIR EL SALTO DE AUGUSTO CURY Y LA ÚNICA QUE LO DEJA POR DEBAJO DE DOS DÍGITOS: 7% en el escenario con Marçal y 8% en el escenario sin él, contra 2% en la ronda de la propia casa del 21/Ago. Las otras cuatro lo pusieron en dos dígitos: ${QUATRO}. La dirección es la misma en las cinco; el nivel difiere en tres a cuatro puntos. En el precio cedió 0,10pp en el contrato de ganador, hasta 1,25% (vol USD 3,69M), y subió 3,60pp en el de 3º lugar de la primera vuelta, hasta 59,50% (vol USD 114 mil). ⚠️ Renan Santos tuvo la mayor caída del panel en esta lectura, 4,50pp en el contrato de 3º lugar, hasta 22,00% (vol USD 269 mil), y la distancia entre los dos en ese mercado pasó de 29,40pp a 37,50pp.`,
  'cards.sentimento.polymarket': `Precios de la ${S}. AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20 punto. ⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL CONTRATO DE JUICIO POLÍTICO DE MINISTRO DEL ${G('SUPREMO', 'stf')}, y la última lectura confirmada de él es la del 03/Set a las 17:28, con 7,40%. Tampoco publica precio nuevo para Ronaldo Caiado, Pablo Marçal y Romeu Zema en el contrato de ganador, porque los tres están debajo del piso de 0,5%. El libro presidencial acumula USD 142,61M.`,
  'cards.stf.toffoli': `Sin acto individual nuevo el 03/Set. Sigue como blanco del pedido de juicio político presentado por Renan Santos, junto con Moraes, según G1 y Poder360.`,
  'cards.stf.moraes': `⭐ FUE ÉL QUIEN ACTUÓ, Y ES EL ACTO MÁS DURO DE LA SERIE. Pidió a Edson Fachin investigar a André Mendonça en la investigación de las fake news, con base en un informe que él mismo encargó a la ${G('Policía Federal', 'pf')} sin aval de la presidencia del tribunal, según Gazeta do Povo y O Globo. El Estadão registra que el informe es interno y sin valor probatorio. Marina Silva defendió que se aparte del Supremo, según Metrópoles.`,
  'cards.stf.gilmar': `Propuso la retirada de delegados de la Policía Federal de los despachos del Supremo, según Folha de S.Paulo y Poder360. Delegados de la PF dijeron que él desvía el foco de problemas reales del tribunal, según Gazeta do Povo.`,
  'cards.stf.mendonca': `Se convirtió en blanco del pedido de investigación hecho por Moraes. Presentó facturas de trajes para rebatir la sospecha de un regalo de Daniel Vorcaro, según Gazeta do Povo, y tiene 5 días hábiles para manifestarse. Su informe sobre Moraes sigue previsto para el 7 o el 8 de septiembre.`,
  'cards.stf.nexo': `⭐ LA CRISIS PASÓ DE REACCIÓN A ACTO, Y ENTRE LOS PROPIOS MINISTROS. Edson Fachin dio 5 días hábiles a Moraes, Mendonça, al procurador general Paulo Gonet y al director general de la Policía Federal para prestar informaciones, según G1, VEJA y Folha de S.Paulo, y postergó a la segunda quincena de septiembre la sesión del pleno sobre el caso, según Poder360. El procedimiento se abrió después de que la Procuraduría pidiera la extinción de la petición que reúne las informaciones de la PF sobre autoridades citadas en la investigación del ${G('Banco Master', 'banco-master')}.`,
  'cards.stf.analise': `⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL CONTRATO de salida de ministro del Supremo por juicio político antes de 2027. La última lectura confirmada es la del 03/Set a las 17:28, con 7,40% (vol USD 87 mil), y es esa la que la página mantiene. 📌 EL CONTRASTE CIERRA EL DÍA: la crisis produjo este jueves el acto más duro de la serie, con un ministro pidiendo la investigación de otro, y este es el único contrato del panel sin lectura nueva para publicar. Es también el menor libro del panel, con volumen acumulado que no pasa de USD 87 mil, y la regla de la casa vale siempre aquí: un precio que anda mucho con dinero de poco no describe un cambio de expectativa del mismo tamaño. El contrato mide la salida de un ministro, no mide si la investigación prospera ni si el Senado lleva el pedido al pleno.`,
})

construir('polls-data', 'es', {
  'polls[0].note': `Datafolha nacional divulgada el 03/Set cerca de las 20h20 (Gazeta do Povo, G1, Folha de S.Paulo, Exame, InfoMoney, Valor Econômico). ⭐ ES LA CUARTA CASA DE PRIMERA LÍNEA EN MEDIR EL SALTO DE AUGUSTO CURY Y LA ÚNICA QUE LO DEJA POR DEBAJO DE DOS DÍGITOS: 7% en el escenario con Pablo Marçal y 8% en el escenario sin él, contra 2% en la ronda de la propia casa del 21/Ago. Las otras cuatro casas de la ventana lo pusieron en 10% u 11%: ${QUATRO}. La propia Folha de S.Paulo trató el punto en un análisis bajo el título de que la campaña anuló el efecto Dark Horse y de que él fincó bandera en el electorado de centro. ⭐ Y LA ${G('SEGUNDA VUELTA', 'segundo-turno')} SE ACHICÓ A LA MITAD DENTRO DE LA CASA: 46% a 44% ahora, contra 47% a 43% el 21/Ago, es decir, la distancia cayó de 4 a 2 puntos y pasa a caber en el margen declarado de 2pp. COMPARACIÓN DENTRO DE LA CASA, que es la única válida. En la ${G('primera vuelta', 'primeiro-turno')} con Marçal nada cambió desde el 21/Ago, con Lula en 39% y Flávio en 32% en las dos rondas. En el escenario sin Marçal, Lula cedió de 39% a 38% y Flávio quedó en 33%, así que la distancia entre los dos salió de 6 a 5 puntos. En el mismo intervalo Ronaldo Caiado fue de 5% a 4%, Romeu Zema de 3% a 2% y Renan Santos de 4% a 4% en el escenario con Marçal y de 4% a 3% en el escenario sin él. ESCENARIO CON MARÇAL, completo: Lula 39%, Flávio Bolsonaro 32%, Augusto Cury 7%, Renan Santos 4%, Ronaldo Caiado 4%, Romeu Zema 2%, Pablo Marçal 2%, Samara Martins 1%, y Rui Costa Pimenta, Wilson Grassi, Edmilson Costa, Clariana Barão y Hertz Dias con 0%. Blanco, nulo o ninguno 6%, indecisos 3%. ESCENARIO SIN MARÇAL: Lula 38%, Flávio 33%, Cury 8%, Caiado 4%, Renan 3%, Zema 2%, Samara Martins 1%, Edmilson Costa 1%, Rui Costa Pimenta 1%, y los demás en 0%. Blanco, nulo o ninguno 6%, indecisos 3%. SEGUNDA VUELTA, tres pares con número confirmado: Lula 46% x Flávio 44%, con 9% de blanco o nulo y 2% de no sabe; Lula 46% x Ronaldo Caiado 41%; y Lula 48% x Romeu Zema 39%. ℹ️ La casa probó un CUARTO par, contra Renan Santos, en que el líder también gana, y el panel registra la dirección sin el número porque la tabla consultada trajo rótulo conflictivo en ese bloque. EVALUACIÓN DEL GOBIERNO: 45% aprueban y 51% desaprueban, según G1, Terra, InfoMoney y CBN Recife. Campo del 01 al 03/Set, n=2.002, margen de 2pp, 95% de confianza, registro ${G('TSE', 'tse')} BR-03669/2026. 📅 LA DIVULGACIÓN DE ESTE JUEVES YA ESTABA EN EL REGISTRO DEL TSE ingerido por el panel la mañana del mismo día, con la fecha prevista y el número de registro coincidiendo con lo publicado.`,
  'polls[0].source': `Datafolha, divulgada el 03/Set/2026 (campo del 01 al 03/Set, n=2.002, margen de 2pp, 95% de confianza, registro TSE BR-03669/2026). Tabla de los dos escenarios de primera vuelta y de los escenarios de segunda vuelta verificada en Gazeta do Povo; evaluación del gobierno verificada en G1, Terra, InfoMoney y CBN Recife.`,
  'approvalData.note': `🏷️ LOS NÚMEROS ESTRUCTURADOS DE ESTE BLOQUE SIGUEN SIENDO LOS DE LA GENIAL/QUAEST DEL 02/Set, y son estos: 45% de aprobación contra 48% de desaprobación, con 7% de no sabe, y 35% de excelente o bueno, 25% de regular y 37% de malo o pésimo. El panel mantiene UNA casa por bloque a propósito, y cambiar la casa aquí rompería la serie interna que sostiene la comparación. ⭐ LA DATAFOLHA DEL 03/Set TRAE LECTURA MÁS RECIENTE Y DE OTRA CASA: 45% aprueban y 51% desaprueban, según G1, Terra, InfoMoney y CBN Recife. La aprobación coincide en las dos casas y la desaprobación difiere en 3 puntos, y el panel registra las dos sin sumarlas. ⭐ DENTRO DE LA PROPIA QUAEST EL CUADRO ES DE INMOVILIDAD. El 05/Ago eran 48% de aprobación contra 47% de desaprobación, el 14/Ago 46% contra 48% y el 02/Set 45% contra 48%. 📌 RECHAZO, de la ronda del 02/Set y de la misma casa: Flávio Bolsonaro 55% y Lula 53%, contra 54% y 52% el 14/Ago. En la misma ronda, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28% y Augusto Cury 25%.`,
  'polymarketComparison.note': `Precios del ${G('Polymarket', 'polymarket')} en la ${S}, con el libro presidencial en USD 142,61M. ⭐ LA ${G('DATAFOLHA', 'datafolha')} SALIÓ CERCA DE LAS 20H20 y es la tercera nacional en 48 horas. Las tres discrepan en el SIGNO de la segunda vuelta entre los dos primeros: ${TRES}. ⭐ Y LA DATAFOLHA ES LA CUARTA CASA DE PRIMERA LÍNEA EN MEDIR EL SALTO DE AUGUSTO CURY Y LA ÚNICA QUE LO DEJA POR DEBAJO DE DOS DÍGITOS, con 7% y 8% en los dos escenarios, contra 10% u 11% en las otras cuatro. En el precio, el único nombre del libro presidencial en moverse desde la lectura de las 17:28 fue el segundo colocado, con alza de 0,35pp, y la distancia hacia el líder cayó a 11,65pp. El líder no se mueve hace más de ocho horas. ⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL CONTRATO DE JUICIO POLÍTICO DE MINISTRO DEL SUPREMO: la última lectura confirmada de él es la del 03/Set a las 17:28, con 7,40%. En los submercados, Augusto Cury subió 3,60pp en el contrato de 3º lugar de la primera vuelta y está en 59,50%, y Renan Santos cedió 4,50pp en el mismo mercado, hasta 22,00%.`,
  'polymarketComparison.candidates[0].pesquisaRange': `38-39%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `${DF} lo da en 39% en el escenario con Pablo Marçal y en 38% en el escenario sin él, contra 39% en los dos escenarios de la ronda de la misma casa del 21/Ago. ⭐ EN LA SEGUNDA VUELTA LA DISTANCIA SE ACHICÓ A LA MITAD DENTRO DE LA CASA: 46% a 44% ahora, contra 47% a 43% el 21/Ago, es decir, de 4 a 2 puntos, y pasa a caber en el margen declarado. Gana también a Ronaldo Caiado por 46% a 41% y a Romeu Zema por 48% a 39%. Evaluación del gobierno: 45% aprueban y 51% desaprueban.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `54,50% (vol USD 9,67M), ${S}. Sin variación desde la lectura de las 15:22 de hoy, es decir, su precio no se mueve hace más de ocho horas. La distancia hacia el segundo cayó a 11,65pp, contra 12,00pp a las 17:28, 14,85pp el 02/Set y 16,55pp el 01/Set. En el contrato de 2º lugar de la primera vuelta subió 1,80pp y pasa a 10,50%.`,
  'polymarketComparison.candidates[1].polymarket': `42,85%`,
  'polymarketComparison.candidates[1].pesquisaRange': `32-33%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `La misma Datafolha lo da en 32% en el escenario con Marçal y en 33% en el escenario sin él, los mismos números de la ronda de la casa del 21/Ago. ⭐ EN LA SEGUNDA VUELTA SE ACERCA A 2 PUNTOS, 44% contra 46%, después de 43% contra 47% el 21/Ago. ⚠️ Y LAS TRES NACIONALES DE LA VENTANA DISCREPAN EN EL SIGNO DE ESE PAR: ${TRES}.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `42,85% (vol USD 9,64M), ${S}. Alza de 0,35pp sobre la lectura de las 17:28 de hoy, y fue el único nombre del libro presidencial en moverse en el intervalo. En el contrato de 2º lugar de la primera vuelta cedió 2,00pp y está en 83,50% (vol USD 527 mil).`,
  'polymarketComparison.candidates[2].polymarket': `1,25%`,
  'polymarketComparison.candidates[2].pesquisaRange': `7-8%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `⭐ LA DATAFOLHA ES LA CUARTA CASA DE PRIMERA LÍNEA EN MEDIR EL SALTO Y LA ÚNICA QUE LO DEJA POR DEBAJO DE DOS DÍGITOS: 7% en el escenario con Marçal y 8% en el escenario sin él, contra 2% en la ronda de la propia casa del 21/Ago. Las otras cuatro casas de la ventana lo pusieron en dos dígitos: ${QUATRO}. El salto es el mismo en todas; el nivel es lo que no lo es.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,25% (vol USD 3,69M), ${S}. Caída de 0,10pp en el contrato de ganador. En el contrato de 3º lugar de la primera vuelta subió 3,60pp y pasa a 59,50% (vol USD 114 mil), por tercer día seguido de alza, y en el de 2º lugar cedió 0,70pp, hasta 1,75%.`,
  'polymarketComparison.candidates[3].pesquisaRange': `3-4%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La Datafolha lo da en 4% en el escenario con Marçal y en 3% en el escenario sin él, contra 4% en los dos escenarios de la ronda de la casa del 21/Ago. ⚠️ LA DISPERSIÓN ENTRE CASAS, EN ESTA VENTANA, VA DE 3% A 7,6%: 3% en la Genial/Quaest y en la PoderData, 3% a 4% en la Datafolha, 6% en la Real Time Big Data del 01/Set y 7,6% en la AtlasIntel del 31/Ago. La casa probó una segunda vuelta contra él en que el líder gana, y el panel registra la dirección sin el número.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,75% (vol USD 12,50M), ${S}. Sin variación en el contrato de ganador desde la lectura de las 15:22 de hoy. ⚠️ En el contrato de 3º lugar de la primera vuelta cedió 4,50pp y pasa a 22,00% en un contrato de USD 269 mil, la mayor caída del panel en esta lectura, y la distancia hacia el primero de ese mercado pasó de 29,40pp a 37,50pp.`,
  'polymarketComparison.candidates[4].pesquisaRange': `4%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `La Datafolha lo coloca en 4% en los dos escenarios de primera vuelta, contra 5% en la ronda de la misma casa del 21/Ago. En una segunda vuelta pierde con el líder por 46% a 41%, margen de 5 puntos. ⚠️ EL PAR DE SEGUNDA VUELTA CONTRA ÉL YA TIENE CUATRO LECTURAS EN LA MISMA SEMANA: 45% a 43% a su favor en la Real Time Big Data del 01/Set, 42% a 37% en su contra en la Genial/Quaest del 02/Set, 44% a 42% en su contra en la PoderData del 03/Set y 46% a 41% en su contra en la Datafolha del mismo día.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,25% (vol USD 7,11M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cedió 0,50pp y está en 10,00% (vol USD 112 mil), ${S}.`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `La Datafolha lo trae en 2% en el escenario con él en la lista, el mismo número de la ronda de la casa del 21/Ago. Su presencia separa los dos escenarios de la casa: con Marçal el líder tiene 39% y el segundo 32%, y sin Marçal el líder tiene 38% y el segundo 33%, es decir, la distancia entre los dos va de 7 a 5 puntos.`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La Datafolha lo mide en 2% en los dos escenarios de primera vuelta, contra 3% en la ronda de la misma casa del 21/Ago. En una segunda vuelta pierde con el líder por 48% a 39%, margen de 9 puntos. Las cuatro casas de la semana midieron ese par en 3, 11, 2 y 9 puntos, y es el par con la mayor dispersión entre casas de la ventana.`,
})
