/** Mapa EN da rodada de fechamento de 03/Set/2026, carimbo 23:45. Ponto decimal. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 03/Sep, 23:45 BRT (04/Sep, 02:45 UTC)'
const DF = 'the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp)'
const THREE = 'Genial/Quaest of 02/Sep put the leader ahead by 42% to 41%, PoderData of 03/Sep put the runner-up ahead by 45% to 44%, and Datafolha of 03/Sep puts the leader ahead by 46% to 44%'
const FOUR = 'BTG/Nexus 11% on 31/Aug, Real Time Big Data 11% on 01/Sep, Genial/Quaest 10% on 02/Sep and PoderData 10% on 03/Sep'
const FIVE = 'BTG/Nexus 11% on 31/Aug, Real Time Big Data 11% on 01/Sep, Genial/Quaest 10% on 02/Sep, PoderData 10% on 03/Sep and Datafolha 7% and 8% across its two scenarios the same day'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 142.61M and the price on this page is from the ${S}. ⭐ ${G('DATAFOLHA', 'datafolha')} CAME OUT AROUND 20:20 and is the third national poll in 48 hours, after Genial/${G('Quaest', 'quaest')} of 02/Sep and PoderData earlier this same Thursday.`,
  'cards.sentimento.text2': `⭐ ALL THREE DISAGREE ON THE SIGN OF THE ${G('SECOND ROUND', 'segundo-turno')} between the top two: ${THREE}. All three margins are 1 or 2 points and all three houses declare a margin of error of 2pp, so none of them asserts a lead outside the margin. The panel records all three and does not choose between them.`,
  'cards.sentimento.text3': `In the price, a single name out of the presidential book's nineteen moved since the 17:28 reading: the runner-up, up 0.35pp to 42.85%. The leader is still at 54.50% and has not moved for more than eight hours. The gap between the two fell to 11.65pp, against 12.00pp at 17:28, 14.85pp on 02/Sep and 16.55pp on 01/Sep, narrowing across four consecutive readings.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 42.85% (vol USD 9.64M accumulated), ${S}, up 0.35pp and the only move in the book over the interval. In the ${G('first round', 'primeiro-turno')} runner-up contract he gave up 2.00pp and stands at 83.50% (vol USD 527 thousand). ${DF} gives him 32% in the scenario with Pablo Marçal and 33% in the one without, the same figures as the house's round of 21/Aug, and 44% in a second round in which the leader has 46%. He used the crisis at the Supreme Court to try to build momentum for the 7 September rally, according to Folha de S.Paulo.`,
  'cards.sentimento.esquerda': `Lula at 54.50% (vol USD 9.67M accumulated), ${S}, unchanged since the 15:22 reading. In the first-round runner-up contract he rose 1.80pp and stands at 10.50% (vol USD 439 thousand). Datafolha gives him 39% and 38% across the two first-round scenarios, and he wins the three second-round pairings with published figures. ⚠️ BUT THE GAP IN THE MAIN PAIRING HALVED WITHIN THE HOUSE ITSELF: 46% to 44%, against 47% to 43% on 21/Aug. Government approval from the same house: 45% approve and 51% disapprove.`,
  'cards.sentimento.terceiraVia': `⭐ DATAFOLHA IS THE FOURTH TOP-TIER HOUSE TO MEASURE AUGUSTO CURY'S JUMP AND THE ONLY ONE THAT LEAVES HIM BELOW DOUBLE DIGITS: 7% in the scenario with Marçal and 8% in the one without, against 2% in the house's own round of 21/Aug. The other four put him in double digits: ${FOUR}. The direction is the same across all five; the level differs by three to four points. In the price he gave up 0.10pp in the winner contract, to 1.25% (vol USD 3.69M), and rose 3.60pp in the first-round third-place contract, to 59.50% (vol USD 114 thousand). ⚠️ Renan Santos had the panel's largest fall in this reading, 4.50pp in the third-place contract, to 22.00% (vol USD 269 thousand), and the gap between the two in that market went from 29.40pp to 37.50pp.`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 point. ⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE ${G('SUPREME COURT', 'stf')} IMPEACHMENT CONTRACT, and its last confirmed reading is the 03/Sep one at 17:28, at 7.40%. It also publishes no new price for Ronaldo Caiado, Pablo Marçal and Romeu Zema in the winner contract, because all three sit below the 0.5% floor. The presidential book has accumulated USD 142.61M.`,
  'cards.stf.toffoli': `No new individual action on 03/Sep. He remains a target of the impeachment request filed by Renan Santos, alongside Moraes, according to G1 and Poder360.`,
  'cards.stf.moraes': `⭐ HE IS THE ONE WHO ACTED, AND IT IS THE HARSHEST ACT IN THE SERIES. He asked Edson Fachin to investigate André Mendonça in the fake news inquiry, based on a report he himself commissioned from the ${G('Federal Police', 'pf')} without the court presidency's approval, according to Gazeta do Povo and O Globo. Estadão records the report as internal and without evidentiary value. Marina Silva argued that he should step aside from the court, according to Metrópoles.`,
  'cards.stf.gilmar': `He proposed removing Federal Police officers from Supreme Court chambers, according to Folha de S.Paulo and Poder360. Federal Police officers said he is diverting attention from the court's real problems, according to Gazeta do Povo.`,
  'cards.stf.mendonca': `He became the target of the investigation request made by Moraes. He produced tailor's receipts to rebut the suspicion of a gift from Daniel Vorcaro, according to Gazeta do Povo, and has five working days to respond. His report on Moraes is still expected on 7 or 8 September.`,
  'cards.stf.nexo': `⭐ THE CRISIS MOVED FROM REACTION TO ACTION, AND BETWEEN THE JUSTICES THEMSELVES. Edson Fachin gave five working days to Moraes, Mendonça, prosecutor general Paulo Gonet and the Federal Police director general to provide information, according to G1, VEJA and Folha de S.Paulo, and postponed to the second half of September the full court session on the case, according to Poder360. The procedure was opened after the Prosecutor General's Office asked for the dismissal of the petition holding the Federal Police material on officials named in the ${G('Banco Master', 'banco-master')} investigation.`,
  'cards.stf.analise': `⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE CONTRACT on a Supreme Court justice leaving through impeachment before 2027. The last confirmed reading is the 03/Sep one at 17:28, at 7.40% (vol USD 87 thousand), and that is the one the page keeps. 📌 THE CONTRAST CLOSES THE DAY: the crisis produced this Thursday the harshest act in the series, with one justice asking for another to be investigated, and this is the only contract on the panel with no new reading to publish. It is also the smallest book on the panel, with accumulated volume that does not exceed USD 87 thousand, and the house rule always applies here: a price that moves a lot on very little money does not describe a shift in expectations of the same size. The contract measures a justice leaving, not whether the investigation goes anywhere nor whether the Senate takes up the request.`,
})

construir('polls-data', 'en', {
  'polls[0].note': `Datafolha national poll released on 03/Sep around 20:20 (Gazeta do Povo, G1, Folha de S.Paulo, Exame, InfoMoney, Valor Econômico). ⭐ IT IS THE FOURTH TOP-TIER HOUSE TO MEASURE AUGUSTO CURY'S JUMP AND THE ONLY ONE THAT LEAVES HIM BELOW DOUBLE DIGITS: 7% in the scenario with Pablo Marçal and 8% in the one without, against 2% in the house's own round of 21/Aug. The other four houses in the window put him at 10% or 11%: ${FOUR}. Folha de S.Paulo itself covered the point in an analysis headlined on the idea that the campaign wiped out the Dark Horse effect and that he planted his flag with centrist voters. ⭐ AND THE ${G('SECOND ROUND', 'segundo-turno')} HALVED WITHIN THE HOUSE: 46% to 44% now, against 47% to 43% on 21/Aug, meaning the gap fell from 4 to 2 points and now fits inside the declared margin of 2pp. COMPARISON WITHIN THE HOUSE, which is the only valid one. In the ${G('first round', 'primeiro-turno')} with Marçal nothing changed since 21/Aug, with Lula at 39% and Flávio at 32% in both rounds. In the scenario without Marçal, Lula gave up from 39% to 38% and Flávio held at 33%, so the gap between the two went from 6 to 5 points. Over the same interval Ronaldo Caiado went from 5% to 4%, Romeu Zema from 3% to 2% and Renan Santos from 4% to 4% in the scenario with Marçal and from 4% to 3% in the one without. SCENARIO WITH MARÇAL, in full: Lula 39%, Flávio Bolsonaro 32%, Augusto Cury 7%, Renan Santos 4%, Ronaldo Caiado 4%, Romeu Zema 2%, Pablo Marçal 2%, Samara Martins 1%, and Rui Costa Pimenta, Wilson Grassi, Edmilson Costa, Clariana Barão and Hertz Dias at 0%. Blank, spoiled or none 6%, undecided 3%. SCENARIO WITHOUT MARÇAL: Lula 38%, Flávio 33%, Cury 8%, Caiado 4%, Renan 3%, Zema 2%, Samara Martins 1%, Edmilson Costa 1%, Rui Costa Pimenta 1%, and the rest at 0%. Blank, spoiled or none 6%, undecided 3%. SECOND ROUND, three pairings with confirmed figures: Lula 46% to Flávio 44%, with 9% blank or spoiled and 2% don't know; Lula 46% to Ronaldo Caiado 41%; and Lula 48% to Romeu Zema 39%. ℹ️ The house tested a FOURTH pairing, against Renan Santos, in which the leader also wins, and the panel records the direction without the figure because the table consulted carried a conflicting label in that block. GOVERNMENT APPROVAL: 45% approve and 51% disapprove, according to G1, Terra, InfoMoney and CBN Recife. Field 01 to 03/Sep, n=2,002, margin of 2pp, 95% confidence, ${G('TSE', 'tse')} registration BR-03669/2026. 📅 THIS THURSDAY'S RELEASE WAS ALREADY ON THE TSE REGISTER ingested by the panel that same morning, with the scheduled date and the registration number matching what was published.`,
  'polls[0].source': `Datafolha, released on 03/Sep/2026 (field 01 to 03/Sep, n=2,002, margin of 2pp, 95% confidence, TSE registration BR-03669/2026). Table of the two first-round scenarios and of the second-round scenarios checked in Gazeta do Povo; government approval checked in G1, Terra, InfoMoney and CBN Recife.`,
  'approvalData.note': `🏷️ THE STRUCTURED FIGURES IN THIS BLOCK ARE STILL THE GENIAL/QUAEST ONES OF 02/Sep, and they are these: 45% approval against 48% disapproval, with 7% don't know, and 35% excellent or good, 25% fair and 37% poor or very poor. The panel deliberately keeps ONE house per block, and switching the house here would break the internal series that supports the comparison. ⭐ DATAFOLHA OF 03/Sep BRINGS A FRESHER READING FROM A DIFFERENT HOUSE: 45% approve and 51% disapprove, according to G1, Terra, InfoMoney and CBN Recife. Approval matches across the two houses and disapproval differs by 3 points, and the panel records both without adding them up. ⭐ WITHIN QUAEST ITSELF THE PICTURE IS ONE OF STILLNESS. On 05/Aug it was 48% approval against 47% disapproval, on 14/Aug 46% against 48% and on 02/Sep 45% against 48%. 📌 REJECTION, from the 02/Sep round and the same house: Flávio Bolsonaro 55% and Lula 53%, against 54% and 52% on 14/Aug. In the same round, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28% and Augusto Cury 25%.`,
  'polymarketComparison.note': `${G('Polymarket', 'polymarket')} prices from the ${S}, with the presidential book at USD 142.61M. ⭐ ${G('DATAFOLHA', 'datafolha')} CAME OUT AROUND 20:20 and is the third national poll in 48 hours. All three disagree on the SIGN of the second round between the top two: ${THREE}. ⭐ AND DATAFOLHA IS THE FOURTH TOP-TIER HOUSE TO MEASURE AUGUSTO CURY'S JUMP AND THE ONLY ONE THAT LEAVES HIM BELOW DOUBLE DIGITS, at 7% and 8% across its two scenarios, against 10% or 11% at the other four. In the price, the only name in the presidential book to move since the 17:28 reading was the runner-up, up 0.35pp, and the gap to the leader fell to 11.65pp. The leader has not moved for more than eight hours. ⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE SUPREME COURT IMPEACHMENT CONTRACT: its last confirmed reading is the 03/Sep one at 17:28, at 7.40%. In the side markets, Augusto Cury rose 3.60pp in the first-round third-place contract and stands at 59.50%, and Renan Santos gave up 4.50pp in the same market, to 22.00%.`,
  'polymarketComparison.candidates[0].pesquisaRange': `38-39%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `${DF} gives him 39% in the scenario with Pablo Marçal and 38% in the one without, against 39% in both scenarios of the house's round of 21/Aug. ⭐ IN THE SECOND ROUND THE GAP HALVED WITHIN THE HOUSE: 46% to 44% now, against 47% to 43% on 21/Aug, that is, from 4 to 2 points, and it now fits inside the declared margin. He also beats Ronaldo Caiado by 46% to 41% and Romeu Zema by 48% to 39%. Government approval: 45% approve and 51% disapprove.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `54.50% (vol USD 9.67M), ${S}. Unchanged since today's 15:22 reading, meaning his price has not moved for more than eight hours. The gap to the runner-up fell to 11.65pp, against 12.00pp at 17:28, 14.85pp on 02/Sep and 16.55pp on 01/Sep. In the first-round runner-up contract he rose 1.80pp to 10.50%.`,
  'polymarketComparison.candidates[1].polymarket': `42.85%`,
  'polymarketComparison.candidates[1].pesquisaRange': `32-33%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `The same Datafolha poll gives him 32% in the scenario with Marçal and 33% in the one without, the same figures as the house's round of 21/Aug. ⭐ IN THE SECOND ROUND HE CLOSES TO 2 POINTS, 44% against 46%, after 43% against 47% on 21/Aug. ⚠️ AND THE THREE NATIONAL POLLS IN THE WINDOW DISAGREE ON THE SIGN OF THAT PAIRING: ${THREE}.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `42.85% (vol USD 9.64M), ${S}. Up 0.35pp on today's 17:28 reading, and it was the only name in the presidential book to move over the interval. In the first-round runner-up contract he gave up 2.00pp and stands at 83.50% (vol USD 527 thousand).`,
  'polymarketComparison.candidates[2].polymarket': `1.25%`,
  'polymarketComparison.candidates[2].pesquisaRange': `7-8%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `⭐ DATAFOLHA IS THE FOURTH TOP-TIER HOUSE TO MEASURE THE JUMP AND THE ONLY ONE THAT LEAVES HIM BELOW DOUBLE DIGITS: 7% in the scenario with Marçal and 8% in the one without, against 2% in the house's own round of 21/Aug. The other four houses in the window put him in double digits: ${FOUR}. The jump is the same in all of them; the level is what is not.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.25% (vol USD 3.69M), ${S}. Down 0.10pp in the winner contract. In the first-round third-place contract he rose 3.60pp to 59.50% (vol USD 114 thousand), a third straight day of gains, and in the runner-up contract he gave up 0.70pp, to 1.75%.`,
  'polymarketComparison.candidates[3].pesquisaRange': `3-4%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `Datafolha gives him 4% in the scenario with Marçal and 3% in the one without, against 4% in both scenarios of the house's round of 21/Aug. ⚠️ THE SPREAD BETWEEN HOUSES, IN THIS WINDOW, RUNS FROM 3% TO 7.6%: 3% at Genial/Quaest and PoderData, 3% to 4% at Datafolha, 6% at Real Time Big Data on 01/Sep and 7.6% at AtlasIntel on 31/Aug. The house tested a second round against him in which the leader wins, and the panel records the direction without the figure.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.75% (vol USD 12.50M), ${S}. Unchanged in the winner contract since today's 15:22 reading. ⚠️ In the first-round third-place contract he gave up 4.50pp to 22.00% in a contract of USD 269 thousand, the panel's largest fall in this reading, and the gap to that market's leader went from 29.40pp to 37.50pp.`,
  'polymarketComparison.candidates[4].pesquisaRange': `4%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `Datafolha puts him at 4% in both first-round scenarios, against 5% in the same house's round of 21/Aug. In a second round he loses to the leader by 46% to 41%, a margin of 5 points. ⚠️ THE SECOND-ROUND PAIRING AGAINST HIM ALREADY HAS FOUR READINGS IN THE SAME WEEK: 45% to 43% in his favour at Real Time Big Data on 01/Sep, 42% to 37% against him at Genial/Quaest on 02/Sep, 44% to 42% against him at PoderData on 03/Sep and 46% to 41% against him at Datafolha the same day.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.25% (vol USD 7.11M) in the WINNER contract, below the 0.5% floor of the double reading, and this round does not publish a new price for him in that contract. In the first-round THIRD-PLACE contract, which is a different market, he gave up 0.50pp and stands at 10.00% (vol USD 112 thousand), ${S}.`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `Datafolha brings him at 2% in the scenario with him on the list, the same figure as the house's round of 21/Aug. His presence is what separates the house's two scenarios: with Marçal the leader has 39% and the runner-up 32%, and without Marçal the leader has 38% and the runner-up 33%, meaning the gap between the two goes from 7 to 5 points.`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `Datafolha measures him at 2% in both first-round scenarios, against 3% in the same house's round of 21/Aug. In a second round he loses to the leader by 48% to 39%, a margin of 9 points. The week's four houses measured that pairing at 3, 11, 2 and 9 points, and it is the pairing with the widest spread between houses in the window.`,
})
