/** Mapa EN, 2a rodada de 03/Set/2026: analysis-data. Ponto decimal. Tudo ou nada. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 03/Sep, 17:28 BRT (20:28 UTC)'
const PD = 'the PoderData poll of 03/Sep (BR-07561/2026, field 30/Aug to 02/Sep, n=3,000, margin of 2pp)'
const FOUR =
  'BTG/Nexus on 31/Aug at 11%, against 2% in the same house’s round of 24/Aug; Real Time Big Data on 01/Sep at 11%; Genial/Quaest on 02/Sep at 10%, against 2% on 14/Aug and 1% on 05/Aug; and PoderData on 03/Sep at 10%, against 4% on 27/Aug'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 142.36M and the price on this page is from the ${S}. There has been no new national poll since the 15:22 reading: PoderData is still the only one with published figures this Thursday, and ${G('Datafolha', 'datafolha')} (BR-03669/2026, n=2,002, field 01 to 03/Sep), which was scheduled for release today on the ${G('TSE', 'tse')} register, still had no figures at the time of this reading.`,
  'cards.sentimento.text2': `⭐ A SINGLE CONTRACT MOVED IN TWO HOURS, AND IT MOVED 2.15pp. The runner-up went from 40.35% to 42.50%, and the other eighteen contracts in the presidential book stayed flat, the leader included, who is still at 54.50%. The gap between the two fell to 12.00pp, against 14.15pp in today's 15:22 reading, 14.85pp on 02/Sep and 16.55pp on 01/Sep.`,
  'cards.sentimento.text3': `⚠️ AND THE MONEY BEHIND THAT MOVE IS SMALL. Between today's two readings the runner-up's contract took in about USD 5.8 thousand of new business, and the leader's took in about USD 7.0 thousand without moving. The entire presidential book grew by USD 10 thousand, on USD 142.36M accumulated. Because the runner-up rose and no other name gave ground, the sum of the YES legs went from 99.20% to 101.35%. The house rule applies here exactly as it already does to the ${G('Supreme Court', 'stf')} contract: a price that moves a lot on very little money does not describe a shift in expectations of the same size.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 42.50% (vol USD 9.59M accumulated) in the presidential book, ${S}, up 2.15pp on today's 15:22 reading, and it is the only move in the book across the two hours between the readings. In the ${G('first round', 'primeiro-turno')} runner-up contract he is still flat at 85.50% (vol USD 519 thousand). ${PD} gives him 34% in the first round and 45% in a ${G('second round', 'segundo-turno')} against the leader, who has 44%. The stock exchange rose 3.06% on 02/Sep after the Genial/${G('Quaest', 'quaest')} release, according to Metrópoles, and the panel records the sequence without assigning it a cause.`,
  'cards.sentimento.esquerda': `Lula at 54.50% (vol USD 9.63M accumulated), ${S}, unchanged since today's 15:22 reading, and his contract took in about USD 7.0 thousand of new business over that stretch without moving. In the first-round runner-up contract he gave up 0.05pp and stands at 8.70% (vol USD 437 thousand). PoderData gives him 37% in the first round and 44% in a second round in which the runner-up has 45%, and he wins the other three pairings the house tested. He declared the ${G('INSS', 'inss')} queue cleared at a ceremony at the Planalto Palace, using the definition given by the social security minister, with 261 thousand requests past 45 days still open in August, according to Metrópoles and Poder360.`,
  'cards.sentimento.terceiraVia': `🔴 CORRECTION OF THE 15:22 READING: Augusto Cury's jump into double digits was not measured by two houses, it was measured by FOUR, and the first is not Genial/Quaest. In the panel's base: ${FOUR}. AtlasIntel on 31/Aug measured him at 7.8%. The jump began on 31/Aug, not this Thursday. In the price he has not moved since the 15:22 reading: 1.35% (vol USD 3.64M) in the winner contract and 55.90% (vol USD 108 thousand) in the first-round third-place contract, where he rose 0.05pp. Renan Santos is still at 1.75% (vol USD 12.48M) in the winner contract and gave up 0.50pp in the third-place contract, where he stands at 26.50%. Ronaldo Caiado is still below the 0.5% floor in the winner contract and gave up 0.50pp in the third-place contract, where he stands at 10.50% (vol USD 111 thousand).`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 point. This round does not publish a new price for Ronaldo Caiado, Pablo Marçal or Romeu Zema in the winner contract, because all three sit below the 0.5% floor. The presidential book has accumulated USD 142.36M.`,

  'cards.inss.text1': `THE ${G('INSS', 'inss')} CEREMONY WAS THIS THURSDAY, at 3pm at the Planalto Palace, and what this round adds is the DEFINITION the government uses. According to the social security minister, quoted by Metrópoles: the queue counts as cleared when fewer people are waiting than the number who filed requests the previous month, and that happened in August 2026.`,
  'cards.inss.text2': `⚠️ WHAT FALLS OUTSIDE THAT COUNT HAS A NUMBER. Requests running more than 45 days late totalled 261 thousand in August, against 1.88 million in January, a fall of 86%. Open applications dropped to 1.2 million, against roughly 3 million at the start of the year, a fall of 59%. Average review time stands at 35 days. Figures from Metrópoles and Poder360.`,
  'cards.inss.text3': `📌 THIS PAGE'S 15:22 READING DESCRIBED THE CRITERION DIFFERENTLY, as an application inside the legal review deadline, and the definition above is the one the minister himself gave. The panel swaps its wording for the minister's, with attribution, and does not arbitrate between the two. On the same Thursday the lower house approved a provisional measure to speed up INSS benefit reviews, according to Metrópoles.`,
  'cards.inss.conclusao': `What this round measures is narrow, and it is worth recording as such: in two hours the news agenda did not change, and a single contract in the presidential book moved. The panel does not attribute that move to the INSS ceremony or to the Supreme Court news, and records that it came with about USD 5.8 thousand of new business.`,

  'cards.bancoMaster.text1': `TODAY'S NEW PLEA DEAL IS STILL THE ONE WITH ANTONIO CARLOS FREIXO JÚNIOR, owner of Entre Investimentos, the first cooperation deal tied directly to the Dark Horse case, according to Folha de S.Paulo and O Globo. ⚠️ THE AGREEMENT IS CLOSED AND NOT YET RATIFIED: the next step is sending it to the reporting justice.`,
  'cards.bancoMaster.text2': `THE REAG FOUNDER'S PLEA DEAL, João Carlos Mansur's, is from 2 September and ADVANCED at the court this Thursday, according to Metrópoles. It was signed by the Prosecutor General's Office and sent to Justice André Mendonça's chambers, and the proposal had been submitted on 26 August. Mendonça still has to schedule a hearing and decide whether to ratify it, and without ratification the agreement does not count as evidence.`,
  'cards.bancoMaster.text3': `⚠️ AND THERE ARE TWO ACCOUNTS OF PRESSURE, BOTH ON THE RECORD. Daniel Vorcaro said in his testimony that he was pressured not to implicate a ${G('Federal Police', 'pf')} director and members of the government, according to Gazeta do Povo, and before that that he received threats while negotiating the plea deal, according to O Globo. The Prosecutor General's Office asked on 02/Sep for that complaint to be SHELVED, saying he presented no evidence, according to Folha de S.Paulo, O Globo and G1. The panel records both and does not arbitrate.`,
  'cards.bancoMaster.conclusao': `The chronology is the information, and it has seven distinct dates: the meeting between the justice and the businessman is from 14 March 2025; the messages are from 16 November 2025; the arrest is from 17 November 2025; the Federal Police report was delivered on 27 August 2026, the same day as the testimony taken without the Federal Police; secrecy was lifted on 1 September; the Reag founder's plea deal was signed on 2 September and went for ratification; and the plea deal with the businessman tied to Dark Horse was closed on 3 September. ⚠️ NEITHER PLEA DEAL HAS BEEN RATIFIED. And what has not happened yet is still scheduled: Mendonça's report on Moraes is expected on 7 or 8 September, according to Poder360.`,

  'cards.stf.moraes': `STILL THE NAME OF THE DAY, AND AGAIN NOT THROUGH ANY ACTION OF HIS OWN. The Paraná bar association asked for his removal from the case and for the prosecutor general to be recused, according to Folha de S.Paulo. Ronaldo Caiado argued for his removal and for impeachment in the Senate, according to Valor Econômico. Renan Santos said his rulings should not be recognised, according to Poder360.`,
  'cards.stf.gilmar': `HE PROPOSED REMOVING FEDERAL POLICE OFFICERS FROM SUPREME COURT CHAMBERS, according to Folha de S.Paulo and Poder360, a measure that responds directly to the testimony taken in Mendonça's chambers without the Federal Police. In a meeting with Lula, he instructed the Federal Police to push back against orders from Mendonça when it considers them unlawful, according to Estadão.`,
  'cards.stf.mendonca': `He received from the Prosecutor General's Office the Reag founder's plea agreement so he can rule on ratification, and the case advanced at the court this Thursday, according to Poder360, G1 and Metrópoles. He is the one who schedules the hearing with the cooperating witness and decides whether the agreement counts as evidence. Poder360 reported that the institute linked to him held 55 contracts with public bodies. He spoke of honouring the people's trust in a speech to religious leaders about the elections, according to Estadão. His report on Moraes is still expected on 7 or 8 September.`,
  'cards.stf.nexo': `THE CRISIS HAS STARTED PRODUCING PROPOSED RULES, NOT JUST REACTIONS. Gilmar Mendes proposed removing Federal Police officers from the court's chambers, Chief Justice Edson Fachin continued his talks with the other justices and said that disagreeing is not the same as hating, and Lula met with Fachin and with Gilmar, according to Poder360, Folha de S.Paulo, Estadão and Pleno.News. Cristiano Zanin was elected to a second term as a substitute justice on the electoral court, according to CartaCapital.`,
  'cards.stf.analise': `The contract on a Supreme Court justice leaving through impeachment before 2027 stands at 7.40% (vol USD 87 thousand) in the ${S}, unchanged since today's 15:22 reading. ⚠️ IT IS THE SMALLEST BOOK ON THE PANEL and accumulated volume is still USD 87 thousand. Over three days the contract went to 10.85%, fell to 6.35% and rose to 7.40%, and the entire book traded since it opened fits into less than one hundredth of the presidential book. A price that moves a lot on very little money does not describe a shift in expectations of the same size. The contract measures a justice leaving, not whether the investigation goes anywhere nor whether the Senate takes up the request.`,
})
