/** Mapa ES de 03/Set/2026: analysis-criteriosa. Vírgula decimal, ponto de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 03/Set, 15:22 BRT (18:22 UTC)'
const PD = 'la PoderData del 03/Set (BR-07561/2026, campo del 30/Ago al 02/Set, n=3.000, margen de 2pp)'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 3 de septiembre de 2026: precio del ${G('Polymarket', 'polymarket')} en ${S}, libro presidencial en USD 142,35M, contra ${PD}, la única nacional con números publicados este jueves. Su divulgación ya constaba en el registro del ${G('TSE', 'tse')} que el panel ingirió esa misma mañana. ⭐ INVIERTE LA ${G('SEGUNDA VUELTA', 'segundo-turno')} DENTRO DE LA PROPIA CASA: Flávio Bolsonaro 45% y Lula 44%, después de Lula 46% a 45% el 13/Ago y Lula 45% a 44% el 27/Ago. ⚠️ Y LA CASA DE LA VÍSPERA MIDIÓ LO CONTRARIO en el mismo par: la Genial/${G('Quaest', 'quaest')} del 02/Set, con campo superpuesto, dio a Lula adelante por 42% a 41%. Otras dos nacionales tenían divulgación marcada para este jueves en el registro del TSE, la ${G('Datafolha', 'datafolha')} y la 100 Cidades, y ninguna de las dos tenía números publicados al momento de esta lectura.`,

  cruzamento: `El 3 de septiembre es la ronda en que dos casas midieron semanas casi idénticas y discreparon sobre quién gana la segunda vuelta entre los dos primeros. En el voto declarado, ${PD} da a Flávio Bolsonaro en 45% y a Lula en 44%, con 8% de blanco o nulo y 3% de no sabe. En las dos rondas anteriores de la misma casa era el líder adelante, por 46% a 45% el 13/Ago y por 45% a 44% el 27/Ago, y esta es la primera de las tres rondas de esta casa desde el 13/Ago en que el segundo aparece numéricamente adelante en ese par. La distancia es de 1 punto y el margen declarado es de 2pp, es decir, ${G('empate técnico', 'empate-tecnico')} según la regla de la propia casa. La Genial/Quaest del 02/Set, con campo del 30/Ago al 01/Set que se superpone casi entero a este, midió el mismo par al revés, 42% a 41% a favor del líder, también con 1 punto de distancia. El panel registra las dos lecturas y no elige entre ellas: lo que la semana muestra es que el par de los dos primeros ya no tiene señal estable entre casas. En la ${G('primera vuelta', 'primeiro-turno')} la PoderData da 37% al líder y 34% al segundo, y dentro de la propia casa la distancia pasó de 6pp el 13/Ago a 3pp el 27/Ago y quedó en 3pp ahora. El salto de Augusto Cury se confirma en una segunda casa: 4% el 27/Ago y 10% ahora en la PoderData, contra 2% el 14/Ago y 10% el 02/Set en la Quaest. Son dos institutos independientes midiendo la misma dirección dentro de sus propias series. La segunda vuelta contra Ronaldo Caiado ya tiene tres resultados distintos en la misma semana, todos con campo superpuesto: la PoderData da al líder adelante por 44% a 42%, la Quaest dio 42% a 37% y la Real Time Big Data del 01/Set daba a Caiado adelante por 45% a 43%. En el precio, el hecho del día es que los dos primeros cayeron juntos, algo que no ocurría en la ronda anterior. El líder cedió 1,00pp y está en 54,50%, después de cinco días parado, y el segundo cedió 0,30pp y está en 40,35%. La distancia entre ellos se achicó por segundo día seguido, de 16,55pp el 01/Set a 14,85pp el 02/Set y 14,15pp ahora, pero por un motivo distinto al de ayer: ayer subió el segundo, hoy el líder cayó más. La suma de las puntas SÍ del libro presidencial está en 99,20%, es decir, el precio que salió de los dos primeros no reapareció en otro nombre. Augusto Cury sigue siendo el caso más claro de contratos distintos respondiendo preguntas distintas: en el contrato de ganador cayó 0,25pp y está en 1,35%, y en el de 3º lugar de la primera vuelta subió 3,45pp y pasa a 55,85% por segundo día seguido de alza. El contrato de salida de ministro del Supremo por juicio político antes de 2027 subió 1,05pp y está en 7,40%, tercera dirección seguida en tres días después de 10,85% y 6,35%, con el volumen acumulado parado en USD 87 mil. Un precio que anda mucho con dinero de poco no describe un cambio de expectativa del mismo tamaño.`,

  // ── Lula ──
  'candidates[0].header': `PRECIO: 54,50% (vol USD 9,63M acumulado), ${S}. Caída de 1,00pp, después de cinco días parado en 55,50%. ENCUESTA: ${PD} lo da en 37% en la primera vuelta y en 44% en una segunda vuelta en que el segundo colocado tiene 45%. Gana los otros tres pares probados por la casa: 44% a 42% contra Ronaldo Caiado, 44% a 42% contra Romeu Zema y 44% a 39% contra Renan Santos.`,
  'candidates[0].fortes[0]': `Sigue adelante en la primera vuelta, con 37% contra 34% del segundo, y la distancia de 3 puntos es la misma que la propia PoderData midió el 27/Ago.`,
  'candidates[0].fortes[1]': `Gana tres de los cuatro pares de segunda vuelta probados por la casa, y en dos de ellos por 2 puntos y en uno por 5.`,
  'candidates[0].fortes[2]': `En el contrato de 2º lugar de la primera vuelta subió 0,75pp y pasa a 8,75%, en un contrato de USD 437 mil.`,
  'candidates[0].fortes[3]': `La caída de su precio en esta ronda vino junto con la del segundo colocado, y no con un alza del adversario como la víspera.`,
  'candidates[0].fortes[4]': `Hizo este jueves, a las 15h en el Planalto, la ceremonia en que declaró en cero la fila del ${G('INSS', 'inss')}, según Poder360.`,
  'candidates[0].fracos[0]': `⚠️ POR PRIMERA VEZ EN LAS TRES RONDAS DE ESTA CASA DESDE EL 13/Ago aparece atrás en la segunda vuelta contra el segundo colocado, 44% a 45%, después de 46% a 45% el 13/Ago y 45% a 44% el 27/Ago.`,
  'candidates[0].fracos[1]': `En el precio cedió 1,00pp y está en 54,50%, cerrando la secuencia de cinco días sin variación.`,
  'candidates[0].fracos[2]': `En la primera vuelta cedió dentro de la propia casa por segunda ronda seguida, de 41% el 13/Ago a 38% el 27/Ago y 37% ahora.`,
  'candidates[0].fracos[3]': `La ceremonia del INSS usa un criterio declarado que angosta el significado del anuncio: la fila se considera en cero cuando las solicitudes dentro del plazo legal de análisis dejan de contar como pendientes, y la cuenta no incluye a quien espera fuera de ese criterio, según O Globo.`,
  'candidates[0].fracos[4]': `La lectura de evaluación de gobierno sigue siendo la de la Quaest del 02/Set, con 45% de aprobación contra 48% de desaprobación, porque la PoderData no publicó evaluación en la tabla verificada.`,
  'candidates[0].analise': `El jueves trajo una nacional con números publicados, y mide casi la misma semana que la nacional del miércoles, con un día de desplazamiento. En la primera vuelta su cuadro cede otra vez dentro de la propia casa, de 38% a 37%, y la distancia hacia el segundo queda parada en 3 puntos. Lo que cambia de verdad es la segunda vuelta: por primera vez en las tres rondas de esta casa desde el 13/Ago aparece atrás, 44% a 45%. La casa de la víspera midió el mismo par al revés, 42% a 41% a su favor, y las dos distancias son de 1 punto contra un margen declarado de 2pp. El panel no dice cuál de las dos está bien: registra que el par que decide la elección ya no tiene señal estable entre casas. En el precio, su movimiento fue de caída por primera vez en seis días, y la distancia hacia el segundo se achicó incluso con el segundo también cayendo, porque él cayó más.`,

  // ── Flávio ──
  'candidates[1].header': `PRECIO: 40,35% (vol USD 9,59M acumulado), ${S}. Caída de 0,30pp, el mismo día en que el líder también cayó, y la distancia entre los dos pasó de 14,85pp a 14,15pp. ENCUESTA: ${PD} lo da en 34% en la primera vuelta y en 45% en una segunda vuelta contra el líder, que tiene 44%.`,
  'candidates[1].fortes[0]': `⭐ EN LA SEGUNDA VUELTA APARECE NUMÉRICAMENTE ADELANTE POR PRIMERA VEZ EN LAS TRES RONDAS DE ESTA CASA DESDE EL 13/Ago, 45% a 44%, después de 45% a 46% el 13/Ago y 44% a 45% el 27/Ago.`,
  'candidates[1].fortes[1]': `Su distancia hacia el líder en la primera vuelta de la propia casa pasó de 6 puntos el 13/Ago a 3 el 27/Ago y quedó en 3 ahora.`,
  'candidates[1].fortes[2]': `En el contrato de 2º lugar de la primera vuelta sigue dominante y no se movió, con 85,50% en un contrato de USD 519 mil.`,
  'candidates[1].fortes[3]': `Su caída en el precio fue de 0,30pp, contra 1,00pp del líder, es decir, perdió menos que el adversario en el mismo día.`,
  'candidates[1].fracos[0]': `En la primera vuelta cedió dentro de la propia casa, de 35% el 13/Ago y 35% el 27/Ago a 34% ahora.`,
  'candidates[1].fracos[1]': `En el precio cayó 0,30pp y está en 40,35%, y el alza de 1,70pp de la víspera no tuvo continuidad.`,
  'candidates[1].fracos[2]': `La ventaja de 1 punto en la segunda vuelta está dentro del margen declarado de 2pp, es decir, es empate técnico según la regla de la propia casa, y la casa de la víspera midió el mismo par al revés.`,
  'candidates[1].fracos[3]': `Usó la crisis en el Supremo para intentar impulsar el acto del 7 de Septiembre, según Folha de S.Paulo, en un día en que el eje de las noticias estaba en el tribunal y no en la campaña.`,
  'candidates[1].analise': `Su día es el inverso del de ayer en las dos mediciones. En el voto declarado hizo el mejor resultado de su propia serie en el par que decide la elección, apareciendo numéricamente adelante por primera vez en las tres rondas de esta casa desde el 13/Ago. En la primera vuelta, sin embargo, cedió 1 punto dentro de la misma casa y la distancia hacia el líder quedó parada en 3. En el precio cayó, y cayó el mismo día en que el líder cayó más, de modo que la distancia entre los dos se achicó sin que él haya subido. Es la segunda lectura seguida en que precio y voto declarado apuntan a lados distintos, y esta vez con las señales cambiadas respecto de la víspera.`,

  // ── Renan ──
  'candidates[2].header': `PRECIO: 1,75% (vol USD 12,48M acumulado), ${S}. Caída de 0,45pp. En el contrato de 3º lugar de la primera vuelta cayó 1,00pp y pasa a 27,00% en un contrato de USD 266 mil. ENCUESTA: ${PD} lo da en 3% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. En una segunda vuelta pierde con el líder por 44% a 39%.`,
  'candidates[2].fortes[0]': `El margen contra él en la segunda vuelta se achicó dentro de la propia casa, de 7 puntos el 27/Ago a 5 ahora, pasando él de 37% a 39%.`,
  'candidates[2].fortes[1]': `Es el único de los nombres fuera del pelotón de arriba que la PoderData prueba en una segunda vuelta y que mejoró su propia posición entre las dos rondas de la casa.`,
  'candidates[2].fortes[2]': `Pidió juicio político contra dos ministros del Supremo en el Senado, según Poder360, y con eso sigue dentro del asunto que domina las noticias de la semana.`,
  'candidates[2].fortes[3]': `El volumen acumulado en el contrato de ganador sigue siendo el mayor entre los nombres de abajo, con USD 12,48M.`,
  'candidates[2].fracos[0]': `En el precio cayó 0,45pp y está en 1,75%, y en el contrato de 3º lugar de la primera vuelta cayó 1,00pp y pasa a 27,00%.`,
  'candidates[2].fracos[1]': `En la primera vuelta cedió dentro de la propia casa, de 4% el 27/Ago a 3%, en el mismo intervalo en que Augusto Cury salió de 4% a 10%.`,
  'candidates[2].fracos[2]': `En el contrato de 3º lugar de la primera vuelta la distancia hacia el primero duplicó de tamaño en dos días, y él está en 27,00% contra 55,85%.`,
  'candidates[2].fracos[3]': `Tiene el mayor volumen acumulado entre los nombres de abajo y aun así su precio está en 1,75%, es decir, dinero grande no sostuvo precio.`,
  'candidates[2].analise': `Su semana tiene dos señales opuestas y hay que separar los contratos. En el voto declarado cedió en la primera vuelta dentro de la propia casa, de 4% a 3%, exactamente en el intervalo en que Augusto Cury fue de 4% a 10% en el mismo instituto. En la segunda vuelta contra el líder, en cambio, mejoró: el margen cayó de 7 a 5 puntos dentro de la casa. En el precio la lectura es de caída en los dos contratos, y la pérdida mayor es la del contrato de 3º lugar, donde fue superado el 01/Set y la distancia hacia el primero duplicó desde entonces. Su contrato de ganador tiene el mayor volumen acumulado entre los nombres de abajo, con USD 12,48M, y aun así el precio no pasa de 1,75%.`,

  // ── Pelotão de trás ──
  'candidates[3].header': `PRECIO: Caiado en 0,25%, Zema en 0,15% y Haddad en 0,05% en el contrato de GANADOR, los tres debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para ninguno de ellos en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, Caiado SUBIÓ 2,50pp y está en 11,00%, y Zema está en 0,80%. ENCUESTA: ${PD} da 2% a Ronaldo Caiado y 1% a Romeu Zema en la primera vuelta. En una segunda vuelta el líder gana a los dos, por 44% a 42% en cada caso.`,
  'candidates[3].subtitle': `Pelotón de atrás en ${S}, y este jueves lo que cambia es la tercera lectura seguida del mismo par de segunda vuelta. Ronaldo Caiado salió de 4% a 2% dentro de la propia PoderData, entre el 27/Ago y ahora, y en la segunda vuelta queda a 2 puntos del líder, 44% a 42%. En tres días ese par fue medido por tres casas con campo superpuesto y dio tres resultados: 45% a 43% a su favor en la Real Time Big Data del 01/Set, 42% a 37% en su contra en la Genial/Quaest del 02/Set y 44% a 42% en su contra ahora.`,
  'candidates[3].caiado.label': `CAIADO (PSD), 0,25% (vol USD 7,11M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, subió 2,50pp y está en 11,00%, en un libro de 111 mil dólares acumulados. EN EL VOTO DECLARADO DE ESTE JUEVES PIERDE LA SEGUNDA VUELTA CON EL LÍDER POR 44% A 42%, el menor margen en su contra entre las tres casas de la semana.`,
  'candidates[3].caiado.fortes': `Su alza de 2,50pp en el contrato de 3º lugar de la primera vuelta es el mayor movimiento de alza del panel en esta ronda, y recupera con holgura la caída de 4,50pp de la víspera. En la segunda vuelta de la PoderData queda a 2 puntos del líder, 44% a 42%, contra 3 puntos en la ronda de la misma casa del 27/Ago. Defendió el apartamiento de Alexandre de Moraes y el juicio político en el Senado, según Valor Econômico, y que el Supremo levante el secreto de todas las investigaciones sobre Banco Master, INSS y Dark Horse, según Estadão.`,
  'candidates[3].caiado.fracos': `En la primera vuelta cayó de 4% a 2% dentro de la propia PoderData, entre el 27/Ago y ahora. En el contrato de ganador sigue debajo del piso de 0,5%, y esta ronda no publica precio nuevo para él allí. Y el par de segunda vuelta en que aparece ya fue medido de tres formas en tres días, lo que vuelve frágil cualquier lectura aislada de él.`,
  'candidates[3].haddad.label': `HADDAD (PT), 0,05% (vol USD 7,43M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él. No es candidato a la Presidencia: disputa la gobernación de São Paulo.`,
  'candidates[3].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,51M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, está en 0,80%, en un libro de 49 mil dólares acumulados.`,
  'candidates[3].zema.fortes': `En la segunda vuelta de la PoderData queda a 2 puntos del líder, 44% a 42%, que es de lejos su mejor resultado entre las tres casas de la semana y el menor margen en su contra en cualquier nacional de la ventana.`,
  'candidates[3].zema.fracos': `Tiene 1% en la primera vuelta, contra 2% en la ronda de la misma casa del 27/Ago. Y la segunda vuelta contra el líder es el escenario en que las tres casas de la semana más discrepan: la Genial/Quaest del 02/Set dio 44% a 33%, margen de 11 puntos, la Real Time Big Data del 01/Set dio 43% a 40%, margen de 3, y la PoderData ahora da 44% a 42%, margen de 2. Tres casas, tres márgenes, en el intervalo de tres días.`,
  'candidates[3].analise': `El par de segunda vuelta contra Ronaldo Caiado es el retrato de la semana: tres casas, tres resultados, todas con campo superpuesto. La Real Time Big Data del 01/Set lo daba adelante del líder por 45% a 43%, la Genial/Quaest del 02/Set dio al líder adelante por 42% a 37%, y la PoderData del 03/Set da al líder adelante por 44% a 42%. Los márgenes van de 2 puntos atrás a 5 puntos adelante, en un intervalo de tres días. El panel registra las tres lecturas y no elige entre ellas. En la primera vuelta, al mismo tiempo, cedió dentro de la propia PoderData, de 4% el 27/Ago a 2%. En el precio los tres siguen debajo del piso en el contrato de ganador, y el único movimiento publicable es el de Caiado en el contrato de 3º lugar, que subió 2,50pp y está en 11,00%, el mayor movimiento de alza del panel en esta ronda.`,
  'candidates[3].fortes': `Ronaldo Caiado subió 2,50pp en el contrato de 3º lugar de la primera vuelta, el mayor movimiento de alza del panel en esta ronda, y en la segunda vuelta de la PoderData queda a 2 puntos del líder, la menor distancia que la casa ya midió en ese par.`,
  'candidates[3].fracos': `Ninguno de los tres llega a 3% en la primera vuelta de la PoderData, los tres siguen debajo del piso de 0,5% en el contrato de ganador, y Caiado cedió dentro de la propia casa, de 4% el 27/Ago a 2% ahora.`,

  // ── Quadro comparativo ──
  'quadroComparativo[0].p': `${PD} lo da en 37% en la primera vuelta, contra 38% en la ronda de la misma casa del 27/Ago y 41% en la del 13/Ago. ⚠️ EN UNA SEGUNDA VUELTA CONTRA EL SEGUNDO COLOCADO QUEDA ATRÁS POR PRIMERA VEZ EN LAS TRES RONDAS DE ESTA CASA DESDE EL 13/Ago, 44% a 45%. Gana los otros tres pares: 44% a 42% contra Ronaldo Caiado, 44% a 42% contra Romeu Zema y 44% a 39% contra Renan Santos.`,
  'quadroComparativo[0].m': `54,50% (vol USD 9,63M), ${S}. Caída de 1,00pp, después de cinco días parado en 55,50%. La distancia hacia el segundo bajó a 14,15pp, contra 14,85pp el 02/Set. En el contrato de 2º lugar de la primera vuelta subió 0,75pp y pasa a 8,75%.`,
  'quadroComparativo[0].t': `cae en el precio por primera vez en seis días y queda atrás en la segunda vuelta de la casa que lo daba adelante en las dos rondas anteriores`,
  'quadroComparativo[0].s': `Hizo a las 15h en el Planalto la ceremonia en que declaró en cero la fila del INSS, con el criterio de plazo legal declarado en la propia fuente, según Poder360 y O Globo. Se reunió con Edson Fachin y Gilmar Mendes sobre la crisis en el Supremo, según Poder360 y Estadão.`,

  'quadroComparativo[1].p': `La misma PoderData lo da en 34% en la primera vuelta, contra 35% en las rondas de la casa del 13/Ago y del 27/Ago. ⭐ EN LA SEGUNDA VUELTA APARECE NUMÉRICAMENTE ADELANTE POR PRIMERA VEZ EN LAS TRES RONDAS DE ESTA CASA DESDE EL 13/Ago, 45% a 44%, y la distancia de 1 punto está dentro del margen declarado de 2pp. La Genial/Quaest de la víspera midió el mismo par al revés, 41% a 42%.`,
  'quadroComparativo[1].m': `40,35% (vol USD 9,59M), ${S}. Caída de 0,30pp, el mismo día en que el líder cayó 1,00pp. En el contrato de 2º lugar de la primera vuelta quedó parado en 85,50%.`,
  'quadroComparativo[1].t': `cede en el precio y en la primera vuelta, y al mismo tiempo hace el mejor resultado de su propia serie en el par que decide la elección`,
  'quadroComparativo[1].s': `Usó la crisis en el Supremo para intentar impulsar el acto del 7 de Septiembre, según Folha de S.Paulo. En Porto Alegre, intentó ligar al líder con Alexandre de Moraes, según Valor Econômico.`,

  'quadroComparativo[2].p': `La PoderData lo mide en 10% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. Es el mismo salto que la Genial/Quaest midió la víspera, de 2% el 14/Ago a 10% el 02/Set, y ahora son dos casas independientes midiendo la misma dirección dentro de sus propias series. La PoderData no probó segunda vuelta con él.`,
  'quadroComparativo[2].m': `1,35% (vol USD 3,64M), ${S}. CAÍDA de 0,25pp en el contrato de ganador, y ALZA de 3,45pp en el contrato de 3º lugar de la primera vuelta, donde está en 55,85% (vol USD 108 mil) y sube por segundo día seguido.`,
  'quadroComparativo[2].t': `confirma el salto en una segunda casa y el precio sigue yendo hacia lados opuestos en los dos contratos`,
  'quadroComparativo[2].s': `Sin hecho propio en las noticias de este jueves. La BBC publicó un análisis según el cual el caso Vorcaro y Moraes puede alimentar una ola antipolítica y favorecerlo a él y a Renan Santos.`,

  'quadroComparativo[3].p': `La PoderData lo da en 3% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. En una segunda vuelta pierde con el líder por 44% a 39%, y la misma casa medía 44% a 37% el 27/Ago, es decir, el margen en su contra se achicó 2 puntos dentro de la casa.`,
  'quadroComparativo[3].m': `1,75% (vol USD 12,48M), ${S}. Caída de 0,45pp. En el contrato de 3º lugar de la primera vuelta cayó 1,00pp y pasa a 27,00% en un contrato de USD 266 mil.`,
  'quadroComparativo[3].t': `cede en el precio y en la primera vuelta, y mejora en el único par de segunda vuelta en que la casa lo prueba`,
  'quadroComparativo[3].s': `Pidió juicio político de Alexandre de Moraes y de Dias Toffoli en el Senado, según Poder360.`,

  'quadroComparativo[4].p': `La PoderData lo coloca en 2% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. ⚠️ LA SEGUNDA VUELTA CONTRA ÉL YA TIENE TRES RESULTADOS DISTINTOS EN LA MISMA SEMANA, todos con campo superpuesto: la PoderData da al líder adelante por 44% a 42%, la Genial/Quaest del 02/Set dio 42% a 37% y la Real Time Big Data del 01/Set lo daba adelante por 45% a 43%.`,
  'quadroComparativo[4].m': `0,25% (vol USD 7,11M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, SUBIÓ 2,50pp y está en 11,00% (vol USD 111 mil).`,
  'quadroComparativo[4].t': `el par de segunda vuelta contra él ya tiene tres lecturas de señal y tamaño distintos en tres días`,
  'quadroComparativo[4].s': `Defendió el apartamiento de Alexandre de Moraes y el juicio político en el Senado, según Valor Econômico, y que el Supremo levante el secreto de todas las investigaciones sobre Banco Master, INSS y Dark Horse, según Estadão.`,

  'quadroComparativo[5].p': `La PoderData lo mide en 2% en la primera vuelta, contra 3% en la ronda de la misma casa del 27/Ago. A diferencia de la Genial/Quaest de la víspera, esta casa publicó un único escenario de primera vuelta, con él en la lista, así que esta ronda no mide el efecto de su presencia sobre el número del segundo colocado.`,
  'quadroComparativo[5].m': `0,15% (vol USD 3,34M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él.`,
  'quadroComparativo[5].t': `la casa de hoy no repite el par de escenarios que medía su efecto, así que no hay lectura nueva sobre eso`,
  'quadroComparativo[5].s': `No aparece en las noticias de este jueves con hecho propio.`,

  'quadroComparativo[6].m': `7,40% (vol USD 87 mil), ${S}. Alza de 1,05pp contra el 6,35% publicado el 02/Set. ⚠️ ES EL MENOR LIBRO DEL PANEL y el volumen acumulado sigue en USD 87 mil, es decir, el dinero nuevo del día es despreciable. En tres días el contrato fue a 10,85%, cayó a 6,35% y subió a 7,40%.`,
  'quadroComparativo[6].t': `tercera dirección seguida en tres días, con el volumen acumulado parado`,
  'quadroComparativo[6].s': `La Procuraduría General de la República cerró un acuerdo de delación con Antonio Carlos Freixo Júnior, dueño de Entre Investimentos, primera colaboración ligada directamente al caso Dark Horse, según Folha de S.Paulo y O Globo, y el acuerdo todavía no fue homologado. El 02/Set la misma Procuraduría firmó la delación de João Carlos Mansur, fundador de Reag, y la envió al despacho de André Mendonça para homologación, según Poder360 y G1. Gilmar Mendes propuso a Edson Fachin vetar delegados de la Policía Federal en despachos del tribunal, según Folha de S.Paulo. El Colegio de Abogados de Paraná pidió el apartamiento de Moraes y la recusación del procurador general, según Folha de S.Paulo. El informe de Mendonça sobre Moraes sigue previsto para el 7 o el 8 de septiembre, según Poder360.`,
})
