/** Mapa ES de 03/Set/2026: polls-data. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 03/Set, 15:22 BRT (18:22 UTC)'
const PD = 'PoderData del 03/Set (BR-07561/2026, campo del 30/Ago al 02/Set, n=3.000)'

construir('polls-data', 'es', {
  'polls[0].note': `PoderData nacional divulgada el 03/Set (Gazeta do Povo). ⭐ INVIERTE LA ${G('SEGUNDA VUELTA', 'segundo-turno')} DENTRO DE LA PROPIA CASA. Flávio Bolsonaro tiene 45% contra 44% de Lula, con 8% de blanco o nulo y 3% de no sabe. En las dos rondas anteriores del mismo instituto era Lula adelante, por 46% a 45% el 13/Ago y por 45% a 44% el 27/Ago, y esta es la primera de la serie de la casa en que el segundo colocado aparece numéricamente adelante en ese par. La distancia es de 1 punto y el margen declarado es de 2pp, es decir, ${G('empate técnico', 'empate-tecnico')} según la regla de la propia casa. ⚠️ Y LA CASA DE LA VÍSPERA MIDIÓ LO CONTRARIO EN EL MISMO PAR: la Genial/${G('Quaest', 'quaest')} del 02/Set, con campo del 30/Ago al 01/Set que se superpone casi entero a este, dio a Lula adelante por 42% a 41%. Los dos márgenes son de 1 punto y apuntan a lados opuestos. COMPARACIÓN DENTRO DE LA CASA, que es la única válida. En la ${G('primera vuelta', 'primeiro-turno')} Lula salió de 41% el 13/Ago a 38% el 27/Ago y 37% ahora, y Flávio de 35% a 35% y 34%, es decir, la distancia entre los dos fue de 6pp a 3pp y quedó en 3pp. ⭐ AUGUSTO CURY SALTA DE 4% A 10% DENTRO DE LA PODERDATA entre el 27/Ago y ahora, el mismo salto que la Genial/Quaest midió la víspera yendo de 2% a 10%. En el mismo intervalo Renan Santos salió de 4% a 3%, Ronaldo Caiado de 4% a 2% y Romeu Zema de 2% a 1%. En los otros tres pares de segunda vuelta probados Lula gana: 44% a 42% contra Caiado, 44% a 42% contra Zema y 44% a 39% contra Renan Santos. Contra Caiado la casa midió 44% a 43% el 27/Ago, y la Real Time Big Data del 01/Set daba a Caiado adelante por 45% a 43%, es decir, tres casas y tres resultados distintos en el mismo par en la misma semana. El escenario de primera vuelta cierra en 100 exactos con 5% de blanco o nulo y 2% de indecisos. Campo del 30/Ago al 02/Set, n=3.000, margen de 2pp, 95% de confianza, contratante el propio instituto, registro ${G('TSE', 'tse')} BR-07561/2026. 📅 LA DIVULGACIÓN DE ESTE JUEVES YA ESTABA EN EL REGISTRO DEL TSE ingerido por el panel esa misma mañana, con la fecha prevista y el número de registro coincidiendo con lo publicado. ℹ️ La casa no publicó evaluación de gobierno ni rechazo en la tabla verificada.`,
  'polls[0].source': `PoderData, divulgada el 03/Set/2026 (campo del 30/Ago al 02/Set, n=3.000, margen de 2pp, 95% de confianza, contratante el propio instituto, registro TSE BR-07561/2026). Tabla completa de la primera vuelta y de los cuatro escenarios de segunda vuelta verificada en Gazeta do Povo.`,

  'approvalData.note': `🏷️ LOS NÚMEROS ESTRUCTURADOS DE ESTE BLOQUE SON DE LA GENIAL/QUAEST DEL 02/Set, y son estos: 45% de aprobación contra 48% de desaprobación, con 7% de no sabe, y 35% de excelente o bueno, 25% de regular y 37% de malo o pésimo, con 3% sin respuesta. ℹ️ LA PODERDATA DEL 03/Set NO PUBLICÓ EVALUACIÓN DE GOBIERNO NI RECHAZO en la tabla verificada, así que este bloque no cambia en esta ronda. El panel mantiene UNA casa por bloque a propósito, para no sumar reglas de institutos distintos. ⭐ DENTRO DE LA PROPIA QUAEST EL CUADRO ES DE INMOVILIDAD. El 05/Ago eran 48% de aprobación contra 47% de desaprobación, el 14/Ago 46% contra 48% y el 02/Set 45% contra 48%. La desaprobación está en el mismo número por tercera ronda seguida de la casa, y la aprobación cedió 1pp en cada una de las dos últimas. En la regla de gestión, el excelente o bueno salió de 36% el 14/Ago a 35%, con regular y malo o pésimo parados en 25% y 37%. 📌 RECHAZO, también de la ronda del 02/Set y de la misma casa: Flávio Bolsonaro 55% y Lula 53%, contra 54% y 52% en la ronda del 14/Ago. Los dos subieron 1pp y la distancia entre ellos no cambió. En la misma ronda, Pablo Marçal 44%, Ronaldo Caiado 40%, Romeu Zema 38%, Renan Santos 28% y Augusto Cury 25%.`,

  'polymarketComparison.note': `Precios del ${G('Polymarket', 'polymarket')} en la ${S}, con el libro presidencial en USD 142,35M. UNA ENCUESTA NACIONAL FUE DIVULGADA ESTE JUEVES, la PoderData (BR-07561/2026, campo del 30/Ago al 02/Set, n=3.000, margen de 2pp, contratante el propio instituto), y su divulgación ya constaba en el registro del TSE ingerido por el panel esa misma mañana. ⭐ INVIERTE LA SEGUNDA VUELTA DENTRO DE LA PROPIA CASA: Flávio Bolsonaro 45% y Lula 44%, después de Lula 46% a 45% el 13/Ago y Lula 45% a 44% el 27/Ago. Es la primera de la serie de la casa en que el segundo colocado aparece numéricamente adelante en ese par, y la distancia de 1 punto está dentro del margen declarado de 2pp. ⚠️ LA CASA DE LA VÍSPERA MIDIÓ LO CONTRARIO: la Genial/Quaest del 02/Set, con campo superpuesto, dio a Lula adelante por 42% a 41%. El panel registra la divergencia y no arbitra entre las dos. ⭐ EN EL PRECIO, LOS DOS PRIMEROS CAYERON EL MISMO DÍA: el líder cedió 1,00pp, hasta 54,50%, cerrando cinco días parado, y el segundo cedió 0,30pp, hasta 40,35%. La distancia entre ellos se achicó por segundo día seguido, de 16,55pp el 01/Set a 14,85pp el 02/Set y 14,15pp ahora, pero por un motivo distinto al de ayer, cuando el segundo subió. La suma de las puntas SÍ del libro presidencial está en 99,20%. ⏳ OTRAS DOS NACIONALES TENÍAN DIVULGACIÓN MARCADA PARA ESTE JUEVES en el registro del TSE, la ${G('Datafolha', 'datafolha')} (BR-03669/2026, n=2.002, campo del 01 al 03/Set) y la 100 Cidades (BR-02793/2026, n=2.000, campo del 28/Ago al 01/Set), y ninguna de las dos tenía números publicados al momento de esta lectura. 📅 EL CALENDARIO HACIA ADELANTE, ya sin los registros que salieron del archivo del TSE: Veritá el 06/Set (BR-09426/2026, n=3.840), Genial/Quaest el 07/Set (BR-01720/2026, n=2.004), y Gerp (BR-00251/2026, n=2.400) y ${G('Nexus', 'nexus-btg')} (BR-06790/2026, n=2.000) el 08/Set.`,

  // Lula
  'polymarketComparison.candidates[0].polymarket': `54,50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `La ${PD} lo da en 37% en la primera vuelta, contra 38% en la ronda de la misma casa del 27/Ago y 41% en la del 13/Ago. ⚠️ EN UNA SEGUNDA VUELTA CONTRA EL SEGUNDO COLOCADO QUEDA ATRÁS POR PRIMERA VEZ EN LAS TRES RONDAS DE ESTA CASA DESDE EL 13/Ago, 44% a 45%, después de 46% a 45% el 13/Ago y 45% a 44% el 27/Ago. La Genial/Quaest de la víspera midió el mismo par al revés, 42% a 41% a su favor. Gana los otros tres pares probados por la PoderData: 44% a 42% contra Ronaldo Caiado, 44% a 42% contra Romeu Zema y 44% a 39% contra Renan Santos.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `54,50% (vol USD 9,63M), ${S}. Caída de 1,00pp, después de cinco días parado en 55,50%. La distancia hacia el segundo bajó a 14,15pp, contra 14,85pp el 02/Set y 16,55pp el 01/Set, y esta vez se achica porque él cayó más, no porque el segundo subió. En el contrato de 2º lugar de la primera vuelta subió 0,75pp, hasta 8,75%.`,

  // Flávio
  'polymarketComparison.candidates[1].polymarket': `40,35%`,
  'polymarketComparison.candidates[1].pesquisaRange': `34%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `La PoderData lo da en 34% en la primera vuelta, contra 35% en las dos rondas anteriores de la misma casa, del 13/Ago y del 27/Ago. ⭐ EN LA SEGUNDA VUELTA APARECE NUMÉRICAMENTE ADELANTE POR PRIMERA VEZ EN LAS TRES RONDAS DE ESTA CASA DESDE EL 13/Ago, 45% a 44%, y la distancia dentro de la casa pasó de 1 punto atrás el 13/Ago y el 27/Ago a 1 punto adelante ahora. El margen declarado es de 2pp, así que es empate técnico según la regla de la propia casa. La Genial/Quaest de la víspera midió el mismo par al revés, 41% a 42%.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40,35% (vol USD 9,59M), ${S}. Caída de 0,30pp, el mismo día en que el líder también cayó, y eso separa esta ronda de la anterior. En el contrato de 2º lugar de la primera vuelta quedó parado en 85,50% (vol USD 519 mil).`,

  // Cury
  'polymarketComparison.candidates[2].polymarket': `1,35%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `La PoderData lo mide en 10% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. Es el mismo salto que la Genial/Quaest midió la víspera, de 2% el 14/Ago a 10% el 02/Set, y ahora son dos casas independientes midiendo la misma dirección dentro de sus propias series. La PoderData no probó segunda vuelta con él.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,35% (vol USD 3,64M), ${S}. CAÍDA de 0,25pp en el contrato de ganador y ALZA de 3,45pp en el contrato de 3º lugar de la primera vuelta, donde está en 55,85% (vol USD 108 mil) y sube por segundo día seguido. Son preguntas distintas: una es ganar la elección, la otra es terminar tercero.`,

  // Renan
  'polymarketComparison.candidates[3].polymarket': `1,75%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La PoderData lo da en 3% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. En una segunda vuelta pierde con el líder por 44% a 39%, margen de 5 puntos, y la misma casa medía 44% a 37% el 27/Ago, es decir, el margen se achicó 2 puntos dentro de la casa. La Genial/Quaest de la víspera midió ese par en 43% a 36%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,75% (vol USD 12,48M), ${S}. Caída de 0,45pp. En el contrato de 3º lugar de la primera vuelta cayó 1,00pp y pasa a 27,00% en un contrato de USD 266 mil.`,

  // Caiado
  'polymarketComparison.candidates[4].pesquisaRange': `2%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `La PoderData lo coloca en 2% en la primera vuelta, contra 4% en la ronda de la misma casa del 27/Ago. ⚠️ LA SEGUNDA VUELTA CONTRA ÉL YA TIENE TRES RESULTADOS DISTINTOS EN LA MISMA SEMANA: la PoderData da al líder adelante por 44% a 42%, la Genial/Quaest del 02/Set dio 42% a 37% y la Real Time Big Data del 01/Set lo daba adelante por 45% a 43%. Las tres casas tuvieron campo superpuesto.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,25% (vol USD 7,11M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, SUBIÓ 2,50pp y está en 11,00% (vol USD 111 mil), lectura confirmada del 03/Set, 15:22 BRT.`,

  // Marçal
  'polymarketComparison.candidates[5].pesquisaRange': `2%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `La PoderData lo mide en 2% en la primera vuelta, contra 3% en la ronda de la misma casa del 27/Ago. A diferencia de la Genial/Quaest de la víspera, esta casa publicó un único escenario de primera vuelta, con él en la lista, así que aquí no está el par de escenarios que mediría el efecto de su presencia.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,34M) en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él.`,

  // Zema
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La PoderData lo mide en 1% en la primera vuelta, contra 2% en la ronda de la misma casa del 27/Ago. En una segunda vuelta pierde con el líder por 44% a 42%, margen de 2 puntos. La Genial/Quaest del 02/Set midió el mismo par en 44% a 33%, margen de 11, y la Real Time Big Data del 01/Set en 43% a 40%, margen de 3. Son tres casas y tres márgenes, de 2, 3 y 11 puntos, en la misma semana.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,15% en el contrato de GANADOR, debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, está en 0,80% (vol USD 49 mil), lectura confirmada del 03/Set, 15:22 BRT.`,
})
