/** Mapa EN: polls-data da rodada de 04/Set/2026, carimbo 19:07. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 04/Sep, 19:07 BRT (22:07 UTC)'
const DF = 'the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp)'
const SEM = 'No new national poll today. '
const QUATRO =
  '45% to 43% in his favour at Real Time Big Data on 01/Sep, 42% to 37% against him at Genial/Quaest on 02/Sep, 44% to 42% against him at PoderData on 03/Sep and 46% to 41% against him at Datafolha the same day'

construir('polls-data', 'en', {
  'polymarketComparison.note': `${G('Polymarket', 'polymarket')} prices at the ${S}, with the presidential book at USD 143.57M. ⭐ NO NATIONAL POLL WAS RELEASED ON 04/Sep, and the ${G('TSE', 'tse')} register says why: seven national polls are in the field right now and the first scheduled release is 06/Sep, from Veritá, followed by Quaest on 07/Sep, Gerp and Nexus on 08/Sep, and Ideia/Canal Meio, Real Time Big Data and PALVER on 09/Sep, the last of these with 5,000 interviews. ⭐ AND IT WAS ON THE DAY WITHOUT A POLL THAT THE PRICE MOVED MOST: the gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp that undid four consecutive readings of narrowing. The panel records the coincidence of dates and assigns no cause. ⚠️ This round publishes no new price for the ${G('Supreme Court', 'stf')} justice impeachment contract nor for the Senate majority one.`,
  'polymarketComparison.sources': `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20pp. Confirmation is done contract by contract. On 04/Sep the winner, first-round runner-up and first-round third-place books confirmed at the 19:07 reading, and the Supreme Court justice impeachment and Senate majority contracts have no confirmed reading in this round. Polls registered with the TSE and released by the polling houses, with reporting from Poder360, Gazeta do Povo, CNN Brasil, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC and Jornal de Brasília. The calendar of polls in the field and of scheduled releases comes from the official TSE register. Series superlatives checked against the Neon backup, in backup/neon/marketPrice, which holds the complete record since 14/Apr.`,

  'polymarketComparison.candidates[0].polymarket': `55.50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `${SEM}The most recent reading is still ${DF}, which gives him 39% in the scenario with Pablo Marçal and 38% in the one without, and winning all four ${G('second-round', 'segundo-turno')} pairings it tested: 46% to 44% against the runner-up, 46% to 41% against Ronaldo Caiado and 48% to 39% against Romeu Zema. Government assessment: 45% approve and 51% disapprove.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55.50% (vol USD 9.72M), ${S}. Up 1.00pp on the reading of 03/Sep, 23:45. ⭐ THE GAP TO THE RUNNER-UP REOPENED BY 3.70pp, from 11.65pp to 15.35pp, after narrowing across four consecutive readings, and it happened on a day with no new national poll. ⚠️ In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 4.70pp and now stands at 5.80% (vol USD 467 thousand).`,

  'polymarketComparison.candidates[1].polymarket': `40.15%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `${SEM}Datafolha of 03/Sep gives him 32% in the scenario with Marçal and 33% in the one without, and 2 points away in the second round, 44% against 46%. ⚠️ THE WINDOW'S THREE NATIONAL POLLS STILL DISAGREE ON THE SIGN OF THAT PAIRING: Genial/${G('Quaest', 'quaest')} of 02/Sep put the leader ahead by 42% to 41%, PoderData of 03/Sep put him ahead by 45% to 44%, and Datafolha of 03/Sep puts the leader ahead by 46% to 44%.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40.15% (vol USD 9.68M), ${S}. ⚠️ DOWN 2.70pp, the largest move of any name in the presidential book in this reading. ⭐ AND HIS TWO CONTRACTS MOVED IN OPPOSITE DIRECTIONS: in the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 4.00pp and now stands at 87.50% (vol USD 586 thousand). In the third-place contract he appears at 1.55% (vol USD 68 thousand).`,

  'polymarketComparison.candidates[2].polymarket': `1.95%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `${SEM}Datafolha of 03/Sep leaves him at 7% in the scenario with Marçal and 8% in the one without, and it is still the only one of the window's five houses to put him below double digits. The other four: BTG/Nexus 11% on 31/Aug, Real Time Big Data 11% on 01/Sep, Genial/Quaest 10% on 02/Sep and PoderData 10% on 03/Sep.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.95% (vol USD 4.07M), ${S}. Up 0.70pp in the winner contract, with around USD 380 thousand of new volume in one day. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 4.85pp and now stands at 54.65% (vol USD 123 thousand), breaking three straight days of gains. And in the first-round runner-up contract, which is a third market, he slipped 0.80pp, from 1.75% to 0.95% in that book, which has accumulated USD 142 thousand.`,

  'polymarketComparison.candidates[3].polymarket': `1.85%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${SEM}Datafolha of 03/Sep gives him 4% in the scenario with Marçal and 3% in the one without. ⚠️ DISPERSION ACROSS HOUSES IN THIS WINDOW RUNS FROM 3% TO 7.6%: 3% at Genial/Quaest and PoderData, 3% to 4% at Datafolha, 6% at Real Time Big Data on 01/Sep and 7.6% at AtlasIntel on 31/Aug.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.85% (vol USD 12.64M), ${S}. Up 0.10pp in the winner contract. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.50pp and now stands at 23.50% (vol USD 277 thousand), recovering part of the 4.50pp he had given up in the previous reading. 📌 Among the four names above 1% in the winner contract, his is the largest accumulated volume, ahead of the leader and the runner-up, in a contract priced below 2%.`,

  'polymarketComparison.candidates[4].tendenciaPesquisa': `${SEM}Datafolha of 03/Sep puts him at 4% in both first-round scenarios and has him losing the second round by 46% to 41%. ⚠️ THE SECOND-ROUND PAIRING AGAINST HIM HAS FOUR READINGS IN THE SAME WEEK AND NO TWO AGREE ON THE MARGIN: ${QUATRO}.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.15% (vol USD 7.15M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he gave up 0.50pp and stands at 9.50% (vol USD 114 thousand), ${S}.`,

  'polymarketComparison.candidates[5].tendenciaPesquisa': `${SEM}Datafolha of 03/Sep has him at 2% in the scenario in which he is on the list. His presence separates the house's two scenarios: with Marçal the leader has 39% and the runner-up 32%, and without Marçal the leader has 38% and the runner-up 33%, so the gap goes from 7 to 5 points.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.64M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he stands at 2.60% (vol USD 47 thousand), ${S}.`,

  'polymarketComparison.candidates[6].tendenciaPesquisa': `${SEM}Datafolha of 03/Sep measures him at 2% in both first-round scenarios and has him losing the second round by 48% to 39%, a margin of 9 points. The week's four houses measured that pairing at 3, 11, 2 and 9 points, and it is the pairing with the widest dispersion across houses in the window.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.15% (vol USD 6.55M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he stands at 0.70% (vol USD 49 thousand), ${S}.`,

  'polymarketComparison.candidates[7].tendenciaPolymarket': `0.05% (vol USD 14.07M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him. He is not a presidential candidate: he is running for re-election in São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0.05% (vol USD 7.43M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him. He is not a presidential candidate: he is running for governor of São Paulo.`,
})
