/** Mapa EN: analysis-criteriosa, republicação de 04/Set/2026 com carimbo 19:53 e o STF no ar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 04/Sep, 19:53 BRT (22:53 UTC)'
const SU = 'reading of 04/Sep, 19:53 BRT (22:53 UTC)'
const DF = 'the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp)'
const SEM = 'No new national poll today. '
const SEMQ = `${SEM}The most recent reading is still ${DF}. `
const QUATRO =
  '45% to 43% in his favour at Real Time Big Data on 01/Sep, 42% to 37% against him at Genial/Quaest on 02/Sep, 44% to 42% against him at PoderData on 03/Sep and 46% to 41% against him at Datafolha the same day'
const FAIXA =
  `⚠️ THIS IS THE ONLY CONTRACT ON THE PANEL GOING OUT WITHOUT THE DOUBLE READING that AFOS applies to the others, ` +
  `and the reason is in the recorded series itself: on 04/Sep it travelled from 10.60% to 19.30%, an amplitude of 8.70pp, ` +
  `with USD 28 of new money over the whole day. 📌 The figure above is ONE reading inside that range, not its centre. ` +
  `Over the four previous days the daily amplitude was 0.10pp, 15.60pp, 4.10pp and 6.30pp, with USD 0, USD 1,852, ` +
  `USD 69 and USD 157 of new money. It is the panel's smallest book and the one most sensitive to a small order.`

construir('analysis-criteriosa', 'en', {
  subtitle: `Cross-reading for 4 September 2026, ${S}, presidential book at USD 143.62M. ⭐ NO NEW NATIONAL POLL WAS RELEASED TODAY, and the ${G('TSE', 'tse')} register says why: seven national polls are IN THE FIELD right now and the first scheduled release is 06/Sep. ⭐ AND IT WAS ON THE DAY WITHOUT A POLL THAT THE PRICE MOVED MOST: the gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp, after narrowing across four consecutive readings. The polling reference is still ${DF}, and it has not changed since yesterday.`,

  'candidates[0].header': `PRICE: 55.50% (vol USD 9.72M accumulated), ${S}, up 1.00pp on the reading of 03/Sep, 23:45. POLL: no new reading. The most recent is still the Datafolha poll of 03/Sep, which gives him 39% in the scenario with Pablo Marçal and 38% in the one without, and winning all four ${G('second-round', 'segundo-turno')} pairings it tested.`,
  'candidates[0].fortes[3]': `Accumulated volume in his contract reached USD 9.72M, and the whole presidential book went from USD 142.61M to USD 143.62M in one day.`,
  'candidates[0].fracos[0]': `⚠️ IN THE ${G('FIRST-ROUND', 'primeiro-turno')} RUNNER-UP CONTRACT HE GAVE UP 2.90pp, from 10.50% to 7.60% (vol USD 469 thousand), and that is his largest move in any contract in this reading.`,
  'candidates[0].analise': `His day is the opposite of yesterday's. On 03/Sep the price did not move for more than eight hours while three national polls were published within 48 hours. Today no national poll was released and his price rose 1.00pp, to 55.50% (vol USD 9.72M accumulated). The gap to the runner-up reopened by 3.70pp and is back to 15.35pp, undoing much of the narrowing accumulated since 01/Sep. 📌 The panel records the coincidence of dates and assigns no cause: there is no new poll to explain the move, and the day's only high-impact act is from the ${G('Supreme Court', 'stf')}, not from the campaign. ⚠️ And there is a contrast inside his own reading: in the winner contract he rose, and in the first-round runner-up contract he gave up 2.90pp, from 10.50% to 7.60%. They are two different markets on the same name, and in this reading they disagree.`,

  'candidates[1].header': `PRICE: 40.15% (vol USD 9.68M accumulated), ${S}, down 2.70pp on the reading of 03/Sep, 23:45, and the largest move of any name in the winner contract in this reading. POLL: no new reading. Datafolha of 03/Sep gives him 32% in the scenario with Marçal and 33% in the one without, and 2 points away in the second round, 44% to 46%.`,

  'candidates[2].header': `PRICE: 1.95% (vol USD 4.07M accumulated), ${S}, up 0.70pp in the winner contract. ⚠️ AND DOWN 5.95pp IN THE ${G('FIRST-ROUND', 'primeiro-turno')} THIRD-PLACE CONTRACT, from 59.50% to 53.55%. POLL: no new reading. The window's five readings run from 7% at Datafolha on 03/Sep to 11% at BTG/Nexus on 31/Aug.`,
  'candidates[2].fortes[2]': `He is still the outright leader of the first-round third-place contract, with 53.55% against 23.50% for that market's second name.`,
  'candidates[2].fracos[0]': `⚠️ HE GAVE UP 5.95pp IN THE THIRD-PLACE CONTRACT, from 59.50% to 53.55% (vol USD 123 thousand), after three straight days of gains in that market.`,
  'candidates[2].analise': `He repeats the runner-up's pattern today, in reverse: he rose 0.70pp in the winner contract, to 1.95% (vol USD 4.07M accumulated), and gave up 5.95pp in the first-round third-place contract, to 53.55% (vol USD 123 thousand). 📌 The two contracts measure different things, and the fall in the third-place one breaks three straight days of gains there. In the runner-up contract he went from 1.75% to 0.95%, meaning all three markets in which he appears moved, and only one of them in his favour. On the polling side there is nothing new: the last measurement is still Datafolha of 03/Sep, at 7% and 8% across the two scenarios, and it remains the only one of the five houses in the window to leave him below double digits.`,

  'candidates[3].header': `PRICE: 1.85% (vol USD 12.64M accumulated), ${S}, up 0.10pp in the winner contract. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.50pp and stands at 23.50% (vol USD 277 thousand). POLL: no new reading. Datafolha of 03/Sep gives him 4% and 3% across the two scenarios.`,
  'candidates[3].fracos[0]': `His gap to the leader of the third-place contract is still wide, 23.50% against 53.55%, or 30.05pp.`,

  'candidates[4].header': `PRICE: Ronaldo Caiado at 0.15% in the WINNER contract (vol USD 7.15M accumulated), below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he stands at 9.00% (vol USD 114 thousand), ${S}, down 1.00pp. Fernando Haddad and Romeu Zema remain below the floor in the winner contract. POLL: no new reading. Datafolha of 03/Sep puts Caiado at 4% in both scenarios and Zema at 2%.`,
  'candidates[4].subtitle': `Back of the pack at the ${S}. ⚠️ THE SECOND-ROUND PAIRING AGAINST RONALDO CAIADO ALREADY HAS FOUR READINGS IN THE SAME WEEK, all with overlapping field periods: ${QUATRO}. No new national poll came in on 04/Sep.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0.15% (vol USD 7.15M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round, which is a different market, he gave up 1.00pp and stands at 9.00%, in a book of USD 114 thousand, ${S}.`,
  'candidates[4].caiado.fracos': `He slipped from 5% to 4% within Datafolha itself between 21/Aug and 03/Sep. In the winner contract he is still below the 0.5% floor, and in the third-place contract he gave up 1.00pp in this reading, from 10.00% to 9.00%. And the second-round pairing in which he appears has already been measured by four houses in the same week, with four different results, and no new poll came in today to break the tie.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0.15% (vol USD 6.55M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round, which is a different market, he stands at 0.70%, in a book of USD 49 thousand, ${S}.`,
  'candidates[4].analise': `The block has no publishable new price in the winner contract: Ronaldo Caiado, Romeu Zema and Fernando Haddad are all below the 0.5% floor of the double reading, and this round publishes no new figure for them in that market. 📌 What does have a reading is the first-round third-place contract, which is a different market: Caiado gave up 1.00pp and stands at 9.00% (vol USD 114 thousand), and Zema stands at 0.70% (vol USD 49 thousand). On the polling side nothing changed: Datafolha of 03/Sep is still the most recent, with Caiado at 4% and Zema at 2%, and the second-round pairing against Caiado at 46% to 41%.`,
  'candidates[4].fortes[0]': `Ronaldo Caiado is still third in the first-round third-place contract, with 9.00% (vol USD 114 thousand), behind only Augusto Cury and Renan Santos.`,
  'candidates[4].fracos[1]': `In the third-place contract he gave up 1.00pp, from 10.00% to 9.00%.`,

  'quadroComparativo[0].m': `55.50% (vol USD 9.72M), ${S}. Up 1.00pp on the reading of 03/Sep, 23:45. The gap to the runner-up went from 11.65pp to 15.35pp, an opening of 3.70pp after four consecutive readings of narrowing. ⚠️ In the first-round runner-up contract he gave up 2.90pp and now stands at 7.60% (vol USD 469 thousand).`,
  'quadroComparativo[1].m': `40.15% (vol USD 9.68M), ${S}. ⚠️ DOWN 2.70pp, the largest move of any name in the presidential book in this reading. ⭐ AND IN THE FIRST-ROUND RUNNER-UP CONTRACT HE ROSE 4.00pp, to 87.50% (vol USD 586 thousand). The two contracts moved in opposite directions.`,
  'quadroComparativo[2].m': `1.95% (vol USD 4.07M), ${S}. Up 0.70pp in the winner contract, with around USD 380 thousand of new volume in one day. ⚠️ In the first-round third-place contract he gave up 5.95pp and now stands at 53.55% (vol USD 123 thousand), breaking three straight days of gains, and in the runner-up contract he fell from 1.75% to 0.95%.`,
  'quadroComparativo[3].m': `1.85% (vol USD 12.64M), ${S}. Up 0.10pp in the winner contract. In the first-round third-place contract he rose 1.50pp and now stands at 23.50% (vol USD 277 thousand), recovering part of the 4.50pp he had given up in the previous reading.`,
  'quadroComparativo[4].m': `0.15% (vol USD 7.15M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round, which is a different market, he gave up 1.00pp and stands at 9.00% (vol USD 114 thousand), ${S}.`,
  'quadroComparativo[4].t': `no new price in the winner contract, and down 1.00pp in the third-place one`,
  'quadroComparativo[5].m': `0.15% (vol USD 3.69M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round he stands at 2.70% (vol USD 47 thousand), ${S}.`,
  'quadroComparativo[6].m': `15.85% (vol USD 87 thousand), ${SU}. ${FAIXA}`,
  'quadroComparativo[6].t': `it travelled 8.70pp within the day on USD 28 of new money, and goes out with the range alongside`,

  cruzamento: `4 September is the exact inverse of the day before, and that is what this page records. ⭐ NO NEW NATIONAL POLL WAS RELEASED, and that is not a collection gap: the ${G('TSE', 'tse')} register shows seven national polls IN THE FIELD right now, and the first scheduled release is 06/Sep, from Veritá. Then come Quaest on 07/Sep, Gerp and Nexus on 08/Sep, and Ideia/Canal Meio, Real Time Big Data and PALVER on 09/Sep. PALVER has the calendar's largest sample, with 5,000 interviews. On 03/Sep there were three national polls within 48 hours and the leader's price sat still for more than eight hours. ⭐ TODAY, WITH NO POLL AT ALL, THE PRICE MOVED MORE THAN YESTERDAY: the gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp that undid four consecutive readings of narrowing. The leader rose 1.00pp, to 55.50%, and the runner-up gave up 2.70pp, to 40.15%, the largest move of any name in the book. 📌 The panel records the coincidence and asserts no cause. There is no voting-intention measurement published today either to support or to contradict the move. ⚠️ THE SECOND DIVERGENCE IS INSIDE THE MARKET ITSELF, and it shows up in two names at once. The runner-up gave up 2.70pp in the winner contract and rose 4.00pp in the ${G('first-round', 'primeiro-turno')} runner-up contract, to 87.50%. Augusto Cury did the opposite: up 0.70pp in the winner contract and down 5.95pp in the third-place one, to 53.55%, breaking three straight days of gains there. They are distinct markets on the same names, and in this reading they do not tell the same story. ⭐ THE THIRD IS THE DAY'S ACT, and it comes from the Supreme Court. Edson Fachin removed from the fake-news inquiry the request by Alexandre de Moraes to investigate André Mendonça and turned it into a separate petition under his own docket, with 5 working days for the prosecutor-general's office, according to Folha de S.Paulo and Gazeta do Povo. Hours later he argued for ending the inquiry, open for seven years, without closing it. 📌 And the contract that measures a Supreme Court justice leaving by impeachment stands at 15.85%, against 7.40% in the reading of 03/Sep at 17:28. ⚠️ IT IS THE PANEL'S ONLY EXCEPTION TO THE DOUBLE READING, and it goes out declared as such because it travelled from 10.60% to 19.30% on 04/Sep, an amplitude of 8.70pp, with USD 28 of new money over the day. The figure is one reading inside that range, and the range is published alongside it. The panel does not say who is right between the price and the poll, and in this round there is one more reason not to: from one of the two sides, nothing came in.`,
})
