/** Mapa EN: analysis-criteriosa da rodada de 04/Set/2026, carimbo 19:07. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 04/Sep, 19:07 BRT (22:07 UTC)'
const DF = 'the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp)'
const SEM = 'No new national poll today. '
const SEMQ = `${SEM}The most recent reading is still ${DF}. `
const SETE =
  'seven national polls are IN THE FIELD right now and the first scheduled release is 06/Sep'
const QUATRO =
  '45% to 43% in his favour at Real Time Big Data on 01/Sep, 42% to 37% against him at Genial/Quaest on 02/Sep, 44% to 42% against him at PoderData on 03/Sep and 46% to 41% against him at Datafolha the same day'

construir('analysis-criteriosa', 'en', {
  subtitle: `Cross-reading for 4 September 2026, ${S}, presidential book at USD 143.57M. ⭐ NO NEW NATIONAL POLL WAS RELEASED TODAY, and the ${G('TSE', 'tse')} register says why: ${SETE}. ⭐ AND IT WAS ON THE DAY WITHOUT A POLL THAT THE PRICE MOVED MOST: the gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp, after narrowing across four consecutive readings. The polling reference is still ${DF}, and it has not changed since yesterday.`,

  'candidates[0].header': `PRICE: 55.50% (vol USD 9.72M accumulated), ${S}, up 1.00pp on the reading of 03/Sep, 23:45. POLL: no new reading. The most recent is still the Datafolha poll of 03/Sep, which gives him 39% in the scenario with Pablo Marçal and 38% in the one without, and winning all four ${G('second-round', 'segundo-turno')} pairings it tested.`,
  'candidates[0].fortes[0]': `He rose 1.00pp and reopened the gap to the runner-up, which goes from 11.65pp to 15.35pp after four consecutive readings of narrowing.`,
  'candidates[0].fortes[1]': `The 3.70pp opening happened on a day with no new national poll, that is, with no voting-intention information entering the market.`,
  'candidates[0].fortes[2]': `He still wins the four second-round pairings tested by Datafolha on 03/Sep, including Ronaldo Caiado by 46% to 41% and Romeu Zema by 48% to 39%.`,
  'candidates[0].fortes[3]': `Accumulated volume in his contract reached USD 9.72M, and the whole presidential book went from USD 142.61M to USD 143.57M in one day.`,
  'candidates[0].fortes[4]': `He is the only one of the four names above 1% whose winner contract rose without another contract on the same name rising against him.`,
  'candidates[0].fracos[0]': `⚠️ IN THE ${G('FIRST-ROUND', 'primeiro-turno')} RUNNER-UP CONTRACT HE GAVE UP 4.70pp, from 10.50% to 5.80% (vol USD 467 thousand), and that is his largest move in any contract in this reading.`,
  'candidates[0].fracos[1]': `Datafolha of 03/Sep, still the most recent poll, halved the second-round gap within the house itself, from 4 to 2 points between 21/Aug and 03/Sep.`,
  'candidates[0].fracos[2]': `Government disapproval at Datafolha is 51% against 45% approval, and no new poll came in today to confirm or contradict that picture.`,
  'candidates[0].fracos[3]': `PoderData of 03/Sep is still the only one of the window's three houses to place him behind in the second round, by 44% to 45%.`,
  'candidates[0].fracos[4]': `The price rose without any voting-intention measurement being published today, so there is no poll supporting the rise.`,
  'candidates[0].analise': `His day is the opposite of yesterday's. On 03/Sep the price did not move for more than eight hours while three national polls were published within 48 hours. Today no national poll was released and his price rose 1.00pp, to 55.50% (vol USD 9.72M accumulated). The gap to the runner-up reopened by 3.70pp and is back to 15.35pp, undoing much of the narrowing accumulated since 01/Sep. 📌 The panel records the coincidence of dates and assigns no cause: there is no new poll to explain the move, and the day's only high-impact act is from the ${G('Supreme Court', 'stf')}, not from the campaign. ⚠️ And there is a contrast inside his own reading: in the winner contract he rose, and in the first-round runner-up contract he gave up 4.70pp, from 10.50% to 5.80%. They are two different markets on the same name, and in this reading they disagree.`,

  'candidates[1].header': `PRICE: 40.15% (vol USD 9.68M accumulated), ${S}, down 2.70pp on the reading of 03/Sep, 23:45, and the largest move of any name in the winner contract in this reading. POLL: no new reading. Datafolha of 03/Sep gives him 32% in the scenario with Marçal and 33% in the one without, and 2 points away in the second round, 44% to 46%.`,
  'candidates[1].fortes[0]': `⭐ IN THE ${G('FIRST-ROUND', 'primeiro-turno')} RUNNER-UP CONTRACT HE ROSE 4.00pp, from 83.50% to 87.50% (vol USD 586 thousand).`,
  'candidates[1].fortes[1]': `Datafolha of 03/Sep, still the most recent poll, keeps him 2 points away in the second round, 44% against 46%, inside the declared margin of 2pp.`,
  'candidates[1].fortes[2]': `The window's three national polls still disagree on the sign of that pairing, and one of them, PoderData of 03/Sep, puts him ahead by 45% to 44%.`,
  'candidates[1].fortes[3]': `Accumulated volume in his contract rose to USD 9.68M, practically level with the leader's, which stands at USD 9.72M.`,
  'candidates[1].fortes[4]': `He said Edson Fachin's decision in the Supreme Court crisis is light at the end of the tunnel, according to Valor Econômico, and that Alexandre de Moraes is in no condition to remain on the court, according to Correio Braziliense.`,
  'candidates[1].fracos[0]': `⚠️ HE GAVE UP 2.70pp IN THE WINNER CONTRACT, from 42.85% to 40.15%, and it is the largest fall of any name in the presidential book in this reading.`,
  'candidates[1].fracos[1]': `The gap to the leader is back to 15.35pp, undoing the narrowing he had been accumulating since 01/Sep, when it stood at 16.55pp.`,
  'candidates[1].fracos[2]': `The fall came on a day with no new national poll, so there is no voting-intention measurement accompanying it.`,
  'candidates[1].fracos[3]': `⚠️ HIS TWO CONTRACTS MOVED IN OPPOSITE DIRECTIONS IN THE SAME READING: down 2.70pp in the winner contract and up 4.00pp in the first-round runner-up contract.`,
  'candidates[1].fracos[4]': `In the first-round third-place contract he appears at 1.55% (vol USD 68 thousand), and that market prices a scenario in which he does not reach the top two.`,
  'candidates[1].analise': `His reading is the strangest of the day, and it is worth describing without rounding. In the winner contract he gave up 2.70pp and stands at 40.15% (vol USD 9.68M accumulated), the largest fall of any name in the book. In the first-round runner-up contract, over the same interval, he rose 4.00pp and stands at 87.50% (vol USD 586 thousand). ⭐ THE TWO MARKETS ARE ABOUT THE SAME NAME AND MOVED IN OPPOSITE DIRECTIONS. One possible reading is that the market cut his chance of winning and raised his chance of finishing the first round in second place, but the panel does not assert that: it records that the two contracts disagreed and that no new poll was published today to arbitrate the disagreement. 📌 The most recent poll is still Datafolha of 03/Sep, which keeps him 2 points away in the second round.`,

  'candidates[2].header': `PRICE: 1.95% (vol USD 4.07M accumulated), ${S}, up 0.70pp in the winner contract. ⚠️ AND DOWN 4.85pp IN THE ${G('FIRST-ROUND', 'primeiro-turno')} THIRD-PLACE CONTRACT, from 59.50% to 54.65%. POLL: no new reading. The window's five readings run from 7% at Datafolha on 03/Sep to 11% at BTG/Nexus on 31/Aug.`,
  'candidates[2].fortes[0]': `He rose 0.70pp in the winner contract, from 1.25% to 1.95%.`,
  'candidates[2].fortes[1]': `Accumulated volume in his contract went from USD 3.69M to USD 4.07M in one day, around USD 380 thousand of new money.`,
  'candidates[2].fortes[2]': `He is still the outright leader of the first-round third-place contract, with 54.65% against 23.50% for that market's second name.`,
  'candidates[2].fortes[3]': `The window's five national houses agree on the direction of his jump, and their disagreement is about level, not sign.`,
  'candidates[2].fracos[0]': `⚠️ HE GAVE UP 4.85pp IN THE THIRD-PLACE CONTRACT, from 59.50% to 54.65% (vol USD 123 thousand), after three straight days of gains in that market.`,
  'candidates[2].fracos[1]': `In the first-round runner-up contract he fell from 1.75% to 0.95% (vol USD 142 thousand), and now sits below 1% in that market.`,
  'candidates[2].fracos[2]': `Dispersion across houses is still wide, from 7% to 11%, and no new poll came in today to narrow it.`,
  'candidates[2].fracos[3]': `In absolute terms his winner contract is still below 2%, and the USD 4.07M of volume sits alongside a price the market treats as remote.`,
  'candidates[2].analise': `He repeats the runner-up's pattern today, in reverse: he rose 0.70pp in the winner contract, to 1.95% (vol USD 4.07M accumulated), and gave up 4.85pp in the first-round third-place contract, to 54.65% (vol USD 123 thousand). 📌 The two contracts measure different things, and the fall in the third-place one breaks three straight days of gains there. In the runner-up contract he went from 1.75% to 0.95%, meaning all three markets in which he appears moved, and only one of them in his favour. On the polling side there is nothing new: the last measurement is still Datafolha of 03/Sep, at 7% and 8% across the two scenarios, and it remains the only one of the five houses in the window to leave him below double digits.`,

  'candidates[3].header': `PRICE: 1.85% (vol USD 12.64M accumulated), ${S}, up 0.10pp in the winner contract. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.50pp and stands at 23.50% (vol USD 277 thousand). POLL: no new reading. Datafolha of 03/Sep gives him 4% and 3% across the two scenarios.`,
  'candidates[3].fortes[0]': `He recovered 1.50pp in the first-round third-place contract, from 22.00% to 23.50%, after giving up 4.50pp in the previous reading.`,
  'candidates[3].fortes[1]': `Among the four names above 1% in the winner contract, his is the largest accumulated volume, at USD 12.64M, ahead of the leader and the runner-up.`,
  'candidates[3].fortes[2]': `He rose 0.10pp in the winner contract, on a day when the book's runner-up gave up 2.70pp.`,
  'candidates[3].fracos[0]': `His gap to the leader of the third-place contract is still wide, 23.50% against 54.65%, or 31.15pp.`,
  'candidates[3].fracos[1]': `In the winner contract he is still below 2%, despite the largest accumulated volume in the pack.`,
  'candidates[3].fracos[2]': `Dispersion across houses in the window runs from 3% to 7.6%, and no new poll came in today to narrow it.`,
  'candidates[3].fracos[3]': `In the first-round runner-up contract he stands at 1.75% (vol USD 1.24M), well behind the leader and the runner-up.`,
  'candidates[3].analise': `His reading is one of partial recovery. In the first-round third-place contract he rose 1.50pp, to 23.50% (vol USD 277 thousand), recovering a third of the 4.50pp he had given up in the reading of 03/Sep. In the winner contract he rose 0.10pp, to 1.85% (vol USD 12.64M accumulated). 📌 His volume is still the panel's most out-of-place figure: among the four names above 1% in the winner contract it is the largest accumulated, ahead of the leader and the runner-up, in a contract the market prices below 2%. The panel records the contrast and does not interpret it. On the polling side, Datafolha of 03/Sep is still the most recent reading and nothing changed today.`,

  'candidates[4].header': `PRICE: Ronaldo Caiado at 0.15% in the WINNER contract (vol USD 7.15M accumulated), below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he stands at 9.50% (vol USD 114 thousand), ${S}, down 0.50pp. Fernando Haddad and Romeu Zema remain below the floor in the winner contract. POLL: no new reading. Datafolha of 03/Sep puts Caiado at 4% in both scenarios and Zema at 2%.`,
  'candidates[4].subtitle': `Back of the pack at the ${S}. ⚠️ THE SECOND-ROUND PAIRING AGAINST RONALDO CAIADO ALREADY HAS FOUR READINGS IN THE SAME WEEK, all with overlapping field periods: ${QUATRO}. No new national poll came in on 04/Sep.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0.15% (vol USD 7.15M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round, which is a different market, he gave up 0.50pp and stands at 9.50%, in a book of USD 114 thousand, ${S}.`,
  'candidates[4].caiado.fortes': `At Datafolha of 03/Sep, still the most recent poll, he has 4% in both first-round scenarios, his best figure among the week's four houses. He is still third in the first-round third-place contract, behind only Augusto Cury and Renan Santos. He took the Supreme Court crisis to television advertising, defended an investigation into alleged bribery by Daniel Vorcaro and took part in a Folha and UOL question-and-answer session this Friday, according to Folha de S.Paulo.`,
  'candidates[4].caiado.fracos': `He slipped from 5% to 4% within Datafolha itself between 21/Aug and 03/Sep. In the winner contract he is still below the 0.5% floor, and in the third-place contract he gave up 0.50pp in this reading, from 10.00% to 9.50%. And the second-round pairing in which he appears has already been measured by four houses in the same week, with four different results, and no new poll came in today to break the tie.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0.15% (vol USD 6.55M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round, which is a different market, he stands at 0.70%, in a book of USD 49 thousand, ${S}.`,
  'candidates[4].zema.fracos': `At Datafolha of 03/Sep he loses by 48% to 39%, a margin of 9 points, and has 2% in the first round against 3% in the same house's round of 21/Aug. ⚠️ The second-round pairing against him is the one with the widest dispersion across houses in the window: the week's four houses measured 3, 11, 2 and 9 points, and no new poll came in on 04/Sep.`,
  'candidates[4].analise': `The block has no publishable new price in the winner contract: Ronaldo Caiado, Romeu Zema and Fernando Haddad are all below the 0.5% floor of the double reading, and this round publishes no new figure for them in that market. 📌 What does have a reading is the first-round third-place contract, which is a different market: Caiado gave up 0.50pp and stands at 9.50% (vol USD 114 thousand), and Zema stands at 0.70% (vol USD 49 thousand). On the polling side nothing changed: Datafolha of 03/Sep is still the most recent, with Caiado at 4% and Zema at 2%, and the second-round pairing against Caiado at 46% to 41%.`,
  'candidates[4].fortes[0]': `Ronaldo Caiado is still third in the first-round third-place contract, with 9.50% (vol USD 114 thousand), behind only Augusto Cury and Renan Santos.`,
  'candidates[4].fortes[1]': `He took the Supreme Court crisis to television advertising and defended an investigation into alleged bribery by Daniel Vorcaro, according to Folha de S.Paulo, and took part in a Folha and UOL question-and-answer session this Friday.`,
  'candidates[4].fortes[2]': `The second-round pairing against him at Datafolha of 03/Sep is 5 points, 46% to 41%, narrower than Romeu Zema's, which is 9 points.`,
  'candidates[4].fracos[0]': `In the winner contract Caiado stands at 0.15%, below the 0.5% floor of the double reading, and this round publishes no new price for him there.`,
  'candidates[4].fracos[1]': `In the third-place contract he gave up 0.50pp, from 10.00% to 9.50%.`,
  'candidates[4].fracos[2]': `Romeu Zema stands at 0.70% in the third-place contract (vol USD 49 thousand) and below the floor in the winner contract.`,
  'candidates[4].fracos[3]': `Fernando Haddad is not a presidential candidate and is running for governor of São Paulo, and his contract is still at 0.05%.`,

  'quadroComparativo[0].p': `${SEM}The most recent reading is still ${DF}. It gives him 39% in the scenario with Pablo Marçal and 38% in the one without, and winning all four ${G('second-round', 'segundo-turno')} pairings it tested: 46% to 44% against the runner-up, 46% to 41% against Ronaldo Caiado and 48% to 39% against Romeu Zema. Government assessment: 45% approve and 51% disapprove.`,
  'quadroComparativo[0].m': `55.50% (vol USD 9.72M), ${S}. Up 1.00pp on the reading of 03/Sep, 23:45. The gap to the runner-up went from 11.65pp to 15.35pp, an opening of 3.70pp after four consecutive readings of narrowing. ⚠️ In the first-round runner-up contract he gave up 4.70pp and now stands at 5.80% (vol USD 467 thousand).`,
  'quadroComparativo[0].t': `he rose in the winner contract and reopened the gap, and gave up in the runner-up contract, over the same interval`,
  'quadroComparativo[0].s': `He said he told Donald Trump that Brazil does not accept interference in its elections, according to G1 and Gazeta do Povo. He said everyone should be investigated and pressed the prosecutor-general's office and the Supreme Court for a resolution of the ${G('Banco Master', 'banco-master')} case, according to Folha de S.Paulo.`,

  'quadroComparativo[1].p': `${SEMQ}It gives him 32% in the scenario with Marçal and 33% in the one without, and 2 points away in the second round, 44% against 46%. ⚠️ THE WINDOW'S THREE NATIONAL POLLS STILL DISAGREE ON THE SIGN OF THAT PAIRING: Genial/${G('Quaest', 'quaest')} of 02/Sep put the leader ahead by 42% to 41%, PoderData of 03/Sep put the runner-up ahead by 45% to 44%, and Datafolha of 03/Sep puts the leader ahead by 46% to 44%.`,
  'quadroComparativo[1].m': `40.15% (vol USD 9.68M), ${S}. ⚠️ DOWN 2.70pp, the largest move of any name in the presidential book in this reading. ⭐ AND IN THE FIRST-ROUND RUNNER-UP CONTRACT HE ROSE 4.00pp, to 87.50% (vol USD 586 thousand). The two contracts moved in opposite directions.`,
  'quadroComparativo[1].t': `the two contracts on the same name disagreed in the same reading, down 2.70pp in one and up 4.00pp in the other`,
  'quadroComparativo[1].s': `He said Edson Fachin's decision in the Supreme Court crisis is light at the end of the tunnel, according to Valor Econômico, and that Alexandre de Moraes is in no condition to remain on the court, according to Correio Braziliense.`,

  'quadroComparativo[2].p': `${SEMQ}It leaves him at 7% in the scenario with Marçal and 8% in the one without, and it is still the only one of the window's five houses to put him below double digits. The five readings: BTG/Nexus 11% on 31/Aug, Real Time Big Data 11% on 01/Sep, Genial/Quaest 10% on 02/Sep, PoderData 10% on 03/Sep and Datafolha 7% and 8% the same day.`,
  'quadroComparativo[2].m': `1.95% (vol USD 4.07M), ${S}. Up 0.70pp in the winner contract, with around USD 380 thousand of new volume in one day. ⚠️ In the first-round third-place contract he gave up 4.85pp and now stands at 54.65% (vol USD 123 thousand), breaking three straight days of gains, and in the runner-up contract he fell from 1.75% to 0.95%.`,
  'quadroComparativo[2].t': `he rose in the winner contract and gave up in the other two markets in which he appears`,
  'quadroComparativo[2].s': `Datafolha published the regional breakdown of its 03/Sep round, according to Folha de S.Paulo. There is no act of his own in this Friday's news.`,

  'quadroComparativo[3].p': `${SEMQ}It gives him 4% in the scenario with Marçal and 3% in the one without. Dispersion across houses in the window runs from 3% to 7.6%, and no new poll came in today to narrow it.`,
  'quadroComparativo[3].m': `1.85% (vol USD 12.64M), ${S}. Up 0.10pp in the winner contract. In the first-round third-place contract he rose 1.50pp and now stands at 23.50% (vol USD 277 thousand), recovering part of the 4.50pp he had given up in the previous reading.`,
  'quadroComparativo[3].t': `he recovered part of the fall in the third-place contract, and still holds the pack's largest accumulated volume`,
  'quadroComparativo[3].s': `The impeachment request he filed against Alexandre de Moraes and Dias Toffoli is still proceeding, according to Gazeta do Povo.`,

  'quadroComparativo[4].p': `${SEMQ}It puts him at 4% in both first-round scenarios and has him losing the second round by 46% to 41%. ⚠️ THE SECOND-ROUND PAIRING AGAINST HIM HAS FOUR READINGS IN THE SAME WEEK AND NO TWO AGREE ON THE MARGIN: ${QUATRO}.`,
  'quadroComparativo[4].m': `0.15% (vol USD 7.15M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round, which is a different market, he gave up 0.50pp and stands at 9.50% (vol USD 114 thousand), ${S}.`,
  'quadroComparativo[4].t': `no new price in the winner contract, and down 0.50pp in the third-place one`,
  'quadroComparativo[4].s': `He took the Supreme Court crisis to television advertising, defended an investigation into alleged bribery by Daniel Vorcaro and took part in a Folha and UOL question-and-answer session this Friday, according to Folha de S.Paulo.`,

  'quadroComparativo[5].p': `${SEMQ}It has him at 2% in the scenario in which he is on the list. His presence separates the house's two scenarios: with Marçal the leader has 39% and the runner-up 32%, and without Marçal the leader has 38% and the runner-up 33%, so the gap goes from 7 to 5 points.`,
  'quadroComparativo[5].m': `0.15% (vol USD 3.64M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the THIRD-PLACE contract of the first round he stands at 2.60% (vol USD 47 thousand), ${S}.`,
  'quadroComparativo[5].t': `no new price in the winner contract, and fourth in the third-place one`,
  'quadroComparativo[5].s': `He does not appear in this Friday's news with an act of his own.`,

  'quadroComparativo[6].p': `No poll. Market on the impeachment of a Supreme Court justice before 2027.`,
  'quadroComparativo[6].m': `⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THIS CONTRACT, for the second day. The last confirmed reading is still the one of 03/Sep at 17:28, at 7.40% (vol USD 87 thousand), and that is the one the page keeps. AFOS only publishes a price that two independent readings confirm, and this contract had no confirmed reading on 04/Sep.`,
  'quadroComparativo[6].t': `no new reading to publish, for the second day running`,
  'quadroComparativo[6].s': `⭐ THE DAY'S ACT: Edson Fachin REMOVED from the fake-news inquiry the request by Alexandre de Moraes to investigate André Mendonça, and created a separate petition under his own docket, with 5 working days for the prosecutor-general's office to respond and another 5 for Mendonça afterwards, according to Folha de S.Paulo and Gazeta do Povo. 📌 The 5-day deadline given to Moraes, Mendonça, Paulo Gonet and Andrei Rodrigues is from 03/Sep, not from this Friday. Hours later, Fachin argued for ENDING the fake-news inquiry, open for seven years, but did not close it, according to Estadão and Gazeta do Povo. The Superior Council of the Federal Prosecution Service opened proceedings concerning Gonet, according to Folha de S.Paulo and Gazeta do Povo. Flávio Dino said the Supreme Court is greater than anyone who sits on it, according to Folha de S.Paulo.`,

  cruzamento: `4 September is the exact inverse of the day before, and that is what this page records. ⭐ NO NEW NATIONAL POLL WAS RELEASED, and that is not a collection gap: the ${G('TSE', 'tse')} register shows seven national polls IN THE FIELD right now, and the first scheduled release is 06/Sep, from Veritá. Then come Quaest on 07/Sep, Gerp and Nexus on 08/Sep, and Ideia/Canal Meio, Real Time Big Data and PALVER on 09/Sep. PALVER has the calendar's largest sample, with 5,000 interviews. On 03/Sep there were three national polls within 48 hours and the leader's price sat still for more than eight hours. ⭐ TODAY, WITH NO POLL AT ALL, THE PRICE MOVED MORE THAN YESTERDAY: the gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp that undid four consecutive readings of narrowing. The leader rose 1.00pp, to 55.50%, and the runner-up gave up 2.70pp, to 40.15%, the largest move of any name in the book. 📌 The panel records the coincidence and asserts no cause. There is no voting-intention measurement published today either to support or to contradict the move. ⚠️ THE SECOND DIVERGENCE IS INSIDE THE MARKET ITSELF, and it shows up in two names at once. The runner-up gave up 2.70pp in the winner contract and rose 4.00pp in the ${G('first-round', 'primeiro-turno')} runner-up contract, to 87.50%. Augusto Cury did the opposite: up 0.70pp in the winner contract and down 4.85pp in the third-place one, to 54.65%, breaking three straight days of gains there. They are distinct markets on the same names, and in this reading they do not tell the same story. ⭐ THE THIRD IS THE DAY'S ACT, and it comes from the Supreme Court. Edson Fachin removed from the fake-news inquiry the request by Alexandre de Moraes to investigate André Mendonça and turned it into a separate petition under his own docket, with 5 working days for the prosecutor-general's office, according to Folha de S.Paulo and Gazeta do Povo. Hours later he argued for ending the inquiry, open for seven years, without closing it. 📌 The contract that measures a Supreme Court justice leaving by impeachment is precisely the one with no confirmed reading in this round, for the second day: the page keeps the 7.40% from the reading of 03/Sep at 17:28, with its own timestamp. AFOS only publishes a price that two independent readings confirm. The panel does not say who is right between the price and the poll, and in this round there is one more reason not to: from one of the two sides, nothing came in.`,
})
