/** Mapa ES: polls-data, republicação de 04/Set/2026 com carimbo 19:53 e o STF no ar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 04/Sep, 19:53 BRT (22:53 UTC)'

construir('polls-data', 'es', {
  'polymarketComparison.note': `Precios de ${G('Polymarket', 'polymarket')} en la ${S}, con el libro presidencial en USD 143,62M. ⭐ NINGUNA ENCUESTA NACIONAL FUE DIVULGADA EL 04/Sep, y el registro del ${G('TSE', 'tse')} dice por qué: siete encuestas nacionales están en campo en este momento y la primera divulgación marcada es el 06/Sep, de Veritá, seguida por Quaest el 07/Sep, Gerp y Nexus el 08/Sep, e Ideia/Canal Meio, Real Time Big Data y PALVER el 09/Sep, esta última con 5.000 entrevistas. ⭐ Y FUE EN EL DÍA SIN ENCUESTA QUE EL PRECIO MÁS SE MOVIÓ: la distancia entre los dos primeros pasó de 11,65pp a 15,35pp, una apertura de 3,70pp que deshizo cuatro lecturas seguidas de estrechamiento. El panel registra la coincidencia de fechas y no atribuye causa. ⚠️ El contrato de destitución de ministro del ${G('Supremo', 'stf')} está en 15,85% y es la única excepción del panel a la doble lectura: recorrió de 10,60% a 19,30% el 04/Sep, amplitud de 8,70pp, con USD 28 de dinero nuevo, y sale declarado como lectura única, con la franja al lado.`,
  'polymarketComparison.sources': `Precios de Polymarket vía el proxy AFOS, y el panel solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20pp. La confirmación se hace contrato a contrato. El 04/Sep los libros de ganador, de 2º lugar, de 3º lugar de la primera vuelta y de mayoría en el Senado confirmaron en la lectura de las 19:53. ⚠️ El contrato de destitución de ministro del Supremo es la única excepción y sale con lectura ÚNICA, declarada como tal y acompañada de la franja que recorrió en el día, medida en la serie grabada en backup/neon/marketPrice. Encuestas registradas en el TSE y divulgadas por las casas encuestadoras, con reporte de Poder360, Gazeta do Povo, CNN Brasil, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC y Jornal de Brasília. El calendario de encuestas en campo y de divulgación prevista sale del registro oficial del TSE. Superlativo de serie verificado en el respaldo de Neon, en backup/neon/marketPrice, que guarda el registro completo desde el 14/Abr.`,

  'polymarketComparison.candidates[0].tendenciaPolymarket': `55,50% (vol USD 9,72M), ${S}. Alza de 1,00pp sobre la lectura del 03/Sep, 23:45. ⭐ LA DISTANCIA HACIA EL SEGUNDO REABRIÓ 3,70pp, de 11,65pp a 15,35pp, tras encogerse en cuatro lecturas seguidas, y eso ocurrió en un día sin ninguna encuesta nacional nueva. ⚠️ En el contrato de 2º lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 2,90pp y pasa a 7,60% (vol USD 469 mil).`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40,15% (vol USD 9,68M), ${S}. ⚠️ CAÍDA DE 2,70pp, la mayor variación de cualquier nombre del libro presidencial en esta lectura. ⭐ Y SUS DOS CONTRATOS SE MOVIERON EN SENTIDOS CONTRARIOS: en el de 2º lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 4,00pp y pasa a 87,50% (vol USD 586 mil). En el de 3º lugar aparece con 1,55% (vol USD 68 mil).`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,95% (vol USD 4,07M), ${S}. Alza de 0,70pp en el contrato de ganador, con cerca de USD 380 mil de volumen nuevo en un día. ⚠️ En el contrato de 3º lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 5,95pp y pasa a 53,55% (vol USD 123 mil), interrumpiendo tres días seguidos de alza. Y en el contrato de 2º lugar de la primera vuelta, que es un tercer mercado, retrocedió 0,80pp, de 1,75% a 0,95% en aquel libro, que acumula USD 142 mil.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,85% (vol USD 12,64M), ${S}. Alza de 0,10pp en el contrato de ganador. En el contrato de 3º lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,50pp y pasa a 23,50% (vol USD 277 mil), recuperando parte de los 4,50pp que había cedido en la lectura anterior. 📌 Entre los cuatro nombres por encima de 1% en el contrato de ganador, es el de mayor volumen acumulado, por delante del líder y del segundo colocado, en un contrato descontado por debajo de 2%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,15% (vol USD 7,15M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, cedió 1,00pp y está en 9,00% (vol USD 114 mil), ${S}.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,69M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la ${G('primera vuelta', 'primeiro-turno')} está en 2,70% (vol USD 47 mil), ${S}.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,15% (vol USD 6,55M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, está en 0,70% (vol USD 49 mil), ${S}.`,
})
