/** Mapa ES: analysis-criteriosa, republicação de 04/Set/2026 com carimbo 19:53 e o STF no ar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 04/Sep, 19:53 BRT (22:53 UTC)'
const SU = 'lectura del 04/Sep, 19:53 BRT (22:53 UTC)'
const DF = 'la encuesta de Datafolha del 03/Sep (BR-03669/2026, campo del 01 al 03/Sep, n=2.002, margen de 2pp)'
const QUATRO =
  '45% a 43% a favor de él en Real Time Big Data del 01/Sep, 42% a 37% en contra en Genial/Quaest del 02/Sep, 44% a 42% en contra en PoderData del 03/Sep y 46% a 41% en contra en Datafolha del mismo día'
const FAIXA =
  `⚠️ ESTE ES EL ÚNICO CONTRATO DEL PANEL QUE SALE SIN LA DOBLE LECTURA que AFOS aplica a los demás, ` +
  `y la razón está en la propia serie grabada: el 04/Sep recorrió de 10,60% a 19,30%, amplitud de 8,70pp, ` +
  `con USD 28 de dinero nuevo en todo el día. 📌 La cifra de arriba es UNA lectura dentro de esa franja, no su centro. ` +
  `En los cuatro días anteriores la amplitud diaria fue de 0,10pp, 15,60pp, 4,10pp y 6,30pp, con USD 0, USD 1.852, ` +
  `USD 69 y USD 157 de dinero nuevo. Es el libro más pequeño del panel y el más sensible a una orden pequeña.`

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 4 de septiembre de 2026, ${S}, libro presidencial en USD 143,62M. ⭐ NINGUNA ENCUESTA NACIONAL NUEVA FUE DIVULGADA HOY, y el registro del ${G('TSE', 'tse')} dice por qué: siete encuestas nacionales están EN CAMPO en este momento y la primera divulgación marcada es el 06/Sep. ⭐ Y FUE EN EL DÍA SIN ENCUESTA QUE EL PRECIO MÁS SE MOVIÓ: la distancia entre los dos primeros pasó de 11,65pp a 15,35pp, una apertura de 3,70pp, tras encogerse en cuatro lecturas seguidas. La referencia de encuesta sigue siendo ${DF}, y no cambió desde ayer.`,

  'candidates[0].header': `PRECIO: 55,50% (vol USD 9,72M acumulado), ${S}, alza de 1,00pp sobre la lectura del 03/Sep, 23:45. ENCUESTA: sin lectura nueva. La más reciente sigue siendo la encuesta de Datafolha del 03/Sep, que lo da en 39% en el escenario con Pablo Marçal y 38% en el escenario sin él, y ganando los cuatro pares de ${G('segunda vuelta', 'segundo-turno')} que probó.`,
  'candidates[0].fortes[3]': `El volumen acumulado en su contrato llegó a USD 9,72M, y el libro presidencial entero pasó de USD 142,61M a USD 143,62M en un día.`,
  'candidates[0].fracos[0]': `⚠️ EN EL CONTRATO DE 2º LUGAR DE LA ${G('PRIMERA VUELTA', 'primeiro-turno')} CEDIÓ 2,90pp, de 10,50% a 7,60% (vol USD 469 mil), y esa es su mayor variación en cualquier contrato en esta lectura.`,
  'candidates[0].analise': `Su día es lo opuesto al de ayer. El 03/Sep el precio no se movió por más de ocho horas mientras tres encuestas nacionales eran publicadas en 48 horas. Hoy ninguna encuesta nacional fue divulgada y su precio subió 1,00pp, a 55,50% (vol USD 9,72M acumulado). La distancia hacia el segundo reabrió 3,70pp y volvió a 15,35pp, deshaciendo buena parte del estrechamiento acumulado desde el 01/Sep. 📌 El panel registra la coincidencia de fechas y no atribuye causa: no existe encuesta nueva para explicar el movimiento, y el único acto de alto impacto del día es del ${G('Supremo', 'stf')}, no de la campaña. ⚠️ Y hay un contraste dentro de su propia lectura: en el contrato de ganador subió, y en el de 2º lugar de la primera vuelta cedió 2,90pp, de 10,50% a 7,60%. Son dos mercados distintos sobre el mismo nombre, y en esta lectura discrepan.`,

  'candidates[1].header': `PRECIO: 40,15% (vol USD 9,68M acumulado), ${S}, caída de 2,70pp sobre la lectura del 03/Sep, 23:45, y la mayor variación de cualquier nombre en el contrato de ganador en esta lectura. ENCUESTA: sin lectura nueva. Datafolha del 03/Sep lo da en 32% en el escenario con Marçal y 33% en el escenario sin él, y a 2 puntos en la segunda vuelta, 44% a 46%.`,

  'candidates[2].header': `PRECIO: 1,95% (vol USD 4,07M acumulado), ${S}, alza de 0,70pp en el contrato de ganador. ⚠️ Y CAÍDA DE 5,95pp EN EL CONTRATO DE 3º LUGAR DE LA ${G('PRIMERA VUELTA', 'primeiro-turno')}, de 59,50% a 53,55%. ENCUESTA: sin lectura nueva. Las cinco lecturas de la ventana van de 7% en Datafolha del 03/Sep a 11% en BTG/Nexus del 31/Ago.`,
  'candidates[2].fortes[2]': `Sigue líder aislado del contrato de 3º lugar de la primera vuelta, con 53,55% contra 23,50% del segundo colocado de ese mercado.`,
  'candidates[2].fracos[0]': `⚠️ CEDIÓ 5,95pp EN EL CONTRATO DE 3º LUGAR, de 59,50% a 53,55% (vol USD 123 mil), tras tres días seguidos de alza en ese mercado.`,
  'candidates[2].analise': `Repite hoy el mismo patrón del segundo colocado, y en sentido invertido: subió 0,70pp en el contrato de ganador, a 1,95% (vol USD 4,07M acumulado), y cedió 5,95pp en el de 3º lugar de la primera vuelta, a 53,55% (vol USD 123 mil). 📌 Los dos contratos miden cosas distintas, y la caída en el de 3º lugar interrumpe tres días seguidos de alza allí. En el contrato de 2º lugar pasó de 1,75% a 0,95%, es decir, los tres mercados en los que aparece se movieron, y solo uno de ellos a favor. Del lado de la encuesta no hay nada nuevo: la última medición sigue siendo Datafolha del 03/Sep, con 7% y 8% en los dos escenarios, y sigue siendo la única de las cinco casas de la ventana que lo deja por debajo de dos dígitos.`,

  'candidates[3].header': `PRECIO: 1,85% (vol USD 12,64M acumulado), ${S}, alza de 0,10pp en el contrato de ganador. En el contrato de 3º lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,50pp y está en 23,50% (vol USD 277 mil). ENCUESTA: sin lectura nueva. Datafolha del 03/Sep lo da en 4% y 3% en los dos escenarios.`,
  'candidates[3].fracos[0]': `Su distancia hacia el primer colocado del contrato de 3º lugar sigue siendo amplia, 23,50% contra 53,55%, o 30,05pp.`,

  'candidates[4].header': `PRECIO: Ronaldo Caiado en 0,15% en el contrato de GANADOR (vol USD 7,15M acumulado), por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, está en 9,00% (vol USD 114 mil), ${S}, caída de 1,00pp. Fernando Haddad y Romeu Zema siguen por debajo del piso en el contrato de ganador. ENCUESTA: sin lectura nueva. Datafolha del 03/Sep coloca a Caiado en 4% en los dos escenarios y a Zema en 2%.`,
  'candidates[4].subtitle': `Pelotón de atrás en la ${S}. ⚠️ EL PAR DE SEGUNDA VUELTA CONTRA RONALDO CAIADO YA TIENE CUATRO LECTURAS EN LA MISMA SEMANA, todas con campo superpuesto: ${QUATRO}. Ninguna encuesta nacional nueva entró el 04/Sep.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0,15% (vol USD 7,15M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cedió 1,00pp y está en 9,00%, en un libro de USD 114 mil, ${S}.`,
  'candidates[4].caiado.fracos': `Cedió de 5% a 4% dentro de la propia Datafolha entre el 21/Ago y el 03/Sep. En el contrato de ganador sigue por debajo del piso de 0,5%, y en el de 3º lugar cedió 1,00pp en esta lectura, de 10,00% a 9,00%. Y el par de segunda vuelta en que aparece ya fue medido por cuatro casas en la misma semana, con cuatro resultados distintos, y ninguna encuesta nueva entró hoy para desempatar.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,55M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, está en 0,70%, en un libro de USD 49 mil, ${S}.`,
  'candidates[4].analise': `El bloque no tiene precio nuevo publicable en el contrato de ganador: Ronaldo Caiado, Romeu Zema y Fernando Haddad están todos por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica número nuevo para ellos en ese mercado. 📌 Lo que sí tiene lectura es el contrato de 3º lugar de la primera vuelta, que es otro mercado: Caiado cedió 1,00pp y está en 9,00% (vol USD 114 mil), y Zema está en 0,70% (vol USD 49 mil). Del lado de la encuesta nada cambió: Datafolha del 03/Sep sigue siendo la más reciente, con Caiado en 4% y Zema en 2%, y el par de segunda vuelta contra Caiado en 46% a 41%.`,
  'candidates[4].fortes[0]': `Ronaldo Caiado sigue tercero en el contrato de 3º lugar de la primera vuelta, con 9,00% (vol USD 114 mil), detrás solo de Augusto Cury y Renan Santos.`,
  'candidates[4].fracos[1]': `En el contrato de 3º lugar cedió 1,00pp, de 10,00% a 9,00%.`,

  'quadroComparativo[0].m': `55,50% (vol USD 9,72M), ${S}. Alza de 1,00pp sobre la lectura del 03/Sep, 23:45. La distancia hacia el segundo pasó de 11,65pp a 15,35pp, una apertura de 3,70pp tras cuatro lecturas seguidas encogiéndose. ⚠️ En el contrato de 2º lugar de la primera vuelta cedió 2,90pp y pasa a 7,60% (vol USD 469 mil).`,
  'quadroComparativo[1].m': `40,15% (vol USD 9,68M), ${S}. ⚠️ CAÍDA DE 2,70pp, la mayor variación de cualquier nombre del libro presidencial en esta lectura. ⭐ Y EN EL CONTRATO DE 2º LUGAR DE LA PRIMERA VUELTA SUBIÓ 4,00pp, a 87,50% (vol USD 586 mil). Los dos contratos se movieron en sentidos contrarios.`,
  'quadroComparativo[2].m': `1,95% (vol USD 4,07M), ${S}. Alza de 0,70pp en el contrato de ganador, con cerca de USD 380 mil de volumen nuevo en un día. ⚠️ En el contrato de 3º lugar de la primera vuelta cedió 5,95pp y pasa a 53,55% (vol USD 123 mil), interrumpiendo tres días seguidos de alza, y en el de 2º lugar cayó de 1,75% a 0,95%.`,
  'quadroComparativo[3].m': `1,85% (vol USD 12,64M), ${S}. Alza de 0,10pp en el contrato de ganador. En el contrato de 3º lugar de la primera vuelta subió 1,50pp y pasa a 23,50% (vol USD 277 mil), recuperando parte de los 4,50pp que había cedido en la lectura anterior.`,
  'quadroComparativo[4].m': `0,15% (vol USD 7,15M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cedió 1,00pp y está en 9,00% (vol USD 114 mil), ${S}.`,
  'quadroComparativo[4].t': `sin precio nuevo en el contrato de ganador, y caída de 1,00pp en el de 3º lugar`,
  'quadroComparativo[5].m': `0,15% (vol USD 3,69M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta está en 2,70% (vol USD 47 mil), ${S}.`,
  'quadroComparativo[6].m': `15,85% (vol USD 87 mil), ${SU}. ${FAIXA}`,
  'quadroComparativo[6].t': `recorrió 8,70pp dentro del día con USD 28 de dinero nuevo, y sale con la franja al lado`,

  cruzamento: `El 4 de septiembre es el inverso exacto del día anterior, y es eso lo que la página registra. ⭐ NO SALIÓ NINGUNA ENCUESTA NACIONAL NUEVA, y eso no es un vacío de recolección: el registro del ${G('TSE', 'tse')} muestra siete encuestas nacionales EN CAMPO en este momento, y la primera divulgación marcada es el 06/Sep, de Veritá. Después vienen Quaest el 07/Sep, Gerp y Nexus el 08/Sep, e Ideia/Canal Meio, Real Time Big Data y PALVER el 09/Sep. PALVER es la mayor muestra del calendario, con 5.000 entrevistas. El 03/Sep fueron tres nacionales en 48 horas y el precio del líder quedó estancado por más de ocho horas. ⭐ HOY, SIN NINGUNA ENCUESTA, EL PRECIO SE MOVIÓ MÁS QUE AYER: la distancia entre los dos primeros pasó de 11,65pp a 15,35pp, una apertura de 3,70pp que deshizo cuatro lecturas seguidas de estrechamiento. El líder subió 1,00pp, a 55,50%, y el segundo cedió 2,70pp, a 40,15%, la mayor variación de cualquier nombre del libro. 📌 El panel registra la coincidencia y no afirma causa. No hay medición de intención de voto publicada hoy para sostener ni para desmentir el movimiento. ⚠️ LA SEGUNDA DIVERGENCIA ESTÁ DENTRO DEL PROPIO MERCADO, y aparece en dos nombres a la vez. El segundo colocado cedió 2,70pp en el contrato de ganador y subió 4,00pp en el de 2º lugar de la ${G('primera vuelta', 'primeiro-turno')}, a 87,50%. Augusto Cury hizo lo contrario: subió 0,70pp en el de ganador y cedió 5,95pp en el de 3º lugar, a 53,55%, interrumpiendo tres días seguidos de alza allí. Son mercados distintos sobre los mismos nombres, y en esta lectura no cuentan la misma historia. ⭐ LA TERCERA ES EL ACTO DEL DÍA, y es del Supremo. Edson Fachin retiró de la investigación de las fake news el pedido de Alexandre de Moraes para investigar a André Mendonça y lo transformó en una petición propia bajo su propia relatoría, con 5 días hábiles para la Fiscalía General, según Folha de S.Paulo y Gazeta do Povo. Horas después defendió el fin de la investigación, abierta hace siete años, sin cerrarla. 📌 Y el contrato que mide la salida de un ministro del Supremo por destitución está en 15,85%, contra 7,40% en la lectura del 03/Sep a las 17:28. ⚠️ ES LA ÚNICA EXCEPCIÓN DEL PANEL A LA DOBLE LECTURA, y sale declarado así porque recorrió de 10,60% a 19,30% el 04/Sep, amplitud de 8,70pp, con USD 28 de dinero nuevo en el día. La cifra es una lectura dentro de esa franja, y la franja se publica al lado. El panel no dice quién tiene razón entre el precio y la encuesta, y en esta ronda hay una razón más para no decirlo: de uno de los dos lados no vino nada.`,
})
