/** Mapa ES: analysis-criteriosa da rodada de 04/Set/2026, carimbo 19:07. Vírgula decimal, ponto de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 04/Sep, 19:07 BRT (22:07 UTC)'
const DF = 'la encuesta de Datafolha del 03/Sep (BR-03669/2026, campo del 01 al 03/Sep, n=2.002, margen de 2pp)'
const SEM = 'Sin encuesta nacional nueva hoy. '
const SEMQ = `${SEM}La lectura más reciente sigue siendo ${DF}. `
const SETE = 'siete encuestas nacionales están EN CAMPO en este momento y la primera divulgación marcada es el 06/Sep'
const QUATRO =
  '45% a 43% a favor de él en Real Time Big Data del 01/Sep, 42% a 37% en contra en Genial/Quaest del 02/Sep, 44% a 42% en contra en PoderData del 03/Sep y 46% a 41% en contra en Datafolha del mismo día'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 4 de septiembre de 2026, ${S}, libro presidencial en USD 143,57M. ⭐ NINGUNA ENCUESTA NACIONAL NUEVA FUE DIVULGADA HOY, y el registro del ${G('TSE', 'tse')} dice por qué: ${SETE}. ⭐ Y FUE EN EL DÍA SIN ENCUESTA QUE EL PRECIO MÁS SE MOVIÓ: la distancia entre los dos primeros pasó de 11,65pp a 15,35pp, una apertura de 3,70pp, tras encogerse en cuatro lecturas seguidas. La referencia de encuesta sigue siendo ${DF}, y no cambió desde ayer.`,

  'candidates[0].header': `PRECIO: 55,50% (vol USD 9,72M acumulado), ${S}, alza de 1,00pp sobre la lectura del 03/Sep, 23:45. ENCUESTA: sin lectura nueva. La más reciente sigue siendo la encuesta de Datafolha del 03/Sep, que lo da en 39% en el escenario con Pablo Marçal y 38% en el escenario sin él, y ganando los cuatro pares de ${G('segunda vuelta', 'segundo-turno')} que probó.`,
  'candidates[0].fortes[0]': `Subió 1,00pp y reabrió la distancia hacia el segundo, que pasa de 11,65pp a 15,35pp tras cuatro lecturas seguidas encogiéndose.`,
  'candidates[0].fortes[1]': `La apertura de 3,70pp ocurrió en un día sin ninguna encuesta nacional nueva, es decir, sin información de intención de voto entrando en el mercado.`,
  'candidates[0].fortes[2]': `Sigue ganando los cuatro pares de segunda vuelta probados por Datafolha del 03/Sep, incluido el de Ronaldo Caiado por 46% a 41% y el de Romeu Zema por 48% a 39%.`,
  'candidates[0].fortes[3]': `El volumen acumulado en su contrato llegó a USD 9,72M, y el libro presidencial entero pasó de USD 142,61M a USD 143,57M en un día.`,
  'candidates[0].fortes[4]': `Es el único de los cuatro nombres por encima de 1% cuyo contrato de ganador subió sin que otro contrato del mismo nombre subiera en su contra.`,
  'candidates[0].fracos[0]': `⚠️ EN EL CONTRATO DE 2º LUGAR DE LA ${G('PRIMERA VUELTA', 'primeiro-turno')} CEDIÓ 4,70pp, de 10,50% a 5,80% (vol USD 467 mil), y esa es su mayor variación en cualquier contrato en esta lectura.`,
  'candidates[0].fracos[1]': `Datafolha del 03/Sep, que sigue siendo la encuesta más reciente, redujo a la mitad la distancia de la segunda vuelta dentro de la propia casa, de 4 a 2 puntos entre el 21/Ago y el 03/Sep.`,
  'candidates[0].fracos[2]': `La desaprobación del gobierno en Datafolha es de 51% contra 45% de aprobación, y ninguna encuesta nueva entró hoy para confirmar o desmentir ese cuadro.`,
  'candidates[0].fracos[3]': `PoderData del 03/Sep sigue siendo la única de las tres casas de la ventana que lo coloca detrás en la segunda vuelta, por 44% a 45%.`,
  'candidates[0].fracos[4]': `El precio subió sin que ninguna medición de intención de voto haya sido publicada hoy, así que no hay encuesta que sostenga el alza.`,
  'candidates[0].analise': `Su día es lo opuesto al de ayer. El 03/Sep el precio no se movió por más de ocho horas mientras tres encuestas nacionales eran publicadas en 48 horas. Hoy ninguna encuesta nacional fue divulgada y su precio subió 1,00pp, a 55,50% (vol USD 9,72M acumulado). La distancia hacia el segundo reabrió 3,70pp y volvió a 15,35pp, deshaciendo buena parte del estrechamiento acumulado desde el 01/Sep. 📌 El panel registra la coincidencia de fechas y no atribuye causa: no existe encuesta nueva para explicar el movimiento, y el único acto de alto impacto del día es del ${G('Supremo', 'stf')}, no de la campaña. ⚠️ Y hay un contraste dentro de su propia lectura: en el contrato de ganador subió, y en el de 2º lugar de la primera vuelta cedió 4,70pp, de 10,50% a 5,80%. Son dos mercados distintos sobre el mismo nombre, y en esta lectura discrepan.`,

  'candidates[1].header': `PRECIO: 40,15% (vol USD 9,68M acumulado), ${S}, caída de 2,70pp sobre la lectura del 03/Sep, 23:45, y la mayor variación de cualquier nombre en el contrato de ganador en esta lectura. ENCUESTA: sin lectura nueva. Datafolha del 03/Sep lo da en 32% en el escenario con Marçal y 33% en el escenario sin él, y a 2 puntos en la segunda vuelta, 44% a 46%.`,
  'candidates[1].fortes[0]': `⭐ EN EL CONTRATO DE 2º LUGAR DE LA ${G('PRIMERA VUELTA', 'primeiro-turno')} SUBIÓ 4,00pp, de 83,50% a 87,50% (vol USD 586 mil).`,
  'candidates[1].fortes[1]': `Datafolha del 03/Sep, aún la encuesta más reciente, lo mantiene a 2 puntos en la segunda vuelta, 44% contra 46%, dentro del margen declarado de 2pp.`,
  'candidates[1].fortes[2]': `Las tres nacionales de la ventana siguen discrepando en el signo de ese par, y una de ellas, PoderData del 03/Sep, lo da adelante por 45% a 44%.`,
  'candidates[1].fortes[3]': `El volumen acumulado en su contrato subió a USD 9,68M, prácticamente empatado con el del líder, que está en USD 9,72M.`,
  'candidates[1].fortes[4]': `Dijo que la decisión de Edson Fachin en la crisis del Supremo es luz al final del túnel, según Valor Econômico, y que Alexandre de Moraes no está en condiciones de seguir en el tribunal, según Correio Braziliense.`,
  'candidates[1].fracos[0]': `⚠️ CEDIÓ 2,70pp EN EL CONTRATO DE GANADOR, de 42,85% a 40,15%, y es la mayor caída de cualquier nombre del libro presidencial en esta lectura.`,
  'candidates[1].fracos[1]': `La distancia hacia el líder volvió a 15,35pp, deshaciendo el estrechamiento que venía acumulando desde el 01/Sep, cuando estaba en 16,55pp.`,
  'candidates[1].fracos[2]': `La caída vino en un día sin ninguna encuesta nacional nueva, así que no hay medición de intención de voto que la acompañe.`,
  'candidates[1].fracos[3]': `⚠️ SUS DOS CONTRATOS SE MOVIERON EN DIRECCIONES OPUESTAS EN LA MISMA LECTURA: menos 2,70pp en el de ganador y más 4,00pp en el de 2º lugar de la primera vuelta.`,
  'candidates[1].fracos[4]': `En el contrato de 3º lugar de la primera vuelta aparece con 1,55% (vol USD 68 mil), y ese mercado descuenta un escenario en el que no llega a los dos primeros.`,
  'candidates[1].analise': `Su lectura es la más extraña del día, y vale describirla sin redondear. En el contrato de ganador cedió 2,70pp y está en 40,15% (vol USD 9,68M acumulado), la mayor caída de cualquier nombre del libro. En el contrato de 2º lugar de la primera vuelta, en el mismo intervalo, subió 4,00pp y está en 87,50% (vol USD 586 mil). ⭐ LOS DOS MERCADOS SON SOBRE EL MISMO NOMBRE Y SE MOVIERON EN SENTIDOS CONTRARIOS. Una lectura posible es que el mercado haya reducido la probabilidad de que gane y aumentado la de que termine la primera vuelta en segundo lugar, pero el panel no lo afirma: registra que los dos contratos discreparon y que ninguna encuesta nueva fue publicada hoy para arbitrar la discrepancia. 📌 La encuesta más reciente sigue siendo Datafolha del 03/Sep, que lo mantiene a 2 puntos en la segunda vuelta.`,

  'candidates[2].header': `PRECIO: 1,95% (vol USD 4,07M acumulado), ${S}, alza de 0,70pp en el contrato de ganador. ⚠️ Y CAÍDA DE 4,85pp EN EL CONTRATO DE 3º LUGAR DE LA ${G('PRIMERA VUELTA', 'primeiro-turno')}, de 59,50% a 54,65%. ENCUESTA: sin lectura nueva. Las cinco lecturas de la ventana van de 7% en Datafolha del 03/Sep a 11% en BTG/Nexus del 31/Ago.`,
  'candidates[2].fortes[0]': `Subió 0,70pp en el contrato de ganador, de 1,25% a 1,95%.`,
  'candidates[2].fortes[1]': `El volumen acumulado en su contrato pasó de USD 3,69M a USD 4,07M en un día, cerca de USD 380 mil de dinero nuevo.`,
  'candidates[2].fortes[2]': `Sigue líder aislado del contrato de 3º lugar de la primera vuelta, con 54,65% contra 23,50% del segundo colocado de ese mercado.`,
  'candidates[2].fortes[3]': `Las cinco casas nacionales de la ventana coinciden en la dirección de su salto, y la discrepancia entre ellas es de nivel, no de signo.`,
  'candidates[2].fracos[0]': `⚠️ CEDIÓ 4,85pp EN EL CONTRATO DE 3º LUGAR, de 59,50% a 54,65% (vol USD 123 mil), tras tres días seguidos de alza en ese mercado.`,
  'candidates[2].fracos[1]': `En el contrato de 2º lugar de la primera vuelta cayó de 1,75% a 0,95% (vol USD 142 mil), y pasa a estar por debajo de 1% en ese mercado.`,
  'candidates[2].fracos[2]': `La dispersión entre casas sigue siendo grande, de 7% a 11%, y ninguna encuesta nueva entró hoy para reducirla.`,
  'candidates[2].fracos[3]': `En términos absolutos su contrato de ganador sigue por debajo de 2%, y el volumen de USD 4,07M convive con un precio que el mercado trata como remoto.`,
  'candidates[2].analise': `Repite hoy el mismo patrón del segundo colocado, y en sentido invertido: subió 0,70pp en el contrato de ganador, a 1,95% (vol USD 4,07M acumulado), y cedió 4,85pp en el de 3º lugar de la primera vuelta, a 54,65% (vol USD 123 mil). 📌 Los dos contratos miden cosas distintas, y la caída en el de 3º lugar interrumpe tres días seguidos de alza allí. En el contrato de 2º lugar pasó de 1,75% a 0,95%, es decir, los tres mercados en los que aparece se movieron, y solo uno de ellos a favor. Del lado de la encuesta no hay nada nuevo: la última medición sigue siendo Datafolha del 03/Sep, con 7% y 8% en los dos escenarios, y sigue siendo la única de las cinco casas de la ventana que lo deja por debajo de dos dígitos.`,

  'candidates[3].header': `PRECIO: 1,85% (vol USD 12,64M acumulado), ${S}, alza de 0,10pp en el contrato de ganador. En el contrato de 3º lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,50pp y está en 23,50% (vol USD 277 mil). ENCUESTA: sin lectura nueva. Datafolha del 03/Sep lo da en 4% y 3% en los dos escenarios.`,
  'candidates[3].fortes[0]': `Recuperó 1,50pp en el contrato de 3º lugar de la primera vuelta, de 22,00% a 23,50%, tras haber cedido 4,50pp en la lectura anterior.`,
  'candidates[3].fortes[1]': `Entre los cuatro nombres por encima de 1% en el contrato de ganador, es el de mayor volumen acumulado, con USD 12,64M, por delante del líder y del segundo colocado.`,
  'candidates[3].fortes[2]': `Subió 0,10pp en el contrato de ganador, en un día en que el segundo colocado del libro cedió 2,70pp.`,
  'candidates[3].fracos[0]': `Su distancia hacia el primer colocado del contrato de 3º lugar sigue siendo amplia, 23,50% contra 54,65%, o 31,15pp.`,
  'candidates[3].fracos[1]': `En el contrato de ganador sigue por debajo de 2%, pese al mayor volumen acumulado del pelotón.`,
  'candidates[3].fracos[2]': `La dispersión entre casas en la ventana va de 3% a 7,6%, y ninguna encuesta nueva entró hoy para estrecharla.`,
  'candidates[3].fracos[3]': `En el contrato de 2º lugar de la primera vuelta está en 1,75% (vol USD 1,24M), detrás del líder y del segundo por amplio margen.`,
  'candidates[3].analise': `Su lectura es de recomposición parcial. En el contrato de 3º lugar de la primera vuelta subió 1,50pp, a 23,50% (vol USD 277 mil), recuperando un tercio de los 4,50pp que había cedido en la lectura del 03/Sep. En el contrato de ganador subió 0,10pp, a 1,85% (vol USD 12,64M acumulado). 📌 Su volumen sigue siendo el dato más fuera de lugar del panel: entre los cuatro nombres por encima de 1% en el contrato de ganador, es el de mayor volumen acumulado, por delante del líder y del segundo colocado, en un contrato que el mercado descuenta por debajo de 2%. El panel registra el contraste y no lo interpreta. Del lado de la encuesta, Datafolha del 03/Sep sigue siendo la lectura más reciente y nada cambió hoy.`,

  'candidates[4].header': `PRECIO: Ronaldo Caiado en 0,15% en el contrato de GANADOR (vol USD 7,15M acumulado), por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, está en 9,50% (vol USD 114 mil), ${S}, caída de 0,50pp. Fernando Haddad y Romeu Zema siguen por debajo del piso en el contrato de ganador. ENCUESTA: sin lectura nueva. Datafolha del 03/Sep coloca a Caiado en 4% en los dos escenarios y a Zema en 2%.`,
  'candidates[4].subtitle': `Pelotón de atrás en la ${S}. ⚠️ EL PAR DE SEGUNDA VUELTA CONTRA RONALDO CAIADO YA TIENE CUATRO LECTURAS EN LA MISMA SEMANA, todas con campo superpuesto: ${QUATRO}. Ninguna encuesta nacional nueva entró el 04/Sep.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0,15% (vol USD 7,15M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cedió 0,50pp y está en 9,50%, en un libro de USD 114 mil, ${S}.`,
  'candidates[4].caiado.fortes': `En Datafolha del 03/Sep, que sigue siendo la encuesta más reciente, tiene 4% en los dos escenarios de primera vuelta, su mejor número entre las cuatro casas de la semana. Sigue tercero en el contrato de 3º lugar de la primera vuelta, detrás solo de Augusto Cury y Renan Santos. Llevó la crisis del Supremo a la propaganda de televisión, defendió una investigación sobre supuesta coima de Daniel Vorcaro y participó en una entrevista pública de Folha y UOL este viernes, según Folha de S.Paulo.`,
  'candidates[4].caiado.fracos': `Cedió de 5% a 4% dentro de la propia Datafolha entre el 21/Ago y el 03/Sep. En el contrato de ganador sigue por debajo del piso de 0,5%, y en el de 3º lugar cedió 0,50pp en esta lectura, de 10,00% a 9,50%. Y el par de segunda vuelta en que aparece ya fue medido por cuatro casas en la misma semana, con cuatro resultados distintos, y ninguna encuesta nueva entró hoy para desempatar.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,55M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, está en 0,70%, en un libro de USD 49 mil, ${S}.`,
  'candidates[4].zema.fracos': `En Datafolha del 03/Sep pierde por 48% a 39%, margen de 9 puntos, y tiene 2% en la primera vuelta contra 3% en la ronda de la misma casa del 21/Ago. ⚠️ El par de segunda vuelta contra él es el de mayor dispersión entre casas de la ventana: las cuatro casas de la semana midieron 3, 11, 2 y 9 puntos, y ninguna encuesta nueva entró el 04/Sep.`,
  'candidates[4].analise': `El bloque no tiene precio nuevo publicable en el contrato de ganador: Ronaldo Caiado, Romeu Zema y Fernando Haddad están todos por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica número nuevo para ellos en ese mercado. 📌 Lo que sí tiene lectura es el contrato de 3º lugar de la primera vuelta, que es otro mercado: Caiado cedió 0,50pp y está en 9,50% (vol USD 114 mil), y Zema está en 0,70% (vol USD 49 mil). Del lado de la encuesta nada cambió: Datafolha del 03/Sep sigue siendo la más reciente, con Caiado en 4% y Zema en 2%, y el par de segunda vuelta contra Caiado en 46% a 41%.`,
  'candidates[4].fortes[0]': `Ronaldo Caiado sigue tercero en el contrato de 3º lugar de la primera vuelta, con 9,50% (vol USD 114 mil), detrás solo de Augusto Cury y Renan Santos.`,
  'candidates[4].fortes[1]': `Llevó la crisis del Supremo a la propaganda de televisión y defendió una investigación sobre supuesta coima de Daniel Vorcaro, según Folha de S.Paulo, y participó en una entrevista pública de Folha y UOL este viernes.`,
  'candidates[4].fortes[2]': `El par de segunda vuelta contra él en Datafolha del 03/Sep es de 5 puntos, 46% a 41%, más estrecho que el de Romeu Zema, que es de 9 puntos.`,
  'candidates[4].fracos[0]': `En el contrato de ganador Caiado está en 0,15%, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él allí.`,
  'candidates[4].fracos[1]': `En el contrato de 3º lugar cedió 0,50pp, de 10,00% a 9,50%.`,
  'candidates[4].fracos[2]': `Romeu Zema está en 0,70% en el contrato de 3º lugar (vol USD 49 mil) y por debajo del piso en el de ganador.`,
  'candidates[4].fracos[3]': `Fernando Haddad no es candidato a la Presidencia y disputa el gobierno de São Paulo, y su contrato sigue en 0,05%.`,

  'quadroComparativo[0].p': `${SEM}La lectura más reciente sigue siendo ${DF}. Lo da en 39% en el escenario con Pablo Marçal y 38% en el escenario sin él, y ganando los cuatro pares de ${G('segunda vuelta', 'segundo-turno')} que probó: 46% a 44% contra el segundo colocado, 46% a 41% contra Ronaldo Caiado y 48% a 39% contra Romeu Zema. Evaluación del gobierno: 45% aprueban y 51% desaprueban.`,
  'quadroComparativo[0].m': `55,50% (vol USD 9,72M), ${S}. Alza de 1,00pp sobre la lectura del 03/Sep, 23:45. La distancia hacia el segundo pasó de 11,65pp a 15,35pp, una apertura de 3,70pp tras cuatro lecturas seguidas encogiéndose. ⚠️ En el contrato de 2º lugar de la primera vuelta cedió 4,70pp y pasa a 5,80% (vol USD 467 mil).`,
  'quadroComparativo[0].t': `subió en el contrato de ganador y reabrió la distancia, y cedió en el de 2º lugar, en el mismo intervalo`,
  'quadroComparativo[0].s': `Afirmó haberle dicho a Donald Trump que Brasil no acepta injerencia en sus elecciones, según G1 y Gazeta do Povo. Dijo que todos deben ser investigados y le reclamó a la Fiscalía General y al Supremo una resolución del caso ${G('Banco Master', 'banco-master')}, según Folha de S.Paulo.`,

  'quadroComparativo[1].p': `${SEMQ}Lo da en 32% en el escenario con Marçal y 33% en el escenario sin él, y a 2 puntos en la segunda vuelta, 44% contra 46%. ⚠️ LAS TRES NACIONALES DE LA VENTANA SIGUEN DISCREPANDO EN EL SIGNO DE ESE PAR: Genial/${G('Quaest', 'quaest')} del 02/Sep dio al líder adelante por 42% a 41%, PoderData del 03/Sep dio al segundo adelante por 45% a 44%, y Datafolha del 03/Sep da al líder adelante por 46% a 44%.`,
  'quadroComparativo[1].m': `40,15% (vol USD 9,68M), ${S}. ⚠️ CAÍDA DE 2,70pp, la mayor variación de cualquier nombre del libro presidencial en esta lectura. ⭐ Y EN EL CONTRATO DE 2º LUGAR DE LA PRIMERA VUELTA SUBIÓ 4,00pp, a 87,50% (vol USD 586 mil). Los dos contratos se movieron en sentidos contrarios.`,
  'quadroComparativo[1].t': `los dos contratos sobre el mismo nombre discreparon en la misma lectura, menos 2,70pp en uno y más 4,00pp en el otro`,
  'quadroComparativo[1].s': `Dijo que la decisión de Edson Fachin en la crisis del Supremo es luz al final del túnel, según Valor Econômico, y que Alexandre de Moraes no está en condiciones de seguir en el tribunal, según Correio Braziliense.`,

  'quadroComparativo[2].p': `${SEMQ}Lo deja en 7% en el escenario con Marçal y 8% en el escenario sin él, y sigue siendo la única de las cinco casas de la ventana que lo coloca por debajo de dos dígitos. Las cinco lecturas: BTG/Nexus 11% el 31/Ago, Real Time Big Data 11% el 01/Sep, Genial/Quaest 10% el 02/Sep, PoderData 10% el 03/Sep y Datafolha 7% y 8% el mismo día.`,
  'quadroComparativo[2].m': `1,95% (vol USD 4,07M), ${S}. Alza de 0,70pp en el contrato de ganador, con cerca de USD 380 mil de volumen nuevo en un día. ⚠️ En el contrato de 3º lugar de la primera vuelta cedió 4,85pp y pasa a 54,65% (vol USD 123 mil), interrumpiendo tres días seguidos de alza, y en el de 2º lugar cayó de 1,75% a 0,95%.`,
  'quadroComparativo[2].t': `subió en el contrato de ganador y cedió en los otros dos en que aparece`,
  'quadroComparativo[2].s': `Datafolha publicó el desglose regional de su ronda del 03/Sep, según Folha de S.Paulo. No hay acto propio de él en las noticias de este viernes.`,

  'quadroComparativo[3].p': `${SEMQ}Lo da en 4% en el escenario con Marçal y 3% en el escenario sin él. La dispersión entre casas en la ventana va de 3% a 7,6%, y ninguna encuesta nueva entró hoy para estrecharla.`,
  'quadroComparativo[3].m': `1,85% (vol USD 12,64M), ${S}. Alza de 0,10pp en el contrato de ganador. En el contrato de 3º lugar de la primera vuelta subió 1,50pp y pasa a 23,50% (vol USD 277 mil), recuperando parte de los 4,50pp que había cedido en la lectura anterior.`,
  'quadroComparativo[3].t': `recompuso parte de la caída del contrato de 3º lugar, y sigue con el mayor volumen acumulado del pelotón`,
  'quadroComparativo[3].s': `El pedido de juicio político que presentó contra Alexandre de Moraes y Dias Toffoli sigue en trámite, según Gazeta do Povo.`,

  'quadroComparativo[4].p': `${SEMQ}Lo coloca en 4% en los dos escenarios de primera vuelta y lo da perdiendo la segunda vuelta por 46% a 41%. ⚠️ EL PAR DE SEGUNDA VUELTA CONTRA ÉL TIENE CUATRO LECTURAS EN LA MISMA SEMANA Y NINGUNA COINCIDE CON LA OTRA EN EL MARGEN: ${QUATRO}.`,
  'quadroComparativo[4].m': `0,15% (vol USD 7,15M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta, que es otro mercado, cedió 0,50pp y está en 9,50% (vol USD 114 mil), ${S}.`,
  'quadroComparativo[4].t': `sin precio nuevo en el contrato de ganador, y caída de 0,50pp en el de 3º lugar`,
  'quadroComparativo[4].s': `Llevó la crisis del Supremo a la propaganda de televisión, defendió una investigación sobre supuesta coima de Daniel Vorcaro y participó en una entrevista pública de Folha y UOL este viernes, según Folha de S.Paulo.`,

  'quadroComparativo[5].p': `${SEMQ}Lo trae en 2% en el escenario en que está en la lista. Su presencia separa los dos escenarios de la casa: con Marçal el líder tiene 39% y el segundo 32%, y sin Marçal el líder tiene 38% y el segundo 33%, es decir, la distancia va de 7 a 5 puntos.`,
  'quadroComparativo[5].m': `0,15% (vol USD 3,64M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de 3º LUGAR de la primera vuelta está en 2,60% (vol USD 47 mil), ${S}.`,
  'quadroComparativo[5].t': `sin precio nuevo en el contrato de ganador, y cuarto colocado en el de 3º lugar`,
  'quadroComparativo[5].s': `No aparece en las noticias de este viernes con un hecho propio.`,

  'quadroComparativo[6].p': `Sin encuesta. Mercado sobre la destitución de un ministro del Supremo antes de 2027.`,
  'quadroComparativo[6].m': `⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA ESTE CONTRATO, por segundo día. La última lectura confirmada sigue siendo la del 03/Sep a las 17:28, con 7,40% (vol USD 87 mil), y es esa la que la página mantiene. AFOS solo publica precio que dos lecturas independientes confirmen, y este contrato no tuvo lectura confirmada el 04/Sep.`,
  'quadroComparativo[6].t': `sin lectura nueva para publicar, por segundo día seguido`,
  'quadroComparativo[6].s': `⭐ EL ACTO DEL DÍA: Edson Fachin RETIRÓ de la investigación de las fake news el pedido de Alexandre de Moraes para investigar a André Mendonça, y creó una petición propia bajo su propia relatoría, con 5 días hábiles para que la Fiscalía General se manifieste y otros 5 para Mendonça a continuación, según Folha de S.Paulo y Gazeta do Povo. 📌 El plazo de 5 días dado a Moraes, Mendonça, Paulo Gonet y Andrei Rodrigues es del 03/Sep y no de este viernes. Horas después, Fachin defendió el FIN de la investigación de las fake news, abierta hace siete años, pero no la cerró, según Estadão y Gazeta do Povo. El Consejo Superior del Ministerio Público Federal abrió un procedimiento sobre Gonet, según Folha de S.Paulo y Gazeta do Povo. Flávio Dino dijo que el Supremo es mayor que cualquiera que lo integra, según Folha de S.Paulo.`,

  cruzamento: `El 4 de septiembre es el inverso exacto del día anterior, y es eso lo que la página registra. ⭐ NO SALIÓ NINGUNA ENCUESTA NACIONAL NUEVA, y eso no es un vacío de recolección: el registro del ${G('TSE', 'tse')} muestra siete encuestas nacionales EN CAMPO en este momento, y la primera divulgación marcada es el 06/Sep, de Veritá. Después vienen Quaest el 07/Sep, Gerp y Nexus el 08/Sep, e Ideia/Canal Meio, Real Time Big Data y PALVER el 09/Sep. PALVER es la mayor muestra del calendario, con 5.000 entrevistas. El 03/Sep fueron tres nacionales en 48 horas y el precio del líder quedó estancado por más de ocho horas. ⭐ HOY, SIN NINGUNA ENCUESTA, EL PRECIO SE MOVIÓ MÁS QUE AYER: la distancia entre los dos primeros pasó de 11,65pp a 15,35pp, una apertura de 3,70pp que deshizo cuatro lecturas seguidas de estrechamiento. El líder subió 1,00pp, a 55,50%, y el segundo cedió 2,70pp, a 40,15%, la mayor variación de cualquier nombre del libro. 📌 El panel registra la coincidencia y no afirma causa. No hay medición de intención de voto publicada hoy para sostener ni para desmentir el movimiento. ⚠️ LA SEGUNDA DIVERGENCIA ESTÁ DENTRO DEL PROPIO MERCADO, y aparece en dos nombres a la vez. El segundo colocado cedió 2,70pp en el contrato de ganador y subió 4,00pp en el de 2º lugar de la ${G('primera vuelta', 'primeiro-turno')}, a 87,50%. Augusto Cury hizo lo contrario: subió 0,70pp en el de ganador y cedió 4,85pp en el de 3º lugar, a 54,65%, interrumpiendo tres días seguidos de alza allí. Son mercados distintos sobre los mismos nombres, y en esta lectura no cuentan la misma historia. ⭐ LA TERCERA ES EL ACTO DEL DÍA, y es del Supremo. Edson Fachin retiró de la investigación de las fake news el pedido de Alexandre de Moraes para investigar a André Mendonça y lo transformó en una petición propia bajo su propia relatoría, con 5 días hábiles para la Fiscalía General, según Folha de S.Paulo y Gazeta do Povo. Horas después defendió el fin de la investigación, abierta hace siete años, sin cerrarla. 📌 El contrato que mide la salida de un ministro del Supremo por destitución es justamente el que no tiene lectura confirmada en esta ronda, por segundo día: la página mantiene el 7,40% de la lectura del 03/Sep a las 17:28, con su propio sello. AFOS solo publica precio que dos lecturas independientes confirmen. El panel no dice quién tiene razón entre el precio y la encuesta, y en esta ronda hay una razón más para no decirlo: de uno de los dos lados no vino nada.`,
})
