/** Mapa EN: analysis-data da rodada de 04/Set/2026, carimbo 19:07. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 04/Sep, 19:07 BRT (22:07 UTC)'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 143.57M and this page's price is from the ${S}. ⭐ NO NATIONAL POLL WAS RELEASED TODAY, and the ${G('TSE', 'tse')} register shows why: seven national polls are in the field right now, and the first scheduled release is 06/Sep. The most recent polling reading is still the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp).`,
  'cards.sentimento.text2': `⭐ AND IT WAS PRECISELY ON THE DAY WITHOUT A POLL THAT THE PRICE MOVED MOST. The gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp that undid four consecutive readings of narrowing. On 03/Sep, with three national polls published within 48 hours, the leader's price did not move for more than eight hours. The panel records the coincidence of dates and assigns no cause: there is no voting-intention measurement published today either to support or to contradict the move.`,
  'cards.sentimento.text3': `⚠️ AND THERE IS A DIVERGENCE INSIDE THE MARKET ITSELF, in two names at once. The runner-up gave up 2.70pp in the winner contract and rose 4.00pp in the ${G('first-round', 'primeiro-turno')} runner-up contract. Augusto Cury did the reverse: up 0.70pp in the winner contract and down 4.85pp in the third-place one. They are different markets on the same names, and in this reading they do not tell the same story.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 40.15% (vol USD 9.68M accumulated), ${S}, down 2.70pp and the largest move of any name in the presidential book in this reading. ⭐ In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 4.00pp and stands at 87.50% (vol USD 586 thousand). Datafolha of 03/Sep, still the most recent poll, keeps him 2 points away in the ${G('second round', 'segundo-turno')}, 44% against 46%.`,
  'cards.sentimento.esquerda': `Lula at 55.50% (vol USD 9.72M accumulated), ${S}, up 1.00pp. The gap to the runner-up reopened to 15.35pp. ⚠️ In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 4.70pp and stands at 5.80% (vol USD 467 thousand), his largest move in any contract in this reading. Datafolha of 03/Sep gives him 39% and 38% across the two scenarios and has him winning all four second-round pairings it tested.`,
  'cards.sentimento.terceiraVia': `Augusto Cury at 1.95% (vol USD 4.07M accumulated), ${S}, up 0.70pp in the winner contract, with around USD 380 thousand of new volume in one day. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 4.85pp and stands at 54.65% (vol USD 123 thousand), breaking three straight days of gains. Renan Santos at 1.85% (vol USD 12.64M accumulated), up 0.10pp, and in the third-place contract he rose 1.50pp to 23.50% (vol USD 277 thousand). Ronaldo Caiado at 0.15% (vol USD 7.15M accumulated) in the winner contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract.`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 of a point. ⚠️ THIS ROUND PUBLISHES NO NEW PRICE for the ${G('Supreme Court', 'stf')} justice impeachment contract nor for the Senate majority one, and it publishes no new price for the names below 0.5%, which are Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas and Fernando Haddad in the winner contract.`,

  'cards.inss.text1': `📌 THERE IS NO NEW ${G('INSS', 'inss')} ACT THIS FRIDAY. The ceremony at the Planalto Palace, the change of criterion and the figures that go with it are all from 03/Sep, and the page keeps them with their date of origin. What came out today on the subject is analysis, not a new fact.`,
  'cards.inss.text2': `⚠️ WHAT FALLS OUTSIDE THE GOVERNMENT'S COUNT HAS A NUMBER, AND IT IS FROM 03/Sep. Claims delayed by more than 45 days totalled 261 thousand in August, against 1.88 million in January, a fall of 86%. Open claims fell to 1.2 million. Folha de S.Paulo reported on 03/Sep that the government changed the criterion for declaring the queue cleared, and O Globo reported the same day that the announcement sits alongside more than 200 thousand claims still awaiting a response.`,
  'cards.inss.text3': `The definition the government uses, given by the social security minister and quoted by Metrópoles on 03/Sep, is that clearing the queue means analysing more claims per month than the number of new ones coming in. It is a throughput criterion, not a stock one, and the two measure different realities.`,
  'cards.inss.impactoLula': `The structured government-assessment reading is still the Genial/${G('Quaest', 'quaest')} one of 02/Sep, with field from 30/Aug to 01/Sep: 45% approve and 48% disapprove, with 7% giving no answer. Datafolha of 03/Sep brings a more recent reading, with 45% approval and 51% disapproval, and the panel keeps one house per block so as not to break the internal series. No new poll came in today.`,
  'cards.inss.impactoGestao': `Within Quaest itself the picture is one of stasis. On 05/Aug it was 48% approval against 47% disapproval, on 14/Aug 46% against 48% and on 02/Sep 45% against 48%. Disapproval repeats the same figure for the third round running. With no new poll today, that picture has not moved.`,
  'cards.inss.conclusao': `What this round measures on the subject is narrow and worth recording as such: nothing changed. There was no new INSS act this Friday and no new government-assessment poll. The price moved, but the panel does not attribute that move to the INSS, because there is nothing from the INSS on this day to attribute it to.`,

  'cards.bancoMaster.text1': `⭐ THE DAY'S ACT IS NOT FROM THE CASE ITSELF, IT IS FROM THE COURT. Edson Fachin removed from the fake-news inquiry the request by Alexandre de Moraes to investigate André Mendonça and turned it into a separate petition under his own docket, with 5 working days for the prosecutor-general's office to respond and another 5 for Mendonça afterwards, according to Folha de S.Paulo and Gazeta do Povo. 📌 The 5-day deadline given to Moraes, Mendonça, Paulo Gonet and Andrei Rodrigues is from 03/Sep, not from this Friday.`,
  'cards.bancoMaster.text2': `The Superior Council of the Federal Prosecution Service opened proceedings to examine the references to Paulo Gonet in Daniel Vorcaro's messages, according to Folha de S.Paulo and Gazeta do Povo. It is the council the prosecutor-general himself chairs.`,
  'cards.bancoMaster.text3': `⚠️ AND THERE ARE TWO PLEA-BARGAIN FRONTS UNDER WAY, WITH DIFFERENT DATES. The plea bargain of the owner of Entre Investimentos, who made payments to the fund that would have financed Dark Horse, was closed by the prosecutor-general's office and sent to the Supreme Court, according to Folha de S.Paulo and G1. And in a REJECTED plea-bargain proposal, from 03/Sep, Daniel Vorcaro said the donation to Jair Bolsonaro and to Tarcisio de Freitas was a bribe arranged by Gilberto Kassab, according to Folha de S.Paulo. Tarcisio de Freitas called the claim an inference bordering on the ridiculous, according to O Globo.`,
  'cards.bancoMaster.conclusao': `The chronology is the information, and it now has eight distinct dates: the meeting between the justice and the businessman is from 14 March 2025; the messages are from 16 November 2025; the arrest is from 17 November 2025; the ${G('Federal Police', 'pf')} report was delivered on 27 August 2026; the lifting of secrecy is from 1 September 2026; the request to investigate Mendonça is from 3 September; the splitting of that request and the proceedings on the prosecutor-general are from 4 September. 📌 None of these dates is today by accident, and the page separates them one by one because headlines tend to compress ten months into a single word.`,

  'cards.stf.toffoli': `No new individual act on 04/Sep. He remains a target of the impeachment request filed by Renan Santos, alongside Alexandre de Moraes, according to Gazeta do Povo.`,
  'cards.stf.moraes': `⚠️ HIS REQUEST WAS SPLIT OFF BY THE COURT'S PRESIDENCY. The investigation he asked for against André Mendonça on 03/Sep was taken out of the fake-news inquiry and became a separate petition under Edson Fachin's docket, according to Folha de S.Paulo and Gazeta do Povo. The fake-news inquiry, which he has overseen for seven years, is the same one Fachin argued for closing hours later. The Paraná bar association asked for his removal on 03/Sep, according to Folha de S.Paulo.`,
  'cards.stf.gilmar': `No new individual act on 04/Sep. His proposal to bar ${G('Federal Police', 'pf')} officers from Supreme Court chambers is from 03/Sep, according to Folha de S.Paulo and Gazeta do Povo, and the page keeps it with its date of origin.`,
  'cards.stf.dino': `He said the Supreme Court is greater than anyone who sits on it, according to Folha de S.Paulo, and called for unity and institutional caution in the face of the crisis, according to Gazeta do Povo. It is his first individual statement in this series.`,
  'cards.stf.mendonca': `⭐ HE WAS THE MAIN BENEFICIARY OF THE DAY'S DECISION: the request to investigate him left the fake-news inquiry and passed to the court president's docket. He will have 5 working days to respond, after the prosecutor-general's office, according to Folha de S.Paulo and Gazeta do Povo. The R$ 26.4 thousand in invoices he presented to rebut the suit allegation are from 03/Sep.`,
  'cards.stf.nexo': `⭐ THE CRISIS WENT FROM AN ACT BETWEEN JUSTICES TO A DECISION BY THE PRESIDENCY. On 03/Sep one justice asked for another to be investigated. On 04/Sep the court president removed that request from the inquiry in which it had been made and placed it under his own docket, and hours later argued for ending that inquiry, open for seven years, without closing it, according to Estadão and Gazeta do Povo. 📌 The distinction matters: he argued and promised to close it, he did not close it.`,
  'cards.stf.analise': `⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE CONTRACT on a Supreme Court justice leaving by impeachment before 2027, for the second day running. The last confirmed reading is the 03/Sep one at 17:28, at 7.40% (vol USD 87 thousand), and that is the one the page keeps, with its own timestamp. AFOS only publishes a price that two independent readings confirm, and this contract had no confirmed reading on 04/Sep. 📌 The contrast is the day's record: the court produced the most concrete decision of the crisis so far, and the contract that measures a justice leaving is precisely the one for which the page has no new figure to show.`,
})
