/** Mapa EN: polls-data, republicação de 04/Set/2026 com carimbo 19:53 e o STF no ar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of 04/Sep, 19:53 BRT (22:53 UTC)'

construir('polls-data', 'en', {
  'polymarketComparison.note': `${G('Polymarket', 'polymarket')} prices at the ${S}, with the presidential book at USD 143.62M. ⭐ NO NATIONAL POLL WAS RELEASED ON 04/Sep, and the ${G('TSE', 'tse')} register says why: seven national polls are in the field right now and the first scheduled release is 06/Sep, from Veritá, followed by Quaest on 07/Sep, Gerp and Nexus on 08/Sep, and Ideia/Canal Meio, Real Time Big Data and PALVER on 09/Sep, the last of these with 5,000 interviews. ⭐ AND IT WAS ON THE DAY WITHOUT A POLL THAT THE PRICE MOVED MOST: the gap between the top two went from 11.65pp to 15.35pp, an opening of 3.70pp that undid four consecutive readings of narrowing. The panel records the coincidence of dates and assigns no cause. ⚠️ The ${G('Supreme Court', 'stf')} justice impeachment contract stands at 15.85% and is the panel's only exception to the double reading: it travelled from 10.60% to 19.30% on 04/Sep, an amplitude of 8.70pp, with USD 28 of new money, and it goes out declared as a single reading, with the range alongside.`,
  'polymarketComparison.sources': `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20pp. Confirmation is done contract by contract. On 04/Sep the winner, first-round runner-up, first-round third-place and Senate majority books confirmed at the 19:53 reading. ⚠️ The Supreme Court justice impeachment contract is the only exception and goes out on a SINGLE reading, declared as such and accompanied by the range it travelled during the day, measured on the series recorded in backup/neon/marketPrice. Polls registered with the TSE and released by the polling houses, with reporting from Poder360, Gazeta do Povo, CNN Brasil, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC and Jornal de Brasília. The calendar of polls in the field and of scheduled releases comes from the official TSE register. Series superlatives checked against the Neon backup, in backup/neon/marketPrice, which holds the complete record since 14/Apr.`,

  'polymarketComparison.candidates[0].tendenciaPolymarket': `55.50% (vol USD 9.72M), ${S}. Up 1.00pp on the reading of 03/Sep, 23:45. ⭐ THE GAP TO THE RUNNER-UP REOPENED BY 3.70pp, from 11.65pp to 15.35pp, after narrowing across four consecutive readings, and it happened on a day with no new national poll. ⚠️ In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 2.90pp and now stands at 7.60% (vol USD 469 thousand).`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40.15% (vol USD 9.68M), ${S}. ⚠️ DOWN 2.70pp, the largest move of any name in the presidential book in this reading. ⭐ AND HIS TWO CONTRACTS MOVED IN OPPOSITE DIRECTIONS: in the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 4.00pp and now stands at 87.50% (vol USD 586 thousand). In the third-place contract he appears at 1.55% (vol USD 68 thousand).`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.95% (vol USD 4.07M), ${S}. Up 0.70pp in the winner contract, with around USD 380 thousand of new volume in one day. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 5.95pp and now stands at 53.55% (vol USD 123 thousand), breaking three straight days of gains. And in the first-round runner-up contract, which is a third market, he slipped 0.80pp, from 1.75% to 0.95% in that book, which has accumulated USD 142 thousand.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.85% (vol USD 12.64M), ${S}. Up 0.10pp in the winner contract. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.50pp and now stands at 23.50% (vol USD 277 thousand), recovering part of the 4.50pp he had given up in the previous reading. 📌 Among the four names above 1% in the winner contract, his is the largest accumulated volume, ahead of the leader and the runner-up, in a contract priced below 2%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.15% (vol USD 7.15M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he gave up 1.00pp and stands at 9.00% (vol USD 114 thousand), ${S}.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.69M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he stands at 2.70% (vol USD 47 thousand), ${S}.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.15% (vol USD 6.55M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he stands at 0.70% (vol USD 49 thousand), ${S}.`,
})
