/** Mapa EN: analysis-criteriosa, rodada de 05/Set/2026. Livro de vencedor sem confirmação, STF de volta à dupla leitura. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S5 = 'confirmed reading of 05/Sep, 13:29 BRT'
const S4 = 'confirmed reading of 04/Sep, 19:53 BRT'
const SEM = 'and this round publishes no new price for that book'
const POLL = 'No new national poll for the second day. The most recent reading is still the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp).'

construir('analysis-criteriosa', 'en', {
  'subtitle': `Cross-reference of 5 September 2026, ${S5} (16:29 UTC) in the ${G('first-round', 'primeiro-turno')} runner-up, third-place and ${G('Supreme Court', 'stf')} impeachment books, presidential book at USD 143.79M. ⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE WINNER BOOK, whose values are still those of the ${S4}. ⭐ AND FOR THE SECOND DAY RUNNING NO NATIONAL POLL WAS RELEASED: the ${G('TSE', 'tse')} register shows eight national polls in the field now, with releases scheduled from 06 to 10/Sep.`,

  'candidates[0].header': `PRICE: 55.50% (vol USD 9.76M accumulated) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 2.25pp and stands at 5.35% (vol USD 470 thousand), ${S5}. POLL: no new reading for the second day. The most recent is still the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp), which gives him 39% in the scenario with Pablo Marçal and 38% without, and has him winning all four ${G('second-round', 'segundo-turno')} pairings it tested.`,
  'candidates[0].analise': `What is measured about him on Friday is a double absence, and it has a recorded explanation. There was no new national poll for the second day running, and the TSE register shows eight national polls in the field right now, with releases scheduled from 06 to 10/Sep. And the winner contract received no new price, because this round's two readings did not confirm within the house tolerance in that book. What moved was the first-round runner-up contract, where he gave up 2.25pp and stands at 5.35% (vol USD 470 thousand). It is his second straight fall in that market, which measures something different from the winner contract: the probability of finishing the first round in second place.`,
  'candidates[1].header': `PRICE: 40.15% (vol USD 9.69M accumulated) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 2.00pp and stands at 89.50% (vol USD 597 thousand), ${S5}. POLL: no new reading. Datafolha of 03/Sep gives him 32% in the scenario with Marçal and 33% without, and 2 points away in the ${G('second round', 'segundo-turno')}, 44% against 46%.`,
  'candidates[1].analise': `His whole move on Friday sits in a single market. In the first-round runner-up contract he rose 2.00pp and reached 89.50% (vol USD 597 thousand), and only one point in the whole series has ever been above it, the 90.50% of 21/Aug. In the winner contract there is no new price in this round. ⚠️ The distinction between the two contracts matters and the panel does not close it: one measures who wins the election and the other measures who finishes the first round in second, and a name can rise in one and stand still in the other without contradiction. The three national polls in the window still disagree on the sign of the second-round pairing against the leader.`,
  'candidates[2].header': `PRICE: 1.95% (vol USD 4.08M accumulated) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 1.60pp and stands at 51.95% (vol USD 124 thousand), ${S5}. POLL: no new reading. Datafolha of 03/Sep leaves him at 7% and 8%, and it is the only one of the five houses in the window to put him below double digits.`,
  'candidates[2].analise': `A second straight fall for him in the first-round third-place contract, down 1.60pp to 51.95% (vol USD 124 thousand). Adding the two readings, that is 7.55pp since 03/Sep in that market, and he is still ahead of Renan Santos, who stands at 24.50%. In the winner contract there is no new price in this round. The spread between houses about him remains the hardest datum in the window: Datafolha of 03/Sep measures him below double digits and the other four houses in the window measure him in double digits.`,
  'candidates[3].header': `PRICE: 1.85% (vol USD 12.68M accumulated) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.00pp and stands at 24.50% (vol USD 278 thousand), ${S5}. POLL: no new reading. Datafolha of 03/Sep gives him 4% and 3% across the two scenarios.`,
  'candidates[3].analise': `He recovers ground in the first-round third-place contract for the second reading running, up 1.00pp to 24.50% (vol USD 278 thousand), while that market's front-runner gives way. In the winner contract there is no new price in this round. 📌 Among the four names above 1% in the winner contract, he is still the one with the largest accumulated volume, USD 12.68M, above the leader and the runner-up, in a contract priced below 2%. The spread between houses about him in this window runs from 3% to 7.6%.`,
  'candidates[4].header': `PRICE: all three are still below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for them in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract, Ronaldo Caiado rose 0.50pp and stands at 9.50% (vol USD 114 thousand) and Romeu Zema stands at 0.70%, ${S5}. POLL: no new reading. Datafolha of 03/Sep puts Caiado at 4% and Zema at 2% in both scenarios.`,
  'candidates[4].analise': `The only one of the three to move on Friday was Ronaldo Caiado, and in a market that is not the winner one: he rose 0.50pp in the first-round third-place contract and stands at 9.50% (vol USD 114 thousand). Fernando Haddad is not a presidential candidate and is running for the government of São Paulo, and the panel keeps him in the table because of the contract that still carries his name. ⚠️ The second-round pairing against Caiado still has four readings in the same week and no two agree on the margin.`,

  'quadroComparativo[0].p': `${POLL} It gives him 39% in the scenario with Pablo Marçal and 38% without, and has him winning all four ${G('second-round', 'segundo-turno')} pairings it tested: 46% to 44% against the runner-up, 46% to 41% against Ronaldo Caiado and 48% to 39% against Romeu Zema. Government approval: 45% approve and 51% disapprove.`,
  'quadroComparativo[0].m': `55.50% (vol USD 9.76M) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 2.25pp and stands at 5.35% (vol USD 470 thousand), ${S5}.`,
  'quadroComparativo[0].t': `no new price in the winner contract this round, and a second straight fall in the runner-up one`,
  'quadroComparativo[0].s': `Met the president of the ${G('Supreme Court', 'stf')} before an event at the Planalto Palace, and the two discussed the crisis at the court, according to Valor Econômico and Folha de S.Paulo. Narrowed his campaign's inner circle and is planning reinforcements, according to Folha de S.Paulo.`,
  'quadroComparativo[1].p': `${POLL} It gives him 32% in the scenario with Marçal and 33% without, and 2 points away in the ${G('second round', 'segundo-turno')}, 44% against 46%. The three national polls in the window still disagree on the sign of that pairing.`,
  'quadroComparativo[1].m': `40.15% (vol USD 9.69M) in the winner contract, ${S4}, ${SEM}. ⭐ In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 2.00pp and stands at 89.50% (vol USD 597 thousand), ${S5}.`,
  'quadroComparativo[1].t': `rose 2.00pp in the runner-up contract and got no new price in the winner one`,
  'quadroComparativo[1].s': `Said the Senate president and Alexandre de Moraes are seeking self-protection, according to Folha de S.Paulo, and that Moraes is in no condition to remain on the ${G('Supreme Court', 'stf')}, according to Correio Braziliense. Called the court president's decision a light at the end of the tunnel, according to Valor Econômico.`,
  'quadroComparativo[2].p': `${POLL} It leaves him at 7% in the scenario with Marçal and 8% without, and it is the only one of the five houses in the window to put him below double digits.`,
  'quadroComparativo[2].m': `1.95% (vol USD 4.08M) in the winner contract, ${S4}, ${SEM}. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 1.60pp and stands at 51.95% (vol USD 124 thousand), ${S5}.`,
  'quadroComparativo[2].t': `second straight fall in the third-place contract, adding 7.55pp since 03/Sep`,
  'quadroComparativo[2].s': `No new individual act on 05/Sep. He is tested in the second-round scenario of the poll Nexus has announced for 08/Sep.`,
  'quadroComparativo[3].p': `${POLL} It gives him 4% in the scenario with Marçal and 3% without. The spread between houses in the window runs from 3% to 7.6%.`,
  'quadroComparativo[3].m': `1.85% (vol USD 12.68M) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.00pp and stands at 24.50% (vol USD 278 thousand), ${S5}.`,
  'quadroComparativo[3].t': `second straight gain in the third-place contract, while that market's front-runner gives way`,
  'quadroComparativo[3].s': `Still the author of the impeachment request against two ${G('Supreme Court', 'stf')} justices. No new individual act on 05/Sep.`,
  'quadroComparativo[4].p': `${POLL} It puts him at 4% in both first-round scenarios and has him losing the ${G('second round', 'segundo-turno')} 46% to 41%.`,
  'quadroComparativo[4].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 0.50pp and stands at 9.50% (vol USD 114 thousand), ${S5}.`,
  'quadroComparativo[4].t': `rose 0.50pp in the first-round third-place contract`,
  'quadroComparativo[4].s': `Defended reform of the ${G('Supreme Court', 'stf')} on the campaign trail, according to reporting by Seu Dinheiro. No other individual act on 05/Sep.`,
  'quadroComparativo[5].p': `${POLL} It brings him at 2% in the scenario where he appears, and his presence separates the house's two scenarios.`,
  'quadroComparativo[5].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 0.50pp and stands at 2.20% (vol USD 47 thousand), ${S5}.`,
  'quadroComparativo[5].t': `gave up 0.50pp in the first-round third-place contract`,
  'quadroComparativo[5].s': `No new individual act on 05/Sep.`,
  'quadroComparativo[6].m': `8.65% (vol USD 88 thousand), ${S5} (16:29 UTC). ⭐ THIS CONTRACT IS BACK ON THE DOUBLE READING in this round, after going out on 04/Sep with a single reading and the day's range declared beside it. Against the 15.85% published the day before, that is a 7.20pp fall.`,
  'quadroComparativo[6].t': `fell 7.20pp and returned to being published on a double reading, 10.60pp below the series high`,
  'quadroComparativo[6].s': `⭐ THE DAY'S ACT IS THE PROSECUTION'S: it ordered an inquiry into whether there was interference in the production of the Federal Police report on the messages, and asked the ${G('Supreme Court', 'stf')} president for authorisation to investigate André Mendonça, according to Estadão, Folha de S.Paulo and Gazeta do Povo. The Prosecution Service's Council opened a procedure on the prosecutor-general's conduct, according to Estadão and Valor Econômico.`,

  'cruzamento': `5 September is a calendar day, and that is what the page records. ⭐ FOR THE SECOND DAY RUNNING NO NATIONAL POLL WAS RELEASED, and the ${G('TSE', 'tse')} register shows why: eight national polls are in the field right now, and the scheduled releases run from 06 to 10/Sep. Veritá on 06/Sep, Quaest on 07/Sep, Gerp and Nexus on 08/Sep, Ideia/Canal Meio, Real Time Big Data and PALVER on 09/Sep, and 100 Cidades, PoderData and AtlasIntel on 10/Sep. Two of them have a sample of 5,000, PALVER and AtlasIntel, and they are the largest on the calendar. 📌 Three of those national polls entered the register on Friday, all with releases scheduled for 10/Sep. There are 29 days to the ${G('first round', 'primeiro-turno')}.\n\n⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE WINNER BOOK, because the two independent readings AFOS takes eight minutes apart did not confirm within 0.20 of a point in that contract. Its values on this page are still those of the confirmed reading of 04/Sep, 19:53 BRT, and they are marked as such line by line. The other four books confirmed and carry prices from 05/Sep, 13:29 BRT.\n\n⭐ WHAT MOVED TODAY WERE THE POSITION MARKETS AND THE IMPEACHMENT ONE. In the first-round runner-up contract the runner-up rose 2.00pp and reached 89.50%, and only one point in the whole series has ever been above it, the 90.50% of 21/Aug, while the leader gave up 2.25pp and stands at 5.35%. In the third-place one, Augusto Cury gave up 1.60pp to 51.95% and Renan Santos rose 1.00pp to 24.50%. In the Senate majority one, the MDB gave up 1.50pp to 10.75%, with the PL at 82.00%. They are different contracts on the same election, and the panel neither adds nor subtracts them.\n\n🔑 AND THE ${G('SUPREME COURT', 'stf')} IMPEACHMENT CONTRACT IS THE DAY'S METHOD CASE. On 04/Sep it went out on a single reading, alongside the range it travelled, because two readings eight minutes apart could not agree in a book that was moving too much. On Friday it confirmed on both readings and returned to the normal rule, at 8.65% (vol USD 88 thousand), against the 15.85% published the day before. In the series recorded since 14/Apr the high is 19.30%, set on 04/Sep, and the low is 2.10%, from 08/Jun: today's price sits 10.60pp below a high from the day before yesterday, in a book that has accumulated USD 88 thousand. The panel records the move and attributes no cause to it.`,
})
