/** Mapa ES: polls-data, rodada de 05/Set/2026. Livro de vencedor sem confirmação. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S5 = 'lectura confirmada del 05/Sep, 13:29 BRT'
const S4 = 'lectura confirmada del 04/Sep, 19:53 BRT'
const SIN = 'y esta ronda no publica precio nuevo para el contrato de ganador, cuyas dos lecturas no confirmaron dentro de 0,20 punto'
const SIN_ENC = 'Sin encuesta nacional nueva por segundo día seguido. La lectura más reciente sigue siendo la Datafolha del 03/Sep (BR-03669/2026, campo del 01 al 03/Sep, n=2.002, margen de 2pp).'

construir('polls-data', 'es', {
  'polymarketComparison.note': `Precios de Polymarket con el libro presidencial en USD 143,79M. ⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL CONTRATO DE GANADOR: las dos lecturas independientes que AFOS toma con ocho minutos de intervalo no confirmaron dentro de 0,20 punto en ese libro, y sus valores siguen siendo los de la ${S4}. Los contratos de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, de tercer lugar de la primera vuelta, de destitución en el ${G('Supremo', 'stf')} y de mayoría en el Senado sí confirmaron y traen precio del 05/Sep, 13:29 BRT (16:29 UTC). ⭐ Y POR SEGUNDO DÍA SEGUIDO NINGUNA ENCUESTA NACIONAL FUE DIVULGADA, y el registro del ${G('TSE', 'tse')} dice por qué: ocho nacionales están en campo en este momento y las divulgaciones previstas van del 06 al 10/Sep, con Veritá el 06/Sep, Quaest el 07/Sep, Gerp y Nexus el 08/Sep, Ideia/Canal Meio, Real Time Big Data y PALVER el 09/Sep, y 100 Cidades, PoderData y AtlasIntel el 10/Sep. Dos de ellas tienen muestra de 5.000. 📌 Lo que se movió en esta lectura fueron los mercados de posición: el segundo colocado subió 2,00pp en el contrato de segundo lugar hasta 89,50%, Augusto Cury cedió 1,60pp en el de tercer lugar hasta 51,95%, y el contrato de destitución en el Supremo volvió a la doble lectura en 8,65%, frente al 15,85% de la víspera.`,
  'polymarketComparison.sources': `Precios de Polymarket vía proxy AFOS, y el panel solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20pp. La confirmación se hace contrato a contrato. El 05/Sep los libros de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, de tercer lugar de la primera vuelta, de destitución en el ${G('Supremo', 'stf')} y de mayoría en el Senado confirmaron en la lectura de las 13:29 BRT, y el de ganador no confirmó, así que mantiene los valores de la lectura confirmada del 04/Sep. Encuestas registradas en el ${G('TSE', 'tse')} y divulgadas por los institutos, con reporte de Poder360, Gazeta do Povo, CNN Brasil, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC y Jornal de Brasília. El calendario de encuestas en campo y de divulgación prevista sale del registro oficial del TSE. Superlativo de serie verificado en el respaldo de Neon, en backup/neon/marketPrice, que guarda el registro completo desde el 14/Abr.`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `${SIN_ENC} Lo da en 39% en el escenario con Pablo Marçal y 38% sin él, y ganando los cuatro pares de ${G('segunda vuelta', 'segundo-turno')} que probó: 46% a 44% contra el segundo colocado, 46% a 41% contra Ronaldo Caiado y 48% a 39% contra Romeu Zema. Evaluación del gobierno: 45% aprueban y 51% desaprueban.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55,50% (vol USD 9,76M) en el contrato de ganador, ${S4}, ${SIN}. ⚠️ En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 2,25pp y está en 5,35% (vol USD 470 mil), ${S5}, su segunda caída seguida en ese mercado.`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `${SIN_ENC} Lo da en 32% en el escenario con Marçal y 33% sin él, y a 2 puntos en la ${G('segunda vuelta', 'segundo-turno')}, 44% contra 46%. ⚠️ LAS TRES NACIONALES DE LA VENTANA SIGUEN DISCREPANDO EN EL SIGNO DE ESE PAR: la Genial/Quaest del 02/Sep dio al líder por delante 42% a 41%, la PoderData del 03/Sep lo dio por delante 45% a 44%, y la Datafolha del 03/Sep da al líder por delante 46% a 44%.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40,15% (vol USD 9,69M) en el contrato de ganador, ${S4}, ${SIN}. ⭐ En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,00pp y está en 89,50% (vol USD 597 mil), ${S5}, y solo un punto de toda la serie estuvo alguna vez por encima, el 90,50% del 21/Ago.`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `${SIN_ENC} Lo deja en 7% en el escenario con Marçal y 8% sin él, y sigue siendo la única de las cinco casas de la ventana que lo pone por debajo de dos dígitos. Las otras cuatro: BTG/Nexus 11% el 31/Ago, Real Time Big Data 11% el 01/Sep, Genial/Quaest 10% el 02/Sep y PoderData 10% el 03/Sep.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,95% (vol USD 4,08M) en el contrato de ganador, ${S4}, ${SIN}. ⚠️ En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,60pp y está en 51,95% (vol USD 124 mil), ${S5}. Sumadas las dos caídas seguidas, son 7,55pp desde el 03/Sep en ese mercado.`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${SIN_ENC} Lo da en 4% en el escenario con Marçal y 3% sin él. ⚠️ LA DISPERSIÓN ENTRE CASAS EN ESTA VENTANA VA DE 3% A 7,6%: 3% en Genial/Quaest y en PoderData, 3% a 4% en Datafolha, 6% en Real Time Big Data el 01/Sep y 7,6% en AtlasIntel el 31/Ago.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,85% (vol USD 12,68M) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,00pp y está en 24,50% (vol USD 278 mil), ${S5}, segunda subida seguida. 📌 Entre los cuatro nombres por encima de 1% en el contrato de ganador, es el de mayor volumen acumulado, por encima del líder y del segundo colocado, en un contrato con precio por debajo de 2%.`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `${SIN_ENC} Lo pone en 4% en los dos escenarios de primera vuelta y lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} 46% a 41%. ⚠️ EL PAR DE SEGUNDA VUELTA CONTRA ÉL TIENE CUATRO LECTURAS EN LA MISMA SEMANA Y NINGUNA COINCIDE CON OTRA EN EL MARGEN.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,15% (vol USD 7,16M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, subió 0,50pp y está en 9,50% (vol USD 114 mil), ${S5}.`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `${SIN_ENC} Lo trae en 2% en el escenario en que aparece, y su presencia separa los dos escenarios de la casa: con Marçal el líder tiene 39% y el segundo 32%, y sin Marçal 38% y 33%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,73M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} cedió 0,50pp y está en 2,20% (vol USD 47 mil), ${S5}.`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `${SIN_ENC} Lo mide en 2% en los dos escenarios de primera vuelta y lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} 48% a 39%, margen de 9 puntos, el par con la mayor dispersión entre casas de la ventana.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,15% (vol USD 6,56M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} está en 0,70% (vol USD 49 mil), ${S5}.`,
})
