/** Mapa ES: analysis-criteriosa, rodada de 05/Set/2026. Livro de vencedor sem confirmação, STF de volta à dupla leitura. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S5 = 'lectura confirmada del 05/Sep, 13:29 BRT'
const S4 = 'lectura confirmada del 04/Sep, 19:53 BRT'
const SIN = 'y esta ronda no publica precio nuevo para ese libro'
const ENC = 'Sin encuesta nacional nueva por segundo día. La lectura más reciente sigue siendo la Datafolha del 03/Sep (BR-03669/2026, campo del 01 al 03/Sep, n=2.002, margen de 2pp).'

construir('analysis-criteriosa', 'es', {
  'subtitle': `Cruce del 5 de septiembre de 2026, ${S5} (16:29 UTC) en los libros de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, de tercer lugar y de destitución en el ${G('Supremo', 'stf')}, libro presidencial en USD 143,79M. ⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL LIBRO DE GANADOR, cuyos valores siguen siendo los de la ${S4}. ⭐ Y POR SEGUNDO DÍA SEGUIDO NINGUNA ENCUESTA NACIONAL FUE DIVULGADA: el registro del ${G('TSE', 'tse')} muestra ocho nacionales en campo ahora, con divulgación prevista del 06 al 10/Sep.`,

  'candidates[0].header': `PRECIO: 55,50% (vol USD 9,76M acumulado) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 2,25pp y está en 5,35% (vol USD 470 mil), ${S5}. ENCUESTA: sin lectura nueva por segundo día. La más reciente sigue siendo la Datafolha del 03/Sep (BR-03669/2026, campo del 01 al 03/Sep, n=2.002, margen de 2pp), que lo da en 39% en el escenario con Pablo Marçal y 38% sin él, y ganando los cuatro pares de ${G('segunda vuelta', 'segundo-turno')} que probó.`,
  'candidates[0].analise': `Lo que se mide sobre él este viernes es una ausencia doble, y tiene explicación registrada. No hubo encuesta nacional nueva por segundo día seguido, y el registro del TSE muestra ocho nacionales en campo en este momento, con divulgaciones previstas del 06 al 10/Sep. Y el contrato de ganador no recibió precio nuevo, porque las dos lecturas de esta ronda no confirmaron dentro de la tolerancia de la casa en ese libro. Lo que se movió fue el contrato de segundo lugar de la primera vuelta, en el que cedió 2,25pp y está en 5,35% (vol USD 470 mil). Es su segunda caída seguida en ese mercado, que mide algo distinto del de ganador: la probabilidad de terminar la primera vuelta en segundo lugar.`,
  'candidates[1].header': `PRECIO: 40,15% (vol USD 9,69M acumulado) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,00pp y está en 89,50% (vol USD 597 mil), ${S5}. ENCUESTA: sin lectura nueva. La Datafolha del 03/Sep lo da en 32% en el escenario con Marçal y 33% sin él, y a 2 puntos en la ${G('segunda vuelta', 'segundo-turno')}, 44% contra 46%.`,
  'candidates[1].analise': `Su movimiento de este viernes está entero en un solo mercado. En el contrato de segundo lugar de la primera vuelta subió 2,00pp y llegó a 89,50% (vol USD 597 mil), y solo un punto de toda la serie estuvo alguna vez por encima, el 90,50% del 21/Ago. En el contrato de ganador no hay precio nuevo en esta ronda. ⚠️ La distinción entre los dos contratos importa y el panel no la cierra: uno mide quién gana la elección y el otro mide quién termina la primera vuelta en segundo, y un nombre puede subir en uno y quedarse quieto en el otro sin contradicción. Las tres nacionales de la ventana siguen discrepando en el signo del par de segunda vuelta contra el líder.`,
  'candidates[2].header': `PRECIO: 1,95% (vol USD 4,08M acumulado) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,60pp y está en 51,95% (vol USD 124 mil), ${S5}. ENCUESTA: sin lectura nueva. La Datafolha del 03/Sep lo deja en 7% y 8%, y es la única de las cinco casas de la ventana que lo pone por debajo de dos dígitos.`,
  'candidates[2].analise': `Segunda caída seguida suya en el contrato de tercer lugar de la primera vuelta, que cedió 1,60pp y está en 51,95% (vol USD 124 mil). Sumadas las dos lecturas, son 7,55pp desde el 03/Sep en ese mercado, y sigue por delante de Renan Santos, que está en 24,50%. En el contrato de ganador no hay precio nuevo en esta ronda. La dispersión entre casas sobre él sigue siendo el dato más duro de la ventana: la Datafolha del 03/Sep lo mide por debajo de dos dígitos y las otras cuatro casas de la ventana lo miden en dos dígitos.`,
  'candidates[3].header': `PRECIO: 1,85% (vol USD 12,68M acumulado) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,00pp y está en 24,50% (vol USD 278 mil), ${S5}. ENCUESTA: sin lectura nueva. La Datafolha del 03/Sep lo da en 4% y 3% en los dos escenarios.`,
  'candidates[3].analise': `Recupera terreno en el contrato de tercer lugar de la primera vuelta por segunda lectura seguida, subiendo 1,00pp hasta 24,50% (vol USD 278 mil), mientras el primer colocado de ese mercado cede. En el contrato de ganador no hay precio nuevo en esta ronda. 📌 Entre los cuatro nombres por encima de 1% en el contrato de ganador, sigue siendo el de mayor volumen acumulado, USD 12,68M, por encima del líder y del segundo colocado, en un contrato con precio por debajo de 2%. La dispersión entre casas sobre él en esta ventana va de 3% a 7,6%.`,
  'candidates[4].header': `PRECIO: los tres siguen por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para ellos en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}, Ronaldo Caiado subió 0,50pp y está en 9,50% (vol USD 114 mil) y Romeu Zema está en 0,70%, ${S5}. ENCUESTA: sin lectura nueva. La Datafolha del 03/Sep pone a Caiado en 4% y a Zema en 2% en los dos escenarios.`,
  'candidates[4].analise': `El único de los tres que se movió este viernes fue Ronaldo Caiado, y en un mercado que no es el de ganador: subió 0,50pp en el contrato de tercer lugar de la primera vuelta y está en 9,50% (vol USD 114 mil). Fernando Haddad no es candidato a la Presidencia y disputa el gobierno de São Paulo, y el panel lo mantiene en la tabla por el contrato que todavía existe con su nombre. ⚠️ El par de segunda vuelta contra Caiado sigue con cuatro lecturas en la misma semana y ninguna coincide con otra en el margen.`,

  'quadroComparativo[0].p': `${ENC} Lo da en 39% en el escenario con Pablo Marçal y 38% sin él, y ganando los cuatro pares de ${G('segunda vuelta', 'segundo-turno')} que probó: 46% a 44% contra el segundo colocado, 46% a 41% contra Ronaldo Caiado y 48% a 39% contra Romeu Zema. Evaluación del gobierno: 45% aprueban y 51% desaprueban.`,
  'quadroComparativo[0].m': `55,50% (vol USD 9,76M) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 2,25pp y está en 5,35% (vol USD 470 mil), ${S5}.`,
  'quadroComparativo[0].t': `sin precio nuevo en el contrato de ganador esta ronda, y segunda caída seguida en el de segundo lugar`,
  'quadroComparativo[0].s': `Se reunió con el presidente del ${G('Supremo', 'stf')} antes de un evento en el Planalto, y los dos trataron de la crisis en el tribunal, según Valor Econômico y Folha de S.Paulo. Restringió el núcleo de la campaña y planea refuerzos, según Folha de S.Paulo.`,
  'quadroComparativo[1].p': `${ENC} Lo da en 32% en el escenario con Marçal y 33% sin él, y a 2 puntos en la ${G('segunda vuelta', 'segundo-turno')}, 44% contra 46%. Las tres nacionales de la ventana siguen discrepando en el signo de ese par.`,
  'quadroComparativo[1].m': `40,15% (vol USD 9,69M) en el contrato de ganador, ${S4}, ${SIN}. ⭐ En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,00pp y está en 89,50% (vol USD 597 mil), ${S5}.`,
  'quadroComparativo[1].t': `subió 2,00pp en el contrato de segundo lugar y se quedó sin precio nuevo en el de ganador`,
  'quadroComparativo[1].s': `Dijo que el presidente del Senado y Alexandre de Moraes buscan autoprotección, según Folha de S.Paulo, y que Moraes no está en condiciones de seguir en el ${G('Supremo', 'stf')}, según Correio Braziliense. Llamó a la decisión del presidente del tribunal una luz al final del túnel, según Valor Econômico.`,
  'quadroComparativo[2].p': `${ENC} Lo deja en 7% en el escenario con Marçal y 8% sin él, y es la única de las cinco casas de la ventana que lo pone por debajo de dos dígitos.`,
  'quadroComparativo[2].m': `1,95% (vol USD 4,08M) en el contrato de ganador, ${S4}, ${SIN}. ⚠️ En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,60pp y está en 51,95% (vol USD 124 mil), ${S5}.`,
  'quadroComparativo[2].t': `segunda caída seguida en el contrato de tercer lugar, sumando 7,55pp desde el 03/Sep`,
  'quadroComparativo[2].s': `Sin acto individual nuevo el 05/Sep. Es probado en el escenario de segunda vuelta de la encuesta que Nexus anunció para el 08/Sep.`,
  'quadroComparativo[3].p': `${ENC} Lo da en 4% en el escenario con Marçal y 3% sin él. La dispersión entre casas en la ventana va de 3% a 7,6%.`,
  'quadroComparativo[3].m': `1,85% (vol USD 12,68M) en el contrato de ganador, ${S4}, ${SIN}. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,00pp y está en 24,50% (vol USD 278 mil), ${S5}.`,
  'quadroComparativo[3].t': `segunda subida seguida en el contrato de tercer lugar, mientras el primero de ese mercado cede`,
  'quadroComparativo[3].s': `Sigue como autor del pedido de destitución contra dos ministros del ${G('Supremo', 'stf')}. Sin acto individual nuevo el 05/Sep.`,
  'quadroComparativo[4].p': `${ENC} Lo pone en 4% en los dos escenarios de primera vuelta y lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} 46% a 41%.`,
  'quadroComparativo[4].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 0,50pp y está en 9,50% (vol USD 114 mil), ${S5}.`,
  'quadroComparativo[4].t': `subió 0,50pp en el contrato de tercer lugar de la primera vuelta`,
  'quadroComparativo[4].s': `Defendió una reforma del ${G('Supremo', 'stf')} en agenda de campaña, según el reporte de Seu Dinheiro. Sin otro acto individual el 05/Sep.`,
  'quadroComparativo[5].p': `${ENC} Lo trae en 2% en el escenario en que aparece, y su presencia separa los dos escenarios de la casa.`,
  'quadroComparativo[5].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 0,50pp y está en 2,20% (vol USD 47 mil), ${S5}.`,
  'quadroComparativo[5].t': `cedió 0,50pp en el contrato de tercer lugar de la primera vuelta`,
  'quadroComparativo[5].s': `Sin acto individual nuevo el 05/Sep.`,
  'quadroComparativo[6].m': `8,65% (vol USD 88 mil), ${S5} (16:29 UTC). ⭐ ESTE CONTRATO VOLVIÓ A LA DOBLE LECTURA en esta ronda, después de salir el 04/Sep con lectura única y el rango del día declarado al lado. Frente al 15,85% publicado la víspera son 7,20pp de caída.`,
  'quadroComparativo[6].t': `cayó 7,20pp y volvió a publicarse con doble lectura, a 10,60pp del techo de la serie`,
  'quadroComparativo[6].s': `⭐ EL ACTO DEL DÍA ES DE LA FISCALÍA: ordenó averiguar si hubo interferencia en la producción del informe de la Policía Federal sobre los mensajes, y pidió al presidente del ${G('Supremo', 'stf')} aval para investigar a André Mendonça, según Estadão, Folha de S.Paulo y Gazeta do Povo. El Consejo del Ministerio Público abrió un procedimiento sobre la conducta del fiscal general, según Estadão y Valor Econômico.`,

  'cruzamento': `El 5 de septiembre es un día de calendario, y es eso lo que la página registra. ⭐ POR SEGUNDO DÍA SEGUIDO NINGUNA ENCUESTA NACIONAL FUE DIVULGADA, y el registro del ${G('TSE', 'tse')} muestra por qué: ocho encuestas nacionales están en campo en este momento, y las divulgaciones previstas van del 06 al 10/Sep. Veritá el 06/Sep, Quaest el 07/Sep, Gerp y Nexus el 08/Sep, Ideia/Canal Meio, Real Time Big Data y PALVER el 09/Sep, y 100 Cidades, PoderData y AtlasIntel el 10/Sep. Dos de ellas tienen muestra de 5.000, PALVER y AtlasIntel, y son las mayores del calendario. 📌 Tres de esas nacionales entraron en el registro este viernes, todas con divulgación prevista para el 10/Sep. Faltan 29 días para la ${G('primera vuelta', 'primeiro-turno')}.\n\n⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL LIBRO DE GANADOR, porque las dos lecturas independientes que AFOS toma con ocho minutos de intervalo no confirmaron dentro de 0,20 punto en ese contrato. Sus valores en esta página siguen siendo los de la lectura confirmada del 04/Sep, 19:53 BRT, y están marcados así línea por línea. Los otros cuatro libros confirmaron y traen precio del 05/Sep, 13:29 BRT.\n\n⭐ LO QUE SE MOVIÓ HOY FUERON LOS MERCADOS DE POSICIÓN Y EL DE DESTITUCIÓN. En el contrato de segundo lugar de la primera vuelta el segundo colocado subió 2,00pp y llegó a 89,50%, y solo un punto de toda la serie estuvo alguna vez por encima, el 90,50% del 21/Ago, mientras el líder cedió 2,25pp y está en 5,35%. En el de tercer lugar, Augusto Cury cedió 1,60pp hasta 51,95% y Renan Santos subió 1,00pp hasta 24,50%. En el de mayoría en el Senado, el MDB cedió 1,50pp hasta 10,75%, con el PL en 82,00%. Son contratos distintos sobre la misma elección, y el panel no los suma ni los resta.\n\n🔑 Y EL CONTRATO DE DESTITUCIÓN EN EL ${G('SUPREMO', 'stf')} ES EL CASO DE MÉTODO DEL DÍA. El 04/Sep salió con lectura única, acompañado del rango que recorrió, porque dos lecturas con ocho minutos de intervalo no lograban coincidir en un libro que se movía demasiado. Este viernes confirmó en las dos lecturas y volvió a la regla normal, en 8,65% (vol USD 88 mil), frente al 15,85% publicado la víspera. En la serie registrada desde el 14/Abr el techo es 19,30%, marcado el 04/Sep, y el piso es 2,10%, del 08/Jun: el precio de ahora está 10,60pp por debajo de un techo de anteayer, en un libro que acumula USD 88 mil. El panel registra el movimiento y no le atribuye causa.`,
})
