/** Mapa EN: analysis-data, rodada de 05/Set/2026. Livro de vencedor sem confirmação, STF de volta à dupla leitura. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S5 = 'confirmed reading of 05/Sep, 13:29 BRT (16:29 UTC)'
const S4 = 'confirmed reading of 04/Sep, 19:53 BRT'
const SEM = 'and this round publishes no new price for that book'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 143.79M and this page's prices come from the ${S5}, in the ${G('first-round', 'primeiro-turno')} runner-up book, the first-round third-place book, the ${G('Supreme Court', 'stf')} impeachment book and the Senate majority book. ⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE WINNER BOOK, and its values are still those of the ${S4}. ⭐ AND FOR THE SECOND DAY RUNNING NO NATIONAL POLL WAS RELEASED: the ${G('TSE', 'tse')} register shows eight national polls in the field right now, with releases scheduled from 06 to 10/Sep, two of them with a sample of 5,000, PALVER and AtlasIntel. There are 29 days to the first round.`,
  'cards.sentimento.text2': `⭐ THE SUPREME COURT IMPEACHMENT CONTRACT IS BACK ON A CONFIRMED READING and stands at 8.65% (vol USD 88 thousand), against the 15.85% published the day before, a fall of 7.20pp. In the series recorded since 14/Apr its high is 19.30%, set on 04/Sep, and its low is 2.10%, from 08/Jun, so today's price sits 10.60pp below its own high, which is from the day before yesterday. On 04/Sep that contract went out on a single reading with the day's range declared beside it, and in this round that is no longer necessary.`,
  'cards.sentimento.text3': `⚠️ AND THE BOOKS THAT MOVED TODAY ARE THE POSITION ONES, NOT THE WINNER BOOK. In the first-round runner-up contract the runner-up rose 2.00pp and stands at 89.50%, while the leader gave up 2.25pp and stands at 5.35%. In the third-place contract, Augusto Cury gave up 1.60pp to 51.95% and Renan Santos rose 1.00pp to 24.50%. In the Senate majority contract, the MDB gave up 1.50pp to 10.75%. They are different markets on the same election, and in this reading they moved while the winner book received no new price.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 40.15% (vol USD 9.69M accumulated) in the winner contract, ${S4}, ${SEM}. ⭐ In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 2.00pp and stands at 89.50% (vol USD 597 thousand), ${S5}. The most recent polling reading is still the Datafolha poll of 03/Sep, which gives him 32% in the scenario with Pablo Marçal and 33% without, and 2 points away in the ${G('second round', 'segundo-turno')}, 44% against 46%.`,
  'cards.sentimento.esquerda': `Lula at 55.50% (vol USD 9.76M accumulated) in the winner contract, ${S4}, ${SEM}. ⚠️ In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 2.25pp and stands at 5.35% (vol USD 470 thousand), ${S5}. Datafolha of 03/Sep gives him 39% and 38% across the two first-round scenarios, has him winning all four second-round pairings it tested, and puts government approval at 45% against 51% disapproval.`,
  'cards.sentimento.terceiraVia': `Augusto Cury at 1.95% (vol USD 4.08M accumulated) in the winner contract, ${S4}, ${SEM}. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 1.60pp and stands at 51.95% (vol USD 124 thousand), ${S5}, a second straight fall in that market. Datafolha of 03/Sep leaves him at 7% and 8% across the two scenarios, and it is still the only one of the five houses in the window to put him below double digits.`,
  'cards.sentimento.polymarket': `Prices from the ${S5} in the ${G('first-round', 'primeiro-turno')} runner-up book, the first-round third-place book, the ${G('Supreme Court', 'stf')} impeachment book and the Senate majority book. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 of a point, and confirmation is done contract by contract. ⚠️ This round publishes no new price for the winner book, whose values are still those of the ${S4}, nor for the names below 0.5%, which are Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas and Fernando Haddad in the winner contract.`,
  'cards.inss.text1': `📌 THERE IS NO NEW INSS ACT ON 05/Sep. The ceremony at the Planalto Palace, the change of criterion and the figures that came with it are all from 03/Sep, and the page keeps them with their original date. What came out on 05/Sep on the subject is analysis, not new fact.`,
  'cards.inss.conclusao': `What this round measures on the subject is narrow and worth recording as such: nothing changed. There was no new INSS act on 05/Sep and no new government approval poll, for the second day running. The structured reading is still the Genial/Quaest poll of 02/Sep, and Datafolha of 03/Sep is the most recent available. The panel does not attribute price movement to this subject, because there is no new fact from it in this window.`,
  'cards.bancoMaster.text1': `📌 THERE IS NO NEW ACT IN THE CASE ON 05/Sep, AND THE CHRONOLOGY OF 04/Sep IS STILL THE INFORMATION. On 04/Sep the Prosecutor-General's Office ordered an inquiry into whether there was interference in the production of the Federal Police report that revealed the Banco Master owner's messages to Alexandre de Moraes, and asked Edson Fachin for authorisation to investigate André Mendonça over that suspicion, according to Estadão, Folha de S.Paulo and Gazeta do Povo. On the same 04/Sep the court's president had already removed the investigation request from the fake news inquiry.`,
  'cards.bancoMaster.text2': `The Federal Prosecution Service's Superior Council opened a procedure to examine the mentions of Paulo Gonet in Daniel Vorcaro's messages, according to Estadão and Valor Econômico, and it is the council the prosecutor-general himself chairs. A wing of the ${G('Supreme Court', 'stf')} argues he should step aside from the case, according to O Globo, and the request that he step aside was also made by a member of Congress, according to SBT News.`,
  'cards.bancoMaster.conclusao': `The chronology is still the information, and the two dates it gained are both from 04/Sep: the court's president removed the investigation request from the fake news inquiry, and the Prosecutor-General's Office ordered an inquiry into the Federal Police report, asking for authorisation to investigate the justice who commissioned it. 📌 The meeting between the justice and the businessman is from 14 March 2025, the messages are from 16 November 2025 and the businessman's arrest is from 17 November 2025. None of those dates is 05/Sep, and the page keeps them with their original date.`,
  'cards.stf.toffoli': `No new individual act on 05/Sep. He remains a target of the impeachment request filed by Renan Santos, alongside Alexandre de Moraes.`,
  'cards.stf.moraes': `⚠️ THE FEDERAL POLICE REPORT HE USED BECAME THE OBJECT OF AN INQUIRY ON 04/Sep. The Prosecutor-General's Office ordered that day an investigation into whether there was interference in the production of that report, which deals with the Banco Master owner's messages to him, according to Folha de S.Paulo, Gazeta do Povo and Estadão. The five-day deadline for him to respond, opened on 03/Sep, is running, and it is what pushes back the court president's decision. No new individual act on 05/Sep.`,
  'cards.stf.gilmar': `No new individual act on 05/Sep. Estadão recorded that the runner-up's campaign coordinator met him on 04/Sep, amid the crisis.`,
  'cards.stf.dino': `No new individual act on 05/Sep. His statement that the ${G('Supreme Court', 'stf')} is bigger than anyone who sits on it is from 04/Sep, and the page keeps it with its original date.`,
  'cards.stf.mendonca': `⚠️ THE PROSECUTION ASKED FOR AUTHORISATION TO INVESTIGATE HIM ON 04/Sep. Paulo Gonet asked Edson Fachin for authorisation to look into a suspicion that he interfered with the Federal Police over the report on the messages, according to Estadão, O Globo and Gazeta do Povo. The five-day deadline for him to respond, opened on 03/Sep, is running. No new individual act on 05/Sep.`,
  'cards.stf.nexo': `⭐ IN TWO DAYS THE CASE LEFT THE COURT AND ENTERED THE PROSECUTION SERVICE, AND THE TWO DAYS ARE 03 AND 04/Sep. On 04/Sep the court's president removed the investigation request from the fake news inquiry and placed it under his own hand. Still on 04/Sep, hours later, the Prosecutor-General's Office ordered an inquiry into the Federal Police report, according to Folha de S.Paulo, Gazeta do Povo and Estadão, and the Prosecution Service's Council opened a procedure to examine the conduct of the prosecutor-general himself, according to Estadão and Valor Econômico. 📌 Edson Fachin signalled an intention to take both cases to the full bench, according to Folha de S.Paulo and G1, and that decision has not been taken yet. No new act is recorded on 05/Sep.`,
  'cards.stf.analise': `8.65% (vol USD 88 thousand) on the contract for a ${G('Supreme Court', 'stf')} justice leaving by impeachment before 2027, ${S5}. ⭐ THIS CONTRACT IS BACK ON THE DOUBLE READING in this round, after going out on 04/Sep with a single reading and the day's range declared beside it. Against the 15.85% published the day before, that is a 7.20pp fall. In the series recorded since 14/Apr the high is 19.30%, set on 04/Sep, and the low is 2.10%, from 08/Jun, so today's price sits 10.60pp below a high from the day before yesterday, in a book that has accumulated USD 88 thousand.`,
})
