/** Mapa EN: polls-data, rodada de 05/Set/2026. Livro de vencedor sem confirmação. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S5 = 'confirmed reading of 05/Sep, 13:29 BRT'
const S4 = 'confirmed reading of 04/Sep, 19:53 BRT'
const SEM = 'and this round publishes no new price for the winner contract, whose two readings did not confirm within 0.20 of a point'
const SEM_POLL = 'No new national poll for the second day running. The most recent reading is still the Datafolha poll of 03/Sep (BR-03669/2026, field 01 to 03/Sep, n=2,002, margin of 2pp).'

construir('polls-data', 'en', {
  'polymarketComparison.note': `Polymarket prices with the presidential book at USD 143.79M. ⚠️ THIS ROUND PUBLISHES NO NEW PRICE FOR THE WINNER CONTRACT: the two independent readings AFOS takes eight minutes apart did not confirm within 0.20 of a point in that book, and its values are still those of the ${S4}. The ${G('first-round', 'primeiro-turno')} runner-up, first-round third-place, ${G('Supreme Court', 'stf')} impeachment and Senate majority contracts did confirm and carry prices from 05/Sep, 13:29 BRT (16:29 UTC). ⭐ AND FOR THE SECOND DAY RUNNING NO NATIONAL POLL WAS RELEASED, and the ${G('TSE', 'tse')} register says why: eight national polls are in the field right now and the scheduled releases run from 06 to 10/Sep, with Veritá on 06/Sep, Quaest on 07/Sep, Gerp and Nexus on 08/Sep, Ideia/Canal Meio, Real Time Big Data and PALVER on 09/Sep, and 100 Cidades, PoderData and AtlasIntel on 10/Sep. Two of them have a sample of 5,000. 📌 What moved in this reading were the position markets: the runner-up rose 2.00pp in the runner-up contract to 89.50%, Augusto Cury gave up 1.60pp in the third-place contract to 51.95%, and the Supreme Court impeachment contract returned to the double reading at 8.65%, against 15.85% the day before.`,
  'polymarketComparison.sources': `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20pp. Confirmation is done contract by contract. On 05/Sep the ${G('first-round', 'primeiro-turno')} runner-up, first-round third-place, ${G('Supreme Court', 'stf')} impeachment and Senate majority books confirmed on the 13:29 BRT reading, and the winner book did not, so it keeps the values of the confirmed reading of 04/Sep. Polls registered with the ${G('TSE', 'tse')} and released by the institutes, with reporting from Poder360, Gazeta do Povo, CNN Brasil, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC and Jornal de Brasília. The calendar of polls in the field and of scheduled releases comes from the official TSE register. Series superlatives checked against the Neon backup, in backup/neon/marketPrice, which holds the complete record since 14/Apr.`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `${SEM_POLL} It gives him 39% in the scenario with Pablo Marçal and 38% without, and has him winning all four ${G('second-round', 'segundo-turno')} pairings it tested: 46% to 44% against the runner-up, 46% to 41% against Ronaldo Caiado and 48% to 39% against Romeu Zema. Government approval: 45% approve and 51% disapprove.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55.50% (vol USD 9.76M) in the winner contract, ${S4}, ${SEM}. ⚠️ In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 2.25pp and stands at 5.35% (vol USD 470 thousand), ${S5}, his second straight fall in that market.`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `${SEM_POLL} It gives him 32% in the scenario with Marçal and 33% without, and 2 points away in the ${G('second round', 'segundo-turno')}, 44% against 46%. ⚠️ THE THREE NATIONAL POLLS IN THE WINDOW STILL DISAGREE ON THE SIGN OF THAT PAIRING: Genial/Quaest of 02/Sep had the leader ahead 42% to 41%, PoderData of 03/Sep had him ahead 45% to 44%, and Datafolha of 03/Sep has the leader ahead 46% to 44%.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `40.15% (vol USD 9.69M) in the winner contract, ${S4}, ${SEM}. ⭐ In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 2.00pp and stands at 89.50% (vol USD 597 thousand), ${S5}, and only one point in the whole series has ever been above it, the 90.50% of 21/Aug.`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `${SEM_POLL} It leaves him at 7% in the scenario with Marçal and 8% without, and it is still the only one of the five houses in the window to put him below double digits. The other four: BTG/Nexus 11% on 31/Aug, Real Time Big Data 11% on 01/Sep, Genial/Quaest 10% on 02/Sep and PoderData 10% on 03/Sep.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.95% (vol USD 4.08M) in the winner contract, ${S4}, ${SEM}. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 1.60pp and stands at 51.95% (vol USD 124 thousand), ${S5}. Adding the two straight falls, that is 7.55pp since 03/Sep in that market.`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${SEM_POLL} It gives him 4% in the scenario with Marçal and 3% without. ⚠️ THE SPREAD BETWEEN HOUSES IN THIS WINDOW RUNS FROM 3% TO 7.6%: 3% at Genial/Quaest and PoderData, 3% to 4% at Datafolha, 6% at Real Time Big Data on 01/Sep and 7.6% at AtlasIntel on 31/Aug.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.85% (vol USD 12.68M) in the winner contract, ${S4}, ${SEM}. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.00pp and stands at 24.50% (vol USD 278 thousand), ${S5}, a second straight gain. 📌 Among the four names above 1% in the winner contract, he is the one with the largest accumulated volume, above the leader and the runner-up, in a contract priced below 2%.`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `${SEM_POLL} It puts him at 4% in both first-round scenarios and has him losing the ${G('second round', 'segundo-turno')} 46% to 41%. ⚠️ THE SECOND-ROUND PAIRING AGAINST HIM HAS FOUR READINGS IN THE SAME WEEK AND NO TWO AGREE ON THE MARGIN.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.15% (vol USD 7.16M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he rose 0.50pp and stands at 9.50% (vol USD 114 thousand), ${S5}.`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `${SEM_POLL} It brings him at 2% in the scenario where he is on the list, and his presence separates the house's two scenarios: with Marçal the leader has 39% and the runner-up 32%, and without Marçal 38% and 33%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.73M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he gave up 0.50pp and stands at 2.20% (vol USD 47 thousand), ${S5}.`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `${SEM_POLL} It measures him at 2% in both first-round scenarios and has him losing the ${G('second round', 'segundo-turno')} 48% to 39%, a margin of 9 points, the pairing with the widest spread between houses in the window.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.15% (vol USD 6.56M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he stands at 0.70% (vol USD 49 thousand), ${S5}.`,
})
