/** Mapa ES: analysis-data, rodada de 05/Set/2026. Livro de vencedor sem confirmação, STF de volta à dupla leitura. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S5 = 'lectura confirmada del 05/Sep, 13:29 BRT (16:29 UTC)'
const S4 = 'lectura confirmada del 04/Sep, 19:53 BRT'
const SIN = 'y esta ronda no publica precio nuevo para ese libro'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 143,79M y los precios de esta página son de la ${S5}, en los libros de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, de tercer lugar de la primera vuelta, de destitución en el ${G('Supremo', 'stf')} y de mayoría en el Senado. ⚠️ ESTA RONDA NO PUBLICA PRECIO NUEVO PARA EL LIBRO DE GANADOR, y sus valores siguen siendo los de la ${S4}. ⭐ Y POR SEGUNDO DÍA SEGUIDO NINGUNA ENCUESTA NACIONAL FUE DIVULGADA: el registro del ${G('TSE', 'tse')} muestra ocho nacionales en campo en este momento, con divulgación prevista del 06 al 10/Sep, y dos de ellas con muestra de 5.000, PALVER y AtlasIntel. Faltan 29 días para la primera vuelta.`,
  'cards.sentimento.text2': `⭐ EL CONTRATO DE DESTITUCIÓN EN EL SUPREMO VOLVIÓ A LA LECTURA CONFIRMADA y está en 8,65% (vol USD 88 mil), frente al 15,85% publicado la víspera, una caída de 7,20pp. En la serie registrada desde el 14/Abr su techo es 19,30%, marcado el 04/Sep, y su piso es 2,10%, del 08/Jun, así que el precio de ahora está 10,60pp por debajo de su propio techo, que es de anteayer. El 04/Sep ese contrato salió con lectura única y el rango del día declarado al lado, y en esta ronda eso ya no es necesario.`,
  'cards.sentimento.text3': `⚠️ Y LOS LIBROS QUE SE MOVIERON HOY SON LOS DE POSICIÓN, NO EL DE GANADOR. En el contrato de segundo lugar de la primera vuelta el segundo colocado subió 2,00pp y está en 89,50%, mientras el líder cedió 2,25pp y está en 5,35%. En el de tercer lugar, Augusto Cury cedió 1,60pp hasta 51,95% y Renan Santos subió 1,00pp hasta 24,50%. En el de mayoría en el Senado, el MDB cedió 1,50pp hasta 10,75%. Son mercados distintos sobre la misma elección, y en esta lectura se movieron mientras el de ganador no recibió precio nuevo.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 40,15% (vol USD 9,69M acumulado) en el contrato de ganador, ${S4}, ${SIN}. ⭐ En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,00pp y está en 89,50% (vol USD 597 mil), ${S5}. La lectura de encuesta más reciente sigue siendo la Datafolha del 03/Sep, que lo da en 32% en el escenario con Pablo Marçal y 33% sin él, y a 2 puntos en la ${G('segunda vuelta', 'segundo-turno')}, 44% contra 46%.`,
  'cards.sentimento.esquerda': `Lula en 55,50% (vol USD 9,76M acumulado) en el contrato de ganador, ${S4}, ${SIN}. ⚠️ En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 2,25pp y está en 5,35% (vol USD 470 mil), ${S5}. La Datafolha del 03/Sep lo da en 39% y 38% en los dos escenarios de primera vuelta, ganando los cuatro pares de segunda vuelta que probó, y trae la evaluación del gobierno en 45% de aprobación contra 51% de desaprobación.`,
  'cards.sentimento.terceiraVia': `Augusto Cury en 1,95% (vol USD 4,08M acumulado) en el contrato de ganador, ${S4}, ${SIN}. ⚠️ En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,60pp y está en 51,95% (vol USD 124 mil), ${S5}, segunda caída seguida en ese mercado. La Datafolha del 03/Sep lo deja en 7% y 8% en los dos escenarios, y sigue siendo la única de las cinco casas de la ventana que lo pone por debajo de dos dígitos.`,
  'cards.sentimento.polymarket': `Precios de la ${S5} en los libros de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, de tercer lugar de la primera vuelta, de destitución en el ${G('Supremo', 'stf')} y de mayoría en el Senado. AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20 punto, y la confirmación se hace contrato a contrato. ⚠️ Esta ronda no publica precio nuevo para el libro de ganador, cuyos valores siguen siendo los de la ${S4}, ni para los nombres por debajo de 0,5%, que son Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas y Fernando Haddad en el contrato de ganador.`,
  'cards.inss.text1': `📌 NO HAY ACTO NUEVO DEL INSS EL 05/Sep. La ceremonia en el Palacio de Planalto, el cambio de criterio y las cifras que lo acompañan son todos del 03/Sep, y la página los mantiene con su fecha de origen. Lo que salió el 05/Sep sobre el tema es análisis, no hecho nuevo.`,
  'cards.inss.conclusao': `Lo que esta ronda mide sobre el tema es estrecho y vale registrarlo así: nada cambió. No hubo acto nuevo del INSS el 05/Sep ni encuesta nueva de evaluación de gobierno, por segundo día seguido. La lectura estructurada sigue siendo la de Genial/Quaest del 02/Sep, y la Datafolha del 03/Sep es la más reciente disponible. El panel no atribuye movimiento de precio a este tema, porque no hay hecho nuevo suyo en esta ventana.`,
  'cards.bancoMaster.text1': `📌 NO HAY ACTO NUEVO DEL CASO EL 05/Sep, Y LA CRONOLOGÍA DEL 04/Sep SIGUE SIENDO LA INFORMACIÓN. El 04/Sep la Fiscalía General de la República ordenó averiguar si hubo interferencia en la producción del informe de la Policía Federal que reveló los mensajes del dueño del Banco Master a Alexandre de Moraes, y pidió a Edson Fachin autorización para investigar a André Mendonça por esa sospecha, según Estadão, Folha de S.Paulo y Gazeta do Povo. El mismo 04/Sep el presidente del tribunal ya había retirado el pedido de investigación de la pesquisa de las fake news.`,
  'cards.bancoMaster.text2': `El Consejo Superior del Ministerio Público Federal abrió un procedimiento para analizar las menciones a Paulo Gonet en los mensajes de Daniel Vorcaro, según Estadão y Valor Econômico, y es el consejo que el propio fiscal general preside. Un ala del ${G('Supremo', 'stf')} defiende que se aparte del caso, según O Globo, y el pedido de apartamiento también fue hecho por una parlamentaria, según SBT News.`,
  'cards.bancoMaster.conclusao': `La cronología sigue siendo la información, y las dos fechas que ganó son ambas del 04/Sep: el presidente del tribunal retiró el pedido de investigación de la pesquisa de las fake news, y la Fiscalía ordenó averiguar el informe de la Policía Federal, pidiendo aval para investigar al ministro que lo encargó. 📌 El encuentro entre el ministro y el empresario es del 14 de marzo de 2025, los mensajes son del 16 de noviembre de 2025 y la prisión del empresario es del 17 de noviembre de 2025. Ninguna de esas fechas es del 05/Sep, y la página las mantiene con su fecha de origen.`,
  'cards.stf.toffoli': `Sin acto individual nuevo el 05/Sep. Sigue como blanco del pedido de destitución presentado por Renan Santos, junto con Alexandre de Moraes.`,
  'cards.stf.moraes': `⚠️ EL INFORME DE LA POLICÍA FEDERAL QUE ÉL USÓ PASÓ A SER OBJETO DE AVERIGUACIÓN EL 04/Sep. La Fiscalía General de la República ordenó ese día investigar si hubo interferencia en la producción de ese informe, que trata de los mensajes del dueño del Banco Master a él, según Folha de S.Paulo, Gazeta do Povo y Estadão. El plazo de cinco días para que se manifieste, abierto el 03/Sep, corre, y es lo que empuja la decisión del presidente del tribunal. Sin acto individual nuevo el 05/Sep.`,
  'cards.stf.gilmar': `Sin acto individual nuevo el 05/Sep. Estadão registró que el coordinador de la campaña del segundo colocado se reunió con él el 04/Sep, en medio de la crisis.`,
  'cards.stf.dino': `Sin acto individual nuevo el 05/Sep. Su pronunciamiento de que el ${G('Supremo', 'stf')} es mayor que cualquiera que lo integre es del 04/Sep, y la página lo mantiene con su fecha de origen.`,
  'cards.stf.mendonca': `⚠️ LA FISCALÍA PIDIÓ AVAL PARA INVESTIGARLO EL 04/Sep. Paulo Gonet pidió a Edson Fachin autorización para averiguar la sospecha de que interfirió en la Policía Federal, en el informe sobre los mensajes, según Estadão, O Globo y Gazeta do Povo. El plazo de cinco días para que se manifieste, abierto el 03/Sep, corre. Sin acto individual nuevo el 05/Sep.`,
  'cards.stf.nexo': `⭐ EN DOS DÍAS EL CASO SALIÓ DEL SUPREMO Y ENTRÓ EN LA FISCALÍA, Y LOS DOS DÍAS SON 03 Y 04/Sep. El 04/Sep el presidente del tribunal retiró el pedido de investigación de la pesquisa de las fake news y lo puso bajo su propia relatoría. Todavía el 04/Sep, horas después, la Fiscalía General de la República ordenó averiguar el informe de la Policía Federal, según Folha de S.Paulo, Gazeta do Povo y Estadão, y el Consejo del Ministerio Público abrió un procedimiento para analizar la conducta del propio fiscal general, según Estadão y Valor Econômico. 📌 Edson Fachin señaló la intención de llevar los dos casos al pleno, según Folha de S.Paulo y G1, y esa decisión todavía no fue tomada. El 05/Sep no hay acto nuevo registrado.`,
  'cards.stf.analise': `8,65% (vol USD 88 mil) en el contrato de salida de ministro del ${G('Supremo', 'stf')} por destitución antes de 2027, ${S5}. ⭐ ESTE CONTRATO VOLVIÓ A LA DOBLE LECTURA en esta ronda, después de salir el 04/Sep con lectura única y el rango del día declarado al lado. Frente al 15,85% publicado la víspera son 7,20pp de caída. En la serie registrada desde el 14/Abr el techo es 19,30%, marcado el 04/Sep, y el piso es 2,10%, del 08/Jun, así que el precio de ahora está 10,60pp por debajo de un techo de anteayer, en un libro que acumula USD 88 mil.`,
})
