/** Mapa EN: polls-data, rodada de 06/Set/2026. Entra a Veritá nacional e os cinco livros confirmam. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S6 = 'confirmed reading of 06/Sep, 13:53 BRT'
const S4 = 'confirmed reading of 04/Sep'
const PISO = 'below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract'

construir('polls-data', 'en', {
  'polls[0].method': 'Phone (IVR)',
  'polls[0].note': `Veritá national poll released on 06/Sep, fieldwork from 01 to 04/Sep, registration BR-09426/2026 at the ${G('TSE', 'tse')}, with 3,804 interviews, a margin of 2pp at 95% confidence and funding from the institute's own resources. ⭐ FLÁVIO BOLSONARO APPEARS NUMERICALLY AHEAD IN THE FIRST ROUND, 38.9% against 38.4% for Lula. ⚠️ The distance of 0.5 point fits entirely inside the margin of 2 points, so what the poll measures is a STATISTICAL TIE and not a lead. It is the second national poll of the window to show that order, after Gerp of 26/Aug, which gave 38% to 37%. ⭐ AND AUGUSTO CURY GOES FROM 2.2% TO 12.2% BETWEEN THE TWO ROUNDS OF THIS HOUSE THAT THE PANEL HOLDS, the one from 21/Aug and this one, a swing of 10 points, with Pablo Marçal going the other way, from 5.2% to 1.4%. ⚠️ THIS SURVEY CARRIES NO ${G('RUNOFF', 'segundo-turno')} SCENARIO, and the most recent reading of that pairing is still Datafolha of 03/Sep. 🏷️ The first-round lines add up to 100.0% with blanks, spoilt ballots and undecided voters, which is coherent. ⚠️ The press publishes the sample as 3,804 and the TSE registration carries 3,840, and the panel uses the published figure with the registered one declared beside it. ⚠️ Veritá has a reliability of 2 on the house scale, the lowest among the institutes in the window, and it is not data to be read on its own: the other national polls of the window still put Lula ahead by margins of 3 to 9.7 points. 📌 The method declared to the TSE is interviewing by automated audible response unit on mobile phones, with transcription by artificial intelligence, and not face-to-face interviewing.`,
  'polls[0].source': `Veritá, registration BR-09426/2026 at the TSE, reported by CNN Brasil and Terra Brasil Notícias on 06/Sep and aggregated in the Wikipedia table, which records the same fieldwork and the same percentages. The institute's own site had not published the round at the time of checking.`,
  'polymarketComparison.note': `Polymarket prices with the presidential book at USD 144.11M, ${S6} (16:53 UTC). ⭐ IN THIS ROUND ALL FIVE BOOKS CONFIRMED across the two independent readings, and the winner book is receiving a new price again. ⭐ AND THE POLL AND THE PRICE MOVED IN OPPOSITE DIRECTIONS: Veritá of 06/Sep puts Flávio Bolsonaro at 38.9% against 38.4% for Lula in the ${G('first round', 'primeiro-turno')}, a distance inside the margin of 2 points, while the winner contract widened the gap from 15.35pp to 16.80pp. They are different quantities, declared voting intention and probability of winning, and they do not subtract from one another. 📌 Still without a new price are the names below 0.5% in the winner contract, which is the floor of the double reading: Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas and Fernando Haddad.`,
  'polymarketComparison.sources': `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20pp. The confirmation is made contract by contract, and on 06/Sep all five books confirmed in the 13:53 BRT reading. Polls registered at the TSE and released by the institutes, with reporting by CNN Brasil, Terra Brasil Notícias, Poder360, Gazeta do Povo, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC and Jornal de Brasília. The calendar of polls in the field and of scheduled releases comes from the official TSE register. Series superlatives checked against the Neon backup, in backup/neon/marketPrice, which holds the complete record since 14/Apr.`,

  'polymarketComparison.candidates[0].polymarket': '56.50%',
  'polymarketComparison.candidates[0].pesquisaRange': '38.4%',
  'polymarketComparison.candidates[0].tendenciaPesquisa': `Veritá of 06/Sep (BR-09426/2026, fieldwork 01 to 04/Sep, n=3,804, margin of 2pp) measures him at 38.4% in the ${G('first round', 'primeiro-turno')}, behind Flávio Bolsonaro by 0.5 point. ⚠️ THE DISTANCE FITS INSIDE THE MARGIN, so the poll measures a statistical tie. On 21/Aug the same house gave him 39.3% against 39.1%. The survey carries no ${G('runoff', 'segundo-turno')} scenario, and the most recent reading of that pairing is still Datafolha of 03/Sep, which has him beating the four pairings tested.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `56.50% (vol USD 9.83M) in the winner contract, ${S6}, a rise of 1.00pp against the ${S4}. ⭐ THE GAP TO THE RUNNER-UP WIDENED FROM 15.35pp TO 16.80pp ON THE SAME DAY THE POLL CLOSED IT. In the first-round runner-up contract he rose 2.55pp to 7.90% (vol USD 474 thousand). In the series recorded since 14/Apr his contract runs from 34.50% to 67.50%, and today's 56.50% sits inside that range.`,

  'polymarketComparison.candidates[1].polymarket': '39.70%',
  'polymarketComparison.candidates[1].pesquisaRange': '38.9%',
  'polymarketComparison.candidates[1].tendenciaPesquisa': `⭐ VERITÁ OF 06/Sep PUTS HIM NUMERICALLY AHEAD IN THE ${G('FIRST ROUND', 'primeiro-turno')}, 38.9% against 38.4%, and it is the second national poll of the window to do so, after Gerp of 26/Aug (38% to 37%). ⚠️ The 0.5 point sits inside the margin of 2 points, so it is a statistical tie. Inside Veritá itself the sign flipped since 21/Aug, when the house gave 39.3% to Lula against 39.1% for him. Veritá has a reliability of 2 on the house scale.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `39.70% (vol USD 9.74M) in the winner contract, ${S6}, a fall of 0.45pp against the ${S4}. ⚠️ THE PRICE MOVED AGAINST THE POLL on the same day. In the first-round runner-up contract he is still at 89.50% (vol USD 612 thousand), unchanged, and only one point in the whole series has ever sat above that, the 90.50% of 21/Aug.`,

  'polymarketComparison.candidates[2].polymarket': '1.15%',
  'polymarketComparison.candidates[2].pesquisaRange': '12.2%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': `⭐ VERITÁ OF 06/Sep MEASURES HIM AT 12.2% IN THE ${G('FIRST ROUND', 'primeiro-turno')}, against 2.2% in the same house's round of 21/Aug. He is third in the survey, comfortably ahead of the fourth, who has 3.7%. The spread between houses in the window is still wide: Datafolha of 03/Sep left him at 7% and 8%.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.15% (vol USD 4.16M) in the WINNER contract, ${S6}, a fall of 0.80pp. ⭐ In the THIRD-PLACE contract of the first round, which is a different market, he rose 4.25pp to 56.20% (vol USD 126 thousand), reversing two consecutive falls. 📌 His two contracts moved in opposite directions: the market is consolidating him as the third-placed finisher of the first round and not as a candidate to win the election.`,

  'polymarketComparison.candidates[3].polymarket': '1.60%',
  'polymarketComparison.candidates[3].pesquisaRange': '3.7%',
  'polymarketComparison.candidates[3].tendenciaPesquisa': `Veritá of 06/Sep measures him at 3.7% in the ${G('first round', 'primeiro-turno')}, ahead of Ronaldo Caiado (1.9%) and Pablo Marçal (1.4%). ⚠️ THE SPREAD BETWEEN HOUSES IN THIS WINDOW RUNS FROM 3% TO 7.6%, and the 3.7% sits at the bottom of it.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.60% (vol USD 12.70M) in the winner contract, ${S6}, a fall of 0.25pp. In the third-place contract of the first round he rose 1.50pp to 26.00% (vol USD 279 thousand), a third consecutive gain. 📌 Among the four names above 1% in the winner contract, his is the largest accumulated volume, above the leader and the runner-up, in a contract priced below 2%.`,

  'polymarketComparison.candidates[4].pesquisaRange': '1.9%',
  'polymarketComparison.candidates[4].tendenciaPesquisa': `Veritá of 06/Sep puts him at 1.9% in the ${G('first round', 'primeiro-turno')}, below the 4% Datafolha measured on 03/Sep. The survey carries no ${G('runoff', 'segundo-turno')} scenario, so the most recent reading of the pairing against him is still Datafolha, at 46% to 41%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.15% (vol USD 7.16M) in the WINNER contract, ${PISO}. In the THIRD-PLACE contract of the first round, which is a different market, he rose 0.50pp back to 10.00% (vol USD 114 thousand), ${S6}.`,

  'polymarketComparison.candidates[5].pesquisaRange': '1.4%',
  'polymarketComparison.candidates[5].tendenciaPesquisa': `Veritá of 06/Sep measures him at 1.4% in the ${G('first round', 'primeiro-turno')}. ⚠️ INSIDE THE HOUSE ITSELF HE FELL FROM 5.2% TO 1.4% SINCE 21/Aug, and Datafolha of 03/Sep measured him at 2%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.73M) in the WINNER contract, ${PISO}. In the THIRD-PLACE contract of the first round he stands at 2.25% (vol USD 47 thousand), ${S6}.`,

  'polymarketComparison.candidates[6].pesquisaRange': '0.3%',
  'polymarketComparison.candidates[6].tendenciaPesquisa': `Veritá of 06/Sep measures him at 0.3% in the ${G('first round', 'primeiro-turno')}, below the 2% Datafolha measured on 03/Sep. The survey carries no ${G('runoff', 'segundo-turno')} scenario, so the most recent reading of the pairing against him is still Datafolha, at 48% to 39%.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.15% (vol USD 6.56M) in the WINNER contract, ${PISO}. In the THIRD-PLACE contract of the first round he rose 0.15pp to 0.85% (vol USD 49 thousand), ${S6}.`,

  'polymarketComparison.candidates[7].tendenciaPesquisa': 'He is not tested as a presidential candidate in the national polls of the window, and Veritá of 06/Sep does not test him either.',
  'polymarketComparison.candidates[8].tendenciaPesquisa': 'He is not tested as a presidential candidate in the national polls of the window, and Veritá of 06/Sep does not test him either.',
})
