/** Mapa ES: analysis-criteriosa, rodada de 06/Set/2026. Pesquisa e preço em direções opostas. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S6 = 'lectura confirmada del 06/Sep, 13:53 BRT'
const S4 = 'lectura confirmada del 04/Sep'
const PISO = 'por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 6 de septiembre de 2026, ${S6} (16:53 UTC) en los cinco libros, con el presidencial en USD 144,11M. Encuesta nacional más reciente: Veritá del 06/Sep, registro BR-09426/2026 en el TSE, campo del 01 al 04/Sep. En esta ronda los cinco libros confirmaron en las dos lecturas.`,

  // ── Lula
  'candidates[0].header': `PRECIO: 56,50% (vol USD 9,83M acumulado) en el contrato de ganador, ${S6}, una subida de 1,00pp frente a la ${S4}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,55pp hasta 7,90% (vol USD 474 mil). ENCUESTA: la Veritá del 06/Sep (BR-09426/2026, campo del 01 al 04/Sep, n=3.804, margen de 2pp) lo mide en 38,4% en la primera vuelta, detrás de Flávio Bolsonaro por 0,5 punto. El levantamiento no trae escenario de ${G('segunda vuelta', 'segundo-turno')}.`,
  'candidates[0].fortes[0]': 'Subió 1,00pp en el contrato de ganador y abrió la distancia hacia el segundo, que pasa de 15,35pp a 16,80pp desde la lectura confirmada del 04/Sep.',
  'candidates[0].fortes[1]': '⭐ EL PRECIO ABRIÓ LA BRECHA EL MISMO DÍA EN QUE LA ENCUESTA LA CERRÓ, y las dos mediciones ordenan la disputa de formas opuestas.',
  'candidates[0].fortes[2]': 'En la serie registrada desde el 14/Abr su contrato va de 34,50% a 67,50%, y el 56,50% de hoy está dentro de ese rango, a 12,00pp del techo del 16/Ago.',
  'candidates[0].fortes[3]': 'La lectura de segunda vuelta más reciente sigue siendo la Datafolha del 03/Sep, que lo da ganando los cuatro pares que probó, y la Veritá de hoy no probó ninguno.',
  'candidates[0].fortes[4]': 'El volumen acumulado en su contrato llegó a USD 9,83M, y el libro presidencial entero está en USD 144,11M.',
  'candidates[0].fracos[0]': '⚠️ LA VERITÁ DEL 06/Sep LO PONE DETRÁS POR PRIMERA VEZ EN UNA RONDA DE ESA CASA: el 21/Ago la misma Veritá le daba 39,3% contra 39,1%, y ahora son 38,4% contra 38,9%.',
  'candidates[0].fracos[1]': 'Es la segunda nacional de la ventana que coloca a Flávio Bolsonaro numéricamente delante en la primera vuelta, después de la Gerp del 26/Ago, que dio 38% a 37%.',
  'candidates[0].fracos[2]': 'La distancia de 0,5 punto está dentro del margen de 2 puntos declarado por Veritá, así que la encuesta mide empate técnico y no una ventaja del adversario.',
  'candidates[0].fracos[3]': 'Veritá tiene confiabilidad 2 en la regla de la casa, la más baja entre los institutos de la ventana, y no es dato que se lea solo.',
  'candidates[0].fracos[4]': 'La desaprobación del gobierno en la Datafolha del 03/Sep es de 51% contra 45% de aprobación, y la Veritá de hoy no divulgó evaluación de gobierno.',
  'candidates[0].analise': `El 6 de septiembre es el día en que las dos mediciones de esta página apuntan hacia lados opuestos, y eso es lo que ella registra. El contrato de ganador subió 1,00pp hasta 56,50% (vol USD 9,83M) y abrió la distancia hacia el segundo de 15,35pp a 16,80pp. El mismo día, Veritá divulgó la primera nacional tras dos días sin ninguna y midió 38,4% para él contra 38,9% del adversario, distancia de 0,5 punto dentro de un margen de 2 puntos. 📌 Son magnitudes distintas: la encuesta mide intención de voto declarada en la ${G('primera vuelta', 'primeiro-turno')} y el contrato mide probabilidad de ganar la elección, y no se restan. El AFOS no arbitra cuál está en lo cierto, registra que hoy discrepan en el orden y que el precio se movió sin que la encuesta lo acompañara.`,

  // ── Flávio Bolsonaro
  'candidates[1].header': `PRECIO: 39,70% (vol USD 9,74M acumulado) en el contrato de ganador, ${S6}, una caída de 0,45pp frente a la ${S4}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} sigue en 89,50% (vol USD 612 mil), sin variación. ENCUESTA: la Veritá del 06/Sep (BR-09426/2026, campo del 01 al 04/Sep, n=3.804, margen de 2pp) lo pone en 38,9% en la primera vuelta, delante de Lula por 0,5 punto y dentro del margen.`,
  'candidates[1].fortes[0]': '⭐ LA VERITÁ DEL 06/Sep LO PONE NUMÉRICAMENTE DELANTE EN LA PRIMERA VUELTA, 38,9% contra 38,4%, y es la segunda nacional de la ventana en hacerlo, después de la Gerp del 26/Ago.',
  'candidates[1].fortes[1]': 'Dentro de la propia Veritá el signo se invirtió: el 21/Ago la casa daba 39,3% a Lula contra 39,1% de él, y ahora el orden está invertido.',
  'candidates[1].fortes[2]': 'Sigue en 89,50% en el contrato de segundo lugar de la primera vuelta (vol USD 612 mil), y solo un punto de toda la serie estuvo alguna vez por encima de eso, el 90,50% del 21/Ago.',
  'candidates[1].fortes[3]': 'El volumen acumulado en su contrato de ganador está en USD 9,74M, prácticamente empatado con el del líder, que está en USD 9,83M.',
  'candidates[1].fortes[4]': 'El 05/Sep visitó en Paraná a un condenado por la trama golpista y volvió a exigir el apartamiento de Alexandre de Moraes, según O Globo y Folha de S.Paulo.',
  'candidates[1].fracos[0]': '⚠️ EL PRECIO SE MOVIÓ CONTRA LA ENCUESTA: cedió 0,45pp en el contrato de ganador el mismo día en que la Veritá lo puso delante en la primera vuelta.',
  'candidates[1].fracos[1]': 'La distancia hacia el líder en el contrato de ganador se abrió de 15,35pp a 16,80pp desde la lectura confirmada del 04/Sep.',
  'candidates[1].fracos[2]': 'La ventaja de 0,5 punto en la Veritá está dentro del margen de 2 puntos, así que lo que la encuesta mide es empate técnico y no una ventaja.',
  'candidates[1].fracos[3]': 'Veritá tiene confiabilidad 2 en la regla de la casa, y las demás nacionales de la ventana siguen dando al líder delante por márgenes de 3 a 9,7 puntos.',
  'candidates[1].fracos[4]': 'La Veritá de hoy no probó ningún escenario de segunda vuelta, así que la lectura más reciente de ese par sigue siendo la Datafolha del 03/Sep, que lo da a 2 puntos, 44% contra 46%.',
  'candidates[1].analise': `Su día tiene un número fuerte y un precio que no lo acompañó. La Veritá del 06/Sep, con campo del 01 al 04/Sep y 3.804 entrevistas, lo mide en 38,9% contra 38,4% del líder, y es la segunda nacional de la ventana en colocarlo numéricamente delante en la ${G('primera vuelta', 'primeiro-turno')}. ⚠️ La distancia de 0,5 punto cabe entera dentro del margen de 2 puntos declarado, así que la lectura correcta es empate técnico. En el mercado el movimiento fue el opuesto: el contrato de ganador cedió 0,45pp hasta 39,70% (vol USD 9,74M), con la distancia hacia el líder abriéndose de 15,35pp a 16,80pp. 📌 En el contrato de segundo lugar de la primera vuelta sigue en 89,50%, sin variación en esta lectura, y es ahí donde el mercado concentra su convicción sobre él.`,

  // ── Augusto Cury
  'candidates[2].header': `PRECIO: 1,15% (vol USD 4,16M acumulado) en el contrato de ganador, ${S6}, una caída de 0,80pp frente a la ${S4}. ⭐ En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 4,25pp hasta 56,20% (vol USD 126 mil). ENCUESTA: la Veritá del 06/Sep lo mide en 12,2% en la primera vuelta, frente a 2,2% en la ronda de la propia casa del 21/Ago.`,
  'candidates[2].fortes[0]': '⭐ ES EL ÚNICO NOMBRE QUE SUBE EN LAS DOS MEDICIONES DE ESTA RONDA: más 4,25pp en el contrato de tercer lugar de la primera vuelta, y 12,2% en la Veritá frente a 2,2% en la ronda de la misma casa del 21/Ago. En la encuesta, todos los demás nombres cedieron entre las dos rondas de la casa.',
  'candidates[2].fortes[1]': 'El 56,20% en el contrato de tercer lugar revierte dos caídas seguidas y lo devuelve por encima del nivel del 03/Sep.',
  'candidates[2].fortes[2]': 'Sigue como líder aislado de ese mercado, con 56,20% contra 26,00% del segundo colocado, una distancia de 30,20pp.',
  'candidates[2].fortes[3]': 'La Veritá lo coloca tercero en la primera vuelta con holgura sobre el cuarto, que es Renan Santos con 3,7%.',
  'candidates[2].fracos[0]': '⚠️ EN EL CONTRATO DE GANADOR CEDIÓ 0,80pp Y ESTÁ EN 1,15%, el valor más bajo entre los cuatro nombres por encima de 1% del libro.',
  'candidates[2].fracos[1]': 'Sus dos contratos se movieron en direcciones opuestas en esta lectura: más 4,25pp en el de tercer lugar y menos 0,80pp en el de ganador.',
  'candidates[2].fracos[2]': 'El mercado lo trata como candidato al pelotón de cabeza de la primera vuelta y no como candidato a ganar la elección, y el volumen de USD 4,16M convive con un precio por debajo de 1,5%.',
  'candidates[2].fracos[3]': 'En el contrato de segundo lugar de la primera vuelta está en 0,95% (vol USD 143 mil), por debajo de 1%.',
  'candidates[2].analise': `Es el único nombre del panel que sube en las dos mediciones a la vez, y la distancia entre ellas es lo que interesa. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 4,25pp hasta 56,20% (vol USD 126 mil), revirtiendo dos caídas seguidas. En la Veritá del 06/Sep aparece con 12,2% en la primera vuelta, frente a 2,2% en la ronda de la propia casa del 21/Ago. ⚠️ Y en el contrato de ganador el movimiento es contrario: cedió 0,80pp hasta 1,15% (vol USD 4,16M). 📌 Las tres lecturas son coherentes entre sí si se leen por lo que cada una mide: el mercado lo ve consolidado como tercer colocado de la primera vuelta y no lo ve como candidato a ganar la elección, y la encuesta mide exactamente la primera de esas dos cosas.`,

  // ── Renan Santos
  'candidates[3].header': `PRECIO: 1,60% (vol USD 12,70M acumulado) en el contrato de ganador, ${S6}, una caída de 0,25pp frente a la ${S4}. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,50pp hasta 26,00% (vol USD 279 mil). ENCUESTA: la Veritá del 06/Sep lo mide en 3,7% en la primera vuelta.`,
  'candidates[3].fortes[0]': 'Subió 1,50pp en el contrato de tercer lugar de la primera vuelta y está en 26,00%, tercera subida seguida en ese mercado.',
  'candidates[3].fortes[1]': 'Es el contrato de mayor volumen acumulado entre los cuatro nombres por encima de 1% del libro presidencial, con USD 12,70M, por encima del líder y del segundo colocado.',
  'candidates[3].fortes[2]': 'La Veritá del 06/Sep lo mide en 3,7%, delante de Ronaldo Caiado, que está en 1,9%, y de Pablo Marçal, que está en 1,4%.',
  'candidates[3].fracos[0]': 'Cedió 0,25pp en el contrato de ganador y está en 1,60%, por debajo de 2% por tercer día.',
  'candidates[3].fracos[1]': 'Su distancia hacia el primer colocado del contrato de tercer lugar sigue amplia, 26,00% contra 56,20%, o 30,20pp.',
  'candidates[3].fracos[2]': 'En la serie registrada desde el 14/Abr su contrato de ganador ya llegó a 17,90%, el 09/Jun, y el 1,60% de hoy está a 15,90pp de ese techo.',
  'candidates[3].fracos[3]': 'El 3,7% de la Veritá está en la parte baja de la dispersión de la ventana, que va de 3% a 7,6% entre las casas.',
  'candidates[3].analise': `Su patrón se mantiene y quedó más nítido. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 1,50pp hasta 26,00% (vol USD 279 mil), tercera subida seguida, mientras en el de ganador cedió 0,25pp hasta 1,60% (vol USD 12,70M). 📌 Su contrato sigue siendo el de mayor volumen acumulado entre los cuatro nombres por encima de 1%, por encima del líder y del segundo colocado, con un precio por debajo de 2%. Volumen acumulado es dinero que ya pasó por el contrato desde su apertura y no dice hacia qué lado fue. La Veritá del 06/Sep lo mide en 3,7% en la primera vuelta, dentro de la franja de 3% a 7,6% en que las casas de la ventana lo colocan.`,

  // ── Caiado / Haddad / Zema
  'candidates[4].header': `PRECIO: los tres siguen por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para ellos en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}, Ronaldo Caiado subió 0,50pp hasta 10,00% (vol USD 114 mil) y Romeu Zema subió 0,15pp hasta 0,85% (vol USD 49 mil), ${S6}. ENCUESTA: la Veritá del 06/Sep pone a Caiado en 1,9% y a Zema en 0,3% en la primera vuelta.`,
  'candidates[4].subtitle': `Pelotón de cola en la ${S6} (16:53 UTC). ⚠️ LA VERITÁ DEL 06/Sep MIDE A LOS DOS POR DEBAJO DE LO QUE LAS OTRAS CASAS DE LA VENTANA VENÍAN MIDIENDO, con Ronaldo Caiado en 1,9% y Romeu Zema en 0,3% en la primera vuelta, frente a 4% y 2% en la Datafolha del 03/Sep. Y no probó ningún escenario de ${G('segunda vuelta', 'segundo-turno')}. El par contra Ronaldo Caiado sigue con cuatro lecturas distintas en la misma semana, todas con campo superpuesto: 45% a 43% a su favor en la Real Time Big Data del 01/Sep, 42% a 37% en su contra en la Genial/Quaest del 02/Sep, 44% a 42% en su contra en la PoderData del 03/Sep y 46% a 41% en su contra en la Datafolha del mismo día.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0,15% (vol USD 7,16M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la primera vuelta, que es otro mercado, subió 0,50pp y volvió a 10,00%, en un libro de USD 114 mil, ${S6} (16:53 UTC).`,
  'candidates[4].caiado.fortes': 'Subió 0,50pp en el contrato de tercer lugar de la primera vuelta y volvió a 10,00%, tercer colocado de ese mercado, detrás solo de Augusto Cury y Renan Santos. El par de segunda vuelta contra él en la Datafolha del 03/Sep es de 5 puntos, 46% a 41%, más estrecho que el de Romeu Zema, que es de 9 puntos. Llevó la crisis del Supremo y el caso Master al espacio electoral gratuito, según Valor Econômico.',
  'candidates[4].caiado.fracos': '⚠️ LA VERITÁ DEL 06/Sep LO MIDE EN 1,9% EN LA PRIMERA VUELTA, por debajo del 4% de la Datafolha del 03/Sep y del 3,3% que la propia Veritá medía el 21/Ago. En el contrato de ganador sigue por debajo del piso de 0,5% de la doble lectura. Y el par de segunda vuelta en que él aparece ya fue medido por cuatro casas en la misma semana, con cuatro resultados distintos, y la Veritá no lo probó.',
  'candidates[4].haddad.fortes': 'No es probado como candidato presidencial en las nacionales de la ventana, y la Veritá del 06/Sep tampoco lo prueba, así que no hay lectura de urna que cruzar con el precio.',
  'candidates[4].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,56M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la primera vuelta, que es otro mercado, subió 0,15pp hasta 0,85%, en un libro de USD 49 mil, ${S6} (16:53 UTC).`,
  'candidates[4].zema.fortes': 'Subió 0,15pp en el contrato de tercer lugar de la primera vuelta y está en 0,85%. En la PoderData del 03/Sep queda a 2 puntos del líder en la segunda vuelta, 44% a 42%, el margen más estrecho contra él en cualquier nacional de la ventana.',
  'candidates[4].zema.fracos': '⚠️ LA VERITÁ DEL 06/Sep LO MIDE EN 0,3% EN LA PRIMERA VUELTA, por debajo del 2% de la Datafolha del 03/Sep y del 1,3% que la propia Veritá medía el 21/Ago. El par de segunda vuelta contra él es el de mayor dispersión entre casas de la ventana, con las cuatro casas de la semana midiendo 3, 11, 2 y 9 puntos, y la Veritá no lo probó.',
  'candidates[4].fortes[0]': 'Ronaldo Caiado subió 0,50pp en el contrato de tercer lugar de la primera vuelta y volvió a 10,00% (vol USD 114 mil), tercer colocado de ese mercado.',
  'candidates[4].fortes[1]': 'Romeu Zema subió 0,15pp en el contrato de tercer lugar y está en 0,85% (vol USD 49 mil).',
  'candidates[4].fortes[2]': 'La lectura de segunda vuelta más reciente contra Caiado sigue siendo la Datafolha del 03/Sep, de 5 puntos, 46% a 41%, más estrecha que la de Zema, que es de 9 puntos.',
  'candidates[4].fracos[0]': '⚠️ LA VERITÁ DEL 06/Sep DA 1,9% A CAIADO Y 0,3% A ZEMA, y los dos quedan por debajo de lo que las otras casas de la ventana venían midiendo, que era 4% y 2% en la Datafolha del 03/Sep.',
  'candidates[4].fracos[1]': 'En el contrato de ganador Caiado está en 0,15% y Zema en 0,15%, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para ellos ahí.',
  'candidates[4].fracos[3]': 'La Veritá no probó ningún escenario de segunda vuelta, así que no hay lectura nueva de los pares contra ellos.',
  'candidates[4].analise': `Los dos que se movieron el 06/Sep se movieron en el mercado de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}, que no es el de ganador. Ronaldo Caiado subió 0,50pp y volvió a 10,00% (vol USD 114 mil) y Romeu Zema subió 0,15pp hasta 0,85% (vol USD 49 mil). ⚠️ En la Veritá del 06/Sep los dos aparecen por debajo de lo que las otras casas de la ventana venían midiendo, con 1,9% y 0,3% frente a 4% y 2% en la Datafolha del 03/Sep, y la comparación entre casas distintas carga método distinto. Fernando Haddad no es candidato a la Presidencia y disputa el gobierno de São Paulo. En el contrato de ganador los tres siguen por debajo del piso de 0,5% de la doble lectura.`,

  // ── quadro comparativo
  'quadroComparativo[0].p': 'La Veritá del 06/Sep (BR-09426/2026, campo del 01 al 04/Sep, n=3.804, margen de 2pp) lo mide en 38,4% en la primera vuelta, detrás de Flávio Bolsonaro por 0,5 punto, dentro del margen. El 21/Ago la misma casa le daba 39,3% contra 39,1%. El levantamiento no trae escenario de segunda vuelta, y la lectura más reciente de ese par sigue siendo la Datafolha del 03/Sep, que lo da ganando los cuatro pares probados.',
  'quadroComparativo[0].m': `56,50% (vol USD 9,83M) en el contrato de ganador, ${S6}, una subida de 1,00pp frente a la ${S4}. En el contrato de segundo lugar de la primera vuelta subió 2,55pp hasta 7,90% (vol USD 474 mil).`,
  'quadroComparativo[0].t': 'subió en el contrato de ganador y abrió la brecha hasta 16,80pp, el mismo día en que la encuesta la cerró',
  'quadroComparativo[0].s': 'El 05/Sep hizo un acto de campaña en el interior de São Paulo, pidió voto para Fernando Haddad y no trató la crisis del Supremo, según O Globo y CartaCapital.',
  'quadroComparativo[1].p': '⭐ La Veritá del 06/Sep lo pone en 38,9% en la primera vuelta, numéricamente delante de Lula por 0,5 punto, dentro del margen de 2 puntos. Es la segunda nacional de la ventana en colocarlo delante, después de la Gerp del 26/Ago, que dio 38% a 37%. Veritá tiene confiabilidad 2 en la regla de la casa.',
  'quadroComparativo[1].m': `39,70% (vol USD 9,74M) en el contrato de ganador, ${S6}, una caída de 0,45pp frente a la ${S4}. En el contrato de segundo lugar de la primera vuelta sigue en 89,50% (vol USD 612 mil), sin variación.`,
  'quadroComparativo[1].t': 'delante en la encuesta y en caída en el precio, el mismo día',
  'quadroComparativo[1].s': 'Interrumpió la campaña el 05/Sep para visitar en Paraná a un condenado por la trama golpista y volvió a exigir el apartamiento de Alexandre de Moraes, según O Globo y Folha de S.Paulo.',
  'quadroComparativo[2].p': '⭐ La Veritá del 06/Sep lo mide en 12,2% en la primera vuelta, frente a 2,2% en la ronda de la propia casa del 21/Ago. Es el tercer colocado del levantamiento, con holgura sobre el cuarto, que tiene 3,7%.',
  'quadroComparativo[2].m': `1,15% (vol USD 4,16M) en el contrato de ganador, ${S6}, una caída de 0,80pp. ⭐ En el contrato de tercer lugar de la primera vuelta subió 4,25pp hasta 56,20% (vol USD 126 mil), revirtiendo dos caídas seguidas.`,
  'quadroComparativo[2].t': 'sube en los dos universos como tercer colocado y cede en el contrato de ganar la elección',
  'quadroComparativo[2].s': 'Sin acto individual nuevo el 06/Sep. Es probado en la segunda vuelta de las encuestas que Nexus y AtlasIntel marcaron para el 08 y el 10/Sep.',
  'quadroComparativo[3].p': 'La Veritá del 06/Sep lo mide en 3,7% en la primera vuelta, delante de Ronaldo Caiado (1,9%) y de Pablo Marçal (1,4%). La dispersión entre casas de la ventana sigue amplia, de 3% a 7,6%.',
  'quadroComparativo[3].m': `1,60% (vol USD 12,70M) en el contrato de ganador, ${S6}, una caída de 0,25pp. En el contrato de tercer lugar de la primera vuelta subió 1,50pp hasta 26,00% (vol USD 279 mil), tercera subida seguida.`,
  'quadroComparativo[3].t': 'tercera subida seguida en el contrato de tercer lugar, con el de ganador cediendo',
  'quadroComparativo[3].s': 'Sigue como autor del pedido de destitución contra dos ministros del Supremo. Sin acto individual nuevo el 06/Sep.',
  'quadroComparativo[4].p': 'La Veritá del 06/Sep lo pone en 1,9% en la primera vuelta, por debajo del 4% que la Datafolha medía el 03/Sep. El levantamiento no trae escenario de segunda vuelta.',
  'quadroComparativo[4].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la primera vuelta subió 0,50pp hasta 10,00% (vol USD 114 mil), ${S6}.`,
  'quadroComparativo[4].t': 'subió 0,50pp en el contrato de tercer lugar y cayó en la encuesta',
  'quadroComparativo[4].s': 'Llevó la crisis del Supremo y el caso Master al espacio electoral gratuito, según Valor Econômico. Sin otro acto individual el 06/Sep.',
  'quadroComparativo[5].p': 'La Veritá del 06/Sep lo mide en 1,4% en la primera vuelta, por debajo del 5,2% que la misma casa medía el 21/Ago y del 2% de la Datafolha del 03/Sep.',
  'quadroComparativo[5].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la primera vuelta está en 2,25% (vol USD 47 mil), ${S6}.`,
  'quadroComparativo[5].t': 'cede en la encuesta dentro de la propia casa, de 5,2% a 1,4% desde el 21/Ago',
  'quadroComparativo[5].s': 'Sin acto individual nuevo el 06/Sep.',

  cruzamento: `El 6 de septiembre es el día en que las dos mediciones de esta página apuntan hacia lados opuestos, y registrarlo es su función. ⭐ LA SEQUÍA DE ENCUESTAS NACIONALES TERMINÓ AL TERCER DÍA: Veritá divulgó una nacional con campo del 01 al 04/Sep, registro BR-09426/2026 en el ${G('TSE', 'tse')}, 3.804 entrevistas y margen de 2 puntos, y pone a Flávio Bolsonaro en 38,9% contra 38,4% de Lula en la ${G('primera vuelta', 'primeiro-turno')}. ⚠️ La distancia de 0,5 punto cabe entera dentro del margen declarado, así que lo que la encuesta mide es empate técnico, no una ventaja. Es la segunda nacional de la ventana que trae al segundo colocado numéricamente delante, después de la Gerp del 26/Ago, que dio 38% a 37%, y Veritá tiene confiabilidad 2 en la regla de la casa. ⭐ EL MISMO DÍA EL MERCADO SE MOVIÓ HACIA EL OTRO LADO: con los cinco libros confirmados en las dos lecturas, el contrato de ganador dio 56,50% a Lula y 39,70% a Flávio Bolsonaro, y la brecha pasó de 15,35pp en la lectura confirmada del 04/Sep a 16,80pp. 📌 Las dos magnitudes no se restan. La encuesta mide intención de voto declarada en la primera vuelta y el contrato mide probabilidad de ganar la elección, y un candidato puede liderar la primera y no la segunda. El AFOS no dice cuál de las dos está en lo cierto. ⭐ EL NOMBRE QUE SUBE EN LOS DOS UNIVERSOS ES AUGUSTO CURY: la Veritá lo mide en 12,2%, frente a 2,2% en la ronda de la misma casa del 21/Ago, y el contrato de tercer lugar de la primera vuelta subió 4,25pp hasta 56,20%. En el contrato de ganador, en cambio, cedió 0,80pp hasta 1,15%, lo que es coherente: el mercado lo consolida como tercer colocado de la primera vuelta y no como candidato a ganar la elección. 📌 En el Supremo el registro es de desacople. El 05/Sep el caso produjo dos actos institucionales nuevos, una propuesta de enmienda al reglamento interno presentada por Gilmar Mendes y un pedido de responsabilización hecho por Cristiano Zanin por quiebra de secreto fiscal, y el contrato de destitución antes de 2027 siguió prácticamente quieto, en 8,60% frente a 8,65% de la víspera. El 06/Sep, domingo, no hay acto institucional nuevo. El calendario del TSE trae otras diez nacionales con divulgación prevista entre el 07 y el 11/Sep, entre ellas Quaest, Nexus, AtlasIntel y Datafolha, y faltan 28 días para la primera vuelta.`,
})
