/** Mapa EN: analysis-data, rodada de 06/Set/2026. Os cinco livros confirmam, e a pesquisa e o preço andam em direções opostas. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S6 = 'confirmed reading of 06/Sep, 13:53 BRT (16:53 UTC)'
const S4 = 'confirmed reading of 04/Sep'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 144.11M and this page's prices come from the ${S6}. ⭐ IN THIS ROUND ALL FIVE BOOKS CONFIRMED, and the winner book is receiving a new price again after one round without. ⭐ AND THE NATIONAL POLLING DROUGHT ENDED ON THE THIRD DAY: Veritá released on 06/Sep a national poll with fieldwork from 01 to 04/Sep, registration BR-09426/2026 at the ${G('TSE', 'tse')}. The register shows another ten national polls with releases scheduled between 07 and 11/Sep, among them Quaest, Nexus, AtlasIntel and Datafolha. There are 28 days to the ${G('first round', 'primeiro-turno')}.`,
  'cards.sentimento.text2': `⭐ THE POLL AND THE PRICE MOVED IN OPPOSITE DIRECTIONS TODAY, and that crossing is what this page exists to record. Veritá puts Flávio Bolsonaro numerically ahead in the first round, 38.9% against 38.4% for Lula, a distance of 0.5 point inside a margin of 2 points. On the same day, the winner contract widened the gap: Lula 56.50% against 39.70%, or 16.80pp, against 15.35pp on the ${S4}. They are different quantities, declared voting intention and traded probability of winning, and they do not subtract from one another. The AFOS records that the two rank the race in opposite ways, without saying which one is right.`,
  'cards.sentimento.text3': `⚠️ AND THE BOOK THAT MOVED MOST WAS THE THIRD-PLACE ONE. Augusto Cury rose 4.25pp to 56.20%, and Renan Santos rose 1.50pp to 26.00%. 📌 Cury's name rises in both universes at once: Veritá measures him at 12.2%, against 2.2% in the same house's round of 21/Aug. In the first-round runner-up contract, Lula rose 2.55pp to 7.90%, while Flávio stayed put at 89.50%. In the Senate majority contract, the MDB gave up 0.40pp to 10.35%.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 39.70% (vol USD 9.74M accumulated) in the winner contract, ${S6}, a fall of 0.45pp against the ${S4}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he is still at 89.50% (vol USD 612 thousand), unchanged. ⭐ The most recent poll is Veritá of 06/Sep, fieldwork from 01 to 04/Sep, which puts him at 38.9% in the first round, ahead of Lula by 0.5 point and inside the margin of 2 points. It is the second national poll of the window to place him numerically ahead, after Gerp of 26/Aug.`,
  'cards.sentimento.esquerda': `Lula at 56.50% (vol USD 9.83M accumulated) in the winner contract, ${S6}, a rise of 1.00pp against the ${S4}. ⚠️ In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 2.55pp to 7.90% (vol USD 474 thousand). Veritá of 06/Sep measures him at 38.4% in the first round, behind Flávio Bolsonaro by 0.5 point, in a survey with no ${G('runoff', 'segundo-turno')} scenario. The most recent runoff reading is still Datafolha of 03/Sep, which has him beating the four pairings it tested.`,
  'cards.sentimento.terceiraVia': `⭐ Augusto Cury is the name that rose most in both universes. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 4.25pp to 56.20% (vol USD 126 thousand), ${S6}, after two consecutive falls. And Veritá of 06/Sep measures him at 12.2% in the first round, against 2.2% in the same house's round of 21/Aug. In the winner contract, however, he gave up 0.80pp to 1.15% (vol USD 4.16M): the market sees him in the leading pack of the first round and not as a candidate to win the election.`,
  'cards.sentimento.polymarket': `Prices from the ${S6}, across the five books this page follows: winner, ${G('first-round', 'primeiro-turno')} runner-up, first-round third place, ${G('Supreme Court', 'stf')} impeachment and Senate majority. The AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 point, and the confirmation is made contract by contract. In this round all five books confirmed. ⚠️ Still without a new price are the names below 0.5% in the winner contract, which are Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas and Fernando Haddad.`,
  'cards.stf.moraes': `⚠️ THE FEDERAL POLICE REPORT HE USED REMAINS UNDER AN INQUIRY OPENED ON 04/Sep by the Prosecutor General's Office, which ordered an investigation into whether there was interference in the production of the document, according to Folha de S.Paulo, Gazeta do Povo and Estadão. No new individual act on 05 or 06/Sep.`,
  'cards.stf.gilmar': `⭐ ON 05/Sep HE FILED A PROPOSED AMENDMENT TO THE COURT'S INTERNAL RULES, presented to president Edson Fachin, to bar the appointment of military and police officers, even those on leave or seconded, to commissioned posts in the justices' offices, according to Folha de S.Paulo, O Globo, Estadão, Valor Econômico and Gazeta do Povo.`,
  'cards.stf.mendonca': `⚠️ THE PROSECUTOR'S OFFICE ASKED FOR CLEARANCE TO INVESTIGATE HIM ON 04/Sep. Paulo Gonet asked Edson Fachin for authorisation to look into the suspicion that he interfered with the Federal Police, in the report on the messages, according to Estadão, O Globo and Gazeta do Povo. No new individual act on 05 or 06/Sep.`,
  'cards.stf.nexo': `⭐ THE CASE PRODUCED TWO NEW ACTS ON 05/Sep, AND NEITHER CAME FROM THE TWO JUSTICES AT THE CENTRE OF THE CRISIS. Gilmar Mendes filed a proposed amendment to the internal rules to remove police and military officers from the justices' offices, presented to Edson Fachin. And Cristiano Zanin went to the ${G('Supreme Court', 'stf')}, the Superior Electoral Court and the Paraná Court of Justice after Deltan Dallagnol attached his tax secrecy data to a candidacy registration, asking that those responsible be held to account, according to Folha de S.Paulo, O Globo, Estadão and Valor Econômico. 📌 Edson Fachin signalled on 05/Sep an intention to take the crisis to the full bench, and that decision has not yet been taken. On 06/Sep, a Sunday, there is no new institutional act.`,
  'cards.stf.analise': `8.60% (vol USD 88 thousand) in the contract on a ${G('Supreme Court', 'stf')} justice leaving by impeachment before 2027, ${S6}, all but unchanged against the 8.65% of the day before. 📌 The contrast with the news is the record of the day: on 05/Sep the case produced two new institutional acts, a proposed amendment to the internal rules and a request for accountability over a breach of tax secrecy, and the price did not move. In the series recorded since 14/Apr the high is 19.30%, set on 04/Sep, and the low is 2.10%, from 08/Jun, so today's price sits 10.60pp below a high from two days ago, in a book that has accumulated USD 88 thousand.`,
})
