/** Mapa ES: analysis-data, rodada de 06/Set/2026. Os cinco livros confirmam, e a pesquisa e o preço andam em direções opostas. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S6 = 'lectura confirmada del 06/Sep, 13:53 BRT (16:53 UTC)'
const S4 = 'lectura confirmada del 04/Sep'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 144,11M y los precios de esta página son de la ${S6}. ⭐ EN ESTA RONDA LOS CINCO LIBROS CONFIRMARON, y el de ganador vuelve a recibir precio nuevo tras una ronda sin él. ⭐ Y LA SEQUÍA DE ENCUESTAS NACIONALES TERMINÓ AL TERCER DÍA: Veritá divulgó el 06/Sep una nacional con campo del 01 al 04/Sep, registro BR-09426/2026 en el ${G('TSE', 'tse')}. El registro muestra otras diez nacionales con divulgación prevista entre el 07 y el 11/Sep, entre ellas Quaest, Nexus, AtlasIntel y Datafolha. Faltan 28 días para la ${G('primera vuelta', 'primeiro-turno')}.`,
  'cards.sentimento.text2': `⭐ LA ENCUESTA Y EL PRECIO SE MOVIERON EN DIRECCIONES OPUESTAS HOY, y ese cruce es lo que esta página existe para registrar. Veritá pone a Flávio Bolsonaro numéricamente delante en la primera vuelta, 38,9% contra 38,4% de Lula, una distancia de 0,5 punto dentro de un margen de 2 puntos. El mismo día, el contrato de ganador abrió la brecha: Lula 56,50% contra 39,70%, o 16,80pp, frente a 15,35pp en la ${S4}. Son magnitudes distintas, intención de voto declarada y probabilidad de ganar negociada, y no se restan. El AFOS registra que las dos ordenan la disputa de formas opuestas, sin decir cuál está en lo cierto.`,
  'cards.sentimento.text3': `⚠️ Y EL LIBRO QUE MÁS SE MOVIÓ FUE EL DE TERCER LUGAR. Augusto Cury subió 4,25pp hasta 56,20%, y Renan Santos subió 1,50pp hasta 26,00%. 📌 El nombre de Cury sube en los dos universos a la vez: Veritá lo mide en 12,2%, frente a 2,2% en la ronda de la propia casa del 21/Ago. En el contrato de segundo lugar de la primera vuelta, Lula subió 2,55pp hasta 7,90%, mientras Flávio se quedó quieto en 89,50%. En el de mayoría en el Senado, el MDB cedió 0,40pp hasta 10,35%.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 39,70% (vol USD 9,74M acumulado) en el contrato de ganador, ${S6}, una caída de 0,45pp frente a la ${S4}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} sigue en 89,50% (vol USD 612 mil), sin variación. ⭐ La encuesta más reciente es la Veritá del 06/Sep, campo del 01 al 04/Sep, que lo pone en 38,9% en la primera vuelta, delante de Lula por 0,5 punto y dentro del margen de 2 puntos. Es la segunda nacional de la ventana que lo coloca numéricamente delante, después de la Gerp del 26/Ago.`,
  'cards.sentimento.esquerda': `Lula en 56,50% (vol USD 9,83M acumulado) en el contrato de ganador, ${S6}, una subida de 1,00pp frente a la ${S4}. ⚠️ En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,55pp hasta 7,90% (vol USD 474 mil). La Veritá del 06/Sep lo mide en 38,4% en la primera vuelta, detrás de Flávio Bolsonaro por 0,5 punto, en un levantamiento sin escenario de ${G('segunda vuelta', 'segundo-turno')}. La lectura de segunda vuelta más reciente sigue siendo la Datafolha del 03/Sep, que lo da ganando los cuatro pares que probó.`,
  'cards.sentimento.terceiraVia': `⭐ Augusto Cury es el nombre que más subió en los dos universos. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 4,25pp hasta 56,20% (vol USD 126 mil), ${S6}, tras dos caídas seguidas. Y la Veritá del 06/Sep lo mide en 12,2% en la primera vuelta, frente a 2,2% en la ronda de la propia casa del 21/Ago. En el contrato de ganador, en cambio, cedió 0,80pp hasta 1,15% (vol USD 4,16M): el mercado lo ve en el pelotón de cabeza de la primera vuelta y no como candidato a ganar la elección.`,
  'cards.sentimento.polymarket': `Precios de la ${S6}, en los cinco libros que esta página sigue: ganador, segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, tercer lugar de la primera vuelta, destitución en el ${G('Supremo', 'stf')} y mayoría en el Senado. El AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20 punto, y la confirmación se hace contrato a contrato. En esta ronda los cinco libros confirmaron. ⚠️ Siguen sin precio nuevo los nombres por debajo de 0,5% en el contrato de ganador, que son Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas y Fernando Haddad.`,
  'cards.stf.moraes': `⚠️ EL INFORME DE LA POLICÍA FEDERAL QUE ÉL USÓ SIGUE BAJO UNA AVERIGUACIÓN ABIERTA EL 04/Sep por la Fiscalía General de la República, que ordenó investigar si hubo interferencia en la producción del documento, según Folha de S.Paulo, Gazeta do Povo y Estadão. Sin acto individual nuevo el 05 ni el 06/Sep.`,
  'cards.stf.gilmar': `⭐ EL 05/Sep PRESENTÓ UNA PROPUESTA DE ENMIENDA AL REGLAMENTO INTERNO DEL TRIBUNAL, entregada al presidente Edson Fachin, para prohibir el nombramiento de militares y policías, aunque estén de licencia o cedidos, en cargos de confianza de los despachos de los ministros, según Folha de S.Paulo, O Globo, Estadão, Valor Econômico y Gazeta do Povo.`,
  'cards.stf.mendonca': `⚠️ LA FISCALÍA PIDIÓ AVAL PARA INVESTIGARLO EL 04/Sep. Paulo Gonet pidió a Edson Fachin autorización para averiguar la sospecha de que interfirió en la Policía Federal, en el informe sobre los mensajes, según Estadão, O Globo y Gazeta do Povo. Sin acto individual nuevo el 05 ni el 06/Sep.`,
  'cards.stf.nexo': `⭐ EL CASO PRODUJO DOS ACTOS NUEVOS EL 05/Sep, Y NINGUNO PARTIÓ DE LOS DOS MINISTROS EN EL CENTRO DE LA CRISIS. Gilmar Mendes presentó una propuesta de enmienda al reglamento interno para sacar a policías y militares de los despachos de los ministros, entregada a Edson Fachin. Y Cristiano Zanin acudió al ${G('Supremo', 'stf')}, al Tribunal Superior Electoral y al Tribunal de Justicia de Paraná después de que Deltan Dallagnol adjuntara datos de su secreto fiscal a un registro de candidatura, pidiendo que se responsabilice a los implicados, según Folha de S.Paulo, O Globo, Estadão y Valor Econômico. 📌 Edson Fachin señaló el 05/Sep la intención de llevar la crisis al pleno, y esa decisión todavía no fue tomada. El 06/Sep, domingo, no hay acto institucional nuevo.`,
  'cards.stf.analise': `8,60% (vol USD 88 mil) en el contrato de salida de ministro del ${G('Supremo', 'stf')} por destitución antes de 2027, ${S6}, prácticamente quieto frente al 8,65% de la víspera. 📌 El contraste con la prensa es el registro del día: el 05/Sep el caso produjo dos actos institucionales nuevos, una propuesta de enmienda al reglamento interno y un pedido de responsabilización por quiebra de secreto fiscal, y el precio no se movió. En la serie registrada desde el 14/Abr el techo es 19,30%, marcado el 04/Sep, y el piso es 2,10%, del 08/Jun, así que el precio de ahora está 10,60pp por debajo de un techo de hace dos días, en un libro que acumula USD 88 mil.`,
})
