/** Mapa ES: polls-data, rodada de 06/Set/2026. Entra a Veritá nacional e os cinco livros confirmam. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S6 = 'lectura confirmada del 06/Sep, 13:53 BRT'
const S4 = 'lectura confirmada del 04/Sep'
const PISO = 'por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato'

construir('polls-data', 'es', {
  'polls[0].method': 'Telefónica (IVR)',
  'polls[0].note': `Veritá nacional divulgada el 06/Sep, campo del 01 al 04/Sep, registro BR-09426/2026 en el ${G('TSE', 'tse')}, con 3.804 entrevistas, margen de 2pp al 95% de confianza y financiación con recursos propios del instituto. ⭐ FLÁVIO BOLSONARO APARECE NUMÉRICAMENTE DELANTE EN LA PRIMERA VUELTA, 38,9% contra 38,4% de Lula. ⚠️ La distancia de 0,5 punto cabe entera dentro del margen de 2 puntos, así que lo que la encuesta mide es un EMPATE TÉCNICO y no una ventaja. Es la segunda nacional de la ventana que trae ese orden, después de la Gerp del 26/Ago, que dio 38% a 37%. ⭐ Y AUGUSTO CURY VA DE 2,2% A 12,2% ENTRE LAS DOS RONDAS DE LA CASA QUE EL PANEL GUARDA, la del 21/Ago y esta, una variación de 10 puntos, con Pablo Marçal haciendo el camino inverso, de 5,2% a 1,4%. ⚠️ ESTE LEVANTAMIENTO NO TRAE ESCENARIO DE ${G('SEGUNDA VUELTA', 'segundo-turno')}, y la lectura más reciente de ese par sigue siendo la Datafolha del 03/Sep. 🏷️ La suma de las líneas de la primera vuelta cierra en 100,0% con blancos, nulos e indecisos, lo que es coherente. ⚠️ La prensa publica la muestra como 3.804 y el registro en el TSE trae 3.840, y el panel usa el número publicado con el registrado declarado al lado. ⚠️ Veritá tiene confiabilidad 2 en la regla de la casa, la más baja entre los institutos de la ventana, y no es dato que se lea solo: las demás nacionales de la ventana siguen dando a Lula delante por márgenes de 3 a 9,7 puntos. 📌 El método declarado al TSE es entrevista por unidad automatizada de respuesta audible en teléfonos móviles, con transcripción por inteligencia artificial, y no entrevista presencial.`,
  'polls[0].source': `Veritá, registro BR-09426/2026 en el TSE, difundida por CNN Brasil y Terra Brasil Notícias el 06/Sep y agregada en la tabla de Wikipedia, que registra el mismo campo y los mismos porcentajes. El sitio del propio instituto no había publicado la ronda en el momento de la verificación.`,
  'polymarketComparison.note': `Precios de Polymarket con el libro presidencial en USD 144,11M, ${S6} (16:53 UTC). ⭐ EN ESTA RONDA LOS CINCO LIBROS CONFIRMARON en las dos lecturas independientes, y el de ganador vuelve a recibir precio nuevo. ⭐ Y LA ENCUESTA Y EL PRECIO SE MOVIERON EN DIRECCIONES OPUESTAS: la Veritá del 06/Sep pone a Flávio Bolsonaro en 38,9% contra 38,4% de Lula en la ${G('primera vuelta', 'primeiro-turno')}, distancia dentro del margen de 2 puntos, mientras el contrato de ganador abrió la brecha de 15,35pp a 16,80pp. Son magnitudes distintas, intención de voto declarada y probabilidad de ganar, y no se restan. 📌 Siguen sin precio nuevo los nombres por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura: Ronaldo Caiado, Romeu Zema, Pablo Marçal, Jair Bolsonaro, Michelle Bolsonaro, Tarcisio de Freitas y Fernando Haddad.`,
  'polymarketComparison.sources': `Precios de Polymarket vía el proxy AFOS, y el panel solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20pp. La confirmación se hace contrato a contrato, y el 06/Sep los cinco libros confirmaron en la lectura de las 13:53 BRT. Encuestas registradas en el TSE y divulgadas por los institutos, con reportaje de CNN Brasil, Terra Brasil Notícias, Poder360, Gazeta do Povo, Exame, UOL, CartaCapital, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, VEJA, BBC y Jornal de Brasília. El calendario de encuestas en campo y de divulgación prevista sale del registro oficial del TSE. Superlativo de serie verificado en el respaldo de Neon, en backup/neon/marketPrice, que guarda el registro completo desde el 14/Abr.`,

  'polymarketComparison.candidates[0].polymarket': '56,50%',
  'polymarketComparison.candidates[0].pesquisaRange': '38,4%',
  'polymarketComparison.candidates[0].tendenciaPesquisa': `La Veritá del 06/Sep (BR-09426/2026, campo del 01 al 04/Sep, n=3.804, margen de 2pp) lo mide en 38,4% en la ${G('primera vuelta', 'primeiro-turno')}, detrás de Flávio Bolsonaro por 0,5 punto. ⚠️ LA DISTANCIA CABE DENTRO DEL MARGEN, así que la encuesta mide un empate técnico. El 21/Ago la misma casa le daba 39,3% contra 39,1%. El levantamiento no trae escenario de ${G('segunda vuelta', 'segundo-turno')}, y la lectura más reciente de ese par sigue siendo la Datafolha del 03/Sep, que lo da ganando los cuatro pares probados.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `56,50% (vol USD 9,83M) en el contrato de ganador, ${S6}, una subida de 1,00pp frente a la ${S4}. ⭐ LA BRECHA HACIA EL SEGUNDO SE ABRIÓ DE 15,35pp A 16,80pp EL MISMO DÍA EN QUE LA ENCUESTA LA CERRÓ. En el contrato de segundo lugar de la primera vuelta subió 2,55pp hasta 7,90% (vol USD 474 mil). En la serie registrada desde el 14/Abr su contrato va de 34,50% a 67,50%, y el 56,50% de hoy está dentro de ese rango.`,

  'polymarketComparison.candidates[1].polymarket': '39,70%',
  'polymarketComparison.candidates[1].pesquisaRange': '38,9%',
  'polymarketComparison.candidates[1].tendenciaPesquisa': `⭐ LA VERITÁ DEL 06/Sep LO PONE NUMÉRICAMENTE DELANTE EN LA ${G('PRIMERA VUELTA', 'primeiro-turno')}, 38,9% contra 38,4%, y es la segunda nacional de la ventana en hacerlo, después de la Gerp del 26/Ago (38% a 37%). ⚠️ Los 0,5 punto están dentro del margen de 2 puntos, así que es empate técnico. Dentro de la propia Veritá el signo se invirtió desde el 21/Ago, cuando la casa daba 39,3% a Lula contra 39,1% de él. Veritá tiene confiabilidad 2 en la regla de la casa.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `39,70% (vol USD 9,74M) en el contrato de ganador, ${S6}, una caída de 0,45pp frente a la ${S4}. ⚠️ EL PRECIO SE MOVIÓ CONTRA LA ENCUESTA el mismo día. En el contrato de segundo lugar de la primera vuelta sigue en 89,50% (vol USD 612 mil), sin variación, y solo un punto de toda la serie estuvo alguna vez por encima de eso, el 90,50% del 21/Ago.`,

  'polymarketComparison.candidates[2].polymarket': '1,15%',
  'polymarketComparison.candidates[2].pesquisaRange': '12,2%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': `⭐ LA VERITÁ DEL 06/Sep LO MIDE EN 12,2% EN LA ${G('PRIMERA VUELTA', 'primeiro-turno')}, frente a 2,2% en la ronda de la propia casa del 21/Ago. Es el tercero del levantamiento, con holgura sobre el cuarto, que tiene 3,7%. La dispersión entre casas de la ventana sigue amplia: la Datafolha del 03/Sep lo dejaba en 7% y 8%.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,15% (vol USD 4,16M) en el contrato de GANADOR, ${S6}, una caída de 0,80pp. ⭐ En el contrato de TERCER LUGAR de la primera vuelta, que es otro mercado, subió 4,25pp hasta 56,20% (vol USD 126 mil), revirtiendo dos caídas seguidas. 📌 Sus dos contratos se movieron en direcciones opuestas: el mercado lo consolida como tercer colocado de la primera vuelta y no como candidato a ganar la elección.`,

  'polymarketComparison.candidates[3].polymarket': '1,60%',
  'polymarketComparison.candidates[3].pesquisaRange': '3,7%',
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La Veritá del 06/Sep lo mide en 3,7% en la ${G('primera vuelta', 'primeiro-turno')}, delante de Ronaldo Caiado (1,9%) y de Pablo Marçal (1,4%). ⚠️ LA DISPERSIÓN ENTRE CASAS EN ESTA VENTANA VA DE 3% A 7,6%, y el 3,7% queda en la parte baja de ella.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,60% (vol USD 12,70M) en el contrato de ganador, ${S6}, una caída de 0,25pp. En el contrato de tercer lugar de la primera vuelta subió 1,50pp hasta 26,00% (vol USD 279 mil), tercera subida seguida. 📌 Entre los cuatro nombres por encima de 1% en el contrato de ganador, es el de mayor volumen acumulado, por encima del líder y del segundo colocado, en un contrato con precio por debajo de 2%.`,

  'polymarketComparison.candidates[4].pesquisaRange': '1,9%',
  'polymarketComparison.candidates[4].tendenciaPesquisa': `La Veritá del 06/Sep lo pone en 1,9% en la ${G('primera vuelta', 'primeiro-turno')}, por debajo del 4% que la Datafolha medía el 03/Sep. El levantamiento no trae escenario de ${G('segunda vuelta', 'segundo-turno')}, así que la lectura más reciente del par contra él sigue siendo la Datafolha, de 46% a 41%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,15% (vol USD 7,16M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la primera vuelta, que es otro mercado, subió 0,50pp y volvió a 10,00% (vol USD 114 mil), ${S6}.`,

  'polymarketComparison.candidates[5].pesquisaRange': '1,4%',
  'polymarketComparison.candidates[5].tendenciaPesquisa': `La Veritá del 06/Sep lo mide en 1,4% en la ${G('primera vuelta', 'primeiro-turno')}. ⚠️ DENTRO DE LA PROPIA CASA CAYÓ DE 5,2% A 1,4% DESDE EL 21/Ago, y la Datafolha del 03/Sep lo medía en 2%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,73M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la primera vuelta está en 2,25% (vol USD 47 mil), ${S6}.`,

  'polymarketComparison.candidates[6].pesquisaRange': '0,3%',
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La Veritá del 06/Sep lo mide en 0,3% en la ${G('primera vuelta', 'primeiro-turno')}, por debajo del 2% que la Datafolha medía el 03/Sep. El levantamiento no trae escenario de ${G('segunda vuelta', 'segundo-turno')}, así que la lectura más reciente del par contra él sigue siendo la Datafolha, de 48% a 39%.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,15% (vol USD 6,56M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la primera vuelta subió 0,15pp hasta 0,85% (vol USD 49 mil), ${S6}.`,

  'polymarketComparison.candidates[7].tendenciaPesquisa': 'No es probado como candidato presidencial en las nacionales de la ventana, y la Veritá del 06/Sep tampoco lo prueba.',
  'polymarketComparison.candidates[8].tendenciaPesquisa': 'No es probado como candidato presidencial en las nacionales de la ventana, y la Veritá del 06/Sep tampoco lo prueba.',
})
