/** Mapa EN: analysis-criteriosa, rodada de 06/Set/2026. Pesquisa e preço em direções opostas. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S6 = 'confirmed reading of 06/Sep, 13:53 BRT'
const S4 = 'confirmed reading of 04/Sep'
const PISO = 'below the 0.5% floor of the double reading, and this round publishes no new price for him in that book'

construir('analysis-criteriosa', 'en', {
  subtitle: `Crossing of 6 September 2026, ${S6} (16:53 UTC) across the five books, with the presidential one at USD 144.11M. Most recent national poll: Veritá of 06/Sep, registration BR-09426/2026 at the TSE, fieldwork from 01 to 04/Sep. In this round all five books confirmed across the two readings.`,

  // ── Lula
  'candidates[0].header': `PRICE: 56.50% (vol USD 9.83M accumulated) in the winner contract, ${S6}, a rise of 1.00pp against the ${S4}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he rose 2.55pp to 7.90% (vol USD 474 thousand). POLL: Veritá of 06/Sep (BR-09426/2026, fieldwork 01 to 04/Sep, n=3,804, margin of 2pp) measures him at 38.4% in the first round, behind Flávio Bolsonaro by 0.5 point. The survey carries no ${G('runoff', 'segundo-turno')} scenario.`,
  'candidates[0].fortes[0]': 'He rose 1.00pp in the winner contract and widened the gap to the runner-up, which goes from 15.35pp to 16.80pp since the confirmed reading of 04/Sep.',
  'candidates[0].fortes[1]': '⭐ THE PRICE WIDENED THE GAP ON THE VERY DAY THE POLL CLOSED IT, and the two measurements rank the race in opposite ways.',
  'candidates[0].fortes[2]': "In the series recorded since 14/Apr his contract runs from 34.50% to 67.50%, and today's 56.50% sits inside that range, 12.00pp below the high of 16/Aug.",
  'candidates[0].fortes[3]': 'The most recent runoff reading is still Datafolha of 03/Sep, which has him beating the four pairings it tested, and the Veritá poll of today tested none.',
  'candidates[0].fortes[4]': 'Accumulated volume in his contract reached USD 9.83M, and the presidential book as a whole stands at USD 144.11M.',
  'candidates[0].fracos[0]': '⚠️ VERITÁ OF 06/Sep PUTS HIM BEHIND FOR THE FIRST TIME IN A ROUND BY THIS HOUSE: on 21/Aug the same Veritá gave him 39.3% against 39.1%, and now it is 38.4% against 38.9%.',
  'candidates[0].fracos[1]': 'It is the second national poll of the window to place Flávio Bolsonaro numerically ahead in the first round, after Gerp of 26/Aug, which gave 38% to 37%.',
  'candidates[0].fracos[2]': 'The distance of 0.5 point sits inside the margin of 2 points declared by Veritá, so the poll measures a statistical tie and not a lead for his opponent.',
  'candidates[0].fracos[3]': 'Veritá has a reliability of 2 on the house scale, the lowest among the institutes in the window, and it is not data to be read on its own.',
  'candidates[0].fracos[4]': 'Government disapproval in the Datafolha of 03/Sep is 51% against 45% approval, and the Veritá poll of today released no government rating.',
  'candidates[0].analise': `6 September is the day on which the two measurements on this page point in opposite directions, and that is what it records. The winner contract rose 1.00pp to 56.50% (vol USD 9.83M) and widened the gap to the runner-up from 15.35pp to 16.80pp. On the same day, Veritá released the first national poll after two days without any and measured 38.4% for him against 38.9% for his opponent, a distance of 0.5 point inside a margin of 2 points. 📌 They are different quantities: the poll measures declared voting intention in the ${G('first round', 'primeiro-turno')} and the contract measures the probability of winning the election, and they do not subtract from one another. The AFOS does not arbitrate which is right; it records that today they disagree on the ranking and that the price moved without the poll following it.`,

  // ── Flávio Bolsonaro
  'candidates[1].header': `PRICE: 39.70% (vol USD 9.74M accumulated) in the winner contract, ${S6}, a fall of 0.45pp against the ${S4}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he is still at 89.50% (vol USD 612 thousand), unchanged. POLL: Veritá of 06/Sep (BR-09426/2026, fieldwork 01 to 04/Sep, n=3,804, margin of 2pp) puts him at 38.9% in the first round, ahead of Lula by 0.5 point and inside the margin.`,
  'candidates[1].fortes[0]': '⭐ VERITÁ OF 06/Sep PUTS HIM NUMERICALLY AHEAD IN THE FIRST ROUND, 38.9% against 38.4%, and it is the second national poll of the window to do so, after Gerp of 26/Aug.',
  'candidates[1].fortes[1]': 'Inside Veritá itself the sign flipped: on 21/Aug the house gave 39.3% to Lula against 39.1% for him, and now the order is reversed.',
  'candidates[1].fortes[2]': 'He is still at 89.50% in the first-round runner-up contract (vol USD 612 thousand), and only one point in the whole series has ever sat above that, the 90.50% of 21/Aug.',
  'candidates[1].fortes[3]': 'Accumulated volume in his winner contract stands at USD 9.74M, all but level with the leader, who is at USD 9.83M.',
  'candidates[1].fortes[4]': 'On 05/Sep he visited a man convicted over the coup plot in Paraná and again called for Alexandre de Moraes to step aside, according to O Globo and Folha de S.Paulo.',
  'candidates[1].fracos[0]': '⚠️ THE PRICE MOVED AGAINST THE POLL: he gave up 0.45pp in the winner contract on the same day Veritá placed him ahead in the first round.',
  'candidates[1].fracos[1]': 'The gap to the leader in the winner contract widened from 15.35pp to 16.80pp since the confirmed reading of 04/Sep.',
  'candidates[1].fracos[2]': 'The 0.5 point advantage in Veritá sits inside the margin of 2 points, so what the poll measures is a statistical tie and not a lead.',
  'candidates[1].fracos[3]': 'Veritá has a reliability of 2 on the house scale, and the other national polls of the window still put the leader ahead by margins of 3 to 9.7 points.',
  'candidates[1].fracos[4]': "Today's Veritá tested no runoff scenario, so the most recent reading of that pairing is still Datafolha of 03/Sep, which has him 2 points behind, 44% against 46%.",
  'candidates[1].analise': `His day has one strong number and a price that did not follow it. Veritá of 06/Sep, with fieldwork from 01 to 04/Sep and 3,804 interviews, measures him at 38.9% against 38.4% for the leader, and it is the second national poll of the window to place him numerically ahead in the ${G('first round', 'primeiro-turno')}. ⚠️ The distance of 0.5 point fits entirely inside the declared margin of 2 points, so the correct reading is a statistical tie. In the market the move was the opposite: the winner contract gave up 0.45pp to 39.70% (vol USD 9.74M), with the gap to the leader widening from 15.35pp to 16.80pp. 📌 In the first-round runner-up contract he is still at 89.50%, unchanged in this reading, and that is where the market concentrates its conviction about him.`,

  // ── Augusto Cury
  'candidates[2].header': `PRICE: 1.15% (vol USD 4.16M accumulated) in the winner contract, ${S6}, a fall of 0.80pp against the ${S4}. ⭐ In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 4.25pp to 56.20% (vol USD 126 thousand). POLL: Veritá of 06/Sep measures him at 12.2% in the first round, against 2.2% in the same house's round of 21/Aug.`,
  'candidates[2].fortes[0]': "⭐ HE IS THE ONLY NAME THAT RISES IN BOTH MEASUREMENTS THIS ROUND: up 4.25pp in the first-round third-place contract, and 12.2% in Veritá against 2.2% in the same house's round of 21/Aug. In the poll, every other name gave ground between the two rounds of that house.",
  'candidates[2].fortes[1]': 'The 56.20% in the third-place contract reverses two consecutive falls and puts him back above the level of 03/Sep.',
  'candidates[2].fortes[2]': 'He remains the clear leader of that market, with 56.20% against 26.00% for the runner-up, a distance of 30.20pp.',
  'candidates[2].fortes[3]': 'Veritá places him third in the first round with a comfortable margin over the fourth, who is Renan Santos with 3.7%.',
  'candidates[2].fracos[0]': '⚠️ IN THE WINNER CONTRACT HE GAVE UP 0.80pp TO 1.15%, the lowest value among the four names above 1% in that book.',
  'candidates[2].fracos[1]': 'His two contracts moved in opposite directions in this reading: up 4.25pp in the third-place one and down 0.80pp in the winner one.',
  'candidates[2].fracos[2]': 'The market treats him as a candidate for the leading pack of the first round and not as a candidate to win the election, and the USD 4.16M of volume sits alongside a price below 1.5%.',
  'candidates[2].fracos[3]': 'In the first-round runner-up contract he stands at 0.95% (vol USD 143 thousand), below 1%.',
  'candidates[2].analise': `He is the only name on the panel that rises in both measurements at once, and the distance between them is what matters. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 4.25pp to 56.20% (vol USD 126 thousand), reversing two consecutive falls. In Veritá of 06/Sep he appears with 12.2% in the first round, against 2.2% in the same house's round on 21/Aug. ⚠️ And in the winner contract the move is the reverse: he gave up 0.80pp to 1.15% (vol USD 4.16M). 📌 The three readings are coherent with one another if each is read for what it measures: the market sees him consolidated as the third-placed finisher of the first round and does not see him as a candidate to win the election, and the poll measures exactly the first of those two things.`,

  // ── Renan Santos
  'candidates[3].header': `PRICE: 1.60% (vol USD 12.70M accumulated) in the winner contract, ${S6}, a fall of 0.25pp against the ${S4}. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.50pp to 26.00% (vol USD 279 thousand). POLL: Veritá of 06/Sep measures him at 3.7% in the first round.`,
  'candidates[3].fortes[0]': 'He rose 1.50pp in the first-round third-place contract to 26.00%, a third consecutive gain in that market.',
  'candidates[3].fortes[1]': 'His is the largest accumulated volume among the four names above 1% in the presidential book, at USD 12.70M, above the leader and the runner-up.',
  'candidates[3].fortes[2]': 'Veritá of 06/Sep measures him at 3.7%, ahead of Ronaldo Caiado, who is at 1.9%, and of Pablo Marçal, who is at 1.4%.',
  'candidates[3].fracos[0]': 'He gave up 0.25pp in the winner contract to 1.60%, below 2% for a third day.',
  'candidates[3].fracos[1]': 'His distance to the leader of the third-place contract is still wide, 26.00% against 56.20%, or 30.20pp.',
  'candidates[3].fracos[2]': "In the series recorded since 14/Apr his winner contract has reached 17.90%, on 09/Jun, and today's 1.60% sits 15.90pp below that high.",
  'candidates[3].fracos[3]': "Veritá's 3.7% sits at the bottom of the window's spread, which runs from 3% to 7.6% between houses.",
  'candidates[3].analise': `His pattern holds and has become sharper. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 1.50pp to 26.00% (vol USD 279 thousand), a third consecutive gain, while in the winner one he gave up 0.25pp to 1.60% (vol USD 12.70M). 📌 His contract is still the one with the largest accumulated volume among the four names above 1%, above the leader and the runner-up, at a price below 2%. Accumulated volume is money that has already passed through the contract since it opened and says nothing about which way it went. Veritá of 06/Sep measures him at 3.7% in the first round, inside the 3% to 7.6% band in which the houses of the window place him.`,

  // ── Caiado / Haddad / Zema
  'candidates[4].header': `PRICE: all three are still below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for them in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract, Ronaldo Caiado rose 0.50pp to 10.00% (vol USD 114 thousand) and Romeu Zema rose 0.15pp to 0.85% (vol USD 49 thousand), ${S6}. POLL: Veritá of 06/Sep puts Caiado at 1.9% and Zema at 0.3% in the first round.`,
  'candidates[4].subtitle': `Back of the pack in the ${S6} (16:53 UTC). ⚠️ VERITÁ OF 06/Sep MEASURES BOTH BELOW WHAT THE OTHER HOUSES OF THE WINDOW HAD BEEN MEASURING, with Ronaldo Caiado at 1.9% and Romeu Zema at 0.3% in the first round, against 4% and 2% in Datafolha of 03/Sep. And it tested no ${G('runoff', 'segundo-turno')} scenario. The pairing against Ronaldo Caiado still has four different readings in the same week, all with overlapping fieldwork: 45% to 43% in his favour in Real Time Big Data of 01/Sep, 42% to 37% against him in Genial/Quaest of 02/Sep, 44% to 42% against him in PoderData of 03/Sep and 46% to 41% against him in Datafolha of the same day.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0.15% (vol USD 7.16M) in the WINNER contract, ${PISO}. In the THIRD-PLACE contract of the first round, which is a different market, he rose 0.50pp back to 10.00%, in a book of USD 114 thousand, ${S6} (16:53 UTC).`,
  'candidates[4].caiado.fortes': 'He rose 0.50pp in the first-round third-place contract and is back at 10.00%, third in that market, behind only Augusto Cury and Renan Santos. The runoff pairing against him in Datafolha of 03/Sep is 5 points, 46% to 41%, narrower than Romeu Zema’s, which is 9 points. He took the Supreme Court crisis and the Master case to the free electoral broadcast, according to Valor Econômico.',
  'candidates[4].caiado.fracos': '⚠️ VERITÁ OF 06/Sep MEASURES HIM AT 1.9% IN THE FIRST ROUND, below the 4% of Datafolha of 03/Sep and the 3.3% Veritá itself measured on 21/Aug. In the winner contract he is still below the 0.5% floor of the double reading. And the runoff pairing in which he appears has already been measured by four houses in the same week, with four different results, and Veritá did not test it.',
  'candidates[4].haddad.fortes': 'He is not tested as a presidential candidate in the national polls of the window, and Veritá of 06/Sep does not test him either, so there is no ballot reading to cross against the price.',
  'candidates[4].zema.label': `ZEMA (Novo), 0.15% (vol USD 6.56M) in the WINNER contract, ${PISO}. In the THIRD-PLACE contract of the first round, which is a different market, he rose 0.15pp to 0.85%, in a book of USD 49 thousand, ${S6} (16:53 UTC).`,
  'candidates[4].zema.fortes': 'He rose 0.15pp in the first-round third-place contract to 0.85%. In PoderData of 03/Sep he is 2 points from the leader in the runoff, 44% to 42%, the narrowest margin against him in any national poll of the window.',
  'candidates[4].zema.fracos': '⚠️ VERITÁ OF 06/Sep MEASURES HIM AT 0.3% IN THE FIRST ROUND, below the 2% of Datafolha of 03/Sep and the 1.3% Veritá itself measured on 21/Aug. The runoff pairing against him is the one with the widest spread between houses in the window, with the four houses of the week measuring 3, 11, 2 and 9 points, and Veritá did not test it.',
  'candidates[4].fortes[0]': 'Ronaldo Caiado rose 0.50pp in the first-round third-place contract and is back at 10.00% (vol USD 114 thousand), third in that market.',
  'candidates[4].fortes[1]': 'Romeu Zema rose 0.15pp in the third-place contract to 0.85% (vol USD 49 thousand).',
  'candidates[4].fortes[2]': 'The most recent runoff reading against Caiado is still Datafolha of 03/Sep, at 5 points, 46% to 41%, narrower than Zema’s, which is 9 points.',
  'candidates[4].fracos[0]': '⚠️ VERITÁ OF 06/Sep GIVES 1.9% TO CAIADO AND 0.3% TO ZEMA, and both come in below what the other houses of the window had been measuring, which was 4% and 2% in Datafolha of 03/Sep.',
  'candidates[4].fracos[1]': 'In the winner contract Caiado is at 0.15% and Zema at 0.15%, below the 0.5% floor of the double reading, and this round publishes no new price for them there.',
  'candidates[4].fracos[3]': 'Veritá tested no runoff scenario, so there is no new reading of the pairings against them.',
  'candidates[4].analise': `The two who moved on 06/Sep moved in the third-place market of the ${G('first round', 'primeiro-turno')}, which is not the winner one. Ronaldo Caiado rose 0.50pp back to 10.00% (vol USD 114 thousand) and Romeu Zema rose 0.15pp to 0.85% (vol USD 49 thousand). ⚠️ In Veritá of 06/Sep both come in below what the other houses of the window had been measuring, with 1.9% and 0.3% against 4% and 2% in Datafolha of 03/Sep, and comparison between different houses carries different method. Fernando Haddad is not a presidential candidate and is running for governor of São Paulo. In the winner contract all three are still below the 0.5% floor of the double reading.`,

  // ── quadro comparativo
  'quadroComparativo[0].p': 'Veritá of 06/Sep (BR-09426/2026, fieldwork 01 to 04/Sep, n=3,804, margin of 2pp) measures him at 38.4% in the first round, behind Flávio Bolsonaro by 0.5 point, inside the margin. On 21/Aug the same house gave him 39.3% against 39.1%. The survey carries no runoff scenario, and the most recent reading of that pairing is still Datafolha of 03/Sep, which has him beating the four pairings tested.',
  'quadroComparativo[0].m': `56.50% (vol USD 9.83M) in the winner contract, ${S6}, a rise of 1.00pp against the ${S4}. In the first-round runner-up contract he rose 2.55pp to 7.90% (vol USD 474 thousand).`,
  'quadroComparativo[0].t': 'rose in the winner contract and widened the gap to 16.80pp, on the very day the poll closed it',
  'quadroComparativo[0].s': 'On 05/Sep he campaigned in inland São Paulo, asked for votes for Fernando Haddad and did not address the Supreme Court crisis, according to O Globo and CartaCapital.',
  'quadroComparativo[1].p': '⭐ Veritá of 06/Sep puts him at 38.9% in the first round, numerically ahead of Lula by 0.5 point, inside the margin of 2 points. It is the second national poll of the window to place him ahead, after Gerp of 26/Aug, which gave 38% to 37%. Veritá has a reliability of 2 on the house scale.',
  'quadroComparativo[1].m': `39.70% (vol USD 9.74M) in the winner contract, ${S6}, a fall of 0.45pp against the ${S4}. In the first-round runner-up contract he is still at 89.50% (vol USD 612 thousand), unchanged.`,
  'quadroComparativo[1].t': 'ahead in the poll and falling in the price, on the same day',
  'quadroComparativo[1].s': 'He interrupted his campaign on 05/Sep to visit a man convicted over the coup plot in Paraná and again called for Alexandre de Moraes to step aside, according to O Globo and Folha de S.Paulo.',
  'quadroComparativo[2].p': "⭐ Veritá of 06/Sep measures him at 12.2% in the first round, against 2.2% in the same house's round on 21/Aug. He is third in the survey, comfortably ahead of the fourth, who has 3.7%.",
  'quadroComparativo[2].m': `1.15% (vol USD 4.16M) in the winner contract, ${S6}, a fall of 0.80pp. ⭐ In the first-round third-place contract he rose 4.25pp to 56.20% (vol USD 126 thousand), reversing two consecutive falls.`,
  'quadroComparativo[2].t': 'rises in both universes as the third-placed finisher and gives ground in the contract on winning the election',
  'quadroComparativo[2].s': 'No new individual act on 06/Sep. He is tested in the runoff of the polls Nexus and AtlasIntel have scheduled for 08 and 10/Sep.',
  'quadroComparativo[3].p': "Veritá of 06/Sep measures him at 3.7% in the first round, ahead of Ronaldo Caiado (1.9%) and Pablo Marçal (1.4%). The spread between houses in the window is still wide, from 3% to 7.6%.",
  'quadroComparativo[3].m': `1.60% (vol USD 12.70M) in the winner contract, ${S6}, a fall of 0.25pp. In the first-round third-place contract he rose 1.50pp to 26.00% (vol USD 279 thousand), a third consecutive gain.`,
  'quadroComparativo[3].t': 'third consecutive gain in the third-place contract, with the winner one giving ground',
  'quadroComparativo[3].s': 'He remains the author of the impeachment request against two Supreme Court justices. No new individual act on 06/Sep.',
  'quadroComparativo[4].p': 'Veritá of 06/Sep puts him at 1.9% in the first round, below the 4% Datafolha measured on 03/Sep. The survey carries no runoff scenario.',
  'quadroComparativo[4].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the first-round third-place contract he rose 0.50pp to 10.00% (vol USD 114 thousand), ${S6}.`,
  'quadroComparativo[4].t': 'rose 0.50pp in the third-place contract and fell in the poll',
  'quadroComparativo[4].s': 'He took the Supreme Court crisis and the Master case to the free electoral broadcast, according to Valor Econômico. No other individual act on 06/Sep.',
  'quadroComparativo[5].p': 'Veritá of 06/Sep measures him at 1.4% in the first round, below the 5.2% the same house measured on 21/Aug and the 2% of Datafolha of 03/Sep.',
  'quadroComparativo[5].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the first-round third-place contract he stands at 2.25% (vol USD 47 thousand), ${S6}.`,
  'quadroComparativo[5].t': 'gives ground in the poll inside the house itself, from 5.2% to 1.4% since 21/Aug',
  'quadroComparativo[5].s': 'No new individual act on 06/Sep.',

  cruzamento: `6 September is the day on which the two measurements on this page point in opposite directions, and recording that is its purpose. ⭐ THE NATIONAL POLLING DROUGHT ENDED ON THE THIRD DAY: Veritá released a national poll with fieldwork from 01 to 04/Sep, registration BR-09426/2026 at the ${G('TSE', 'tse')}, 3,804 interviews and a margin of 2 points, and it puts Flávio Bolsonaro at 38.9% against 38.4% for Lula in the ${G('first round', 'primeiro-turno')}. ⚠️ The distance of 0.5 point fits entirely inside the declared margin, so what the poll measures is a statistical tie, not a lead. It is the second national poll of the window to bring the runner-up numerically ahead, after Gerp of 26/Aug, which gave 38% to 37%, and Veritá has a reliability of 2 on the house scale. ⭐ ON THE SAME DAY THE MARKET MOVED THE OTHER WAY: with all five books confirmed across the two readings, the winner contract gave 56.50% to Lula and 39.70% to Flávio Bolsonaro, and the gap went from 15.35pp on the confirmed reading of 04/Sep to 16.80pp. 📌 The two quantities do not subtract from one another. The poll measures declared voting intention in the first round and the contract measures the probability of winning the election, and a candidate can lead the first and not the second. The AFOS does not say which of the two is right. ⭐ THE NAME THAT RISES IN BOTH UNIVERSES IS AUGUSTO CURY: Veritá measures him at 12.2%, against 2.2% in the same house's round on 21/Aug, and the first-round third-place contract rose 4.25pp to 56.20%. In the winner contract, however, he gave up 0.80pp to 1.15%, which is coherent: the market is consolidating him as the third-placed finisher of the first round and not as a candidate to win the election. 📌 At the Supreme Court the record is one of decoupling. On 05/Sep the case produced two new institutional acts, a proposed amendment to the internal rules filed by Gilmar Mendes and a request for accountability made by Cristiano Zanin over a breach of tax secrecy, and the contract on impeachment before 2027 stayed all but still, at 8.60% against 8.65% the day before. On 06/Sep, a Sunday, there is no new institutional act. The TSE calendar carries another ten national polls with releases scheduled between 07 and 11/Sep, among them Quaest, Nexus, AtlasIntel and Datafolha, and there are 28 days to the first round.`,
})
