/** Mapa ES: analysis-criteriosa, rodada de 07/Set/2026. Segundo dia de divergência, e o 2º turno da Veritá inverte o par. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S7 = 'lectura confirmada del 07/Sep, 13:02 BRT'
const S6 = 'lectura confirmada del 06/Sep'
const PISO = 'por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 7 de septiembre de 2026, ${S7} (16:02 UTC), con el presidencial en USD 144,60M. En esta ronda dos de los cinco libros recibieron precio nuevo: el de ganador y el de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}. Encuesta nacional más reciente: Veritá del 06/Sep, registro BR-09426/2026 en el ${G('TSE', 'tse')}, cuyo escenario de ${G('segunda vuelta', 'segundo-turno')} salió después de la ronda de ayer e invierte el par.`,

  // ── Lula
  'candidates[0].header': `PRECIO: 57,50% (vol USD 9,92M acumulado) en el contrato de ganador, ${S7}, un alza de 1,00pp frente a la ${S6}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} no hay lectura nueva el 07/Sep. ENCUESTA: 38,4% en la primera vuelta de Veritá del 06/Sep, detrás por 0,5 punto dentro del margen, y 43,1% frente a 48,5% en la ${G('segunda vuelta', 'segundo-turno')} de la misma ronda.`,
  'candidates[0].fortes[0]': 'Subió 1,00pp en el contrato de ganador y abrió la distancia sobre el segundo, que pasa de 16,80pp a 18,05pp desde la lectura confirmada del 06/Sep. Es la segunda rueda seguida de apertura.',
  'candidates[0].fortes[1]': 'Su contrato subió en los dos días en que la encuesta de Veritá fue contra él, primero empatando la primera vuelta y ahora entregando la segunda vuelta a su adversario.',
  'candidates[0].fortes[2]': 'En las otras dos encuestas nacionales de la ventana que prueban la segunda vuelta contra Flávio Bolsonaro sigue por delante: Datafolha del 03/Sep, 46% a 44%, y Quaest del 02/Sep, 42% a 41%.',
  'candidates[0].fracos[0]': 'Veritá del 06/Sep es la primera encuesta nacional de la ventana que le da derrota en la segunda vuelta, por 48,5% a 43,1%, una distancia de 5,4 puntos que no cabe en el margen de 2 puntos de la propia encuesta.',
  'candidates[0].fracos[1]': 'El rechazo medido en la misma ronda es de 35% para él frente a 25,8% para su adversario.',
  'candidates[0].fracos[2]': 'En la primera vuelta de la misma encuesta aparece detrás por 0,5 punto, lo que es empate técnico, pero dentro de la propia Veritá el signo cambió desde el 21/Ago, cuando la casa le daba 39,3% frente a 39,1%.',
  'candidates[0].analise': `El 7 de septiembre repite la divergencia del día anterior y la profundiza. El contrato de ganador subió 1,00pp hasta 57,50% (vol USD 9,92M) y la distancia sobre el segundo se abrió de 16,80pp a 18,05pp, segunda rueda seguida de apertura. En el mismo tramo, el escenario de ${G('segunda vuelta', 'segundo-turno')} de Veritá, que solo salió después de la ronda de ayer, lo coloca detrás por 48,5% a 43,1%. Las dos magnitudes no se restan, porque una es intención de voto declarada en un par y la otra es probabilidad implícita de ganar la elección, pero ordenan la disputa al revés y eso es lo que la página registra. Vale la salvedad de que Veritá tiene confiabilidad 2 en la regla de la casa, la más baja de la ventana, y que las otras dos encuestas nacionales que prueban el par van en sentido opuesto.`,

  // ── Flávio Bolsonaro
  'candidates[1].header': `PRECIO: 39,45% (vol USD 9,80M acumulado) en el contrato de ganador, ${S7}, una caída de 0,25pp frente a la ${S6}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} no hay lectura nueva el 07/Sep. ENCUESTA: 38,9% en la primera vuelta de Veritá del 06/Sep y 48,5% frente a 43,1% en la ${G('segunda vuelta', 'segundo-turno')} de la misma ronda.`,
  'candidates[1].fortes[0]': 'Veritá del 06/Sep es la primera encuesta nacional de la ventana que le entrega la segunda vuelta, por 48,5% a 43,1%, una distancia de 5,4 puntos que no cabe en el margen de 2 puntos.',
  'candidates[1].fortes[1]': 'La misma ronda lo pone numéricamente por delante en la primera vuelta, 38,9% frente a 38,4%, y mide rechazo de 25,8% frente a 35% de su adversario.',
  'candidates[1].fortes[2]': 'Dentro de la propia Veritá el signo cambió desde el 21/Ago, cuando la casa daba 39,3% a Lula frente a 39,1% de él.',
  'candidates[1].fracos[0]': 'El precio fue contra la encuesta por segundo día seguido: cedió 0,25pp en el contrato de ganador el día en que la encuesta le entregó la segunda vuelta.',
  'candidates[1].fracos[1]': 'Las otras dos encuestas nacionales de la ventana que prueban el par van en sentido opuesto: Datafolha del 03/Sep, 46% a 44% para Lula, y Quaest del 02/Sep, 42% a 41%, también para Lula.',
  'candidates[1].fracos[2]': 'Veritá tiene confiabilidad 2 en la regla de la casa, la más baja entre los institutos de la ventana.',
  'candidates[1].analise': `La ronda del 7 de septiembre le entrega el mejor resultado de encuesta de la ventana y el peor movimiento de precio del mismo tramo. El escenario de ${G('segunda vuelta', 'segundo-turno')} de Veritá, publicado después de la ronda de ayer, lo da ganando por 48,5% a 43,1%, y es la primera vez en toda la ventana que una encuesta nacional lo hace. En el contrato de ganador cedió 0,25pp y está en 39,45% (vol USD 9,80M), con la distancia sobre el líder abriéndose por segunda rueda. Es el segundo día seguido en que las dos mediciones se mueven en direcciones opuestas para él, y el registro es ese, sin arbitrar cuál de las dos tiene razón.`,

  // ── Augusto Cury
  'candidates[2].header': `PRECIO: 1,15% (vol USD 4,19M acumulado) en el contrato de GANADOR, ${S7}, sin variación. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} subió 2,35pp y está en 58,55% (vol USD 126 mil). ENCUESTA: 12,2% en la primera vuelta de Veritá del 06/Sep.`,
  'candidates[2].fortes[0]': 'Segunda alza seguida en el contrato de tercer lugar de la primera vuelta, que pasa de 56,20% a 58,55%, el mismo día en que Renan Santos cede 1,50pp en ese mismo libro.',
  'candidates[2].fortes[1]': 'Veritá del 06/Sep lo mide en 12,2% en la primera vuelta, frente a 2,2% en la ronda de la propia casa el 21/Ago.',
  'candidates[2].fortes[2]': 'Es el tercer colocado del levantamiento con holgura sobre el cuarto, que tiene 3,7%.',
  'candidates[2].fracos[0]': 'En el contrato de ganar la elección no se movió y sigue en 1,15%, es decir, el mercado lo consolida como tercer colocado de la primera vuelta y no como candidato a ganar.',
  'candidates[2].fracos[1]': 'La dispersión entre casas sigue amplia: Datafolha del 03/Sep lo dejaba en 7% y 8%, frente al 12,2% de Veritá.',
  'candidates[2].fracos[2]': 'El volumen del contrato de tercer lugar es de USD 126 mil, muy por debajo del libro de ganador, y el movimiento en un libro fino pide una lectura más cautelosa.',
  'candidates[2].analise': `Sus dos contratos siguen contando historias distintas, y la distancia entre ellas aumentó. En el libro de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,35pp y llegó a 58,55%, segunda alza seguida, mientras en el libro de ganador no se movió y permanece en 1,15%. La encuesta acompaña el primer movimiento y no el segundo: Veritá lo mide en 12,2%, seis veces lo que la misma casa medía el 21/Ago. En esta ronda es el nombre que más subió entre los que recibieron precio nuevo.`,

  // ── Renan Santos
  'candidates[3].header': `PRECIO: 1,55% (vol USD 12,76M acumulado) en el contrato de ganador, ${S7}, una caída de 0,05pp. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,50pp y está en 24,50% (vol USD 279 mil). ENCUESTA: 3,7% en la primera vuelta de Veritá del 06/Sep.`,
  'candidates[3].fortes[0]': 'Entre los cuatro nombres por encima de 1% en el contrato de ganador, es el de mayor volumen acumulado, USD 12,76M, por encima del líder y del segundo colocado.',
  'candidates[3].fortes[1]': 'Sigue como autor del pedido de destitución contra dos ministros del Supremo, tema que lo mantiene en el noticiero.',
  'candidates[3].fracos[0]': 'Cedió 1,50pp en el contrato de tercer lugar de la primera vuelta e interrumpió tres alzas seguidas, el mismo día en que Augusto Cury subió 2,35pp en ese mismo libro.',
  'candidates[3].fracos[1]': 'Veritá del 06/Sep lo mide en 3,7% en la primera vuelta, en la parte baja de una dispersión entre casas que va de 3% a 7,6%.',
  'candidates[3].fracos[2]': 'El contrato de ganador sigue con precio por debajo de 2% pese a que su volumen acumulado es el mayor entre los cuatro nombres por encima de 1%.',
  'candidates[3].analise': `La ronda invierte el movimiento de las tres anteriores en el libro de tercer lugar: cede 1,50pp hasta 24,50%, mientras Augusto Cury sube 2,35pp hasta 58,55%. Los dos se mueven en el mismo libro y en direcciones opuestas, lo que es coherente con una partición en la que la masa se desplaza entre nombres. En el contrato de ganador la variación es de 0,05pp, dentro del ruido del propio libro. Su volumen acumulado sigue siendo el mayor entre los cuatro nombres por encima de 1%, en un contrato con precio por debajo de 2%.`,

  // ── Caiado / Haddad / Zema
  'candidates[4].header': `PRECIO: los tres siguen por debajo del piso de 0,5% en el contrato de GANADOR, y esta ronda no publica precio nuevo para ellos en ese libro. En el de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, ${S7}: Ronaldo Caiado cedió 0,50pp y está en 9,50% (vol USD 115 mil) y Romeu Zema sigue en 0,85% (vol USD 51 mil). ENCUESTA: Caiado 1,9% y Zema 0,3% en la primera vuelta de Veritá del 06/Sep.`,
  'candidates[4].subtitle': `Pelotón de atrás en la ${S7} (16:02 UTC). ⚠️ VERITÁ DEL 06/Sep MIDE A CAIADO EN 1,9% Y A ZEMA EN 0,3% EN LA ${G('PRIMERA VUELTA', 'primeiro-turno')}, los dos por debajo de lo que Datafolha medía el 03/Sep, 4% y 2%. En el libro de tercer lugar de la primera vuelta, que recibió precio nuevo en esta ronda, los dos se movieron en direcciones distintas: Caiado cedió 0,50pp y Zema quedó parado.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0,15% (vol USD 7,23M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, cedió 0,50pp y está en 9,50%, en un libro de USD 115 mil, ${S7}.`,
  'candidates[4].caiado.fortes': 'Sigue como cuarto nombre del contrato de tercer lugar de la primera vuelta, detrás de Augusto Cury, Renan Santos y del propio Flávio Bolsonaro en ese libro. El par de segunda vuelta contra él en la Datafolha del 03/Sep es de 5 puntos, 46% a 41%, más estrecho que el de Romeu Zema, que es de 9 puntos.',
  'candidates[4].caiado.fracos': '⚠️ CEDE EN LOS DOS UNIVERSOS EN ESTA RONDA: 0,50pp en el contrato de tercer lugar de la primera vuelta y de 4% a 1,9% entre la Datafolha del 03/Sep y la Veritá del 06/Sep. En el contrato de ganador sigue por debajo del piso de 0,5%.',
  'candidates[4].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,56M) en el contrato de GANADOR, ${PISO}. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, sigue en 0,85% sin variación, en un libro de USD 51 mil, ${S7}.`,
  'candidates[4].zema.fortes': 'Tuvo el acto de mayor visibilidad entre los tres este lunes, en la avenida Paulista, con un panel contra un ministro del Supremo y defensa de una reforma judicial, según Gazeta do Povo, O Globo y Valor Econômico. En la PoderData del 03/Sep queda a 2 puntos del líder en la segunda vuelta, 44% a 42%, el margen más estrecho contra él en cualquier encuesta nacional de la ventana.',
  'candidates[4].zema.fracos': '⚠️ VERITÁ DEL 06/Sep LO MIDE EN 0,3% EN LA PRIMERA VUELTA, por debajo del 2% de la Datafolha del 03/Sep. Y el acto del 07/Sep no produjo movimiento en el libro donde tiene precio: en el contrato de tercer lugar de la primera vuelta quedó parado en 0,85%.',
  'candidates[4].analise': `Ninguno de los tres recibe precio nuevo en el contrato de ganador, porque los tres están por debajo del piso de 0,5% de la doble lectura. En el libro de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}, que sí recibió precio nuevo en esta ronda, Caiado cedió 0,50pp hasta 9,50% y Zema quedó parado en 0,85%. La encuesta de Veritá va en la misma dirección para Caiado, que cae de 4% en la Datafolha del 03/Sep a 1,9%. El 7 de septiembre le dio a Zema el acto de mayor visibilidad de los tres, en la Paulista, sin que eso produjera movimiento de precio en el libro donde tiene cotización.`,
  'candidates[4].fortes[0]': 'Ronaldo Caiado sigue como cuarto nombre del libro de tercer lugar de la primera vuelta, por delante de Pablo Marçal y de Romeu Zema.',
  'candidates[4].fortes[1]': 'Romeu Zema tuvo acto propio el 07/Sep en la avenida Paulista, con crítica al Supremo y defensa de una reforma judicial, según Valor Econômico, O Globo y Gazeta do Povo.',
  'candidates[4].fracos[0]': 'Caiado cedió 0,50pp en el libro de tercer lugar y Veritá del 06/Sep lo mide en 1,9%, por debajo del 4% de la Datafolha del 03/Sep.',
  'candidates[4].fracos[1]': 'Zema no se movió en el libro de tercer lugar y Veritá lo mide en 0,3%, por debajo del 2% de la Datafolha.',
  'candidates[4].fracos[2]': 'Fernando Haddad no es candidato a la Presidencia: disputa el gobierno de São Paulo, y su contrato presidencial está en 0,05%.',

  // ── Quadro comparativo
  'quadroComparativo[0].p': `Veritá del 06/Sep (BR-09426/2026, campo del 01 al 04/Sep, n=3.804, margen de 2pp) lo mide en 38,4% en la ${G('primera vuelta', 'primeiro-turno')}, detrás por 0,5 punto y dentro del margen. El escenario de ${G('segunda vuelta', 'segundo-turno')} de la misma ronda, que salió después, lo pone detrás por 48,5% a 43,1%. Datafolha del 03/Sep y Quaest del 02/Sep siguen dándole el par a él.`,
  'quadroComparativo[0].m': `57,50% (vol USD 9,92M) en el contrato de ganador, ${S7}, un alza de 1,00pp frente a la ${S6}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} no hay lectura nueva el 07/Sep.`,
  'quadroComparativo[0].t': 'subió por segunda rueda seguida y abrió la brecha hasta 18,05pp, en el mismo tramo en que la encuesta le dio derrota en la segunda vuelta',
  'quadroComparativo[0].s': 'Participó del desfile del 7 de Septiembre en Brasilia junto a Edson Fachin, Davi Alcolumbre y Hugo Motta, e hizo un pronunciamiento en cadena sobre soberanía, según Poder360, Valor Econômico y Estadão.',
  'quadroComparativo[1].p': `⭐ Veritá del 06/Sep lo pone por delante en los dos escenarios: 38,9% frente a 38,4% en la ${G('primera vuelta', 'primeiro-turno')}, dentro del margen, y 48,5% frente a 43,1% en la ${G('segunda vuelta', 'segundo-turno')}. Es la primera encuesta nacional de la ventana que le entrega la segunda vuelta.`,
  'quadroComparativo[1].m': `39,45% (vol USD 9,80M) en el contrato de ganador, ${S7}, una caída de 0,25pp frente a la ${S6}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} no hay lectura nueva el 07/Sep.`,
  'quadroComparativo[1].t': 'por delante en los dos escenarios de la encuesta y en caída en el precio, por segundo día seguido',
  'quadroComparativo[1].s': 'Faltó al desfile del 7 de Septiembre y fue a un culto junto a Tarcísio de Freitas, según Poder360 y O Globo. Michelle Bolsonaro no participó de su acto, según VEJA.',
  'quadroComparativo[2].p': 'Veritá del 06/Sep lo mide en 12,2% en la primera vuelta, frente a 2,2% en la ronda de la propia casa el 21/Ago. La Datafolha del 03/Sep lo dejaba en 7% y 8%.',
  'quadroComparativo[2].m': `1,15% (vol USD 4,19M) en el contrato de ganador, ${S7}, sin variación. ⭐ En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 2,35pp y está en 58,55% (vol USD 126 mil), segunda alza seguida.`,
  'quadroComparativo[2].t': 'sube por segunda vez seguida en el libro de tercer lugar y no se mueve en el de ganador',
  'quadroComparativo[2].s': 'Hizo un acto en Copacabana el 07/Sep, con un guiño al ministro André Mendonça, según O Globo. Criticó la polarización entre los dos primeros colocados, según Banda B.',
  'quadroComparativo[3].p': 'Veritá del 06/Sep lo mide en 3,7% en la primera vuelta, por delante de Ronaldo Caiado (1,9%) y de Pablo Marçal (1,4%). La dispersión entre casas de la ventana va de 3% a 7,6%.',
  'quadroComparativo[3].m': `1,55% (vol USD 12,76M) en el contrato de ganador, ${S7}, una caída de 0,05pp. ⚠️ En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,50pp y está en 24,50% (vol USD 279 mil).`,
  'quadroComparativo[3].t': 'interrumpió tres alzas seguidas en el libro de tercer lugar, el mismo día en que Cury subió en él',
  'quadroComparativo[3].s': 'Sigue como autor del pedido de destitución contra dos ministros del Supremo. Sin acto individual nuevo el 07/Sep.',
  'quadroComparativo[4].p': 'Veritá del 06/Sep lo pone en 1,9% en la primera vuelta, por debajo del 4% que la Datafolha del 03/Sep medía.',
  'quadroComparativo[4].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 0,50pp y está en 9,50% (vol USD 115 mil), ${S7}.`,
  'quadroComparativo[4].t': 'cede en los dos universos, en la encuesta y en el libro de tercer lugar',
  'quadroComparativo[4].s': 'Sin acto individual nuevo el 07/Sep en el noticiero recogido.',
  'quadroComparativo[5].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 0,40pp y está en 1,85% (vol USD 48 mil), ${S7}.`,
  'quadroComparativo[5].t': 'cede en el libro de tercer lugar y sigue cayendo dentro de la propia casa que lo mide',
  'quadroComparativo[5].s': 'Sin acto individual nuevo el 07/Sep en el noticiero recogido.',

  cruzamento: `El 7 de septiembre es el segundo día seguido en que las dos mediciones de esta página apuntan hacia lados opuestos, y esta vez la distancia entre ellas es mayor. ⭐ EL ESCENARIO DE ${G('SEGUNDA VUELTA', 'segundo-turno')} DE VERITÁ SALIÓ DESPUÉS DE LA RONDA DE AYER E INVIERTE EL PAR: Flávio Bolsonaro 48,5% frente a 43,1% de Lula, con 4,9% de blancos y nulos y 3,6% de indecisos, en la misma ronda de campo del 01 al 04/Sep con 3.804 entrevistas y margen de 2 puntos. Es la primera encuesta nacional de la ventana que le entrega la segunda vuelta, frente a la Datafolha del 03/Sep (46% a 44%) y la Quaest del 02/Sep (42% a 41%), las dos en sentido opuesto. ⚠️ Y EL PRECIO FUE HACIA EL OTRO LADO: el contrato de ganador subió 1,00pp para Lula y abrió la brecha de 16,80pp a 18,05pp, segunda rueda seguida de apertura. 📌 Las dos magnitudes no se restan, porque la encuesta mide intención de voto declarada en un par de segunda vuelta y el contrato mide probabilidad implícita de ganar la elección. La página registra que hoy ordenan la disputa al revés, sin arbitrar entre ellas, y anota que Veritá tiene confiabilidad 2 en la regla de la casa, la más baja de la ventana. ⚠️ EN ESTA RONDA DOS DE LOS CINCO LIBROS RECIBIERON PRECIO NUEVO, el de ganador y el de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}. Para los otros tres no hay lectura nueva el 07/Sep. ⭐ Y EL LIBRO DE TERCER LUGAR CAMBIÓ DE PROTAGONISTA: Augusto Cury subió 2,35pp hasta 58,55% y Renan Santos cedió 1,50pp hasta 24,50%, los dos en el mismo mercado y en direcciones opuestas. 🗳️ Una encuesta nacional nueva estaba prevista para hoy, la Quaest de registro BR-01720/2026 y campo del 03 al 06/Sep, y hasta la captura de esta ronda no había sido divulgada con números. Los porcentajes de Quaest que circulan hoy en la prensa son los de la ronda anterior de la casa, registro BR-07065/2026, campo del 30/Ago al 01/Sep, divulgada el 02/Sep.`,
})
