/** Mapa EN: analysis-criteriosa, rodada de 07/Set/2026. Segundo dia de divergência, e o 2º turno da Veritá inverte o par. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S7 = 'confirmed reading of 07/Sep, 13:02 BRT'
const S6 = 'confirmed reading of 06/Sep'
const PISO = 'below the 0.5% floor of the double reading, and this round publishes no new price for him in that book'

construir('analysis-criteriosa', 'en', {
  subtitle: `Crossing of 7 September 2026, ${S7} (16:02 UTC), with the presidential book at USD 144.60M. In this round two of the five books received a new price: the winner one and the ${G('first-round', 'primeiro-turno')} third-place one. Most recent national poll: Veritá of 06/Sep, registration BR-09426/2026 at the ${G('TSE', 'tse')}, whose ${G('runoff', 'segundo-turno')} scenario came out after yesterday's round and flips the pairing.`,

  // ── Lula
  'candidates[0].header': `PRICE: 57.50% (vol USD 9.92M accumulated) in the winner contract, ${S7}, a rise of 1.00pp against the ${S6}. In the ${G('first-round', 'primeiro-turno')} runner-up contract there is no fresh reading on 07/Sep. POLL: 38.4% in the first round of Veritá of 06/Sep, behind by 0.5 point inside the margin, and 43.1% against 48.5% in the ${G('runoff', 'segundo-turno')} of the same round.`,
  'candidates[0].fortes[0]': 'He rose 1.00pp in the winner contract and widened the gap to the runner-up, which goes from 16.80pp to 18.05pp since the confirmed reading of 06/Sep. It is the second consecutive session of widening.',
  'candidates[0].fortes[1]': 'His contract rose on both days when the Veritá poll moved against him, first tying the first round and now handing the runoff to his opponent.',
  'candidates[0].fortes[2]': 'In the other two national polls of the window that test the runoff against Flávio Bolsonaro he is still ahead: Datafolha of 03/Sep, 46% to 44%, and Quaest of 02/Sep, 42% to 41%.',
  'candidates[0].fracos[0]': 'Veritá of 06/Sep is the first national poll of the window to hand him defeat in the runoff, by 48.5% to 43.1%, a distance of 5.4 points that does not fit inside the poll’s own margin of 2 points.',
  'candidates[0].fracos[1]': 'The rejection measured in the same round is 35% for him against 25.8% for his opponent.',
  'candidates[0].fracos[2]': 'In the first round of the same poll he appears behind by 0.5 point, which is a statistical tie, but inside Veritá itself the sign has flipped since 21/Aug, when the house gave him 39.3% against 39.1%.',
  'candidates[0].analise': `7 September repeats the divergence of the previous day and deepens it. The winner contract rose 1.00pp to 57.50% (vol USD 9.92M) and the gap to the runner-up widened from 16.80pp to 18.05pp, a second consecutive session of widening. Over the same stretch the Veritá ${G('runoff', 'segundo-turno')} scenario, which came out only after yesterday's round, places him behind by 48.5% to 43.1%. The two quantities do not subtract from one another, because one is declared voting intention in a pairing and the other is the implied probability of winning the election, but they rank the race in opposite ways and that is what the page records. Worth the caveat that Veritá carries a reliability of 2 on the house scale, the lowest in the window, and that the two other national polls testing the pairing go the other way.`,

  // ── Flávio Bolsonaro
  'candidates[1].header': `PRICE: 39.45% (vol USD 9.80M accumulated) in the winner contract, ${S7}, a fall of 0.25pp against the ${S6}. In the ${G('first-round', 'primeiro-turno')} runner-up contract there is no fresh reading on 07/Sep. POLL: 38.9% in the first round of Veritá of 06/Sep and 48.5% against 43.1% in the ${G('runoff', 'segundo-turno')} of the same round.`,
  'candidates[1].fortes[0]': 'Veritá of 06/Sep is the first national poll of the window to hand him the runoff, by 48.5% to 43.1%, a distance of 5.4 points that does not fit inside the margin of 2 points.',
  'candidates[1].fortes[1]': 'The same round puts him numerically ahead in the first round, 38.9% against 38.4%, and measures rejection of 25.8% against 35% for his opponent.',
  'candidates[1].fortes[2]': 'Inside Veritá itself the sign has flipped since 21/Aug, when the house gave 39.3% to Lula against 39.1% for him.',
  'candidates[1].fracos[0]': 'The price moved against the poll for the second day running: he gave up 0.25pp in the winner contract on the day the poll handed him the runoff.',
  'candidates[1].fracos[1]': 'The other two national polls of the window that test the pairing go the other way: Datafolha of 03/Sep, 46% to 44% for Lula, and Quaest of 02/Sep, 42% to 41%, also for Lula.',
  'candidates[1].fracos[2]': 'Veritá carries a reliability of 2 on the house scale, the lowest among the institutes in the window.',
  'candidates[1].analise': `The round of 7 September hands him the best polling result of the window and the worst price movement of the same stretch. The Veritá ${G('runoff', 'segundo-turno')} scenario, published after yesterday's round, has him winning by 48.5% to 43.1%, and it is the first time in the whole window that a national poll does so. In the winner contract he gave up 0.25pp and stands at 39.45% (vol USD 9.80M), with the gap to the leader widening for a second session. It is the second day running in which the two measurements move in opposite directions for him, and that is the record, without arbitrating which of the two is right.`,

  // ── Augusto Cury
  'candidates[2].header': `PRICE: 1.15% (vol USD 4.19M accumulated) in the WINNER contract, ${S7}, unchanged. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he rose 2.35pp to 58.55% (vol USD 126 thousand). POLL: 12.2% in the first round of Veritá of 06/Sep.`,
  'candidates[2].fortes[0]': 'A second consecutive gain in the first-round third-place contract, which goes from 56.20% to 58.55%, on the very day Renan Santos gives up 1.50pp in that same book.',
  'candidates[2].fortes[1]': 'Veritá of 06/Sep measures him at 12.2% in the first round, against 2.2% in the same house’s round on 21/Aug.',
  'candidates[2].fortes[2]': 'He is the third-placed name in the survey with a clear margin over the fourth, who has 3.7%.',
  'candidates[2].fracos[0]': 'In the contract on winning the election he did not move and remains at 1.15%, which is to say the market is consolidating him as the third-placed finisher of the first round and not as a candidate to win.',
  'candidates[2].fracos[1]': 'Dispersion between houses is still wide: Datafolha of 03/Sep left him at 7% and 8%, against Veritá’s 12.2%.',
  'candidates[2].fracos[2]': 'The volume of the third-place contract is USD 126 thousand, far below the winner book, and movement in a thin book calls for a more careful reading.',
  'candidates[2].analise': `His two contracts keep telling different stories, and the distance between them has grown. In the ${G('first-round', 'primeiro-turno')} third-place book he rose 2.35pp and reached 58.55%, a second consecutive gain, while in the winner book he did not move and stays at 1.15%. The poll follows the first movement and not the second: Veritá measures him at 12.2%, six times what the same house measured on 21/Aug. In this round he is the name that rose the most among those that received a new price.`,

  // ── Renan Santos
  'candidates[3].header': `PRICE: 1.55% (vol USD 12.76M accumulated) in the winner contract, ${S7}, a fall of 0.05pp. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he gave up 1.50pp to 24.50% (vol USD 279 thousand). POLL: 3.7% in the first round of Veritá of 06/Sep.`,
  'candidates[3].fortes[0]': 'Among the four names above 1% in the winner contract, his is the largest accumulated volume, USD 12.76M, above the leader and the runner-up.',
  'candidates[3].fortes[1]': 'He remains the author of the impeachment request against two Supreme Court justices, a subject that keeps him in the news.',
  'candidates[3].fracos[0]': 'He gave up 1.50pp in the first-round third-place contract and broke three consecutive gains, on the very day Augusto Cury rose 2.35pp in that same book.',
  'candidates[3].fracos[1]': 'Veritá of 06/Sep measures him at 3.7% in the first round, at the lower end of a dispersion between houses that runs from 3% to 7.6%.',
  'candidates[3].fracos[2]': 'The winner contract is still priced below 2% even though his accumulated volume is the largest among the four names above 1%.',
  'candidates[3].analise': `The round reverses the movement of the previous three in the third-place book: he gives up 1.50pp to 24.50%, while Augusto Cury rises 2.35pp to 58.55%. The two move in the same book and in opposite directions, which is coherent with a partition in which mass shifts between names. In the winner contract the variation is 0.05pp, inside the noise of the book itself. His accumulated volume remains the largest among the four names above 1%, in a contract priced below 2%.`,

  // ── Caiado / Haddad / Zema
  'candidates[4].header': `PRICE: all three remain below the 0.5% floor in the WINNER contract, and this round publishes no new price for them in that book. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE one, ${S7}: Ronaldo Caiado gave up 0.50pp to 9.50% (vol USD 115 thousand) and Romeu Zema holds at 0.85% (vol USD 51 thousand). POLL: Caiado at 1.9% and Zema at 0.3% in the first round of Veritá of 06/Sep.`,
  'candidates[4].subtitle': `Chasing pack on the ${S7} (16:02 UTC). ⚠️ VERITÁ OF 06/Sep MEASURES CAIADO AT 1.9% AND ZEMA AT 0.3% IN THE ${G('FIRST ROUND', 'primeiro-turno')}, both below what Datafolha measured on 03/Sep, 4% and 2%. In the third-place book of the first round, which received a new price in this round, the two moved in different directions: Caiado gave up 0.50pp and Zema stood still.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0.15% (vol USD 7.23M) in the WINNER contract, ${PISO}. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he gave up 0.50pp to 9.50%, in a book of USD 115 thousand, ${S7}.`,
  'candidates[4].caiado.fortes': 'He remains the fourth name in the first-round third-place contract, behind Augusto Cury, Renan Santos and Flávio Bolsonaro himself in that book. The runoff pairing against him in Datafolha of 03/Sep is 5 points, 46% to 41%, tighter than Romeu Zema’s, which is 9 points.',
  'candidates[4].caiado.fracos': '⚠️ HE GIVES GROUND IN BOTH UNIVERSES IN THIS ROUND: 0.50pp in the first-round third-place contract and from 4% to 1.9% between Datafolha of 03/Sep and Veritá of 06/Sep. In the winner contract he stays below the 0.5% floor.',
  'candidates[4].zema.label': `ZEMA (Novo), 0.15% (vol USD 6.56M) in the WINNER contract, ${PISO}. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he holds at 0.85% with no change, in a book of USD 51 thousand, ${S7}.`,
  'candidates[4].zema.fortes': 'He had the most visible event of the three on Monday, on Avenida Paulista, with a panel against a Supreme Court justice and a call for judicial reform, according to Gazeta do Povo, O Globo and Valor Econômico. In PoderData of 03/Sep he sits 2 points from the leader in the runoff, 44% to 42%, the narrowest margin against him in any national poll of the window.',
  'candidates[4].zema.fracos': '⚠️ VERITÁ OF 06/Sep MEASURES HIM AT 0.3% IN THE FIRST ROUND, below the 2% of Datafolha of 03/Sep. And the event of 07/Sep produced no movement in the book where he is priced: in the first-round third-place contract he stood still at 0.85%.',
  'candidates[4].analise': `None of the three receives a new price in the winner contract, because all three sit below the 0.5% floor of the double reading. In the ${G('first-round', 'primeiro-turno')} third-place book, which did receive a new price in this round, Caiado gave up 0.50pp to 9.50% and Zema stayed put at 0.85%. The Veritá poll runs in the same direction for Caiado, who falls from 4% in Datafolha of 03/Sep to 1.9%. 7 September gave Zema the most visible event of the three, on Avenida Paulista, without that producing any price movement in the book where he is priced.`,
  'candidates[4].fortes[0]': 'Ronaldo Caiado remains the fourth name in the first-round third-place book, ahead of Pablo Marçal and Romeu Zema.',
  'candidates[4].fortes[1]': 'Romeu Zema had an event of his own on 07/Sep on Avenida Paulista, with criticism of the Supreme Court and a call for judicial reform, according to Valor Econômico, O Globo and Gazeta do Povo.',
  'candidates[4].fracos[0]': 'Caiado gave up 0.50pp in the third-place book and Veritá of 06/Sep measures him at 1.9%, below the 4% of Datafolha of 03/Sep.',
  'candidates[4].fracos[1]': 'Zema did not move in the third-place book and Veritá measures him at 0.3%, below Datafolha’s 2%.',
  'candidates[4].fracos[2]': 'Fernando Haddad is not a presidential candidate: he is running for the government of São Paulo, and his presidential contract stands at 0.05%.',

  // ── Quadro comparativo
  'quadroComparativo[0].p': `Veritá of 06/Sep (BR-09426/2026, fieldwork 01 to 04/Sep, n=3,804, margin of 2pp) measures him at 38.4% in the ${G('first round', 'primeiro-turno')}, behind by 0.5 point and inside the margin. The ${G('runoff', 'segundo-turno')} scenario of the same round, released later, puts him behind by 48.5% to 43.1%. Datafolha of 03/Sep and Quaest of 02/Sep still give the pairing to him.`,
  'quadroComparativo[0].m': `57.50% (vol USD 9.92M) in the winner contract, ${S7}, a rise of 1.00pp against the ${S6}. In the ${G('first-round', 'primeiro-turno')} runner-up contract there is no fresh reading on 07/Sep.`,
  'quadroComparativo[0].t': 'rose for a second consecutive session and widened the gap to 18.05pp, over the same stretch in which the poll handed him defeat in the runoff',
  'quadroComparativo[0].s': 'He took part in the 7 September parade in Brasília alongside Edson Fachin, Davi Alcolumbre and Hugo Motta, and made a national broadcast on sovereignty, according to Poder360, Valor Econômico and Estadão.',
  'quadroComparativo[1].p': `⭐ Veritá of 06/Sep puts him ahead in both scenarios: 38.9% against 38.4% in the ${G('first round', 'primeiro-turno')}, inside the margin, and 48.5% against 43.1% in the ${G('runoff', 'segundo-turno')}. It is the first national poll of the window to hand him the second round.`,
  'quadroComparativo[1].m': `39.45% (vol USD 9.80M) in the winner contract, ${S7}, a fall of 0.25pp against the ${S6}. In the ${G('first-round', 'primeiro-turno')} runner-up contract there is no fresh reading on 07/Sep.`,
  'quadroComparativo[1].t': 'ahead in both poll scenarios and falling in price, for the second day running',
  'quadroComparativo[1].s': 'He missed the 7 September parade and went to a church service alongside Tarcísio de Freitas, according to Poder360 and O Globo. Michelle Bolsonaro did not attend his event, according to VEJA.',
  'quadroComparativo[2].p': 'Veritá of 06/Sep measures him at 12.2% in the first round, against 2.2% in the same house’s round on 21/Aug. Datafolha of 03/Sep left him at 7% and 8%.',
  'quadroComparativo[2].m': `1.15% (vol USD 4.19M) in the winner contract, ${S7}, unchanged. ⭐ In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 2.35pp to 58.55% (vol USD 126 thousand), a second consecutive gain.`,
  'quadroComparativo[2].t': 'rises for the second time running in the third-place book and does not move in the winner one',
  'quadroComparativo[2].s': 'He held an event in Copacabana on 07/Sep, with a nod to justice André Mendonça, according to O Globo. He criticised the polarisation between the top two, according to Banda B.',
  'quadroComparativo[3].p': 'Veritá of 06/Sep measures him at 3.7% in the first round, ahead of Ronaldo Caiado (1.9%) and Pablo Marçal (1.4%). Dispersion between houses in the window runs from 3% to 7.6%.',
  'quadroComparativo[3].m': `1.55% (vol USD 12.76M) in the winner contract, ${S7}, a fall of 0.05pp. ⚠️ In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 1.50pp to 24.50% (vol USD 279 thousand).`,
  'quadroComparativo[3].t': 'broke three consecutive gains in the third-place book, on the very day Cury rose in it',
  'quadroComparativo[3].s': 'He remains the author of the impeachment request against two Supreme Court justices. No new individual act on 07/Sep.',
  'quadroComparativo[4].p': 'Veritá of 06/Sep puts him at 1.9% in the first round, below the 4% Datafolha measured on 03/Sep.',
  'quadroComparativo[4].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 0.50pp to 9.50% (vol USD 115 thousand), ${S7}.`,
  'quadroComparativo[4].t': 'gives ground in both universes, in the poll and in the third-place book',
  'quadroComparativo[4].s': 'No new individual act on 07/Sep in the news collected.',
  'quadroComparativo[5].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 0.40pp to 1.85% (vol USD 48 thousand), ${S7}.`,
  'quadroComparativo[5].t': 'gives ground in the third-place book and keeps falling inside the very house that measures him',
  'quadroComparativo[5].s': 'No new individual act on 07/Sep in the news collected.',

  cruzamento: `7 September is the second day running on which the two measurements on this page point in opposite directions, and this time the distance between them is wider. ⭐ THE VERITÁ ${G('RUNOFF', 'segundo-turno')} SCENARIO CAME OUT AFTER YESTERDAY'S ROUND AND FLIPS THE PAIRING: Flávio Bolsonaro 48.5% against 43.1% for Lula, with 4.9% blank and spoilt and 3.6% undecided, in the same round with fieldwork from 01 to 04/Sep, 3,804 interviews and a margin of 2 points. It is the first national poll of the window to hand him the second round, against Datafolha of 03/Sep (46% to 44%) and Quaest of 02/Sep (42% to 41%), both the other way. ⚠️ AND THE PRICE WENT THE OTHER WAY: the winner contract rose 1.00pp for Lula and widened the gap from 16.80pp to 18.05pp, a second consecutive session of widening. 📌 The two quantities do not subtract from one another, because the poll measures declared voting intention in a runoff pairing and the contract measures the implied probability of winning the election. The page records that today they rank the race in opposite ways, without arbitrating between them, and notes that Veritá carries a reliability of 2 on the house scale, the lowest in the window. ⚠️ IN THIS ROUND TWO OF THE FIVE BOOKS RECEIVED A NEW PRICE, the winner one and the ${G('first-round', 'primeiro-turno')} third-place one. For the other three there is no fresh reading on 07/Sep. ⭐ AND THE THIRD-PLACE BOOK CHANGED WHO IS MOVING: Augusto Cury rose 2.35pp to 58.55% and Renan Santos gave up 1.50pp to 24.50%, both in the same market and in opposite directions. 🗳️ A fresh national poll was scheduled for today, the Quaest with registration BR-01720/2026 and fieldwork from 03 to 06/Sep, and up to this round's capture it had not been released with numbers. The Quaest figures circulating in the press today are those of the house's previous round, registration BR-07065/2026, fieldwork from 30/Aug to 01/Sep, released on 02/Sep.`,
})
