/** Mapa EN: analysis-data, rodada de 07/Set/2026. Segundo dia de divergência, e o 2º turno da Veritá inverte o par. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S7 = 'confirmed reading of 07/Sep, 13:02 BRT'
const S6 = 'confirmed reading of 06/Sep'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 144.60M and the prices on this page come from the ${S7} (16:02 UTC). ⚠️ IN THIS ROUND TWO OF THE FIVE BOOKS RECEIVED A NEW PRICE, the winner one and the ${G('first-round', 'primeiro-turno')} third-place one. For the first-round runner-up book, the Supreme Court impeachment book and the Senate majority book there is no fresh reading on 07/Sep, and their numbers on this page are those of the previous round. The AFOS publishes only prices that two independent readings confirm.`,

  'cards.sentimento.text2': `⭐ THE POLL AND THE PRICE MOVED IN OPPOSITE DIRECTIONS FOR THE SECOND DAY RUNNING, and this time the distance between them is wider. The ${G('runoff', 'segundo-turno')} scenario from Veritá, released after yesterday's round, puts Flávio Bolsonaro ahead by 48.5% to 43.1%, with 4.9% blank and spoilt and 3.6% undecided. It is the first national poll of the window to hand him the runoff: Datafolha of 03/Sep gives 46% to 44% for Lula and Quaest of 02/Sep gives 42% to 41%, also for Lula. ⚠️ And the winner contract went the other way: Lula rose 1.00pp to 57.50% and the gap over the runner-up widened from 16.80pp to 18.05pp. 📌 The two quantities do not subtract from one another, because one is declared voting intention in a pairing and the other is the implied probability of winning the election. The page records that today they rank the race in opposite ways, without arbitrating.`,

  'cards.sentimento.text3': `⭐ AND THE THIRD-PLACE BOOK CHANGED WHO IS MOVING. Augusto Cury rose 2.35pp to 58.55%, a second consecutive gain, while Renan Santos gave up 1.50pp to 24.50%, breaking three consecutive gains. The two moved in the same market and in opposite directions. 🗳️ A fresh national poll was scheduled for today, the Quaest with registration BR-01720/2026 and fieldwork from 03 to 06/Sep, and up to this round's capture it had not been released with numbers. The Quaest figures circulating in the press today are those of the house's previous round, registration BR-07065/2026, fieldwork from 30/Aug to 01/Sep, released on 02/Sep.`,

  'cards.sentimento.direita': `Flávio Bolsonaro at 39.45% (vol USD 9.80M accumulated) in the winner contract, ${S7}, a fall of 0.25pp against the ${S6}. ⚠️ THE PRICE MOVED AGAINST THE POLL FOR THE SECOND DAY RUNNING, and this time the poll hands him the ${G('runoff', 'segundo-turno')}: Veritá of 06/Sep puts him at 48.5% against 43.1% for Lula, and in the ${G('first round', 'primeiro-turno')} at 38.9% against 38.4%, a distance that fits inside the margin of 2 points and is therefore a ${G('statistical tie', 'empate-tecnico')}. In the first-round runner-up contract there is no fresh reading on 07/Sep. Veritá carries a reliability of 2 on the house scale, the lowest among the institutes in the window.`,

  'cards.sentimento.esquerda': `Lula at 57.50% (vol USD 9.92M accumulated) in the winner contract, ${S7}, a rise of 1.00pp against the ${S6}. ⭐ THE GAP OVER THE RUNNER-UP WIDENED FROM 16.80pp TO 18.05pp, a second consecutive session of widening. ⚠️ And it happened over the same stretch in which the poll moved against him: Veritá of 06/Sep places him behind in the ${G('runoff', 'segundo-turno')} by 48.5% to 43.1% and measures rejection of 35% for him against 25.8% for his opponent. The other two national polls of the window that test the pairing still give him the runoff. In the ${G('first-round', 'primeiro-turno')} runner-up contract there is no fresh reading on 07/Sep.`,

  'cards.sentimento.terceiraVia': `⭐ Augusto Cury rises for the second time running in the ${G('first-round', 'primeiro-turno')} third-place contract: 2.35pp, reaching 58.55% (vol USD 126 thousand), ${S7}. In the WINNER contract, which is a different market, he did not move and remains at 1.15% (vol USD 4.19M): the market is consolidating him as the third-placed finisher and not as a candidate to win. Veritá of 06/Sep measures him at 12.2% in the first round, against 2.2% in the same house's round on 21/Aug, and Datafolha of 03/Sep left him at 7% and 8%. ⚠️ Renan Santos went the other way in the same book, giving up 1.50pp to 24.50% (vol USD 279 thousand), and Ronaldo Caiado gave up 0.50pp to 9.50%.`,

  'cards.sentimento.polymarket': `Prices from the ${S7} (16:02 UTC). ⚠️ Two of the five books this page follows received a new price in this round, the winner one and the ${G('first-round', 'primeiro-turno')} third-place one. For the first-round runner-up book, the Supreme Court impeachment book and the Senate majority book there is no fresh reading on 07/Sep, and their numbers are those of the previous round. The AFOS publishes only prices that two independent readings confirm, and says so when there is none.`,

  'cards.inss.text1': `📌 THERE IS NO NEW INSS ACT ON 07/Sep, AND THERE WAS NONE ON 06/Sep EITHER. The sweep of the day's news returned not a single story on the subject, and 7 September is a national holiday. The ceremony at the Planalto Palace, the change of criterion and the figures this page records are still those of 05/Sep and before.`,

  'cards.inss.conclusao': `What this round measures on the subject is narrow, and it is worth recording as such: nothing changed in two days. There was no new INSS act on 06 or 07/Sep, and the structured reading of government approval is still Genial/Quaest of 02/Sep. The distinction the panel has kept from the start still holds: what the government paid is one thing, what fell outside its count is another.`,

  'cards.bancoMaster.text1': `📌 THERE IS NO NEW INSTITUTIONAL ACT IN THE CASE ON 07/Sep, AND THE CHRONOLOGY OF 04/Sep REMAINS THE INFORMATION. Today's coverage of the subject is stocktaking and reaction, a week after the messages were published, and it carries no ruling, no testimony and no fresh act by an authority. On 04/Sep the Prosecutor General's Office asked for authorisation to investigate suspected interference in the production of the Federal Police report.`,

  'cards.bancoMaster.conclusao': `The chronology remains the information, and the two dates it gained are both from 04/Sep: the president of the court received the Prosecutor General's request and the Higher Council of the Federal Public Prosecution Service opened proceedings. On 07/Sep there was no new act, and what circulates is reaction to what was already on the record.`,

  'cards.stf.toffoli': `No new individual act on 07/Sep. He remains a target of the impeachment request filed by Renan Santos, alongside Alexandre de Moraes.`,

  'cards.stf.moraes': `No new individual act on 07/Sep. The Federal Police report he used remains under an inquiry opened on 04/Sep by the Prosecutor General's Office, which ordered an investigation into whether there was interference in the production of the document, according to Folha de S.Paulo, Gazeta do Povo and Estadão. On 07/Sep he was the target of placards and effigies at right-wing rallies in Brasília and on Avenida Paulista, according to Metrópoles, Gazeta do Povo and Valor Econômico.`,

  'cards.stf.gilmar': `No new individual act on 07/Sep. The proposed amendment to the court's internal rules that he presented to Edson Fachin, banning the appointment of military and police officers to commissioned posts in justices' offices, is from 05/Sep and the page keeps it with its date of origin.`,

  'cards.stf.dino': `No new individual act on 07/Sep. His statement that the Supreme Court is greater than anyone who sits on it is from 04/Sep, and the page keeps it with its date of origin.`,

  'cards.stf.mendonca': `No new individual act on 07/Sep. The Prosecutor General's request to investigate him is from 04/Sep, when Paulo Gonet asked Edson Fachin for authorisation to look into suspected interference by him in the Federal Police, according to Estadão, O Globo and Gazeta do Povo. ⚠️ On 07/Sep his name appeared at the campaign events of two presidential candidates, with Augusto Cury nodding to him in Copacabana and supporters handing out T-shirts at an event with Flávio Bolsonaro, according to O Globo.`,

  'cards.stf.nexo': `⚠️ 7 SEPTEMBER TOOK THE SUPREME COURT CRISIS INTO THE STREET, AND THAT IS THE RECORD OF THE DAY, with no new institutional act by the court. Romeu Zema displayed a panel showing Alexandre de Moraes behind bars at the Avenida Paulista rally and called for judicial reform, according to Gazeta do Povo, O Globo and Valor Econômico. In Brasília there was a right-wing rally against the court, with an effigy of Moraes in prison, according to Metrópoles and Poder360. And André Mendonça's name circulated at the events of two presidential candidates. 📌 None of these is an act of the court: they are campaign acts about the court, and the distinction matters for reading the contract.`,

  'cards.stf.analise': `There is no fresh reading on 07/Sep for the contract on a Supreme Court justice leaving by impeachment before 2027, and the figure on this page is that of the previous round, 8.60% (vol USD 88 thousand). 📌 The record of the day is the decoupling between street and price: 7 September put the court crisis at the centre of the campaign events, with a panel of Moraes behind bars on Avenida Paulista and an effigy of him in Brasília, and the contract received no new price in this round. In the series recorded since 14/Apr it runs from 2.10% to 19.30%.`,
})
