/** Mapa ES: polls-data, rodada de 08/Set/2026. Entram a BTG/Nexus de 08/Set e a Quaest de 07/Set. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S8 = 'lectura confirmada del 08/Sep, 12:00 BRT'
const S7 = 'lectura confirmada del 07/Sep'

construir('polls-data', 'es', {
  'polls[0].note': `Encuesta nacional BTG/Nexus divulgada el 08/Sep, campo del 04 al 07/Sep, registro BR-06790/2026 en el ${G('TSE', 'tse')}, 2.002 entrevistas por teléfono en el sistema CATI, margen de 2pp y 95% de confianza, costo declarado de R$ 164.888,89 (Poder360, Gazeta do Povo, Folha de S.Paulo, CNN Brasil, Metrópoles, JOTA, Estadão, VEJA, CartaCapital y Exame). ⭐ ES LA PRIMERA VEZ QUE ESTA CASA DA LA ${G('SEGUNDA VUELTA', 'segundo-turno')} A FLÁVIO BOLSONARO: 46% contra 45% de Lula. ⚠️ La distancia de 1 punto cabe entera dentro del margen de 2 puntos, así que lo que la encuesta mide es ${G('EMPATE TÉCNICO', 'empate-tecnico')} y no liderazgo. En la ronda anterior de la propia casa, del 31/Ago (BR-08900/2026, campo del 28 al 30/Ago, n=2.005), el mismo par salía 46% a 45% para LULA, es decir los mismos dos números con los lados invertidos. ⭐ Y ES LA TERCERA ENCUESTA NACIONAL SEGUIDA QUE NO DA EL PAR AL LÍDER, después de la Quaest del 07/Sep, que dio empate en 41% a 41%, y de la Veritá del 06/Sep, que dio 48,5% a 43,1%. Las dos anteriores iban en sentido opuesto: Datafolha del 03/Sep, 46% a 44%, y Quaest del 02/Sep, 42% a 41%, las dos para Lula. 🏷️ LA CASA PUBLICÓ DOS ESCENARIOS ESTIMULADOS DE ${G('PRIMERA VUELTA', 'primeiro-turno')} Y LOS DOS ESTÁN CORRECTOS, lo que explica que la prensa haya publicado al segundo con números distintos: 35% en el escenario SIN Pablo Marçal y 34% en el escenario CON él, con el líder en 39% en los dos. Pablo Marçal está inhabilitado y el Tribunal Superior Electoral tiene hasta el 14/Sep para juzgar los registros de los candidatos presidenciales. ⭐ Y LA SEGUNDA VUELTA CON AUGUSTO CURY ES EL NÚMERO QUE MÁS SE APARTA DE LA BASE: la casa lo da numéricamente por delante del líder por 45% a 43%, y la Quaest del 07/Sep, con campo prácticamente superpuesto, da al líder por delante en el mismo par por 39% a 35%. Son 6 puntos de diferencia entre dos casas sobre la misma pregunta, y el panel registra las dos sin elegir. COMPARACIÓN DENTRO DE LA CASA, que es la única válida: en la primera vuelta sin Marçal el líder se quedó en 39% por segunda ronda seguida y el segundo subió de 33% a 35%, mientras Augusto Cury cedió de 11% a 9%. RECHAZO: Flávio Bolsonaro 50% y Lula 49%, contra 55% y 53% que la Quaest midió en la misma semana, es decir las dos casas coinciden en el orden y difieren en 5 y 4 puntos en el nivel. APROBACIÓN DEL GOBIERNO: 45% aprueban y 50% desaprueban, con 4% sin respuesta, y en la escala de gestión 36% de óptima o buena, 18% de regular y 46% de mala o pésima. ⚠️ La desaprobación coincide exactamente con el 50% que la Quaest midió el 07/Sep, y la aprobación difiere en 2 puntos. 📅 LA DIVULGACIÓN DE HOY YA ESTABA EN EL CALENDARIO PUBLICADO POR EL PANEL DESDE EL 03/Sep, con la fecha prevista y el número de registro coincidiendo con lo publicado. 🏷️ El escenario espontáneo divulgado por la casa no entra en esta ficha porque el panel no logró confirmarlo en dos fuentes independientes.`,

  'polls[1].note': `Encuesta nacional Genial/Quaest divulgada el 07/Sep, campo del 03 al 06/Sep, registro BR-01720/2026 en el ${G('TSE', 'tse')}, 2.004 entrevistados de 16 años o más, margen de 2pp y 95% de confianza (G1, O Globo, Folha de S.Paulo, Estadão, Valor Econômico, UOL, CNN Brasil, Gazeta do Povo, Poder360, Brasil de Fato, Band y Congresso em Foco). ⭐ LA ${G('SEGUNDA VUELTA', 'segundo-turno')} SALIÓ EMPATADA EN 41% A 41%, y es la primera vez que la casa no da el par al líder. Dentro de la propia serie de la Quaest la distancia venía encogiendo ronda a ronda: 5 puntos el 05/Ago (44% x 39%), 3 puntos el 14/Ago (43% x 40%), 1 punto el 02/Sep (42% x 41%) y ahora cero. ⚠️ EN LA ${G('PRIMERA VUELTA', 'primeiro-turno')} LA CASA SIGUE DANDO 7 PUNTOS AL LÍDER, 36% contra 29%, y esa es la mayor ventaja entre las tres encuestas nacionales de campo superpuesto: la BTG/Nexus del 08/Sep da 4 puntos y la Veritá del 06/Sep puso al segundo 0,5 punto por delante. Son 7,5 puntos de amplitud entre casas sobre la misma pregunta, más del doble del margen de error que cada una declara. COMPARACIÓN DENTRO DE LA CASA: frente a la ronda del 02/Sep el líder cedió 1 punto, de 37% a 36%, el segundo se quedó estancado en 29% y Augusto Cury cedió 2 puntos, de 10% a 8%. ⚠️ AUGUSTO CURY CEDE EN LAS DOS CASAS DE LA SEMANA, de 10% a 8% aquí y de 11% a 9% en la BTG/Nexus, cada una dentro de su propia serie. La casa publicó dos escenarios de primera vuelta, con y sin Pablo Marçal, y el segundo se queda en 29% en los dos, es decir su inclusión no mueve el par de arriba. ⭐ Y LA SEGUNDA VUELTA CONTRA AUGUSTO CURY CONTRADICE A LA OTRA CASA DE LA SEMANA: aquí el líder gana por 39% a 35%, y la BTG/Nexus del 08/Sep da a Cury por delante por 45% a 43%. RECHAZO: Flávio Bolsonaro 55% y Lula 53%, contra 50% y 49% en la BTG/Nexus, con las dos casas coincidiendo en el orden y difiriendo en el nivel. APROBACIÓN DEL GOBIERNO: 43% aprueban y 50% desaprueban. Dentro de la propia casa eran 48% contra 47% el 05/Ago, 46% contra 48% el 14/Ago y 45% contra 48% el 02/Sep, es decir la desaprobación repitió 48% durante tres rondas y ahora subió 2 puntos. 📅 LA DIVULGACIÓN DE ESTE LUNES YA ESTABA EN EL REGISTRO DEL ${G('TSE', 'tse')} ingerido por el panel, y el 07/Sep la página registró que hasta la captura de aquella ronda todavía no traía números. Salió después, y esta ficha es el registro de ella.`,

  'approvalData.note': `🏷️ LOS NÚMEROS ESTRUCTURADOS DE ESTE BLOQUE PASAN A SER LOS DE LA GENIAL/QUAEST DEL 07/Sep, y son: 43% de aprobación contra 50% de desaprobación. El panel mantiene UNA casa por bloque a propósito, y como la ronda nueva es de la misma casa la serie interna se preserva entera. ⚠️ DENTRO DE LA PROPIA QUAEST LA INMOVILIDAD SE ACABÓ: eran 48% de aprobación contra 47% de desaprobación el 05/Ago, 46% contra 48% el 14/Ago y 45% contra 48% el 02/Sep. La desaprobación había repetido 48% durante tres rondas seguidas y ahora subió 2 puntos, en el mismo intervalo en que la aprobación cedió 2. ⭐ Y LA BTG/NEXUS DEL 08/Sep, DE OTRA CASA Y CON CAMPO SUPERPUESTO, LLEGA EXACTAMENTE A LA MISMA DESAPROBACIÓN: 45% de aprobación y 50% de desaprobación, con 4% sin respuesta, y en la escala de gestión 36% de óptima o buena, 18% de regular y 46% de mala o pésima. Las dos casas coinciden en 50% en la desaprobación y difieren en 2 puntos en la aprobación, y el panel registra las dos sin sumarlas. La Datafolha del 03/Sep, que medía 45% y 51%, sigue registrada con su fecha de origen.`,

  'polymarketComparison.note': `Precios de Polymarket con el libro presidencial en USD 145,26M, ${S8} (15:00 UTC). ⭐ EN ESTA RONDA LOS CINCO LIBROS RECIBIERON PRECIO NUEVO, algo que no ocurría desde el 06/Sep: ganador, segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, tercer lugar de la primera vuelta, impeachment en el ${G('Supremo', 'stf')} y mayoría en el Senado. ⭐ Y LA ENCUESTA Y EL PRECIO SE MOVIERON HACIA EL MISMO LADO POR PRIMERA VEZ EN ESTA VENTANA: el contrato de ganador cerró la brecha de 18,05pp a 10,65pp, con Lula cediendo 3,00pp hasta 54,50% y Flávio Bolsonaro subiendo 4,40pp hasta 43,85%, y las dos encuestas nacionales que entraron acortan la disputa, con la BTG/Nexus del 08/Sep dando al segundo la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45% y la Quaest del 07/Sep registrando empate en 41% a 41%. ⚠️ LA PRIMERA VUELTA NO ACOMPAÑA: las tres casas de campo superpuesto dan 7, 4 y menos 0,5 punto de ventaja al líder, una amplitud de 7,5 puntos entre casas. 📌 Las dos magnitudes no se restan, porque una es intención de voto declarada y la otra es probabilidad implícita de ganar la elección. Hoy ordenan la disputa del mismo modo, y la página lo registra sin arbitrar entre ellas.`,

  'polymarketComparison.sources': `Precios de Polymarket vía el proxy AFOS, y el panel solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20pp. La confirmación se hace contrato a contrato, y el 08/Sep los cinco libros confirmaron. Encuestas registradas en el ${G('TSE', 'tse')} y divulgadas por los institutos, con reporte de Poder360, Gazeta do Povo, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, CNN Brasil, Metrópoles, JOTA, VEJA, CartaCapital, Exame, UOL, Band, Brasil de Fato y Congresso em Foco. El calendario de encuestas en campo y de divulgación prevista sale del registro oficial del TSE. Superlativo de serie verificado en el backup de Neon, en backup/neon/marketPrice, que guarda el registro completo desde el 14/Abr.`,

  'polymarketComparison.candidates[0].polymarket': `54,50%`,
  'polymarketComparison.candidates[0].pesquisaRange': `36% a 39%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `La BTG/Nexus del 08/Sep (BR-06790/2026, campo del 04 al 07/Sep, n=2.002, margen de 2pp) lo mide en 39% en la ${G('primera vuelta', 'primeiro-turno')}, en el escenario sin Pablo Marçal, y lo pone POR DETRÁS en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45%. La Quaest del 07/Sep (BR-01720/2026, campo del 03 al 06/Sep, n=2.004) da 36% en la primera vuelta y empate en 41% a 41% en la segunda. ⭐ Con la Veritá del 06/Sep, son tres encuestas nacionales seguidas sin darle la victoria en el par, frente a la Datafolha del 03/Sep (46% a 44%) y la Quaest del 02/Sep (42% a 41%), las dos a su favor. La aprobación del gobierno es de 43% contra 50% en la Quaest y 45% contra 50% en la BTG/Nexus.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `54,50% (vol USD 10,13M) en el contrato de ganador, ${S8}, una caída de 3,00pp frente a la ${S7}. La brecha sobre el segundo cayó de 18,05pp a 10,65pp, tras dos jornadas seguidas de apertura, con USD 660 mil de dinero nuevo en el libro presidencial. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} está en 9,70% (vol USD 480 mil).`,

  'polymarketComparison.candidates[1].polymarket': `43,85%`,
  'polymarketComparison.candidates[1].pesquisaRange': `29% a 35%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `La BTG/Nexus del 08/Sep lo pone POR DELANTE en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45%, distancia que cabe dentro del margen de 2 puntos y por lo tanto es ${G('empate técnico', 'empate-tecnico')}, y es la primera vez que esa casa lo hace: en su ronda del 31/Ago el mismo par salía 46% a 45% para el otro lado. En la ${G('primera vuelta', 'primeiro-turno')} la casa lo mide en 35% en el escenario sin Pablo Marçal y en 34% en el escenario con él. La Quaest del 07/Sep da 29% en la primera vuelta, lo mismo que el 02/Sep, y empate en 41% a 41% en la segunda. ⚠️ Las dos casas miden su rechazo por encima del líder: 55% contra 53% en la Quaest y 50% contra 49% en la BTG/Nexus.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `43,85% (vol USD 9,91M) en el contrato de ganador, ${S8}, una subida de 4,40pp frente a la ${S7}, el mayor movimiento de la ronda. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,00pp y está en 88,50% (vol USD 644 mil). En la serie registrada desde el 14/Abr su contrato de ganador va de 22,00% a 45,50%, y la lectura de hoy queda dentro de esa franja.`,

  'polymarketComparison.candidates[2].polymarket': `0,85%`,
  'polymarketComparison.candidates[2].pesquisaRange': `8% a 9%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `⚠️ CEDE EN LAS DOS CASAS DE LA SEMANA, cada una dentro de su propia serie: la Quaest lo lleva de 10% el 02/Sep a 8%, y la BTG/Nexus de 11% el 31/Ago a 9%. ⭐ Y UN NÚMERO VA EN LA DIRECCIÓN CONTRARIA: la BTG/Nexus lo da numéricamente por delante del líder en una ${G('segunda vuelta', 'segundo-turno')}, por 45% a 43%, mientras la Quaest, en la misma semana y en el mismo par, da al líder por delante 39% a 35%. Son 6 puntos de diferencia entre dos casas sobre la misma pregunta, y el panel registra las dos sin elegir.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `0,85% (vol USD 4,34M) en el contrato de GANADOR, ${S8}, una caída de 0,30pp, a 0,05pp del piso de su serie, que empieza el 27/Ago y va de 0,80% a 5,00%. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, cedió 6,55pp y está en 52,00% (vol USD 129 mil), devolviendo con holgura la subida de 2,35pp de la víspera.`,

  'polymarketComparison.candidates[3].polymarket': `1,30%`,
  'polymarketComparison.candidates[3].pesquisaRange': `3% a 4%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La BTG/Nexus del 08/Sep lo mide en 4% en la ${G('primera vuelta', 'primeiro-turno')}, contra 3% que la misma casa medía el 31/Ago, y la Quaest del 07/Sep lo mantiene en 3%, lo mismo que el 02/Sep. En los pares de ${G('segunda vuelta', 'segundo-turno')} las dos casas lo dan perdiendo con holgura: 47% a 39% en la BTG/Nexus y 42% a 37% en la Quaest.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,30% (vol USD 12,83M) en el contrato de ganador, ${S8}, una caída de 0,25pp, a 0,10pp del piso de su serie, que va de 1,20% a 17,90% desde el 14/Abr. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} subió 5,00pp y está en 29,50% (vol USD 282 mil), deshaciendo la caída de 1,50pp de la víspera. Sigue con el mayor volumen acumulado entre los nombres por encima del piso de publicación en el contrato de ganador.`,

  'polymarketComparison.candidates[4].pesquisaRange': `3% a 4%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `La BTG/Nexus del 08/Sep lo mide en 4% en la ${G('primera vuelta', 'primeiro-turno')} y lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} por 46% a 43%, el menor margen entre los tres pares en que esa casa da la victoria al líder. La Quaest del 07/Sep lo mide en 3% y da 41% a 38%, su par más ajustado después del que involucra al segundo.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `Por debajo de 0,5% en el contrato de GANADOR, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} subió 0,50pp y está en 10,00% (vol USD 115 mil), ${S8}.`,

  'polymarketComparison.candidates[5].pesquisaRange': `1% a 3%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `La BTG/Nexus del 08/Sep lo mide en 3% en el escenario de ${G('primera vuelta', 'primeiro-turno')} que lo incluye y la Quaest del 07/Sep en 1%. ⚠️ Solo en la BTG/Nexus su inclusión mueve el par de arriba, llevando al segundo de 35% a 34%; en la Quaest el segundo se queda en 29% en los dos escenarios. Está inhabilitado, y el Tribunal Superior Electoral tiene hasta el 14/Sep para juzgar los registros de los candidatos presidenciales.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `Por debajo de 0,5% en el contrato de GANADOR, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} cedió 0,10pp y está en 1,75% (vol USD 48 mil), ${S8}.`,

  'polymarketComparison.candidates[6].pesquisaRange': `1% a 2%`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La BTG/Nexus del 08/Sep lo mide en 1% en el escenario sin Pablo Marçal y en 2% en el escenario con él, y la Quaest del 07/Sep en 2%. Las diferencias caben dentro del margen de 2 puntos de cada casa. En los pares de ${G('segunda vuelta', 'segundo-turno')} es el más holgado de las dos: 47% a 40% en la BTG/Nexus y 44% a 33% en la Quaest.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `Por debajo de 0,5% en el contrato de GANADOR, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} sigue en 0,85% (vol USD 51 mil), ${S8}.`,

  'polymarketComparison.candidates[7].tendenciaPesquisa': `Ninguna de las dos encuestas nacionales que entraron el 07 y el 08/Sep lo prueba en escenario presidencial. Disputa la reelección en São Paulo.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `Por debajo de 0,5% en el contrato de GANADOR, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él. Su libro es el mayor del panel en volumen acumulado en un contrato que paga 0,05%, y esa combinación es la firma de un mercado que ya resolvió la pregunta.`,

  'polymarketComparison.candidates[8].tendenciaPesquisa': `Ninguna de las dos encuestas nacionales que entraron el 07 y el 08/Sep lo prueba en escenario presidencial. No es candidato a la Presidencia: disputa el gobierno de São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `Por debajo de 0,5% en el contrato de GANADOR, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él. Su precio presidencial es residuo de libro, no medida de campaña.`,
})
