/** Mapa ES: analysis-criteriosa, rodada de 08/Set/2026. Encuesta y precio se mueven hacia el MISMO lado por primera vez en la ventana. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S8 = 'lectura confirmada del 08/Sep, 12:00 BRT'
const S7 = 'lectura confirmada del 07/Sep'

construir('analysis-criteriosa', 'es', {
  'subtitle': `Cruce del 8 de septiembre de 2026, ${S8} (15:00 UTC), con el libro presidencial en USD 145,26M. En esta ronda los CINCO libros recibieron precio nuevo, algo que no ocurría desde el 06/Sep. Dos encuestas nacionales entraron en la base: la Quaest del 07/Sep, registro BR-01720/2026, y la BTG/Nexus del 08/Sep, registro BR-06790/2026.`,

  'cruzamento': `Después de dos días apuntando hacia lados opuestos, las dos mediciones de esta página se movieron hacia el mismo lado, y el movimiento es grande de los dos lados. ⭐ EL CONTRATO DE GANADOR CERRÓ LA BRECHA DE 18,05pp A 10,65pp: Lula cedió 3,00pp y está en 54,50% (vol USD 10,13M) y Flávio Bolsonaro subió 4,40pp y está en 43,85% (vol USD 9,91M), con USD 660 mil de dinero nuevo en el libro presidencial desde la ${S7}. ⭐ Y LAS TRES ENCUESTAS NACIONALES MÁS RECIENTES VAN EN LA MISMA DIRECCIÓN EN LA ${G('SEGUNDA VUELTA', 'segundo-turno')}: la BTG/Nexus del 08/Sep da a Flávio Bolsonaro por delante 46% a 45%, la Quaest del 07/Sep registra empate en 41% a 41% y la Veritá del 06/Sep dio 48,5% a 43,1%. Las dos anteriores iban al revés, con la Datafolha del 03/Sep en 46% a 44% y la Quaest del 02/Sep en 42% a 41%, las dos a favor de Lula. ⚠️ Y LA ${G('PRIMERA VUELTA', 'primeiro-turno')} NO ACOMPAÑA A LA SEGUNDA. Con trabajo de campo prácticamente superpuesto, las tres casas discrepan sobre el tamaño de la ventaja del líder: 7 puntos en la Quaest, 4 puntos en la BTG/Nexus en el escenario sin Pablo Marçal, y la Veritá puso al segundo 0,5 punto por delante. Son 7,5 puntos de amplitud entre casas sobre la misma pregunta, y es mayor que cualquiera de los tres márgenes de error, que son de 2 puntos. 📌 Las dos magnitudes no se restan, porque la encuesta mide intención de voto declarada y el contrato mide probabilidad implícita de ganar la elección. Hoy ordenan la disputa del mismo modo, y la página lo registra sin arbitrar. 🏛️ Dos actos institucionales entraron en la ventana: André Mendonça apartó por 90 días al director general de la Policía Federal y al director de Inteligencia, y la Segunda Sala formó mayoría siguiendo al ponente antes de que Gilmar Mendes pidiera vista, lo que SUSPENDIÓ el juicio. ⚠️ En el mismo intervalo el contrato de salida de un ministro del ${G('Supremo', 'stf')} por impeachment cedió 1,15pp y está en 7,45%.`,

  'candidates[0].header': `PRECIO: 54,50% (vol USD 10,13M acumulado) en el contrato de ganador, ${S8}, una caída de 3,00pp frente a la ${S7}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} está en 9,70% (vol USD 480 mil). ENCUESTA: 39% en la primera vuelta de la BTG/Nexus del 08/Sep y 45% contra 46% en la ${G('segunda vuelta', 'segundo-turno')} de la misma ronda; 36% en la primera vuelta de la Quaest del 07/Sep y empate en 41% a 41% en la segunda.`,
  'candidates[0].fortes[0]': `Sigue por delante en la ${G('primera vuelta', 'primeiro-turno')} en las dos encuestas nacionales que entraron: 39% contra 35% en la BTG/Nexus del 08/Sep, en el escenario sin Pablo Marçal, y 36% contra 29% en la Quaest del 07/Sep.`,
  'candidates[0].fortes[1]': `La BTG/Nexus lo da ganando tres de los cinco pares de ${G('segunda vuelta', 'segundo-turno')} que probó: 46% a 43% contra Ronaldo Caiado, 47% a 40% contra Romeu Zema y 47% a 39% contra Renan Santos.`,
  'candidates[0].fortes[2]': `Las dos casas miden su rechazo por debajo del segundo: 53% contra 55% en la Quaest y 49% contra 50% en la BTG/Nexus.`,
  'candidates[0].fracos[0]': `Cedió 3,00pp en el contrato de ganador y la brecha sobre el segundo cayó de 18,05pp a 10,65pp, tras dos jornadas seguidas de apertura.`,
  'candidates[0].fracos[1]': `La BTG/Nexus del 08/Sep lo pone por detrás en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45% y la Quaest del 07/Sep registra empate en 41% a 41%. Sumadas a la Veritá del 06/Sep, son tres encuestas nacionales seguidas sin darle la victoria en el par.`,
  'candidates[0].fracos[2]': `La aprobación del gobierno cayó dentro de la propia Quaest, de 45% contra 48% el 02/Sep a 43% contra 50% ahora, y la BTG/Nexus mide 45% contra 50% en la misma semana. Las dos casas llegan exactamente a la misma desaprobación.`,
  'candidates[0].analise': `El 8 de septiembre es el primer día de esta ventana en que la encuesta y el precio van hacia el mismo lado, y el movimiento es grande en los dos. El contrato de ganador cedió 3,00pp y está en 54,50% (vol USD 10,13M), con la brecha sobre el segundo cayendo de 18,05pp a 10,65pp. En el mismo intervalo entraron dos encuestas nacionales y las dos acortan la disputa: la BTG/Nexus lo pone por detrás 46% a 45% en la ${G('segunda vuelta', 'segundo-turno')} y la Quaest registra empate en 41% a 41%. ⚠️ La ${G('primera vuelta', 'primeiro-turno')} de esas mismas dos casas cuenta otra historia, porque en ella sigue por delante por 4 y por 7 puntos. Lo que la página registra es que las dos mediciones coincidieron en la dirección y no en el tamaño, y que el desacuerdo entre las casas sobre la primera vuelta es mayor que el margen de error que ellas declaran.`,

  'candidates[1].header': `PRECIO: 43,85% (vol USD 9,91M acumulado) en el contrato de ganador, ${S8}, una subida de 4,40pp frente a la ${S7}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,00pp y está en 88,50% (vol USD 644 mil). ENCUESTA: 35% en la primera vuelta de la BTG/Nexus del 08/Sep en el escenario sin Pablo Marçal y 46% contra 45% en la ${G('segunda vuelta', 'segundo-turno')}; 29% en la primera vuelta de la Quaest del 07/Sep y empate en 41% a 41% en la segunda.`,
  'candidates[1].fortes[0]': `Subió 4,40pp en el contrato de ganador, el mayor movimiento de la ronda, y cerró la brecha con el líder de 18,05pp a 10,65pp.`,
  'candidates[1].fortes[1]': `La BTG/Nexus del 08/Sep lo pone por delante en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45%. Es la tercera encuesta nacional seguida que no le da el par al líder, después de la Quaest de ayer, que dio empate, y de la Veritá del 06/Sep.`,
  'candidates[1].fortes[2]': `En la Quaest no se movió en la ${G('primera vuelta', 'primeiro-turno')}, con 29% en dos rondas seguidas de la casa, mientras el líder cedió 1 punto, de 37% a 36%.`,
  'candidates[1].fracos[0]': `Cedió 1,00pp en el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} y está en 88,50% (vol USD 644 mil), con USD 32 mil de dinero nuevo en ese libro.`,
  'candidates[1].fracos[1]': `En la primera vuelta sigue por detrás en las dos encuestas nacionales que entraron: 35% contra 39% en la BTG/Nexus, escenario sin Pablo Marçal, y 29% contra 36% en la Quaest.`,
  'candidates[1].fracos[2]': `Las dos casas miden su rechazo por encima del líder: 55% contra 53% en la Quaest y 50% contra 49% en la BTG/Nexus.`,
  'candidates[1].analise': `La ronda del 8 de septiembre le entrega el mayor movimiento de precio del día y el mejor resultado de encuesta de la ventana, y esta vez los dos van en la misma dirección. El contrato de ganador subió 4,40pp y está en 43,85% (vol USD 9,91M) y la brecha con el líder cayó de 18,05pp a 10,65pp. La BTG/Nexus de hoy lo pone por delante en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45%, distancia que cabe dentro del margen de 2 puntos y por lo tanto es ${G('empate técnico', 'empate-tecnico')}, y la Quaest de ayer registra empate numérico en 41% a 41%. ⚠️ La ${G('primera vuelta', 'primeiro-turno')} de esas mismas dos casas lo deja 4 y 7 puntos por detrás, y esa es la distancia que la página registra sin intentar cerrarla. En la serie registrada desde el 14/Abr su contrato de ganador va de 22,00% a 45,50%, y la lectura de hoy queda dentro de esa franja.`,

  'candidates[2].header': `PRECIO: 0,85% (vol USD 4,34M acumulado) en el contrato de GANADOR, ${S8}, una caída de 0,30pp. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} cedió 6,55pp y está en 52,00% (vol USD 129 mil). ENCUESTA: 9% en la primera vuelta de la BTG/Nexus del 08/Sep y 8% en la de la Quaest del 07/Sep.`,
  'candidates[2].fortes[0]': `⭐ La BTG/Nexus del 08/Sep lo prueba en una ${G('segunda vuelta', 'segundo-turno')} contra el líder y lo da numéricamente por delante, por 45% a 43%, dentro del margen de 2 puntos. La Quaest del 07/Sep prueba el mismo par y da al líder por delante 39% a 35%.`,
  'candidates[2].fortes[1]': `Sigue siendo el tercero en las dos encuestas nacionales que entraron, con 9% en la BTG/Nexus y 8% en la Quaest, por delante del cuarto en las dos.`,
  'candidates[2].fortes[2]': `El contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} sigue siendo suyo, con 52,00% contra 29,50% del segundo nombre de ese libro.`,
  'candidates[2].fracos[0]': `Cedió 6,55pp en el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} y devolvió con holgura la subida de 2,35pp de la ronda anterior.`,
  'candidates[2].fracos[1]': `Las dos casas lo miden a la baja dentro de su propia serie: la Quaest va de 10% el 02/Sep a 8%, y la BTG/Nexus de 11% el 31/Ago a 9%.`,
  'candidates[2].fracos[2]': `En el contrato de ganar la elección cedió 0,30pp y está en 0,85%, a 0,05pp del piso de su serie, que empieza el 27/Ago y va de 0,80% a 5,00%.`,
  'candidates[2].analise': `Los tres medidores que lo tocan apuntan hacia abajo en esta ronda. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 6,55pp y está en 52,00% (vol USD 129 mil); la Quaest lo lleva de 10% a 8% y la BTG/Nexus de 11% a 9%, cada una dentro de su propia serie; y en el contrato de ganar la elección cedió 0,30pp y está en 0,85%, a 0,05pp del piso de su serie. ⭐ Y hay un número que va en la dirección contraria, en un par de ${G('segunda vuelta', 'segundo-turno')}: la BTG/Nexus lo da por delante del líder por 45% a 43%, mientras la Quaest, en la misma semana y en el mismo par, da al líder por delante 39% a 35%. Son 6 puntos de diferencia entre dos casas sobre la misma pregunta, y el panel registra las dos sin elegir.`,

  'candidates[3].header': `PRECIO: 1,30% (vol USD 12,83M acumulado) en el contrato de ganador, ${S8}, una caída de 0,25pp. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')} subió 5,00pp y está en 29,50% (vol USD 282 mil). ENCUESTA: 4% en la primera vuelta de la BTG/Nexus del 08/Sep y 3% en la de la Quaest del 07/Sep.`,
  'candidates[3].fortes[0]': `Subió 5,00pp en el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} y deshizo la caída de 1,50pp de la ronda anterior, en el mismo libro en que Augusto Cury cedió 6,55pp.`,
  'candidates[3].fortes[1]': `La BTG/Nexus del 08/Sep lo mide en 4% en la primera vuelta, contra 3% que la misma casa medía el 31/Ago.`,
  'candidates[3].fortes[2]': `Sigue con el mayor volumen acumulado entre los nombres por encima del piso de 0,5% en el contrato de ganador, USD 12,83M, por encima del líder y del segundo.`,
  'candidates[3].fracos[0]': `Cedió 0,25pp en el contrato de ganador y está en 1,30%, a 0,10pp del piso de su serie, que va de 1,20% a 17,90% desde el 14/Abr.`,
  'candidates[3].fracos[1]': `La Quaest del 07/Sep lo mantiene en 3% en la ${G('primera vuelta', 'primeiro-turno')}, lo mismo que la ronda de la casa del 02/Sep.`,
  'candidates[3].fracos[2]': `En los pares de ${G('segunda vuelta', 'segundo-turno')} las dos casas lo dan perdiendo con holgura: 47% a 39% en la BTG/Nexus y 42% a 37% en la Quaest.`,
  'candidates[3].analise': `El libro de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} deshizo en un día el movimiento de la ronda anterior. Subió 5,00pp y está en 29,50% (vol USD 282 mil), mientras Augusto Cury cedió 6,55pp, exactamente lo inverso de lo que hicieron los dos el 07/Sep. ⚠️ El libro es fino, con USD 282 mil y USD 129 mil acumulados en esos dos nombres, contra USD 145,26M del presidencial, y un movimiento grande en libro fino pide una lectura más cautelosa. En el contrato de ganar la elección cedió 0,25pp y está en 1,30%, a 0,10pp del piso de la serie, en un contrato cuyo volumen acumulado es el mayor entre los nombres por encima del piso de publicación.`,

  'candidates[4].header': `PRECIO: los tres siguen por debajo del piso de 0,5% en el contrato de GANADOR, y esta ronda no publica precio nuevo para ellos en ese libro. En el de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, ${S8}: Ronaldo Caiado subió 0,50pp y está en 10,00% (vol USD 115 mil) y Romeu Zema sigue en 0,85% (vol USD 51 mil). ENCUESTA: Caiado 4% y Zema 1% en la primera vuelta de la BTG/Nexus del 08/Sep, escenario sin Pablo Marçal, y Caiado 3% y Zema 2% en la de la Quaest del 07/Sep.`,
  'candidates[4].subtitle': `Pelotón de atrás en la ${S8} (15:00 UTC). ⚠️ LAS DOS ENCUESTAS NACIONALES QUE ENTRARON MIDEN A CAIADO EN 4% Y 3% Y A ZEMA EN 1% Y 2% EN LA ${G('PRIMERA VUELTA', 'primeiro-turno')}, diferencias que caben dentro del margen de 2 puntos de cada casa. En el libro de tercer lugar de la primera vuelta, que recibió precio nuevo en esta ronda, los dos se movieron en direcciones distintas: Caiado subió 0,50pp y Zema se quedó quieto.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0,15% (vol USD 7,25M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, subió 0,50pp y está en 10,00%, en un libro de USD 115 mil, ${S8} (15:00 UTC).`,
  'candidates[4].caiado.fortes': `⭐ EN LAS DOS CASAS DE LA SEMANA TIENE EL PAR DE ${G('SEGUNDA VUELTA', 'segundo-turno')} MÁS AJUSTADO DESPUÉS DEL QUE INVOLUCRA AL SEGUNDO: 46% a 43% en la BTG/Nexus del 08/Sep, el menor margen entre los tres pares en que esa casa da la victoria al líder, y 41% a 38% en la Quaest del 07/Sep. Y subió 0,50pp en el contrato de tercer lugar de la primera vuelta, volviendo a 10,00%.`,
  'candidates[4].caiado.fracos': `⚠️ En el contrato de GANADOR sigue por debajo del piso de 0,5%, y es el único de los tres universos en que no se mueve. En la ${G('primera vuelta', 'primeiro-turno')} las dos casas lo miden en 4% y 3%, sin variación relevante frente a sus rondas anteriores.`,
  'candidates[4].haddad.fortes': `No es probado como candidato presidencial en las encuestas nacionales de la ventana, y ni la BTG/Nexus del 08/Sep ni la Quaest del 07/Sep lo prueban, así que no hay lectura de urna para cruzar con el precio.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0,15% (vol USD 6,65M) en el contrato de GANADOR, por debajo del piso de 0,5% de la doble lectura, y esta ronda no publica precio nuevo para él en ese contrato. En el contrato de TERCER LUGAR de la ${G('primera vuelta', 'primeiro-turno')}, que es otro mercado, sigue en 0,85% sin variación, en un libro de USD 51 mil, ${S8} (15:00 UTC).`,
  'candidates[4].zema.fortes': `La BTG/Nexus del 08/Sep lo mide en 2% en el escenario de ${G('primera vuelta', 'primeiro-turno')} que incluye a Pablo Marçal, contra 1% en el escenario sin él, y la Quaest del 07/Sep lo mide en 2%. Las tres lecturas caben dentro del margen de 2 puntos de cada casa.`,
  'candidates[4].zema.fracos': `⚠️ EN LOS PARES DE ${G('SEGUNDA VUELTA', 'segundo-turno')} ES EL MÁS HOLGADO DE LAS DOS CASAS: 47% a 40% en la BTG/Nexus y 44% a 33% en la Quaest, es decir 7 y 11 puntos de distancia. Y se quedó estancado en 0,85% en el contrato de tercer lugar de la primera vuelta, por detrás de Pablo Marçal, que está en 1,75%.`,
  'candidates[4].fortes[0]': `Ronaldo Caiado subió 0,50pp en el libro de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} y volvió a 10,00%, tercer nombre de ese libro.`,
  'candidates[4].fortes[1]': `La BTG/Nexus del 08/Sep lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} frente al líder por 46% a 43%, el menor margen entre los tres pares en que esa casa da la victoria al líder.`,
  'candidates[4].fortes[2]': `En la Quaest del 07/Sep el par de ${G('segunda vuelta', 'segundo-turno')} contra él es el más ajustado después del que involucra al segundo: 41% a 38%.`,
  'candidates[4].fracos[0]': `Ninguno de los tres recibe precio nuevo en el contrato de ganador, porque los tres siguen por debajo del piso de 0,5% de la doble lectura.`,
  'candidates[4].fracos[1]': `Romeu Zema no se movió en el libro de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} y sigue en 0,85%, por detrás de Pablo Marçal, que está en 1,75%.`,
  'candidates[4].analise': `En el libro de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')}, el único en que dos de ellos tienen precio, Ronaldo Caiado subió 0,50pp y está en 10,00% y Romeu Zema se quedó estancado en 0,85%. Las dos encuestas nacionales que entraron miden a Caiado en 4% y 3% en la primera vuelta y a Zema en 1% y 2%, diferencias que caben dentro del margen de 2 puntos de cada casa. ⭐ El número de Caiado que más informa es el de la ${G('segunda vuelta', 'segundo-turno')}: 46% a 43% en la BTG/Nexus y 41% a 38% en la Quaest, y en las dos casas es el par más ajustado después del que involucra al segundo. En el contrato de ganar la elección los tres siguen por debajo del piso, y la página no publica precio nuevo para ellos en ese libro.`,

  'quadroComparativo[0].p': `La BTG/Nexus del 08/Sep (BR-06790/2026, campo del 04 al 07/Sep, n=2.002, margen de 2pp) lo mide en 39% en la ${G('primera vuelta', 'primeiro-turno')}, en el escenario sin Pablo Marçal, y lo pone por detrás 46% a 45% en la ${G('segunda vuelta', 'segundo-turno')}. La Quaest del 07/Sep (BR-01720/2026, campo del 03 al 06/Sep, n=2.004, margen de 2pp) da 36% en la primera vuelta y empate en 41% a 41% en la segunda.`,
  'quadroComparativo[0].m': `54,50% (vol USD 10,13M) en el contrato de ganador, ${S8}, una caída de 3,00pp frente a la ${S7}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} está en 9,70% (vol USD 480 mil).`,
  'quadroComparativo[0].t': `cedió 3,00pp y la brecha sobre el segundo cayó de 18,05pp a 10,65pp, el mismo día en que dos encuestas nacionales acortaron la disputa`,
  'quadroComparativo[0].s': `Reunió a colaboradores para discutir la reacción a la decisión de André Mendonça que apartó al director general de la Policía Federal, y el ministro de Relaciones Institucionales llamó al apartamiento una intromisión, según O Globo.`,

  'quadroComparativo[1].p': `La BTG/Nexus del 08/Sep lo pone por delante en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45%, dentro del margen de 2 puntos, y lo mide en 35% en la ${G('primera vuelta', 'primeiro-turno')} en el escenario sin Pablo Marçal y en 34% en el escenario con él. La Quaest del 07/Sep da 29% en la primera vuelta y empate en 41% a 41% en la segunda.`,
  'quadroComparativo[1].m': `43,85% (vol USD 9,91M) en el contrato de ganador, ${S8}, una subida de 4,40pp frente a la ${S7}. En el contrato de segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 1,00pp y está en 88,50% (vol USD 644 mil).`,
  'quadroComparativo[1].t': `subió 4,40pp, el mayor movimiento de la ronda, y es la tercera encuesta nacional seguida que no da la segunda vuelta al líder`,
  'quadroComparativo[1].s': `En el acto de la avenida Paulista del 07/Sep vinculó al líder con Alexandre de Moraes y dijo que nombraría cinco ministros al Supremo, según JOTA, O Globo y Folha de S.Paulo.`,

  'quadroComparativo[2].p': `La BTG/Nexus del 08/Sep lo mide en 9% en la ${G('primera vuelta', 'primeiro-turno')}, contra 11% en la ronda de la propia casa del 31/Ago, y lo da numéricamente por delante del líder en una ${G('segunda vuelta', 'segundo-turno')}, por 45% a 43%. La Quaest del 07/Sep lo mide en 8%, contra 10% el 02/Sep, y en el mismo par da al líder por delante 39% a 35%.`,
  'quadroComparativo[2].m': `0,85% (vol USD 4,34M) en el contrato de ganador, ${S8}, una caída de 0,30pp. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 6,55pp y está en 52,00% (vol USD 129 mil).`,
  'quadroComparativo[2].t': `cede en los dos contratos y en las dos casas, y el único número a su favor es un par de segunda vuelta que la otra casa contradice por 6 puntos`,
  'quadroComparativo[2].s': `Hizo un acto en Río el 07/Sep, con un guiño a André Mendonça y un reclamo de investigación sobre el Supremo, según Folha de S.Paulo.`,

  'quadroComparativo[3].p': `La BTG/Nexus del 08/Sep lo mide en 4% en la ${G('primera vuelta', 'primeiro-turno')}, contra 3% el 31/Ago, y lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} por 47% a 39%. La Quaest del 07/Sep lo mantiene en 3% y da 42% a 37%.`,
  'quadroComparativo[3].m': `1,30% (vol USD 12,83M) en el contrato de ganador, ${S8}, una caída de 0,25pp. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 5,00pp y está en 29,50% (vol USD 282 mil).`,
  'quadroComparativo[3].t': `subió 5,00pp en el libro de tercer lugar y deshizo la caída de la víspera, en el mismo movimiento en que Augusto Cury cedió 6,55pp`,
  'quadroComparativo[3].s': `Lanzó un manifiesto en un acto en Ibirapuera el 07/Sep y pidió la prisión de Alexandre de Moraes y Dias Toffoli, según Folha de S.Paulo.`,

  'quadroComparativo[4].p': `La BTG/Nexus del 08/Sep lo mide en 4% en la ${G('primera vuelta', 'primeiro-turno')} y lo da perdiendo la ${G('segunda vuelta', 'segundo-turno')} por 46% a 43%, el menor margen entre los tres pares en que esa casa da la victoria al líder. La Quaest del 07/Sep lo mide en 3% y da 41% a 38%.`,
  'quadroComparativo[4].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} subió 0,50pp y está en 10,00% (vol USD 115 mil), ${S8}.`,
  'quadroComparativo[4].t': `sube en el libro de tercer lugar y tiene, en las dos casas, el par de segunda vuelta más ajustado después del que involucra al segundo`,
  'quadroComparativo[4].s': `Sin acto individual nuevo el 08/Sep en las noticias recogidas.`,

  'quadroComparativo[5].p': `La BTG/Nexus del 08/Sep lo mide en 3% en el escenario de ${G('primera vuelta', 'primeiro-turno')} que lo incluye y la Quaest del 07/Sep en 1%. Está inhabilitado, y el Tribunal Superior Electoral tiene hasta el 14/Sep para juzgar los registros de los candidatos presidenciales.`,
  'quadroComparativo[5].m': `Por debajo de 0,5% en el contrato de ganador, que es el piso de la doble lectura, y esta ronda no publica precio nuevo para él en ese libro. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 0,10pp y está en 1,75% (vol USD 48 mil), ${S8}.`,
  'quadroComparativo[5].t': `aparece en 3% y en 1% en los escenarios que lo incluyen, y solo en la BTG/Nexus su inclusión mueve al segundo, de 35% a 34%`,
  'quadroComparativo[5].s': `Sin acto individual nuevo el 08/Sep en las noticias recogidas.`,
})
