/** Mapa EN: analysis-criteriosa, rodada de 08/Set/2026. Pesquisa e preço andam para o MESMO lado pela primeira vez na janela. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S8 = 'confirmed reading of 08/Sep, 12:00 BRT'
const S7 = 'confirmed reading of 07/Sep'

construir('analysis-criteriosa', 'en', {
  'subtitle': `Cross-reading of 8 September 2026, ${S8} (15:00 UTC), with the presidential book at USD 145.26M. In this round ALL FIVE books received a new price, which had not happened since 06/Sep. Two national polls entered the base: Quaest of 07/Sep, registration BR-01720/2026, and BTG/Nexus of 08/Sep, registration BR-06790/2026.`,

  'cruzamento': `After two days pointing in opposite directions, the two measurements on this page moved the same way, and the movement is large on both sides. ⭐ THE WINNER CONTRACT CLOSED THE GAP FROM 18.05pp TO 10.65pp: Lula gave up 3.00pp to 54.50% (vol USD 10.13M) and Flávio Bolsonaro rose 4.40pp to 43.85% (vol USD 9.91M), with USD 660 thousand of fresh money in the presidential book since the ${S7}. ⭐ AND THE THREE MOST RECENT NATIONAL POLLS ALL POINT THE SAME WAY IN THE ${G('RUNOFF', 'segundo-turno')}: BTG/Nexus of 08/Sep puts Flávio Bolsonaro ahead by 46% to 45%, Quaest of 07/Sep records a tie at 41% to 41%, and Veritá of 06/Sep gave 48.5% to 43.1%. The two before them went the other way, with Datafolha of 03/Sep at 46% to 44% and Quaest of 02/Sep at 42% to 41%, both in Lula's favour. ⚠️ AND THE ${G('FIRST ROUND', 'primeiro-turno')} DOES NOT FOLLOW THE RUNOFF. With fieldwork that all but overlaps, the three houses disagree on the size of the leader's advantage: 7 points at Quaest, 4 points at BTG/Nexus in the scenario without Pablo Marçal, and Veritá put the runner-up 0.5 point ahead. That is 7.5 points of spread between houses on the same question, and it is wider than any of their three margins of error, which are 2 points each. 📌 The two quantities do not subtract from one another, because the poll measures declared voting intention and the contract measures the implied probability of winning the election. Today they rank the race the same way, and the page records that without arbitrating. 🏛️ Two institutional acts entered the window: André Mendonça removed the director general of the Federal Police and the intelligence director for 90 days, and the Second Panel formed a majority behind the rapporteur before Gilmar Mendes asked for more time to review, which SUSPENDED the judgment. ⚠️ Over the same stretch the contract on a ${G('Supreme Court', 'stf')} justice leaving by impeachment gave up 1.15pp to 7.45%.`,

  'candidates[0].header': `PRICE: 54.50% (vol USD 10.13M accumulated) in the winner contract, ${S8}, a fall of 3.00pp against the ${S7}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he stands at 9.70% (vol USD 480 thousand). POLL: 39% in the first round of BTG/Nexus of 08/Sep and 45% against 46% in the ${G('runoff', 'segundo-turno')} of the same round; 36% in the first round of Quaest of 07/Sep and a tie at 41% to 41% in the runoff.`,
  'candidates[0].fortes[0]': `He is still ahead in the ${G('first round', 'primeiro-turno')} in both national polls that entered: 39% against 35% at BTG/Nexus of 08/Sep, in the scenario without Pablo Marçal, and 36% against 29% at Quaest of 07/Sep.`,
  'candidates[0].fortes[1]': `BTG/Nexus has him winning three of the five ${G('runoff', 'segundo-turno')} pairings it tested: 46% to 43% against Ronaldo Caiado, 47% to 40% against Romeu Zema and 47% to 39% against Renan Santos.`,
  'candidates[0].fortes[2]': `Both houses measure his rejection below that of the runner-up: 53% against 55% at Quaest and 49% against 50% at BTG/Nexus.`,
  'candidates[0].fracos[0]': `He gave up 3.00pp in the winner contract and the gap over the runner-up fell from 18.05pp to 10.65pp, after two consecutive sessions of widening.`,
  'candidates[0].fracos[1]': `BTG/Nexus of 08/Sep places him behind in the ${G('runoff', 'segundo-turno')} by 46% to 45%, and Quaest of 07/Sep records a tie at 41% to 41%. Added to Veritá of 06/Sep, that is three national polls in a row without handing him the pairing.`,
  'candidates[0].fracos[2]': `Government approval fell inside Quaest itself, from 45% against 48% on 02/Sep to 43% against 50% now, and BTG/Nexus measures 45% against 50% in the same week. The two houses arrive at exactly the same disapproval figure.`,
  'candidates[0].analise': `8 September is the first day of this window in which the poll and the price move the same way, and the movement is large in both. The winner contract gave up 3.00pp to 54.50% (vol USD 10.13M), with the gap over the runner-up falling from 18.05pp to 10.65pp. Over the same stretch two national polls entered and both shorten the race: BTG/Nexus places him behind by 46% to 45% in the ${G('runoff', 'segundo-turno')} and Quaest records a tie at 41% to 41%. ⚠️ The ${G('first round', 'primeiro-turno')} of those same two houses tells another story, because there he is still ahead by 4 and by 7 points. What the page records is that the two measurements agreed on direction and did not agree on size, and that the disagreement between the houses about the first round is wider than the margin of error they declare.`,

  'candidates[1].header': `PRICE: 43.85% (vol USD 9.91M accumulated) in the winner contract, ${S8}, a rise of 4.40pp against the ${S7}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 1.00pp to 88.50% (vol USD 644 thousand). POLL: 35% in the first round of BTG/Nexus of 08/Sep in the scenario without Pablo Marçal and 46% against 45% in the ${G('runoff', 'segundo-turno')}; 29% in the first round of Quaest of 07/Sep and a tie at 41% to 41% in the runoff.`,
  'candidates[1].fortes[0]': `He rose 4.40pp in the winner contract, the largest movement of the round, and closed the gap to the leader from 18.05pp to 10.65pp.`,
  'candidates[1].fortes[1]': `BTG/Nexus of 08/Sep puts him ahead in the ${G('runoff', 'segundo-turno')} by 46% to 45%. It is the third national poll in a row not to hand the pairing to the leader, after Quaest of yesterday, which gave a tie, and Veritá of 06/Sep.`,
  'candidates[1].fortes[2]': `At Quaest he did not move in the ${G('first round', 'primeiro-turno')}, holding 29% across two consecutive rounds of the house, while the leader gave up 1 point, from 37% to 36%.`,
  'candidates[1].fracos[0]': `He gave up 1.00pp in the ${G('first-round', 'primeiro-turno')} runner-up contract and stands at 88.50% (vol USD 644 thousand), with USD 32 thousand of fresh money in that book.`,
  'candidates[1].fracos[1]': `In the first round he is still behind in both national polls that entered: 35% against 39% at BTG/Nexus, scenario without Pablo Marçal, and 29% against 36% at Quaest.`,
  'candidates[1].fracos[2]': `Both houses measure his rejection above the leader's: 55% against 53% at Quaest and 50% against 49% at BTG/Nexus.`,
  'candidates[1].analise': `The round of 8 September hands him the largest price movement of the day and the most favourable poll result of the window, and this time the two point the same way. The winner contract rose 4.40pp to 43.85% (vol USD 9.91M) and the gap to the leader fell from 18.05pp to 10.65pp. BTG/Nexus of today puts him ahead in the ${G('runoff', 'segundo-turno')} by 46% to 45%, a distance that fits inside the margin of 2 points and is therefore a ${G('statistical tie', 'empate-tecnico')}, and Quaest of yesterday records a numerical tie at 41% to 41%. ⚠️ The ${G('first round', 'primeiro-turno')} of those same two houses leaves him 4 and 7 points behind, and that is the distance the page records without trying to close it. In the series recorded since 14/Apr his winner contract runs from 22.00% to 45.50%, and today's reading sits inside that band.`,

  'candidates[2].header': `PRICE: 0.85% (vol USD 4.34M accumulated) in the WINNER contract, ${S8}, a fall of 0.30pp. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he gave up 6.55pp to 52.00% (vol USD 129 thousand). POLL: 9% in the first round of BTG/Nexus of 08/Sep and 8% in that of Quaest of 07/Sep.`,
  'candidates[2].fortes[0]': `⭐ BTG/Nexus of 08/Sep tests him in a ${G('runoff', 'segundo-turno')} against the leader and puts him numerically ahead, by 45% to 43%, inside the margin of 2 points. Quaest of 07/Sep tests the same pairing and puts the leader ahead by 39% to 35%.`,
  'candidates[2].fortes[1]': `He is still the third-placed name in both national polls that entered, with 9% at BTG/Nexus and 8% at Quaest, ahead of the fourth-placed name in both.`,
  'candidates[2].fortes[2]': `The ${G('first-round', 'primeiro-turno')} third-place contract is still his, with 52.00% against 29.50% for the second name in that book.`,
  'candidates[2].fracos[0]': `He gave up 6.55pp in the ${G('first-round', 'primeiro-turno')} third-place contract, handing back with room to spare the 2.35pp rise of the previous round.`,
  'candidates[2].fracos[1]': `Both houses measure him falling inside their own series: Quaest takes him from 10% on 02/Sep to 8%, and BTG/Nexus from 11% on 31/Aug to 9%.`,
  'candidates[2].fracos[2]': `In the contract on winning the election he gave up 0.30pp to 0.85%, 0.05pp above the floor of his series, which begins on 27/Aug and runs from 0.80% to 5.00%.`,
  'candidates[2].analise': `The three gauges that touch him all point down in this round. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 6.55pp to 52.00% (vol USD 129 thousand); Quaest takes him from 10% to 8% and BTG/Nexus from 11% to 9%, each inside its own series; and in the contract on winning the election he gave up 0.30pp to 0.85%, 0.05pp above the floor of his series. ⭐ And one figure runs the other way, in a ${G('runoff', 'segundo-turno')} pairing: BTG/Nexus puts him ahead of the leader by 45% to 43%, while Quaest, in the same week and in the same pairing, puts the leader ahead by 39% to 35%. That is 6 points of difference between two houses on the same question, and the panel records both without choosing.`,

  'candidates[3].header': `PRICE: 1.30% (vol USD 12.83M accumulated) in the winner contract, ${S8}, a fall of 0.25pp. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he rose 5.00pp to 29.50% (vol USD 282 thousand). POLL: 4% in the first round of BTG/Nexus of 08/Sep and 3% in that of Quaest of 07/Sep.`,
  'candidates[3].fortes[0]': `He rose 5.00pp in the ${G('first-round', 'primeiro-turno')} third-place contract and undid the 1.50pp fall of the previous round, in the same book where Augusto Cury gave up 6.55pp.`,
  'candidates[3].fortes[1]': `BTG/Nexus of 08/Sep measures him at 4% in the first round, against 3% the same house measured on 31/Aug.`,
  'candidates[3].fortes[2]': `He still carries the largest accumulated volume among the names above the 0.5% floor in the winner contract, USD 12.83M, above the leader's and the runner-up's.`,
  'candidates[3].fracos[0]': `He gave up 0.25pp in the winner contract to 1.30%, 0.10pp above the floor of his series, which runs from 1.20% to 17.90% since 14/Apr.`,
  'candidates[3].fracos[1]': `Quaest of 07/Sep keeps him at 3% in the ${G('first round', 'primeiro-turno')}, the same as the house's round on 02/Sep.`,
  'candidates[3].fracos[2]': `In the ${G('runoff', 'segundo-turno')} pairings both houses have him losing comfortably: 47% to 39% at BTG/Nexus and 42% to 37% at Quaest.`,
  'candidates[3].analise': `The ${G('first-round', 'primeiro-turno')} third-place book undid in one day the movement of the previous round. He rose 5.00pp to 29.50% (vol USD 282 thousand), while Augusto Cury gave up 6.55pp, exactly the reverse of what the two did on 07/Sep. ⚠️ The book is thin, with USD 282 thousand and USD 129 thousand accumulated on those two names, against USD 145.26M in the presidential one, and a large movement in a thin book calls for a more cautious reading. In the contract on winning the election he gave up 0.25pp to 1.30%, 0.10pp above the floor of the series, in a contract whose accumulated volume is the largest among the names above the publication floor.`,

  'candidates[4].header': `PRICE: all three remain below the 0.5% floor in the WINNER contract, and this round publishes no new price for them in that book. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE one, ${S8}: Ronaldo Caiado rose 0.50pp to 10.00% (vol USD 115 thousand) and Romeu Zema is unchanged at 0.85% (vol USD 51 thousand). POLL: Caiado 4% and Zema 1% in the first round of BTG/Nexus of 08/Sep, scenario without Pablo Marçal, and Caiado 3% and Zema 2% in that of Quaest of 07/Sep.`,
  'candidates[4].subtitle': `The trailing pack in the ${S8} (15:00 UTC). ⚠️ THE TWO NATIONAL POLLS THAT ENTERED MEASURE CAIADO AT 4% AND 3% AND ZEMA AT 1% AND 2% IN THE ${G('FIRST ROUND', 'primeiro-turno')}, differences that fit inside each house's margin of 2 points. In the first-round third-place book, which received a new price in this round, the two moved in different directions: Caiado rose 0.50pp and Zema stayed put.`,
  'candidates[4].caiado.label': `CAIADO (PSD), 0.15% (vol USD 7.25M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he rose 0.50pp to 10.00%, in a book of USD 115 thousand, ${S8} (15:00 UTC).`,
  'candidates[4].caiado.fortes': `⭐ IN BOTH HOUSES OF THE WEEK HE HAS THE TIGHTEST ${G('RUNOFF', 'segundo-turno')} PAIRING AFTER THE ONE INVOLVING THE RUNNER-UP: 46% to 43% at BTG/Nexus of 08/Sep, the smallest margin among the three pairings in which that house hands the leader the win, and 41% to 38% at Quaest of 07/Sep. And he rose 0.50pp in the first-round third-place contract, back to 10.00%.`,
  'candidates[4].caiado.fracos': `⚠️ In the WINNER contract he remains below the 0.5% floor, and it is the only one of the three universes in which he does not move. In the ${G('first round', 'primeiro-turno')} the two houses measure him at 4% and 3%, with no meaningful change against their previous rounds.`,
  'candidates[4].haddad.fortes': `He is not tested as a presidential candidate in the national polls of the window, and neither BTG/Nexus of 08/Sep nor Quaest of 07/Sep tests him, so there is no ballot-box reading to cross against the price.`,
  'candidates[4].zema.label': `ZEMA (Novo), 0.15% (vol USD 6.65M) in the WINNER contract, below the 0.5% floor of the double reading, and this round publishes no new price for him in that contract. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he is unchanged at 0.85%, in a book of USD 51 thousand, ${S8} (15:00 UTC).`,
  'candidates[4].zema.fortes': `BTG/Nexus of 08/Sep measures him at 2% in the ${G('first-round', 'primeiro-turno')} scenario that includes Pablo Marçal, against 1% in the scenario without him, and Quaest of 07/Sep measures him at 2%. The three readings fit inside each house's margin of 2 points.`,
  'candidates[4].zema.fracos': `⚠️ IN THE ${G('RUNOFF', 'segundo-turno')} PAIRINGS HE IS THE MOST COMFORTABLE FOR THE LEADER IN BOTH HOUSES: 47% to 40% at BTG/Nexus and 44% to 33% at Quaest, that is 7 and 11 points of distance. And he stayed put at 0.85% in the first-round third-place contract, behind Pablo Marçal, who stands at 1.75%.`,
  'candidates[4].fortes[0]': `Ronaldo Caiado rose 0.50pp in the ${G('first-round', 'primeiro-turno')} third-place book and is back at 10.00%, the third name in that book.`,
  'candidates[4].fortes[1]': `BTG/Nexus of 08/Sep has him losing the ${G('runoff', 'segundo-turno')} to the leader by 46% to 43%, the smallest margin among the three pairings in which that house hands the leader the win.`,
  'candidates[4].fortes[2]': `At Quaest of 07/Sep the ${G('runoff', 'segundo-turno')} pairing against him is the tightest after the one involving the runner-up: 41% to 38%.`,
  'candidates[4].fracos[0]': `None of the three receives a new price in the winner contract, because all three remain below the 0.5% floor of the double reading.`,
  'candidates[4].fracos[1]': `Romeu Zema did not move in the ${G('first-round', 'primeiro-turno')} third-place book and is unchanged at 0.85%, behind Pablo Marçal, who stands at 1.75%.`,
  'candidates[4].analise': `In the ${G('first-round', 'primeiro-turno')} third-place book, the only one in which two of them carry a price, Ronaldo Caiado rose 0.50pp to 10.00% and Romeu Zema stayed put at 0.85%. The two national polls that entered measure Caiado at 4% and 3% in the first round and Zema at 1% and 2%, differences that fit inside each house's margin of 2 points. ⭐ The Caiado figure that says most is the ${G('runoff', 'segundo-turno')} one: 46% to 43% at BTG/Nexus and 41% to 38% at Quaest, and in both houses he is the tightest pairing after the one involving the runner-up. In the contract on winning the election all three remain below the floor, and the page publishes no new price for them in that book.`,

  'quadroComparativo[0].p': `BTG/Nexus of 08/Sep (BR-06790/2026, fieldwork 04 to 07/Sep, n=2,002, margin of 2pp) measures him at 39% in the ${G('first round', 'primeiro-turno')}, in the scenario without Pablo Marçal, and places him behind by 46% to 45% in the ${G('runoff', 'segundo-turno')}. Quaest of 07/Sep (BR-01720/2026, fieldwork 03 to 06/Sep, n=2,004, margin of 2pp) gives 36% in the first round and a tie at 41% to 41% in the runoff.`,
  'quadroComparativo[0].m': `54.50% (vol USD 10.13M) in the winner contract, ${S8}, a fall of 3.00pp against the ${S7}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he stands at 9.70% (vol USD 480 thousand).`,
  'quadroComparativo[0].t': `gave up 3.00pp and the gap over the runner-up fell from 18.05pp to 10.65pp, on the same day two national polls shortened the race`,
  'quadroComparativo[0].s': `He gathered aides to discuss the response to André Mendonça's decision removing the director general of the Federal Police, and the institutional relations minister called the removal an intrusion, according to O Globo.`,

  'quadroComparativo[1].p': `BTG/Nexus of 08/Sep puts him ahead in the ${G('runoff', 'segundo-turno')} by 46% to 45%, inside the margin of 2 points, and measures him at 35% in the ${G('first round', 'primeiro-turno')} in the scenario without Pablo Marçal and at 34% in the scenario with him. Quaest of 07/Sep gives 29% in the first round and a tie at 41% to 41% in the runoff.`,
  'quadroComparativo[1].m': `43.85% (vol USD 9.91M) in the winner contract, ${S8}, a rise of 4.40pp against the ${S7}. In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 1.00pp to 88.50% (vol USD 644 thousand).`,
  'quadroComparativo[1].t': `rose 4.40pp, the largest movement of the round, and this is the third national poll in a row not to hand the runoff to the leader`,
  'quadroComparativo[1].s': `At the Avenida Paulista rally on 07/Sep he tied the leader to Alexandre de Moraes and said he would appoint five justices to the Supreme Court, according to JOTA, O Globo and Folha de S.Paulo.`,

  'quadroComparativo[2].p': `BTG/Nexus of 08/Sep measures him at 9% in the ${G('first round', 'primeiro-turno')}, against 11% in the same house's round on 31/Aug, and puts him numerically ahead of the leader in a ${G('runoff', 'segundo-turno')}, by 45% to 43%. Quaest of 07/Sep measures him at 8%, against 10% on 02/Sep, and in the same pairing puts the leader ahead by 39% to 35%.`,
  'quadroComparativo[2].m': `0.85% (vol USD 4.34M) in the winner contract, ${S8}, a fall of 0.30pp. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 6.55pp to 52.00% (vol USD 129 thousand).`,
  'quadroComparativo[2].t': `gives ground in both contracts and in both houses, and the only figure in his favour is a runoff pairing that the other house contradicts by 6 points`,
  'quadroComparativo[2].s': `He held a rally in Rio on 07/Sep, nodding to André Mendonça and calling for an investigation into the Supreme Court, according to Folha de S.Paulo.`,

  'quadroComparativo[3].p': `BTG/Nexus of 08/Sep measures him at 4% in the ${G('first round', 'primeiro-turno')}, against 3% on 31/Aug, and has him losing the ${G('runoff', 'segundo-turno')} by 47% to 39%. Quaest of 07/Sep keeps him at 3% and gives 42% to 37%.`,
  'quadroComparativo[3].m': `1.30% (vol USD 12.83M) in the winner contract, ${S8}, a fall of 0.25pp. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 5.00pp to 29.50% (vol USD 282 thousand).`,
  'quadroComparativo[3].t': `rose 5.00pp in the third-place book and undid the previous day's fall, in the same movement in which Augusto Cury gave up 6.55pp`,
  'quadroComparativo[3].s': `He launched a manifesto at a rally in Ibirapuera on 07/Sep and called for the arrest of Alexandre de Moraes and Dias Toffoli, according to Folha de S.Paulo.`,

  'quadroComparativo[4].p': `BTG/Nexus of 08/Sep measures him at 4% in the ${G('first round', 'primeiro-turno')} and has him losing the ${G('runoff', 'segundo-turno')} by 46% to 43%, the smallest margin among the three pairings in which that house hands the leader the win. Quaest of 07/Sep measures him at 3% and gives 41% to 38%.`,
  'quadroComparativo[4].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract he rose 0.50pp to 10.00% (vol USD 115 thousand), ${S8}.`,
  'quadroComparativo[4].t': `rises in the third-place book and has, in both houses, the tightest runoff pairing after the one involving the runner-up`,
  'quadroComparativo[4].s': `No new individual act on 08/Sep in the news collected.`,

  'quadroComparativo[5].p': `BTG/Nexus of 08/Sep measures him at 3% in the ${G('first-round', 'primeiro-turno')} scenario that includes him and Quaest of 07/Sep at 1%. He is barred from running, and the Superior Electoral Court has until 14/Sep to rule on the presidential candidacies.`,
  'quadroComparativo[5].m': `Below 0.5% in the winner contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 0.10pp to 1.75% (vol USD 48 thousand), ${S8}.`,
  'quadroComparativo[5].t': `shows up at 3% and at 1% in the scenarios that include him, and only at BTG/Nexus does his inclusion move the runner-up, from 35% to 34%`,
  'quadroComparativo[5].s': `No new individual act on 08/Sep in the news collected.`,
})
