/** Mapa EN: polls-data, rodada de 08/Set/2026. Entram a BTG/Nexus de 08/Set e a Quaest de 07/Set. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S8 = 'confirmed reading of 08/Sep, 12:00 BRT'
const S7 = 'confirmed reading of 07/Sep'

construir('polls-data', 'en', {
  'polls[0].note': `BTG/Nexus national poll released on 08/Sep, fieldwork from 04 to 07/Sep, registration BR-06790/2026 with the ${G('TSE', 'tse')}, 2,002 interviews by telephone on the CATI system, a margin of 2pp and 95% confidence, declared cost of R$ 164,888.89 (Poder360, Gazeta do Povo, Folha de S.Paulo, CNN Brasil, Metrópoles, JOTA, Estadão, VEJA, CartaCapital and Exame). ⭐ IT IS THE FIRST TIME THIS HOUSE HANDS THE ${G('RUNOFF', 'segundo-turno')} TO FLÁVIO BOLSONARO: 46% against 45% for Lula. ⚠️ The distance of 1 point fits entirely inside the margin of 2 points, so what the poll measures is a ${G('STATISTICAL TIE', 'empate-tecnico')} and not a lead. In the house's previous round, on 31/Aug (BR-08900/2026, fieldwork 28 to 30/Aug, n=2,005), the same pairing came out 46% to 45% for LULA, that is the same two figures with the sides swapped. ⭐ AND IT IS THE THIRD NATIONAL POLL IN A ROW NOT TO HAND THE PAIRING TO THE LEADER, after Quaest of 07/Sep, which gave a tie at 41% to 41%, and Veritá of 06/Sep, which gave 48.5% to 43.1%. The two before them went the other way: Datafolha of 03/Sep, 46% to 44%, and Quaest of 02/Sep, 42% to 41%, both for Lula. 🏷️ THE HOUSE PUBLISHED TWO PROMPTED ${G('FIRST-ROUND', 'primeiro-turno')} SCENARIOS AND BOTH ARE CORRECT, which explains why the press reported the runner-up with different figures: 35% in the scenario WITHOUT Pablo Marçal and 34% in the scenario WITH him, with the leader at 39% in both. Pablo Marçal is barred from running and the Superior Electoral Court has until 14/Sep to rule on the presidential candidacies. ⭐ AND THE RUNOFF WITH AUGUSTO CURY IS THE FIGURE THAT STANDS FURTHEST FROM THE BASE: the house puts him numerically ahead of the leader by 45% to 43%, and Quaest of 07/Sep, with fieldwork that all but overlaps, puts the leader ahead in the same pairing by 39% to 35%. That is 6 points of difference between two houses on the same question, and the panel records both without choosing. COMPARISON INSIDE THE HOUSE, which is the only valid one: in the first round without Marçal the leader held 39% for a second consecutive round and the runner-up rose from 33% to 35%, while Augusto Cury gave up from 11% to 9%. REJECTION: Flávio Bolsonaro 50% and Lula 49%, against 55% and 53% measured by Quaest in the same week, that is the two houses agree on the order and differ by 5 and 4 points on the level. GOVERNMENT APPROVAL: 45% approve and 50% disapprove, with 4% giving no answer, and on the management scale 36% excellent or good, 18% fair and 46% poor or terrible. ⚠️ The disapproval matches exactly the 50% Quaest measured on 07/Sep, and approval differs by 2 points. 📅 TODAY'S RELEASE WAS ALREADY IN THE CALENDAR PUBLISHED BY THE PANEL SINCE 03/Sep, with the expected date and the registration number matching what was published. 🏷️ The unprompted scenario released by the house is not in this entry because the panel could not confirm it in two independent sources.`,

  'polls[1].note': `Genial/Quaest national poll released on 07/Sep, fieldwork from 03 to 06/Sep, registration BR-01720/2026 with the ${G('TSE', 'tse')}, 2,004 respondents aged 16 or over, a margin of 2pp and 95% confidence (G1, O Globo, Folha de S.Paulo, Estadão, Valor Econômico, UOL, CNN Brasil, Gazeta do Povo, Poder360, Brasil de Fato, Band and Congresso em Foco). ⭐ THE ${G('RUNOFF', 'segundo-turno')} CAME OUT TIED AT 41% TO 41%, and it is the first time the house has not handed the pairing to the leader. Inside Quaest's own series the distance had been narrowing round by round: 5 points on 05/Aug (44% x 39%), 3 points on 14/Aug (43% x 40%), 1 point on 02/Sep (42% x 41%) and now zero. ⚠️ IN THE ${G('FIRST ROUND', 'primeiro-turno')} THE HOUSE STILL GIVES THE LEADER 7 POINTS, 36% against 29%, and that is the widest advantage among the three national polls with overlapping fieldwork: BTG/Nexus of 08/Sep gives 4 points and Veritá of 06/Sep put the runner-up 0.5 point ahead. That is 7.5 points of spread between houses on the same question, more than double the margin of error each one declares. COMPARISON INSIDE THE HOUSE: against the round of 02/Sep the leader gave up 1 point, from 37% to 36%, the runner-up stayed put at 29% and Augusto Cury gave up 2 points, from 10% to 8%. ⚠️ AUGUSTO CURY GIVES GROUND IN BOTH HOUSES OF THE WEEK, from 10% to 8% here and from 11% to 9% at BTG/Nexus, each one inside its own series. The house published two first-round scenarios, with and without Pablo Marçal, and the runner-up holds 29% in both, that is his inclusion does not move the top pairing. ⭐ AND THE RUNOFF AGAINST AUGUSTO CURY CONTRADICTS THE OTHER HOUSE OF THE WEEK: here the leader wins by 39% to 35%, and BTG/Nexus of 08/Sep puts Cury ahead by 45% to 43%. REJECTION: Flávio Bolsonaro 55% and Lula 53%, against 50% and 49% at BTG/Nexus, with the two houses agreeing on the order and differing on the level. GOVERNMENT APPROVAL: 43% approve and 50% disapprove. Inside the house itself it was 48% against 47% on 05/Aug, 46% against 48% on 14/Aug and 45% against 48% on 02/Sep, that is disapproval repeated 48% for three rounds and has now risen 2 points. 📅 THIS MONDAY'S RELEASE WAS ALREADY IN THE ${G('TSE', 'tse')} REGISTRY ingested by the panel, and on 07/Sep the page recorded that up to that round's capture it still carried no figures. It came out afterwards, and this entry is the record of it.`,

  'approvalData.note': `🏷️ THE STRUCTURED FIGURES IN THIS BLOCK BECOME THOSE OF GENIAL/QUAEST OF 07/Sep, and they are: 43% approval against 50% disapproval. The panel keeps ONE house per block by design, and because the new round comes from the same house the internal series is preserved in full. ⚠️ INSIDE QUAEST ITSELF THE STILLNESS IS OVER: it was 48% approval against 47% disapproval on 05/Aug, 46% against 48% on 14/Aug and 45% against 48% on 02/Sep. Disapproval had repeated 48% for three consecutive rounds and has now risen 2 points, over the same stretch in which approval gave up 2. ⭐ AND BTG/NEXUS OF 08/Sep, FROM ANOTHER HOUSE AND WITH OVERLAPPING FIELDWORK, ARRIVES AT EXACTLY THE SAME DISAPPROVAL: 45% approval and 50% disapproval, with 4% giving no answer, and on the management scale 36% excellent or good, 18% fair and 46% poor or terrible. The two houses coincide at 50% on disapproval and differ by 2 points on approval, and the panel records both without adding them together. Datafolha of 03/Sep, which measured 45% and 51%, remains recorded with its date of origin.`,

  'polymarketComparison.note': `Polymarket prices with the presidential book at USD 145.26M, ${S8} (15:00 UTC). ⭐ IN THIS ROUND ALL FIVE BOOKS RECEIVED A NEW PRICE, which had not happened since 06/Sep: winner, ${G('first-round', 'primeiro-turno')} runner-up, first-round third place, ${G('Supreme Court', 'stf')} impeachment and Senate majority. ⭐ AND THE POLL AND THE PRICE MOVED THE SAME WAY FOR THE FIRST TIME IN THIS WINDOW: the winner contract closed the gap from 18.05pp to 10.65pp, with Lula giving up 3.00pp to 54.50% and Flávio Bolsonaro rising 4.40pp to 43.85%, and the two national polls that entered shorten the race, with BTG/Nexus of 08/Sep giving the runner-up the ${G('runoff', 'segundo-turno')} by 46% to 45% and Quaest of 07/Sep recording a tie at 41% to 41%. ⚠️ THE FIRST ROUND DOES NOT FOLLOW: the three houses with overlapping fieldwork give the leader 7, 4 and minus 0.5 point of advantage, a spread of 7.5 points between houses. 📌 The two quantities do not subtract from one another, because one is declared voting intention and the other is the implied probability of winning the election. Today they rank the race the same way, and the page records that without arbitrating between them.`,

  'polymarketComparison.sources': `Polymarket prices via the AFOS proxy, and the panel publishes only prices that two independent readings, taken eight minutes apart, confirm within 0.20pp. Confirmation is done contract by contract, and on 08/Sep all five books confirmed. Polls registered with the ${G('TSE', 'tse')} and released by the institutes, with reporting from Poder360, Gazeta do Povo, G1, Folha de S.Paulo, O Globo, Estadão, Valor Econômico, CNN Brasil, Metrópoles, JOTA, VEJA, CartaCapital, Exame, UOL, Band, Brasil de Fato and Congresso em Foco. The calendar of polls in the field and of scheduled releases comes from the official TSE registry. Series superlatives checked against the Neon backup, in backup/neon/marketPrice, which holds the complete record since 14/Apr.`,

  'polymarketComparison.candidates[0].polymarket': `54.50%`,
  'polymarketComparison.candidates[0].pesquisaRange': `36% to 39%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `BTG/Nexus of 08/Sep (BR-06790/2026, fieldwork 04 to 07/Sep, n=2,002, margin of 2pp) measures him at 39% in the ${G('first round', 'primeiro-turno')}, in the scenario without Pablo Marçal, and places him BEHIND in the ${G('runoff', 'segundo-turno')} by 46% to 45%. Quaest of 07/Sep (BR-01720/2026, fieldwork 03 to 06/Sep, n=2,004) gives 36% in the first round and a tie at 41% to 41% in the runoff. ⭐ With Veritá of 06/Sep, that is three national polls in a row without handing him the win in the pairing, against Datafolha of 03/Sep (46% to 44%) and Quaest of 02/Sep (42% to 41%), both in his favour. Government approval is 43% against 50% at Quaest and 45% against 50% at BTG/Nexus.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `54.50% (vol USD 10.13M) in the winner contract, ${S8}, a fall of 3.00pp against the ${S7}. The gap over the runner-up fell from 18.05pp to 10.65pp, after two consecutive sessions of widening, with USD 660 thousand of fresh money in the presidential book. In the ${G('first-round', 'primeiro-turno')} runner-up contract he stands at 9.70% (vol USD 480 thousand).`,

  'polymarketComparison.candidates[1].polymarket': `43.85%`,
  'polymarketComparison.candidates[1].pesquisaRange': `29% to 35%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `BTG/Nexus of 08/Sep puts him AHEAD in the ${G('runoff', 'segundo-turno')} by 46% to 45%, a distance that fits inside the margin of 2 points and is therefore a ${G('statistical tie', 'empate-tecnico')}, and it is the first time that house has done so: in its round of 31/Aug the same pairing came out 46% to 45% the other way. In the ${G('first round', 'primeiro-turno')} the house measures him at 35% in the scenario without Pablo Marçal and at 34% in the scenario with him. Quaest of 07/Sep gives 29% in the first round, the same as 02/Sep, and a tie at 41% to 41% in the runoff. ⚠️ Both houses measure his rejection above the leader's: 55% against 53% at Quaest and 50% against 49% at BTG/Nexus.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `43.85% (vol USD 9.91M) in the winner contract, ${S8}, a rise of 4.40pp against the ${S7}, the largest movement of the round. In the ${G('first-round', 'primeiro-turno')} runner-up contract he gave up 1.00pp to 88.50% (vol USD 644 thousand). In the series recorded since 14/Apr his winner contract runs from 22.00% to 45.50%, and today's reading sits inside that band.`,

  'polymarketComparison.candidates[2].polymarket': `0.85%`,
  'polymarketComparison.candidates[2].pesquisaRange': `8% to 9%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `⚠️ HE GIVES GROUND IN BOTH HOUSES OF THE WEEK, each one inside its own series: Quaest takes him from 10% on 02/Sep to 8%, and BTG/Nexus from 11% on 31/Aug to 9%. ⭐ AND ONE FIGURE RUNS THE OTHER WAY: BTG/Nexus puts him numerically ahead of the leader in a ${G('runoff', 'segundo-turno')}, by 45% to 43%, while Quaest, in the same week and in the same pairing, puts the leader ahead by 39% to 35%. That is 6 points of difference between two houses on the same question, and the panel records both without choosing.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `0.85% (vol USD 4.34M) in the WINNER contract, ${S8}, a fall of 0.30pp, 0.05pp above the floor of his series, which begins on 27/Aug and runs from 0.80% to 5.00%. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract, which is a different market, he gave up 6.55pp to 52.00% (vol USD 129 thousand), handing back with room to spare the 2.35pp rise of the day before.`,

  'polymarketComparison.candidates[3].polymarket': `1.30%`,
  'polymarketComparison.candidates[3].pesquisaRange': `3% to 4%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `BTG/Nexus of 08/Sep measures him at 4% in the ${G('first round', 'primeiro-turno')}, against 3% the same house measured on 31/Aug, and Quaest of 07/Sep keeps him at 3%, the same as 02/Sep. In the ${G('runoff', 'segundo-turno')} pairings both houses have him losing comfortably: 47% to 39% at BTG/Nexus and 42% to 37% at Quaest.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.30% (vol USD 12.83M) in the winner contract, ${S8}, a fall of 0.25pp, 0.10pp above the floor of his series, which runs from 1.20% to 17.90% since 14/Apr. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he rose 5.00pp to 29.50% (vol USD 282 thousand), undoing the 1.50pp fall of the day before. He still carries the largest accumulated volume among the names above the publication floor in the winner contract.`,

  'polymarketComparison.candidates[4].pesquisaRange': `3% to 4%`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `BTG/Nexus of 08/Sep measures him at 4% in the ${G('first round', 'primeiro-turno')} and has him losing the ${G('runoff', 'segundo-turno')} by 46% to 43%, the smallest margin among the three pairings in which that house hands the leader the win. Quaest of 07/Sep measures him at 3% and gives 41% to 38%, its tightest pairing after the one involving the runner-up.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `Below 0.5% in the WINNER contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he rose 0.50pp to 10.00% (vol USD 115 thousand), ${S8}.`,

  'polymarketComparison.candidates[5].pesquisaRange': `1% to 3%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `BTG/Nexus of 08/Sep measures him at 3% in the ${G('first-round', 'primeiro-turno')} scenario that includes him and Quaest of 07/Sep at 1%. ⚠️ Only at BTG/Nexus does his inclusion move the top pairing, taking the runner-up from 35% to 34%; at Quaest the runner-up holds 29% in both scenarios. He is barred from running, and the Superior Electoral Court has until 14/Sep to rule on the presidential candidacies.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `Below 0.5% in the WINNER contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he gave up 0.10pp to 1.75% (vol USD 48 thousand), ${S8}.`,

  'polymarketComparison.candidates[6].pesquisaRange': `1% to 2%`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `BTG/Nexus of 08/Sep measures him at 1% in the scenario without Pablo Marçal and at 2% in the scenario with him, and Quaest of 07/Sep at 2%. The differences fit inside each house's margin of 2 points. In the ${G('runoff', 'segundo-turno')} pairings he is the most comfortable of the two: 47% to 40% at BTG/Nexus and 44% to 33% at Quaest.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `Below 0.5% in the WINNER contract, which is the floor of the double reading, and this round publishes no new price for him in that book. In the ${G('first-round', 'primeiro-turno')} THIRD-PLACE contract he is unchanged at 0.85% (vol USD 51 thousand), ${S8}.`,

  'polymarketComparison.candidates[7].tendenciaPesquisa': `Neither of the two national polls that entered on 07 and 08/Sep tests him in a presidential scenario. He is running for re-election in São Paulo.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `Below 0.5% in the WINNER contract, which is the floor of the double reading, and this round publishes no new price for him. His book is the largest on the panel by accumulated volume in a contract that pays 0.05%, and that combination is the signature of a market that has already settled the question.`,

  'polymarketComparison.candidates[8].tendenciaPesquisa': `Neither of the two national polls that entered on 07 and 08/Sep tests him in a presidential scenario. He is not a presidential candidate: he is running for the government of São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `Below 0.5% in the WINNER contract, which is the floor of the double reading, and this round publishes no new price for him. His presidential price is book residue, not a measure of a campaign.`,
})
