/** Mapa EN: analysis-data, rodada de 08/Set/2026. Cinco livros com preço novo e a crise do Supremo vira ato institucional. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S8 = 'confirmed reading of 08/Sep, 12:00 BRT'
const S7 = 'confirmed reading of 07/Sep'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 145.26M and the prices on this page come from the ${S8} (15:00 UTC). ⭐ IN THIS ROUND ALL FIVE BOOKS RECEIVED A NEW PRICE, which had not happened since 06/Sep: winner, ${G('first-round', 'primeiro-turno')} runner-up, first-round third place, ${G('Supreme Court', 'stf')} impeachment and Senate majority. The AFOS publishes only prices that two independent readings confirm.`,

  'cards.sentimento.text2': `⭐ THE POLL AND THE PRICE MOVED THE SAME WAY FOR THE FIRST TIME IN THIS WINDOW, after two days pointing in opposite directions. The winner contract closed the gap from 18.05pp to 10.65pp: Lula gave up 3.00pp to 54.50% and Flávio Bolsonaro rose 4.40pp to 43.85%, with USD 660 thousand of fresh money in the book since the ${S7}. Over the same stretch two national polls entered and both shorten the race: BTG/Nexus of 08/Sep gives Flávio Bolsonaro the ${G('runoff', 'segundo-turno')} by 46% to 45% and Quaest of 07/Sep records a tie at 41% to 41%. With Veritá of 06/Sep, that is three national polls in a row not handing the pairing to the leader. 📌 The two quantities do not subtract from one another, because one is declared voting intention and the other is the implied probability of winning the election. Today they rank the race the same way, and the page records that without arbitrating.`,

  'cards.sentimento.text3': `⚠️ THE ${G('FIRST ROUND', 'primeiro-turno')} DOES NOT FOLLOW THE RUNOFF, AND THAT IS WHERE THE HOUSES DISAGREE MOST. With fieldwork that all but overlaps, Quaest gives the leader a 7-point advantage, BTG/Nexus gives 4 points in the scenario without Pablo Marçal and Veritá of 06/Sep put the runner-up 0.5 point ahead. That is 7.5 points of spread between houses on the same question, more than double the margin of error each one declares. ⭐ AND THE THIRD-PLACE BOOK UNDID IN ONE DAY THE MOVEMENT OF THE DAY BEFORE: Augusto Cury gave up 6.55pp to 52.00%, after rising 2.35pp on 07/Sep, and Renan Santos rose 5.00pp to 29.50%, after giving up 1.50pp. The two moved in the same market and in opposite directions for the second day running, now with the roles reversed.`,

  'cards.sentimento.direita': `Flávio Bolsonaro at 43.85% (vol USD 9.91M accumulated) in the winner contract, ${S8}, a rise of 4.40pp against the ${S7}, the largest movement of the round. ⭐ AND THIS TIME THE PRICE MOVED IN THE SAME DIRECTION AS THE POLL: BTG/Nexus of 08/Sep puts him ahead in the ${G('runoff', 'segundo-turno')} by 46% to 45%, a distance that fits inside the margin of 2 points and is therefore a ${G('statistical tie', 'empate-tecnico')}, and Quaest of 07/Sep records a numerical tie at 41% to 41%. ⚠️ In the ${G('first round', 'primeiro-turno')} of those same two houses he is still behind, with 35% against 39% at BTG/Nexus and 29% against 36% at Quaest. In the first-round runner-up contract he gave up 1.00pp to 88.50% (vol USD 644 thousand).`,

  'cards.sentimento.esquerda': `Lula at 54.50% (vol USD 10.13M accumulated) in the winner contract, ${S8}, a fall of 3.00pp against the ${S7}. ⚠️ THE GAP OVER THE RUNNER-UP FELL FROM 18.05pp TO 10.65pp, after two consecutive sessions of widening. The two national polls that entered point the same way: 46% to 45% against him in the ${G('runoff', 'segundo-turno')} at BTG/Nexus and a tie at 41% to 41% at Quaest. In the ${G('first round', 'primeiro-turno')} he is still ahead in both, by 4 and by 7 points. Government approval fell inside Quaest itself, from 45% against 48% on 02/Sep to 43% against 50% now, and BTG/Nexus measures 45% against 50%: the two houses arrive at the same disapproval figure. In the first-round runner-up contract he stands at 9.70% (vol USD 480 thousand).`,

  'cards.sentimento.terceiraVia': `⚠️ Augusto Cury gives ground in the three gauges that touch him. In the ${G('first-round', 'primeiro-turno')} third-place contract he gave up 6.55pp to 52.00% (vol USD 129 thousand), ${S8}, handing back with room to spare the 2.35pp rise of the day before. Quaest takes him from 10% on 02/Sep to 8% and BTG/Nexus from 11% on 31/Aug to 9%, each inside its own series. In the WINNER contract, which is a different market, he gave up 0.30pp to 0.85% (vol USD 4.34M), 0.05pp above the floor of his series. ⭐ AND ONE FIGURE RUNS THE OTHER WAY: BTG/Nexus puts him numerically ahead of the leader in a ${G('runoff', 'segundo-turno')}, by 45% to 43%, while Quaest, in the same week and in the same pairing, puts the leader ahead by 39% to 35%. That is 6 points of difference between two houses on the same question. ⚠️ Renan Santos went the other way in the third-place book, rising 5.00pp to 29.50% (vol USD 282 thousand), and Ronaldo Caiado rose 0.50pp to 10.00%.`,

  'cards.sentimento.polymarket': `Prices from the ${S8} (15:00 UTC). ⭐ The five books this page follows all received a new price in this round: winner, ${G('first-round', 'primeiro-turno')} runner-up, first-round third place, ${G('Supreme Court', 'stf')} impeachment and Senate majority. The AFOS publishes only prices that two independent readings confirm, and says so when there is none.`,

  'cards.inss.text1': `📌 THERE IS NO NEW INSS ACT ON 08/Sep. 🔴 AND THERE IS A DATE TRAP IN TODAY'S NEWS, which the page records rather than repeats: Folha de S.Paulo and Valor Econômico published on 08/Sep that the ${G('Supreme Court', 'stf')} ruled the INSS may set the interest-rate cap on payroll loans, and the judgment was completed in the virtual plenary on 28/Aug, with Nunes Marques as rapporteur and the banking association's request defeated. Today's stories are explanation and follow-up, not an act of the day, and the page records them with their date of origin.`,

  'cards.inss.impactoLula': `The structured reading of government approval becomes that of Genial/Quaest of 07/Sep, with fieldwork from 03 to 06/Sep: 43% approve and 50% disapprove. It is the same house as the previous round, so the internal series of the block is preserved. ⚠️ BTG/Nexus of 08/Sep measures 45% approval and 50% disapproval in the same week: the two houses arrive at exactly the same disapproval figure and differ by 2 points on approval.`,

  'cards.inss.impactoGestao': `Inside Quaest itself the picture is no longer one of stillness. It was 48% approval against 47% disapproval on 05/Aug, 46% against 48% on 14/Aug, 45% against 48% on 02/Sep and 43% against 50% on 07/Sep. Disapproval had repeated 48% for three consecutive rounds and has now risen 2 points, over the same stretch in which approval gave up 2.`,

  'cards.inss.conclusao': `What this round measures on the subject is narrow: there was no new INSS act on 08/Sep, and what changed was the government approval reading, which becomes that of Genial/Quaest of 07/Sep, with 43% approval against 50% disapproval. The distinction the panel has kept from the start still holds: what the government paid is one thing, what fell outside its count is another, and neither is to be confused with voting intention.`,

  'cards.bancoMaster.text1': `⚠️ THERE IS A NEW ACT ON 08/Sep, AND IT COMES FROM OUTSIDE THE CASE. In ordering the removal of the director general of the Federal Police, André Mendonça stated that the intelligence report cited by Alexandre de Moraes had tipped off new targets and damaged the Master case investigations, according to O Globo. The dispute over who controls the inquiry now carries, inside the court, accusations of a smokescreen and of a cover-up operation, according to G1. On 04/Sep the Prosecutor General's Office asked for authorisation to investigate suspected interference in the production of the Federal Police report, and that request still stands.`,

  'cards.bancoMaster.text2': `The Superior Council of the Federal Public Prosecutor's Office opened a procedure on 04/Sep to examine the references to Paulo Gonet in Daniel Vorcaro's messages, and it is the council that the prosecutor general himself chairs. One wing of the ${G('Supreme Court', 'stf')} argues that he should step aside from the case, according to O Globo, and the request for him to step aside was also made by a member of Congress, according to SBT News. ⚠️ Alexandre de Moraes and André Mendonça are to make submissions on the messages case by the end of the week, according to O Globo.`,

  'cards.bancoMaster.conclusao': `What changed on 08/Sep is that the case is no longer contained within itself: the decision that removed the Federal Police leadership expressly cites damage to the Master investigations, and the dispute over who controls the inquiry has become a dispute between justices. The earlier dates still stand, and both are from 04/Sep: the court president received the Prosecutor General's request and the Superior Council of the Federal Public Prosecutor's Office opened a procedure.`,

  'cards.stf.toffoli': `No new individual act on 08/Sep. He remains a target of the impeachment request filed by Renan Santos, alongside Alexandre de Moraes, and was cited again at the campaign events of 07/Sep, when Renan Santos called for the arrest of both, according to Folha de S.Paulo.`,

  'cards.stf.moraes': `No new individual act on 08/Sep. ⚠️ But the decision of the day is about the material he used: André Mendonça removed the director general of the Federal Police and the intelligence director and ordered an inquiry into the production of intelligence reports on judges, calling preposterous the reports used by Moraes, according to O Globo, Metrópoles and Gazeta do Povo. On 07/Sep he was the target of placards and effigies at the right-wing rallies in Brasília and on Avenida Paulista, according to Metrópoles, Gazeta do Povo and Valor Econômico.`,

  'cards.stf.gilmar': `⚠️ New act on 08/Sep: he asked for more time to review the case in the extraordinary virtual session of the Second Panel examining the removal of the director general of the Federal Police, five minutes after the session opened at 10am, which SUSPENDED the judgment, according to Metrópoles, Migalhas and Folha de S.Paulo. The proposed amendment to the court's internal rules that he put to Edson Fachin, barring the appointment of military and police officers to commissioned posts in justices' offices, is from 05/Sep and the page keeps it with its date of origin.`,

  'cards.stf.dino': `No new individual act on 08/Sep. His statement that the ${G('Supreme Court', 'stf')} is greater than anyone who sits on it is from 04/Sep, and the page keeps it with its date of origin.`,

  'cards.stf.mendonca': `⭐ NEW AND HIGH-IMPACT ACT ON 08/Sep: he ordered the precautionary removal for 90 days of Andrei Rodrigues, director general of the Federal Police, and of Leandro Almada da Costa, intelligence director, and ordered the internal affairs unit to open criminal and administrative inquiries into the production of intelligence reports on judges, according to Metrópoles, Gazeta do Povo, O Globo and Migalhas. In the decision he states that he was the target of systematic and illegal monitoring by Federal Police intelligence for more than 30 days, and that is his allegation, not an established fact. ⚠️ In the Second Panel virtual session opened at 10am, Nunes Marques and Luiz Fux brought forward their votes and formed a majority behind the rapporteur, but Gilmar Mendes asked for more time to review and the judgment is SUSPENDED, with Dias Toffoli's vote still outstanding. The Prosecutor General's request to investigate him, from 04/Sep, still stands.`,

  'cards.stf.nexo': `⚠️ THE SUPREME COURT CRISIS LEFT THE STREET AND BECAME AN INSTITUTIONAL ACT, AND THAT IS THE RECORD OF THE DAY. On 07/Sep it was in the campaign events; on 08/Sep one justice removed the leadership of the Federal Police, the Second Panel formed a majority behind the rapporteur and another justice suspended the judgment with a request for more time to review. Former presidents of the court called on Edson Fachin to act and spoke of the court's most acute crisis, and senators admit the chance of a justice being impeached, according to Folha de S.Paulo. 📌 The distinction the page kept until yesterday, between a campaign act about the court and an act of the court, stopped applying today: both exist, and the second one is new.`,

  'cards.stf.analise': `The contract on a ${G('Supreme Court', 'stf')} justice leaving by impeachment before 2027 gave up 1.15pp to 7.45% (vol USD 88 thousand), ${S8}. ⚠️ THE RECORD OF THE DAY IS THAT THE PRICE FELL ON THE DAY OF THE MOST CONCRETE INSTITUTIONAL ACT OF THE CRISIS: one justice removed the director general of the Federal Police for 90 days, the Second Panel formed a majority behind the rapporteur and a request for more time to review suspended the judgment, and the contract went down. In the series recorded since 14/Apr it runs from 2.10% to 19.30%, with the peak on 04/Sep, and today's reading sits inside that band. 📌 It is the smallest book on the panel by accumulated volume, and movement in a thin book calls for a more cautious reading than in the presidential one, which has accumulated USD 145.26M.`,
})
