/** Mapa ES: analysis-data, rodada de 08/Set/2026. Cinco libros con precio nuevo y la crisis del Supremo se vuelve acto institucional. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S8 = 'lectura confirmada del 08/Sep, 12:00 BRT'
const S7 = 'lectura confirmada del 07/Sep'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 145,26M y los precios de esta página son de la ${S8} (15:00 UTC). ⭐ EN ESTA RONDA LOS CINCO LIBROS RECIBIERON PRECIO NUEVO, algo que no ocurría desde el 06/Sep: ganador, segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, tercer lugar de la primera vuelta, impeachment en el ${G('Supremo', 'stf')} y mayoría en el Senado. El AFOS solo publica precio que dos lecturas independientes confirmen.`,

  'cards.sentimento.text2': `⭐ LA ENCUESTA Y EL PRECIO SE MOVIERON HACIA EL MISMO LADO POR PRIMERA VEZ EN ESTA VENTANA, después de dos días apuntando hacia lados opuestos. El contrato de ganador cerró la brecha de 18,05pp a 10,65pp: Lula cedió 3,00pp y está en 54,50% y Flávio Bolsonaro subió 4,40pp y está en 43,85%, con USD 660 mil de dinero nuevo en el libro desde la ${S7}. En el mismo intervalo entraron dos encuestas nacionales y las dos acortan la disputa: la BTG/Nexus del 08/Sep da a Flávio Bolsonaro la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45% y la Quaest del 07/Sep registra empate en 41% a 41%. Con la Veritá del 06/Sep, son tres encuestas nacionales seguidas sin dar el par al líder. 📌 Las dos magnitudes no se restan, porque una es intención de voto declarada y la otra es probabilidad implícita de ganar la elección. Hoy ordenan la disputa del mismo modo, y la página lo registra sin arbitrar.`,

  'cards.sentimento.text3': `⚠️ LA ${G('PRIMERA VUELTA', 'primeiro-turno')} NO ACOMPAÑA A LA SEGUNDA, Y AHÍ ES DONDE LAS CASAS MÁS DISCREPAN. Con trabajo de campo prácticamente superpuesto, la Quaest da 7 puntos de ventaja al líder, la BTG/Nexus da 4 puntos en el escenario sin Pablo Marçal y la Veritá del 06/Sep puso al segundo 0,5 punto por delante. Son 7,5 puntos de amplitud entre casas sobre la misma pregunta, más del doble del margen de error que cada una declara. ⭐ Y EL LIBRO DE TERCER LUGAR DESHIZO EN UN DÍA EL MOVIMIENTO DE LA VÍSPERA: Augusto Cury cedió 6,55pp y está en 52,00%, tras subir 2,35pp el 07/Sep, y Renan Santos subió 5,00pp y está en 29,50%, tras ceder 1,50pp. Los dos se movieron en el mismo mercado y en direcciones opuestas por segundo día seguido, ahora invirtiendo los papeles.`,

  'cards.sentimento.direita': `Flávio Bolsonaro en 43,85% (vol USD 9,91M acumulado) en el contrato de ganador, ${S8}, una subida de 4,40pp frente a la ${S7}, el mayor movimiento de la ronda. ⭐ Y ESTA VEZ EL PRECIO SE MOVIÓ EN LA MISMA DIRECCIÓN QUE LA ENCUESTA: la BTG/Nexus del 08/Sep lo pone por delante en la ${G('segunda vuelta', 'segundo-turno')} por 46% a 45%, distancia que cabe dentro del margen de 2 puntos y por lo tanto es ${G('empate técnico', 'empate-tecnico')}, y la Quaest del 07/Sep registra empate numérico en 41% a 41%. ⚠️ En la ${G('primera vuelta', 'primeiro-turno')} de esas mismas dos casas sigue por detrás, con 35% contra 39% en la BTG/Nexus y 29% contra 36% en la Quaest. En el contrato de segundo lugar de la primera vuelta cedió 1,00pp y está en 88,50% (vol USD 644 mil).`,

  'cards.sentimento.esquerda': `Lula en 54,50% (vol USD 10,13M acumulado) en el contrato de ganador, ${S8}, una caída de 3,00pp frente a la ${S7}. ⚠️ LA BRECHA SOBRE EL SEGUNDO CAYÓ DE 18,05pp A 10,65pp, tras dos jornadas seguidas de apertura. Las dos encuestas nacionales que entraron van en la misma dirección: 46% a 45% en su contra en la ${G('segunda vuelta', 'segundo-turno')} de la BTG/Nexus y empate en 41% a 41% en la Quaest. En la ${G('primera vuelta', 'primeiro-turno')} sigue por delante en las dos, por 4 y por 7 puntos. La aprobación del gobierno cayó dentro de la propia Quaest, de 45% contra 48% el 02/Sep a 43% contra 50% ahora, y la BTG/Nexus mide 45% contra 50%: las dos casas llegan a la misma desaprobación. En el contrato de segundo lugar de la primera vuelta está en 9,70% (vol USD 480 mil).`,

  'cards.sentimento.terceiraVia': `⚠️ Augusto Cury cede en los tres medidores que lo tocan. En el contrato de tercer lugar de la ${G('primera vuelta', 'primeiro-turno')} cedió 6,55pp y está en 52,00% (vol USD 129 mil), ${S8}, devolviendo con holgura la subida de 2,35pp de la víspera. La Quaest lo lleva de 10% el 02/Sep a 8% y la BTG/Nexus de 11% el 31/Ago a 9%, cada una dentro de su propia serie. En el contrato de GANADOR, que es otro mercado, cedió 0,30pp y está en 0,85% (vol USD 4,34M), a 0,05pp del piso de su serie. ⭐ Y UN NÚMERO VA EN LA DIRECCIÓN CONTRARIA: la BTG/Nexus lo da numéricamente por delante del líder en una ${G('segunda vuelta', 'segundo-turno')}, por 45% a 43%, mientras la Quaest, en la misma semana y en el mismo par, da al líder por delante 39% a 35%. Son 6 puntos de diferencia entre dos casas sobre la misma pregunta. ⚠️ Renan Santos hizo el camino inverso en el libro de tercer lugar, subiendo 5,00pp hasta 29,50% (vol USD 282 mil), y Ronaldo Caiado subió 0,50pp hasta 10,00%.`,

  'cards.sentimento.polymarket': `Precios de la ${S8} (15:00 UTC). ⭐ Los cinco libros que esta página sigue recibieron precio nuevo en esta ronda: ganador, segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, tercer lugar de la primera vuelta, impeachment en el ${G('Supremo', 'stf')} y mayoría en el Senado. El AFOS solo publica precio que dos lecturas independientes confirmen, y dice cuándo no lo hay.`,

  'cards.inss.text1': `📌 NO HAY ACTO NUEVO DEL INSS EL 08/Sep. 🔴 Y HAY UNA TRAMPA DE FECHA EN LAS NOTICIAS DE HOY, que la página registra en vez de repetir: Folha de S.Paulo y Valor Econômico publicaron el 08/Sep que el ${G('Supremo', 'stf')} decidió que el INSS puede fijar el techo de intereses del crédito con descuento en nómina, y el juicio se concluyó en el pleno virtual el 28/Ago, con ponencia de Nunes Marques y derrota del pedido de la asociación de bancos. Las noticias de hoy son explicación y repercusión, no acto del día, y la página las registra con su fecha de origen.`,

  'cards.inss.impactoLula': `La lectura estructurada de evaluación del gobierno pasa a ser la de la Genial/Quaest del 07/Sep, con campo del 03 al 06/Sep: 43% aprueban y 50% desaprueban. Es la misma casa de la ronda anterior, y por eso la serie interna del bloque se preserva. ⚠️ La BTG/Nexus del 08/Sep mide 45% de aprobación y 50% de desaprobación en la misma semana: las dos casas llegan exactamente a la misma desaprobación y difieren en 2 puntos en la aprobación.`,

  'cards.inss.impactoGestao': `Dentro de la propia Quaest el cuadro dejó de ser de inmovilidad. Eran 48% de aprobación contra 47% de desaprobación el 05/Ago, 46% contra 48% el 14/Ago, 45% contra 48% el 02/Sep y 43% contra 50% el 07/Sep. La desaprobación había repetido 48% durante tres rondas seguidas y ahora subió 2 puntos, en el mismo intervalo en que la aprobación cedió 2.`,

  'cards.inss.conclusao': `Lo que esta ronda mide sobre el tema es estrecho: no hubo acto nuevo del INSS el 08/Sep, y lo que cambió fue la lectura de evaluación del gobierno, que pasa a ser la de la Genial/Quaest del 07/Sep, con 43% de aprobación contra 50% de desaprobación. La distinción que el panel mantiene desde el inicio sigue valiendo: una cosa es lo que el gobierno pagó, otra es lo que quedó fuera de su cuenta, y ninguna de las dos se confunde con intención de voto.`,

  'cards.bancoMaster.text1': `⚠️ HAY ACTO NUEVO EL 08/Sep, Y VIENE DE FUERA DEL CASO. Al ordenar el apartamiento del director general de la Policía Federal, André Mendonça afirmó que el informe de inteligencia citado por Alexandre de Moraes anticipó nuevos objetivos y perjudicó las investigaciones del caso Master, según O Globo. La disputa sobre quién controla la investigación pasó a tener, dentro del tribunal, acusaciones de cortina de humo y de operación de encubrimiento, según G1. El 04/Sep la Fiscalía General de la República pidió autorización para investigar sospecha de interferencia en la producción del informe de la Policía Federal, y ese pedido sigue en pie.`,

  'cards.bancoMaster.text2': `El Consejo Superior del Ministerio Público Federal abrió un procedimiento el 04/Sep para analizar las menciones a Paulo Gonet en los mensajes de Daniel Vorcaro, y es el consejo que el propio fiscal general preside. Un ala del ${G('Supremo', 'stf')} defiende que se aparte del caso, según O Globo, y el pedido de apartamiento también lo hizo un parlamentario, según SBT News. ⚠️ Alexandre de Moraes y André Mendonça se manifestarán hasta el fin de la semana sobre el caso de los mensajes, según O Globo.`,

  'cards.bancoMaster.conclusao': `Lo que cambió el 08/Sep es que el caso dejó de estar contenido en sí mismo: la decisión que apartó a la cúpula de la Policía Federal cita expresamente perjuicio a las investigaciones del Master, y la disputa sobre quién controla la investigación se volvió disputa entre ministros. Las fechas anteriores siguen en pie, y son las dos del 04/Sep: el presidente del tribunal recibió el pedido de la Fiscalía y el Consejo Superior del Ministerio Público Federal abrió procedimiento.`,

  'cards.stf.toffoli': `Sin acto individual nuevo el 08/Sep. Sigue siendo blanco del pedido de impeachment presentado por Renan Santos, junto con Alexandre de Moraes, y volvió a ser citado en los actos de campaña del 07/Sep, cuando Renan Santos pidió la prisión de los dos, según Folha de S.Paulo.`,

  'cards.stf.moraes': `Sin acto individual nuevo el 08/Sep. ⚠️ Pero la decisión del día es sobre el material que él usó: André Mendonça apartó al director general de la Policía Federal y al director de Inteligencia y ordenó investigar la producción de informes de inteligencia sobre magistrados, llamando descabellados los informes usados por Moraes, según O Globo, Metrópoles y Gazeta do Povo. El 07/Sep fue blanco de carteles y muñecos en los actos de la derecha en Brasilia y en la avenida Paulista, según Metrópoles, Gazeta do Povo y Valor Econômico.`,

  'cards.stf.gilmar': `⚠️ Acto nuevo el 08/Sep: pidió vista en la sesión virtual extraordinaria de la Segunda Sala que analizaba el apartamiento del director general de la Policía Federal, cinco minutos después de abrirse la sesión a las 10h, lo que SUSPENDIÓ el juicio, según Metrópoles, Migalhas y Folha de S.Paulo. La propuesta de enmienda al reglamento interno que presentó a Edson Fachin, para prohibir el nombramiento de militares y policías en cargos de confianza en los despachos de los ministros, es del 05/Sep y la página la mantiene con su fecha de origen.`,

  'cards.stf.dino': `Sin acto individual nuevo el 08/Sep. Su pronunciamiento de que el ${G('Supremo', 'stf')} es mayor que cualquiera que lo integre es del 04/Sep, y la página lo mantiene con su fecha de origen.`,

  'cards.stf.mendonca': `⭐ ACTO NUEVO Y DE ALTO IMPACTO EL 08/Sep: determinó el apartamiento preventivo por 90 días de Andrei Rodrigues, director general de la Policía Federal, y de Leandro Almada da Costa, director de Inteligencia, y ordenó a la corregiduría abrir investigación penal y administrativa sobre la producción de informes de inteligencia acerca de magistrados, según Metrópoles, Gazeta do Povo, O Globo y Migalhas. En la decisión afirma haber sido blanco de vigilancia sistemática e ilegal de la inteligencia de la Policía Federal durante más de 30 días, y esa es su alegación, no un hecho establecido. ⚠️ En la sesión virtual de la Segunda Sala abierta a las 10h, Nunes Marques y Luiz Fux adelantaron su voto y formaron mayoría siguiendo al ponente, pero Gilmar Mendes pidió vista y el juicio está SUSPENDIDO, con el voto de Dias Toffoli aún pendiente. El pedido de la Fiscalía para investigarlo, del 04/Sep, sigue en pie.`,

  'cards.stf.nexo': `⚠️ LA CRISIS DEL SUPREMO SALIÓ DE LA CALLE Y SE VOLVIÓ ACTO INSTITUCIONAL, Y ESE ES EL REGISTRO DEL DÍA. El 07/Sep estaba en los actos de campaña; el 08/Sep un ministro apartó a la cúpula de la Policía Federal, la Segunda Sala formó mayoría siguiendo al ponente y otro ministro suspendió el juicio con un pedido de vista. Expresidentes del tribunal pidieron acción a Edson Fachin y hablaron de la más aguda crisis de la corte, y senadores admiten la posibilidad de impeachment de un ministro, según Folha de S.Paulo. 📌 La distinción que la página mantenía hasta ayer, entre acto de campaña sobre el tribunal y acto del tribunal, dejó de valer hoy: los dos existen, y el segundo es nuevo.`,

  'cards.stf.analise': `El contrato de salida de un ministro del ${G('Supremo', 'stf')} por impeachment antes de 2027 cedió 1,15pp y está en 7,45% (vol USD 88 mil), ${S8}. ⚠️ EL REGISTRO DEL DÍA ES QUE EL PRECIO CAYÓ EL DÍA DEL ACTO INSTITUCIONAL MÁS CONCRETO DE LA CRISIS: un ministro apartó al director general de la Policía Federal por 90 días, la Segunda Sala formó mayoría siguiendo al ponente y un pedido de vista suspendió el juicio, y el contrato fue hacia abajo. En la serie registrada desde el 14/Abr va de 2,10% a 19,30%, con el techo el 04/Sep, y la lectura de hoy queda dentro de esa franja. 📌 Es el menor libro del panel en volumen acumulado, y un movimiento en libro fino pide una lectura más cautelosa que la del presidencial, que acumula USD 145,26M.`,
})
