/**
 * Mapa EN de 18/Ago/2026.
 *
 * O dia NÃO tem captura certificada: a trava rodou cinco vezes e bloqueou as
 * cinco. Os preços na tela seguem sendo os de 17/Ago, 18:48 BRT, e cada campo
 * abaixo declara isso em vez de deixar o leitor supor que o número é de hoje.
 */
import { construir } from '../build-locale-json'

const CONF = 'confirmed reading of Aug 17, 6:48 PM BRT'
const TRAVA =
  'The AFOS capture guard takes two readings 8 minutes apart and only clears them if they agree within 0.20pp. It ran FIVE times between 8:30 PM and 9:37 PM BRT on Aug 18 and blocked all five.'

construir('analysis-criteriosa', 'en', {
  subtitle: `UPDATE Aug 18, 47 days from the first round and on the THIRD DAY OF THE OFFICIAL CAMPAIGN. ⛔ NO NEW PRICE, AND THE REASON IS THE FINDING OF THE DAY: the AFOS capture guard ran FIVE times between 8:30 PM and 9:37 PM and blocked all five. The panel keeps the ${CONF}, and declares below the range each contract was read in tonight. NO new national poll: the latest is still BTG/Nexus of Aug 17 (n=2,003, field Aug 14 to 16, TSE registration BR-03317/2026). Datafolha and Veritá publish on Aug 21, both already in the field, and Datafolha is the first to measure Pablo Marçal.`,

  cruzamento: `⭐ THE FINDING OF THE DAY IS NOT A PRICE, IT IS THE REFUSAL TO CERTIFY ONE. ${TRAVA} That is why the panel publishes NO new price: it keeps the ${CONF}, and declares here what was read. 🔑 THE PART THAT MATTERS IS WHERE THE INSTABILITY SAT. Across the ten readings of the night the leader came in at 63.50% EVERY time, with 0.00pp of amplitude, and Renan Santos at 3.95% and Ronaldo Caiado at 0.45% did not move either. What blocked certification were the thin contracts and the placement ones: the runner-up ranged between 32.45% and 32.75%, and PABLO MARÇAL ranged between 0.65% and 1.15%, that is 0.50pp of amplitude on a contract worth about 1%, nearly half its own value. In the second place book the runner-up swung 1.00pp, and in the third place book Renan and Caiado swung 0.50pp each. ⚠️ WHAT THIS MEANS AND WHAT IT DOES NOT: a thin book moves on little money, so high amplitude there is NOT an electoral signal, it is market depth. The panel records the difference instead of publishing a number that two readings do not confirm. 📌 POLLS: nothing new. The latest national one is BTG/Nexus of Aug 17, which measured STABILITY, with the distance between the top two at the same 5 points and the runoff identical at 47 to 44. Thursday and Friday change that: Real Time Big Data on Aug 19, Datafolha and Veritá on Aug 21, and Datafolha is the FIRST to include Pablo Marçal, who today has a price in the market and no ballot-box measurement at all.`,

  'quadroComparativo[0].t': `⛔ NO CONFIRMED READING TODAY. The price above is the one from Aug 17, 6:48 PM BRT. Across the ten readings between 8:30 PM and 9:37 PM tonight he appeared at 63.50% in ALL of them, with 0.00pp of amplitude, but the guard certifies the WHOLE capture or none of it, and other contracts disagreed. ⛔ No superlative: the high of the 88-day series is still 66.50%, from Aug 1, and the low is 39.50%, from Jun 2.`,
  'quadroComparativo[0].s': `Third day of the official campaign, 47 days from the first round. In a STATE poll in Paraná he trails in the runoff, 35% to 52%, according to Poder360, and leads in Pernambuco, 58% to 24%, according to Real Time Big Data. 📌 State polls do not enter the national panel, and are here as coverage. 📅 Datafolha and Veritá publish on Aug 21.`,

  'quadroComparativo[1].t': `⛔ NO CONFIRMED READING TODAY. The price above is the one from Aug 17, 6:48 PM BRT. Tonight he was read between 32.45% and 32.75%, and he was one of the contracts that blocked certification, disagreeing 0.30pp between samples in the presidential book and 1.00pp in the second place book. ⛔ No superlative: the high of the 88-day series is 33.20%, from Jun 2, and no reading tonight passed it.`,
  'quadroComparativo[1].s': `He leads the second place contract comfortably, read between 87.00% and 87.50% tonight. In a STATE poll in Paraná he stands at 52% against 35% in the runoff, according to Poder360 and CartaCapital. 📌 State polls do not enter the national panel.`,

  'quadroComparativo[2].t': `⛔ NO CONFIRMED READING TODAY. The price above is the one from Aug 17, 6:48 PM BRT. In the presidential book he was STABLE across the ten readings of the night, at 3.95%, with 0.00pp of amplitude. It was in the PLACEMENT books that he moved: 0.35pp in the second place one and 0.50pp in the third place one. ⛔ The low of the 88-day series was touched on Aug 18, at 3.60%, and the high is 17.90%, from Jun 9.`,
  'quadroComparativo[2].s': `He stays ahead in the third place contract, read between 56.50% and 57.00% tonight, against 37.00% to 37.50% for Caiado. 📌 The poll says the opposite: BTG/Nexus of Aug 17 gives Caiado 5% and him 4%.`,

  // ⚠️ NÃO usar a constante TRAVA aqui: ela cita a tolerância de 0.20pp, e o
  // pt-BR deste campo não cita. O gate numérico reprovou por causa disso, com
  // razão: tradução não acrescenta número.
  'candidates[0].analise': `⛔ THERE WAS NO CERTIFIED PRICE TODAY, and that is the record of the day. The capture guard ran five times between 8:30 PM and 9:37 PM and blocked all five. Across the ten readings of that window he appeared at 63.50% in ALL of them, with 0.00pp of amplitude, the most stable contract in the book. But the guard certifies the whole capture or none of it, and other contracts disagreed, so the panel keeps the ${CONF}. 📌 POLLS: no new national one. BTG/Nexus of Aug 17 remains the latest, with 41% in the first round and 47% in the runoff, and the distance to the runner-up unchanged at 5 points. In STATE polls today he trails in Paraná, 35% to 52% in the runoff, and leads in Pernambuco, 58% to 24%. State polls do not enter the national panel and are here as coverage. 📅 Datafolha and Veritá publish on Aug 21, both already in the field.`,

  'candidates[1].analise': `⛔ NO CERTIFIED PRICE TODAY. He was one of the contracts that blocked certification: he disagreed 0.30pp between samples in the presidential book, read between 32.45% and 32.75%, and 1.00pp in the second place book, between 86.50% and 87.50%. The panel keeps the ${CONF}, of 31.45%. ⛔ NO SUPERLATIVE: the high of the 88-day series is 33.20%, from Jun 2, and no reading tonight passed it. 📌 POLLS: nothing new nationally. BTG/Nexus of Aug 17 has him at 36% in the first round and 44% in the runoff, with the distance to the leader at the same 5 points. In a STATE poll in Paraná he stands at 52% against 35% in the runoff, according to Poder360 and CartaCapital, and state polls do not enter the national panel.`,

  'candidates[2].analise': `⛔ NO CERTIFIED PRICE TODAY, and his behaviour separates two things. In the PRESIDENTIAL contract he sat still at 3.95% across the ten readings of the night, with 0.00pp of amplitude. In the PLACEMENT contracts he moved: 0.35pp in the second place one and 0.50pp in the third place one, where he was read between 56.50% and 57.00%. 📏 The low of the 88-day series was touched on Aug 18, at 3.60%, against a high of 17.90% on Jun 9. 📌 THE DISAGREEMENT WITH THE BALLOT BOX CONTINUES: BTG/Nexus of Aug 17 gives Caiado 5% and him 4%, while the market keeps him far ahead in the third place contract, 57.00% against 37.00%. These are different questions: the poll measures declared intention, the contract measures probability of placement.`,

  'candidates[3].analise': `⛔ NO CERTIFIED PRICE TODAY. Caiado was STABLE at 0.45% across the ten presidential readings, and swung 0.50pp in the third place contract, between 37.00% and 37.50%. 🏷️ PABLO MARÇAL was the MOST UNSTABLE contract of the night: read between 0.65% and 1.15%, that is 0.50pp of amplitude on a contract worth about 1%, nearly half its own value. A thin book moves on little money, so high amplitude there is market depth and NOT an electoral signal. 📄 ELECTORAL STATUS, updated today: Marçal asked the electoral court to correct his asset declaration, and the declared wealth fell from R$ 7.4 billion to R$ 149.9 million, according to G1, Valor and O Globo, which belong to the same group and therefore count as one source. He remains INELIGIBLE until 2032, with campaigning allowed by injunction and registration still pending. Tarcísio remains a candidate for re-election as governor of São Paulo and Haddad for governor of São Paulo, and their contracts stay in the book priced at the floor.`,
})
