/**
 * Mapa ES de 18/Ago/2026. Convenções travadas: decimal com VÍRGULA, `pesquisa`
 * vira `encuesta`, `estadual` vira `estatal`, e o verbo de mercado é `descontar`.
 */
import { construir } from '../build-locale-json'

const CONF = 'lectura confirmada del 17 de ago, 18:48 BRT'

construir('analysis-criteriosa', 'es', {
  subtitle: `ACTUALIZACIÓN 18 de ago, a 47 días de la primera vuelta y en el TERCER DÍA DE LA CAMPAÑA OFICIAL. ⛔ SIN PRECIO NUEVO, Y EL MOTIVO ES EL HALLAZGO DEL DÍA: la traba de captura del AFOS corrió CINCO veces entre las 20:30 y las 21:37 y bloqueó las cinco. El panel mantiene la ${CONF}, y declara abajo el rango en que cada contrato fue leído esta noche. NINGUNA encuesta nacional nueva: la última sigue siendo la Nexus/BTG del 17 de ago (n=2.003, campo del 14 al 16 de ago, registro TSE BR-03317/2026). Datafolha y Veritá publican el 21 de ago, las dos ya en campo, y Datafolha es la primera en medir a Pablo Marçal.`,

  cruzamento: `⭐ EL HALLAZGO DE HOY NO ES UN PRECIO, ES LA NEGATIVA A CERTIFICAR UNO. La traba de captura del AFOS hace dos lecturas separadas por 8 minutos y solo libera si concuerdan dentro de 0,20pp. Corrió CINCO veces entre las 20:30 y las 21:37 BRT del 18 de ago y bloqueó las cinco. Por eso el panel NO publica precio nuevo: mantiene la ${CONF}, y declara aquí lo que se leyó. 🔑 LA PARTE QUE IMPORTA ES DÓNDE ESTABA LA INESTABILIDAD. En las diez lecturas de la noche el líder apareció en 63,50% TODAS las veces, con amplitud de 0,00pp, y Renan Santos en 3,95% y Ronaldo Caiado en 0,45% tampoco se movieron. Lo que impidió la certificación fueron los contratos finos y los de posición: el segundo varió entre 32,45% y 32,75%, y PABLO MARÇAL varió entre 0,65% y 1,15%, o sea 0,50pp de amplitud en un contrato que vale cerca de 1%, casi la mitad de su propio valor. En el libro de segundo lugar el segundo osciló 1,00pp, y en el de tercer lugar Renan y Caiado oscilaron 0,50pp cada uno. ⚠️ QUÉ SIGNIFICA ESTO Y QUÉ NO: un libro fino se mueve con poco dinero, así que amplitud alta ahí NO es señal electoral, es espesor de mercado. El panel registra la diferencia en vez de publicar un número que dos lecturas no confirman. 📌 ENCUESTAS: nada nuevo. La última nacional es la Nexus/BTG del 17 de ago, que midió ESTABILIDAD, con la distancia entre los dos primeros en los mismos 5 puntos y la segunda vuelta idéntica en 47 a 44. El jueves y el viernes cambian eso: Real Time Big Data el 19 de ago, Datafolha y Veritá el 21 de ago, y Datafolha es la PRIMERA en incluir a Pablo Marçal, que hoy tiene precio en el mercado y ninguna medición de urna.`,

  'quadroComparativo[0].t': `⛔ SIN LECTURA CONFIRMADA HOY. El precio de arriba es el del 17 de ago, 18:48 BRT. En las diez lecturas entre las 20:30 y las 21:37 de esta noche apareció en 63,50% en TODAS, con amplitud de 0,00pp, pero la traba certifica la captura ENTERA o ninguna, y otros contratos discreparon. ⛔ Sin superlativo: el máximo de la serie de 88 días sigue en 66,50%, del 1 de ago, y el piso es 39,50%, del 2 de jun.`,
  'quadroComparativo[0].s': `Tercer día de campaña oficial, a 47 días de la primera vuelta. En una encuesta ESTATAL de Paraná aparece atrás en la segunda vuelta, 35% contra 52%, según Poder360, y adelante en Pernambuco, 58% contra 24%, según Real Time Big Data. 📌 La encuesta estatal no entra en el panel nacional, y está aquí como cobertura. 📅 Datafolha y Veritá publican el 21 de ago.`,

  'quadroComparativo[1].t': `⛔ SIN LECTURA CONFIRMADA HOY. El precio de arriba es el del 17 de ago, 18:48 BRT. Esta noche fue leído entre 32,45% y 32,75%, y fue uno de los contratos que impidieron la certificación, discrepando 0,30pp entre muestras en el presidencial y 1,00pp en el libro de segundo lugar. ⛔ Sin superlativo: el máximo de la serie de 88 días es 33,20%, del 2 de jun, y ninguna lectura de esta noche lo superó.`,
  'quadroComparativo[1].s': `Lidera con holgura el contrato de segundo lugar, leído entre 87,00% y 87,50% esta noche. En una encuesta ESTATAL de Paraná aparece con 52% contra 35% en la segunda vuelta, según Poder360 y CartaCapital. 📌 La estatal no entra en el panel nacional.`,

  'quadroComparativo[2].t': `⛔ SIN LECTURA CONFIRMADA HOY. El precio de arriba es el del 17 de ago, 18:48 BRT. En el presidencial quedó ESTABLE en las diez lecturas de la noche, en 3,95%, con amplitud de 0,00pp. Fue en los libros de POSICIÓN donde se movió: 0,35pp en el de segundo lugar y 0,50pp en el de tercero. ⛔ El piso de la serie de 88 días se tocó el 18 de ago, con 3,60%, y el máximo es 17,90%, del 9 de jun.`,
  'quadroComparativo[2].s': `Sigue adelante en el contrato de tercer lugar, leído entre 56,50% y 57,00% esta noche, contra 37,00% a 37,50% de Caiado. 📌 La encuesta dice lo contrario: la Nexus/BTG del 17 de ago da 5% a Caiado y 4% a él.`,

  'candidates[0].analise': `⛔ HOY NO HUBO PRECIO CERTIFICADO, y ese es el registro del día. La traba de captura corrió cinco veces entre las 20:30 y las 21:37 y bloqueó las cinco. En las diez lecturas de esa ventana apareció en 63,50% en TODAS, con amplitud de 0,00pp, el contrato más estable del libro. Pero la traba certifica la captura entera o ninguna, y otros contratos discreparon, así que el panel mantiene la ${CONF}. 📌 ENCUESTAS: ninguna nacional nueva. La Nexus/BTG del 17 de ago sigue siendo la última, con 41% en la primera vuelta y 47% en la segunda, y la distancia hacia el segundo inalterada en 5 puntos. En encuestas ESTATALES de hoy aparece atrás en Paraná, 35% contra 52% en la segunda vuelta, y adelante en Pernambuco, 58% contra 24%. La estatal no entra en el panel nacional y está aquí como cobertura. 📅 Datafolha y Veritá publican el 21 de ago, las dos ya en campo.`,

  'candidates[1].analise': `⛔ SIN PRECIO CERTIFICADO HOY. Fue uno de los contratos que impidieron la certificación: discrepó 0,30pp entre muestras en el presidencial, leído entre 32,45% y 32,75%, y 1,00pp en el libro de segundo lugar, entre 86,50% y 87,50%. El panel mantiene la ${CONF}, de 31,45%. ⛔ SIN SUPERLATIVO: el máximo de la serie de 88 días es 33,20%, del 2 de jun, y ninguna lectura de esta noche lo superó. 📌 ENCUESTAS: nada nacional nuevo. La Nexus/BTG del 17 de ago lo tiene en 36% en la primera vuelta y 44% en la segunda, con la distancia hacia el líder en los mismos 5 puntos. En una encuesta ESTATAL de Paraná aparece con 52% contra 35% en la segunda vuelta, según Poder360 y CartaCapital, y la estatal no entra en el panel nacional.`,

  'candidates[2].analise': `⛔ SIN PRECIO CERTIFICADO HOY, y su comportamiento separa dos cosas. En el contrato PRESIDENCIAL quedó quieto en 3,95% en las diez lecturas de la noche, con amplitud de 0,00pp. En los contratos de POSICIÓN se movió: 0,35pp en el de segundo lugar y 0,50pp en el de tercero, donde fue leído entre 56,50% y 57,00%. 📏 El piso de la serie de 88 días se tocó el 18 de ago, con 3,60%, contra un máximo de 17,90% el 9 de jun. 📌 LA DISCREPANCIA CON LA URNA CONTINÚA: la Nexus/BTG del 17 de ago da 5% a Caiado y 4% a él, mientras el mercado lo mantiene muy adelante en el contrato de tercer lugar, 57,00% contra 37,00%. Son preguntas distintas: la encuesta mide intención declarada, el contrato mide probabilidad de posición.`,

  'candidates[3].analise': `⛔ SIN PRECIO CERTIFICADO HOY. Caiado quedó ESTABLE en 0,45% en las diez lecturas presidenciales, y osciló 0,50pp en el contrato de tercer lugar, entre 37,00% y 37,50%. 🏷️ PABLO MARÇAL fue el contrato MÁS INESTABLE de la noche: leído entre 0,65% y 1,15%, o sea 0,50pp de amplitud en un contrato que vale cerca de 1%, casi la mitad de su propio valor. Un libro fino se mueve con poco dinero, así que amplitud alta ahí es espesor de mercado y NO señal electoral. 📄 ESTADO ELECTORAL, actualizado hoy: Marçal pidió al tribunal electoral la corrección de su declaración de bienes, y el patrimonio declarado cayó de R$ 7,4 mil millones a R$ 149,9 millones, según G1, Valor y O Globo, que son del mismo grupo y por eso cuentan como una fuente. Sigue INELEGIBLE hasta 2032, con campaña habilitada por medida cautelar y registro aún pendiente. Tarcísio sigue como candidato a la reelección al gobierno de São Paulo y Haddad al gobierno de São Paulo, y sus contratos siguen en el libro con precio en el piso.`,
})
