/** Mapa ES de 18/Ago/2026, versão publicada: captura certificada de 22:32 BRT. */
import { construir } from '../build-locale-json'

const CAR = 'lectura confirmada del 18 de ago, 22:32 BRT (01:32 UTC)'

construir('analysis-criteriosa', 'es', {
  subtitle: `ACTUALIZACIÓN 18 de ago, a 47 días de la primera vuelta y en el TERCER DÍA DE LA CAMPAÑA OFICIAL. LA DISTANCIA ENTRE LULA Y FLÁVIO BOLSONARO SE ACORTÓ POR SEGUNDO DÍA SEGUIDO y cerró en 31,45pp, contra 37,05pp el 16 de ago, en un libro presidencial que acumula USD 128,96M. La única encuesta nacional de la semana, la Nexus/BTG del 17 de ago (n=2.003, campo del 14 al 16 de ago, BR-03317/2026), dijo lo contrario: la distancia entre los dos NO cambió, siguió en los mismos 5 puntos. RONALDO CAIADO subió en el contrato de victoria y cayó en el de tercer lugar el mismo día. Datafolha y Veritá publican el 21 de ago, las dos ya en campo, y Datafolha es la primera en medir a Pablo Marçal.`,

  cruzamento: `⭐ EL HALLAZGO DEL DÍA ES UNA DIVERGENCIA DE DIRECCIÓN ENTRE LOS DOS UNIVERSOS QUE EL PANEL MIDE. En la ${CAR}, LULA cerró en 63,50% (vol USD 8,67M), caída de 1,00pp, y FLÁVIO BOLSONARO en 32,05% (vol USD 8,62M), alza de 0,60pp. La distancia entre los dos se acortó 1,60pp y quedó en 31,45pp, SEGUNDO día seguido de acercamiento: eran 37,05pp el 16 de ago y 33,05pp el 17 de ago, o sea 5,60pp en dos días. 🔑 LA URNA DICE LO CONTRARIO: la Nexus/BTG del 17 de ago midió a Lula pasando de 40% a 41% y a Flávio de 35% a 36%, lo que deja la diferencia entre ellos INTACTA en 5 puntos, y cada movimiento de 1 punto cabe dentro del margen de 2pp de la propia casa. Una medición que no acorta no explica un acortamiento. ⛔ Dirección igual no es causa, y dirección OPUESTA tampoco: el panel registra las dos lecturas y no arbitra. ⭐⭐ EL SEGUNDO CRUCE ES RONALDO CAIADO CONTRA SÍ MISMO. Más que triplicó en el contrato de VICTORIA, de 0,25% a 0,80% (vol USD 6,34M), volviendo a quedar por encima del corte de 0,5% que el panel usa para separar precio de ruido; y CEDIÓ en el contrato de TERCER LUGAR, de 38,50% a 37,00%. Ganar la elección y terminar tercero son preguntas distintas, y en esta ronda apuntaron a lados opuestos. ⛔ SIN SUPERLATIVO sobre él: 0,80% es recuperación del piso de la serie, 0,50% el 15 de ago, y no cercanía al máximo, que es 2,40%, del 19 de jun. De los 86 días registrados desde el 21 de may, 84 tuvieron un valor igual o superior al de hoy. 📌 Y RENAN SANTOS REABRIÓ LA VENTAJA QUE VENÍA PERDIENDO: en el contrato de tercer lugar saltó de 52,50% a 57,00%, y su distancia hacia Caiado volvió de 14,00pp a 20,00pp, deshaciendo dos días de acercamiento. En la intención declarada el orden sigue invertido, con Caiado en 5% contra 4% de Renan. 📅 Ninguna encuesta nacional nueva entró: la ingesta del tribunal electoral leyó 606 registros y no encontró ninguno. Real Time Big Data publica el 19 de ago, y Datafolha y Veritá el 21 de ago.`,

  'candidates[0].header': `PRECIO: 63,50% (vol USD 8,67M acumulado), ${CAR}`,
  'candidates[1].header': `PRECIO: 32,05% (vol USD 8,62M acumulado), ${CAR}`,
  'candidates[2].header': `PRECIO: 4,40% (vol USD 10,11M acumulado), ${CAR}`,
  'candidates[3].header': `PRECIO para todo el pelotón, ${CAR}: Ronaldo Caiado 0,80% (vol USD 6,34M), Pablo Marçal 0,90% (vol USD 1,66M), Romeu Zema 0,15% (vol USD 5,71M), Fernando Haddad 0,05% y Tarcísio de Freitas 0,05% (vol USD 13,93M, el mayor del libro).`,

  'candidates[0].analise': `PRECIO en 63,50% (vol USD 8,67M acumulado), ${CAR}, caída de 1,00pp. LA DISTANCIA hacia el segundo SE ACORTÓ 1,60pp y quedó en 31,45pp, segundo día seguido de acercamiento: eran 37,05pp el 16 de ago y 33,05pp el 17 de ago. 🔑 LA URNA DICE LO CONTRARIO: la Nexus/BTG del 17 de ago lo llevó de 40% a 41% y al adversario de 35% a 36%, así que la distancia entre los dos NO cambió, siguió en 5 puntos, y cada movimiento cabe dentro del margen de 2pp. Una medición que no acorta no explica un acortamiento. 📌 En encuestas ESTATALES de hoy aparece atrás en Paraná, 35% contra 52% en la segunda vuelta, y adelante en Pernambuco, 58% contra 24%; la estatal no entra en el panel nacional. ⛔ Sin superlativo: el máximo de la serie de 88 días sigue en 66,50%, del 1 de ago. 📅 Datafolha y Veritá publican el 21 de ago, las dos ya en campo.`,

  'candidates[1].analise': `PRECIO en 32,05% (vol USD 8,62M acumulado), ${CAR}, alza de 0,60pp y quinto día seguido subiendo. En el contrato de SEGUNDO LUGAR marca 88,50%. ⛔ NO es récord: el máximo de la serie de 88 días es 33,20%, del 2 de jun. 📌 EN LA URNA, la Nexus/BTG del 17 de ago lo tiene en 36% en la primera vuelta y 44% en la segunda, con la distancia hacia el líder en los mismos 5 puntos. En una encuesta ESTATAL de Paraná aparece con 52% contra 35% en la segunda vuelta, según Poder360 y CartaCapital, y la estatal no entra en el panel nacional.`,

  'candidates[2].analise': `PRECIO en 4,40% (vol USD 10,11M acumulado), ${CAR}, alza de 0,35pp. ⭐ EL MOVIMIENTO FUERTE FUE EN LA POSICIÓN: en el contrato de TERCER LUGAR saltó de 52,50% a 57,00%, y su distancia hacia Caiado en ese libro REABRIÓ de 14,00pp a 20,00pp, deshaciendo dos días de acercamiento. 📌 LA DISCREPANCIA CON LA URNA CONTINÚA Y ESTÁ INVERTIDA: la Nexus/BTG del 17 de ago da 5% a Caiado y 4% a él, mientras el mercado lo mantiene 20 puntos adelante en el contrato de posición. Son preguntas distintas: la encuesta mide intención declarada, el contrato mide probabilidad de posición.`,

  'candidates[2].fracos[1]': `⚠️ Su book es FINO, y eso importa para leer el movimiento: en el contrato presidencial vale poco más de 4%, y en ese rango poco dinero mueve el precio. La lectura de posición, en el contrato de tercer lugar, es donde carga peso de verdad.`,

  'candidates[3].analise': `⭐ RONALDO CAIADO ES EL CRUCE DEL DÍA, Y ES CONTRA SÍ MISMO. En el contrato de VICTORIA más que triplicó, de 0,25% a 0,80% (vol USD 6,34M), ${CAR}, y volvió a quedar por encima del corte de 0,5% que el panel usa para separar precio de ruido. En el contrato de TERCER LUGAR CEDIÓ, de 38,50% a 37,00%. Los dos movimientos son del mismo día y apuntan a lados opuestos. ⛔ SIN SUPERLATIVO: 0,80% es recuperación del piso de la serie, 0,50% el 15 de ago, y no cercanía al máximo, que es 2,40%, del 19 de jun; de los 86 días registrados desde el 21 de may, 84 tuvieron un valor igual o superior al de hoy. 📌 El PSD confirmó su candidatura a la Presidencia, según Acessa.com. PABLO MARÇAL repitió 0,90%, con el volumen pasando de USD 1,21M a USD 1,66M en un día, y 🏷️ su estado electoral cambió hoy: pidió al tribunal electoral la corrección de su declaración de bienes y el patrimonio declarado cayó de R$ 7,4 mil millones a R$ 149,9 millones, según G1 y Valor Econômico, que son del mismo grupo. Sigue INELEGIBLE hasta 2032, con campaña habilitada por medida cautelar y registro pendiente. ROMEU ZEMA cayó a 0,15%. TARCÍSIO sigue como candidato a la reelección al gobierno de São Paulo y HADDAD al gobierno de São Paulo, con sus contratos en el piso.`,

  'quadroComparativo[0].m': `63,50% (vol USD 8,67M acumulado), ${CAR}`,
  'quadroComparativo[0].t': `🔴 CAÍDA de 1,00pp, de 64,50% a 63,50%, y la distancia hacia el segundo SE ACORTÓ 1,60pp, a 31,45pp. Es el SEGUNDO día seguido de acercamiento, sumando 5,60pp desde el 16 de ago. ⛔ Sin superlativo: el máximo de la serie de 88 días sigue en 66,50%, del 1 de ago, y el piso es 39,50%, del 2 de jun.`,
  'quadroComparativo[0].s': `Tercer día de campaña oficial, a 47 días de la primera vuelta. En una encuesta ESTATAL de Paraná aparece atrás en la segunda vuelta, 35% contra 52%, según Poder360 y CartaCapital, y adelante en Pernambuco, 58% contra 24%. 📌 La estatal no entra en el panel nacional y está aquí como cobertura. 📅 Datafolha y Veritá publican el 21 de ago.`,

  'quadroComparativo[1].m': `32,05% (vol USD 8,62M acumulado), ${CAR}`,
  'quadroComparativo[1].t': `🔺 ALZA de 0,60pp, de 31,45% a 32,05%, quinto día seguido subiendo, y la distancia hacia el líder se acortó a 31,45pp. ⛔ NO es récord: el máximo de la serie de 88 días es 33,20%, del 2 de jun. En el contrato de SEGUNDO LUGAR marca 88,50%.`,
  'quadroComparativo[1].s': `En una encuesta ESTATAL de Paraná aparece con 52% contra 35% en la segunda vuelta, según Poder360 y CartaCapital. 📌 La estatal no entra en el panel nacional. En la urna nacional la Nexus/BTG del 17 de ago lo tiene en 36% en la primera vuelta y 44% en la segunda.`,

  'quadroComparativo[2].m': `4,40% (vol USD 10,11M acumulado), ${CAR}`,
  'quadroComparativo[2].t': `🔺 ALZA de 0,35pp en el presidencial, de 4,05% a 4,40%. ⭐ Y el movimiento fuerte fue en el contrato de TERCER LUGAR: saltó de 52,50% a 57,00%, y su distancia hacia Caiado en ese libro REABRIÓ de 14,00pp a 20,00pp, deshaciendo dos días de acercamiento. ⛔ Sin superlativo: el máximo de la serie de 88 días es 17,90%, del 9 de jun.`,
  'quadroComparativo[2].s': `📌 La urna y el precio siguen discrepando sobre quién es el tercero: la Nexus/BTG del 17 de ago da 5% a Caiado y 4% a él, mientras el mercado lo mantiene muy adelante en el contrato de posición.`,
})
