/** Mapa EN de 18/Ago/2026, versão publicada: captura certificada de 22:32 BRT. */
import { construir } from '../build-locale-json'

const CAR = 'confirmed reading of Aug 18, 10:32 PM BRT (01:32 UTC)'

construir('analysis-criteriosa', 'en', {
  subtitle: `UPDATE Aug 18, 47 days from the first round and on the THIRD DAY OF THE OFFICIAL CAMPAIGN. THE DISTANCE BETWEEN LULA AND FLÁVIO BOLSONARO NARROWED FOR THE SECOND DAY RUNNING and closed at 31.45pp, against 37.05pp on Aug 16, in a presidential book that has accumulated USD 128.96M. The only national poll of the week, BTG/Nexus of Aug 17 (n=2,003, field Aug 14 to 16, BR-03317/2026), said the opposite: the distance between the two did NOT change, it stayed at the same 5 points. RONALDO CAIADO rose in the contract on winning and fell in the third place one on the same day. Datafolha and Veritá publish on Aug 21, both already in the field, and Datafolha is the first to measure Pablo Marçal.`,

  cruzamento: `⭐ THE FINDING OF THE DAY IS A DIVERGENCE OF DIRECTION BETWEEN THE TWO UNIVERSES THE PANEL MEASURES. In the ${CAR}, LULA closed at 63.50% (vol USD 8.67M), down 1.00pp, and FLÁVIO BOLSONARO at 32.05% (vol USD 8.62M), up 0.60pp. The distance between them narrowed 1.60pp to 31.45pp, the SECOND day running of convergence: it was 37.05pp on Aug 16 and 33.05pp on Aug 17, that is 5.60pp in two days. 🔑 THE BALLOT BOX SAYS THE OPPOSITE: BTG/Nexus of Aug 17 measured Lula going from 40% to 41% and Flávio from 35% to 36%, which leaves the difference between them INTACT at 5 points, and each 1-point move fits inside the house's own 2pp margin. A measurement that does not narrow cannot explain a narrowing. ⛔ Same direction is not causation, and OPPOSITE direction is not either: the panel records both readings and does not arbitrate. ⭐⭐ THE SECOND CROSSING IS RONALDO CAIADO AGAINST HIMSELF. He more than tripled in the contract on WINNING, from 0.25% to 0.80% (vol USD 6.34M), returning above the 0.5% cut the panel uses to separate price from noise; and he GAVE GROUND in the THIRD PLACE contract, from 38.50% to 37.00%. Winning the election and finishing third are different questions, and in this round they pointed opposite ways. ⛔ NO SUPERLATIVE about him: 0.80% is a recovery from the series low, 0.50% on Aug 15, and not proximity to the high, which is 2.40%, from Jun 19. Of the 86 days recorded since May 21, 84 had a value equal to or above today's. 📌 AND RENAN SANTOS REOPENED THE LEAD HE HAD BEEN LOSING: in the third place contract he jumped from 52.50% to 57.00%, and his distance to Caiado went back from 14.00pp to 20.00pp, undoing two days of convergence. In declared intention the order is still reversed, with Caiado at 5% against Renan's 4%. 📅 No new national poll came in: the electoral court ingestion read 606 records and found none. Real Time Big Data publishes on Aug 19, and Datafolha and Veritá on Aug 21.`,

  'candidates[0].header': `PRICE: 63.50% (vol USD 8.67M accumulated), ${CAR}`,
  'candidates[1].header': `PRICE: 32.05% (vol USD 8.62M accumulated), ${CAR}`,
  'candidates[2].header': `PRICE: 4.40% (vol USD 10.11M accumulated), ${CAR}`,
  'candidates[3].header': `PRICE for the whole pack, ${CAR}: Ronaldo Caiado 0.80% (vol USD 6.34M), Pablo Marçal 0.90% (vol USD 1.66M), Romeu Zema 0.15% (vol USD 5.71M), Fernando Haddad 0.05% and Tarcísio de Freitas 0.05% (vol USD 13.93M, the largest in the book).`,

  'candidates[0].analise': `PRICE at 63.50% (vol USD 8.67M accumulated), ${CAR}, down 1.00pp. THE DISTANCE to the runner-up NARROWED 1.60pp to 31.45pp, the second day running of convergence: it was 37.05pp on Aug 16 and 33.05pp on Aug 17. 🔑 THE BALLOT BOX SAYS THE OPPOSITE: BTG/Nexus of Aug 17 took him from 40% to 41% and his opponent from 35% to 36%, so the distance between the two did NOT change, it stayed at 5 points, and each move fits inside the 2pp margin. A measurement that does not narrow cannot explain a narrowing. 📌 In STATE polls today he trails in Paraná, 35% against 52% in the runoff, and leads in Pernambuco, 58% against 24%; state polls do not enter the national panel. ⛔ No superlative: the high of the 88-day series is still 66.50%, from Aug 1. 📅 Datafolha and Veritá publish on Aug 21, both already in the field.`,

  'candidates[1].analise': `PRICE at 32.05% (vol USD 8.62M accumulated), ${CAR}, up 0.60pp and a fifth day running of gains. In the SECOND PLACE contract he marks 88.50%. ⛔ NOT a record: the high of the 88-day series is 33.20%, from Jun 2. 📌 IN THE BALLOT BOX, BTG/Nexus of Aug 17 has him at 36% in the first round and 44% in the runoff, with the distance to the leader at the same 5 points. In a STATE poll in Paraná he stands at 52% against 35% in the runoff, according to Poder360 and CartaCapital, and state polls do not enter the national panel.`,

  'candidates[2].analise': `PRICE at 4.40% (vol USD 10.11M accumulated), ${CAR}, up 0.35pp. ⭐ THE STRONG MOVE WAS IN PLACEMENT: in the THIRD PLACE contract he jumped from 52.50% to 57.00%, and his distance to Caiado in that book REOPENED from 14.00pp to 20.00pp, undoing two days of convergence. 📌 THE DISAGREEMENT WITH THE BALLOT BOX CONTINUES AND IS INVERTED: BTG/Nexus of Aug 17 gives Caiado 5% and him 4%, while the market keeps him 20 points ahead in the placement contract. These are different questions: the poll measures declared intention, the contract measures probability of placement.`,

  'candidates[2].fracos[1]': `⚠️ His book is THIN, and that matters for reading the move: in the presidential contract he is worth a little over 4%, and in that range little money moves the price. The placement reading, in the third place contract, is where he carries real weight.`,

  'candidates[3].analise': `⭐ RONALDO CAIADO IS THE CROSSING OF THE DAY, AND IT IS AGAINST HIMSELF. In the contract on WINNING he more than tripled, from 0.25% to 0.80% (vol USD 6.34M), ${CAR}, and returned above the 0.5% cut the panel uses to separate price from noise. In the THIRD PLACE contract he GAVE GROUND, from 38.50% to 37.00%. Both moves are from the same day and point opposite ways. ⛔ NO SUPERLATIVE: 0.80% is a recovery from the series low, 0.50% on Aug 15, and not proximity to the high, which is 2.40%, from Jun 19; of the 86 days recorded since May 21, 84 had a value equal to or above today's. 📌 The PSD confirmed his presidential candidacy, according to Acessa.com. PABLO MARÇAL repeated 0.90%, with volume going from USD 1.21M to USD 1.66M in one day, and 🏷️ his electoral status changed today: he asked the electoral court to correct his asset declaration and declared wealth fell from R$ 7.4 billion to R$ 149.9 million, according to G1 and Valor Econômico, which belong to the same group. He remains INELIGIBLE until 2032, with campaigning allowed by injunction and registration pending. ROMEU ZEMA fell to 0.15%. TARCÍSIO remains a candidate for re-election as governor of São Paulo and HADDAD for governor of São Paulo, with their contracts at the floor.`,

  'quadroComparativo[0].m': `63.50% (vol USD 8.67M accumulated), ${CAR}`,
  'quadroComparativo[0].t': `🔴 DOWN 1.00pp, from 64.50% to 63.50%, and the distance to the runner-up NARROWED 1.60pp, to 31.45pp. It is the SECOND day running of convergence, adding up to 5.60pp since Aug 16. ⛔ No superlative: the high of the 88-day series is still 66.50%, from Aug 1, and the low is 39.50%, from Jun 2.`,
  'quadroComparativo[0].s': `Third day of the official campaign, 47 days from the first round. In a STATE poll in Paraná he trails in the runoff, 35% against 52%, according to Poder360 and CartaCapital, and leads in Pernambuco, 58% against 24%. 📌 State polls do not enter the national panel and are here as coverage. 📅 Datafolha and Veritá publish on Aug 21.`,

  'quadroComparativo[1].m': `32.05% (vol USD 8.62M accumulated), ${CAR}`,
  'quadroComparativo[1].t': `🔺 UP 0.60pp, from 31.45% to 32.05%, a fifth day running of gains, and the distance to the leader narrowed to 31.45pp. ⛔ NOT a record: the high of the 88-day series is 33.20%, from Jun 2. In the SECOND PLACE contract he marks 88.50%.`,
  'quadroComparativo[1].s': `In a STATE poll in Paraná he stands at 52% against 35% in the runoff, according to Poder360 and CartaCapital. 📌 State polls do not enter the national panel. In the national ballot box BTG/Nexus of Aug 17 has him at 36% in the first round and 44% in the runoff.`,

  'quadroComparativo[2].m': `4.40% (vol USD 10.11M accumulated), ${CAR}`,
  'quadroComparativo[2].t': `🔺 UP 0.35pp in the presidential book, from 4.05% to 4.40%. ⭐ And the strong move was in the THIRD PLACE contract: he jumped from 52.50% to 57.00%, and his distance to Caiado in that book REOPENED from 14.00pp to 20.00pp, undoing two days of convergence. ⛔ No superlative: the high of the 88-day series is 17.90%, from Jun 9.`,
  'quadroComparativo[2].s': `📌 The ballot box and the price still disagree about who is third: BTG/Nexus of Aug 17 gives Caiado 5% and him 4%, while the market keeps him far ahead in the placement contract.`,
})
