/** Mapa ES de 19/Ago/2026: captura certificada de 14:58 BRT. */
import { construir } from '../build-locale-json'

const CAR = 'lectura confirmada del 19 de ago, 14:58 BRT (17:58 UTC)'

construir('analysis-criteriosa', 'es', {
  subtitle: `ACTUALIZACIÓN 19 de ago, a 46 días de la primera vuelta y en el CUARTO DÍA DE LA CAMPAÑA OFICIAL. LA DISTANCIA ENTRE LULA Y FLÁVIO BOLSONARO SE ACORTÓ POR TERCER DÍA SEGUIDO y cerró en 30,95pp, contra 37,05pp el 16 de ago, en un libro presidencial que acumula USD 129,21M. Y el movimiento tiene un solo lado: LULA quedó quieto en 63,50% por segundo día, y quien se movió fue FLÁVIO BOLSONARO, en un sexto día seguido de alza. NINGUNA encuesta nacional nueva: la última sigue siendo la Nexus/BTG del 17 de ago (n=2.003, campo del 14 al 16 de ago, BR-03317/2026). La Datafolha nacional publica el 21 de ago y es la primera en medir a Pablo Marçal.`,

  cruzamento: `⭐ EL MOVIMIENTO DEL DÍA TIENE UN SOLO LADO, Y ESE ES EL HALLAZGO. En la ${CAR}, LULA repitió 63,50% (vol USD 8,69M), sin variación por segundo día seguido, y FLÁVIO BOLSONARO subió 0,50pp a 32,55% (vol USD 8,63M), en un sexto día seguido de alza. La distancia entre los dos se acortó a 30,95pp, TERCER día seguido de acercamiento: eran 37,05pp el 16 de ago, 33,05pp el 17 y 31,45pp el 18, o sea 6,10pp en tres días. 🔑 QUIEN ESTÁ ACORTANDO LA DISTANCIA NO ES QUIEN ESTÁ CAYENDO. El líder no perdió precio alguno en dos días; el acercamiento entero vino del segundo subiendo. ⛔ SIN SUPERLATIVO: 32,55% NO es récord. De los 88 días de la serie desde el 22 de may, 2 marcaron un valor igual o superior, y el máximo sigue en 33,20%, del 2 de jun. 📌 Y LA URNA SIGUE MUDA al respecto: ninguna encuesta nacional nueva desde el 17 de ago, y aquella midió la distancia entre los dos INALTERADA en 5 puntos. Una medición que no acorta no explica un acortamiento de 6,10pp. ⚠️ RONALDO CAIADO DEVOLVIÓ LO QUE HABÍA SUBIDO: de 0,80% a 0,55% (vol USD 6,35M), deshaciendo el alza de la víspera, y en el contrato de tercer lugar cedió de 37,00% a 36,00%. Su distancia hacia Renan Santos en ese libro se abrió más, de 20,00pp a 21,00pp. ⛔ Sin superlativo aquí tampoco: 85 de los 86 días de la serie están por encima de 0,55%. 📊 Las dos encuestas del día son ESTATALES y no entran en el panel nacional: la Real Time Big Data en el Distrito Federal, con Flávio Bolsonaro en 44% y Lula en 39% en la segunda vuelta, y la Datafolha en São Paulo. 📅 La Datafolha NACIONAL sale el 21 de ago y es la primera en incluir a Pablo Marçal, que hoy tiene un precio de 0,75% y ninguna medición de urna.`,

  'candidates[0].header': `PRECIO: 63,50% (vol USD 8,69M acumulado), ${CAR}`,
  'candidates[1].header': `PRECIO: 32,55% (vol USD 8,63M acumulado), ${CAR}`,
  'candidates[2].header': `PRECIO: 4,05% (vol USD 10,14M acumulado), ${CAR}`,
  'candidates[3].header': `PRECIO para todo el pelotón, ${CAR}: Pablo Marçal 0,75% (vol USD 1,72M), Ronaldo Caiado 0,55% (vol USD 6,35M), Romeu Zema 0,15% (vol USD 5,72M), Fernando Haddad 0,05% y Tarcísio de Freitas 0,05% (vol USD 13,95M, el mayor del libro).`,

  'candidates[0].analise': `PRECIO en 63,50% (vol USD 8,69M acumulado), ${CAR}, SIN VARIACIÓN por segundo día seguido. ⭐ LA DISTANCIA hacia el segundo se acortó 0,50pp a 30,95pp, TERCER día seguido de acercamiento, sumando 6,10pp desde el 16 de ago. 🔑 Y el acortamiento no vino de él: en dos días no perdió precio alguno, y el acercamiento entero es del adversario subiendo. 📌 LA URNA SIGUE MUDA: ninguna encuesta nacional nueva desde el 17 de ago, y aquella midió la distancia entre los dos INALTERADA en 5 puntos. Una medición que no acorta no explica un acortamiento de 6,10pp. 📊 En una encuesta ESTATAL del Distrito Federal aparece con 39% contra 44% en la segunda vuelta y es aprobado por 54% de ese electorado, según CNN Brasil; la estatal no entra en el panel nacional. ⛔ Sin superlativo: el máximo de la serie de 88 días sigue en 66,50%, del 1 de ago. 📅 Datafolha nacional el 21 de ago.`,

  'candidates[1].analise': `PRECIO en 32,55% (vol USD 8,63M acumulado), ${CAR}, alza de 0,50pp y SEXTO día seguido subiendo. ⭐ Es el único responsable del acortamiento de la distancia en los dos últimos días, porque el líder quedó quieto. ⛔ NO ES RÉCORD: de los 88 días de la serie desde el 22 de may, 2 marcaron un valor igual o superior a 32,55%, y el máximo sigue en 33,20%, del 2 de jun. 📌 EN EL TABLERO decidió limitar su participación en debates de la primera vuelta y comparecer solo cuando Lula esté presente, según Folha de S.Paulo y O Globo. 📊 En una encuesta ESTATAL del Distrito Federal aparece con 44% contra 39% en la segunda vuelta; la estatal no entra en el panel nacional. En la urna nacional la Nexus/BTG del 17 de ago lo tiene en 36% en la primera vuelta y 44% en la segunda.`,

  'candidates[2].analise': `PRECIO en 4,05% (vol USD 10,14M acumulado), ${CAR}, caída de 0,35pp que devuelve lo que subió la víspera. ⚠️ Sigue cerca del piso: 86 de los 88 días de la serie están por encima de 4,05%, y el piso se tocó el 18 de ago, con 3,60%. ⭐ EN EL CONTRATO DE TERCER LUGAR quedó ESTABLE en 57,00% y aun así ABRIÓ distancia, de 20,00pp a 21,00pp, porque quien cedió fue Ronaldo Caiado. 📌 La discrepancia con la urna continúa sin resolución: la Nexus/BTG del 17 de ago da 5% a Caiado y 4% a él, mientras el mercado lo mantiene 21 puntos adelante en la posición. Son preguntas distintas: la encuesta mide intención declarada, el contrato mide probabilidad de posición.`,

  'candidates[3].analise': `⚠️ RONALDO CAIADO DEVOLVIÓ LO QUE HABÍA SUBIDO. En el contrato de VICTORIA cayó de 0,80% a 0,55% (vol USD 6,35M), ${CAR}, deshaciendo el alza de la víspera, y en el de TERCER LUGAR cedió de 37,00% a 36,00%. ⛔ Sin superlativo: 85 de los 86 días de la serie desde el 22 de may están por encima de 0,55%, y el máximo es 2,40%, del 19 de jun. El PSD confirmó su candidatura a la Presidencia. 🏷️ PABLO MARÇAL cayó a 0,75% (vol USD 1,72M), con el volumen aún subiendo, de USD 1,66M a USD 1,72M en un día. Sigue INELEGIBLE hasta 2032, con campaña habilitada por medida cautelar y registro pendiente, y la Datafolha del 21 de ago es la PRIMERA en medirlo: hoy tiene precio y ninguna medición de urna. ROMEU ZEMA sigue en 0,15%, por debajo del corte de 0,5%. TARCÍSIO sigue como candidato a la reelección al gobierno de São Paulo y HADDAD al gobierno de São Paulo, con sus contratos en el piso y el de Tarcísio cargando USD 13,95M, el mayor volumen de todo el libro presidencial.`,

  'quadroComparativo[0].m': `63,50% (vol USD 8,69M acumulado), ${CAR}`,
  'quadroComparativo[0].t': `➖ SIN VARIACIÓN por segundo día seguido, en 63,50%. La distancia hacia el segundo se acortó 0,50pp a 30,95pp, TERCER día seguido de acercamiento, sumando 6,10pp desde el 16 de ago. 🔑 Y el acortamiento no vino de él: no perdió precio alguno, quien subió fue el adversario. ⛔ Sin superlativo: el máximo de la serie de 88 días sigue en 66,50%, del 1 de ago, y 23 de los 88 días están en 63,50% o por encima.`,
  'quadroComparativo[0].s': `Cuarto día de campaña oficial, a 46 días de la primera vuelta. En una encuesta ESTATAL del Distrito Federal aparece con 39% contra 44% en la segunda vuelta, y es aprobado por 54% contra 45% de desaprobación en ese electorado, según CNN Brasil. 📌 La estatal no entra en el panel nacional y está aquí como cobertura. 📅 Datafolha nacional el 21 de ago.`,

  'quadroComparativo[1].m': `32,55% (vol USD 8,63M acumulado), ${CAR}`,
  'quadroComparativo[1].t': `🔺 ALZA de 0,50pp, de 32,05% a 32,55%, SEXTO día seguido subiendo, y único responsable del acortamiento de la distancia. ⛔ NO es récord: de los 88 días de la serie desde el 22 de may, 2 marcaron un valor igual o superior a 32,55%, y el máximo sigue en 33,20%, del 2 de jun.`,
  'quadroComparativo[1].s': `Decidió limitar su participación en debates de la primera vuelta y comparecer solo cuando Lula esté presente, según Folha de S.Paulo y O Globo. En una encuesta ESTATAL del Distrito Federal aparece con 44% contra 39% en la segunda vuelta, según CNN Brasil. 📌 La estatal no entra en el panel nacional.`,

  'quadroComparativo[2].m': `4,05% (vol USD 10,14M acumulado), ${CAR}`,
  'quadroComparativo[2].t': `🔻 CAÍDA de 0,35pp, de 4,40% a 4,05%, devolviendo lo que subió la víspera. ⚠️ Sigue cerca del piso de la serie: 86 de los 88 días registrados desde el 22 de may están por encima de 4,05%, y el piso se tocó el 18 de ago, con 3,60%. En el contrato de TERCER LUGAR quedó ESTABLE en 57,00%, y su distancia hacia Caiado en ese libro ABRIÓ de 20,00pp a 21,00pp, porque quien cedió fue el otro.`,
  'quadroComparativo[2].s': `📌 La discrepancia con la urna continúa y nadie la resolvió hoy: la Nexus/BTG del 17 de ago da 5% a Caiado y 4% a él, y el mercado lo mantiene 21 puntos adelante en el contrato de posición. Son preguntas distintas.`,

  'quadroComparativo[3].m': `0,55% (vol USD 6,35M acumulado), ${CAR}`,
  'quadroComparativo[3].t': `🔻 DEVOLVIÓ lo que había subido: de 0,80% a 0,55%, deshaciendo el alza de la víspera. Sigue por encima del corte de 0,5% que el panel usa para separar precio de ruido, pero por poco. En el contrato de TERCER LUGAR cedió de 37,00% a 36,00%. ⛔ Sin superlativo: 85 de los 86 días de la serie desde el 22 de may están por encima de 0,55%, y el máximo es 2,40%, del 19 de jun.`,
  'quadroComparativo[3].s': `El PSD confirmó su candidatura a la Presidencia. 📌 En la intención declarada sigue siendo el tercer nombre, con 5% en la Nexus/BTG del 17 de ago contra 4% de Renan Santos, y en el precio de posición sigue 21 puntos detrás de él.`,

  'quadroComparativo[4].m': `0,15% (vol USD 5,72M acumulado), ${CAR}`,
  'quadroComparativo[4].t': `➖ SIN VARIACIÓN en 0,15%, por debajo del corte de 0,5% que el panel usa para separar precio de ruido. En ese rango la variación no sostiene interpretación. En el contrato de tercer lugar marca 4,85%.`,
  'quadroComparativo[4].s': `En la urna la Nexus/BTG del 17 de ago le da 4% en la primera vuelta, empatado con Renan Santos dentro del margen de 2pp, y esa lectura vale por sí sola, independiente del precio.`,

  'quadroComparativo[5].m': `3,40% (vol USD 84 mil), ${CAR}`,
  'quadroComparativo[5].t': `➖ QUIETO en 3,40%, sin variación desde el 17 de ago.`,
  'quadroComparativo[5].s': `Contrato sobre la remoción de un ministro del Supremo por impeachment antes de 2027, mantenido en el panel como termómetro institucional.`,
})
