/** Mapa EN de 19/Ago/2026: captura certificada de 14:58 BRT. */
import { construir } from '../build-locale-json'

const CAR = 'confirmed reading of Aug 19, 2:58 PM BRT (5:58 PM UTC)'

construir('analysis-criteriosa', 'en', {
  subtitle: `UPDATE Aug 19, 46 days from the first round and on the FOURTH DAY OF THE OFFICIAL CAMPAIGN. THE DISTANCE BETWEEN LULA AND FLÁVIO BOLSONARO NARROWED FOR THE THIRD DAY RUNNING and closed at 30.95pp, against 37.05pp on Aug 16, in a presidential book that has accumulated USD 129.21M. And the move has only one side: LULA stayed at 63.50% for the second day, and the one who moved was FLÁVIO BOLSONARO, on a sixth day running of gains. NO new national poll: the latest is still BTG/Nexus of Aug 17 (n=2,003, field Aug 14 to 16, BR-03317/2026). The national Datafolha publishes on Aug 21 and is the first to measure Pablo Marçal.`,

  cruzamento: `⭐ THE MOVE OF THE DAY HAS ONLY ONE SIDE, AND THAT IS THE FINDING. In the ${CAR}, LULA repeated 63.50% (vol USD 8.69M), unchanged for a second day running, and FLÁVIO BOLSONARO rose 0.50pp to 32.55% (vol USD 8.63M), on a sixth day running of gains. The distance between them narrowed to 30.95pp, the THIRD day running of convergence: it was 37.05pp on Aug 16, 33.05pp on Aug 17 and 31.45pp on Aug 18, that is 6.10pp in three days. 🔑 THE ONE NARROWING THE DISTANCE IS NOT THE ONE FALLING. The leader lost no price at all in two days; the entire convergence came from the runner-up rising. ⛔ NO SUPERLATIVE: 32.55% is NOT a record. Of the 88 days in the series since May 22, 2 posted a value equal to or above it, and the high is still 33.20%, from Jun 2. 📌 AND THE BALLOT BOX STAYS SILENT about it: no new national poll since Aug 17, and that one measured the distance between the two UNCHANGED at 5 points. A measurement that does not narrow cannot explain a narrowing of 6.10pp. ⚠️ RONALDO CAIADO GAVE BACK WHAT HE HAD GAINED: from 0.80% to 0.55% (vol USD 6.35M), undoing the previous day's rise, and in the third place contract he gave ground from 37.00% to 36.00%. His distance to Renan Santos in that book widened further, from 20.00pp to 21.00pp. ⛔ No superlative here either: 85 of the 86 days in the series are above 0.55%. 📊 The two polls of the day are STATE polls and do not enter the national panel: Real Time Big Data in the Federal District, with Flávio Bolsonaro at 44% and Lula at 39% in the runoff, and Datafolha in São Paulo. 📅 The NATIONAL Datafolha comes out on Aug 21 and is the first to include Pablo Marçal, who today has a price of 0.75% and no ballot-box measurement.`,

  'candidates[0].header': `PRICE: 63.50% (vol USD 8.69M accumulated), ${CAR}`,
  'candidates[1].header': `PRICE: 32.55% (vol USD 8.63M accumulated), ${CAR}`,
  'candidates[2].header': `PRICE: 4.05% (vol USD 10.14M accumulated), ${CAR}`,
  'candidates[3].header': `PRICE for the whole pack, ${CAR}: Pablo Marçal 0.75% (vol USD 1.72M), Ronaldo Caiado 0.55% (vol USD 6.35M), Romeu Zema 0.15% (vol USD 5.72M), Fernando Haddad 0.05% and Tarcísio de Freitas 0.05% (vol USD 13.95M, the largest in the book).`,

  'candidates[0].analise': `PRICE at 63.50% (vol USD 8.69M accumulated), ${CAR}, UNCHANGED for a second day running. ⭐ THE DISTANCE to the runner-up narrowed 0.50pp to 30.95pp, the THIRD day running of convergence, adding up to 6.10pp since Aug 16. 🔑 And the narrowing did not come from him: in two days he lost no price at all, and the entire convergence is the opponent rising. 📌 THE BALLOT BOX STAYS SILENT: no new national poll since Aug 17, and that one measured the distance between the two UNCHANGED at 5 points. A measurement that does not narrow cannot explain a narrowing of 6.10pp. 📊 In a STATE poll in the Federal District he stands at 39% against 44% in the runoff and is approved by 54% of that electorate, according to CNN Brasil; state polls do not enter the national panel. ⛔ No superlative: the high of the 88-day series is still 66.50%, from Aug 1. 📅 National Datafolha on Aug 21.`,

  'candidates[1].analise': `PRICE at 32.55% (vol USD 8.63M accumulated), ${CAR}, up 0.50pp and a SIXTH day running of gains. ⭐ He is solely responsible for the narrowing of the distance over the last two days, because the leader stood still. ⛔ NOT A RECORD: of the 88 days in the series since May 22, 2 posted a value equal to or above 32.55%, and the high is still 33.20%, from Jun 2. 📌 ON THE BOARD he decided to limit his participation in first round debates and to attend only when Lula is present, according to Folha de S.Paulo and O Globo. 📊 In a STATE poll in the Federal District he stands at 44% against 39% in the runoff; state polls do not enter the national panel. In the national ballot box BTG/Nexus of Aug 17 has him at 36% in the first round and 44% in the runoff.`,

  'candidates[2].analise': `PRICE at 4.05% (vol USD 10.14M accumulated), ${CAR}, down 0.35pp, giving back what he gained the previous day. ⚠️ He remains close to the low: 86 of the 88 days in the series are above 4.05%, and the low was touched on Aug 18, at 3.60%. ⭐ IN THE THIRD PLACE CONTRACT he was STABLE at 57.00% and still WIDENED his lead, from 20.00pp to 21.00pp, because the one who gave ground was Ronaldo Caiado. 📌 The disagreement with the ballot box continues unresolved: BTG/Nexus of Aug 17 gives Caiado 5% and him 4%, while the market keeps him 21 points ahead on placement. These are different questions: the poll measures declared intention, the contract measures probability of placement.`,

  'candidates[3].analise': `⚠️ RONALDO CAIADO GAVE BACK WHAT HE HAD GAINED. In the contract on WINNING he fell from 0.80% to 0.55% (vol USD 6.35M), ${CAR}, undoing the previous day's rise, and in the THIRD PLACE one he gave ground from 37.00% to 36.00%. ⛔ No superlative: 85 of the 86 days in the series since May 22 are above 0.55%, and the high is 2.40%, from Jun 19. The PSD confirmed his presidential candidacy. 🏷️ PABLO MARÇAL fell to 0.75% (vol USD 1.72M), with volume still rising, from USD 1.66M to USD 1.72M in one day. He remains INELIGIBLE until 2032, with campaigning allowed by injunction and registration pending, and Datafolha of Aug 21 is the FIRST to measure him: today he has a price and no ballot-box measurement. ROMEU ZEMA stays at 0.15%, below the 0.5% cut. TARCÍSIO remains a candidate for re-election as governor of São Paulo and HADDAD for governor of São Paulo, with their contracts at the floor and Tarcísio's carrying USD 13.95M, the largest volume in the whole presidential book.`,

  'quadroComparativo[0].m': `63.50% (vol USD 8.69M accumulated), ${CAR}`,
  'quadroComparativo[0].t': `➖ UNCHANGED for a second day running, at 63.50%. The distance to the runner-up narrowed 0.50pp to 30.95pp, the THIRD day running of convergence, adding up to 6.10pp since Aug 16. 🔑 And the narrowing did not come from him: he lost no price at all, the one who rose was the opponent. ⛔ No superlative: the high of the 88-day series is still 66.50%, from Aug 1, and 23 of the 88 days are at 63.50% or above.`,
  'quadroComparativo[0].s': `Fourth day of the official campaign, 46 days from the first round. In a STATE poll in the Federal District he stands at 39% against 44% in the runoff, and is approved by 54% against 45% disapproval in that electorate, according to CNN Brasil. 📌 State polls do not enter the national panel and are here as coverage. 📅 National Datafolha on Aug 21.`,

  'quadroComparativo[1].m': `32.55% (vol USD 8.63M accumulated), ${CAR}`,
  'quadroComparativo[1].t': `🔺 UP 0.50pp, from 32.05% to 32.55%, a SIXTH day running of gains, and solely responsible for the narrowing of the distance. ⛔ NOT a record: of the 88 days in the series since May 22, 2 posted a value equal to or above 32.55%, and the high is still 33.20%, from Jun 2.`,
  'quadroComparativo[1].s': `He decided to limit his participation in first round debates and to attend only when Lula is present, according to Folha de S.Paulo and O Globo. In a STATE poll in the Federal District he stands at 44% against 39% in the runoff, according to CNN Brasil. 📌 State polls do not enter the national panel.`,

  'quadroComparativo[2].m': `4.05% (vol USD 10.14M accumulated), ${CAR}`,
  'quadroComparativo[2].t': `🔻 DOWN 0.35pp, from 4.40% to 4.05%, giving back what he gained the previous day. ⚠️ He remains close to the low of the series: 86 of the 88 days recorded since May 22 are above 4.05%, and the low was touched on Aug 18, at 3.60%. In the THIRD PLACE contract he was STABLE at 57.00%, and his distance to Caiado in that book WIDENED from 20.00pp to 21.00pp, because the one who gave ground was the other.`,
  'quadroComparativo[2].s': `📌 The disagreement with the ballot box continues and nobody resolved it today: BTG/Nexus of Aug 17 gives Caiado 5% and him 4%, and the market keeps him 21 points ahead in the placement contract. These are different questions.`,

  'quadroComparativo[3].m': `0.55% (vol USD 6.35M accumulated), ${CAR}`,
  'quadroComparativo[3].t': `🔻 GAVE BACK what he had gained: from 0.80% to 0.55%, undoing the previous day's rise. He stays above the 0.5% cut the panel uses to separate price from noise, but barely. In the THIRD PLACE contract he gave ground from 37.00% to 36.00%. ⛔ No superlative: 85 of the 86 days in the series since May 22 are above 0.55%, and the high is 2.40%, from Jun 19.`,
  'quadroComparativo[3].s': `The PSD confirmed his presidential candidacy. 📌 In declared intention he is still the third name, with 5% in BTG/Nexus of Aug 17 against Renan Santos's 4%, and on placement price he is still 21 points behind him.`,

  'quadroComparativo[4].m': `0.15% (vol USD 5.72M accumulated), ${CAR}`,
  'quadroComparativo[4].t': `➖ UNCHANGED at 0.15%, below the 0.5% cut the panel uses to separate price from noise. In that range a move does not sustain interpretation. In the third place contract he marks 4.85%.`,
  'quadroComparativo[4].s': `In the ballot box BTG/Nexus of Aug 17 gives him 4% in the first round, tied with Renan Santos inside the 2pp margin, and that reading stands on its own, independent of the price.`,

  'quadroComparativo[5].m': `3.40% (vol USD 84 thousand), ${CAR}`,
  'quadroComparativo[5].t': `➖ FLAT at 3.40%, unchanged since Aug 17.`,
  'quadroComparativo[5].s': `Contract on a Supreme Court justice being removed by impeachment before 2027, kept in the panel as an institutional thermometer.`,
})
