/**
 * Correção ES de 25/Ago: a sabatina do Zema no Jornal Nacional foi em 24/Ago,
 * não em 25/Ago, e quem foi ao JN em 25/Ago foi Ronaldo Caiado. Lula e Flávio
 * confirmaram presença para 27 e 28/Ago.
 * Convenções ES: VÍRGULA decimal e PONTO de milhar.
 */
import { construir } from '../build-locale-json'

const NEXUS = 'BTG/Nexus del 24 de ago (n=2.006, campo del 21 al 23 de ago, registro TSE BR-09028/2026)'

construir('analysis-criteriosa', 'es', {
  'candidates[0].fortes[3]':
    `Confirmó presencia en la entrevista del Jornal Nacional, fijada para el 27 de ago, según Valor Econômico, Poder360 y Metrópoles del 25 de ago. Es su primera aparición confirmada en un formato de confrontación tras faltar al debate de Band el 23 de ago.`,
  'candidates[0].analise':
    `Su precio lleva dos días estancado en 62,50% (vol USD 8,97M acumulado) y la distancia hacia el segundo volvió a abrirse, de 27,45pp a 27,85pp, sin que él ganara nada: quien cedió fue el otro lado. Contra la serie entera desde el 14 de abr, la menor distancia jamás registrada entre los dos es negativa, de 8 puntos a favor del segundo el 6 de may, así que estrecharse y abrirse en este rango son movimientos comunes de este libro y no un cambio de cuadro. La encuesta más reciente sigue siendo la BTG/Nexus del 24 de ago, que lo da en 41% en la primera vuelta y por delante en la segunda por 46% a 45%, y este martes no hubo nacional nueva. Lo que el día agrega es de agenda y no de número: confirmó presencia en la entrevista del Jornal Nacional, fijada para el 27 de ago, tras faltar al debate del 23 de ago.`,
  'candidates[1].fortes[4]':
    `Confirmó presencia en la entrevista del Jornal Nacional, fijada para el 28 de ago en vivo desde los estudios de Río, según Valor Econômico, Poder360 y Metrópoles del 25 de ago, tras haber condicionado su presencia en el debate de Band a la asistencia del rival.`,
  'candidates[3].caiado.fortes':
    `⭐ LA MAYOR SUBIDA DEL PANEL EN EL DÍA ES SUYA, y está en el contrato de tercer lugar de la primera vuelta: 3,00pp, llegando a 42,00%. El movimiento acerca el precio al orden que las encuestas ya mostraban, porque la ${NEXUS} lo mantiene en 5% en la primera vuelta frente a 3% de Renan Santos. Esa misma encuesta lo probó en segunda vuelta contra el primero y midió 46% a 42%, según Metrópoles. ⭐ Y ÉL FUE EL ENTREVISTADO DEL JORNAL NACIONAL EL 25 DE AGO, el segundo de la serie que Romeu Zema abrió el 24 de ago, con 40 minutos frente a Renata Vasconcellos y César Tralli. También participó del primer debate presidencial, el 23 de ago.`,
  'candidates[3].zema.fortes':
    `⭐ SU EXPOSICIÓN FUE EL 24 DE AGO Y LA COBERTURA CIRCULÓ EL 25 DE AGO: abrió la serie de entrevistas del Jornal Nacional, 40 minutos con Renata Vasconcellos y César Tralli, según BBC y O Globo. El 25 de ago fue entrevistado de nuevo, esta vez por CBN, O Globo y Valor, donde defendió cambios en el pacto federativo. La ${NEXUS} lo mantiene en 3% en la primera vuelta, el mismo nivel que la casa viene midiendo desde el 3 de ago.`,
  'candidates[3].analise':
    `El pelotón tiene un nombre que se movió de verdad hoy, y no fue en el libro presidencial. Ronaldo Caiado subió 3,00pp en el contrato de tercer lugar y llegó a 42,00%, la mayor subida del panel en el día, mientras en el presidencial cedía 0,15pp hasta 0,55% (vol USD 6,59M acumulado). El movimiento acerca el precio al orden que las encuestas vienen registrando, que lo pone por delante de Renan Santos por 5% a 3%, sin que el contrato se invirtiera: el rival sigue con 51,50%. Romeu Zema, en 0,25% (vol USD 5,98M acumulado), abrió la serie de entrevistas del Jornal Nacional el 24 de ago y fue entrevistado por CBN, O Globo y Valor el 25 de ago, y su precio no registró nada de eso. Fernando Haddad sigue en 0,05% (vol USD 7,30M acumulado), sin variación.`,
  'candidates[3].fortes[0]':
    `⭐ Ronaldo Caiado hizo la mayor subida del día en cualquier libro del panel: 3,00pp en el contrato de tercer lugar, llegando a 42,00%. El mismo día fue el entrevistado del Jornal Nacional.`,
  'candidates[3].fortes[2]':
    `Romeu Zema abrió la serie de entrevistas del Jornal Nacional el 24 de ago, con 40 minutos, y el 25 de ago fue entrevistado por CBN, O Globo y Valor.`,
  'quadroComparativo[0].s':
    `Séptimo día de campaña oficial, a 43 días de la primera vuelta. Confirmó presencia en la entrevista del Jornal Nacional, fijada para el 27 de ago, según Valor Econômico y Poder360, tras faltar al debate de Band el 23 de ago.`,
  'quadroComparativo[1].s':
    `Confirmó presencia en la entrevista del Jornal Nacional, fijada para el 28 de ago, según Valor Econômico y Poder360. 🏛️ O Globo del 25 de ago informa que administra el desgaste del caso Dark Horse tras la decisión del ministro Flávio Dino, y dejó las explicaciones a la productora.`,
  'quadroComparativo[3].p':
    `La BTG/Nexus lo mantiene en 5%, por delante de Renan Santos en las encuestas. Esa misma encuesta probó la segunda vuelta contra Lula y midió 46% a 42%, según Metrópoles. Participó del debate del 23 de ago y fue el entrevistado del Jornal Nacional el 25 de ago.`,
  'quadroComparativo[3].s':
    `El precio del tercer lugar se movió hacia el orden que las encuestas ya mostraban, que lo pone por delante por 5% a 3%. El orden del contrato no se invirtió: el rival sigue con 51,50%. ⭐ Y fue el entrevistado del Jornal Nacional este martes, el segundo de una serie de seis que va hasta el 29 de ago.`,
  'cruzamento':
    `El día no tuvo encuesta nacional nueva y sí tuvo movimiento de precio, y los dos hechos juntos definen la lectura. La tanda divulgada este martes por Quaest es toda estatal, cubriendo Rio Grande do Norte, Paraná, Rio Grande do Sul, Alagoas, Maranhão y Santa Catarina, y el panel solo cruza ámbito nacional. La encuesta más reciente del país sigue siendo la BTG/Nexus del 24 de ago.\n\nEn el libro presidencial, que suma USD 132,88M, el primero quedó estancado en 62,50% por segundo día seguido y el segundo cedió 0,40pp, hasta 34,65%. La distancia entre los dos volvió a abrirse, de 27,45pp a 27,85pp, y se abrió sin que el líder ganara nada. Contra la serie entera desde el 14 de abr, verificada en la copia de seguridad de la base y no por la ventana de la API, la menor distancia jamás registrada entre los dos es negativa, de 8 puntos a favor del segundo el 6 de may. Un movimiento en este rango es rutina de este libro.\n\n⭐ EL HALLAZGO DEL DÍA ESTÁ EN EL CONTRATO DE TERCER LUGAR, y es de convergencia entre instrumentos. Renan Santos cedió 2,50pp hasta 51,50%, mientras Ronaldo Caiado subía 3,00pp hasta 42,00%, la mayor subida del panel en el día. La brecha entre los dos cayó de 15,00pp a 9,50pp. Las encuestas vienen diciendo lo contrario del precio en ese punto desde hace semanas, con Caiado en 5% y Renan Santos en 3% en la ronda más reciente, y este martes el precio se movió hacia las encuestas sin que el orden del contrato se invirtiera.\n\n⚠️ LA SALVEDAD QUE IMPONE LA SERIE, y sin ella la lectura de arriba se vuelve un titular falso: 9,50pp no es la menor brecha jamás registrada en este contrato. El mismo libro estuvo en 3,5pp el 22 de ago a las 19:30, y el cierre de ese día marcaba 15,5pp. Quien mira solo el cierre de cada día no ve el piso, y habría concluido que hoy es mínimo de serie cuando no lo es.\n\nEl segundo contrato del segundo fue en dirección opuesta a su presidencial: en el libro de segundo lugar de la primera vuelta subió 2,00pp y llegó a 87,50%. El mercado quedó más convencido de que llega a la segunda vuelta y algo menos convencido de que gana. Son contratos distintos, que miden desenlaces distintos, y el panel no resta uno del otro.\n\nEn el terreno de los hechos, el día tuvo una confirmación y un acto de investigación. Los dos primeros confirmaron presencia en las entrevistas del Jornal Nacional, Lula el 27 de ago y Flávio Bolsonaro el 28 de ago, según Valor Econômico, Poder360 y Metrópoles, tras haber faltado ambos al debate de Band el 23 de ago. La serie empezó el 24 de ago con Romeu Zema y tuvo a Ronaldo Caiado el 25 de ago. Y la Policía Federal hizo un allanamiento en el Instituto de Previsión de Campo Grande por aportes en el Banco Master, según Folha de S.Paulo y O Globo. Ninguno de los dos movió precio.`,
})
