/**
 * Correção EN de 25/Ago: a sabatina do Zema no Jornal Nacional foi em 24/Ago,
 * não em 25/Ago, e quem foi ao JN em 25/Ago foi Ronaldo Caiado. Lula e Flávio
 * confirmaram presença para 27 e 28/Ago.
 * Convenções EN: PONTO decimal e VÍRGULA de milhar.
 */
import { construir } from '../build-locale-json'

const STAMP = 'confirmed reading of Aug 25, 3:22 PM BRT (6:22 PM UTC)'
const NEXUS = 'BTG/Nexus of Aug 24 (n=2,006, field Aug 21 to 23, TSE registration BR-09028/2026)'

construir('analysis-criteriosa', 'en', {
  'candidates[0].fortes[3]':
    `He confirmed he will take part in the Jornal Nacional interview, set for Aug 27, according to Valor Econômico, Poder360 and Metrópoles of Aug 25. It is his first confirmed appearance in a confrontational format after skipping the Band debate on Aug 23.`,
  'candidates[0].analise':
    `His price has been frozen for two days at 62.50% (vol USD 8.97M accumulated) and the distance to the runner-up widened again, from 27.45pp to 27.85pp, without him gaining anything: it was the other side that gave ground. Against the full series since Apr 14, the narrowest distance ever recorded between the two is negative, 8 points in the runner-up's favour on May 6, so narrowing and widening in this range are ordinary moves for this book and not a change of picture. The most recent poll is still the BTG/Nexus of Aug 24, which puts him at 41% in the first round and ahead in the runoff by 46% to 45%, and this Tuesday there was no new national poll. What the day adds is about the calendar and not about numbers: he confirmed he will take part in the Jornal Nacional interview, set for Aug 27, after skipping the Aug 23 debate.`,
  'candidates[1].fortes[4]':
    `He confirmed he will take part in the Jornal Nacional interview, set for Aug 28, live from the network's Rio studios, according to Valor Econômico, Poder360 and Metrópoles of Aug 25, after having made his presence at the Band debate conditional on his rival showing up.`,
  'candidates[3].caiado.fortes':
    `⭐ THE LARGEST GAIN ON THE PANEL TODAY IS HIS, and it is in the first-round third-place contract: 3.00pp, reaching 42.00%. The move brings the price closer to the order the polling already showed, because the ${NEXUS} keeps him at 5% in the first round against 3% for Renan Santos. That same poll tested him in a runoff against the front-runner and measured 46% to 42%, according to Metrópoles. ⭐ AND HE WAS THE JORNAL NACIONAL INTERVIEWEE ON AUG 25, the second in the series Romeu Zema opened on Aug 24, with 40 minutes facing Renata Vasconcellos and César Tralli. He also took part in the first presidential debate, on Aug 23.`,
  'candidates[3].zema.fortes':
    `⭐ HIS EXPOSURE WAS ON AUG 24 AND THE COVERAGE CIRCULATED ON AUG 25: he opened the Jornal Nacional interview series, 40 minutes with Renata Vasconcellos and César Tralli, according to BBC and O Globo. On Aug 25 he was questioned again, this time by CBN, O Globo and Valor, where he argued for changes to the federal revenue-sharing pact. The ${NEXUS} keeps him at 3% in the first round, the same level the house has been measuring since Aug 3.`,
  'candidates[3].analise':
    `The pack has one name that genuinely moved today, and it was not in the presidential book. Ronaldo Caiado rose 3.00pp in the third-place contract and reached 42.00%, the largest gain on the panel today, while in the presidential book he gave back 0.15pp to 0.55% (vol USD 6.59M accumulated). The move brings the price closer to the order the polling has been recording, which puts him ahead of Renan Santos by 5% to 3%, without the contract flipping: his rival still holds 51.50%. Romeu Zema, at 0.25% (vol USD 5.98M accumulated), opened the Jornal Nacional interview series on Aug 24 and was questioned by CBN, O Globo and Valor on Aug 25, and his price recorded none of it. Fernando Haddad remains at 0.05% (vol USD 7.30M accumulated), unchanged.`,
  'candidates[3].fortes[0]':
    `⭐ Ronaldo Caiado posted the largest gain of the day in any book on the panel: 3.00pp in the third-place contract, reaching 42.00%. On the same day he was the Jornal Nacional interviewee.`,
  'candidates[3].fortes[2]':
    `Romeu Zema opened the Jornal Nacional interview series on Aug 24, with 40 minutes, and on Aug 25 he was questioned by CBN, O Globo and Valor.`,
  'quadroComparativo[0].s':
    `Seventh day of the official campaign, 43 days from the first round. He confirmed he will take part in the Jornal Nacional interview, set for Aug 27, according to Valor Econômico and Poder360, after skipping the Band debate on Aug 23.`,
  'quadroComparativo[1].s':
    `He confirmed he will take part in the Jornal Nacional interview, set for Aug 28, according to Valor Econômico and Poder360. 🏛️ O Globo of Aug 25 reports that he is managing the fallout from the Dark Horse case after Justice Flávio Dino's decision, and left the explaining to the production company.`,
  'quadroComparativo[3].p':
    `The BTG/Nexus keeps him at 5%, ahead of Renan Santos in the polling. That same poll tested the runoff against Lula and measured 46% to 42%, according to Metrópoles. He took part in the Aug 23 debate and was the Jornal Nacional interviewee on Aug 25.`,
  'quadroComparativo[3].s':
    `The third-place price moved toward the order the polling already showed, which puts him ahead at 5% to 3%. The contract's order did not flip: his rival still holds 51.50%. ⭐ And he was the Jornal Nacional interviewee this Tuesday, the second in a series of six running through Aug 29.`,
  'cruzamento':
    `The day had no new national poll and did have price movement, and the two facts together define the reading. The batch Quaest released this Tuesday is entirely state-level, covering Rio Grande do Norte, Paraná, Rio Grande do Sul, Alagoas, Maranhão and Santa Catarina, and this panel only cross-references national scope. The country's most recent poll is still the BTG/Nexus of Aug 24.\n\nIn the presidential book, which totals USD 132.88M, the front-runner stood still at 62.50% for a second straight day and the runner-up gave back 0.40pp, to 34.65%. The distance between the two widened again, from 27.45pp to 27.85pp, and it widened without the leader gaining anything. Against the full series since Apr 14, checked in the database backup rather than through the API window, the narrowest distance ever recorded between the two is negative, 8 points in the runner-up's favour on May 6. Movement in this range is routine for this book.\n\n⭐ THE FINDING OF THE DAY IS IN THE THIRD-PLACE CONTRACT, and it is about instruments converging. Renan Santos gave back 2.50pp to 51.50%, while Ronaldo Caiado rose 3.00pp to 42.00%, the largest gain on the panel today. The gap between the two fell from 15.00pp to 9.50pp. The polling has been saying the opposite of the price on this point for weeks, with Caiado at 5% and Renan Santos at 3% in the most recent round, and this Tuesday the price moved toward the polling without the contract's order flipping.\n\n⚠️ THE CAVEAT THE SERIES IMPOSES, and without it the reading above becomes a false headline: 9.50pp is not the narrowest gap ever recorded in this contract. The same book was at 3.5pp on Aug 22 at 7:30 PM, and that day's close read 15.5pp. Anyone looking only at daily closes does not see the floor, and would have concluded today is a series low when it is not.\n\nThe runner-up's second contract moved the opposite way from his presidential one: in the first-round second-place book he rose 2.00pp and reached 87.50%. The market grew more convinced he makes the runoff and slightly less convinced he wins. These are different contracts, measuring different outcomes, and the panel does not subtract one from the other.\n\nOn the factual side, the day brought a confirmation and an investigative act. The top two candidates confirmed they will take part in the Jornal Nacional interviews, Lula on Aug 27 and Flávio Bolsonaro on Aug 28, according to Valor Econômico, Poder360 and Metrópoles, after both skipped the Band debate on Aug 23. The series opened on Aug 24 with Romeu Zema and had Ronaldo Caiado on Aug 25. And the Federal Police carried out a search and seizure at the Campo Grande Pension Institute over money placed with Banco Master, according to Folha de S.Paulo and O Globo. Neither moved a price.`,
})
