/**
 * Mapa EN de 26/Ago/2026 para o polls-data do painel do Brasil.
 * Entram: as DUAS nacionais novas (Gerp e Indexa/Broadcast), o instituto novo no
 * cadastro, e o bloco do grafo, cuja nota mudou e cujas amplitudes de 30 dias
 * foram recalculadas.
 * Convenções EN: PONTO decimal e VÍRGULA de milhar.
 * ⛔ `updatedAt` e `lastUpdate` NÃO se traduzem.
 * 🏷️ `pesquisa` é `poll`, nunca `research`; `urna` é `polling`.
 */
import { construir } from '../build-locale-json'

construir('polls-data', 'en', {
  'polls[0].note':
    `Gerp national poll released on Aug 26, registration BR-03547/2026, with 2,400 interviews and a 2pp margin at 95% confidence, costing R$ 20,000 from the firm's own funds. Checked against Poder360 and Gazeta do Povo, with the registration matching in both. ⭐ IT IS THE FIRST IN OUR TABLE IN WHICH FLÁVIO COMES OUT AHEAD IN THE FIRST ROUND, at 38% against Lula's 37%, inside the margin. The only other one in which he was not behind is Gerp's own poll of Aug 11, which showed a 38 to 38 tie. 📊 THE COMPARISON WITH THE HOUSE ITSELF: in the runoff the distance went from 2 points (Flávio 45 x Lula 43, registration BR-08045/2026, fieldwork Aug 6 to 10) to 5 points now, and in the first round Lula gave up 1 point in the same tracker. ⚠️ FILED IS NOT PUBLISHED, and here the two diverge: the TSE filing declares fieldwork from Aug 20 to 23 and publication expected on Aug 25, and the institute released it on Aug 26 reporting fieldwork from Aug 21 to 25. The table follows what the institute published, and the divergence is declared. 🔀 AND IT CAME OUT ON THE SAME DAY AS INDEXA, POINTING THE OTHER WAY: Gerp has Flávio winning the runoff by 5 and Indexa has Lula winning it by 5, with overlapping fieldwork windows. That is ten points apart between two houses on the same contest. 📌 The collection mode does not appear in the part of the filing I read, and the "Misto" label comes from the institute's profile, not from this round.`,
  'polls[0].source':
    `Gerp, released on Aug 26, 2026 (fieldwork Aug 21 to 25 per the institute, n=2,400, 2.0pp margin, TSE registration BR-03547/2026, cost R$ 20,000 from its own funds). Figures checked against Poder360 and Gazeta do Povo, with registration BR-03547/2026 confirmed in both, and cross-checked against the Wikipedia table of 2026 presidential polls.`,
  'polls[0].scenarios[0].name': `Stimulated scenario (first round)`,
  'polls[1].note':
    `Indexa/Broadcast national poll released on Aug 26, registration BR-06366/2026, with 2,000 individual telephone interviews and a 2.2pp margin at 95% confidence, costing R$ 164,000. Fieldwork Aug 20 to 23, and here the TSE filing and the release DO match. Checked against Gazeta do Povo, Money Times and CartaCapital, with the registration matching. 📊 COMPARISON WITH THE HOUSE ITSELF: its July round had Lula at 41% and Flávio at 31%, and it now has 39% and 34%, so the gap narrowed from 10 points to 5, with Lula giving up 2 and Flávio gaining 4. 📌 TWO FIRST-ROUND SCENARIOS, and the difference is Pablo Marçal: without him, Lula 39% and Flávio 34%; with him, Lula 39% and Flávio 33%, and Marçal comes in at 2%. Four runoff scenarios, all with Lula ahead: 46 x 41 against Flávio, 45 x 34 against Zema, 44 x 38 against Caiado and 46 x 34 against Renan Santos. 🔀 IT CAME OUT ON THE SAME DAY AS GERP, POINTING THE OTHER WAY: Indexa has Lula winning the runoff by 5 and Gerp has Flávio winning it by 5, with overlapping fieldwork windows. 🆕 The institute enters the table's roster today, with a reliability of 3 assigned by analogy with houses of similar standing, and that rating is editorial and open to revision.`,
  'polls[1].source':
    `Indexa/Broadcast, released on Aug 26, 2026 (fieldwork Aug 20 to 23, n=2,000, telephone, 2.2pp margin, TSE registration BR-06366/2026, cost R$ 164,000). Figures checked against Gazeta do Povo, Money Times and CartaCapital, with registration BR-06366/2026 confirmed, and cross-checked against the Wikipedia table of 2026 presidential polls.`,
  'institutes[21].note':
    `Instituto Indexa, distributed by Broadcast, of Grupo Estado. Entered the table on Aug 26, 2026.`,
  'polymarketComparison.note':
    `Polymarket prices from the confirmed reading of Aug 25, 3:22 PM BRT (6:22 PM UTC), with the presidential book at USD 132.88M. Two new national polls came out on Aug 26 and they contradict each other: Gerp (BR-03547/2026, fieldwork Aug 21 to 25, n=2,400) has Flávio ahead in the first round with 38% against 37%, and winning the runoff 47% to 42%; Indexa/Broadcast (BR-06366/2026, fieldwork Aug 20 to 23, n=2,000) has Lula ahead with 39% against 34%, and winning the runoff 46% to 41%. That is ten points apart between two houses on the same contest, with overlapping fieldwork windows, and the panel publishes both without averaging them. ⚖️ The POLLING side of this block stays on BTG/Nexus of Aug 24, which is the most reliable national poll on the house's own ruler, and not on either of today's two. The 30-day range was recalculated with them inside, and three floors gave way: Lula from 38% to 37%, Caiado from 3.1% to 3% and Zema from 1.3% to 1%. The distance between the top two opened again, from 27.45pp to 27.85pp, and it opened because the second gave up 0.40pp, not because the first gained. ⭐ The move of Aug 25 is in the third-place contract for the first round: Renan Santos gave up 2.50pp to 51.50% and Ronaldo Caiado rose 3.00pp to 42.00%, taking the gap between the two from 15.00pp to 9.50pp, in the direction the polling was already showing. ⚠️ And that is NOT a series low: the same book stood at 3.5pp on Aug 22 at 7:30 PM, checked in the database backup against the series that begins on Apr 14. Probability of winning and voting intention measure different things, and the panel does not subtract one from the other.`,
  'polymarketComparison.sources':
    `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20pp. On Aug 25 there is a fresh confirmed reading for every contract covered, at 3:22 PM BRT (6:22 PM UTC): presidential, second place, third place, Senate and impeachment at the STF. Polls filed with the TSE and released by the institutes, as reported by G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, UOL, O Globo, Correio Braziliense, Gazeta do Povo, Money Times and CartaCapital. The two national polls of Aug 26 were each checked against two sources, with the TSE registration number matching, and cross-checked against the Wikipedia table of 2026 presidential polls.`,
  'polymarketComparison.candidates[0].pesquisaRange': `37-44.9%`,
  'polymarketComparison.candidates[3].pesquisaRange': `3-6%`,
  'polymarketComparison.candidates[6].pesquisaRange': `1-4%`,
})
