/** Mapa EN de 29/Ago/2026, parte B: analysis-data e polls-data. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of Aug 29, 1:27 PM BRT (4:27 PM UTC)'
const DISC =
  "In the panel's 30-day window he had already appeared ahead in the runoff in three other national polls: Gerp of Aug 26, 47% to 42%, Veritá of Aug 21, 47.3% to 42%, and Gerp of Aug 11, 45% to 43%. The pollsters disagree with each other about the runoff, and the clearest case is Aug 26, when Gerp gave him 47% to 42% and Indexa/Broadcast gave the leader 46% to 41%, on the SAME day and with opposite signs."
const VIRADA =
  'Across the two Vox readings the sign of the runoff changed sides: on Jul 31 the leader was 6.4 points ahead and now he is 0.6 point behind.'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book holds USD 138.92M and the price on this page is from the ${S}. The day did bring a national poll: Vox Brasil (BR-05519/2026, fieldwork Aug 25 to 27, n=2,100, margin of 2.15pp, in person), the first in two days. It brings the ${G('first round', 'primeiro-turno')} at 37.1% to 34.8% and the ${G('runoff', 'segundo-turno')} at 45.1% to 44.5% for the runner-up. The 0.6 point sits inside the margin, so the reading is a ${G('technical tie', 'empate-tecnico')}.`,
  'cards.sentimento.text2': `On price, the runner-up rose 3.30pp, to 38.95%, the largest move on the panel, and the leader gave up 1.00pp, to 56.50%. The distance between the two fell to 17.55pp, the lowest value in the 20-day window. The series shows that narrowing running since Aug 10, when the distance was 36.40pp, without a single day of meaningful reversal. This time both sides moved, unlike the two previous days, when the leader stood still.`,
  'cards.sentimento.text3': `Away from the outright-winner contract, the day has one change of position. Ronaldo Caiado took the lead of the third-place contract for the first round, at 36.50%, up 2.00pp, while Renan Santos fell 3.00pp, to 32.50%. That book had the same leader since Aug 9. Declared voting intention points the same way by another route: Vox places Caiado as the third name in the first round, at 5.0%, ahead of Renan Santos at 3.3%, Romeu Zema at 2.8% and Augusto Cury at 2.6%.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 38.95% (vol USD 9.21M) in the presidential book, up 3.30pp, the largest move on the panel. In the second-place contract for the first round he rose 1.50pp, to 86.50%, and this time BOTH of his books moved in the same direction. In Vox of Aug 29 he has 34.8% in the first round and 45.1% in the runoff, and comparing the pollster with itself shows rises of 3.6pp and 4.0pp in one month. In his TV Globo interview he tried to tie Banco Master to his opponent and promised to respect the election result, according to O Globo, and refused to account for the Dark Horse case, according to Folha de S.Paulo. He told the Faria Lima financial district that relations with the Supreme Court improve once he appoints four justices, according to Estadão.`,
  'cards.sentimento.esquerda': `Lula at 56.50% (vol USD 9.42M), down 1.00pp. In Vox of Aug 29 he has 37.1% in the first round, ahead by 2.3 points, and 44.5% in the runoff, behind by 0.6 point inside the margin. Against Vox's own Jul 31 reading he gives up 3.4pp in the first round and 3.0pp in the runoff. His rejection is 52.7%, above the opponent's 49.3%, according to CNN Brasil. In the radio advertising debut he focused on education, according to InfoMoney, called his opponent the worst of the Bolsonaros, according to Estadão, and his campaign launched a site tying the rival to militia and to Banco Master, according to Poder360.`,
  'cards.sentimento.terceiraVia': `Ronaldo Caiado took the lead of the third-place contract for the first round, at 36.50%, up 2.00pp, and is the third name in the first round in Vox of Aug 29, at 5.0%. In the outright-winner contract he remains at 0.25% (vol USD 6.89M), below the 0.5% floor of the double reading. Renan Santos at 2.25% (vol USD 11.81M), down 0.65pp, and he lost the lead of the third-place contract, which he had held since Aug 9. Augusto Cury gave up 0.35pp in the outright-winner contract, to 3.15% (vol USD 2.55M), debuted on radio campaign advertising and gained 2 million followers over the week, according to SpaceMoney.`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS publishes only prices that two independent readings, taken eight minutes apart, confirm within 0.20pp, and the confirmation is done contract by contract. Names below 0.5% fall outside that watch, because a thin book swings on its own. The presidential book holds USD 138.92M since opening.`,
  'cards.inss.text1': `The case involving the president's son was the political axis of the day. The Federal Police is investigating whether a lobbyist friend of his acted at the postal service, according to Folha de S.Paulo, and allies see the president under pressure, with a strategy of outsourcing the fiscal adjustment debate to ministers. The government is aiming for a positive agenda in Congress to shift the focus, according to CNN Brasil.`,
  'cards.inss.text2': `On the campaign trail, the president held events in Bahia and avoided questions about his son's dealings inside his own administration, according to Terra. The director-general of the Federal Police said, without naming the case, that the force acts without protecting and without persecuting, and defended technical conduct.`,
  'cards.inss.text3': `The institutional crisis around the case escalated. André Mendonça sees no room for a truce with the Federal Police leadership, and Edson Fachin is trying to broker an understanding to reduce the tension, according to Folha de S.Paulo. The entry of the court's presidency as a mediator is the new fact of the day in coverage of the episode.`,
  'cards.inss.text4': `⚠️ The case remains live and unresolved. The distinction the panel has kept from the start still holds: the effect on government approval is one thing, the effect on voting intention is another, and the two do not move together by default. The poll released on Friday has fieldwork from Aug 25 to 27 and measures neither this week's escalation nor the advertising debut.`,
  'cards.inss.impactoLula': `Not isolable, and today's new reading does NOT reach the period in question. Vox Brasil of Aug 29 has fieldwork from Aug 25 to 27, before the escalation of the crisis between Mendonça and the Federal Police. The clean comparison it allows is the pollster against itself: 37.1% in the first round against 40.5% on Jul 31, and 44.5% in the runoff against 47.5%. On price, his outright-winner contract gave up 1.00pp on Friday, to 56.50%.`,
  'cards.inss.impactoGestao': `A new reading on Friday, and it is the most negative of the recent series: Vox Brasil brings 52.7% rejection of the president, according to CNN Brasil, and 53.3% disapproval, according to Exame. The week's earlier measurements remain available for comparison: 42% approval against 50% disapproval in PoderData of Aug 27, 46% against 50% in Indexa/Broadcast of Aug 26, 43% against 51% in Gerp of Aug 26, and 48% against 49% in BTG/Nexus of Aug 24.`,
  'cards.inss.conclusao': `On Aug 29 the case advances on two fronts at once, the investigation, with the lobbyist at the postal service, and the crisis between the court and the Federal Police. The panel records both movements and does not convert one into the other. It also records that the day's poll measures neither of them, because its fieldwork closed on Aug 27.`,
  'cards.bancoMaster.text1': `The content of the testimony became public on Friday. Daniel Vorcaro told the Federal Police he did not corrupt Central Bank staff and again signaled a plea deal, according to Folha de S.Paulo and Estadão. It was his first testimony this year on the suspicion of corruption at the Central Bank, described in coverage as one of broad clarifications.`,
  'cards.bancoMaster.text2': `The willingness to negotiate a plea deal is the new fact, and it changes the kind of risk the case carries: an approved agreement would turn the person under investigation into a source of evidence about others. None of that is settled, and the panel records the stated willingness, not an agreement.`,
  'cards.bancoMaster.text3': `The case entered the campaign from both sides on the same day. The leader played on radio campaign advertising the audio in which his opponent calls Vorcaro brother, according to Valor Econômico, and his campaign launched a site tying the rival to the bank and to militia, according to Poder360. The opponent replied that there is nothing wrong with his relationship with Vorcaro, according to G1, and that the president is the one who owes explanations, according to Gazeta do Povo.`,
  'cards.bancoMaster.conclusao': `⭐ THE CROSSING OF THE DAY IS IN THE ORDER OF EVENTS, NOT IN THE CAUSE. The case became a central piece of campaign advertising and the testimony became public on the same Friday, and on the same day the runner-up's price rose 3.30pp, the largest rise on the panel. The panel does NOT claim one produced the other, and there is a concrete reason not to: his price started rising on the night of Aug 28, before the testimony's content and the poll came out. When two measurements move in the same direction, what gets recorded is the sequence, not the mechanism.`,
  'cards.stf.toffoli': `No new individual act captured on Aug 29.`,
  'cards.stf.moraes': `No new individual act by him on Aug 29. Governor Wilson Lima publicly defended his impeachment, according to AM POST.`,
  'cards.stf.gilmar': `No new individual act captured on Aug 29.`,
  'cards.stf.dino': `He said the judiciary's over-prominence is not desirable but that the Supreme Court cannot run away from it, according to Folha de S.Paulo. He remains one of the two poles of the internal rift over who runs the cases involving the president's son and Dark Horse.`,
  'cards.stf.mendonca': `⭐ THE NAME OF THE DAY AT THE COURT IS HIS FOR THE FOURTH DAY RUNNING. He sees no room for a truce with the Federal Police leadership in the case involving the president's son, according to Folha de S.Paulo. He also suspended the ruling on Vale's taxation abroad. The day before he summoned X to explain to the electoral court the filter that blocks recommendations of candidate profiles.`,
  'cards.stf.nexo': `⭐ THE THREAD OF THE DAY IS THE COURT'S PRESIDENCY STEPPING IN. Edson Fachin is trying to broker an understanding to reduce the tension between Mendonça and the Federal Police leadership, according to Folha de S.Paulo, and that mediation is the new fact of the day in coverage of the episode. Alongside it, the electoral court took X to task and demanded explanations about failures in its algorithm filter, and the runner-up went to that same court against his opponent's remarks about campaign accounts, according to Poder360. The court and the electoral court appear on Friday arbitrating the investigation, the jurisdiction and the advertising all at once.`,
  'cards.stf.analise': `The contract on a Supreme Court justice leaving by impeachment before 2027 stands at 3.45% (vol USD 84 thousand), up 0.05pp in the ${S}. It stood at 3.40% on 13 of the last 15 days. ⚠️ It is the smallest book on the panel, and in a book that size half a percentage point does not separate news from noise: the level tells you more than the move. On Friday a governor publicly defended the impeachment of a justice, and the price barely moved.`,
})

construir('polls-data', 'en', {
  'polls[0].note': `Vox Brasil national poll published Aug 29 (Metrópoles, CNN Brasil, VEJA, Exame, JOTA, Alagoas 24 Horas). First round Lula 37.1% x Flávio Bolsonaro 34.8%, a distance of 2.3pp, a technical tie by the 2.15pp margin; Ronaldo Caiado 5.0%, Renan Santos 3.3%, Romeu Zema 2.8%, Augusto Cury 2.6%, others 4.1%, blank and null 3.5% and don't know 6.8%. The table closes at 100.0. Runoff Flávio 45.1% x Lula 44.5%, also a technical tie. Fieldwork Aug 25 to 27, n=2,100, in person, margin 2.15pp, 95% confidence, registration BR-05519/2026, funded by the institute's own resources. ⭐ THE COMPARISON THAT COUNTS IS WITH THE POLLSTER ITSELF, SAME METHOD AND SAME SAMPLE, AND IT SHOWS THE RUNOFF FLIPPING IN ONE MONTH: on Jul 31 Vox measured first round Lula 40.5% x Flávio 31.2%, a distance of 9.3pp, and runoff Lula 47.5% x Flávio 41.1%, a distance of 6.4pp outside the margin. Now the first-round distance is 2.3pp and the runoff has changed sides, with 0.6pp for Flávio. That is 7.0 points of narrowing in the first round and 7.0 points of reversal in the runoff, which Exame also reported. ⚠️ THIS HOLDS FOR THE VOX SERIES, NOT FOR THE SET OF NATIONAL POLLS. ${VIRADA} ${DISC} REJECTION of 52.7% for Lula and 49.3% for Flávio (CNN Brasil). Exame records disapproval of Lula at 53.3% in the same round. NATIONAL SCOPE confirmed on release. ⚠️ Fieldwork closed on Aug 27, BEFORE campaign advertising debuted on Aug 28, so this poll does not measure any advertising effect.`,
  'polls[0].source': `Vox Brasil released on Aug 29 by Metrópoles, CNN Brasil, VEJA, Exame, JOTA and Alagoas 24 Horas. TSE registration BR-05519/2026.`,
  'polymarketComparison.note': `Polymarket prices in the ${S}, with the presidential book at USD 138.92M. THE DAY DID BRING A NATIONAL POLL: Vox Brasil (BR-05519/2026, fieldwork Aug 25 to 27, n=2,100, margin of 2.15pp, in person), the first in two days. It brings the first round at 37.1% to 34.8%, a distance of 2.3 points, and the runoff at 45.1% to 44.5% for Flávio Bolsonaro. The 0.6 point sits inside the margin, so the reading is a ${G('technical tie', 'empate-tecnico')} and not a lead. ${VIRADA} That holds for the Vox series, not for the set of national polls. ${DISC} The comparison that carries the day is the pollster against itself: on Jul 31 Vox measured 40.5% to 31.2% in the first round and 47.5% to 41.1% in the runoff, with the same in-person method and the same sample of 2,100. In one month the first-round distance fell 7.0 points and the runoff changed sides. In the market, Flávio Bolsonaro's outright-winner contract rose 3.30pp, to 38.95%, the largest move on the panel, Lula's gave up 1.00pp, to 56.50%, and the distance between the two fell to 17.55pp, the lowest value in the 20-day window. AFOS does not say which of the two instruments is right: both are forecasts of the same event and can be wrong together, and only the count settles it. What the record allows us to state is the sequence, because Flávio Bolsonaro's price started rising on the night of Aug 28, before the poll was released on Aug 29. Away from the top, the third-place contract for the first round changed leaders: Ronaldo Caiado rose to 36.50% and Renan Santos fell to 32.50%, ending a lead that had lasted since Aug 9, and Vox points the same way by placing Caiado as the third name in the first round, at 5.0%. ⚠️ A poll percentage and a contract price are different quantities and do not subtract: one measures declared voting intention, the other measures the implied probability of winning.`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `Vox Brasil of Aug 29 (BR-05519/2026, fieldwork Aug 25 to 27, n=2,100) puts him at 37.1% in the first round, 2.3 points ahead, and at 44.5% in the runoff against 45.1%, behind by 0.6 point inside the 2.15pp margin. Against Vox's own Jul 31 reading he gives up 3.4pp in the first round and 3.0pp in the runoff.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `56.50% (vol USD 9.42M) in the ${S}. Down 1.00pp, and the distance to the runner-up fell to 17.55pp, the lowest value in the 20-day window, after twenty days of near-continuous narrowing since the 36.40pp of Aug 10.`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `Vox Brasil of Aug 29 puts him at 34.8% in the first round and at 45.1% in the runoff, ahead of the leader by 0.6 point and inside the 2.15pp margin, that is, a technical tie. ${VIRADA} ${DISC} Against Vox's own Jul 31 reading he rises 3.6pp in the first round and 4.0pp in the runoff, with the same in-person method and the same sample.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `38.95% (vol USD 9.21M) in the ${S}. Up 3.30pp, the LARGEST move on the panel. In the second-place contract for the first round he rose 1.50pp, to 86.50%, and this time both books moved in the same direction.`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `Vox Brasil of Aug 29 measures him at 2.6% in the first round, the sixth name on the table, below the 4% PoderData/Aya gave him on Aug 27.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `3.15% (vol USD 2.55M) in the ${S}. Down 0.35pp. This round publishes no new number for him in the third-place contract, which stood at 26.70% on Aug 28.`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `Vox Brasil of Aug 29 measures him at 3.3% in the first round, the fourth name on the table, ahead of Zema and Cury and behind Caiado.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `2.25% (vol USD 11.81M) in the ${S}. Down 0.65pp. In the third-place contract he gave up 3.00pp, to 32.50%, and LOST the lead he had held since Aug 9.`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `Vox Brasil of Aug 29 puts him at 5.0% in the first round, the THIRD name on the table. In the runoff he loses to the leader 45.5% to 41.1%, a distance of 4.4 points.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.25% (vol USD 6.89M) in the ${S}. Unchanged, and below the 0.5% floor of the double reading. In the third-place contract he rose 2.00pp, to 36.50%, and TOOK the lead of that book.`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `Vox Brasil of Aug 29 does not carry him in the released first-round table. PoderData/Aya of Aug 27 measured him at 3% in the first round.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.06M) in the ${S}. Unchanged, and below the 0.5% floor of the double reading.`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `Vox Brasil of Aug 29 measures him at 2.8% in the first round and tests a runoff scenario in which he loses to the leader 45.5% to 39.3%.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.05% (vol USD 6.32M) in the ${S}. Down 0.10pp, and below the 0.5% floor of the double reading.`,
  'polymarketComparison.candidates[7].tendenciaPesquisa': `He is not tested as a presidential candidate in the national polls in the window.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `0.05% (vol USD 14.06M) in the ${S}. Unchanged. He is not a presidential candidate: he is running for re-election in São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0.05% (vol USD 7.41M) in the ${S}. Unchanged. He is not a presidential candidate: he is running for governor of São Paulo.`,
})
