/** Mapa ES de 29/Ago/2026, parte B: analysis-data e polls-data. Coma decimal, punto de millar. */
import { readFileSync } from 'fs'
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 29/Ago, 13:27 BRT (16:27 UTC)'
const DISC =
  'En la ventana de 30 días del panel él ya aparecía por delante en la segunda vuelta en otras tres encuestas nacionales: Gerp del 26/Ago, por 47% a 42%, Veritá del 21/Ago, por 47,3% a 42%, y Gerp del 11/Ago, por 45% a 43%. Las casas discrepan entre sí sobre la segunda vuelta, y el caso más claro es el 26/Ago, cuando Gerp le dio 47% a 42% y Indexa/Broadcast le dio 46% a 41% al líder, el MISMO día y con signos opuestos.'
const VIRADA =
  'En las dos lecturas de Vox el signo de la segunda vuelta cambió de lado: el 31/Jul el líder estaba 6,4 puntos por delante y ahora está 0,6 punto por detrás.'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 138,92M y el precio de esta página es de la ${S}. El día tuvo encuesta nacional divulgada: la Vox Brasil (BR-05519/2026, campo del 25 al 27/Ago, n=2.100, margen de 2,15pp, presencial), la primera en dos días. Trae la ${G('primera vuelta', 'primeiro-turno')} en 37,1% a 34,8% y la ${G('segunda vuelta', 'segundo-turno')} en 45,1% a 44,5% para el segundo. Los 0,6 punto quedan dentro del margen, así que la lectura es de ${G('empate técnico', 'empate-tecnico')}.`,
  'cards.sentimento.text2': `En el precio, el segundo subió 3,30pp, a 38,95%, la mayor variación del panel, y el líder cedió 1,00pp, a 56,50%. La distancia entre ambos cayó a 17,55pp, el menor valor de la ventana de 20 días. La serie muestra ese estrechamiento corriendo desde el 10/Ago, cuando la distancia era de 36,40pp, sin un solo día de reversión relevante. Esta vez los dos lados se movieron, a diferencia de los dos días anteriores, en que el líder quedó inmóvil.`,
  'cards.sentimento.text3': `Fuera del contrato de ganador, el día tiene un cambio de posición. Ronaldo Caiado asumió el liderazgo del contrato de tercer lugar de la primera vuelta, con 36,50%, subida de 2,00pp, mientras Renan Santos cayó 3,00pp, a 32,50%. Ese libro tenía el mismo líder desde el 09/Ago. La intención declarada apunta en la misma dirección por otro camino: Vox coloca a Caiado como tercer nombre de la primera vuelta, con 5,0%, por delante de Renan Santos, con 3,3%, de Romeu Zema, con 2,8%, y de Augusto Cury, con 2,6%.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 38,95% (vol USD 9,21M) en el presidencial, subida de 3,30pp, la mayor variación del panel. En el contrato de segundo lugar de la primera vuelta subió 1,50pp, a 86,50%, y esta vez sus DOS libros se movieron en la MISMA dirección. En la Vox del 29/Ago tiene 34,8% en la primera vuelta y 45,1% en la segunda, y la comparación de la casa consigo misma muestra subidas de 3,6pp y 4,0pp en un mes. En la entrevista a TV Globo intentó vincular el Banco Master a su adversario y prometió respetar el resultado de la elección, según O Globo, y se negó a rendir cuentas sobre el caso Dark Horse, según Folha de S.Paulo. Dijo a la Faria Lima que la relación con el Supremo mejora cuando nombre a cuatro ministros, según Estadão.`,
  'cards.sentimento.esquerda': `Lula en 56,50% (vol USD 9,42M), caída de 1,00pp. En la Vox del 29/Ago tiene 37,1% en la primera vuelta, por delante por 2,3 puntos, y 44,5% en la segunda, por detrás por 0,6 punto dentro del margen. Frente a la propia Vox del 31/Jul cede 3,4pp en la primera vuelta y 3,0pp en la segunda. Su rechazo es de 52,7%, por encima del 49,3% del adversario, según CNN Brasil. En el debut del espacio electoral en radio se centró en educación, según InfoMoney, llamó a su adversario el peor de los Bolsonaro, según Estadão, y la campaña lanzó un sitio que vincula al rival con milicia y con el Banco Master, según Poder360.`,
  'cards.sentimento.terceiraVia': `Ronaldo Caiado asumió la punta del contrato de tercer lugar de la primera vuelta, con 36,50%, subida de 2,00pp, y es el tercer nombre de la primera vuelta en la Vox del 29/Ago, con 5,0%. En el contrato de ganador sigue en 0,25% (vol USD 6,89M), por debajo del piso de 0,5% de la doble lectura. Renan Santos en 2,25% (vol USD 11,81M), caída de 0,65pp, y perdió el liderazgo del contrato de tercer lugar, que ocupaba desde el 09/Ago. Augusto Cury cedió 0,35pp en el contrato de ganador, a 3,15% (vol USD 2,55M), debutó en la propaganda electoral de radio y ganó 2 millones de seguidores en la semana, según SpaceMoney.`,
  'cards.sentimento.polymarket': `Precios de la ${S}. AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20pp, y la confirmación se hace contrato a contrato. Nombres por debajo de 0,5% quedan fuera de esa vigilancia, porque un libro fino oscila solo. El libro presidencial acumula USD 138,92M desde la apertura.`,
  'cards.inss.text1': `El caso que involucra al hijo del presidente fue el eje político del día. La Policía Federal investiga si una amiga lobista suya actuó en Correos, según Folha de S.Paulo, y aliados ven al presidente bajo presión, con la estrategia de tercerizar en ministros el debate sobre el ajuste fiscal. El gobierno apunta a una agenda positiva en el Congreso para desviar el foco, según CNN Brasil.`,
  'cards.inss.text2': `En la campaña, el presidente hizo agenda en Bahía y evitó preguntas sobre la actuación de su hijo en su propio gobierno, según Terra. El director general de la Policía Federal dijo, sin citar el caso, que la corporación actúa sin proteger y sin perseguir, y defendió una actuación técnica.`,
  'cards.inss.text3': `La crisis institucional en torno al caso escaló. André Mendonça no ve margen para una tregua con la cúpula de la Policía Federal, y Edson Fachin intenta construir un entendimiento para reducir la tensión, según Folha de S.Paulo. La entrada de la presidencia del tribunal como mediadora es el hecho nuevo de este viernes en la cobertura del episodio.`,
  'cards.inss.text4': `⚠️ El caso sigue vivo y sin desenlace. La distinción que el panel mantiene desde el inicio sigue valiendo: una cosa es el efecto sobre la evaluación del gobierno, otra es el efecto sobre la intención de voto, y las dos no van juntas por defecto. La encuesta divulgada este viernes tiene campo del 25 al 27/Ago y no mide ni la escalada de esta semana ni el debut de la propaganda.`,
  'cards.inss.impactoLula': `No aislable, y la lectura nueva de hoy NO alcanza el período en cuestión. La Vox Brasil del 29/Ago tiene campo del 25 al 27/Ago, anterior a la escalada de la crisis entre Mendonça y la Policía Federal. La comparación limpia que permite es de la casa consigo misma: 37,1% en la primera vuelta contra 40,5% el 31/Jul, y 44,5% en la segunda contra 47,5%. En el precio, su contrato de ganador cedió 1,00pp este viernes, a 56,50%.`,
  'cards.inss.impactoGestao': `Lectura nueva este viernes, y es la más negativa de la serie reciente: la Vox Brasil trae rechazo de 52,7% al presidente, según CNN Brasil, y desaprobación de 53,3%, según Exame. Las mediciones anteriores de la semana siguen disponibles para comparación: 42% de aprobación contra 50% de desaprobación en PoderData del 27/Ago, 46% contra 50% en Indexa/Broadcast del 26/Ago, 43% contra 51% en Gerp del 26/Ago, y 48% contra 49% en BTG/Nexus del 24/Ago.`,
  'cards.inss.conclusao': `El 29/Ago el caso avanza en dos frentes al mismo tiempo, el de la investigación, con la lobista en Correos, y el de la crisis entre el tribunal y la Policía Federal. El panel registra los dos movimientos y no convierte uno en el otro. Y registra también que la encuesta del día no mide ninguno de los dos, porque su campo cerró el 27/Ago.`,
  'cards.bancoMaster.text1': `El contenido de la declaración se hizo público este viernes. Daniel Vorcaro afirmó a la Policía Federal que no corrompió a funcionarios del Banco Central y volvió a insinuar una delación premiada, según Folha de S.Paulo y Estadão. Fue su primera declaración del año sobre la sospecha de corrupción en el Banco Central, descrita por la cobertura como de aclaraciones amplias.`,
  'cards.bancoMaster.text2': `La disposición a negociar una delación es el hecho nuevo, y cambia el tipo de riesgo del caso: un acuerdo homologado convertiría al investigado en fuente de prueba sobre terceros. Nada de eso está cerrado, y el panel registra la disposición declarada, no un acuerdo.`,
  'cards.bancoMaster.text3': `El caso entró en la campaña por los dos lados el mismo día. El líder reprodujo en el espacio electoral de radio el audio en que su adversario trata a Vorcaro de hermano, según Valor Econômico, y su campaña lanzó un sitio que vincula al rival con el banco y con milicia, según Poder360. El adversario respondió que no hay nada malo en su relación con Vorcaro, según G1, y que quien debe explicaciones es el presidente, según Gazeta do Povo.`,
  'cards.bancoMaster.conclusao': `⭐ EL CRUCE DEL DÍA ESTÁ EN EL ORDEN DE LOS HECHOS, NO EN LA CAUSA. El caso se volvió pieza central de la propaganda y la declaración del investigado se hizo pública el mismo viernes, y el mismo día el precio del segundo subió 3,30pp, la mayor subida del panel. El panel NO afirma que una cosa causó la otra, y hay un motivo concreto para no afirmarlo: la subida de su precio empezó la noche del 28/Ago, antes de que salieran el contenido de la declaración y la encuesta. Cuando dos mediciones se mueven en la misma dirección, lo que se registra es la secuencia, no el mecanismo.`,
  'cards.stf.toffoli': `Sin acto individual nuevo registrado el 29/Ago.`,
  'cards.stf.moraes': `Sin acto individual nuevo suyo el 29/Ago. El gobernador Wilson Lima defendió públicamente su destitución, según AM POST.`,
  'cards.stf.gilmar': `Sin acto individual nuevo registrado el 29/Ago.`,
  'cards.stf.dino': `Dijo que el protagonismo excesivo del Poder Judicial no es deseable, pero que el Supremo no puede eludirlo, según Folha de S.Paulo. Sigue como uno de los dos polos de la fractura interna sobre quién conduce los casos que involucran al hijo del presidente y el Dark Horse.`,
  'cards.stf.mendonca': `⭐ EL NOMBRE DEL DÍA EN EL TRIBUNAL ES ÉL POR CUARTO DÍA SEGUIDO. No ve margen para una tregua con la cúpula de la Policía Federal en el caso que involucra al hijo del presidente, según Folha de S.Paulo. También suspendió el juicio sobre la tributación de Vale en el exterior. La víspera había intimado a X a explicar al TSE el filtro que impide la recomendación de perfiles de candidatos.`,
  'cards.stf.nexo': `⭐ EL NEXO DEL DÍA ES LA PRESIDENCIA DEL TRIBUNAL ENTRANDO EN ESCENA. Edson Fachin intenta construir un entendimiento para reducir la tensión entre Mendonça y la cúpula de la Policía Federal, según Folha de S.Paulo, y esa mediación es el hecho nuevo del día en la cobertura del episodio. Junto a eso, el TSE encuadró a X y exigió explicaciones sobre fallas en el filtro de algoritmo, y el segundo recurrió al propio TSE contra declaraciones de su adversario sobre cuentas de campaña, según Poder360. El tribunal y la corte electoral aparecen este viernes arbitrando al mismo tiempo la investigación, la competencia y la propaganda.`,
  'cards.stf.analise': `El contrato de salida de un ministro del Supremo por destitución antes de 2027 está en 3,45% (vol USD 84 mil), subida de 0,05pp en la ${S}. Estuvo en 3,40% en 13 de los últimos 15 días. ⚠️ Es el menor libro del panel, y en un libro de ese tamaño medio punto porcentual no separa noticia de ruido: el nivel informa más que la variación. Este viernes hubo defensa pública de la destitución de un ministro por parte de un gobernador, y el precio casi no se movió.`,
})

const anterior = JSON.parse(readFileSync('public/polls-data.es.json', 'utf8'))
const notaPoder = anterior.polls.find((p: { register: string }) => p.register === 'BR-04974/2026')?.note as string
if (!notaPoder) throw new Error('nota da PoderData nao encontrada na traducao ES anterior')
const PARA_ES = "⭐ Y el 4% de Augusto Cury queda en el tope del intervalo en que las 11 lecturas del panel lo miden, de 1% a 4%."
const i = notaPoder.indexOf('⭐ Y el 4% de Augusto Cury')
if (i < 0) throw new Error('frase do Cury nao localizada na traducao ES')
const fim = notaPoder.indexOf('. ', notaPoder.indexOf('hasta ahora', i) >= 0 ? notaPoder.indexOf('hasta ahora', i) : i + 80)
const notaNovaEs = notaPoder.slice(0, i) + PARA_ES + (fim > 0 ? notaPoder.slice(fim + 1) : '')

construir('polls-data', 'es', {
  'polls[0].note': `Vox Brasil nacional publicada el 29/Ago (Metrópoles, CNN Brasil, VEJA, Exame, JOTA, Alagoas 24 Horas). Primera vuelta Lula 37,1% x Flávio Bolsonaro 34,8%, distancia de 2,3pp, empate técnico por el margen de 2,15pp; Ronaldo Caiado 5,0%, Renan Santos 3,3%, Romeu Zema 2,8%, Augusto Cury 2,6%, otros 4,1%, blancos y nulos 3,5% y no saben 6,8%. La tabla cierra en 100,0. Segunda vuelta Flávio 45,1% x Lula 44,5%, también empate técnico. Campo del 25 al 27/Ago, n=2.100, presencial, margen 2,15pp, 95% de confianza, registro BR-05519/2026, financiada con recursos del propio instituto. ⭐ LA COMPARACIÓN QUE VALE ES CON LA PROPIA CASA, MISMO MÉTODO Y MISMA MUESTRA, Y MUESTRA LA SEGUNDA VUELTA INVIRTIÉNDOSE EN UN MES: el 31/Jul Vox medía primera vuelta Lula 40,5% x Flávio 31,2%, distancia de 9,3pp, y segunda vuelta Lula 47,5% x Flávio 41,1%, distancia de 6,4pp fuera del margen. Ahora la distancia de la primera vuelta es de 2,3pp y la de la segunda cambió de lado, con 0,6pp para Flávio. Son 7,0 puntos de estrechamiento en la primera vuelta y 7,0 puntos de reversión en la segunda, lo que Exame también constató. ⚠️ ESTO VALE PARA LA SERIE DE VOX, NO PARA EL CONJUNTO DE LAS NACIONALES. ${VIRADA} ${DISC} RECHAZO de 52,7% a Lula y 49,3% a Flávio (CNN Brasil). Exame registra desaprobación de Lula en 53,3% en la misma ronda. ALCANCE NACIONAL confirmado en la divulgación. ⚠️ El campo cerró el 27/Ago, ANTES del debut del espacio electoral el 28/Ago, así que esta encuesta no mide efecto de propaganda.`,
  'polls[0].source': `Vox Brasil divulgada el 29/Ago por Metrópoles, CNN Brasil, VEJA, Exame, JOTA y Alagoas 24 Horas. Registro TSE BR-05519/2026.`,
  'polls[1].note': notaNovaEs,
  'polymarketComparison.note': `Precios de Polymarket en la ${S}, con el libro presidencial en USD 138,92M. EL DÍA TUVO ENCUESTA NACIONAL DIVULGADA: la Vox Brasil (BR-05519/2026, campo del 25 al 27/Ago, n=2.100, margen de 2,15pp, presencial), la primera en dos días. Trae la primera vuelta en 37,1% a 34,8%, distancia de 2,3 puntos, y la segunda vuelta en 45,1% a 44,5% para Flávio Bolsonaro. Los 0,6 punto quedan dentro del margen, así que la lectura es de ${G('empate técnico', 'empate-tecnico')} y no de liderazgo. ${VIRADA} Eso vale para la serie de Vox, no para el conjunto de las nacionales. ${DISC} La comparación que sostiene el día es de la casa consigo misma: el 31/Jul Vox medía 40,5% a 31,2% en la primera vuelta y 47,5% a 41,1% en la segunda, con el mismo método presencial y la misma muestra de 2.100. En un mes la distancia de la primera vuelta cayó 7,0 puntos y la de la segunda cambió de lado. En el mercado, el contrato de ganador de Flávio Bolsonaro subió 3,30pp, a 38,95%, la mayor variación del panel, el de Lula cedió 1,00pp, a 56,50%, y la distancia entre ambos cayó a 17,55pp, el menor valor de la ventana de 20 días. AFOS no dice cuál de los dos instrumentos está en lo cierto: ambos son previsiones del mismo evento y pueden equivocarse juntos, y solo el escrutinio lo resuelve. Lo que el registro permite afirmar es la secuencia, porque el precio de Flávio Bolsonaro empezó a subir la noche del 28/Ago, antes de que la encuesta se divulgara el 29/Ago. Fuera de la cima, el contrato de tercer lugar de la primera vuelta cambió de líder: Ronaldo Caiado subió a 36,50% y Renan Santos cayó a 32,50%, poniendo fin a una punta que duraba desde el 09/Ago, y Vox apunta en la misma dirección al colocar a Caiado como tercer nombre de la primera vuelta, con 5,0%. ⚠️ Un porcentaje de encuesta y un precio de contrato son magnitudes distintas y no se restan: uno mide intención de voto declarada, el otro mide probabilidad implícita de ganar.`,
  'polymarketComparison.candidates[0].polymarket': '56,50%',
  'polymarketComparison.candidates[0].pesquisaRange': '37,1-38%',
  'polymarketComparison.candidates[1].polymarket': '38,95%',
  'polymarketComparison.candidates[1].pesquisaRange': '34,8-35%',
  'polymarketComparison.candidates[2].polymarket': '3,15%',
  'polymarketComparison.candidates[2].pesquisaRange': '2,6-4%',
  'polymarketComparison.candidates[3].polymarket': '2,25%',
  'polymarketComparison.candidates[3].pesquisaRange': '3,3-4%',
  'polymarketComparison.candidates[4].polymarket': '0,25%',
  'polymarketComparison.candidates[4].pesquisaRange': '4-5%',
  'polymarketComparison.candidates[6].pesquisaRange': '1-2,8%',
  'polymarketComparison.candidates[0].tendenciaPesquisa': `La Vox Brasil del 29/Ago (BR-05519/2026, campo del 25 al 27/Ago, n=2.100) lo da en 37,1% en la primera vuelta, 2,3 puntos por delante, y en 44,5% en la segunda contra 45,1%, por detrás por 0,6 punto dentro del margen de 2,15pp. Frente a la propia Vox del 31/Jul cede 3,4pp en la primera vuelta y 3,0pp en la segunda.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `56,50% (vol USD 9,42M) en la ${S}. Caída de 1,00pp, y la distancia al segundo cayó a 17,55pp, el menor valor de la ventana de 20 días, tras veinte días de estrechamiento casi continuo desde los 36,40pp del 10/Ago.`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `La Vox Brasil del 29/Ago lo da en 34,8% en la primera vuelta y en 45,1% en la segunda, por delante del líder por 0,6 punto y dentro del margen de 2,15pp, es decir, empate técnico. ${VIRADA} ${DISC} Frente a la propia Vox del 31/Jul sube 3,6pp en la primera vuelta y 4,0pp en la segunda, con el mismo método presencial y la misma muestra.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `38,95% (vol USD 9,21M) en la ${S}. Subida de 3,30pp, la MAYOR variación del panel. En el contrato de segundo lugar de la primera vuelta subió 1,50pp, a 86,50%, y esta vez los dos libros se movieron en la misma dirección.`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `La Vox Brasil del 29/Ago lo mide en 2,6% en la primera vuelta, el sexto nombre de la tabla, por debajo del 4% que PoderData/Aya le dio el 27/Ago.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `3,15% (vol USD 2,55M) en la ${S}. Caída de 0,35pp. Esta ronda no publica número nuevo para él en el contrato de tercer lugar, que estaba en 26,70% el 28/Ago.`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La Vox Brasil del 29/Ago lo mide en 3,3% en la primera vuelta, el cuarto nombre de la tabla, por delante de Zema y de Cury y por detrás de Caiado.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `2,25% (vol USD 11,81M) en la ${S}. Caída de 0,65pp. En el contrato de tercer lugar cedió 3,00pp, a 32,50%, y PERDIÓ el liderazgo que ocupaba desde el 09/Ago.`,
  'polymarketComparison.candidates[4].tendenciaPesquisa': `La Vox Brasil del 29/Ago lo coloca en 5,0% en la primera vuelta, el TERCER nombre de la tabla. En la segunda vuelta pierde ante el líder por 45,5% a 41,1%, distancia de 4,4 puntos.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,25% (vol USD 6,89M) en la ${S}. Sin variación, y por debajo del piso de 0,5% de la doble lectura. En el contrato de tercer lugar subió 2,00pp, a 36,50%, y ASUMIÓ el liderazgo de ese libro.`,
  'polymarketComparison.candidates[5].tendenciaPesquisa': `La Vox Brasil del 29/Ago no lo trae en la tabla divulgada de la primera vuelta. PoderData/Aya del 27/Ago lo medía en 3% en la primera vuelta.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,06M) en la ${S}. Sin variación, y por debajo del piso de 0,5% de la doble lectura.`,
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La Vox Brasil del 29/Ago lo mide en 2,8% en la primera vuelta y prueba un escenario de segunda vuelta en que pierde ante el líder por 45,5% a 39,3%.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,05% (vol USD 6,32M) en la ${S}. Caída de 0,10pp, y por debajo del piso de 0,5% de la doble lectura.`,
  'polymarketComparison.candidates[7].tendenciaPesquisa': `No se lo prueba como candidato presidencial en las nacionales de la ventana.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `0,05% (vol USD 14,06M) en la ${S}. Sin variación. No es candidato a la Presidencia: disputa la reelección en São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPesquisa': `No se lo prueba como candidato presidencial en las nacionales de la ventana.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0,05% (vol USD 7,41M) en la ${S}. Sin variación. No es candidato a la Presidencia: disputa el gobierno de São Paulo.`,
})
