/** Mapa EN de 30/Ago/2026: analysis-criteriosa, analysis-data e polls-data. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of Aug 30, 4:40 PM BRT (7:40 PM UTC)'
const VOX = 'Vox Brasil of Aug 29 (BR-05519/2026, fieldwork Aug 25 to 27, n=2,100)'
const FATO =
  'Dias Toffoli signed a ruling on Saturday, August 29, pulling Renan Santos and running mate Aroldo Medina’s candidacy registration off the docket of the virtual plenary session set for August 31. He pointed to signs of illegality because the ticket filed 18 social media profiles on August 19, with the registration request submitted on August 7, outside the legal deadline. The decision became public on August 30'
const SEM =
  'NO NEW NATIONAL POLL WAS RELEASED THIS SUNDAY. The most recent one is still Vox Brasil of Aug 29 (BR-05519/2026, fieldwork Aug 25 to 27, n=2,100)'
const ONDA =
  "The TSE registry lists eight national polls scheduled for release between Aug 31 and Sep 3, three of them on Monday, among them the first Datafolha presidential poll after the candidates' TV Globo interviews. Registration is not release, and none of their numbers enters the panel before it is out."
const DISC =
  "In the panel's 30-day window he had already appeared ahead in the runoff in three other national polls: Gerp of Aug 26, 47% to 42%, Veritá of Aug 21, 47.3% to 42%, and Gerp of Aug 11, 45% to 43%. The pollsters disagree with each other about the runoff, and the clearest case is Aug 26, when Gerp gave him 47% to 42% and Indexa/Broadcast gave the leader 46% to 41%, on the SAME day and with opposite signs."

construir('analysis-criteriosa', 'en', {
  subtitle: `Crossing of Aug 30, 2026: Polymarket price in the ${S}, presidential book at USD 139.76M, against ${VOX}, which is still the most recent national poll RELEASED. This Sunday had no new national poll, and the ${G('TSE', 'tse')} registry lists eight national polls scheduled for release between Aug 31 and Sep 3, among them Datafolha and Quaest.`,

  'candidates[0].header': `PRICE: 55.50% (vol USD 9.50M accumulated), ${S}. No change on the day. POLLING: ${VOX} puts him at 37.1% in the ${G('first round', 'primeiro-turno')}, 2.3 points ahead, and at 44.5% in the ${G('runoff', 'segundo-turno')} against 45.1%, behind by 0.6 point inside the 2.15pp margin. No national poll was released this Sunday.`,
  'candidates[0].fortes[2]': `His campaign opened an offensive at the ${G('TSE', 'tse')} against his opponent, Caiado and Zema over posts and speeches this Sunday, according to Folha de S.Paulo, and asked for his opponent to be declared ineligible for economic abuse, according to Metrópoles.`,
  'candidates[0].fracos[3]': `The outright-winner price has not moved since Friday afternoon, across nine consecutive captures in the series, and the distance to the runner-up fell to 14.40pp, the narrowest since Jun 10. All of the narrowing over the past 24 hours came from his opponent's side.`,
  'candidates[0].analise': `Sunday pulled the two measurements apart, and that separation is the record of the day. The declared ballot had no new reading: ${VOX} is still the most recent national poll released, with the ${G('first round', 'primeiro-turno')} at 37.1% to 34.8% and the ${G('runoff', 'segundo-turno')} at 45.1% to 44.5% for the runner-up, inside the margin. The price did move, and it moved on one side only. He has been stuck at 55.50% (vol USD 9.50M) since Friday afternoon, across nine consecutive captures, while his opponent rose 1.75pp. The distance between the two closed at 14.40pp, the narrowest since June 10. ${ONDA} Until then the panel serves a fresh price and a Friday poll, and it says so.`,

  'candidates[1].header': `PRICE: 41.10% (vol USD 9.31M accumulated), ${S}. Up 1.75pp, the largest move among the panel's names this round, and his highest price since May 13. POLLING: ${VOX} puts him at 34.8% in the ${G('first round', 'primeiro-turno')} and at 45.1% in the ${G('runoff', 'segundo-turno')}, ahead of the leader by 0.6 point and inside the margin.`,
  'candidates[1].fortes[2]': `The outright-winner contract rose 1.75pp this Sunday, to 41.10%, the largest move among the panel's names this round, and it is his highest price since May 13. In the first-round second-place contract he sits at 85.50%.`,
  'candidates[1].fracos[3]': `The 1.75pp rise came on a Sunday with NO national poll released, and the most recent reading has fieldwork from Aug 25 to 27. Nothing in the two measurements isolates the cause of the move.`,
  'candidates[1].analise': `He is the only name on the panel that moved continuously over the past 24 hours. The price went from 39.35% on Friday to 41.10% (vol USD 9.31M) this Sunday, rising almost monotonically through the day, and it is his highest value since May 13. It is not a series high: the top is still 45.50%, from May 6. In the first-round second-place contract he sits at 85.50%, meaning the market treats his trip to the ${G('runoff', 'segundo-turno')} as close to settled and trades the rest. The declared ballot brought no new reading this Sunday, so the comparison is still with Vox of Aug 29, which puts him at 34.8% in the ${G('first round', 'primeiro-turno')} and ahead by 0.6 point in the runoff, inside the margin. What the day adds is campaign fact, not measurement: he met Bukele's justice minister and said he takes inspiration from the El Salvador model, and the leader's campaign went to the ${G('TSE', 'tse')} against him on three fronts.`,

  'candidates[2].header': `PRICE: 2.25% (vol USD 11.88M accumulated), ${S}. No change. In the first-round third-place contract he sits at 25.00%. POLLING: Vox of Aug 29 measures him at 3.3% in the ${G('first round', 'primeiro-turno')}, the fourth name on the table.`,
  'candidates[2].fortes[0]': `His book has accumulated USD 11.88M, the LARGEST among the panel's candidates, above the leader at USD 9.50M and the runner-up at USD 9.31M. Volume is not price, but it measures how much money has passed through the contract.`,

  'candidates[3].header': `PRICE: Caiado 0.15% (vol USD 6.97M), Haddad 0.05% (vol USD 7.41M) and Zema 0.05% (vol USD 6.37M), ${S}. All three below the 0.5% floor of the double reading. POLLING: Vox of Aug 29 puts Caiado at 5.0% in the ${G('first round', 'primeiro-turno')}, the third name on the table.`,
  'candidates[3].subtitle': `Back of the field in the ${S}. Augusto Cury gives up 1.40pp in the outright-winner contract, to 1.85%, and Ronaldo Caiado is the third name in the ${G('first round', 'primeiro-turno')} in Vox Brasil of Aug 29, at 5.0%, while he leads the first-round third-place contract at 43.50%.`,
  'candidates[3].caiado.label': `CAIADO (PSD), presidential Poly 0.15% (vol USD 6.97M accumulated, ${S}), down 0.10pp, BELOW the 0.5% floor of the double reading. In the first-round third-place contract he is the leading name, at 43.50%.`,
  'candidates[3].caiado.fortes': `He is the THIRD name in the ${G('first round', 'primeiro-turno')} in Vox Brasil of Aug 29, at 5.0%, ahead of Renan Santos at 3.3%, Romeu Zema at 2.8% and Augusto Cury at 2.6%. In the ${G('runoff', 'segundo-turno')} of that same Vox he loses to the leader 45.5% to 41.1%, a distance of 4.4 points, the narrowest of the two alternative scenarios tested. And in the first-round third-place contract he is the LEADING name, at 43.50%.`,
  'candidates[3].caiado.fracos': `In the outright-winner contract he gave up 0.10pp, to 0.15%, below the 0.5% floor at which the double reading certifies movement. The distance between the 5.0% the declared ballot gives him and the 0.15% of the implied probability is large, and the two quantities do not subtract: one measures voting intention and the other, the chance of winning. This Sunday he joined the list of targets in the offensive the leader's campaign opened at the ${G('TSE', 'tse')} over posts and speeches, according to Folha de S.Paulo.`,
  'candidates[3].haddad.label': `HADDAD (PT), presidential Poly 0.05% (vol USD 7.41M accumulated, ${S}), no change. Below the 0.5% floor of the double reading.`,
  'candidates[3].zema.label': `ZEMA (Novo), presidential Poly 0.05% (vol USD 6.37M accumulated, ${S}), no change. Below the 0.5% floor of the double reading.`,
  'candidates[3].zema.fracos': `The outright-winner contract is still at 0.05%, below the watch floor, and in the first-round third-place contract he sits at 2.15%. The 6.2-point distance in the Vox ${G('runoff', 'segundo-turno')} scenario is wider than Caiado's, at 4.4 points. This Sunday he joined the offensive the leader's campaign opened at the ${G('TSE', 'tse')}, and his candidacy registration goes to trial at the court on Monday, according to Veja.`,
  'candidates[3].fortes[0]': `RONALDO CAIADO (PSD) is the third name in the ${G('first round', 'primeiro-turno')} in Vox of Aug 29, at 5.0%, and he is the LEADING name in the first-round third-place contract, at 43.50%, while in the outright-winner contract he pays 0.15%.`,
  'candidates[3].fortes[3]': `AUGUSTO CURY (Avante) gave an interview to TV Globo this Sunday, according to BBC, and in the first-round third-place contract he sits at 25.45%.`,
  'candidates[3].fracos[1]': `Cury gave up 1.40pp in the outright-winner contract, to 1.85%, the largest drop among the panel's names this round, and his 2.6% in Vox of Aug 29 sits below the 4% PoderData/Aya gave him on Aug 27.`,
  'candidates[3].analise': `The back of the field is still where the two measurements disagree most, and Caiado's case is the sharpest on the panel. He is the THIRD name in the ${G('first round', 'primeiro-turno')} in Vox of Aug 29, at 5.0%, and in the outright-winner contract he sits at 0.15% (vol USD 6.97M), below the watch floor of the double reading. At the same time, he is the LEADING name in the first-round third-place contract, at 43.50%. In other words, the market pays a lot for him to finish third and almost nothing for him to win, and the two things are consistent with each other. Haddad and Zema remain at 0.05% each, and Haddad is not a presidential candidate: he is running for governor of São Paulo. Caiado joined this Sunday the offensive the leader's campaign opened at the ${G('TSE', 'tse')} over posts and speeches.`,

  'candidates[0].fortes[3]': `His outright-winner contract is still at 55.50%, more than 14 points above the runner-up, and the presidential book holds USD 139.76M.`,
  'candidates[1].fracos[4]': `The first-round second-place contract puts him at 85.50%, meaning the market treats his trip to the ${G('runoff', 'segundo-turno')} as close to settled and trades the rest. A high price there is not the same as a high price in the outright-winner contract, where he pays 41.10%.`,
  'candidates[2].fortes[2]': `In the first-round third-place contract he sits at 25.00%, practically level with Augusto Cury at 25.45% and behind Ronaldo Caiado at 43.50%.`,
  'candidates[2].fracos[0]': `In the outright-winner contract he pays 2.25%, and he is the fourth name in the ${G('first round', 'primeiro-turno')} in Vox of Aug 29, at 3.3%. The two quantities do not subtract: one measures voting intention and the other, the chance of winning.`,
  'candidates[3].fracos[2]': `In the first-round third-place contract, Caiado has 43.50%, Cury has 25.45% and Zema has 2.15%. The name leading that contract is the same one paying 0.15% in the outright-winner contract, and the panel does not add the two readings together.`,

  'quadroComparativo[0].m': `55.50% (vol USD 9.50M), ${S}. No change on the day. His price has not left 55.50% since Friday afternoon, across nine consecutive captures in the series. The distance to the runner-up fell to 14.40pp, the narrowest since Jun 10.`,
  'quadroComparativo[0].t': `flat on price for a second day, and the distance narrows only from his opponent's side`,
  'quadroComparativo[0].s': `His campaign opened an offensive at the ${G('TSE', 'tse')} against his opponent, Caiado and Zema over posts and speeches, according to Folha de S.Paulo, went to the court over his opponent's speech in Barretos, according to O Globo, and asked for him to be declared ineligible for economic abuse, according to Metrópoles.`,
  'quadroComparativo[1].m': `41.10% (vol USD 9.31M), ${S}. Up 1.75pp, the largest move among the panel's names this round, and his highest price since May 13. In the first-round second-place contract he sits at 85.50%, and in the third-place contract at 2.75%.`,
  'quadroComparativo[1].t': `rises for a second day and takes the distance to its narrowest point since June`,
  'quadroComparativo[1].s': `He met Bukele's justice minister, said he takes inspiration from the El Salvador model and stated that Brazil has few prisoners, according to Estadão, Folha de S.Paulo and Poder360. The former Air Force commander denied asking for votes for the leader and called his statement reckless, according to G1.`,
  'quadroComparativo[2].m': `1.85% (vol USD 2.89M) in the outright-winner contract, ${S}. Down 1.40pp, the largest drop among the panel's names this round. In the first-round third-place contract he sits at 25.45%.`,
  'quadroComparativo[2].t': `gives ground in the outright-winner contract on the fourth day of his series`,
  'quadroComparativo[2].s': `He gave an interview to TV Globo, according to BBC.`,
  'quadroComparativo[3].m': `2.25% (vol USD 11.88M), ${S}. No change, and the price did not move in the window when the court's decision on his registration became public. In the first-round third-place contract he sits at 25.00%.`,
  'quadroComparativo[4].m': `0.15% (vol USD 6.97M), ${S}. Down 0.10pp, and below the 0.5% floor of the double reading. In the first-round third-place contract he is the leading name, at 43.50%.`,
  'quadroComparativo[4].t': `third in the declared ballot, first in the third-place contract and bottom of the field in the outright-winner one`,
  'quadroComparativo[4].s': `He is among the targets of the offensive the leader's campaign opened at the ${G('TSE', 'tse')} over posts and speeches, according to Folha de S.Paulo.`,
  'quadroComparativo[5].m': `0.15% (vol USD 3.07M), ${S}. No change, and below the 0.5% floor of the double reading.`,
  'quadroComparativo[5].s': `He does not appear in this Sunday's news coverage with a fact of his own.`,
  'quadroComparativo[6].m': `3.60% (vol USD 84 thousand), ${S}. Up 0.15pp, and it remains the smallest book on the panel.`,
  'quadroComparativo[6].t': `rises a little, and it is the smallest book on the panel`,


  // --- ERRATA: o despacho de Toffoli e de SABADO 29/Ago ---
  'candidates[2].fracos[3]': `${FATO}, with seven outlets publishing between 3:47 PM and 6:56 PM Brasília time. His price did not react on either Saturday or Sunday.`,
  'candidates[2].analise': `His crossing is the most direct of the day, and the result is that there was no crossing. ${FATO}, with seven outlets publishing between 3:47 PM and 6:56 PM Brasília time. His price did not move: 2.25% (vol USD 11.88M) in the confirmed reading, the same value as Friday, and the series keeps him at 2.30% in every cron capture on Saturday and Sunday, including those after publication. His book is the third largest in the outright-winner contract, at USD 11.88M, above the leader's and the runner-up's, which makes the absence of movement harder to put down to a thin market. The panel records the fact, the date of the act and the absence of a reaction, and assigns no cause to any of the three.`,
  'quadroComparativo[3].s': `${FATO}, according to Poder360 and Gazeta do Povo. The ${G('TSE', 'tse')} begins ruling on the registrations of the leader, the runner-up, Zema and him on August 31, according to Veja.`,
  'quadroComparativo[3].t': `price flat across the two days his registration stalled at the court`,
  'quadroComparativo[6].s': `${FATO}, according to Poder360. Gilmar Mendes barred the judges' union from charging a fee on the eve of an assembly on ethics rules at the court, according to Estadão, and limited contributions from the judges who joined, according to Poder360. Proposals to rein in the court are multiplying in Congress and are stalling under Alcolumbre, according to Gazeta do Povo.`,
  cruzamento: `Sunday had the two measurements moving at different speeds, and that is what the panel records. The declared ballot stood still: no national poll was released, and the most recent one is still Vox Brasil of Aug 29 (BR-05519/2026, fieldwork Aug 25 to 27, n=2,100), with a 2.15pp margin and in-person fieldwork, showing the ${G('first round', 'primeiro-turno')} at 37.1% to 34.8% and the ${G('runoff', 'segundo-turno')} at 45.1% to 44.5% for the runner-up, inside the margin. The price did move, and on one side only: the leader has not left 55.50% since Friday afternoon, across nine consecutive captures, and the runner-up rose 1.75pp, to 41.10%. The distance between the two closed at 14.40pp, the narrowest since June 10, and the runner-up's price is his highest since May 13. The second crossing is a judicial fact against a price, and the date of the act matters. ${FATO}, with seven outlets publishing between 3:47 PM and 6:56 PM Brasília time. His outright-winner contract did not move on either day: 2.25%, the same value as Friday, in a book of USD 11.88M. The ${G('TSE', 'tse')} begins ruling on the registrations of the leader, the runner-up, Zema and him on August 31. The third record is one of calendar, and it comes from the TSE itself: eight national polls are scheduled for release between Aug 31 and Sep 3, three of them on Monday, including the first Datafolha presidential poll after the candidates' TV Globo interviews. Registration is not release, and no number from those eight enters here before it is out. What the panel serves today is a Sunday price and a Friday poll, with both dates declared.`,
})

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 139.76M and the price on this page comes from the ${S}. ${SEM}.`,
  'cards.sentimento.text2': `On price, the runner-up rose 1.75pp, to 41.10%, the largest move among the panel's names this round, and the leader did not move, staying at 55.50% for a second day. The distance between the two fell to 14.40pp, the narrowest since Jun 10, and the runner-up's price is his highest since May 13.`,
  'cards.sentimento.text3': `The first-round second-place and third-place contracts publish numbers again this round, after one round without a new reading: the runner-up sits at 85.50% to reach the ${G('runoff', 'segundo-turno')}, and Caiado leads the third-place contract at 43.50%, the same name that sits at 0.15% in the outright-winner contract.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 41.10% (vol USD 9.31M) in the presidential contract, up 1.75pp, the largest move among the panel's names this round, and 85.50% in the first-round second-place contract. In Vox of Aug 29 he has 34.8% in the ${G('first round', 'primeiro-turno')} and 45.1% in the ${G('runoff', 'segundo-turno')}, ahead by 0.6 point inside the margin.`,
  'cards.sentimento.esquerda': `Lula at 55.50% (vol USD 9.50M), no change for a second day. In Vox of Aug 29 he has 37.1% in the ${G('first round', 'primeiro-turno')}, ahead by 2.3 points, and 44.5% in the ${G('runoff', 'segundo-turno')}, behind by 0.6 point inside the 2.15pp margin.`,
  'cards.sentimento.terceiraVia': `Ronaldo Caiado is the third name in the ${G('first round', 'primeiro-turno')} in Vox of Aug 29, at 5.0%, and in the outright-winner contract he sits at 0.15% (vol USD 6.97M), below the 0.5% floor of the double reading. In the first-round third-place contract he is the leading name, at 43.50%. Augusto Cury gave up 1.40pp in the outright-winner contract, to 1.85%, the largest drop among the panel's names this round.`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 point. The presidential book has accumulated USD 139.76M.`,
  'cards.inss.text1': `The case involving the president's son stayed in this Sunday's news through a new front. A friend of his struck a deal with the prosecution service to avoid arrest for corruption, according to Veja. The investigations rest mainly on messages, trips and closeness to lobbyists, according to Folha de S.Paulo.`,
  'cards.inss.text2': `The postal service, which is at the centre of the inquiry into the lobbyist's activity, closed the second quarter with a loss of R$ 2.4 billion and has accumulated R$ 5.5 billion in losses this year, according to Valor Econômico. The government will include a R$ 6 billion injection into the state company in the 2027 budget and says the measure brings more stability, according to O Globo.`,
  'cards.inss.text3': `On the political side, the president's allies tried to contain the lobbyist after he called her a crook, according to Folha de S.Paulo, and his defence avoided questions about his son's role during the campaign schedule.`,
  'cards.inss.text4': `The case is still live and unresolved. The distinction the panel has kept from the start still holds: the effect on the government's approval is one thing, the effect on voting intention is another, and the two do not add up.`,
  'cards.inss.impactoLula': `Not isolable, and there is no new reading to measure it. No national poll was released this Sunday, and Vox Brasil of Aug 29 has fieldwork from Aug 25 to 27, before this weekend's events. The eight national polls registered for Aug 31 to Sep 3 are the first that can reach the period.`,
  'cards.inss.impactoGestao': `No new reading this Sunday. The standing reference is still Vox Brasil of Aug 29, with 52.7% rejection of the president, according to CNN Brasil, and 53.3% disapproval, the highest level of the year, according to Exame.`,
  'cards.inss.conclusao': `On Aug 30 the case advances through the judicial route, with the deal between the president's son's friend and the prosecution service, and through the fiscal route, with the postal service's loss and the announced injection. Neither has a ballot reading that reaches it yet, and the panel does not attribute any price move to them.`,
  'cards.bancoMaster.text1': `This Sunday brought no new fact in the case. The day's news collection returned zero items on the query dedicated to the topic, and what exists is from the day before: Daniel Vorcaro's first testimony of the year was concluded on Aug 28, with broad clarifications and a search for a plea deal, according to Folha de S.Paulo.`,
  'cards.bancoMaster.text2': `The prosecutor general's complaint about his plea-deal attempts is from Aug 29, according to Folha de S.Paulo, and the Dark Horse contradictions over the money and the missing accounting are also from the day before.`,
  'cards.bancoMaster.text3': `The case entered the campaign on Friday from both sides, and this Sunday it had no development of its own. The runner-up dodged the subject in his TV Globo interview, according to Folha de S.Paulo.`,
  'cards.bancoMaster.conclusao': `THIS ROUND HAS NO NEW FACT IN THE CASE, AND THAT IS DECLARED. What the panel shows is the picture from Aug 28 and 29, with the date of each piece in the text. The willingness to negotiate a plea deal is still the element that could change the type of risk in the case, and it did not advance publicly this Sunday.`,
  'cards.stf.moraes': `No new individual action captured on Aug 30.`,
  'cards.stf.gilmar': `He barred the judges' union from charging a fee on the eve of an assembly on ethics rules at the court, according to Estadão, and limited contributions from the judges who joined the union, according to Poder360.`,
  'cards.stf.dino': `No new individual action captured on Aug 30.`,
  'cards.stf.mendonca': `No new individual action captured on Aug 30, after four consecutive days as the most cited name at the court.`,

  // --- ERRATA: o despacho de Toffoli e de SABADO 29/Ago ---
  'cards.stf.toffoli': `HE IS THE COURT'S NAME IN THIS SUNDAY'S COVERAGE, THROUGH A SATURDAY ACT. ${FATO}, with seven outlets publishing between 3:47 PM and 6:56 PM Brasília time, among them G1, O Globo, Estadão and Poder360.`,
  'cards.stf.nexo': `THE COURT ENTERS THE ELECTION THROUGH THE REGISTRATION DOOR. The ${G('TSE', 'tse')} begins ruling on August 31 on the candidacy registrations of Lula, Flávio Bolsonaro, Zema and Renan Santos, according to Veja, and Renan Santos's has already come off the docket through a ruling dated August 29. In Congress, proposals to rein in the Supreme Court are multiplying and stalling under Alcolumbre, according to Gazeta do Povo. On its own docket this week, the court may rule on Funrural, free legal aid and the ITBI property tax, according to Valor Econômico.`,
  'cards.stf.analise': `The contract on a Supreme Court justice leaving through impeachment before 2027 sits at 3.60% (vol USD 84 thousand), up 0.15pp in the ${S}. It is the smallest book on the panel, and its price did not follow the volume of court activity this weekend: the registration pulled off the docket by a ruling dated August 29, Gilmar Mendes's two decisions on the judges' union and the registration rulings starting on August 31 moved the contract no more than 0.15 point.`,
})

construir('polls-data', 'en', {
  'polymarketComparison.note': `Polymarket prices in the ${S}, with the presidential book at USD 139.76M. ${SEM}, with a 2.15pp margin and in-person fieldwork, showing the ${G('first round', 'primeiro-turno')} at 37.1% to 34.8% and the ${G('runoff', 'segundo-turno')} at 45.1% to 44.5% for the runner-up, inside the margin. The price did move, and on one side only: the leader has not left 55.50% since Friday afternoon, across nine consecutive captures, and the runner-up rose 1.75pp, to 41.10%. The distance closed at 14.40pp, the narrowest since Jun 10, and the runner-up's price is his highest since May 13, without being a series high, which is still 45.50% from May 6. ${ONDA}`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55.50% (vol USD 9.50M) in the ${S}. No change for a second day, and his price has not left 55.50% since the afternoon of Aug 29, across nine consecutive captures in the series. The distance to the runner-up fell to 14.40pp, the narrowest since Jun 10.`,
  'polymarketComparison.candidates[0].polymarket': `55.50%`,
  'polymarketComparison.candidates[1].polymarket': `41.10%`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `41.10% (vol USD 9.31M) in the ${S}. Up 1.75pp, the largest move among the panel's names this round, and his highest price since May 13. It is not a series high: the top is still 45.50%, from May 6. In the first-round second-place contract he sits at 85.50%.`,
  'polymarketComparison.candidates[2].polymarket': `1.85%`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1.85% (vol USD 2.89M) in the ${S}. Down 1.40pp, the largest drop among the panel's names this round, on the fourth day of his series. In the first-round third-place contract he sits at 25.45%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `2.25% (vol USD 11.88M) in the ${S}. No change, including in the capture that followed the court's decision on his registration. In the first-round third-place contract he sits at 25.00%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.15% (vol USD 6.97M) in the ${S}. Down 0.10pp, and below the 0.5% floor of the double reading. In the first-round third-place contract he is the leading name, at 43.50%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.07M) in the ${S}. No change, and below the 0.5% floor of the double reading.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.05% (vol USD 6.37M) in the ${S}. No change, and below the 0.5% floor of the double reading. In the first-round third-place contract he sits at 2.15%.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `0.05% (vol USD 14.06M) in the ${S}. No change. He is not a presidential candidate: he is running for re-election in São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0.05% (vol USD 7.41M) in the ${S}. No change. He is not a presidential candidate: he is running for governor of São Paulo.`,
})
