/** Mapa ES de 30/Ago/2026: analysis-criteriosa, analysis-data e polls-data. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 30/Ago, 16:40 BRT (19:40 UTC)'
const VOX = 'Vox Brasil del 29/Ago (BR-05519/2026, campo del 25 al 27/Ago, n=2.100)'
const FATO =
  'Dias Toffoli firmó el 29 de agosto, sábado, un despacho que retiró de la agenda el registro de candidatura de Renan Santos y del vice Aroldo Medina, que sería juzgado en el plenario virtual del 31 de agosto. Señaló indicios de ilicitud porque la fórmula entregó 18 perfiles de redes sociales el 19 de agosto, con el pedido de registro protocolado el 7 de agosto, fuera del plazo. La decisión se hizo pública el 30 de agosto'
const SEM =
  'ESTE DOMINGO NO HUBO ENCUESTA NACIONAL DIVULGADA. La más reciente sigue siendo Vox Brasil del 29/Ago (BR-05519/2026, campo del 25 al 27/Ago, n=2.100)'
const ONDA =
  'El registro del TSE trae ocho encuestas nacionales con divulgación prevista entre el 31/Ago y el 03/Sep, tres de ellas el lunes, entre ellas la primera Datafolha presidencial después de las entrevistas de los candidatos en TV Globo. Registro no es divulgación, y ningún número de esas ocho entra en el panel antes de salir.'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 30 de agosto de 2026: precio de Polymarket en ${S}, libro presidencial en USD 139,76M, contra ${VOX}, que sigue siendo la encuesta nacional más reciente DIVULGADA. Este domingo no tuvo encuesta nacional nueva, y el registro del ${G('TSE', 'tse')} trae ocho nacionales con divulgación prevista entre el 31/Ago y el 03/Sep, entre ellas Datafolha y Quaest.`,

  'candidates[0].header': `PRECIO: 55,50% (vol USD 9,50M acumulado), ${S}. Sin variación en el día. ENCUESTA: ${VOX} lo da en 37,1% en la ${G('primera vuelta', 'primeiro-turno')}, 2,3 puntos por delante, y en 44,5% en la ${G('segunda vuelta', 'segundo-turno')} contra 45,1%, por detrás por 0,6 punto dentro del margen de 2,15pp. Ninguna encuesta nacional fue divulgada este domingo.`,
  'candidates[0].fortes[2]': `Su campaña abrió una ofensiva en el ${G('TSE', 'tse')} contra su adversario, Caiado y Zema por publicaciones y discursos este domingo, según Folha de S.Paulo, y pidió la inelegibilidad de su adversario por abuso económico, según Metrópoles.`,
  'candidates[0].fortes[3]': `Su contrato de ganador sigue en 55,50%, más de 14 puntos por encima del segundo, y el libro presidencial acumula USD 139,76M.`,
  'candidates[0].fracos[3]': `El precio del contrato de ganador no se mueve desde la tarde del viernes, en nueve capturas seguidas de la serie, y la distancia hacia el segundo bajó a 14,40pp, la más estrecha desde el 10/Jun. Todo el estrechamiento de las últimas 24 horas vino del lado del adversario.`,
  'candidates[0].analise': `El domingo separó las dos mediciones, y esa separación es el registro del día. La urna declarada no tuvo lectura nueva: ${VOX} sigue siendo la nacional más reciente divulgada, con la ${G('primera vuelta', 'primeiro-turno')} en 37,1% contra 34,8% y la ${G('segunda vuelta', 'segundo-turno')} en 45,1% contra 44,5% para el segundo, dentro del margen. El precio sí se movió, y se movió de un solo lado. Está estancado en 55,50% (vol USD 9,50M) desde la tarde del viernes, en nueve capturas seguidas, mientras el adversario subió 1,75pp. La distancia entre los dos cerró en 14,40pp, la más estrecha desde el 10 de junio. ${ONDA} Hasta entonces el panel sirve precio nuevo y encuesta del viernes, y lo dice.`,

  'candidates[1].header': `PRECIO: 41,10% (vol USD 9,31M acumulado), ${S}. Alza de 1,75pp, la mayor variación entre los nombres del panel en esta ronda, y su precio más alto desde el 13/May. ENCUESTA: ${VOX} lo da en 34,8% en la ${G('primera vuelta', 'primeiro-turno')} y en 45,1% en la ${G('segunda vuelta', 'segundo-turno')}, por delante del líder por 0,6 punto y dentro del margen.`,
  'candidates[1].fortes[2]': `El contrato de ganador subió 1,75pp este domingo, hasta 41,10%, la mayor variación entre los nombres del panel en esta ronda, y es su precio más alto desde el 13/May. En el contrato de 2º lugar de la primera vuelta está en 85,50%.`,
  'candidates[1].fracos[3]': `El alza de 1,75pp vino en un domingo SIN encuesta nacional divulgada, y la lectura más reciente tiene campo del 25 al 27/Ago. Nada en las dos mediciones aísla la causa del movimiento.`,
  'candidates[1].fracos[4]': `El contrato de 2º lugar de la primera vuelta lo coloca en 85,50%, es decir, el mercado trata su llegada a la ${G('segunda vuelta', 'segundo-turno')} como casi resuelta y disputa el resto. Un precio alto ahí no es lo mismo que precio alto en el de ganador, donde paga 41,10%.`,
  'candidates[1].analise': `Es el único nombre del panel que se movió de forma continua en las últimas 24 horas. El precio salió de 39,35% el viernes y cerró en 41,10% (vol USD 9,31M) este domingo, con alza casi monótona a lo largo del día, y es su valor más alto desde el 13 de mayo. No es máximo de la serie: el techo sigue siendo 45,50%, del 06 de mayo. En el contrato de 2º lugar de la primera vuelta está en 85,50%, o sea, el mercado trata su llegada a la ${G('segunda vuelta', 'segundo-turno')} como casi resuelta y disputa el resto. La urna declarada no trajo lectura nueva este domingo, así que la comparación sigue siendo con la Vox del 29/Ago, que lo da en 34,8% en la ${G('primera vuelta', 'primeiro-turno')} y por delante por 0,6 punto en la segunda. Lo que el día agrega es hecho de campaña, no medición: se reunió con el ministro de Justicia de Bukele y dijo inspirarse en el modelo de El Salvador, y la campaña del líder fue al ${G('TSE', 'tse')} contra él en tres frentes.`,

  'candidates[2].header': `PRECIO: 2,25% (vol USD 11,88M acumulado), ${S}. Sin variación. En el contrato de 3º lugar de la primera vuelta está en 25,00%. ENCUESTA: la Vox del 29/Ago lo mide en 3,3% en la ${G('primera vuelta', 'primeiro-turno')}, el cuarto nombre de la tabla.`,
  'candidates[2].fortes[0]': `Su libro acumula USD 11,88M, el MAYOR entre los candidatos del panel, por encima del líder, con USD 9,50M, y del segundo, con USD 9,31M. Volumen no es precio, pero mide cuánto dinero pasó por el contrato.`,
  'candidates[2].fortes[2]': `En el contrato de 3º lugar de la primera vuelta está en 25,00%, prácticamente empatado con Augusto Cury, que tiene 25,45%, y por detrás de Ronaldo Caiado, con 43,50%.`,
  'candidates[2].fracos[0]': `En el contrato de ganador paga 2,25%, y es el cuarto nombre de la ${G('primera vuelta', 'primeiro-turno')} en la Vox del 29/Ago, con 3,3%. Las dos magnitudes no se restan: una mide intención de voto y la otra, chance de ganar.`,

  'candidates[3].header': `PRECIO: Caiado 0,15% (vol USD 6,97M), Haddad 0,05% (vol USD 7,41M) y Zema 0,05% (vol USD 6,37M), ${S}. Los tres por debajo del piso de 0,5% de la doble lectura. ENCUESTA: la Vox del 29/Ago coloca a Caiado en 5,0% en la ${G('primera vuelta', 'primeiro-turno')}, el tercer nombre de la tabla.`,
  'candidates[3].subtitle': `Pelotón de atrás en ${S}. Augusto Cury cede 1,40pp en el contrato de ganador, hasta 1,85%, y Ronaldo Caiado es el tercer nombre de la ${G('primera vuelta', 'primeiro-turno')} en Vox Brasil del 29/Ago, con 5,0%, al mismo tiempo que lidera el contrato de 3º lugar de la primera vuelta, con 43,50%.`,
  'candidates[3].caiado.label': `CAIADO (PSD), Poly presidencial 0,15% (vol USD 6,97M acumulado, ${S}), caída de 0,10pp, POR DEBAJO del piso de 0,5% de la doble lectura. En el contrato de 3º lugar de la primera vuelta es el primer nombre, con 43,50%.`,
  'candidates[3].caiado.fortes': `Es el TERCER nombre de la ${G('primera vuelta', 'primeiro-turno')} en Vox Brasil del 29/Ago, con 5,0%, por delante de Renan Santos, con 3,3%, de Romeu Zema, con 2,8%, y de Augusto Cury, con 2,6%. En la ${G('segunda vuelta', 'segundo-turno')} de esa misma Vox pierde ante el líder por 45,5% a 41,1%, distancia de 4,4 puntos, la menor entre los dos escenarios alternativos probados. Y en el contrato de 3º lugar de la primera vuelta es el PRIMER nombre, con 43,50%.`,
  'candidates[3].caiado.fracos': `En el contrato de ganador cedió 0,10pp, hasta 0,15%, por debajo del piso de 0,5% en que la doble lectura certifica movimiento. La distancia entre el 5,0% que la urna declarada le da y el 0,15% de la probabilidad implícita es grande, y las dos magnitudes no se restan: una mide intención de voto y la otra, chance de ganar. Este domingo entró en la lista de blancos de la ofensiva que la campaña del líder abrió en el ${G('TSE', 'tse')} por publicaciones y discursos, según Folha de S.Paulo.`,
  'candidates[3].haddad.label': `HADDAD (PT), Poly presidencial 0,05% (vol USD 7,41M acumulado, ${S}), sin variación. Por debajo del piso de 0,5% de la doble lectura.`,
  'candidates[3].zema.label': `ZEMA (Novo), Poly presidencial 0,05% (vol USD 6,37M acumulado, ${S}), sin variación. Por debajo del piso de 0,5% de la doble lectura.`,
  'candidates[3].zema.fracos': `El contrato de ganador sigue en 0,05%, por debajo del piso de vigilancia, y en el de 3º lugar de la primera vuelta está en 2,15%. La distancia de 6,2 puntos en el escenario de ${G('segunda vuelta', 'segundo-turno')} de la Vox es mayor que la de Caiado, de 4,4 puntos. Este domingo entró en la ofensiva que la campaña del líder abrió en el ${G('TSE', 'tse')}, y su registro de candidatura entra a juicio en el tribunal el lunes, según Veja.`,
  'candidates[3].fortes[0]': `RONALDO CAIADO (PSD) es el tercer nombre de la ${G('primera vuelta', 'primeiro-turno')} en la Vox del 29/Ago, con 5,0%, y es el PRIMER nombre del contrato de 3º lugar de la primera vuelta, con 43,50%, mientras en el contrato de ganador paga 0,15%.`,
  'candidates[3].fortes[3]': `AUGUSTO CURY (Avante) dio una entrevista a TV Globo este domingo, según BBC, y en el contrato de 3º lugar de la primera vuelta está en 25,45%.`,
  'candidates[3].fracos[1]': `Cury cedió 1,40pp en el contrato de ganador, hasta 1,85%, la mayor caída entre los nombres del panel en esta ronda, y su 2,6% en la Vox del 29/Ago queda por debajo del 4% que PoderData/Aya le dio el 27/Ago.`,
  'candidates[3].fracos[2]': `En el contrato de 3º lugar de la primera vuelta, Caiado tiene 43,50%, Cury tiene 25,45% y Zema tiene 2,15%. El nombre que lidera ese contrato es el mismo que paga 0,15% en el de ganador, y el panel no suma las dos lecturas.`,
  'candidates[3].analise': `El pelotón de atrás sigue siendo el lugar donde las dos mediciones más discrepan, y el caso de Caiado es el más nítido del panel. Es el TERCER nombre de la ${G('primera vuelta', 'primeiro-turno')} en la Vox del 29/Ago, con 5,0%, y en el contrato de ganador está en 0,15% (vol USD 6,97M), por debajo del piso de vigilancia de la doble lectura. Al mismo tiempo, es el PRIMER nombre del contrato de 3º lugar de la primera vuelta, con 43,50%. Es decir, el mercado paga alto para que llegue tercero y casi nada para que gane, y las dos cosas son coherentes entre sí. Haddad y Zema siguen en 0,05% cada uno, y Haddad no es candidato a la Presidencia: disputa la gobernación de São Paulo. Caiado entró este domingo en la ofensiva que la campaña del líder abrió en el ${G('TSE', 'tse')} por publicaciones y discursos.`,

  'quadroComparativo[0].m': `55,50% (vol USD 9,50M), ${S}. Sin variación en el día. Su precio no sale de 55,50% desde la tarde del viernes, en nueve capturas seguidas de la serie. La distancia hacia el segundo bajó a 14,40pp, la más estrecha desde el 10/Jun.`,
  'quadroComparativo[0].t': `estancado en el precio por segundo día, y la distancia se acorta solo por el lado del adversario`,
  'quadroComparativo[0].s': `Su campaña abrió una ofensiva en el ${G('TSE', 'tse')} contra su adversario, Caiado y Zema por publicaciones y discursos, según Folha de S.Paulo, fue al tribunal contra el discurso del adversario en Barretos, según O Globo, y pidió su inelegibilidad por abuso económico, según Metrópoles.`,
  'quadroComparativo[1].m': `41,10% (vol USD 9,31M), ${S}. Alza de 1,75pp, la mayor variación entre los nombres del panel en esta ronda, y su precio más alto desde el 13/May. En el contrato de 2º lugar de la primera vuelta está en 85,50%, y en el de 3º lugar en 2,75%.`,
  'quadroComparativo[1].t': `sube por segundo día y lleva la distancia al punto más estrecho desde junio`,
  'quadroComparativo[1].s': `Se reunió con el ministro de Justicia de Bukele, dijo inspirarse en el modelo de El Salvador y afirmó que Brasil tiene pocos presos, según Estadão, Folha de S.Paulo y Poder360. El excomandante de la Fuerza Aérea negó pedir voto para el líder y calificó su declaración de temeraria, según G1.`,
  'quadroComparativo[2].m': `1,85% (vol USD 2,89M) en el contrato de ganador, ${S}. Caída de 1,40pp, la mayor caída entre los nombres del panel en esta ronda. En el contrato de 3º lugar de la primera vuelta está en 25,45%.`,
  'quadroComparativo[2].t': `cede en el contrato de ganador en el cuarto día de vida de su serie`,
  'quadroComparativo[2].s': `Dio una entrevista a TV Globo, según BBC.`,
  'quadroComparativo[3].m': `2,25% (vol USD 11,88M), ${S}. Sin variación, y el precio no se movió en la ventana en que la decisión del tribunal sobre su registro se hizo pública. En el contrato de 3º lugar de la primera vuelta está en 25,00%.`,
  'quadroComparativo[4].m': `0,15% (vol USD 6,97M), ${S}. Caída de 0,10pp, y por debajo del piso de 0,5% de la doble lectura. En el contrato de 3º lugar de la primera vuelta es el primer nombre, con 43,50%.`,
  'quadroComparativo[4].t': `tercero en la urna declarada, primero en el contrato de 3º lugar y último pelotón en el de ganador`,
  'quadroComparativo[4].s': `Está entre los blancos de la ofensiva que la campaña del líder abrió en el ${G('TSE', 'tse')} por publicaciones y discursos, según Folha de S.Paulo.`,
  'quadroComparativo[5].m': `0,15% (vol USD 3,07M), ${S}. Sin variación, y por debajo del piso de 0,5% de la doble lectura.`,
  'quadroComparativo[5].s': `No aparece en las noticias de este domingo con un hecho propio.`,
  'quadroComparativo[6].m': `3,60% (vol USD 84 mil), ${S}. Alza de 0,15pp, y sigue siendo el menor libro del panel.`,
  'quadroComparativo[6].t': `sube poco, y es el menor libro del panel`,


  // --- ERRATA: o despacho de Toffoli e de SABADO 29/Ago ---
  'candidates[2].fracos[3]': `${FATO}, con siete medios publicando entre las 15h47 y las 18h56 de Brasilia. Su precio no reaccionó ni el sábado ni el domingo.`,
  'candidates[2].analise': `Su cruce es el más directo del día, y el resultado es que no hubo cruce. ${FATO}, con siete medios publicando entre las 15h47 y las 18h56 de Brasilia. Su precio no se movió: 2,25% (vol USD 11,88M) en la lectura confirmada, el mismo valor del viernes, y la serie lo mantiene en 2,30% en todas las capturas del cron del sábado y del domingo, incluidas las posteriores a la publicación. Su libro es el tercero mayor del contrato de ganador, con USD 11,88M, por encima del libro del líder y del segundo, lo que hace más difícil atribuir la ausencia de movimiento a un mercado delgado. El panel registra el hecho, la fecha del acto y la ausencia de reacción, y no atribuye causa a ninguno de los tres.`,
  'quadroComparativo[3].s': `${FATO}, según Poder360 y Gazeta do Povo. El ${G('TSE', 'tse')} comienza a juzgar los registros del líder, del segundo, de Zema y de él el 31 de agosto, según Veja.`,
  'quadroComparativo[3].t': `precio estancado en los dos días en que su registro se trabó en el tribunal`,
  'quadroComparativo[6].s': `${FATO}, según Poder360. Gilmar Mendes prohibió al sindicato de jueces cobrar una cuota en vísperas de una asamblea sobre normas éticas en el tribunal, según Estadão, y limitó la contribución de los jueces que se adhirieron, según Poder360. Las propuestas para frenar al tribunal se multiplican en el Congreso y se traban bajo Alcolumbre, según Gazeta do Povo.`,
  cruzamento: `El domingo tuvo las dos mediciones andando a ritmos distintos, y eso es lo que el panel registra. La urna declarada quedó quieta: ninguna encuesta nacional fue divulgada, y la más reciente sigue siendo Vox Brasil del 29/Ago (BR-05519/2026, campo del 25 al 27/Ago, n=2.100), con margen de 2,15pp y campo presencial, con la ${G('primera vuelta', 'primeiro-turno')} en 37,1% contra 34,8% y la ${G('segunda vuelta', 'segundo-turno')} en 45,1% contra 44,5% para el segundo, dentro del margen. El precio sí anduvo, y de un solo lado: el líder no sale de 55,50% desde la tarde del viernes, en nueve capturas seguidas, y el segundo subió 1,75pp, hasta 41,10%. La distancia entre los dos cerró en 14,40pp, la más estrecha desde el 10 de junio, y el precio del segundo es el más alto suyo desde el 13 de mayo. El segundo cruce es de hecho judicial contra precio, y la fecha del acto importa. ${FATO}, con siete medios publicando entre las 15h47 y las 18h56 de Brasilia. Su contrato de ganador no se movió en ninguno de los dos días: 2,25%, el mismo valor del viernes, en un libro de USD 11,88M. El ${G('TSE', 'tse')} comienza a juzgar los registros del líder, del segundo, de Zema y de él el 31 de agosto. El tercer registro es de calendario, y viene del propio TSE: ocho encuestas nacionales tienen divulgación prevista entre el 31/Ago y el 03/Sep, tres de ellas el lunes, incluida la primera Datafolha presidencial después de las entrevistas de los candidatos en TV Globo. Registro no es divulgación, y ningún número de esas ocho entra aquí antes de salir. Lo que el panel sirve hoy es precio de domingo y encuesta del viernes, con las dos fechas declaradas.`,
})

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 139,76M y el precio de esta página es de la ${S}. ${SEM}.`,
  'cards.sentimento.text2': `En el precio, el segundo subió 1,75pp, hasta 41,10%, la mayor variación entre los nombres del panel en esta ronda, y el líder no se movió, quedando en 55,50% por segundo día. La distancia entre los dos bajó a 14,40pp, la más estrecha desde el 10/Jun, y el precio del segundo es el más alto suyo desde el 13/May.`,
  'cards.sentimento.text3': `Los contratos de 2º y 3º lugar de la primera vuelta vuelven a publicar número en esta ronda, después de una ronda sin lectura nueva: el segundo está en 85,50% para llegar a la ${G('segunda vuelta', 'segundo-turno')}, y Caiado lidera el contrato de 3º lugar con 43,50%, el mismo nombre que está en 0,15% en el contrato de ganador.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 41,10% (vol USD 9,31M) en el presidencial, alza de 1,75pp, la mayor variación entre los nombres del panel en esta ronda, y 85,50% en el contrato de 2º lugar de la primera vuelta. En la Vox del 29/Ago tiene 34,8% en la ${G('primera vuelta', 'primeiro-turno')} y 45,1% en la ${G('segunda vuelta', 'segundo-turno')}, por delante por 0,6 punto dentro del margen.`,
  'cards.sentimento.esquerda': `Lula en 55,50% (vol USD 9,50M), sin variación por segundo día. En la Vox del 29/Ago tiene 37,1% en la ${G('primera vuelta', 'primeiro-turno')}, por delante por 2,3 puntos, y 44,5% en la ${G('segunda vuelta', 'segundo-turno')}, por detrás por 0,6 punto dentro del margen de 2,15pp.`,
  'cards.sentimento.terceiraVia': `Ronaldo Caiado es el tercer nombre de la ${G('primera vuelta', 'primeiro-turno')} en la Vox del 29/Ago, con 5,0%, y en el contrato de ganador está en 0,15% (vol USD 6,97M), por debajo del piso de 0,5% de la doble lectura. En el contrato de 3º lugar de la primera vuelta es el primer nombre, con 43,50%. Augusto Cury cedió 1,40pp en el contrato de ganador, hasta 1,85%, la mayor caída entre los nombres del panel en esta ronda.`,
  'cards.sentimento.polymarket': `Precios de la ${S}. AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20 punto. El libro presidencial acumula USD 139,76M.`,
  'cards.inss.text1': `El caso que involucra al hijo del presidente siguió en las noticias de este domingo por un frente nuevo. Un amigo suyo cerró un acuerdo con el Ministerio Público para no ser detenido por corrupción, según Veja. Las investigaciones tienen como principales elementos mensajes, viajes y cercanía con lobistas, según Folha de S.Paulo.`,
  'cards.inss.text2': `Correios, que está en el centro de la indagación sobre la actuación de la lobista, cerró el segundo trimestre con una pérdida de R$ 2,4 mil millones y acumula R$ 5,5 mil millones de pérdida en el año, según Valor Econômico. El gobierno incluirá un aporte de R$ 6 mil millones en la estatal en el Presupuesto de 2027 y dice que la medida trae más estabilidad, según O Globo.`,
  'cards.inss.text3': `Del lado político, aliados del presidente intentaron contener a la lobista después de que él la llamara pillina, según Folha de S.Paulo, y su defensa evitó preguntas sobre la actuación del hijo durante la agenda de campaña.`,
  'cards.inss.text4': `El caso sigue vivo y sin desenlace. La distinción que el panel mantiene desde el inicio sigue valiendo: una cosa es el efecto sobre la evaluación del gobierno, otra es el efecto sobre la intención de voto, y las dos no se suman.`,
  'cards.inss.impactoLula': `No aislable, y no hay lectura nueva para medirlo. Ninguna encuesta nacional fue divulgada este domingo, y la Vox Brasil del 29/Ago tiene campo del 25 al 27/Ago, anterior a los hechos de este fin de semana. Las ocho nacionales registradas para el 31/Ago al 03/Sep son las primeras que pueden alcanzar el período.`,
  'cards.inss.impactoGestao': `Sin lectura nueva este domingo. La referencia vigente sigue siendo la Vox Brasil del 29/Ago, con rechazo de 52,7% al presidente, según CNN Brasil, y desaprobación de 53,3%, el mayor nivel del año, según Exame.`,
  'cards.inss.conclusao': `El 30/Ago el caso avanza por la vía judicial, con el acuerdo del amigo del hijo del presidente con el Ministerio Público, y por la vía fiscal, con la pérdida de Correios y el aporte anunciado. Ninguna de las dos tiene lectura de urna que las alcance todavía, y el panel no atribuye movimiento de precio a ellas.`,
  'cards.bancoMaster.text1': `Este domingo no trajo hecho nuevo del caso. La recolección de noticias del día devolvió cero ítems en la consulta dedicada al tema, y lo que existe es de la víspera: la primera declaración de Daniel Vorcaro en el año fue concluida el 28/Ago, con aclaraciones amplias y búsqueda de delación, según Folha de S.Paulo.`,
  'cards.bancoMaster.text2': `El reclamo del procurador general sobre sus intentos de delación es del 29/Ago, según Folha de S.Paulo, y las contradicciones del Dark Horse para justificar el dinero y la falta de rendición de cuentas también son de la víspera.`,
  'cards.bancoMaster.text3': `El caso entró en la campaña el viernes por los dos lados, y este domingo no tuvo desdoblamiento propio. El segundo esquivó el tema en la entrevista a TV Globo, según Folha de S.Paulo.`,
  'cards.bancoMaster.conclusao': `ESTA RONDA NO TIENE HECHO NUEVO DEL CASO, Y ESO ESTÁ DECLARADO. Lo que el panel muestra es el cuadro del 28 y 29/Ago, con la fecha de cada pieza en el texto. La disposición a negociar delación sigue siendo el elemento que puede cambiar el tipo de riesgo del caso, y no avanzó públicamente este domingo.`,
  'cards.stf.moraes': `Sin acto individual nuevo capturado el 30/Ago.`,
  'cards.stf.gilmar': `Prohibió al sindicato de jueces cobrar una cuota en vísperas de una asamblea sobre normas éticas en el tribunal, según Estadão, y limitó la contribución de los jueces que se adhirieron al sindicato, según Poder360.`,
  'cards.stf.dino': `Sin acto individual nuevo capturado el 30/Ago.`,
  'cards.stf.mendonca': `Sin acto individual nuevo capturado el 30/Ago, después de cuatro días seguidos como el nombre más citado del tribunal.`,

  // --- ERRATA: o despacho de Toffoli e de SABADO 29/Ago ---
  'cards.stf.toffoli': `ES EL NOMBRE DEL TRIBUNAL EN LA COBERTURA DE ESTE DOMINGO, POR UN ACTO DEL SÁBADO. ${FATO}, con siete medios publicando entre las 15h47 y las 18h56 de Brasilia, entre ellos G1, O Globo, Estadão y Poder360.`,
  'cards.stf.nexo': `EL TRIBUNAL ENTRA EN LA ELECCIÓN POR LA PUERTA DEL REGISTRO. El ${G('TSE', 'tse')} comienza a juzgar el 31 de agosto los registros de candidatura de Lula, Flávio Bolsonaro, Zema y Renan Santos, según Veja, y el de Renan Santos ya salió de la agenda por despacho del 29 de agosto. En el Congreso, las propuestas para frenar al Supremo se multiplican y se traban bajo Alcolumbre, según Gazeta do Povo. En su propia agenda de la semana, el tribunal puede juzgar Funrural, justicia gratuita e ITBI, según Valor Econômico.`,
  'cards.stf.analise': `El contrato de salida de un ministro del Supremo por juicio político antes de 2027 está en 3,60% (vol USD 84 mil), alza de 0,15pp en la ${S}. Es el menor libro del panel, y su precio no acompañó el volumen de actos del tribunal este fin de semana: el registro retirado de la agenda por despacho del 29 de agosto, las dos decisiones de Gilmar Mendes sobre el sindicato de jueces y el juicio de los registros que empieza el 31 de agosto no movieron el contrato más allá de 0,15 punto.`,
})

construir('polls-data', 'es', {
  'polymarketComparison.note': `Precios de Polymarket en la ${S}, con el libro presidencial en USD 139,76M. ${SEM}, con margen de 2,15pp y campo presencial, con la ${G('primera vuelta', 'primeiro-turno')} en 37,1% contra 34,8% y la ${G('segunda vuelta', 'segundo-turno')} en 45,1% contra 44,5% para el segundo, dentro del margen. El precio sí se movió, y por un solo lado: el líder no sale de 55,50% desde la tarde del viernes, en nueve capturas seguidas, y el segundo subió 1,75pp, hasta 41,10%. La distancia cerró en 14,40pp, la más estrecha desde el 10/Jun, y el precio del segundo es el más alto suyo desde el 13/May, sin ser máximo de la serie, que sigue en 45,50% del 06/May. ${ONDA}`,
  'polymarketComparison.candidates[0].polymarket': `55,50%`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55,50% (vol USD 9,50M) en la ${S}. Sin variación por segundo día, y su precio no sale de 55,50% desde la tarde del 29/Ago, en nueve capturas seguidas de la serie. La distancia hacia el segundo bajó a 14,40pp, la más estrecha desde el 10/Jun.`,
  'polymarketComparison.candidates[1].polymarket': `41,10%`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `41,10% (vol USD 9,31M) en la ${S}. Alza de 1,75pp, la mayor variación entre los nombres del panel en esta ronda, y su precio más alto desde el 13/May. No es máximo de la serie: el techo sigue siendo 45,50%, del 06/May. En el contrato de 2º lugar de la primera vuelta está en 85,50%.`,
  'polymarketComparison.candidates[2].polymarket': `1,85%`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `1,85% (vol USD 2,89M) en la ${S}. Caída de 1,40pp, la mayor caída entre los nombres del panel en esta ronda, en el cuarto día de vida de su serie. En el contrato de 3º lugar de la primera vuelta está en 25,45%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `2,25% (vol USD 11,88M) en la ${S}. Sin variación, incluso en la captura posterior a la decisión del tribunal sobre su registro. En el contrato de 3º lugar de la primera vuelta está en 25,00%.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,15% (vol USD 6,97M) en la ${S}. Caída de 0,10pp, y por debajo del piso de 0,5% de la doble lectura. En el contrato de 3º lugar de la primera vuelta es el primer nombre, con 43,50%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,07M) en la ${S}. Sin variación, y por debajo del piso de 0,5% de la doble lectura.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,05% (vol USD 6,37M) en la ${S}. Sin variación, y por debajo del piso de 0,5% de la doble lectura. En el contrato de 3º lugar de la primera vuelta está en 2,15%.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `0,05% (vol USD 14,06M) en la ${S}. Sin variación. No es candidato a la Presidencia: disputa la reelección en São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0,05% (vol USD 7,41M) en la ${S}. Sin variación. No es candidato a la Presidencia: disputa la gobernación de São Paulo.`,
})
