/** Mapa EN de 31/Ago/2026: só polls-data. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S31 = 'confirmed reading of Aug 31, 1:43 PM BRT (4:43 PM UTC)'
const S30 = 'confirmed reading of Aug 30, 4:40 PM BRT (7:40 PM UTC)'
const PISO = 'below the 0.5% floor of the double reading'

construir('polls-data', 'en', {
  'polls[0].note': `AtlasIntel in partnership with Bloomberg, released on Aug 31 (UOL, Exame, Estadão, Poder360, Gazeta do Povo, VEJA, Brasil de Fato). ${G('First round', 'primeiro-turno')} Lula 43.4% x Flávio Bolsonaro 33.7%, a distance of 9.7pp, with Augusto Cury at 7.8% and Renan Santos at 7.6% practically tied for third. ${G('Runoff', 'segundo-turno')} Lula 47.1% x Flávio 42.6%, a distance of 4.5pp. In the other runoff scenarios, Lula 46.6% x Ronaldo Caiado 41.0%, Lula 47.0% x Romeu Zema 40.7% and Lula 47.5% x Renan Santos 26.0%. The pollster also tested the scenario with Jair Bolsonaro, currently ineligible, in which Lula has 46.8% against 44.1%. Fieldwork Aug 25 to 30, n=5,014 surveyed by electronic form, margin of 1pp, 95% confidence, registration BR-07972/2026. It is the largest national sample in the panel's 30-day window. ⭐ ITS FIELDWORK CLOSED ON AUG 30, AFTER THE FREE ELECTORAL AIRTIME DEBUTED ON AUG 28, unlike Vox of Aug 29, whose fieldwork closed on Aug 27. The two are not comparable on that point. ⚠️ TWO NATIONAL POLLS CAME OUT ON THE SAME DAY AND DISAGREE ON THE SIZE OF THE GAP, not on its sign: this one gives 9.7pp in the first round and 4.5pp in the runoff, and BTG/Nexus of that same Aug 31 gives 6pp and 1pp. On the third-placed name the difference is 3.2pp, with 7.8% here and 11% there. Neither one contradicts the other about who is ahead.`,

  'polls[0].source': `AtlasIntel in partnership with Bloomberg, released on Aug 31, 2026 (fieldwork Aug 25 to 30, n=5,014, electronic form, margin 1.0pp, ${G('TSE', 'tse')} registration BR-07972/2026). Figures checked against Gazeta do Povo, UOL, Exame, Estadão and Poder360.`,

  'polls[1].note': `BTG/Nexus released on Aug 31 (CNN Brasil, UOL, Poder360, Gazeta do Povo, VEJA, CartaCapital) and also published on the pollster's own website. ${G('First round', 'primeiro-turno')} Lula 39% x Flávio Bolsonaro 33%, a distance of 6pp, with Augusto Cury at 11%, Ronaldo Caiado at 5%, Renan Santos at 3% and Romeu Zema at 1%. ${G('Runoff', 'segundo-turno')} Lula 46% x Flávio 45%, inside the 2pp margin. Fieldwork Aug 28 to 30, n=2,005 by phone, margin of 2pp, 95% confidence, registration BR-08900/2026, commissioned by BTG Pactual. ⭐ THE COMPARISON THAT COUNTS IS WITH THE POLLSTER ITSELF, SAME METHOD AND SAME SAMPLE, AND IT SHOWS THE THIRD-PLACED NAME MULTIPLYING BY FIVE IN ONE WEEK: against Nexus of Aug 24, Cury goes from 2% to 11%, a gain of 9 points, the first name outside the top two to reach double digits in this series, according to CNN Brasil. Over the same interval the runner-up gives up 4 points, from 37% to 33%, and the leader gives up 2, from 41% to 39%. ⚠️ AND THE RUNOFF DID NOT MOVE: it was 46% to 45% on Aug 24 and it is still 46% to 45%, meaning the first-round rearrangement did not show up in the same pollster's runoff. 📌 Two national polls came out on this Aug 31 and they disagree on the size of the gap: this one gives 6pp in the first round and 1pp in the runoff, and AtlasIntel/Bloomberg of the same day gives 9.7pp and 4.5pp.`,

  'polls[1].source': `BTG/Nexus, released on Aug 31, 2026 (fieldwork Aug 28 to 30, n=2,005, phone, margin 2.0pp, ${G('TSE', 'tse')} registration BR-08900/2026), commissioned by BTG Pactual. Figures checked against the pollster's website, CNN Brasil, UOL and Poder360.`,

  'approvalData.note': `🏷️ THE STRUCTURED FIGURES IN THIS BLOCK COME FROM GENIAL/QUAEST OF AUG 14, and they are: 46% approval against 48% disapproval, with 6% don't know, and 36% excellent or good, 25% fair and 37% poor or terrible. The panel keeps ONE pollster per block on purpose, so as not to add up the rulers of different houses. ⭐ TWO NEW READINGS ON AUG 31, declared here and NOT mixed into the figures above, both with fieldwork closed on Aug 30, that is, already after the free electoral airtime debuted on Aug 28. BTG/Nexus brings 46% approval against 51% disapproval (Poder360), and the pollster itself records that the distance between the two is the widest since May (VEJA). AtlasIntel/Bloomberg brings disapproval at 52.9%, with the rise concentrated among younger voters and lower income brackets (InfoMoney). 📌 REJECTION of the top two names, also in the two Aug 31 rounds: AtlasIntel gives 52.7% for the runner-up and 52.0% for the leader (CNN Brasil, UOL), and BTG/Nexus gives 50% for the runner-up and 49% for the leader (Metrópoles). In both houses the runner-up is the more rejected of the two, and in both the difference between them fits inside the margin. 📌 The earlier readings of the week still hold as series: PoderData/Aya of Aug 27 with 42% against 50%, Indexa/Broadcast of Aug 26 with 46% against 50% and Gerp of Aug 26 with 43% against 51%. ⚠️ Each house uses its own approval ruler, so the comparison that counts is each pollster against itself, never one pollster against another.`,

  'polymarketComparison.note': `Polymarket prices in the ${S31}, with the presidential book at USD 140.52M. TWO NATIONAL POLLS WERE RELEASED THIS MONDAY, the first since Vox Brasil of Aug 29. AtlasIntel/Bloomberg (BR-07972/2026, fieldwork Aug 25 to 30, n=5,014, electronic form, margin of 1pp) puts the ${G('first round', 'primeiro-turno')} at 43.4% to 33.7% and the ${G('runoff', 'segundo-turno')} at 47.1% to 42.6%. BTG/Nexus (BR-08900/2026, fieldwork Aug 28 to 30, n=2,005, phone, margin of 2pp) puts them at 39% to 33% and 46% to 45%. The two agree on who is ahead and disagree on the size: 9.7pp against 6pp in the first round, and 4.5pp against 1pp in the runoff. Fieldwork for both closed on Aug 30, already after the free electoral airtime debuted on Aug 28. In the price, the leader has not moved off 55.50% for the third day running, and the runner-up gave up 2.05pp, from 41.10% to 39.05%, so the distance widened from 14.40pp to 16.45pp. ⭐ THE CROSSING OF THE DAY IS IN THE DIRECTION: in the first round the two measurements point the same way, with the runner-up giving ground both in the declared ballot and in the price. In the runoff they point the same way too, and it is the leader's way: against Vox of Aug 29, which had the runner-up 0.6pp ahead, AtlasIntel hands the leader back a 4.5pp advantage and Nexus hands back 1pp, on the same day the price widened. ⚠️ And Nexus against itself did not move: it was the same 46% to 45% on Aug 24. This round publishes no new figure for Augusto Cury or for the names in the third-place contract.`,

  'polymarketComparison.candidates[0].polymarket': `55.50%`,
  'polymarketComparison.candidates[0].pesquisaRange': `39-43.4%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `AtlasIntel/Bloomberg of Aug 31 puts him at 43.4% in the ${G('first round', 'primeiro-turno')} and 47.1% in the ${G('runoff', 'segundo-turno')} against 42.6%, and BTG/Nexus of the same day puts him at 39% and 46% against 45%. In the Nexus comparison against itself, against Aug 24, he gives up 2 points in the first round and does not move in the runoff, which is still 46 to 45. Rejection of 52.0% by AtlasIntel and 49% by Nexus.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55.50% (vol USD 9.53M), ${S31}. No change on the day, and his price has not moved off 55.50% for the third day running. The distance to the runner-up widened to 16.45pp, against 14.40pp yesterday, and the whole widening came from the other side.`,

  'polymarketComparison.candidates[1].polymarket': `39.05%`,
  'polymarketComparison.candidates[1].pesquisaRange': `33-33.7%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `AtlasIntel/Bloomberg of Aug 31 puts him at 33.7% in the ${G('first round', 'primeiro-turno')} and 42.6% in the ${G('runoff', 'segundo-turno')}, 4.5 points behind the leader, and BTG/Nexus of the same day puts him at 33% and 45%, 1 point behind, inside the 2pp margin. In the Nexus comparison against itself, against Aug 24, he gives up 4 points in the first round. He is the more rejected of the two in both houses, with 52.7% by AtlasIntel and 50% by Nexus.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `39.05% (vol USD 9.37M), ${S31}. Down 2.05pp on the day, after four consecutive closes on the rise, from 35.50% on Aug 27 to 41.20% on Aug 30. In the first-round second-place contract he is still at 85.50%, unchanged.`,

  'polymarketComparison.candidates[2].polymarket': `1.85%`,
  'polymarketComparison.candidates[2].pesquisaRange': `7.8-11%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `BTG/Nexus of Aug 31 measures him at 11% in the ${G('first round', 'primeiro-turno')}, against 2% in its own round of Aug 24, a gain of 9 points in one week, and he is the first name outside the top two to reach double digits in that series, according to CNN Brasil. AtlasIntel/Bloomberg of the same day measures him at 7.8%, practically tied with Renan Santos for third. The two houses disagree by 3.2 points about him.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `This round publishes no new price for him. The last published price is the one from Aug 30, 4:40 PM BRT, at 1.85%. His contract opened on Aug 27 and the series has 68 captures, too short for a superlative.`,

  'polymarketComparison.candidates[3].polymarket': `1.85%`,
  'polymarketComparison.candidates[3].pesquisaRange': `3-7.6%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `AtlasIntel/Bloomberg of Aug 31 measures him at 7.6% in the ${G('first round', 'primeiro-turno')}, practically tied with Augusto Cury for third, and in a hypothetical ${G('runoff', 'segundo-turno')} he loses 47.5% to 26.0%. BTG/Nexus of the same day measures him at 3%, unchanged against Aug 24. It is the widest distance between the two houses on a single name this round, at 4.6 points.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1.85% (vol USD 11.95M), ${S31}. Down 0.40pp on the day. His accumulated volume is the largest in the presidential book among the names below the top two.`,

  'polymarketComparison.candidates[4].tendenciaPolymarket': `0.15% (vol USD 6.97M) in the ${S30}. Down 0.10pp, and ${PISO}. In the first-round third-place contract he is the leading name, at 43.50%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0.15% (vol USD 3.07M) in the ${S30}. No change, and ${PISO}.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0.05% (vol USD 6.37M) in the ${S30}. No change, and ${PISO}. In the first-round third-place contract he sits at 2.15%.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `0.05% (vol USD 14.06M) in the ${S30}. No change. He is not a presidential candidate: he is running for re-election in São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0.05% (vol USD 7.41M) in the ${S30}. No change. He is not a presidential candidate: he is running for governor of São Paulo.`,
})
