/** Mapa ES de 31/Ago/2026: analysis-criteriosa. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 31/Ago, 13:43 BRT (16:43 UTC)'
const ATLAS = 'AtlasIntel/Bloomberg del 31/Ago (BR-07972/2026, campo del 25 al 30/Ago, n=5.014)'
const NEXUS = 'BTG/Nexus del 31/Ago (BR-08900/2026, campo del 28 al 30/Ago, n=2.005)'
const SEM = 'Esta ronda no publica precio nuevo para él, y el último precio publicado es el del 30/Ago, 16:40 BRT'
const PISO = 'por debajo del piso de 0,5% en que la doble lectura certifica movimiento'
const TOFFOLI =
  'Dias Toffoli suspendió la propaganda electoral de la fórmula, el traspaso de recursos y el derecho a participar en debates, según G1, después de citar indicios de ilicitud en el registro y aplazar el juicio de la fórmula, según Folha de S.Paulo y O Globo'
const TSE_PROP =
  'El TSE suspendió la pieza de propaganda de su campaña que listaba un currículum del adversario citando el Banco Master y el esquema de retorno de salarios, según O Globo, Folha de S.Paulo, Terra y CBN, y la Justicia Electoral suspendió también la que lo llamaba empleado fantasma, según G1'

construir('analysis-criteriosa', 'es', {
  subtitle: `Cruce del 31 de agosto de 2026: precio de Polymarket en ${S}, libro presidencial en USD 140,52M, contra las DOS encuestas nacionales divulgadas este lunes, la ${ATLAS} y la ${NEXUS}. Son las primeras nacionales desde la Vox Brasil del 29/Ago, y el campo de las dos cerró el 30/Ago, ya después del estreno del horario electoral gratuito el 28/Ago.`,

  // ── Lula ────────────────────────────────────────────────────────────────────
  'candidates[0].header': `PRECIO: 55,50% (vol USD 9,53M acumulado), ${S}. Sin variación en el día, y su precio no sale de 55,50% por tercer día seguido. ENCUESTA: la AtlasIntel lo da en 43,4% en la ${G('primera vuelta', 'primeiro-turno')} y 47,1% en la ${G('segunda', 'segundo-turno')} contra 42,6%, y la BTG/Nexus lo da en 39% y 46% contra 45%. Las dos coinciden en que está adelante y discrepan del tamaño: 9,7pp contra 6pp en la primera vuelta.`,
  'candidates[0].fortes[0]': `Las dos nacionales de este lunes lo ponen adelante en la primera y en la segunda vuelta, y es la primera vez desde la Vox del 29/Ago que la segunda vuelta trae signo favorable a él en una encuesta nacional divulgada.`,
  'candidates[0].fortes[1]': `La AtlasIntel es la mayor muestra nacional de la ventana de 30 días del panel, con n=5.014, y en ella su ventaja en la primera vuelta es de 9,7 puntos.`,
  'candidates[0].fortes[2]': `En los escenarios alternativos de la AtlasIntel gana todos los probados: 46,6% a 41,0% contra Ronaldo Caiado, 47,0% a 40,7% contra Romeu Zema y 47,5% a 26,0% contra Renan Santos.`,
  'candidates[0].fortes[3]': `Es menos rechazado que el segundo colocado en las dos casas, con 52,0% por la AtlasIntel y 49% por la BTG/Nexus.`,
  'candidates[0].fortes[4]': `En el precio, la distancia hacia el segundo colocado se abrió a 16,45pp, contra 14,40pp de la víspera, y la apertura vino entera del lado del adversario.`,
  'candidates[0].fracos[0]': `La desaprobación del gobierno aparece por encima de la aprobación en las dos lecturas nuevas: 52,9% de desaprobación por la AtlasIntel, según InfoMoney, y 46% de aprobación contra 51% de desaprobación por la BTG/Nexus, según VEJA.`,
  'candidates[0].fracos[1]': `La propia BTG/Nexus registra que la distancia entre aprobación y desaprobación es la mayor desde mayo.`,
  'candidates[0].fracos[2]': `En la comparación de la Nexus consigo misma, contra la ronda del 24/Ago, cede 2 puntos en la primera vuelta, de 41% a 39%.`,
  'candidates[0].fracos[3]': `En la segunda vuelta de esa misma Nexus el cuadro no se movió: era 46% a 45% el 24/Ago y sigue en 46% a 45%, es decir, el reacomodo de la primera vuelta no llegó a la segunda.`,
  'candidates[0].fracos[4]': `${TSE_PROP}.`,
  'candidates[0].analise': `El lunes devolvió al panel lo que faltaba desde el 29/Ago: lectura de urna. Dos nacionales salieron el mismo día, con métodos distintos y muestras distintas, y las dos lo ponen adelante en las dos vueltas. Discrepan del tamaño, 9,7pp contra 6pp en la primera vuelta y 4,5pp contra 1pp en la segunda, y no discrepan del signo. En el precio está en 55,50% (vol USD 9,53M) y no se movió por tercer día, mientras el adversario cedió 2,05pp. Es la primera ronda de la semana en que las dos mediciones andan en la misma dirección en la ${G('primera vuelta', 'primeiro-turno')}, con el segundo colocado cediendo en la urna declarada y en el precio. El lado que no acompaña es el de la evaluación del gobierno: las dos casas traen desaprobación por encima de la aprobación, y la Nexus registra la mayor distancia entre las dos desde mayo. Intención de voto y evaluación de gobierno son reglas distintas, y el panel no las suma.`,

  // ── Flávio Bolsonaro ────────────────────────────────────────────────────────
  'candidates[1].header': `PRECIO: 39,05% (vol USD 9,37M acumulado), ${S}. Caída de 2,05pp en el día, la mayor variación entre los nombres del panel en esta ronda. ENCUESTA: la AtlasIntel lo da en 33,7% en la ${G('primera vuelta', 'primeiro-turno')} y 42,6% en la ${G('segunda', 'segundo-turno')}, y la BTG/Nexus en 33% y 45%, a 1 punto del líder y dentro del margen de 2pp.`,
  'candidates[1].fortes[0]': `En la segunda vuelta de la BTG/Nexus está a 1 punto del líder, 45% contra 46%, dentro del margen de 2pp, lo que caracteriza un ${G('empate técnico', 'empate-tecnico')}.`,
  'candidates[1].fortes[1]': `En el contrato de 2º lugar de la primera vuelta sigue en 85,50%, sin variación, y es el nombre que el mercado considera más probable para llegar a la segunda vuelta.`,
  'candidates[1].fortes[2]': `La segunda vuelta de la Nexus no se movió contra la ronda de la propia casa del 24/Ago, pese a que él cedió 4 puntos en la primera vuelta en el mismo intervalo.`,
  'candidates[1].fortes[3]': `El volumen acumulado de su contrato, USD 9,37M, es el segundo mayor del libro presidencial y está a menos de USD 0,2M del volumen del líder.`,
  'candidates[1].fortes[4]': `La propaganda de la campaña adversaria que listaba acusaciones contra él fue suspendida por el TSE y por la Justicia Electoral el mismo día, según O Globo, Folha de S.Paulo y G1.`,
  'candidates[1].fracos[0]': `Cedió 2,05pp en el precio, de 41,10% a 39,05%, después de cuatro cierres seguidos al alza que lo habían llevado de 35,50% el 27/Ago a 41,20% el 30/Ago.`,
  'candidates[1].fracos[1]': `En la comparación de la Nexus consigo misma cede 4 puntos en la primera vuelta, de 37% a 33%, el doble de la pérdida del líder en el mismo intervalo.`,
  'candidates[1].fracos[2]': `Es el más rechazado en las dos casas, con 52,7% por la AtlasIntel, según CNN Brasil, y 50% por la BTG/Nexus, según Metrópoles.`,
  'candidates[1].fracos[3]': `La distancia hacia el líder se abrió en las dos mediciones al mismo tiempo: 16,45pp en el precio, contra 14,40pp de la víspera, y 9,7pp en la AtlasIntel.`,
  'candidates[1].fracos[4]': `El excomandante de la FAB negó hacer campaña para el líder y respondió a una declaración suya, según O Tempo y G1.`,
  'candidates[1].analise': `Fue el nombre que más se movió en esta ronda, y el movimiento es de caída en las dos mediciones al mismo tiempo. En el precio cedió 2,05pp y volvió a 39,05% (vol USD 9,37M), deshaciendo buena parte de la subida de cuatro ruedas que lo había llevado a 41,20% el 30/Ago. En la urna declarada, la comparación que vale es la de la Nexus consigo misma, mismo método y misma muestra: cede 4 puntos en la primera vuelta en una semana, el doble de lo que cedió el líder. El contrapunto está en la segunda vuelta: en esa misma Nexus quedó quieta en 45% contra 46%, dentro del margen, y sigue en 85,50% en el contrato de 2º lugar de la primera vuelta. Es decir, el mercado sigue tratando como casi seguro que llega a la segunda vuelta, y lo que se movió fue la expectativa sobre lo que ocurre allí. El rechazo es el dato más estable del conjunto: es el más rechazado en las dos casas.`,

  // ── Renan Santos ────────────────────────────────────────────────────────────
  'candidates[2].header': `PRECIO: 1,85% (vol USD 11,95M acumulado), ${S}. Caída de 0,40pp en el día. ENCUESTA: la AtlasIntel lo mide en 7,6% en la ${G('primera vuelta', 'primeiro-turno')}, prácticamente empatado con Augusto Cury en la tercera posición, y la BTG/Nexus lo mide en 3%, sin variación contra el 24/Ago.`,
  'candidates[2].fortes[0]': `La AtlasIntel lo coloca en 7,6% en la primera vuelta, prácticamente empatado con Augusto Cury en 7,8%, y es su mejor marca en una nacional dentro de la ventana de 30 días del panel.`,
  'candidates[2].fortes[1]': `El volumen acumulado de su contrato, USD 11,95M, es el mayor del libro presidencial entre todos los nombres por debajo de los dos primeros.`,
  'candidates[2].fortes[2]': `Mantuvo el 3% de la BTG/Nexus sin variación contra la ronda de la propia casa del 24/Ago, en un día en que el líder y el segundo colocado cedieron.`,
  'candidates[2].fracos[0]': `${TOFFOLI}.`,
  'candidates[2].fracos[1]': `La AtlasIntel le da 67% de imagen negativa, la mayor entre los presidenciables, según CartaCapital.`,
  'candidates[2].fracos[2]': `En una segunda vuelta hipotética contra el líder pierde por 47,5% a 26,0% en la AtlasIntel, la mayor distancia entre los escenarios alternativos probados por la casa.`,
  'candidates[2].fracos[3]': `Las dos casas discrepan en 4,6 puntos sobre él, 7,6% contra 3%, la mayor distancia entre ellas sobre un mismo nombre en esta ronda.`,
  'candidates[2].analise': `Es el nombre con el contraste más fuerte de la ronda: su mejor encuesta hasta aquí y su peor decisión judicial hasta aquí, el mismo día. La AtlasIntel lo coloca en 7,6%, empatado con Augusto Cury por la tercera posición, y la BTG/Nexus lo mantiene en 3%, lo que abre una distancia de 4,6 puntos entre las dos casas sobre la misma persona. En el tribunal, Dias Toffoli suspendió propaganda, traspaso de recursos y derecho a debate de la fórmula, lo que es una decisión de alcance práctico mayor que el retiro de agenda de la víspera. En el precio cedió 0,40pp, a 1,85% (vol USD 11,95M). Su volumen sigue siendo el mayor del libro entre los nombres fuera de los dos primeros, y eso separa su caso del de Caiado o Marçal: hay dinero real posicionado, incluso con precio bajo. El dato que amarra los dos lados es la imagen negativa de 67% de la AtlasIntel, la mayor de la tabla.`,

  // ── Caiado / Haddad / Zema ──────────────────────────────────────────────────
  'candidates[3].header': `PRECIO: Caiado 0,15% (vol USD 6,97M), Haddad 0,05% (vol USD 7,41M) y Zema 0,05% (vol USD 6,37M). Los tres están ${PISO}, y esta ronda no publica precio nuevo para ninguno de ellos: los últimos precios publicados son los del 30/Ago, 16:40 BRT. ENCUESTA: la BTG/Nexus del 31/Ago coloca a Caiado en 5% en la ${G('primera vuelta', 'primeiro-turno')}, el cuarto nombre de su tabla, y a Zema en 1%, el último.`,
  'candidates[3].subtitle': `Pelotón de atrás en la ${S}. Ronaldo Caiado aparece en 5% en la primera vuelta de la BTG/Nexus y Romeu Zema en 1%, y los dos siguen por debajo del piso de 0,5% en el contrato de ganador. Augusto Cury, que no está en este bloque, es quien se movió en la urna declarada.`,
  'candidates[3].caiado.label': `CAIADO (PSD), presidencial Poly 0,15% (vol USD 6,97M acumulado), ${PISO}. ${SEM}, en 0,15%. En el contrato de 3º lugar de la primera vuelta dejó de ser el primer nombre.`,
  'candidates[3].caiado.fortes': `La BTG/Nexus lo mide en 5% en la primera vuelta, sin variación contra la ronda de la propia casa del 24/Ago, y es el cuarto nombre de su tabla, detrás de Augusto Cury. En una segunda vuelta de la AtlasIntel pierde ante el líder por 46,6% a 41,0%, distancia de 5,6 puntos, la más estrecha entre los escenarios alternativos probados.`,
  'candidates[3].caiado.fracos': `Quedó por detrás de Augusto Cury en la BTG/Nexus, que en la ronda del 24/Ago lo tenía adelante. En el contrato de ganador sigue en 0,15%, ${PISO}, y la distancia entre el 5% que la urna declarada le da y el 0,15% de la probabilidad implícita es grande, sin que las dos magnitudes se resten: una mide intención de voto y la otra, posibilidad de victoria.`,
  'candidates[3].haddad.label': `HADDAD (PT), presidencial Poly 0,05% (vol USD 7,41M acumulado), ${PISO}. ${SEM}, en 0,05%. No es candidato a la Presidencia.`,
  'candidates[3].zema.label': `ZEMA (Novo), presidencial Poly 0,05% (vol USD 6,37M acumulado), ${PISO}. ${SEM}, en 0,05%.`,
  'candidates[3].zema.fracos': `La BTG/Nexus lo mide en 1% en la primera vuelta, contra 3% en la ronda de la propia casa del 24/Ago, una pérdida de 2 puntos que lo coloca en el último lugar de su tabla. En una segunda vuelta de la AtlasIntel pierde ante el líder por 47,0% a 40,7%, distancia de 6,3 puntos, más amplia que la de Caiado.`,
  'candidates[3].fortes[0]': `RONALDO CAIADO (PSD) está en 5% en la primera vuelta de la BTG/Nexus, sin variación contra la ronda de la propia casa del 24/Ago, en un día en que los dos primeros colocados cedieron.`,
  'candidates[3].fortes[1]': `En la segunda vuelta probada por la AtlasIntel, Caiado es quien llega más cerca del líder entre los escenarios alternativos, con 41,0% contra 46,6%.`,
  'candidates[3].fortes[2]': `Los contratos de los tres acumulan volumen relevante incluso con el precio en el piso: USD 7,41M en Haddad, USD 6,97M en Caiado y USD 6,37M en Zema.`,
  'candidates[3].fortes[3]': `Ninguno de los tres fue blanco de una decisión judicial este lunes, al contrario del cuarto nombre de la tabla.`,
  'candidates[3].fracos[0]': `Los tres siguen por debajo del piso de 0,5% en el contrato de ganador, la franja en la que la doble lectura de AFOS no certifica movimiento.`,
  'candidates[3].fracos[1]': `Caiado perdió la tercera posición en la BTG/Nexus ante Augusto Cury, que saltó de 2% a 11% en la misma casa.`,
  'candidates[3].fracos[2]': `Zema cedió 2 puntos en la BTG/Nexus, de 3% a 1%, y es el último nombre de su tabla.`,
  'candidates[3].fracos[3]': `Haddad no es candidato a la Presidencia: disputa el gobierno de São Paulo, y su contrato mide un desenlace que su campaña no persigue.`,
  'candidates[3].analise': `El pelotón de atrás perdió la referencia que tenía. Hasta la ronda del 24/Ago de la BTG/Nexus, Ronaldo Caiado era el tercer nombre de la tercera vía en las nacionales y el primer nombre del contrato de 3º lugar de la primera vuelta. Este lunes mantuvo el 5% de la misma casa y fue superado por Augusto Cury, que llegó a 11%. Zema cedió 2 puntos y quedó en 1%. En el precio, los tres siguen en el piso: 0,15% en Caiado y 0,05% en Haddad y en Zema, todos por debajo del umbral de 0,5% en que la doble lectura certifica movimiento, y por eso esta ronda no publica precio nuevo para ninguno de los tres. Lo que separa este bloque del caso de Renan Santos es el volumen: sus contratos acumulan entre USD 6,37M y USD 7,41M, dinero real posicionado en un desenlace que el mercado descuenta como muy improbable.`,

  // ── Quadro comparativo ──────────────────────────────────────────────────────
  'quadroComparativo[0].p': `La ${ATLAS} lo da en 43,4% en la ${G('primera vuelta', 'primeiro-turno')} y 47,1% en la ${G('segunda', 'segundo-turno')} contra 42,6%, y la ${NEXUS} lo da en 39% y 46% contra 45%. En la comparación de la Nexus consigo misma, contra el 24/Ago, cede 2 puntos en la primera vuelta y no se mueve en la segunda, que sigue en 46 a 45. Rechazo de 52,0% por la AtlasIntel y 49% por la Nexus.`,
  'quadroComparativo[0].m': `55,50% (vol USD 9,53M), ${S}. Sin variación en el día, y su precio no sale de 55,50% por tercer día seguido. La distancia hacia el segundo se abrió a 16,45pp, contra 14,40pp de ayer.`,
  'quadroComparativo[0].t': `quieto en el precio por tercer día, y la distancia se abre solo por el lado del adversario`,
  'quadroComparativo[0].s': `${TSE_PROP}. Después de la derrota en el Senado, dijo que indicará a Messias nuevamente al Supremo, según Migalhas.`,
  'quadroComparativo[1].p': `La misma AtlasIntel lo da en 33,7% en la primera vuelta y 42,6% en la segunda, a 4,5 puntos del líder, y la Nexus lo da en 33% y 45%, a 1 punto, dentro del margen de 2pp y por lo tanto en ${G('empate técnico', 'empate-tecnico')}. En la comparación de la Nexus consigo misma cede 4 puntos en la primera vuelta, de 37% a 33%, el doble de la pérdida del líder. Es el más rechazado en las dos casas, con 52,7% por la AtlasIntel y 50% por la Nexus.`,
  'quadroComparativo[1].m': `39,05% (vol USD 9,37M), ${S}. Caída de 2,05pp, la mayor variación entre los nombres del panel en esta ronda, después de cuatro cierres seguidos al alza que lo llevaron de 35,50% el 27/Ago a 41,20% el 30/Ago. En el contrato de 2º lugar de la primera vuelta sigue en 85,50%.`,
  'quadroComparativo[1].t': `cede en las dos mediciones el mismo día, y deshace buena parte de la subida de cuatro ruedas`,
  'quadroComparativo[1].s': `Dijo que indicará al Supremo ministros contrarios al aborto, a las drogas y a las injusticias, según Gazeta do Povo. El excomandante de la FAB negó hacer campaña para el líder y respondió a una declaración suya, según O Tempo y G1.`,
  'quadroComparativo[2].p': `La ${NEXUS} lo mide en 11% en la ${G('primera vuelta', 'primeiro-turno')}, contra 2% en su propia ronda del 24/Ago, una ganancia de 9 puntos en una semana, y es el primer nombre fuera de los dos primeros en llegar a dos dígitos en esa serie, según CNN Brasil. La AtlasIntel lo mide en 7,8%, prácticamente empatado con Renan Santos.`,
  'quadroComparativo[2].m': `1,85% (vol USD 2,89M) en el contrato de ganador. ${SEM}, y su serie tiene 68 capturas, demasiado corta para un superlativo.`,
  'quadroComparativo[2].t': `el nombre que se movió en la urna declarada, sin lectura de precio nueva en esta ronda`,
  'quadroComparativo[2].s': `Las campañas de los dos primeros colocados reaccionaron a su subida en las encuestas, según UOL. La búsqueda de su nombre en Google fue 900% mayor en la semana siguiente al debate del 22/Ago, según CNN Brasil.`,
  'quadroComparativo[3].p': `La AtlasIntel lo mide en 7,6% en la primera vuelta, prácticamente empatado con Augusto Cury en la tercera posición, y en una segunda vuelta hipotética pierde por 47,5% a 26,0%. La Nexus lo mide en 3%, sin variación contra el 24/Ago. Es la mayor distancia entre las dos casas sobre un mismo nombre en esta ronda, de 4,6 puntos. La AtlasIntel le da 67% de imagen negativa, la mayor entre los presidenciables, según CartaCapital.`,
  'quadroComparativo[3].m': `1,85% (vol USD 11,95M), ${S}. Caída de 0,40pp en el día. Su volumen acumulado es el mayor del libro presidencial entre los nombres por debajo de los dos primeros.`,
  'quadroComparativo[3].t': `mejor encuesta y peor decisión judicial el mismo día`,
  'quadroComparativo[3].s': `${TOFFOLI}. Llamó al líder amigo y al segundo colocado aliado del crimen organizado, según UOL.`,
  'quadroComparativo[4].p': `La ${NEXUS} lo coloca en 5% en la primera vuelta, sin variación contra la ronda de la propia casa del 24/Ago, y es el cuarto nombre de su tabla, detrás de Augusto Cury. En una segunda vuelta de la AtlasIntel pierde ante el líder por 46,6% a 41,0%, distancia de 5,6 puntos, la más estrecha entre los escenarios alternativos.`,
  'quadroComparativo[4].m': `0,15% (vol USD 6,97M), ${PISO}. ${SEM}, en 0,15%.`,
  'quadroComparativo[4].t': `mantiene el 5% de la urna declarada y pierde la tercera posición ante otro nombre`,
  'quadroComparativo[4].s': `No aparece en el noticiero de este lunes con un hecho propio.`,
  'quadroComparativo[5].p': `Las dos nacionales de este lunes no lo traen en la tabla divulgada de la primera vuelta. La PoderData/Aya del 27/Ago lo medía en 3% en la primera vuelta.`,
  'quadroComparativo[5].m': `0,15% (vol USD 3,07M), ${PISO}. ${SEM}, en 0,15%.`,
  'quadroComparativo[5].s': `No aparece en el noticiero de este lunes con un hecho propio.`,
  'quadroComparativo[6].m': `3,60% (vol USD 84 mil), ${S}. Sin variación, y sigue siendo el menor libro del panel.`,
  'quadroComparativo[6].t': `quieto en un día de decisión del tribunal sobre una fórmula presidencial`,
  'quadroComparativo[6].s': `${TOFFOLI}. Gilmar Mendes frenó el cobro de un sindicato de jueces a magistrados no asociados, según O Globo. Después de la derrota en el Senado, el líder dijo que indicará a Messias nuevamente al tribunal, según Migalhas, y el segundo colocado dijo que indicará ministros contrarios al aborto, a las drogas y a las injusticias, según Gazeta do Povo.`,

  cruzamento: `El 31 de agosto es la primera ronda de la semana en que las dos mediciones del panel andan en la misma dirección, y eso la distingue de las anteriores. Dos nacionales fueron divulgadas el mismo día, la ${ATLAS} y la ${NEXUS}, y las dos muestran al segundo colocado cediendo en la ${G('primera vuelta', 'primeiro-turno')}. En el precio, cedió 2,05pp, de 41,10% a 39,05%, mientras el líder no salió de 55,50% por tercer día seguido. La distancia entre los dos se abrió de 14,40pp a 16,45pp, y la apertura vino de un solo lado.

Las dos casas coinciden sobre quién está adelante y discrepan sobre el tamaño: 9,7pp contra 6pp en la primera vuelta, y 4,5pp contra 1pp en la ${G('segunda', 'segundo-turno')}. La discrepancia de tamaño entre institutos con métodos distintos, formulario electrónico contra teléfono, es comportamiento normal de instrumento, y el panel publica las dos sin elegir entre ellas.

El movimiento que las dos casas registran y el precio no registra es el de Augusto Cury. La Nexus lo mide en 11% en la primera vuelta, contra 2% en su propia ronda del 24/Ago, y la AtlasIntel lo mide en 7,8%. Esta ronda no publica precio nuevo para él, y el último publicado es el del 30/Ago, 16:40 BRT, en 1,85%. La serie de su contrato tiene 68 capturas, demasiado corta para sostener un superlativo.

Lo que no acompaña al conjunto es la evaluación del gobierno. Las dos casas traen desaprobación por encima de la aprobación, con 52,9% por la AtlasIntel y 51% contra 46% por la Nexus, que registra la mayor distancia entre las dos desde mayo. Intención de voto y evaluación de gobierno son reglas distintas, medidas con preguntas distintas, y el panel no las suma ni deriva una de la otra.`,
})
