/** Mapa ES de 31/Ago/2026: analysis-data. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S = 'lectura confirmada del 31/Ago, 13:43 BRT (16:43 UTC)'
const ATLAS = 'AtlasIntel/Bloomberg (BR-07972/2026, campo del 25 al 30/Ago, n=5.014)'
const NEXUS = 'BTG/Nexus (BR-08900/2026, campo del 28 al 30/Ago, n=2.005)'

construir('analysis-data', 'es', {
  'cards.sentimento.text1': `El libro presidencial acumula USD 140,52M y el precio de esta página es de la ${S}. DOS ENCUESTAS NACIONALES FUERON DIVULGADAS ESTE LUNES, las primeras desde la Vox Brasil del 29/Ago: la ${ATLAS} y la ${NEXUS}.`,
  'cards.sentimento.text2': `En el precio, el segundo colocado cedió 2,05pp, a 39,05%, y el líder no se movió, quedando en 55,50% por tercer día seguido. La distancia entre los dos se abrió a 16,45pp, contra 14,40pp de ayer, y la apertura vino entera del lado del segundo.`,
  'cards.sentimento.text3': `En la ${G('primera vuelta', 'primeiro-turno')} las dos encuestas y el precio apuntan hacia el mismo lado, con el segundo colocado cediendo en las dos mediciones. Y el asunto de las dos casas es el tercer colocado: la Nexus mide a Augusto Cury en 11%, contra 2% en su propia ronda del 24/Ago, y la AtlasIntel lo mide en 7,8%, prácticamente empatado con Renan Santos.`,
  'cards.sentimento.direita': `Flávio Bolsonaro en 39,05% (vol USD 9,37M) en el contrato presidencial, caída de 2,05pp, y 85,50% en el contrato de 2º lugar de la primera vuelta, sin variación. La AtlasIntel lo da en 33,7% en la primera vuelta y 42,6% en la ${G('segunda', 'segundo-turno')}, y la BTG/Nexus en 33% y 45%, a 1 punto del líder y dentro del margen. Es el más rechazado en las dos casas, con 52,7% por la AtlasIntel y 50% por la Nexus.`,
  'cards.sentimento.esquerda': `Lula en 55,50% (vol USD 9,53M), sin variación por tercer día. La AtlasIntel lo da en 43,4% en la ${G('primera vuelta', 'primeiro-turno')} y 47,1% en la ${G('segunda', 'segundo-turno')}, y la BTG/Nexus en 39% y 46%. Rechazo de 52,0% por la AtlasIntel y 49% por la Nexus, y en las dos casas es menos rechazado que el segundo colocado, con la diferencia cabiendo en el margen.`,
  'cards.sentimento.terceiraVia': `Augusto Cury es el nombre que se movió en la urna declarada: 11% en la ${G('primera vuelta', 'primeiro-turno')} por la BTG/Nexus, una ganancia de 9 puntos contra la ronda de la propia casa del 24/Ago, y 7,8% por la AtlasIntel. Esta ronda no publica precio nuevo para él, y el último publicado es el del 30/Ago, 16:40 BRT, en 1,85%. Renan Santos aparece en 7,6% por la AtlasIntel y 3% por la Nexus, y está en 1,85% (vol USD 11,95M) en el contrato de ganador, caída de 0,40pp. La AtlasIntel le da 67% de imagen negativa, la mayor entre los presidenciables, según CartaCapital.`,
  'cards.sentimento.polymarket': `Precios de la ${S}. AFOS solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen dentro de 0,20 punto. El libro presidencial acumula USD 140,52M.`,

  'cards.inss.text1': `El frente del caso que apareció este lunes es patrimonial. La lobista amiga del hijo del presidente tiene una serie de deudas en la Justicia por impagos, según O Globo, que cita un reportaje sobre su historial.`,
  'cards.inss.text2': `Correos, que está en el centro de la investigación sobre la actuación de la lobista, camina hacia cerrar el año con el peor resultado de su historia, según O Globo. El gobierno presentó el Presupuesto de 2027 con un aporte de R$ 6 mil millones en la estatal, según O Globo, y el ministro de Planificación respondió que el aporte no es una transferencia instantánea de R$ 6 mil millones, según Folha de S.Paulo.`,
  'cards.inss.text3': `Del lado de la gestión, el gobierno prevé dejar en cero la fila del INSS esta misma semana, después de una caída de 86% en el tiempo de espera, según CONTEE. Es la primera vez en la semana que el caso y la gestión del instituto aparecen el mismo día con signos opuestos.`,
  'cards.inss.text4': `El caso sigue vivo y sin desenlace. La distinción que el panel mantiene desde el inicio sigue valiendo: una cosa es el efecto sobre la evaluación del gobierno, otra el efecto sobre la intención de voto, y las dos no se suman.`,
  'cards.inss.impactoLula': `Ahora existe lectura nueva, y alcanza parte del período. Las dos nacionales de este lunes tienen campo cerrado el 30/Ago, ya después del estreno del horario electoral gratuito el 28/Ago. En intención de voto el líder está en 43,4% por la AtlasIntel y 39% por la Nexus, y en esta última cede 2 puntos contra la ronda de la propia casa del 24/Ago.`,
  'cards.inss.impactoGestao': `Dos lecturas nuevas de desaprobación, declaradas aquí y no mezcladas con el bloque estructurado del panel. La AtlasIntel/Bloomberg trae desaprobación de 52,9%, con el alza concentrada entre jóvenes y franjas de menor ingreso, según InfoMoney. La BTG/Nexus trae 46% de aprobación contra 51% de desaprobación, y la propia casa registra que la distancia entre las dos es la mayor desde mayo, según VEJA.`,
  'cards.inss.conclusao': `El 31/Ago el caso avanza por la vía patrimonial, con el historial de deudas de la lobista, y por la vía fiscal, con el peor resultado de la historia de Correos y el aporte en el Presupuesto de 2027. Las dos lecturas de desaprobación divulgadas hoy tienen campo que alcanza el período, y las dos apuntan desaprobación por encima de la aprobación. El panel no les atribuye el movimiento del precio.`,

  'cards.bancoMaster.text1': `La consulta dedicada al caso devolvió cero ítems este lunes, y lo que apareció vino por vía lateral. O Globo publicó sobre el intercambio de información entre la Policía Federal y Estados Unidos respecto de las investigaciones sobre Daniel Vorcaro.`,
  'cards.bancoMaster.text2': `El caso entró en la propaganda electoral y salió de ella el mismo día. El ${G('TSE', 'tse')} suspendió la pieza de la campaña del líder que listaba un currículum del segundo colocado citando el Banco Master y el esquema de retorno de salarios, según O Globo, Folha de S.Paulo, Terra y CBN, y la Justicia Electoral suspendió también la pieza que lo llamaba empleado fantasma, según G1.`,
  'cards.bancoMaster.text3': `Es decir, el caso dejó de circular como hecho de investigación y pasó a circular como objeto de decisión electoral. No hubo desarrollo propio de la investigación este lunes.`,
  'cards.bancoMaster.conclusao': `ESTA RONDA NO TIENE HECHO NUEVO DE LA INVESTIGACIÓN, Y ESO ESTÁ DECLARADO. Lo que cambió es el lugar del caso: salió del noticiero de investigación y entró en el de propaganda suspendida. La disposición a negociar una delación sigue siendo el elemento que puede cambiar el tipo de riesgo, y no avanzó públicamente este lunes.`,

  'cards.stf.toffoli': `ES EL NOMBRE DEL TRIBUNAL EN LA COBERTURA DE ESTE LUNES, Y POR UN ACTO QUE VA MÁS ALLÁ DEL REGISTRO. Después de citar indicios de ilicitud en el registro de candidatura de Renan Santos y del vice Aroldo Medina y aplazar el juicio de la fórmula, según Folha de S.Paulo y O Globo, suspendió la propaganda electoral de la fórmula, el traspaso de recursos y el derecho a participar en debates, según G1. Es la decisión de mayor alcance práctico del tribunal sobre una candidatura presidencial esta semana.`,
  'cards.stf.moraes': `Sin acto individual nuevo capturado el 31/Ago.`,
  'cards.stf.gilmar': `Frenó el cobro de un sindicato de jueces a magistrados no asociados, según O Globo, como desarrollo de la decisión sobre la tasa que ya había prohibido la víspera.`,
  'cards.stf.dino': `Sin acto individual nuevo capturado el 31/Ago.`,
  'cards.stf.mendonca': `Sin acto individual nuevo capturado el 31/Ago.`,
  'cards.stf.nexo': `EL TRIBUNAL ENTRA EN LA ELECCIÓN POR DOS PUERTAS ESTE LUNES. Por la del registro, con la decisión que suspendió propaganda, recursos y debate de la fórmula de Renan Santos. Y por la de la composición: después de la derrota en el Senado, el líder dijo que indicará a Messias nuevamente al Supremo, según Migalhas, y el segundo colocado dijo que indicará ministros contrarios al aborto, a las drogas y a las injusticias, según Gazeta do Povo. Los dos primeros colocados hablaron de indicación al tribunal el mismo día.`,
  'cards.stf.analise': `El contrato de salida de un ministro del Supremo por impeachment antes de 2027 está en 3,60% (vol USD 84 mil), sin variación en la ${S}. Es el menor libro del panel, y siguió quieto en un día en que el tribunal suspendió la propaganda de una fórmula presidencial y los dos primeros colocados hablaron públicamente sobre a quién indicarían. El contrato mide la salida de un ministro, no la influencia del tribunal en la elección, y por eso los dos movimientos no se encuentran.`,
})
