/** Mapa ES de 31/Ago/2026: só polls-data. Vírgula decimal, ponto de milhar, igual ao pt-BR. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const S31 = 'lectura confirmada del 31/Ago, 13:43 BRT (16:43 UTC)'
const S30 = 'lectura confirmada del 30/Ago, 16:40 BRT (19:40 UTC)'
const PISO = 'por debajo del piso de 0,5% de la doble lectura'

construir('polls-data', 'es', {
  'polls[0].note': `AtlasIntel en alianza con Bloomberg, divulgada el 31/Ago (UOL, Exame, Estadão, Poder360, Gazeta do Povo, VEJA, Brasil de Fato). ${G('Primera vuelta', 'primeiro-turno')} Lula 43,4% x Flávio Bolsonaro 33,7%, distancia de 9,7pp, con Augusto Cury 7,8% y Renan Santos 7,6% prácticamente empatados en la tercera posición. ${G('Segunda vuelta', 'segundo-turno')} Lula 47,1% x Flávio 42,6%, distancia de 4,5pp. En los demás escenarios de segunda vuelta, Lula 46,6% x Ronaldo Caiado 41,0%, Lula 47,0% x Romeu Zema 40,7% y Lula 47,5% x Renan Santos 26,0%. La casa también probó el escenario con Jair Bolsonaro, hoy inelegible, en el que Lula tiene 46,8% contra 44,1%. Campo del 25 al 30/Ago, n=5.014 consultados por formulario electrónico, margen de 1pp, 95% de confianza, registro BR-07972/2026. Es la mayor muestra nacional de la ventana de 30 días del panel. ⭐ SU CAMPO CERRÓ EL 30/Ago, DESPUÉS DEL ESTRENO DEL HORARIO ELECTORAL GRATUITO EL 28/Ago, a diferencia de la Vox del 29/Ago, cuyo campo cerró el 27/Ago. Las dos no son comparables en ese punto. ⚠️ DOS NACIONALES SALIERON EL MISMO DÍA Y DISCREPAN EN EL TAMAÑO DE LA DISTANCIA, no en el signo: esta da 9,7pp en la primera vuelta y 4,5pp en la segunda, y la BTG/Nexus de ese mismo 31/Ago da 6pp y 1pp. Sobre el tercer colocado la diferencia es de 3,2pp, con 7,8% aquí y 11% allá. Ninguna de las dos contradice a la otra sobre quién está adelante.`,

  'polls[0].source': `AtlasIntel en alianza con Bloomberg, divulgada el 31/Ago/2026 (campo del 25 al 30/Ago, n=5.014, formulario electrónico, margen 1,0pp, registro ${G('TSE', 'tse')} BR-07972/2026). Números verificados en Gazeta do Povo, UOL, Exame, Estadão y Poder360.`,

  'polls[1].note': `BTG/Nexus divulgada el 31/Ago (CNN Brasil, UOL, Poder360, Gazeta do Povo, VEJA, CartaCapital) y publicada también en el sitio del propio instituto. ${G('Primera vuelta', 'primeiro-turno')} Lula 39% x Flávio Bolsonaro 33%, distancia de 6pp, con Augusto Cury 11%, Ronaldo Caiado 5%, Renan Santos 3% y Romeu Zema 1%. ${G('Segunda vuelta', 'segundo-turno')} Lula 46% x Flávio 45%, dentro del margen de 2pp. Campo del 28 al 30/Ago, n=2.005 por teléfono, margen de 2pp, 95% de confianza, registro BR-08900/2026, contratada por BTG Pactual. ⭐ LA COMPARACIÓN QUE VALE ES CON LA PROPIA CASA, MISMO MÉTODO Y MISMA MUESTRA, Y MUESTRA AL TERCER COLOCADO MULTIPLICANDO POR CINCO EN UNA SEMANA: contra la Nexus del 24/Ago, Cury pasa de 2% a 11%, una ganancia de 9 puntos, el primer nombre fuera de los dos primeros en llegar a dos dígitos en esta serie, según CNN Brasil. En el mismo intervalo el segundo colocado cede 4 puntos, de 37% a 33%, y el líder cede 2, de 41% a 39%. ⚠️ Y LA SEGUNDA VUELTA NO SE MOVIÓ: era 46% a 45% el 24/Ago y sigue en 46% a 45%, es decir, el reacomodo de la primera vuelta no apareció en la segunda vuelta de la misma casa. 📌 Dos nacionales salieron este 31/Ago y discrepan en el tamaño de la distancia: esta da 6pp en la primera vuelta y 1pp en la segunda, y la AtlasIntel/Bloomberg del mismo día da 9,7pp y 4,5pp.`,

  'polls[1].source': `BTG/Nexus, divulgada el 31/Ago/2026 (campo del 28 al 30/Ago, n=2.005, teléfono, margen 2,0pp, registro ${G('TSE', 'tse')} BR-08900/2026), contratada por BTG Pactual. Números verificados en el sitio del instituto, CNN Brasil, UOL y Poder360.`,

  'approvalData.note': `🏷️ LOS NÚMEROS ESTRUCTURADOS DE ESTE BLOQUE SON DE GENIAL/QUAEST DEL 14/Ago, y son estos: 46% de aprobación contra 48% de desaprobación, con 6% de no sabe, y 36% de excelente o bueno, 25% de regular y 37% de malo o pésimo. El panel mantiene UNA casa por bloque a propósito, para no sumar reglas de institutos diferentes. ⭐ DOS LECTURAS NUEVAS EL 31/Ago, declaradas aquí y NO mezcladas arriba, las dos con campo cerrado el 30/Ago, es decir, ya después del estreno del horario electoral gratuito el 28/Ago. La BTG/Nexus trae 46% de aprobación contra 51% de desaprobación (Poder360), y la propia casa registra que la distancia entre las dos es la mayor desde mayo (VEJA). La AtlasIntel/Bloomberg trae desaprobación de 52,9%, con el alza concentrada entre jóvenes y franjas de menor ingreso (InfoMoney). 📌 RECHAZO a los dos primeros colocados, también en las dos rondas del 31/Ago: la AtlasIntel da 52,7% para el segundo colocado y 52,0% para el líder (CNN Brasil, UOL), y la BTG/Nexus da 50% para el segundo y 49% para el líder (Metrópoles). En las dos casas el segundo colocado es el más rechazado, y en las dos la diferencia entre ellos cabe en el margen. 📌 Las lecturas anteriores de la semana siguen valiendo como serie: PoderData/Aya del 27/Ago con 42% contra 50%, Indexa/Broadcast del 26/Ago con 46% contra 50% y Gerp del 26/Ago con 43% contra 51%. ⚠️ Cada casa usa su propia regla de aprobación, así que la comparación que vale es la de cada instituto consigo mismo, nunca entre institutos.`,

  'polymarketComparison.note': `Precios de Polymarket en la ${S31}, con el libro presidencial en USD 140,52M. DOS ENCUESTAS NACIONALES FUERON DIVULGADAS ESTE LUNES, las primeras desde la Vox Brasil del 29/Ago. La AtlasIntel/Bloomberg (BR-07972/2026, campo del 25 al 30/Ago, n=5.014, formulario electrónico, margen de 1pp) trae la ${G('primera vuelta', 'primeiro-turno')} en 43,4% a 33,7% y la ${G('segunda', 'segundo-turno')} en 47,1% a 42,6%. La BTG/Nexus (BR-08900/2026, campo del 28 al 30/Ago, n=2.005, teléfono, margen de 2pp) trae 39% a 33% y 46% a 45%. Las dos coinciden sobre quién está adelante y discrepan sobre el tamaño: 9,7pp contra 6pp en la primera vuelta, y 4,5pp contra 1pp en la segunda. El campo de las dos cerró el 30/Ago, ya después del estreno del horario electoral gratuito el 28/Ago. En el precio, el líder no sale de 55,50% por tercer día seguido, y el segundo colocado cedió 2,05pp, de 41,10% a 39,05%, de modo que la distancia se abrió de 14,40pp a 16,45pp. ⭐ EL CRUCE DEL DÍA ESTÁ EN LA DIRECCIÓN: en la primera vuelta las dos mediciones apuntan hacia el mismo lado, con el segundo colocado cediendo en la urna declarada y en el precio. En la segunda vuelta apuntan hacia el mismo lado también, y es el lado del primer colocado: contra la Vox del 29/Ago, que daba al segundo 0,6pp adelante, la AtlasIntel devuelve 4,5pp de ventaja al líder y la Nexus devuelve 1pp, el mismo día en que el precio se abrió. ⚠️ Y la Nexus contra ella misma no se movió: eran los mismos 46% a 45% el 24/Ago. Esta ronda no publica número nuevo para Augusto Cury ni para los nombres del contrato de tercer lugar.`,

  'polymarketComparison.candidates[0].polymarket': `55,50%`,
  'polymarketComparison.candidates[0].pesquisaRange': `39-43,4%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa': `La AtlasIntel/Bloomberg del 31/Ago lo da en 43,4% en la ${G('primera vuelta', 'primeiro-turno')} y 47,1% en la ${G('segunda', 'segundo-turno')} contra 42,6%, y la BTG/Nexus del mismo día lo da en 39% y 46% contra 45%. En la comparación de la Nexus consigo misma, contra el 24/Ago, cede 2 puntos en la primera vuelta y no se mueve en la segunda, que sigue en 46 a 45. Rechazo de 52,0% por la AtlasIntel y 49% por la Nexus.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': `55,50% (vol USD 9,53M), ${S31}. Sin variación en el día, y su precio no sale de 55,50% por tercer día seguido. La distancia hacia el segundo se abrió a 16,45pp, contra 14,40pp de ayer, y la apertura vino entera del otro lado.`,

  'polymarketComparison.candidates[1].polymarket': `39,05%`,
  'polymarketComparison.candidates[1].pesquisaRange': `33-33,7%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa': `La AtlasIntel/Bloomberg del 31/Ago lo da en 33,7% en la ${G('primera vuelta', 'primeiro-turno')} y 42,6% en la ${G('segunda', 'segundo-turno')}, a 4,5 puntos del líder, y la BTG/Nexus del mismo día lo da en 33% y 45%, a 1 punto, dentro del margen de 2pp. En la comparación de la Nexus consigo misma, contra el 24/Ago, cede 4 puntos en la primera vuelta. Es el más rechazado en las dos casas, con 52,7% por la AtlasIntel y 50% por la Nexus.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `39,05% (vol USD 9,37M), ${S31}. Caída de 2,05pp en el día, después de cuatro cierres seguidos al alza, de 35,50% el 27/Ago a 41,20% el 30/Ago. En el contrato de 2º lugar de la primera vuelta sigue en 85,50%, sin variación.`,

  'polymarketComparison.candidates[2].polymarket': `1,85%`,
  'polymarketComparison.candidates[2].pesquisaRange': `7,8-11%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa': `La BTG/Nexus del 31/Ago lo mide en 11% en la ${G('primera vuelta', 'primeiro-turno')}, contra 2% en su propia ronda del 24/Ago, una ganancia de 9 puntos en una semana, y es el primer nombre fuera de los dos primeros en llegar a dos dígitos en esa serie, según CNN Brasil. La AtlasIntel/Bloomberg del mismo día lo mide en 7,8%, prácticamente empatado con Renan Santos en la tercera posición. Las dos casas discrepan en 3,2 puntos sobre él.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `Esta ronda no publica precio nuevo para él. El último precio publicado es el del 30/Ago, 16:40 BRT, en 1,85%. Su contrato se abrió el 27/Ago y la serie tiene 68 capturas, demasiado corta para un superlativo.`,

  'polymarketComparison.candidates[3].polymarket': `1,85%`,
  'polymarketComparison.candidates[3].pesquisaRange': `3-7,6%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa': `La AtlasIntel/Bloomberg del 31/Ago lo mide en 7,6% en la ${G('primera vuelta', 'primeiro-turno')}, prácticamente empatado con Augusto Cury en la tercera posición, y en una ${G('segunda vuelta', 'segundo-turno')} hipotética pierde por 47,5% a 26,0%. La BTG/Nexus del mismo día lo mide en 3%, sin variación contra el 24/Ago. Es la mayor distancia entre las dos casas sobre un mismo nombre en esta ronda, de 4,6 puntos.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `1,85% (vol USD 11,95M), ${S31}. Caída de 0,40pp en el día. Su volumen acumulado es el mayor del libro presidencial entre los nombres por debajo de los dos primeros.`,

  'polymarketComparison.candidates[4].tendenciaPolymarket': `0,15% (vol USD 6,97M) en la ${S30}. Caída de 0,10pp, y ${PISO}. En el contrato de 3º lugar de la primera vuelta es el primer nombre, con 43,50%.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `0,15% (vol USD 3,07M) en la ${S30}. Sin variación, y ${PISO}.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `0,05% (vol USD 6,37M) en la ${S30}. Sin variación, y ${PISO}. En el contrato de 3º lugar de la primera vuelta está en 2,15%.`,
  'polymarketComparison.candidates[7].tendenciaPolymarket': `0,05% (vol USD 14,06M) en la ${S30}. Sin variación. No es candidato a la Presidencia: disputa la reelección en São Paulo.`,
  'polymarketComparison.candidates[8].tendenciaPolymarket': `0,05% (vol USD 7,41M) en la ${S30}. Sin variación. No es candidato a la Presidencia: disputa el gobierno de São Paulo.`,
})
