/** Mapa EN de 31/Ago/2026: analysis-data. Ponto decimal, vírgula de milhar. */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const S = 'confirmed reading of Aug 31, 1:43 PM BRT (4:43 PM UTC)'
const ATLAS = 'AtlasIntel/Bloomberg (BR-07972/2026, fieldwork Aug 25 to 30, n=5,014)'
const NEXUS = 'BTG/Nexus (BR-08900/2026, fieldwork Aug 28 to 30, n=2,005)'

construir('analysis-data', 'en', {
  'cards.sentimento.text1': `The presidential book has accumulated USD 140.52M and the price on this page is from the ${S}. TWO NATIONAL POLLS WERE RELEASED THIS MONDAY, the first since Vox Brasil of Aug 29: ${ATLAS} and ${NEXUS}.`,
  'cards.sentimento.text2': `In the price, the runner-up gave up 2.05pp, to 39.05%, and the leader did not move, holding at 55.50% for the third day running. The distance between the two widened to 16.45pp, against 14.40pp yesterday, and the whole widening came from the runner-up's side.`,
  'cards.sentimento.text3': `In the ${G('first round', 'primeiro-turno')} the two polls and the price point the same way, with the runner-up giving ground in both measurements. And the subject in both houses is the third-placed name: Nexus measures Augusto Cury at 11%, against 2% in its own round of Aug 24, and AtlasIntel measures him at 7.8%, practically tied with Renan Santos.`,
  'cards.sentimento.direita': `Flávio Bolsonaro at 39.05% (vol USD 9.37M) in the presidential contract, down 2.05pp, and 85.50% in the first-round second-place contract, unchanged. AtlasIntel puts him at 33.7% in the first round and 42.6% in the ${G('runoff', 'segundo-turno')}, and BTG/Nexus at 33% and 45%, 1 point behind the leader and inside the margin. He is the more rejected of the two in both houses, with 52.7% by AtlasIntel and 50% by Nexus.`,
  'cards.sentimento.esquerda': `Lula at 55.50% (vol USD 9.53M), unchanged for the third day. AtlasIntel puts him at 43.4% in the ${G('first round', 'primeiro-turno')} and 47.1% in the ${G('runoff', 'segundo-turno')}, and BTG/Nexus at 39% and 46%. Rejection of 52.0% by AtlasIntel and 49% by Nexus, and in both houses he is less rejected than the runner-up, with the difference fitting inside the margin.`,
  'cards.sentimento.terceiraVia': `Augusto Cury is the name that moved in the declared ballot: 11% in the ${G('first round', 'primeiro-turno')} by BTG/Nexus, a gain of 9 points against its own round of Aug 24, and 7.8% by AtlasIntel. This round publishes no new price for him, and the last one published is from Aug 30, 4:40 PM BRT, at 1.85%. Renan Santos comes in at 7.6% by AtlasIntel and 3% by Nexus, and sits at 1.85% (vol USD 11.95M) in the outright-winner contract, down 0.40pp. AtlasIntel gives him a 67% negative image, the highest among the presidential candidates, according to CartaCapital.`,
  'cards.sentimento.polymarket': `Prices from the ${S}. AFOS only publishes a price that two independent readings, taken eight minutes apart, confirm within 0.20 point. The presidential book has accumulated USD 140.52M.`,

  'cards.inss.text1': `The front of the case that surfaced this Monday is a financial one. The lobbyist who is a friend of the president's son has a series of court debts over unpaid bills, according to O Globo, which cites reporting on her record.`,
  'cards.inss.text2': `The postal service, which sits at the centre of the inquiry into the lobbyist's activity, is heading for the worst annual result in its history, according to O Globo. The government presented the 2027 budget with a R$ 6 billion capital injection into the state company, according to O Globo, and the planning minister replied that the injection is not a R$ 6 billion instant transfer, according to Folha de S.Paulo.`,
  'cards.inss.text3': `On the management side, the government expects to clear the INSS queue this week, after an 86% drop in waiting time, according to CONTEE. It is the first time this week that the case and the running of the institute appear on the same day with opposite signs.`,
  'cards.inss.text4': `The case is still live and unresolved. The distinction the panel has kept from the start still holds: the effect on the government's ratings is one thing, the effect on voting intention is another, and the two do not add up.`,
  'cards.inss.impactoLula': `There is now a new reading, and it reaches part of the period. Both national polls released this Monday closed fieldwork on Aug 30, already after the free electoral airtime debuted on Aug 28. In voting intention the leader is at 43.4% by AtlasIntel and 39% by Nexus, and in the latter he gives up 2 points against the same house's round of Aug 24.`,
  'cards.inss.impactoGestao': `Two new disapproval readings, declared here and not mixed into the panel's structured block. AtlasIntel/Bloomberg brings disapproval at 52.9%, with the rise concentrated among younger voters and lower income brackets, according to InfoMoney. BTG/Nexus brings 46% approval against 51% disapproval, and the house itself records that the distance between the two is the widest since May, according to VEJA.`,
  'cards.inss.conclusao': `On Aug 31 the case advances on the financial front, with the lobbyist's record of debts, and on the fiscal front, with the postal service's worst result in its history and the injection in the 2027 budget. Both disapproval readings released today have fieldwork that reaches the period, and both put disapproval above approval. The panel does not attribute the price move to them.`,

  'cards.bancoMaster.text1': `The query dedicated to the case returned zero items this Monday, and what did surface came in sideways. O Globo published on the exchange of information between the Federal Police and the United States regarding the investigations into Daniel Vorcaro.`,
  'cards.bancoMaster.text2': `The case entered electoral advertising and left it on the same day. The ${G('TSE', 'tse')} suspended the leader's campaign spot that listed a résumé of the runner-up citing Banco Master and the payroll kickback scheme, according to O Globo, Folha de S.Paulo, Terra and CBN, and the Electoral Court also suspended the spot that called him a ghost employee, according to G1.`,
  'cards.bancoMaster.text3': `That is, the case stopped circulating as an investigative fact and started circulating as the object of an electoral ruling. There was no development of the inquiry itself this Monday.`,
  'cards.bancoMaster.conclusao': `THIS ROUND HAS NO NEW FACT FROM THE INQUIRY, AND THAT IS DECLARED. What changed is the case's location: it left the investigation news cycle and entered the suspended-advertising one. The willingness to negotiate a plea deal is still the element that could change the type of risk, and it did not advance publicly this Monday.`,

  'cards.stf.toffoli': `HE IS THE COURT'S NAME IN THIS MONDAY'S COVERAGE, AND FOR AN ACT THAT GOES BEYOND THE REGISTRATION. After citing signs of illegality in the candidacy registration of Renan Santos and running mate Aroldo Medina and postponing the ticket's ruling, according to Folha de S.Paulo and O Globo, he suspended the ticket's electoral advertising, its transfer of funds and its right to take part in debates, according to G1. It is the court's most far-reaching practical decision on a presidential candidacy this week.`,
  'cards.stf.moraes': `No new individual act captured on Aug 31.`,
  'cards.stf.gilmar': `He barred a judges' union from charging non-member magistrates, according to O Globo, following on from the decision on the fee he had already prohibited the day before.`,
  'cards.stf.dino': `No new individual act captured on Aug 31.`,
  'cards.stf.mendonca': `No new individual act captured on Aug 31.`,
  'cards.stf.nexo': `THE COURT ENTERS THE ELECTION THROUGH TWO DOORS THIS MONDAY. Through registration, with the decision that suspended advertising, funds and debate rights for the Renan Santos ticket. And through composition: after the defeat in the Senate, the leader said he will nominate Messias to the Supreme Court again, according to Migalhas, and the runner-up said he will nominate justices opposed to abortion, drugs and injustice, according to Gazeta do Povo. The top two names spoke about court nominations on the same day.`,
  'cards.stf.analise': `The contract on a Supreme Court justice leaving by impeachment before 2027 sits at 3.60% (vol USD 84 thousand), unchanged in the ${S}. It is the smallest book on the panel, and it stayed still on a day when the court suspended a presidential ticket's advertising and the top two names spoke publicly about whom they would nominate. The contract measures a justice leaving, not the court's influence on the election, and that is why the two movements do not meet.`,
})
