/**
 * Mapa ES da ERRATA de serie de 11/Ago para analysis-criteriosa.json.
 * Restaura o topo do Flavio (34,40% em 13/Mai) e o piso do Renan (6,80% em 06/Ago),
 * que a rodada de fechamento havia trocado por valores de fecho-do-dia.
 */
import { construir } from '../build-locale-json'

construir('analysis-criteriosa', 'es', {
  'candidates[1].analise':
    "SU DÍA TIENE EL MEJOR Y EL PEOR DATO DE LA VENTANA, Y LOS DOS SALIERON JUNTOS. Gerp lo pone por delante en la segunda vuelta, con 45% contra 43%, y es la primera nacional del período en hacerlo; la propia difusión trata la diferencia de 2pp como empate técnico dentro del margen. El mismo día CNT/MDA lo pone nueve puntos por detrás, con 39% contra 48%. Futura queda en el medio, con 44% contra 46,5%. EN LA PRIMERA VUELTA LA DISTANCIA ES IGUALMENTE GRANDE: 28,7% en CNT/MDA y 38% en Gerp, 9,3 puntos entre dos lecturas del mismo día. SU AMPLITUD EN LA VENTANA LLEGÓ A 11,3pp, contra 6pp del líder, y el 28,7% abrió un piso nuevo. Elegir una de las tres es elegir la conclusión, y por eso el panel publica el conjunto. EN EL PRECIO EL DÍA FUE DE IDA Y VUELTA Y TERMINÓ EN CERO: cayó a 26,95% en la lectura de las 16:27 y cerró en 27,25%, exactamente donde estaba el 10/Ago. En la serie de 90 días, 25 tuvieron un valor igual o superior, con un techo de 34,40% el 13/May y un piso de 22,00% el 3/Jul. EL RECHAZO SIGUE ALTO: 47,1% en Futura, en empate técnico con el 45,9% del líder. EN EL TABLERO, afirmó el 11/Ago que irá a los debates y que no debe explicaciones sobre el caso Master, grabó propaganda con Michelle Bolsonaro afirmando que Moraes es articulador del adversario, y insinuó el fin de la reelección para atraer partidos. 📌 El eslogan de su campaña salió el 10/Ago, no hoy.",
  'candidates[2].fortes[1]':
    "Cerró 0,10pp por encima del 10/Ago, y en la serie de 90 días 78 tuvieron un valor igual o superior, con un piso de 6,80% el 6/Ago.",
  'candidates[2].analise':
    "FUE EL ÚNICO NOMBRE EN MOVERSE DE VERDAD EN TODO EL DÍA, Y EL MOVIMIENTO FUE DE IDA Y VUELTA. En la lectura de las 16:27 marcaba 8,40%, un alza de 0,75pp; en la lectura de cierre, a las 18:22, estaba en 7,75%, es decir, 0,10pp por encima del 10/Ago. ⚠️ LAS DOS LECTURAS FUERON CONFIRMADAS, cada una por dos capturas tomadas con ocho minutos de intervalo, así que ninguna está equivocada: el día simplemente siguió después de la primera. El panel publica el cierre y registra el camino, porque esconder el camino haría que una oscilación de 1,4pp pareciera un día estancado. En la serie de 90 días, 78 tuvieron un valor igual o superior a 7,75%, con un techo de 17,90% el 9/Jun y un piso de 6,80% el 6/Ago. EN LA ENCUESTA Gerp le da 5% en la primera vuelta, por detrás solo del 10% que Palver midió por internet el 10/Ago, y CNT/MDA y Futura no publicaron el campo completo. EL EFECTO DE MÉTODO SIGUE SIENDO LA LECTURA CENTRAL SOBRE ÉL: el mismo nombre va de 4% a 10% según el entorno de la entrevista, y la salvedad no es de este panel, fue declarada por la propia Palver, que informó que prueba enfoques para reducir el efecto en encuestas online. ⚠️ EL PANEL NO ATRIBUYE NINGUNA DE LAS DOS PUNTAS DE ESE VAIVÉN A LA DISCUSIÓN PÚBLICA SOBRE MÉTODO que la prensa hizo el 10 y el 11/Ago. No hay medición que ligue las dos cosas. Sigue con el mayor volumen acumulado del libro entre los nombres por encima de 1%, con USD 9,44M.",
})
