/**
 * Mapa EN de analysis-data.json — 29/Jul/2026.
 *
 * Convenções: ponto decimal e vírgula de milhar. "pesquisa" é poll, nunca
 * research. "urna" é polling, mas "urna eletrônica" é voting machine.
 * Link de glossário só na PRIMEIRA ocorrência de cada termo por campo.
 */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/en/glossary#${id})`

construir('analysis-data', 'en', {
  'cards.sentimento.text1':
    `With 67 days to the ${G('first round', 'primeiro-turno')}, Wednesday gave the panel exactly what was missing yesterday: a national poll, and the largest sample in the window. ${G('AtlasIntel', 'atlasintel')}/Bloomberg (field Jul 22 to 27, n=5,021, 1pp margin, 95% confidence, BR-08602/2026, cost of R$ 80,000, self-funded) has Lula at 44.9% and Flávio Bolsonaro at 35.8% in the first round, a gap of 9.1pp, with Renan Santos at 7.8%, Ronaldo Caiado at 3.1% and Romeu Zema at 2.8%. In a scenario reduced to five names, Lula goes to 47.4% and Flávio to 37.0%. In the ${G('runoff', 'segundo-turno')}, Lula wins the SIX scenarios he appears in, and his tightest margin is not against Flávio: it is against JAIR Bolsonaro, 49.2% to 43.9%, a difference of 5.3pp against the 6.3pp of the scenario with the son. The distance between those two scenarios, 1.0pp, sits at the edge of the margin, so the panel does not call this a reversal and records that, by the same institute and in the same field period, the father's name tests equal or better. In the two scenarios WITHOUT Lula, Haddad 44.3% x Flávio 43.7%, a ${G('statistical tie', 'empate-tecnico')}, and Alckmin 45.8% x Flávio 42.7%.`,
  'cards.sentimento.text2':
    `The day's cross-reading is the exact inverse of yesterday's, and the inversion is the finding. Yesterday there was no national polling and the favourite's price ROSE 1.00pp. Today the largest-sample poll of the window came out and the favourite's price FELL 1.00pp, from 63.50% to 62.50%, with the gap over Flávio easing from +39.65pp to +38.55pp. The direction matches the poll's, which also narrowed the gap, but the sizes do not: against the institute's own Jul 1 round, the first-round gap narrowed by 0.6pp, from 9.7pp to 9.1pp, while the market narrowed by 1.10pp. And there is a detail that changes the reading: in that comparison BOTH front-runners fall, Lula from 46.3% to 44.9% and Flávio from 36.6% to 35.8%, and with a 1pp margin each of those moves fits inside the noise. In other words, the polling says stability, not advance or retreat. The panel records the coincidence of direction and does NOT claim the poll moved the price, because the same session carried the fallout of the artificial-intelligence video at the ${G('STF', 'stf')} and the Brazilian government's reading that the extension of the US emergency may be preparing new sanctions.`,
  'cards.sentimento.text3':
    `In the market, Lula fell 1.00pp to 62.50% (vol USD 7.73M), and the level caveat matters: this is not a drop in level, it is the same value as Jul 25 and Jul 27, with the top of the AFOS series having marked 63.50% on Jul 26 and Jul 28. Flávio rose 0.10pp to 23.95% (vol USD 7.70M), and the daily close of the series records his FOURTH consecutive advance, up from 22.90% on Jul 25. Renan Santos fell 0.15pp to 8.60% (vol USD 8.59M), but the number of his that matters today is another one: with 7.8% in the polling, the distance between price and declared vote fell to 0.80pp, and in this round it narrowed on the POLLING side, which rose, and not on the price side, as had been happening since June. Caiado inverted the signal of the two previous sessions: he rose 0.45pp in the winner contract, to 2.35%, and fell 1.00pp in first-round third place, to 25.50%, with Renan recovering 1.00pp in that book, to 61.50%. Zema rose 0.20pp, to 0.75%. Total accumulated volume in the presidential book at USD 116.49M. Capture note: the double-reading guard REJECTED the first round over a 1.00pp divergence in Renan's third place and APPROVED the second with no divergence at all, four readings in total across sixteen minutes, so every price enters firm and there is no range.`,
  'cards.sentimento.direita':
    `Flávio rose 0.10pp to 23.95% (vol USD 7.70M), a fourth consecutive daily close on the rise in the AFOS series, up from 22.90% on Jul 25. In the sub-markets, he stayed FLAT at 78.00% in first-round second place for a second session and FELL 1.50pp in third place, to 6.25%. In the polling, ${G('AtlasIntel', 'atlasintel')} has him at 35.8% in the ${G('first round', 'primeiro-turno')}, a 0.8pp retreat against the institute's Jul 1 round, and at 42.9% in the ${G('runoff', 'segundo-turno')}. The hardest number for him is the 52.9% rejection, the highest among those tested, which sits 17.1pp above his own voting intention; for Lula that distance is 4.5pp. Among state polls, the day was good where the votes are: he leads São Paulo in BOTH rounds, 34% x 30% in the first and 40% x 35% in the runoff (Genial/${G('Quaest', 'quaest')}, n=1,650, field Jul 23 to 27, BR-09998/2026). On the institutional front, the bill for his own convention arrived: Jair Bolsonaro's defence told the ${G('STF', 'stf')} he did NOT authorise the use of his own image and voice in the artificial-intelligence video, after Moraes gave 48 hours on Jul 28, while Flávio's campaign told the ${G('TSE', 'tse')} the video is legal and does not deceive voters (Folha de S.Paulo, O Globo, Estadão, Jul 29). He still has no running mate, with the Aug 5 deadline less than a week away.`,
  'cards.sentimento.esquerda':
    `Lula fell 1.00pp to 62.50% (vol USD 7.73M) on the day the largest-sample national poll of the window came out. It is not a drop in level: 62.50% is the same value as Jul 25 and Jul 27, and the top of the AFOS series marked 63.50% on Jul 26 and Jul 28. By the daily close, today's gap over Flávio, +38.55pp at the capture, is the narrowest since Jul 24. In the polling, ${G('AtlasIntel', 'atlasintel')} has him at 44.9% in the ${G('first round', 'primeiro-turno')} and winning the six runoffs he appears in, with approval of his performance rising 1.7pp against the Jul 1 round, from 45.9% to 47.6%, and disapproval falling 1.1pp, from 52.3% to 51.2%. Disapproval remains ahead by the same method. Among the state polls released today, he dominates the Northeast, with 52% in Bahia and 54% in Ceará, and LOSES São Paulo in both rounds, which completes the picture of a geographically split race with the largest electoral college on the opposing side. On the institutional front, he publicly complained about corporatism among judges and prosecutors and argued for institutional reform (Folha de S.Paulo), and the São Paulo electoral court fined him R$ 15,000 for early campaigning, ordering the video taken down (Estadão, G1, Valor Econômico).`,
  'cards.sentimento.terceiraVia':
    `The pack inverted the signal of the two previous days, and the inversion is in Caiado. He had been rising in the third-place book and falling in the winner book; today he RISES 0.45pp in the winner, to 2.35% (vol USD 5.20M), and FALLS 1.00pp in first-round third place, to 25.50%. The 2.35% of this capture sits above every daily close of the AFOS series since Jun 20, when the series marked 2.30%, and the series maximum is 2.40%, from Apr 14 and Jun 19. Except that the polling went hard against him: ${G('AtlasIntel', 'atlasintel')} has him at 3.1% in the ${G('first round', 'primeiro-turno')}, half the 6% from ${G('BTG/Nexus', 'nexus-btg')} two days earlier, and in the ${G('runoff', 'segundo-turno')} it has him losing 48.2% to 38.9%, far from the ${G('statistical tie', 'empate-tecnico')} of 45% to 43% in that survey. The divergence the panel recorded on Jul 27 gained a third measurement and it landed on ${G('Datafolha', 'datafolha')}'s side. Politically it was his best day: Tarcísio de Freitas cleared allies to back his candidacy (CNN Brasil) and he began attacking Lula and Flávio in equal measure (Folha de S.Paulo). The pack's best polling number, though, belongs to Haddad, for a reason of method: it is NATIONAL. In one of AtlasIntel's scenarios without Lula he ties statistically with Flávio, 44.3% to 43.7%, and his price in the first-round second-place book rose 0.35pp, to 1.20%, while the winner contract stayed at 0.25%. Zema rose 0.20pp to 0.75%, and the national poll reframes yesterday's state number: in the national runoff he loses 48.6% to 39.6%. Michelle stayed at 0.45%, Jair at 1.05%, Alckmin rose 0.10pp to 0.35% and Camilo Santana fell 0.05pp to 0.35%.`,
  'cards.sentimento.polymarket':
    `Lula 62.50% (down 1.00pp, vol USD 7.73M), Flávio 23.95% (up 0.10pp, vol USD 7.70M), Renan Santos 8.60% (down 0.15pp, vol USD 8.59M), Caiado 2.35% (up 0.45pp, vol USD 5.20M), Jair 1.05% (flat, vol USD 5.26M), Zema 0.75% (up 0.20pp, vol USD 4.57M), Michelle 0.45% (flat, vol USD 9.34M), Alckmin 0.35% (up 0.10pp, vol USD 4.94M), Camilo Santana 0.35% (down 0.05pp), Haddad 0.25% (flat, vol USD 6.38M), Tereza Cristina 0.20% (up 0.05pp), Tarcísio 0.15% (flat, vol USD 13.66M). Lula's gap over Flávio at +38.55pp, down 1.10pp against yesterday, and the widest gap in the AFOS series remains +39.80pp, from Jul 26. Sub-markets: first-round second place with Flávio 78.00% (flat), Renan 11.75% (down 0.40pp) and Haddad 1.20% (up 0.35pp); third place with Renan 61.50% (up 1.00pp), Caiado 25.50% (down 1.00pp), Flávio 6.25% (down 1.50pp) and Zema 4.50% (down 0.10pp). Senate by seats: ${G('PL', 'pl')} 71.00% (flat) and ${G('MDB', 'mdb')} 17.60% (up 0.35pp). Impeachment of an ${G('STF', 'stf')} justice at 2.85% (up 0.05pp). Total accumulated volume in the presidential book at USD 116.49M. Capture Jul 29, 21:47 UTC: guard REJECTED in the first round over 1.00pp in Renan's third place and APPROVED in the second with no divergences.`,
  'cards.inss.text1':
    `The fiscal agenda went a third day with no fresh development: Senate in recess, priority bills stalled and the promulgation of the ${G('pauta-bomba', 'pauta-bomba')} still held back by Davi Alcolumbre, with the Budget emerging as the next friction front between the Senate presidency and the government. The day's economic axis stayed external and changed in nature. The one-year extension of the US national emergency over Brazil, signed on Jul 28, stopped being a matter of legal form and became a matter of expectation: the Brazilian government began reading the extension as possible preparation for new sanctions (O Globo, Valor Econômico, Jul 29), and the ${G('PL', 'pl')} campaign leadership expects US measures against Alexandre de Moraes (O Globo). In parallel, US senators accused the Trump administration of promoting conspiracy theories about the Brazilian elections (G1, CBN). Domestically, the government extended Desenrola until Aug 31, a programme that has already renegotiated R$ 22 billion in debt.`,
  'cards.inss.text2':
    `The market did today the opposite of what it did yesterday, and the comparison between the two sessions is more informative than either one alone. Yesterday there was NO national polling and the favourite's price rose 1.00pp. Today the largest-sample national poll of the window came out and the favourite's price FELL 1.00pp, to 62.50%. The market's direction matches the polling's, which also narrowed the gap, but the sizes differ, 0.6pp in the poll against 1.10pp in the market, and the same session carried two other events capable of moving price: the fallout of the artificial-intelligence video at the ${G('STF', 'stf')} and the government's reading of the extension of the US emergency. The panel records the coincidence of direction and does not pick a cause, because it has no instrument to separate the contributions. The level caveat also holds: 62.50% is the same value as Jul 25 and Jul 27, and the top of the AFOS series marked 63.50% on Jul 26 and Jul 28, so what happened was the return of the point taken yesterday, not a drop in level.`,
  'cards.inss.text3':
    `The market on impeachment of an ${G('STF', 'stf')} justice rose 0.05pp to 2.85% (vol USD 83,000), which in practice describes a motionless book. And the stillness is the record that matters, because this was the week's densest day in institutional facts: Jair Bolsonaro's defence told Moraes he did not authorise the artificial-intelligence video shown at the ${G('PL', 'pl')} convention, ${G('TSE', 'tse')} justices began seeing abuse in the use of AI in campaigning, and the STF is preparing to act should the TSE not punish. The method caveat is worth more than the number: with USD 83,000 in accumulated volume against USD 116.49M in the presidential book, this market moves on very little money, and a 0.05pp change in it sustains no narrative in any direction. What real money did was keep treating the whole set as institutional friction, not as risk of a justice being removed.`,
  'cards.inss.text4':
    `On inflation, the shift the panel recorded yesterday undid itself in a single session, and that is the day's lesson about small books. The modal band went BACK to 5.00% to 5.49%, at 37.95%, while the 4.50% to 4.99% band fell from 39.25% to 34.70% and the 5.50% to 5.99% band collapsed from 12.20% to 3.55%. In other words, the centre of the distribution climbed back the step it had come down yesterday. The two caveats still matter more than the numbers: the whole book adds up to USD 80,000, and the inflation market is NOT covered by the double-reading guard, which watches only the five electoral books. Changing modal band two days in a row in a book that size is noise, and the honest record is that yesterday's reading did not hold.`,
  'cards.inss.impactoLula':
    `Fresh reading, and it is the largest sample and smallest margin in the window: ${G('AtlasIntel', 'atlasintel')}/Bloomberg of Jul 29 (field Jul 22 to 27, n=5,021, 1pp margin, BR-08602/2026) has approval of Lula's performance at 47.6% against 51.2% disapproval, with 1.2% who do not know. Against the institute's own Jul 1 round, approval RISES 1.7pp, from 45.9% to 47.6%, and disapproval FALLS 1.1pp, from 52.3% to 51.2%. Both moves sit outside the 1pp margin, which sets them apart from the rest of the round, where voting intention moved inside the noise. Even so, disapproval remains ahead by the same method, and the panel does not call that a swing. The contrast between institutes still stands: ${G('BTG/Nexus', 'nexus-btg')} of Jul 27 gave 47% x 49%, and ${G('Datafolha', 'datafolha')} of Jul 24 gave the reverse, 49% x 48%. Adding the week's three readings, Lula's approval sits in a narrow band between 47% and 49%. The earlier ones: PoderData Jul 22 at 46% x 47%, Indexa Jul 21 at 49% x 48%, Real Time Jul 21 at 46% x 50%, Genial/${G('Quaest', 'quaest')} Jul 15 at 48% x 47% and PoderData/Aya Jul 16 at 42% x 51%.`,
  'cards.inss.impactoGestao':
    `Fresh reading on government performance: ${G('AtlasIntel', 'atlasintel')} of Jul 29 brings 37.9% great or good, 12.7% fair and 49.3% bad or terrible. ${G('BTG/Nexus', 'nexus-btg')} of Jul 27 measured 36% x 20% x 43%, and ${G('Datafolha', 'datafolha')} of Jul 24 measured 32% x 28% x 38%. The three institutes disagree on the level and agree on the sign: the administration is rated worse than the person, and the distance between the two indicators persists. In AtlasIntel that distance is 9.7pp, with 47.6% approving his performance and 37.9% calling the administration great or good. On inflation, the modal band went back to 5.00% to 5.49%, at 37.95%, ahead of the 4.50% to 4.99% band, which fell to 34.70%, in a book that adds up to USD 80,000 and does not pass through the capture guard.`,
  'cards.inss.conclusao':
    `With 67 days to the election, Wednesday inverted Tuesday. Yesterday there was no national polling and the favourite's price rose 1.00pp; today the largest-sample poll of the window came out and the price fell 1.00pp, to 62.50%, returning the point taken the day before. The polling says stability: against the same institute's Jul 1 round, BOTH front-runners fall and the gap narrows 0.6pp, all inside the 1pp margin. Two findings remain from the day. The first is about Renan Santos: with 7.8% in the polling and 8.60% in price, the distance fell to 0.80pp, and in this round it narrowed on the POLLING side, which rose, and not on the price side, as had been happening since June. The second is about Caiado: the winner price rose 0.45pp on the same day the polling cut him in half, from 6% at ${G('BTG/Nexus', 'nexus-btg')} to 3.1%, and the third measurement on him landed on ${G('Datafolha', 'datafolha')}'s side. On the institutional axis, the week's densest day produced a 0.05pp move in a book of USD 83,000, which is next to nothing. And the state polls completed the picture of a split country by adding the largest electoral college: Flávio leads São Paulo in both rounds, Lula dominates the Northeast with 52% in Bahia and 54% in Ceará, and Minas Gerais remains a ${G('statistical tie', 'empate-tecnico')}.`,
  'cards.bancoMaster.text1':
    `Wednesday brought a promotion in status, not a fresh fact, and the difference matters to this panel's method. What the previous day recorded as an exclusive report by Valor Econômico, namely that André Mendonça authorised the ${G('Federal Police', 'pf')} to trace assets abroad belonging to Daniel Vorcaro and others involved, appeared on Wednesday in Estadão as well, described as authorised international cooperation. In other words, the reporting is no longer single-sourced. Yesterday the panel recorded the item attributed to one outlet and without an independent second source; today that caveat falls away.`,
  'cards.bancoMaster.text2':
    `On the legislative front, the news is still the absence of a decision, and it gained context. The writ of mandamus disputing the setting up of the ${G('Banco Master', 'banco-master')} inquiry commission has sat for four months in Kassio Nunes Marques's chambers, and the request by four senators to remove him as rapporteur was rejected by Edson Fachin as untimely, without examination of the merits. On Wednesday the same justice appeared on another front that concentrates decision-making power: the ${G('TSE', 'tse')} loosened rules for digital platforms in a new version of its regulation and concentrated decisions with Nunes Marques (Estadão). The panel records the two things side by side and asserts no relationship between them.`,
  'cards.bancoMaster.text3':
    `On price, the record is the usual one and it is worth repeating with the exact number: the market on impeachment of an ${G('STF', 'stf')} justice rose 0.05pp to 2.85%, in a book of USD 83,000. A change that size on that volume is practically stillness, and the panel attributes it to NOTHING. Wednesday carried the fallout of the artificial-intelligence video at the STF, the government's reading of the extension of the US emergency, Dino's decision on parliamentary amendments and three state polls. Choosing which of those events moved 0.05pp in a book of USD 83,000 would be inventing precision the data does not have.`,
  'cards.bancoMaster.conclusao':
    `The three fronts of the Master case remain on separate tracks and should not be added together: the criminal one, at the ${G('STF', 'stf')} under Mendonça as rapporteur, now with asset tracing abroad confirmed by two outlets; the property one, in the Rio courts, with a freeze of up to R$ 135 million already set; and the legislative one, dammed up for four months in a writ of mandamus that is not being judged. Wednesday's news is about the quality of the information, not about progress: the item that entered yesterday from a single source now has a second newsroom behind it. When the path of parliamentary investigation stalls in a decision that never comes, the cost does not show up in market price, it shows up in time, and today's 2.85%, in a book of USD 83,000, measures how little real money prices that axis.`,
  'cards.stf.toffoli':
    `Toffoli remains isolated at the ${G('STF', 'stf')} after the Master crisis, with no fresh individual act captured on Wednesday.`,
  'cards.stf.moraes':
    `The day's most active front, and it was born inside the ${G('PL', 'pl')} convention. After giving 48 hours on Jul 28 for Jair Bolsonaro's defence to explain the artificial-intelligence video carrying the former president's image and voice, citing risk of a fresh breach of his precautionary measures, he received the answer on Wednesday: the defence stated that Bolsonaro did NOT authorise the use of his own image and voice, and argued that he could not have done so because he is barred from receiving visitors (Folha de S.Paulo, O Globo, Estadão, G1, Jul 29). The same day, Flávio's campaign told the ${G('TSE', 'tse')} the video is legal and does not deceive voters, and the ${G('PT', 'pt')} petitioned the TSE over another AI piece, in which Flávio flies a fighter jet alongside Javier Milei. The panel records the positions and projects no outcome.`,
  'cards.stf.gilmar':
    `No individual act by Gilmar in the period. The recent joint vote stands, with Dino, Moraes and Zanin, which eased restrictions on ${G('penduricalhos', 'penduricalhos')}.`,
  'cards.stf.dino':
    `He acted again on Wednesday and on the budget axis: he ordered the government and Congress to specify the responsibility of members of parliament over amendments, gave Congress 10 days to present a proposal and signalled that a member can be punished for failing to oversee an amendment they earmarked (G1, Folha de S.Paulo, Jul 29). It is the same dispute over control of the budget still open at the Court, now with a deadline.`,
  'cards.stf.mendonca':
    `He remains rapporteur of the inquiry opened on Jul 23 into Vorcaro's transfers for the film about Jair Bolsonaro, and the authorisation for the ${G('Federal Police', 'pf')} to trace assets abroad belonging to the former banker and others involved, published as an exclusive by Valor Econômico on Jul 28, appeared on Wednesday in Estadão as well. The single-source caveat the panel recorded yesterday therefore falls away.`,
  'cards.stf.nexo':
    `Wednesday's link is the use of artificial intelligence in campaigning, and it cuts across the ${G('TSE', 'tse')} and the ${G('STF', 'stf')} at once. TSE justices began seeing abuse in the video carrying Bolsonaro's image and want to curb excessive use of AI in campaigns, while the STF is preparing to act should the TSE not punish (Estadão, O Globo). The same day, the TSE loosened rules for digital platforms in a new version of its regulation and concentrated decisions with Kassio Nunes Marques, the same justice who has held for four months the writ of mandamus on the ${G('Banco Master', 'banco-master')} inquiry commission. Externally, the extension of the US national emergency over Brazil, signed on Jul 28, came to be read by the government as possible preparation for new sanctions, and the ${G('PL', 'pl')} campaign leadership expects US measures against Moraes. And there is a counterpoint from the opposite direction: Lula publicly complained about corporatism among judges and prosecutors and argued for institutional reform (Folha de S.Paulo).`,
  'cards.stf.analise':
    `The market on impeachment of an ${G('STF', 'stf')} justice before 2027 ROSE 0.05pp to 2.85% (vol USD 83,000). The method caveat comes before the reading, and in this case it is practically the whole reading: 0.05pp in a book of USD 83,000, against USD 116.49M in the presidential book, is stillness, not repricing. With that said, the record that matters is the contrast. This was the week's densest day in institutional facts: the former president's defence told the STF he did not authorise the artificial-intelligence video shown at his own son's convention, which puts the campaign piece in contradiction with the father; ${G('TSE', 'tse')} justices came to see abuse and want to curb AI in campaigning; the STF is preparing to act should the TSE not punish; Dino set a deadline for Congress on the amendments axis; and the President of the Republic publicly complained about corporatism among judges and prosecutors. Faced with all of that, real money did not move. It is the same pattern this panel has recorded since June: the market treats institutional friction as friction, and not as probability of a justice being removed.`,
})
