/**
 * Mapas EN e ES do analysis-data.json para a publicação de 31/Jul 17:33.
 * EN usa ponto decimal e vírgula de milhar; ES mantém a convenção do pt.
 */
import { construir } from '../build-locale-json'

const G = (l: 'en' | 'es', id: string, txt: string) => `[${txt}](/${l}/glossary#${id})`
const T1_EN = G('en', 'primeiro-turno', 'first round')
const T1a_EN = G('en', 'primeiro-turno', 'first-round')
const T2_EN = G('en', 'segundo-turno', 'runoff')
const T1_ES = G('es', 'primeiro-turno', 'primera vuelta')
const T2_ES = G('es', 'segundo-turno', 'segunda vuelta')
const STF_EN = G('en', 'stf', 'STF')
const STF_ES = G('es', 'stf', 'STF')

const VOX_EN = 'Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, 2.15pp margin, 95% confidence, BR-01084/2026)'
const VOX_ES = 'Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, 95% de confianza, BR-01084/2026)'

const TRAVA_EN = 'The double-reading capture guard failed BOTH of today\'s rounds, which is why the range rule applies. What repeated goes in FIRM and what diverged goes in as a declared RANGE. One book diverged, the MDB in the Senate, which swung between 25.20% and 26.60% across three readings. The full presidential contract repeated across ALL FOUR readings, so the panel\'s headline figure is firm.'
const TRAVA_ES = 'La traba de doble lectura reprobó las DOS rondas de hoy, y por eso vale la regla de franja. Lo que se repitió entra FIRME y lo que divergió entra como FRANJA declarada. Divergió un solo book, el del MDB en el Senado, que osciló entre 25,20% y 26,60% en tres lecturas. El contrato presidencial entero se repitió en las CUATRO lecturas, así que el dato principal del panel está firme.'

const RENAN3_EN = `THREE consecutive institutes cut Renan Santos, and it is the sequence that matters, not the isolated number: AtlasIntel 7.8% on Jul 29, PoderData 4% on Jul 30 and Vox Brasil 3.0% on Jul 31. With the price at 8.15%, the distance between market and polling reaches 5.15pp, the widest in the window. On Jul 29 the panel recorded that same distance at 0.90pp and called it convergence. Three institutes later, it has quadrupled.`
const RENAN3_ES = `TRES institutos seguidos recortaron a Renan Santos, y es la secuencia lo que importa, no el número aislado: AtlasIntel 7,8% el 29 de julio, PoderData 4% el 30 de julio y Vox Brasil 3,0% el 31 de julio. Con el precio en 8,15%, la distancia entre mercado y encuesta llega a 5,15pp, la mayor del recorte. El 29 de julio el panel registró esa misma distancia en 0,90pp y la llamó convergencia. Tres institutos después, se cuadruplicó.`

const EN: Record<string, string> = {
  'cards.sentimento.text1': `With 65 days to the ${T1_EN}, the day's polling is ${VOX_EN}: Lula 40.5% x Flávio Bolsonaro 31.2% in the first round, with Ronaldo Caiado 5.5%, Romeu Zema 3.2% and Renan Santos 3.0%. In the ${T2_EN}, Lula 47.5% x Flávio 41.1%. That is a 9.3pp gap in the first round and 6.4pp in the runoff, and the runoff difference falls OUTSIDE the two margins added together, so this reading does not describe a statistical tie. Adding up the week, three houses measured the first-round gap at 9.1pp, 6pp and 9.3pp, which makes PoderData of Jul 30 the outlier, not Vox.`,

  'cards.sentimento.text2': `The day's crossing has a clear asymmetry: Lula did not move and the rest of the board moved a lot. His winner contract stayed at 63.50% for a second consecutive session, while Flávio rose 0.35pp, Renan Santos fell 0.30pp, Caiado fell 0.80pp, Camilo Santana rose 1.70pp and Alckmin rose 0.75pp. ${RENAN3_EN}`,

  'cards.sentimento.text3': 'In the market, Lula was FLAT at 63.50% (vol USD 7.77M) for a second day. Flávio rose 0.35pp, to 24.30% (vol USD 7.76M), and the gap narrowed from +39.55pp to +39.20pp, by his movement and not the front-runner\'s. Renan Santos fell 0.30pp, to 8.15% (vol USD 8.63M). Caiado fell 0.80pp, to 1.75% (vol USD 5.22M), giving back in one session the gain of two days. Camilo Santana rose to 2.20% (vol USD 4.16M) and Geraldo Alckmin to 1.10% (vol USD 4.98M). Jair Bolsonaro stayed at 0.95%, Tereza Cristina at 0.55%, Zema fell 0.10pp to 0.45% and Haddad rose 0.15pp to 0.30%. Tarcísio de Freitas remains at 0.15% (vol USD 13.68M), still the highest accumulated volume in the book. Total accumulated volume in the presidential market adds up to USD 117.03M.',

  'cards.sentimento.direita': `Flávio rose 0.35pp, to 24.30% (vol USD 7.76M), and narrowed the gap to +39.20pp. In the sub-markets the signal is crossed and worth recording: he FELL 1.00pp in the ${T1a_EN} second-place book, to 78.00% (vol USD 216,000), and FELL 0.60pp in the third-place book, to 5.65%. Rising in the chance of winning while giving ground in both placing books is an unusual combination, and the counterpart to the fall in the second-place book is Renan Santos rising 3.25pp in that same contract, which suggests internal reallocation rather than a fresh reading on the ${T2_EN}. In the polling, Vox has him at 31.2% in the first round and 41.1% in the runoff, with the 6.4pp difference falling outside the two margins added together. The day was busy on ticket-building: he said Tereza Cristina had accepted the running-mate slot, the senator said there had been a conversation and that the decision depends on the PL and the PP-União, and the PP leadership assesses that she accepted knowing the party would block it. Three versions of the same fact, and the panel records all three. The Aug 5 deadline for naming a running mate is less than a week away.`,

  'cards.sentimento.esquerda': `Lula was FLAT at 63.50% (vol USD 7.77M) for a second consecutive session, holding the value that ties the top of the AFOS series. The gap narrowed to +39.20pp by his opponent's movement. At Vox Brasil he has 40.5% in the ${T1_EN} and 47.5% in the ${T2_EN}, with a 6.4pp lead that falls outside the two margins added together. The institute records that, between May and July, Lula gained 7.3pp and Flávio lost 2.7pp within its own series, reversing a lead that had belonged to the senator, and the panel reproduces that as the institute's claim, because it is an internal comparison of theirs. Two names from his camp rose in the market on the same day: Camilo Santana to 2.20% and Geraldo Alckmin to 1.10%, on the day the PCdoB formalized support for the Lula-Alckmin ticket. The panel records the coincidence and does not assert cause. On Camilo, the series caveat is mandatory: 2.20% is NOT a peak, his series maximum is 4.10%, from May 3, and what happened was a recovery from the series MINIMUM, 0.50%, set the day before.`,

  'cards.sentimento.terceiraVia': `The chasing pack had its busiest day of the week. CAIADO gave it all back: he fell 0.80pp, to 1.75% (vol USD 5.22M), undoing in one session the gain of two days. The series caveat undoes any reading of collapse, because 1.75% sits inside his normal range since Jul 22 and the 2.55% of the previous day was the deviation. And he RISES 1.00pp in the ${T1a_EN} third-place book, to 26.50%, which makes the signal crossed. In the polling, Vox gives him 5.5%, his best national reading in the window, above PoderData's 5% and well above AtlasIntel's 3.1%. The divergence about him remains open at four levels within the same month. RENAN SANTOS fell 0.30pp in the winner book, to 8.15% (vol USD 8.63M), but ROSE 3.25pp in the first-round second-place book, to 9.35%, recovering two thirds of what he had lost the previous day. That is the contradiction of the day: the polling cuts him for a third consecutive institute and the money hands back part of the runoff chance it had removed 24 hours earlier. CAMILO SANTANA rose to 2.20% and ALCKMIN to 1.10%, both on the day of the PCdoB's formal support for the Lula-Alckmin ticket. ZEMA fell 0.10pp, to 0.45%, in a third consecutive session of decline, on a day when Marcelo Aro left his Senate ticket to run for the government of Minas Gerais, a move Zema publicly called betrayal.`,

  'cards.sentimento.polymarket': `Lula 63.50% (flat, vol USD 7.77M), Flávio 24.30% (up 0.35pp, vol USD 7.76M), Renan Santos 8.15% (down 0.30pp, vol USD 8.63M), Camilo Santana 2.20% (vol USD 4.16M), Caiado 1.75% (down 0.80pp, vol USD 5.22M), Alckmin 1.10% (vol USD 4.98M), Jair 0.95%, Tereza Cristina 0.55%, Zema 0.45% (down 0.10pp), Haddad 0.30% (up 0.15pp). Lula's gap over Flávio at +39.20pp, against +39.55pp on Jul 30. Total accumulated volume in the presidential market at USD 117.03M. Sub-markets: ${T1a_EN} second place with Flávio 78.00% (down 1.00pp, vol USD 216,000), Renan Santos 9.35% (UP 3.25pp, vol USD 1.09M) and Lula 8.25%; third place with Renan 62.00% (flat, vol USD 164,000), Caiado 26.50% (up 1.00pp, vol USD 37,000), Flávio 5.65% (down 0.60pp) and Zema 4.45%; impeachment of an ${STF_EN} justice FLAT at 3.10% (vol USD 83,000); Senate with PL 72.00% (up 6.50pp, vol USD 258,000) and MDB as a declared RANGE of 25.20% to 26.60%; inflation with the 5.00% to 5.49% band at 38.30% and the 4.50% to 4.99% band at 33.70% (up 1.20pp). ${TRAVA_EN} Live capture Jul 31, 20:33 UTC.`,

  'cards.inss.text1': 'The fiscal agenda saw no fresh development, with the Senate in recess and the Budget as the next front of friction between the Senate presidency and the government. The political day was about ticket-building, not economics: Flávio Bolsonaro said Tereza Cristina had accepted the running-mate slot, the senator said there had been a conversation and that the decision depends on the PL and the PP-União, and the PP leadership assesses that she accepted knowing the party would block it. In Minas Gerais, Marcelo Aro left Romeu Zema\'s Senate ticket to run for the state government, and Zema called the move betrayal. The PCdoB formalized support for the Lula-Alckmin ticket.',

  'cards.inss.text2': `The market's mark for the day was asymmetry: the front-runner did not move and almost everything else did. Lula stayed at 63.50% for a second session, while Flávio rose 0.35pp, Renan fell 0.30pp, Caiado fell 0.80pp and two names from the government's camp rose. ${RENAN3_EN}`,

  'cards.inss.text3': `The market on impeachment of an ${STF_EN} justice was FLAT at 3.10% (vol USD 83,000), with no variation across the four readings of today's capture guard. A day with no fresh institutional development on that axis, and the price followed the absence. With USD 83,000 in accumulated volume against USD 117.03M in the presidential market, this contract is only worth recording when it moves in a sustained way, and today it simply did not move.`,

  'cards.inss.text4': 'In the Senate, the PL ROSE 6.50pp and reached 72.00% (vol USD 258,000), and the MDB enters today as a declared RANGE, from 25.20% to 26.60%, because it was the only book the capture guard failed on both rounds. Added together, the two carry more than 97% of the probability assigned to just two parties, which by itself indicates a wide spread in that book. In inflation, the modal band is still 5.00% to 5.49%, at 38.30%, and the 4.50% to 4.99% band rose 1.20pp, to 33.70%, in a book of USD 81,000 that is NOT covered by the guard. A large move in a small book is a record, not a signal.',

  'cards.inss.impactoLula': 'Vox Brasil of Jul 31 did not publish approval and disapproval in this round, so the evaluation picture remains the one from Jul 30, with the week\'s two opposite readings still standing: PoderData measured personal approval falling to 43% against 49% disapproval, and AtlasIntel, 24 hours earlier, measured it rising 1.7pp, to 47.6% against 51.2%. The panel continues to show AtlasIntel on the gauge, by the criterion it published on Jul 29, the largest sample and the smallest margin in the window. The week\'s band remains between 43% and 49%.',

  'cards.inss.impactoGestao': 'The Vox Brasil round of Jul 31 did NOT publish a management rating, so the picture remains the one from Jul 30 and the week\'s two readings still stand, pointing in opposite directions. PoderData of Jul 30 brought 34% good or very good, 16% fair and 47% poor or terrible, with poor or terrible rising 10pp against the institute\'s Jul 22 round. AtlasIntel of Jul 29 measured 49.3% poor or terrible, BTG/Nexus of Jul 27 measured 43% and Datafolha of Jul 24 measured 38%. The four institutes still agree on what matters most: management is rated worse than the person, and the distance between the two indicators persists.',

  'cards.inss.conclusao': `With 65 days to the election, the day was one of asymmetry: the front-runner's price sat still at 63.50% for a second session and almost everything else on the board moved. The new polling, ${VOX_EN}, gives 40.5% x 31.2% in the ${T1_EN} and 47.5% x 41.1% in the ${T2_EN}, and that 6.4pp difference falls outside the two margins added together, unlike what PoderData measured the day before. Three houses in the same week gave 9.1pp, 6pp and 9.3pp for the first-round gap, and the panel records that the outlier is PoderData. ${RENAN3_EN} And the market contradicted itself in his case, handing back in the second-place book part of what it had taken 24 hours earlier. CAIADO gave back the whole two-day gain on the same day he received the best national polling of the window. None of these readings is attributed to a cause, because the day had no event that explains them.`,

  'cards.bancoMaster.text1': 'Friday brought no fresh act in the Master case, and the record is one of continuity with a locked verb. The Federal Police\'s consideration of asking Interpol to include Flávio Bolsonaro and Daniel Vorcaro in the silver notice, recorded on Jul 30, stands exactly as it was: the Federal Police is CONSIDERING, it has not filed, and Interpol has decided nothing. A silver notice locates assets and funds abroad and is NOT an arrest order, unlike a red notice. The stated target is to trace the R$ 61 million from Banco Master said to have financed the film about Jair Bolsonaro\'s career.',

  'cards.bancoMaster.text2': 'On the legislative front, the news is still the absence of a decision. The writ of mandamus disputing the installation of the Banco Master CPI has sat for more than four months in Kassio Nunes Marques\'s chambers, and the request by four senators to remove him from the case was rejected. With the Senate in recess and the August agenda still contested, there is no deadline in sight. The panel records the elapsed time because it is the fact: four months without a decision on installing a CPI is, in itself, a decision about installing it.',

  'cards.bancoMaster.text3': `On price, the record is one of stillness and it is worth a single line: the market on impeachment of an ${STF_EN} justice was FLAT at 3.10%, in a book of USD 83,000, with no variation across any of the four readings of today's capture guard. On a day with no fresh institutional development, a still price is the expected behaviour. The panel does not build a reading on the absence of movement in a contract that size.`,

  'cards.bancoMaster.conclusao': `The three fronts of the Master case remain on separate tracks and should not be added together: the criminal one, at the ${STF_EN} under André Mendonça, with overseas asset tracing authorized in a May decision and the Interpol question still under CONSIDERATION; the asset one, in the Rio courts, with freezes; and the legislative one, stalled for more than four months in Nunes Marques's chambers. None of them produced a new act on Friday. The only market touching the case, impeachment of an STF justice, sat still at 3.10%, in a book of USD 83,000 that cannot support a reading of risk repricing in any direction.`,

  'cards.stf.toffoli': `Toffoli remains isolated at the ${STF_EN} after the Master crisis, with no fresh individual act captured on Friday.`,
  'cards.stf.moraes': 'No new order from Moraes captured on Friday. The front he opened over the artificial-intelligence video shown at the PL convention remains live, with the 48-hour deadline already expired and the next decision pending.',
  'cards.stf.gilmar': 'No individual act from Gilmar in the period. The recent joint vote stands, with Dino, Moraes and Zanin, which reduced restrictions on penduricalhos.',
  'cards.stf.dino': 'No new act on Friday. Still running is the 10-day deadline set on Jul 29 for the government and Congress to specify the responsibility of members of Congress over earmarks.',
  'cards.stf.mendonca': 'He remains rapporteur of the inquiry opened on Jul 23 into Vorcaro\'s transfers for the film about Jair Bolsonaro. No new act on Friday. The Federal Police\'s consideration of asking Interpol to include Flávio Bolsonaro and Daniel Vorcaro in the silver notice, recorded on Jul 30, remains a CONSIDERATION: the Federal Police has not filed and Interpol has decided nothing.',
  'cards.stf.nexo': 'Friday\'s connecting thread moved off the judicial axis and onto the party axis, and it is about ticket composition. Flávio Bolsonaro said Tereza Cristina had accepted the running-mate slot on his ticket; the senator said there had been a conversation and that the decision depends on the PL and the PP-União; and the PP leadership assesses that she accepted precisely because she knew the party would block it. Three versions of the same fact, and the panel records all three without choosing. On the other side, the PCdoB formalized support for the Lula-Alckmin ticket, and in Minas Gerais Marcelo Aro left Zema\'s Senate ticket to run for the state government, a move Zema called betrayal. The Aug 5 deadline for naming running mates is less than a week away and is what organizes the coming days.',
  'cards.stf.analise': `The market on impeachment of an ${STF_EN} justice before 2027 was FLAT at 3.10% (vol USD 83,000), with no variation in any of the four readings of today's capture guard. It is the second consecutive session at the same value. The reading is short and it is this: a day with no fresh institutional development on that axis, and a still price. In a book of USD 83,000 against USD 117.03M in the presidential market, absence of movement in the face of absence of fact is the expected behaviour, and recording it costs one sentence.`,
}

const ES: Record<string, string> = {
  'cards.sentimento.text1': `A 65 días de la ${T1_ES}, la encuesta del día es ${VOX_ES}: Lula 40,5% x Flávio Bolsonaro 31,2% en la primera vuelta, con Ronaldo Caiado 5,5%, Romeu Zema 3,2% y Renan Santos 3,0%. En la ${T2_ES}, Lula 47,5% x Flávio 41,1%. Son 9,3pp de brecha en la primera vuelta y 6,4pp en la segunda, y esa diferencia de segunda vuelta queda FUERA de los dos márgenes sumados, así que esta lectura no describe empate técnico. Sumando la semana, tres casas midieron la brecha de la primera vuelta en 9,1pp, 6pp y 9,3pp, lo que coloca a PoderData del 30 de julio como la fuera de la curva, no a Vox.`,

  'cards.sentimento.text2': `El cruce del día tiene una asimetría clara: Lula no se movió y el resto del tablero se movió mucho. Su contrato de ganador quedó en 63,50% por segunda rueda consecutiva, mientras Flávio subió 0,35pp, Renan Santos cayó 0,30pp, Caiado cayó 0,80pp, Camilo Santana subió 1,70pp y Alckmin subió 0,75pp. ${RENAN3_ES}`,

  'cards.sentimento.text3': 'En el mercado, Lula quedó ESTABLE en 63,50% (vol USD 7,77M) por segundo día. Flávio subió 0,35pp, a 24,30% (vol USD 7,76M), y la brecha retrocedió de +39,55pp a +39,20pp, por movimiento suyo y no del favorito. Renan Santos cayó 0,30pp, a 8,15% (vol USD 8,63M). Caiado cayó 0,80pp, a 1,75% (vol USD 5,22M), devolviendo en una rueda el alza de dos días. Camilo Santana subió a 2,20% (vol USD 4,16M) y Geraldo Alckmin a 1,10% (vol USD 4,98M). Jair Bolsonaro quedó en 0,95%, Tereza Cristina en 0,55%, Zema cayó 0,10pp a 0,45% y Haddad subió 0,15pp a 0,30%. Tarcísio de Freitas sigue en 0,15% (vol USD 13,68M), todavía el mayor volumen acumulado del book. El volumen total acumulado en el presidencial suma USD 117,03M.',

  'cards.sentimento.direita': `Flávio subió 0,35pp, a 24,30% (vol USD 7,76M), y estrechó la brecha a +39,20pp. En los submercados la señal es cruzada y vale registrarla: CAYÓ 1,00pp en el book de segundo lugar de la ${T1_ES}, a 78,00% (vol USD 216.000), y CAYÓ 0,60pp en el de tercer lugar, a 5,65%. Subir en la chance de ganar y ceder en los dos de colocación es combinación inusual, y la contrapartida de la caída en el book de segundo lugar es el alza de 3,25pp de Renan Santos en ese mismo contrato, lo que sugiere reasignación interna y no lectura nueva sobre la ${T2_ES}. En la encuesta, Vox lo trae en 31,2% en la primera vuelta y 41,1% en la segunda, con la diferencia de 6,4pp quedando fuera de los dos márgenes sumados. El día fue movido en la formación de fórmula: él afirmó que Tereza Cristina aceptó ser vice, la senadora dijo que hubo conversación y que la decisión depende del PL y del PP-União, y la cúpula del PP evalúa que ella aceptó sabiendo que el partido lo bloquearía. Tres versiones del mismo hecho, y el panel registra las tres. El plazo del 5 de agosto para definir vice está a menos de una semana.`,

  'cards.sentimento.esquerda': `Lula quedó ESTABLE en 63,50% (vol USD 7,77M) por segunda rueda consecutiva, manteniendo el valor que iguala el techo de la serie del AFOS. La brecha retrocedió a +39,20pp por movimiento del adversario. En Vox Brasil tiene 40,5% en la ${T1_ES} y 47,5% en la ${T2_ES}, con una ventaja de 6,4pp que queda fuera de los dos márgenes sumados. El instituto registra que, entre mayo y julio, Lula creció 7,3pp y Flávio retrocedió 2,7pp en su propia serie, invirtiendo una ventaja que era del senador, y el panel lo reproduce como afirmación del instituto, porque es comparación interna suya. Dos nombres de su campo subieron en el mercado el mismo día: Camilo Santana a 2,20% y Geraldo Alckmin a 1,10%, el día en que el PCdoB formalizó apoyo a la fórmula Lula-Alckmin. El panel registra la coincidencia y no afirma causa. Sobre Camilo, la salvedad de serie es obligatoria: 2,20% NO es techo, su máximo de serie es 4,10%, del 3 de mayo, y lo que hubo fue recuperación del MÍNIMO de la serie, 0,50%, marcado la víspera.`,

  'cards.sentimento.terceiraVia': `El pelotón tuvo el día más movido de la semana. CAIADO devolvió todo: cayó 0,80pp, a 1,75% (vol USD 5,22M), deshaciendo en una rueda el alza de dos días. La salvedad de serie deshace cualquier lectura de colapso, porque 1,75% está dentro de su franja normal desde el 22 de julio y el 2,55% de la víspera era la desviación. Y SUBE 1,00pp en el book de tercer lugar de la ${T1_ES}, a 26,50%, lo que vuelve cruzada la señal. En la encuesta, Vox le da 5,5%, su mejor lectura nacional del recorte, por encima del 5% de PoderData y bastante por encima del 3,1% de AtlasIntel. La divergencia sobre él sigue abierta en cuatro niveles dentro del mismo mes. RENAN SANTOS cayó 0,30pp en el book de ganador, a 8,15% (vol USD 8,63M), pero SUBIÓ 3,25pp en el book de segundo lugar de la primera vuelta, a 9,35%, recuperando dos tercios de lo que había perdido la víspera. Esa es la contradicción del día: la encuesta lo recorta por tercer instituto consecutivo y el dinero le devuelve parte de la chance de segunda vuelta que le había quitado 24 horas antes. CAMILO SANTANA subió a 2,20% y ALCKMIN a 1,10%, ambos el día del apoyo formal del PCdoB a la fórmula Lula-Alckmin. ZEMA cayó 0,10pp, a 0,45%, en la tercera rueda consecutiva de baja, en un día en que Marcelo Aro dejó su fórmula al Senado para disputar el gobierno de Minas Gerais, movimiento que Zema llamó públicamente traición.`,

  'cards.sentimento.polymarket': `Lula 63,50% (estable, vol USD 7,77M), Flávio 24,30% (alza 0,35pp, vol USD 7,76M), Renan Santos 8,15% (caída 0,30pp, vol USD 8,63M), Camilo Santana 2,20% (vol USD 4,16M), Caiado 1,75% (caída 0,80pp, vol USD 5,22M), Alckmin 1,10% (vol USD 4,98M), Jair 0,95%, Tereza Cristina 0,55%, Zema 0,45% (caída 0,10pp), Haddad 0,30% (alza 0,15pp). Brecha de Lula sobre Flávio en +39,20pp, contra +39,55pp el 30 de julio. Volumen total acumulado en el presidencial en USD 117,03M. Submercados: segundo lugar de la ${T1_ES} con Flávio 78,00% (caída 1,00pp, vol USD 216.000), Renan Santos 9,35% (ALZA de 3,25pp, vol USD 1,09M) y Lula 8,25%; tercer lugar con Renan 62,00% (estable, vol USD 164.000), Caiado 26,50% (alza 1,00pp, vol USD 37.000), Flávio 5,65% (caída 0,60pp) y Zema 4,45%; impeachment de ministro del ${STF_ES} ESTABLE en 3,10% (vol USD 83.000); Senado con PL 72,00% (alza 6,50pp, vol USD 258.000) y MDB como FRANJA declarada de 25,20% a 26,60%; inflación con la franja de 5,00% a 5,49% en 38,30% y la de 4,50% a 4,99% en 33,70% (alza 1,20pp). ${TRAVA_ES} Captura en vivo 31 de julio, 20:33 UTC.`,

  'cards.inss.text1': 'La agenda fiscal no tuvo hecho nuevo, con el Senado en receso y el Presupuesto como próximo frente de fricción entre la presidencia del Senado y el gobierno. El día político fue de formación de fórmula, no de economía: Flávio Bolsonaro afirmó que Tereza Cristina aceptó ser vice, la senadora dijo que hubo conversación y que la decisión depende del PL y del PP-União, y la cúpula del PP evalúa que ella aceptó sabiendo que el partido lo bloquearía. En Minas Gerais, Marcelo Aro dejó la fórmula de Romeu Zema al Senado para disputar el gobierno estatal, y Zema llamó traición al movimiento. El PCdoB formalizó apoyo a la fórmula Lula-Alckmin.',

  'cards.inss.text2': `La marca del día en el mercado fue la asimetría: el favorito no se movió y casi todo el resto sí. Lula quedó en 63,50% por segunda rueda, mientras Flávio subió 0,35pp, Renan cayó 0,30pp, Caiado cayó 0,80pp y dos nombres del campo del gobierno subieron. ${RENAN3_ES}`,

  'cards.inss.text3': `El mercado de impeachment de ministro del ${STF_ES} quedó ESTABLE en 3,10% (vol USD 83.000), sin variación en las cuatro lecturas de la traba de captura de hoy. Un día sin hecho institucional nuevo en ese eje, y el precio acompañó la ausencia. Con USD 83.000 de volumen acumulado contra USD 117,03M del presidencial, este contrato solo es registrable cuando se mueve de forma sostenida, y hoy simplemente no se movió.`,

  'cards.inss.text4': 'En el Senado, el PL SUBIÓ 6,50pp y llegó a 72,00% (vol USD 258.000), y el MDB entra hoy como FRANJA declarada, de 25,20% a 26,60%, porque fue el único book que la traba de captura reprobó en las dos rondas. Sumados, los dos cargan más del 97% de la probabilidad asignada a apenas dos partidos, lo que por sí solo indica spread ancho en ese book. En inflación, la franja modal sigue en 5,00% a 5,49%, con 38,30%, y la de 4,50% a 4,99% subió 1,20pp, a 33,70%, en un book de USD 81.000 que NO está cubierto por la traba. Movimiento grande en book pequeño es registro, no señal.',

  'cards.inss.impactoLula': 'La Vox Brasil del 31 de julio no publicó aprobación y desaprobación en esta ronda, así que el cuadro de evaluación sigue siendo el del 30 de julio, con las dos lecturas opuestas de la semana todavía vigentes: PoderData midió la aprobación personal cayendo a 43% contra 49% de desaprobación, y AtlasIntel, 24 horas antes, la midió subiendo 1,7pp, a 47,6% contra 51,2%. El panel sigue exhibiendo AtlasIntel en el medidor, por el criterio que publicó el 29 de julio, la mayor muestra y el menor margen del recorte. La franja de la semana sigue entre 43% y 49%.',

  'cards.inss.impactoGestao': 'La ronda de Vox Brasil del 31 de julio NO publicó evaluación de gestión, así que el cuadro sigue siendo el del 30 de julio y las dos lecturas de la semana siguen vigentes, apuntando hacia lados opuestos. PoderData del 30 de julio trajo 34% de óptima o buena, 16% de regular y 47% de mala o pésima, con la mala o pésima subiendo 10pp contra la ronda del 22 de julio del instituto. AtlasIntel del 29 de julio medía 49,3% de mala o pésima, BTG/Nexus del 27 de julio medía 43% y Datafolha del 24 de julio medía 38%. Los cuatro institutos siguen coincidiendo en lo que más importa: la gestión es evaluada peor que la persona, y la distancia entre los dos indicadores persiste.',

  'cards.inss.conclusao': `A 65 días de la elección, el día fue de asimetría: el precio del favorito quedó quieto en 63,50% por segunda rueda y casi todo el resto del tablero se movió. La encuesta nueva, ${VOX_ES}, da 40,5% x 31,2% en la ${T1_ES} y 47,5% x 41,1% en la ${T2_ES}, y esa diferencia de 6,4pp queda fuera de los dos márgenes sumados, a diferencia de lo que midió PoderData la víspera. Tres casas en la misma semana dieron 9,1pp, 6pp y 9,3pp de brecha en la primera vuelta, y el panel registra que la fuera de la curva es PoderData. ${RENAN3_ES} Y el mercado se contradijo en su caso, devolviendo en el book de segundo lugar parte de lo que había quitado 24 horas antes. CAIADO devolvió toda el alza de dos días el mismo día en que recibió la mejor encuesta nacional del recorte. Ninguna de estas lecturas se atribuye a una causa, porque el día no tuvo evento que las explique.`,

  'cards.bancoMaster.text1': 'El viernes no trajo acto nuevo en el caso Master, y el registro es de continuidad con un verbo trabado. La evaluación de la Policía Federal sobre pedir a la Interpol la inclusión de Flávio Bolsonaro y de Daniel Vorcaro en la difusión plateada, registrada el 30 de julio, sigue exactamente como estaba: la Policía Federal EVALÚA, no pidió, y la Interpol no decidió nada. La difusión plateada localiza bienes y recursos en el exterior y NO es orden de detención, a diferencia de la difusión roja. El objetivo declarado es rastrear los R$ 61 millones del Banco Master que habrían financiado la película sobre la trayectoria de Jair Bolsonaro.',

  'cards.bancoMaster.text2': 'En el frente legislativo, la novedad sigue siendo la ausencia de decisión. El mandato de seguridad que discute la instalación de la CPI del Banco Master lleva más de cuatro meses en el despacho de Kassio Nunes Marques, y el pedido de cuatro senadores para apartarlo de la relatoría fue rechazado. Con el Senado en receso y la agenda de agosto todavía en disputa, no hay plazo a la vista. El panel registra el tiempo transcurrido porque es el hecho: cuatro meses sin decisión sobre la instalación de una CPI es, en sí, una decisión sobre su instalación.',

  'cards.bancoMaster.text3': `Sobre el precio, el registro es de inmovilidad y vale una sola línea: el mercado de impeachment de ministro del ${STF_ES} quedó ESTABLE en 3,10%, en un book de USD 83.000, sin variación en ninguna de las cuatro lecturas de la traba de captura de hoy. En un día sin hecho institucional nuevo, precio quieto es el comportamiento esperado. El panel no construye lectura sobre ausencia de movimiento en un contrato de ese tamaño.`,

  'cards.bancoMaster.conclusao': `Los tres frentes del caso Master siguen en carriles separados y no deben sumarse: el criminal, en el ${STF_ES} bajo relatoría de André Mendonça, con rastreo patrimonial autorizado en decisión de mayo y con la cuestión de la Interpol todavía en EVALUACIÓN; el patrimonial, en la Justicia de Rio, con bloqueos; y el legislativo, detenido hace más de cuatro meses en el despacho de Nunes Marques. Ninguno de ellos produjo acto nuevo este viernes. El único mercado que toca el caso, el de impeachment de ministro del STF, quedó quieto en 3,10%, en un book de USD 83.000 que no sostiene lectura de revaluación de riesgo en ninguna dirección.`,

  'cards.stf.toffoli': `Toffoli sigue aislado en el ${STF_ES} tras la crisis del Master, sin acto individual nuevo capturado este viernes.`,
  'cards.stf.moraes': 'Sin despacho nuevo de Moraes capturado este viernes. El frente que abrió por el video generado por inteligencia artificial exhibido en la convención del PL sigue vigente, con el plazo de 48 horas ya vencido y la decisión siguiente pendiente.',
  'cards.stf.gilmar': 'Sin acto individual de Gilmar en el período. Permanece el voto conjunto reciente, con Dino, Moraes y Zanin, que redujo restricciones a penduricalhos.',
  'cards.stf.dino': 'Sin acto nuevo este viernes. Sigue corriendo el plazo de 10 días dado el 29 de julio para que gobierno y Congreso especifiquen la responsabilidad de parlamentarios sobre enmiendas parlamentarias.',
  'cards.stf.mendonca': 'Sigue como relator de la investigación abierta el 23 de julio sobre las transferencias de Vorcaro para la película sobre Jair Bolsonaro. Sin acto nuevo este viernes. La evaluación de la Policía Federal sobre pedir a la Interpol la inclusión de Flávio Bolsonaro y de Daniel Vorcaro en la difusión plateada, registrada el 30 de julio, sigue siendo EVALUACIÓN: la Policía Federal no pidió y la Interpol no decidió nada.',
  'cards.stf.nexo': 'El nexo de este viernes salió del eje judicial y fue al eje partidario, y es de composición de fórmula. Flávio Bolsonaro afirmó que Tereza Cristina aceptó ser vice en su fórmula; la senadora dijo que hubo conversación y que la decisión depende del PL y del PP-União; y la cúpula del PP evalúa que ella aceptó justamente por saber que el partido lo bloquearía. Tres versiones del mismo hecho, y el panel registra las tres sin elegir. Del otro lado, el PCdoB formalizó apoyo a la fórmula Lula-Alckmin, y en Minas Gerais Marcelo Aro dejó la fórmula de Zema al Senado para disputar el gobierno estatal, movimiento que Zema llamó traición. El plazo del 5 de agosto para definir vices está a menos de una semana y es lo que organiza los próximos días.',
  'cards.stf.analise': `El mercado de impeachment de ministro del ${STF_ES} antes de 2027 quedó ESTABLE en 3,10% (vol USD 83.000), sin variación en ninguna de las cuatro lecturas de la traba de captura de hoy. Es la segunda rueda consecutiva en el mismo valor. La lectura es corta y es esta: un día sin hecho institucional nuevo en ese eje, y precio quieto. En un book de USD 83.000 contra USD 117,03M del presidencial, ausencia de movimiento ante ausencia de hecho es el comportamiento esperado, y registrarlo cuesta una frase.`,
}

construir('analysis-data', 'en', EN)
construir('analysis-data', 'es', ES)
