/**
 * Mapa ES de analysis-data.json — /atualizar-brz 02/Ago/2026.
 *
 * Convenções travadas: ES mantém vírgula decimal e ponto de milhar, igual ao
 * pt-BR. "pesquisa" é encuesta, nunca investigación; "estadual" é estatal;
 * "parado" é estancado, porque parado em ES é desempregado; o verbo de mercado
 * é descontar, nunca precificar.
 */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/es/glossary#${id})`

construir('analysis-data', 'es', {
  'cards.sentimento.text1':
    `A 63 días de la ${G('primera vuelta', 'primeiro-turno')} NO hubo encuesta nacional nueva, y ahora hay fecha para la próxima. La última sigue siendo la de Vox Brasil del 31/Jul (n=2.100, campo del 26 al 28/Jul, margen de 2,15pp, 95% de confianza, registro ${G('TSE', 'tse')} BR-01084/2026): Lula 40,5% frente a Flávio Bolsonaro 31,2% en la primera vuelta, con Caiado 5,5%, Zema 3,2% y Renan Santos 3,0%, y 47,5% frente a 41,1% en la ${G('segunda vuelta', 'segundo-turno')}. El barrido del TSE de hoy leyó 538 registros y no insertó ninguno nuevo, lo que confirma por el lado del registro lo que la prensa confirma por el lado de la publicación. CUATRO encuestas nacionales están en campo ahora mismo: dos de Nexus, una de ${G('Quaest', 'quaest')} y una de Ideia/Canal Meio, con publicación declarada entre el 3 y el 5/Ago. Fecha declarada en el registro no es publicación, y el panel las va a verificar una por una. Las encuestas del día son ESTATALES y por eso no entran en el panel nacional: la de ${G('Datafolha', 'datafolha')} en Pernambuco da Lula 57% frente a Flávio 22% en ese estado, y la de Genial/Quaest muestra a Lula por delante en cuatro estados y a Flávio en uno.`,
  'cards.sentimento.text2':
    `El cruce del día invierte el mecanismo de los dos anteriores. Lula quedó ESTANCADO en 65,50% y la brecha se ABRIÓ de +40,75pp a +40,95pp, pero se abrió porque FLÁVIO CAYÓ 0,20pp, y no porque el favorito subiera. En las dos jornadas anteriores el récord venía con el rival subiendo también; hoy es al revés, y la diferencia importa para la lectura. El techo de la serie quedó atrás y la ventana debe decirse entera: el máximo es 66,50%, del cierre del 1/Ago, y la brecha máxima es +41,80pp del mismo día, ambos por encima de lo que el panel muestra hoy. La serie del AFOS cubre del 14/Abr a hoy, 108 días, y fue verificada directamente contra la base de datos. RENAN SANTOS es el movimiento del día: SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M), INTERRUMPIENDO una racha de caídas que duraba nueve rondas, el mismo día en que Missão oficializó su candidatura. El panel registra la coincidencia de fechas y no afirma causa.`,
  'cards.sentimento.text3':
    `En el mercado, Lula quedó ESTANCADO en 65,50% (vol USD 7,90M) y Flávio CAYÓ 0,20pp hasta 24,55% (vol USD 7,82M), interrumpiendo seis jornadas sin caída, y es esa caída la que abre la brecha hasta +40,95pp. Renan Santos SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M). El pelotón se dividió, a diferencia de ayer, cuando encogió entero: Camilo Santana subió 0,20pp hasta 0,65% (vol USD 4,27M), Jair Bolsonaro subió 0,10pp hasta 0,65% y Haddad subió 0,05pp hasta 0,30% (vol USD 6,63M), mientras Caiado cayó 0,20pp hasta 1,15% (vol USD 5,27M), Zema cayó 0,10pp hasta 0,25% (vol USD 4,64M), y Michelle y Tereza Cristina cayeron 0,10pp cada una, ambas hasta 0,15%. Alckmin quedó estancado en 0,35% y Tarcísio de Freitas sigue en 0,05%, con USD 13,70M de volumen acumulado, el mayor del libro. El volumen total acumulado en el presidencial suma USD 118,11M, frente a USD 117,52M ayer.`,
  'cards.sentimento.direita':
    `Flávio CAYÓ 0,20pp hasta 24,55% (vol USD 7,82M), interrumpiendo seis jornadas sin caída, y fue su caída la que ABRIÓ la brecha hasta +40,95pp, porque Lula quedó quieto. En los submercados la señal va al revés, y el panel no elige entre las dos: SUBE 1,00pp en el segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, hasta 80,50% (vol USD 217 mil), su mayor marca en ese contrato en el seguimiento del panel, y queda prácticamente quieto en el tercer lugar, en 4,90%. Cede en la probabilidad de ganar y sube en la de llegar a la ${G('segunda vuelta', 'segundo-turno')}, en la misma jornada. En el armado de la fórmula, sigue SIN candidato a vice a tres días del plazo del 5/Ago. Valor Econômico registra que él y Lula llegaron al tramo final de las convenciones sin ampliar alianzas, con el ${G('Centrão', 'centrao')} todavía neutral, y la convención nacional de ${G('Republicanos', 'republicanos')}, que decide la alianza presidencial, es el 4/Ago. En la convención del ${G('PL', 'pl')} en Santa Catarina pidió votos antes del plazo legal, que solo se abre el 16/Ago, y usó un nuevo video con Jair Bolsonaro después de que Moraes lo cuestionara por el anterior, generado con inteligencia artificial. Carlos Bolsonaro criticó al ${G('STF', 'stf')} desde el mismo palco.`,
  'cards.sentimento.esquerda':
    `Lula quedó ESTANCADO en 65,50% (vol USD 7,90M) el día en que el ${G('PT', 'pt')} oficializó su candidatura. La brecha se ABRIÓ hasta +40,95pp por caída del rival, y no por alza propia, lo que cambia el mecanismo respecto de las dos jornadas anteriores. El precio de hoy está 1,00pp POR DEBAJO del techo de la serie, que es 66,50%, del cierre del 1/Ago. La convención nacional del PT, en São Paulo, oficializó la fórmula con Alckmin como vice y reunió a siete partidos, en la octava vez que Lula es candidato a la presidencia y en la búsqueda del cuarto mandato. Dijo que no quiere ser el presidente del Bolsa Família y prometió disputar las enmiendas con el Congreso, y Tebet llamó golpista a Flávio desde el palco. También pidió votos antes del plazo legal, que se abre el 16/Ago, y Flávio hizo lo mismo el mismo día. En su campo el mercado subió: Camilo Santana ganó 0,20pp hasta 0,65%, y Haddad ganó 0,05pp hasta 0,30%. Alckmin quedó estancado en 0,35%. En el eje judicial, las dos investigaciones sobre Lulinha agudizaron la tensión entre Mendonça y la Policía Federal, su abogado acusa a sectores de la ${G('PF', 'pf')} de intentar interferir en la elección, y Roberta Luchsinger pidió que se investigue una filtración de conversaciones. Una investigación no es una condena.`,
  'cards.sentimento.terceiraVia':
    `El pelotón se DIVIDIÓ, y esa es la diferencia respecto de ayer, cuando encogió entero. RENAN SANTOS es el movimiento del día: SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M), interrumpiendo nueve rondas de caída, y subió también en los dos libros de colocación, 0,20pp en el segundo lugar, hasta 8,75%, y 2,00pp en el tercer lugar, hasta 63,50% (vol USD 168 mil), donde es favorito aislado. El giro no deshace el arco, y la ventana debe decirse: venía de 12,00% el 23/Jul y tocó 7,10% en el cierre del 1/Ago, y NO es mínimo de serie, porque el mínimo es 5,30%, del 26/Abr, y el máximo es 17,90%, del 9/Jun. Con el precio subiendo y la encuesta quieta en 3,0%, la distancia entre mercado y encuesta VOLVIÓ A ABRIRSE, de 4,60pp a 4,95pp. CAIADO tocó el piso de la serie dentro del propio día: la recolección de las 11:30 UTC registró 0,90%, que iguala el menor valor desde el 14/Abr, ya registrado entre el 5 y el 9/Jul, y la captura trabada de las 19:42 UTC trae 1,15%, con caída de 0,20pp en la cuarta jornada seguida de baja. El panel publica la captura trabada y registra el piso intradiario en vez de elegir uno de los dos. En el tercer lugar SUBE 2,00pp, hasta 24,50%, recuperando la caída de la víspera. CAMILO SANTANA subió 0,20pp hasta 0,65%, y aquí cabe una salvedad de recolección: la serie del AFOS no tiene punto del 1/Ago para ese nombre, así que el panel no repite la frase de mínimo de serie que publicó ayer. ZEMA cayó 0,10pp hasta 0,25%, y su serie no tiene punto después del 30/Jul.`,
  'cards.sentimento.polymarket':
    `Lula 65,50% (estancado, vol USD 7,90M), Flávio 24,55% (baja de 0,20pp, vol USD 7,82M), Renan Santos 7,95% (alza de 0,35pp, vol USD 8,82M), Caiado 1,15% (baja de 0,20pp, vol USD 5,27M), Jair 0,65% (alza de 0,10pp), Camilo Santana 0,65% (alza de 0,20pp, vol USD 4,27M), Alckmin 0,35% (estancado), Haddad 0,30% (alza de 0,05pp), Zema 0,25% (baja de 0,10pp), Michelle 0,15% (baja de 0,10pp), Tereza Cristina 0,15% (baja de 0,10pp), Tarcísio 0,05% (estancado, vol USD 13,70M). Brecha de Lula sobre Flávio en +40,95pp, frente a +40,75pp en la captura publicada el 1/Ago, y POR DEBAJO del máximo de la serie, que es +41,80pp en el cierre del 1/Ago. Volumen total acumulado en el presidencial en USD 118,11M. Submercados: segundo lugar de la ${G('primera vuelta', 'primeiro-turno')} con Flávio en 80,50% (alza de 1,00pp, vol USD 217 mil), Renan Santos en 8,75% (alza de 0,20pp, vol USD 1,09M) y Lula en 7,55% (baja de 0,85pp); tercer lugar con Renan en 63,50% (alza de 2,00pp, vol USD 168 mil), Caiado en 24,50% (alza de 2,00pp, vol USD 37 mil), Flávio en 4,90% y Zema en 4,60% (estancado); destitución de un ministro del ${G('STF', 'stf')} ESTANCADA en 3,10% (vol USD 83 mil) por cuarta jornada; Senado con ${G('PL', 'pl')} ESTANCADO en 72,50% (vol USD 259 mil) y ${G('MDB', 'mdb')} en 18,75%, con baja de 2,60pp en un libro de USD 8 mil; inflación con la banda de 5,00% a 5,49% en 34,75% y la de 4,50% a 4,99% en 27,00%. La traba de doble lectura APROBÓ la ronda, sin ningún motivo de bloqueo, con las dos lecturas dentro de 0,20pp en todos los libros. Todos los precios entran firmes, sin rango declarado. Captura en vivo del 2/Ago a las 19:42 UTC.`,
  'cards.inss.text1':
    `La agenda fiscal no tuvo novedad este domingo, y el Congreso vuelve esta semana, junto con el regreso del ${G('STF', 'stf')} y el plazo final de las fórmulas el 5/Ago. El día político fue de CONVENCIÓN NACIONAL, de los dos lados. El ${G('PT', 'pt')} oficializó a Lula en São Paulo, con Alckmin como vice y siete partidos en la alianza, en su octava candidatura a la presidencia. Missão oficializó a Renan Santos, también en São Paulo. Y Flávio Bolsonaro estuvo en la convención del ${G('PL', 'pl')} en Santa Catarina. Lula y Flávio pidieron votos antes del plazo legal, que solo se abre el 16/Ago, y el registro es de los dos, no de uno. Valor Econômico resume el saldo del ciclo de convenciones: los dos llegaron al tramo final sin ampliar alianzas, y el ${G('Centrão', 'centrao')} sigue neutral.`,
  'cards.inss.text2':
    `El mercado invirtió el mecanismo de las dos jornadas anteriores. Lula quedó ESTANCADO en 65,50% y la brecha se ABRIÓ hasta +40,95pp, pero se abrió por caída de Flávio, que cedió 0,20pp y fue a 24,55%, interrumpiendo seis jornadas sin caída. En los dos días anteriores la brecha se abría con el rival subiendo también, y hoy es al revés. El techo de la serie quedó atrás: el máximo es 66,50%, del cierre del 1/Ago, y el precio de hoy está 1,00pp por debajo. RENAN SANTOS SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M), interrumpiendo nueve rondas de caída, el mismo día de la convención que lo oficializó. El pelotón se dividió: Camilo Santana y Jair Bolsonaro subieron, Caiado y Zema cayeron. La asimetría del día es la misma de la víspera: nada de esto tuvo encuesta nacional para acompañarlo, y la última sigue siendo la de Vox Brasil del 31/Jul.`,
  'cards.inss.text3':
    `El mercado de destitución de un ministro del ${G('STF', 'stf')} quedó ESTANCADO en 3,10% (vol USD 83 mil), sin variación en las dos lecturas de la traba de captura de hoy, en la cuarta jornada seguida en el mismo valor. El eje judicial produjo hechos en el período, con las investigaciones sobre Lulinha agudizando la tensión entre Mendonça y la Policía Federal, pero nada de eso apunta a un integrante de la Corte, que es el objeto de este contrato. Con USD 83 mil de volumen acumulado frente a USD 118,11M del presidencial, este contrato solo es registrable cuando se mueve de forma sostenida.`,
  'cards.inss.text4':
    `En el Senado, el ${G('PL', 'pl')} quedó ESTANCADO en 72,50% (vol USD 259 mil), y el ${G('MDB', 'mdb')} CAYÓ 2,60pp hasta 18,75%, en un libro de USD 8 mil que no sostiene una lectura de reprecio. Sumados, los dos superan el 91% de probabilidad atribuida a apenas dos partidos, lo que por sí solo indica spread amplio. En la inflación, la banda modal sigue siendo la de 5,00% a 5,49%, que CAYÓ 3,45pp hasta 34,75%, y la de 4,50% a 4,99% CAYÓ 7,00pp hasta 27,00%, en un libro que NO está cubierto por la traba. Y hay una salvedad de coherencia que el panel mide y publica en vez de esconder: las diez bandas suman 94,15%, por debajo del piso de 95% que el AFOS usa para tratar una distribución como probabilidad legible. Los niveles entran como registro de recolección, no como lectura de expectativa.`,
  'cards.inss.impactoLula':
    `La de Vox Brasil del 31/Jul no publicó aprobación ni desaprobación, y ninguna nacional fue publicada desde entonces, así que el cuadro de evaluación sigue siendo el del 30/Jul, con las dos lecturas opuestas de la semana todavía en pie: PoderData midió la aprobación personal cayendo a 43% frente a 49% de desaprobación, y AtlasIntel, 24 horas antes, la midió subiendo 1,7pp, hasta 47,6% frente a 51,2%. El panel sigue exhibiendo a AtlasIntel en el medidor por el criterio publicado el 29/Jul, la mayor muestra y el menor margen del recorte. El rango de la semana sigue entre 43% y 49%. Cuatro nacionales están en campo y deberían publicar entre el 3 y el 5/Ago, lo que debería rehacer este cuadro dentro de la semana.`,
  'cards.inss.impactoGestao':
    `Sin ronda nacional nueva, el cuadro de gestión sigue siendo el del 30/Jul y las dos lecturas de la semana continúan apuntando a lados opuestos. PoderData del 30/Jul trajo 34% de óptimo o bueno, 16% de regular y 47% de malo o pésimo, con el malo o pésimo subiendo 10pp frente a la ronda del 22/Jul del instituto. AtlasIntel del 29/Jul medía 49,3% de malo o pésimo, ${G('BTG/Nexus', 'nexus-btg')} del 27/Jul medía 43% y ${G('Datafolha', 'datafolha')} del 24/Jul medía 38%. Los cuatro institutos siguen coincidiendo en lo que más importa: la gestión se evalúa peor que la persona, y la distancia entre los dos indicadores persiste.`,
  'cards.inss.conclusao':
    `A 63 días de la elección, el día fue de convención nacional de los dos lados y de inversión de mecanismo en el mercado. El favorito quedó quieto en 65,50% y la brecha se abrió hasta +40,95pp porque el rival cayó, al contrario de las dos jornadas anteriores, en que la brecha se abría con los dos subiendo. El techo de la serie quedó atrás, y es de ayer: 66,50%. El movimiento del día fue de Renan Santos, que subió 0,35pp e interrumpió nueve rondas de caída el mismo día de la convención que lo oficializó, y el panel registra la coincidencia de fechas sin afirmar causa. En la política, el ${G('PT', 'pt')} oficializó a Lula con Alckmin en São Paulo, Missão oficializó a Renan, Flávio estuvo en la convención del ${G('PL', 'pl')} en Santa Catarina, y los dos principales pidieron votos antes del plazo legal. Flávio y Zema siguen sin vice a tres días del plazo. Ninguna de estas lecturas se atribuye a una causa: el panel registra la coincidencia de fechas y se detiene ahí.`,
  'cards.bancoMaster.text1':
    `Este domingo el caso ${G('Banco Master', 'banco-master')} no tuvo acto judicial nuevo, y el registro es de lo que la investigación hizo salir a la luz. La Policía Federal apunta al interés de Daniel Vorcaro en enmiendas presentadas en el Senado, dentro de un proyecto que regulaba el mercado de carbono. Es material de investigación, no una decisión, y el panel lo registra como tal. La representación del partido Novo contra el senador Jaques Wagner sigue en el Consejo de Ética del Senado, presentada el 1/Ago, sostenida por el informe de la ${G('PF', 'pf')} que se hizo público cuando André Mendonça levantó el secreto de parte de la investigación: 74 llamadas entre el senador y Augusto Lima, exsocio del banco, entre noviembre de 2023 y mayo de 2025, sumando más de cinco horas y treinta minutos de conversación en 555 días.`,
  'cards.bancoMaster.text2':
    `El hecho político del caso hoy es que su contención electoral falló. El ${G('PT', 'pt')} admitió que el acuerdo para dejar el caso Master fuera de la elección en Bahía SE ROMPIÓ. En la convención estatal del 1/Ago, Lula pidió votos para Jaques Wagner, llamó al aliado líder del gobierno y dijo que el Senado está en un bajo nivel. Dentro de la propia convención hubo disonancia registrada: Geraldo Júnior fue el único que no mencionó a Wagner en su discurso. El panel registra los hechos lado a lado y no transforma uno en el otro: una representación ante el Consejo de Ética y una oficialización en convención son procesos distintos, y ninguno decide al otro. Wagner dijo públicamente que va a probar su inocencia. Nada de esto es una condena.`,
  'cards.bancoMaster.text3':
    `En el frente legislativo no hubo novedad, y la ausencia sigue siendo el hecho: el recurso sobre la instalación de la comisión investigadora del Banco Master lleva más de cuatro meses en el despacho de Kassio Nunes Marques. El Congreso vuelve esta semana, lo que recoloca ese frente en movimiento posible. Sobre el precio, el registro es de inmovilidad: el mercado de destitución de un ministro del ${G('STF', 'stf')} quedó ESTANCADO en 3,10%, en un libro de USD 83 mil, en la cuarta jornada seguida en el mismo valor. Vale repetir la salvedad de ayer, porque sigue valiendo: ese contrato NO descuenta el caso Wagner, que corre contra un senador y no contra un ministro.`,
  'cards.bancoMaster.conclusao':
    `Los frentes del caso ${G('Banco Master', 'banco-master')} siguen en carriles separados. El criminal, en el ${G('STF', 'stf')} bajo André Mendonça, tuvo su mayor movimiento el 31/Jul, con el secreto levantado, y este domingo lo que apareció fue contenido de investigación, con la Policía Federal apuntando al interés de Vorcaro en enmiendas del Senado. El patrimonial sigue en la justicia de Río, con bloqueos. El legislativo sigue detenido hace más de cuatro meses, y el Congreso vuelve esta semana. El partidario está en el Consejo de Ética. Y el frente que comparte el mismo relator, pero no es del Master, quedó más tenso: las dos investigaciones sobre Lulinha agudizaron la fricción entre Mendonça y la Policía Federal, su abogado acusa a sectores de la ${G('PF', 'pf')} de intentar interferir en la elección, y Roberta Luchsinger pidió que se investigue una supuesta filtración de conversaciones. El panel registra que el mismo ministro concentra las investigaciones de mayor impacto en vísperas de la elección y no extrae de eso una lectura de intención.`,
  'cards.stf.toffoli':
    `Toffoli sigue aislado en el ${G('STF', 'stf')} tras la crisis del Master, sin acto individual nuevo capturado este domingo.`,
  'cards.stf.moraes':
    `Cuestionó a Flávio Bolsonaro por el video generado con inteligencia artificial exhibido en la convención del ${G('PL', 'pl')}, y la respuesta fue un video NUEVO con Jair Bolsonaro, usado en la convención del PL en Santa Catarina. En el plano personal de la familia, autorizó a la cuñada a cuidar de Jair Bolsonaro mientras Michelle pasaba por exámenes en Brasilia.`,
  'cards.stf.dino':
    `Sin acto nuevo este domingo. Sigue corriendo el plazo de 10 días dado el 29/Jul para que el gobierno y el Congreso especifiquen la responsabilidad de los parlamentarios sobre las enmiendas.`,
  'cards.stf.mendonca':
    `Concentra las investigaciones de mayor impacto del período, y ahora con fricción explícita. Sigue como relator de la investigación abierta el 23/Jul sobre las transferencias de Vorcaro para la película sobre Jair Bolsonaro. El 30/Jul autorizó la primera investigación sobre tráfico de influencias de Fábio Luís Lula da Silva, conocido como Lulinha, ante el Ministerio de Salud, y el 31/Jul una SEGUNDA, sobre su actuación ante Dataprev, además de levantar el secreto de parte de la investigación sobre Jaques Wagner. Este domingo no hubo acto nuevo, pero la prensa registra que las investigaciones sobre Lulinha elevaron la tensión entre él y la Policía Federal.`,
  'cards.stf.nexo':
    `El nexo de este domingo es de CONVENCIÓN NACIONAL, y el eje judicial entra por la fricción institucional. El ${G('PT', 'pt')} oficializó a Lula con Alckmin en São Paulo, reuniendo a siete partidos, y Missão oficializó a Renan Santos, también en São Paulo. Flávio Bolsonaro estuvo en la convención del ${G('PL', 'pl')} en Santa Catarina, donde él y Carlos Bolsonaro criticaron al ${G('STF', 'stf')}, y usó un nuevo video con Jair después de ser cuestionado por Moraes por el anterior, generado con inteligencia artificial. Lula y Flávio pidieron votos antes del plazo legal, que se abre el 16/Ago. Flávio y Zema siguen sin vice a tres días del plazo del 5/Ago, y la convención nacional de ${G('Republicanos', 'republicanos')}, que trata la alianza presidencial, es el 4/Ago. En el eje judicial, lo que se extiende desde el 31/Jul es la tensión entre Mendonça y la Policía Federal en torno a las investigaciones sobre Lulinha, con su abogado acusando a sectores de la ${G('PF', 'pf')} de intentar interferir en la elección.`,
  'cards.stf.analise':
    `El mercado de destitución de un ministro del ${G('STF', 'stf')} antes de 2027 quedó ESTANCADO en 3,10% (vol USD 83 mil), sin variación en las dos lecturas de la traba de captura de hoy. Es la cuarta jornada seguida en el mismo valor. El eje judicial produjo hechos en el período, con dos investigaciones sobre Lulinha, el secreto levantado sobre un senador y fricción abierta entre el relator y la Policía Federal, pero ninguno de ellos apunta a la remoción de un integrante de la Corte, que es el objeto de este contrato. En un libro de USD 83 mil frente a USD 118,11M del presidencial, un precio quieto ante un hecho que no toca el objeto es el comportamiento esperado.`,
})
