/** Tradução do /atualizar-brz de 01/Ago 13:49 — analysis-criteriosa. */
import { construir } from '../build-locale-json'

const TRAVA_EN = 'The double-reading capture guard failed the first round, with Renan Santos in transit from 7.15% to 7.60% and Caiado\'s third-place book swinging between 22.00% and 22.50%, and APPROVED the second. All prices go in firm, with no declared range. Live capture Aug 1, 16:49 UTC.'
const TRAVA_ES = 'La traba de doble lectura reprobó la primera ronda, con Renan Santos en tránsito de 7,15% a 7,60% y el tercer lugar de Caiado oscilando entre 22,00% y 22,50%, y APROBÓ la segunda. Todos los precios entran firmes, sin franja declarada. Captura en vivo 1 de agosto, 16:49 UTC.'

const TARCISIO_EN = 'Tarcísio de Freitas appears at 0.05% in the presidential contract, with USD 13.69M of accumulated volume, the largest in the book. The panel records the level and does not claim it is his lowest: the AFOS series holds only three days for that name, between Apr 28 and May 14, and does not support a superlative.'
const TARCISIO_ES = 'Tarcísio de Freitas aparece en 0,05% en el contrato presidencial, con USD 13,69M de volumen acumulado, el mayor del book. El panel registra el nivel y no afirma que sea el menor suyo: la serie del AFOS tiene apenas tres días para ese nombre, entre el 28 de abril y el 14 de mayo, y no sostiene superlativo.'

const RENAN_EN = 'RENAN SANTOS fell 0.55pp and went to 7.60% (vol USD 8.72M), his lowest value since May 14. The fall is one of sequence, not of a single session: on Jul 23 he stood at 12.00% and has since given ground in eight of nine rounds, adding up to 4.40pp. Before May 14 the series records lower values, which is why the window is declared and the panel does not write "of the series".'
const RENAN_ES = 'RENAN SANTOS cayó 0,55pp y fue a 7,60% (vol USD 8,72M), su menor valor desde el 14 de mayo. La caída es de secuencia, no de una rueda: el 23 de julio estaba en 12,00% y desde entonces cedió en ocho de nueve rondas, sumando 4,40pp. Antes del 14 de mayo la serie registra valores menores, por eso la ventana se declara y el panel no escribe "de la serie".'

const PORTAS_EN = 'On ticket-building, Flávio Bolsonaro remains without a running mate four days from the Aug 5 deadline. Tereza Cristina publicly regretted the end of the arrangement after the PP\'s refusal, saying that what happened is settled, and he thanked her and said he is negotiating with other parties. On Saturday, Republicanos made official Tarcísio de Freitas\'s bid for RE-ELECTION as governor of São Paulo, with Flávio present on the platform, but Tarcísio himself kept the focus on the state and avoided nationalizing his speech. These are distinct things and the panel does not merge them: Saturday\'s convention is a state one and deals with the São Paulo governorship; the party\'s national convention, which decides the presidential alliance, is set for Aug 4.'
const PORTAS_ES = 'En la formación de fórmula, Flávio Bolsonaro sigue sin vice a cuatro días del plazo del 5 de agosto. Tereza Cristina lamentó públicamente el fin de la articulación tras la negativa del PP, diciendo que lo que fue está puesto, y él agradeció y afirmó que negocia con otros partidos. Este sábado el Republicanos oficializó la candidatura de Tarcísio de Freitas a la REELECCIÓN en el gobierno de São Paulo, con Flávio presente en el palco, pero el propio Tarcísio mantuvo el foco en el estado y evitó nacionalizar el discurso. Son cosas distintas y el panel no las junta: la convención de hoy es estatal y trata del gobierno de São Paulo; la convención nacional del partido, que decide sobre alianza presidencial, está marcada para el 4 de agosto.'

const en = {
  subtitle: `UPDATE Aug 1, 13:49 BRT, 64 days to the [first round](/en/glossary#primeiro-turno). A SECOND CONSECUTIVE DAY OF A NEW TOP. Lula rose 1.00pp to 65.50% (vol USD 7.82M), the maximum of the AFOS series, which runs from Apr 14 to today. Flávio Bolsonaro rose 0.40pp, to 24.75% (vol USD 7.79M), and even so the gap WIDENED from +40.15pp to +40.75pp, also the maximum of the series that holds both names, which begins on May 3. Both records were broken on Jul 31 and broken again today, and on both occasions with the opponent rising alongside: the move is demand for the front-runner and not deterioration on the other side. ${RENAN_EN} THE WHOLE CHASING PACK SHRANK: Caiado fell 0.25pp, to 1.35% (vol USD 5.24M), Jair Bolsonaro fell 0.30pp, to 0.55%, Alckmin fell 0.10pp, to 0.35%, and CAMILO SANTANA gave back everything he had gained the day before, falling 0.90pp to 0.45% (vol USD 4.19M), which is his lowest value in the AFOS series, below the 0.50% of Jul 30. ${TARCISIO_EN} IN THE PLACING BOOKS, Flávio rose 1.00pp in first-round second place, to 79.50%, while Renan gave up 0.80pp, to 8.55%, and in third place Caiado COLLAPSED 5.00pp, from 27.50% to 22.50% (vol USD 37,000), undoing in one session the gain the panel recorded yesterday. ${PORTAS_EN} ON THE JUDICIAL AXIS, André Mendonça authorized on the afternoon of Jul 31 a SECOND inquiry into Fábio Luís Lula da Silva, known as Lulinha, this time over his dealings with Dataprev, after the first one, over the Health Ministry, authorized on Jul 30. The national poll remains Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, margin of 2.15pp, 95% confidence, BR-01084/2026), with no new national round since then. Total accumulated volume in the presidential market at USD 117.52M. ${TRAVA_EN}`,
  'candidates[0].header': 'Polymarket 65.50% (up 1.00pp, vol USD 7.82M accumulated), 64 days to the election, at the MAXIMUM of the AFOS series for a second consecutive day. The gap over Flávio widens to +40.75pp, also a series maximum. No new national poll: the latest remains Vox Brasil of Jul 31 (n=2,100), with 40.5% in the [first round](/en/glossary#primeiro-turno) and 47.5% x 41.1% in the [runoff](/en/glossary#segundo-turno).',
  'candidates[0].fortes[0]': 'He PASSED his own top for a second consecutive day, going from 64.50% to 65.50%, the highest value in the AFOS series, which runs from Apr 14 to today.',
  'candidates[0].fracos[0]': 'The gap of +40.75pp is a series maximum, but it widened on a day when Flávio ALSO rose 0.40pp, which rules out a reading of deterioration of the opponent.',
  'candidates[0].analise': 'His day repeated yesterday\'s and went further. The winner contract ROSE 1.00pp and went to 65.50% (vol USD 7.82M), a second series top in two sessions, and the gap WIDENED to +40.75pp, also a maximum. On both days the move came with Flávio rising alongside, which describes demand for the front-runner and not deterioration on the other side. NO NEW POLL. No national poll has been published since Vox Brasil of Jul 31, so the price moved 2.00pp across two sessions with no voting-intention reading to accompany it. It is the fifth session in nine days where this happens, and the panel records the asymmetry without explaining it. IN HIS CAMP, the market undid the previous day\'s move: Camilo Santana gave back 0.90pp and went to 0.45%, his lowest value in the AFOS series, below the 0.50% of Jul 30, and Alckmin gave up 0.10pp, to 0.35%. The easy reading would be to tie this to yesterday\'s PCdoB backing, and the panel does not: the formal support still stands and the price returned to its starting point within 24 hours. ON THE PARTY CALENDAR, the PT makes his candidacy official at a national convention this Sunday, Aug 2, after state conventions in Ceará on Jul 31 and in Bahia today. And his camp took a new judicial fact: on the afternoon of Jul 31, André Mendonça authorized a SECOND inquiry into Lulinha, now over his dealings with Dataprev, a day after the first. An inquiry is not a conviction and the panel does not treat it as one.',
  'candidates[1].header': 'Polymarket 24.75% (up 0.40pp, vol USD 7.79M accumulated), but the gap WIDENS to +40.75pp because Lula rose more. He RISES 1.00pp in [first-round](/en/glossary#primeiro-turno) second place, to 79.50%, and FALLS to 4.95% in third. He remains WITHOUT a running mate four days from the Aug 5 deadline, after the PP\'s refusal.',
  'candidates[1].fortes[0]': 'RISES 0.40pp in the winner contract, to 24.75%, a sixth consecutive session without a fall in that contract.',
  'candidates[1].fortes[3]': 'RISES 1.00pp in the first-round second-place book, to 79.50%, his highest mark in that contract in the panel\'s tracking.',
  'candidates[1].fracos[0]': 'He ROSE in the winner contract and even so saw the gap WIDEN from +40.15pp to +40.75pp, because Lula rose 1.00pp in the same session.',
  'candidates[1].fracos[3]': 'He remains WITHOUT a running mate four days from the Aug 5 deadline. Tereza Cristina regretted the end of the arrangement after the PP\'s refusal and he says he is negotiating with other parties, with no new name announced.',
  'candidates[1].analise': `His signal today is one of a rising price and a tightening political arrangement, and the two do not cancel out. He RISES 0.40pp in the winner contract, to 24.75% (vol USD 7.79M), a sixth consecutive session without a fall, and even so SEES THE GAP WIDEN to +40.75pp, because Lula rose more. In the placing books he RISES 1.00pp in [first-round](/en/glossary#primeiro-turno) second place, to 79.50% (vol USD 216,000), his highest mark there in the panel's tracking, and gives way in third place, to 4.95%. Added together, the two moves say his [runoff](/en/glossary#segundo-turno) position became more consolidated, not less. ${PORTAS_EN} The panel also records, as coverage and not as a number, that the press attributes part of the Centrão's resistance to his exposure to the Master case, without any market measure for it. In the polling, the most recent reading remains Vox Brasil of Jul 31, with 31.2% in the first round and 41.1% in the runoff.`,
  'candidates[2].header': 'Polymarket 7.60% in the winner contract (down 0.55pp, vol USD 8.72M accumulated), his lowest value since May 14. The fall is one of sequence: 12.00% on Jul 23, with 4.40pp given up across nine rounds. In [first-round](/en/glossary#primeiro-turno) second place he FALLS 0.80pp, to 8.55%, and in third place he stays FLAT at 61.50%.',
  'candidates[2].fortes[0]': 'He stays FLAT at 61.50% in the first-round third-place book, and his cushion over Caiado INCREASED, because his rival fell 5.00pp there.',
  'candidates[2].fortes[1]': 'He holds the largest accumulated volume among the competitive names in the presidential market, USD 8.72M, above Lula and above Flávio.',
  'candidates[2].fracos[0]': 'FALLS 0.55pp in the winner contract, to 7.60%, his lowest value since May 14 and a fifth consecutive session of decline.',
  'candidates[2].fracos[1]': 'He gave up 4.40pp across nine rounds, from 12.00% on Jul 23 to 7.60% today, with a gain in only one of them.',
  'candidates[2].fracos[3]': 'FALLS 0.55pp in the winner contract, to 7.60%, the fifth consecutive session of decline in that contract.',
  'candidates[2].analise': `${RENAN_EN} And today's move resolves, on one side, the contradiction the panel recorded yesterday. On Jul 30 the money took away his [runoff](/en/glossary#segundo-turno) chance, dropping the second-place book from 11.70% to 6.10%; on Jul 31 it gave much of it back, taking it to 9.35%; today it took away 0.80pp again, to 8.55%. Three directions in three sessions in the same book, with the winner contract falling in all of them. The reading that survives is the winner contract's, which is where the volume is: USD 8.72M, the largest among the competitive names. In third place he stayed FLAT at 61.50% and his cushion over Caiado increased, because his rival collapsed 5.00pp there. On the polling, nothing changed: the latest national reading remains Vox Brasil of Jul 31, which gave him 3.0%. With the price now at 7.60%, the distance between market and poll NARROWED from 5.15pp to 4.60pp, and it narrowed from the price side, not the polling side.`,
  'candidates[3].header': 'Polymarket: Caiado 1.35% (down 0.25pp, vol USD 5.24M), Jair 0.55% (down 0.30pp), Camilo Santana 0.45% (down 0.90pp, a series low), Alckmin 0.35% (down 0.10pp), Zema 0.35% (flat), Haddad 0.25%, Michelle 0.25%, Tereza Cristina 0.25%, Tarcísio 0.05%. The entire chasing pack gave ground or stood still, and no name passes 1.35%.',
  'candidates[3].subtitle': 'Aug 1, 64 days out: the whole chasing pack shrank, and that is the difference from the previous day, when the signals were crossed. Caiado gave way in the winner contract and collapsed 5.00pp in the third-place book, undoing in one session the previous day\'s gain. Camilo Santana gave back 0.90pp and went to his lowest value in the series. Jair Bolsonaro and Alckmin also gave ground. Zema was flat, interrupting four consecutive declines. No name in the chasing pack passes 1.35%.',
  'candidates[3].caiado.label': 'CAIADO (PSD), presidential Poly 1.35% (down 0.25pp, vol USD 5.24M) | [first-round](/en/glossary#primeiro-turno) third place 22.50% (down 5.00pp, vol USD 37,000) | second place 1.00% | candidate made official on Jul 26, with Kassab as running mate | latest national: Vox Brasil Jul 31, first round 5.5%',
  'candidates[3].caiado.fortes': 'The best national poll of the window is still his, the 5.5% from Vox Brasil of Jul 31, above PoderData\'s 5% on Jul 30 and well above AtlasIntel\'s 3.1% on Jul 29. In the first-round third-place book he holds second position, with 22.50%, behind only Renan Santos. And the divergence between institutes about him remains open at FOUR levels within the same month, 6% at Nexus, 5.5% at Vox, 5% at PoderData and 3.1% at AtlasIntel.',
  'candidates[3].caiado.fracos': 'The winner contract FELL 0.25pp, to 1.35%, and the third-place one COLLAPSED 5.00pp, from 27.50% to 22.50%, undoing in a single session the entire gain the panel recorded the day before. The series caveat is mandatory and does not describe a collapse: his minimum in the AFOS series is 0.90%, from Jul 9, so 1.35% remains above the floor, even if below the 1.80% to 2.40% band in which he traded between Jul 22 and Jul 30. What remains is that yesterday\'s reallocation, from winner to third place, was undone within 24 hours, and he now gives way in both books at the same time.',
  'candidates[3].haddad.label': 'HADDAD (PT), presidential Poly 0.25% (flat) | [first-round](/en/glossary#primeiro-turno) second place 1.00% | not tested by Vox Brasil in any scenario, because he is running for the São Paulo state government',
  'candidates[3].haddad.fortes': 'He stays FLAT at 0.25% in the winner contract and holds 1.00% in the first-round second-place book, interrupting the run of gains without giving ground.',
  'candidates[3].zema.label': 'ZEMA (Novo), presidential Poly 0.35% (flat, vol USD 4.61M) | [first-round](/en/glossary#primeiro-turno) third place 4.60% | Vox Brasil Jul 31: first round 3.2% | made official by Novo on Jul 27, still WITHOUT a running mate, deadline Aug 5',
  'candidates[3].zema.fortes': 'In the polling he holds steady: the 3.2% from Vox on Jul 31 is practically the same as PoderData\'s 3% on Jul 30 and above AtlasIntel\'s 2.8% on Jul 29. He RISES to 4.60% in the first-round third-place book, ahead of the entire chasing pack except Caiado, and interrupts four consecutive sessions of decline in the winner contract, staying flat at 0.35%. He has been official for Novo since Jul 27.',
  'candidates[3].zema.fracos': 'He remains WITHOUT a defined running mate, with the Aug 5 deadline four days away, and Novo ruled out Barbosa for the slot. A series caveat, and it is a large one: his maximum in the AFOS series is 10.10%, from Apr 26, so 0.35% is less than a twentieth of that level and moves in this range carry almost no informational value.',
  'candidates[3].analise': `The entire chasing pack shrank, and that is the difference from yesterday, when the signals were crossed. CAIADO fell 0.25pp in the winner contract, to 1.35% (vol USD 5.24M), and COLLAPSED 5.00pp in the third-place book, from 27.50% to 22.50% (vol USD 37,000), undoing in one session exactly the gain the panel recorded yesterday. The series caveat applies and is not one of collapse: his minimum is 0.90%, from Jul 9, so 1.35% is above the floor, even if below the 1.80% to 2.40% band in which he traded between Jul 22 and Jul 30. CAMILO SANTANA gave back 0.90pp and went to 0.45%, his lowest value in the series, below the 0.50% of Jul 30: in two sessions he rose from the minimum and went back below it. JAIR BOLSONARO fell 0.30pp, to 0.55%, and ALCKMIN gave up 0.10pp, to 0.35%. ZEMA was FLAT at 0.35%, interrupting four sessions of decline, and rose to 4.60% in the third-place book. TEREZA CRISTINA rose 0.05pp, to 0.25%, the day after the PP\'s veto, in a contract that measures who wins the presidency and not who fills the running-mate slot. ${TARCISIO_EN}`,
  'candidates[3].fortes[0]': 'Caiado still holds the best national poll of the window, the 5.5% from Vox Brasil of Jul 31, above PoderData\'s 5% and AtlasIntel\'s 3.1%.',
  'candidates[3].fortes[1]': 'Caiado holds second position in the first-round third-place book, with 22.50%, behind only Renan Santos.',
  'candidates[3].fortes[2]': 'Tereza Cristina rose 0.05pp, to 0.25%, the day after the PP vetoed her as running mate, in a contract that measures the presidency and not the running-mate slot.',
  'candidates[3].fracos[0]': 'Caiado FELL 0.25pp in the winner contract, to 1.35%, and COLLAPSED 5.00pp in the third-place book, from 27.50% to 22.50%, undoing in one session the previous day\'s gain.',
  'candidates[3].fracos[1]': 'No name in the chasing pack passes 1.35% in the presidential contract, against 65.50% for the front-runner.',
  'candidates[3].fracos[4]': 'Camilo Santana gave back 0.90pp and went to 0.45%, his lowest value in the AFOS series, below the 0.50% of Jul 30, undoing in one session the previous day\'s gain.',
  'quadroComparativo[0].p': 'NO NEW POLL. The latest national one remains Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, margin of 2.15pp, 95% confidence, BR-01084/2026), with 40.5% in the [first round](/en/glossary#primeiro-turno) and 47.5% x 41.1% in the [runoff](/en/glossary#segundo-turno). The poll of the day is a state one and for that reason does not enter here: Datafolha in Pernambuco gives him 57% in the state.',
  'quadroComparativo[0].m': '65.50% (vol USD 7.82M accumulated)',
  'quadroComparativo[0].t': 'ROSE 1.00pp and went to 65.50%, the MAXIMUM of the AFOS series for a second consecutive day. The gap over Flávio WIDENED from +40.15pp to +40.75pp, also a series maximum.',
  'quadroComparativo[0].s': '64 days to the election. The price moved 2.00pp across two sessions with NO national poll in between, and the panel records the asymmetry without asserting cause, because there is no voting-intention reading to accompany the move. Live Polymarket Aug 1, 16:49 UTC.',
  'quadroComparativo[1].p': 'Vox Brasil of Jul 31: 31.2% in the first round and 41.1% in the runoff against Lula\'s 47.5%. The 6.4pp difference in the runoff falls outside the two margins added together, so this reading does NOT describe a statistical tie. No new national poll since then.',
  'quadroComparativo[1].m': '24.75% (vol USD 7.79M accumulated)',
  'quadroComparativo[1].t': 'RISES 0.40pp to 24.75% and still sees the gap WIDEN, because the front-runner rose more. RISES 1.00pp in [first-round](/en/glossary#primeiro-turno) second place, to 79.50%, and gives way to 4.95% in third place.',
  'quadroComparativo[1].s': 'Rising in the winner contract and seeing the gap widen at the same time is the record of the day, and the explanation is arithmetic: the front-runner rose more. Politically, he remains without a running mate four days from the deadline, and the Republicanos convention that decides the presidential alliance is only on Aug 4.',
  'quadroComparativo[2].p': 'Vox of Jul 31 gave 3.0% and closed the sequence: THREE consecutive institutes cut him, from 7.8% at AtlasIntel on Jul 29 to 4% at PoderData on Jul 30 and 3.0% now. No new poll since then. With the price at 7.60%, the distance between market and poll NARROWED from 5.15pp to 4.60pp, and it narrowed from the price side.',
  'quadroComparativo[2].m': '7.60% (vol USD 8.72M accumulated)',
  'quadroComparativo[2].t': 'FALLS 0.55pp, to 7.60%, his lowest value since May 14, in a fifth consecutive session of decline. Gives up 0.80pp in [first-round](/en/glossary#primeiro-turno) second place, to 8.55%, and stays FLAT at 61.50% in third place.',
  'quadroComparativo[2].s': 'He is the name that moved most in the window, and always downward: 4.40pp given up across nine rounds since Jul 23. The distance between market and poll, which the panel watched quadruple, has started to close, and it closed because the price fell, not because the polling rose.',
  'quadroComparativo[3].p': 'Vox of Jul 31 gave 5.5%, his best national poll of the window, above PoderData\'s 5% and well above AtlasIntel\'s 3.1%. No new poll since then, and the divergence between institutes about him remains open at four levels within the same month.',
  'quadroComparativo[3].m': '1.35% (vol USD 5.24M)',
  'quadroComparativo[3].t': 'FALLS 0.25pp in the winner contract, to 1.35%, and COLLAPSES 5.00pp in the third-place book, from 27.50% to 22.50%, undoing in one session the previous day\'s gain. His series minimum is 0.90%, from Jul 9.',
  'quadroComparativo[3].s': 'The reallocation the panel recorded yesterday, from winner to third place, was undone within 24 hours: he now gives way in both books at the same time. The series caveat applies and does not describe a collapse, because his minimum is 0.90%, from Jul 9.',
  'quadroComparativo[4].p': 'Vox Brasil of Jul 31: 3.2% in the first round, practically the same as PoderData\'s 3% and above AtlasIntel\'s 2.8%. No new poll since then.',
  'quadroComparativo[4].m': '0.35% (vol USD 4.61M)',
  'quadroComparativo[4].t': 'FLAT at 0.35%, interrupting four consecutive sessions of decline, and RISES to 4.60% in the [first-round](/en/glossary#primeiro-turno) third-place book.',
  'quadroComparativo[4].s': 'The polling keeps him steady around 3% and the price stopped falling after four sessions. A series caveat, and it is a large one: his maximum in the AFOS series is 10.10%, from Apr 26, so moves in this range carry almost no informational value. He remains without a running mate, with the deadline on Aug 5.',
  'quadroComparativo[5].t': 'FLAT at 3.10% for a third session, with no variation across the readings of today\'s two guard rounds.',
  'quadroComparativo[5].s': 'A day with no fresh institutional fact touching the object of this contract, which measures the removal of an STF JUSTICE. The judicial axis did produce fact, the second inquiry into Lulinha, but it targets a private individual and not a member of the Court. With USD 83,000 of accumulated volume against USD 117.52M in the presidential market, a flat price in the face of facts that do not touch the object is the expected behavior.',
  cruzamento: `THE CROSS-READING OF AUG 1 has a single axis in the market and it is yesterday's, now repeated. Lula ROSE 1.00pp and went to 65.50% (vol USD 7.82M), the MAXIMUM of the AFOS series, which runs from Apr 14 to today, for a second consecutive day. Flávio Bolsonaro ROSE 0.40pp, to 24.75% (vol USD 7.79M), and even so the gap WIDENED from +40.15pp to +40.75pp, also the maximum of the series that holds both names, which begins on May 3. On both days the record came with the opponent rising alongside, which describes demand for the front-runner and not deterioration on the other side. `
    + `And there is an asymmetry worth recording without explaining: the price moved 2.00pp across two sessions with NO new national poll. The latest remains Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, margin of 2.15pp, 95% confidence, BR-01084/2026), which gave Lula 40.5% x Flávio 31.2% in the [first round](/en/glossary#primeiro-turno) and 47.5% x 41.1% in the [runoff](/en/glossary#segundo-turno). The panel asserts no cause for the move and has no way to: there was no voting-intention reading in the interval. `
    + `${RENAN_EN} And today's move resolves, on one side, the contradiction recorded yesterday: on Jul 30 the money took away his runoff chance, on Jul 31 it gave much of it back, and today it took away 0.80pp again in the second-place book, which goes to 8.55%. Three directions in three sessions, with the winner contract falling in all of them. With the price at 7.60% and the polling at 3.0%, the distance between market and poll NARROWED from 5.15pp to 4.60pp, and it narrowed from the price side. `
    + `THE WHOLE CHASING PACK SHRANK, and that is the difference from yesterday, when the signals were crossed. CAIADO fell 0.25pp in the winner contract, to 1.35% (vol USD 5.24M), and COLLAPSED 5.00pp in the third-place book, from 27.50% to 22.50% (vol USD 37,000), undoing in one session the previous day's gain; the series caveat applies and does not describe a collapse, because his minimum is 0.90%, from Jul 9. CAMILO SANTANA gave back 0.90pp and went to 0.45% (vol USD 4.19M), his lowest value in the series, below the 0.50% of Jul 30: he rose from the minimum and went back below it in two sessions. Jair Bolsonaro fell 0.30pp, to 0.55%, Alckmin gave up 0.10pp, to 0.35%, and Zema was FLAT at 0.35%, interrupting four consecutive declines. ${TARCISIO_EN} `
    + `${PORTAS_EN} Tereza Cristina appears at 0.25% in the PRESIDENTIAL contract, up 0.05pp, and the distinction matters: that contract measures who wins the presidency, not who fills the running-mate slot. `
    + `ON THE JUDICIAL AXIS, the new fact belongs to the government's camp. On the afternoon of Jul 31, André Mendonça authorized a SECOND Federal Police inquiry into Fábio Luís Lula da Silva, known as Lulinha, this time over his dealings with Dataprev, a day after authorizing the first, over the Health Ministry. None of this is a conviction and the panel does not treat it as one: they are two open inquiries. In the Master case, Novo filed its petition against senator Jaques Wagner with the Ethics Council, following through on the request announced the day before, and the PT made his name official at the Bahia state convention on Saturday. `
    + `ON THE CALENDAR, the PT makes Lula's candidacy official at a national convention on Aug 2, and Republicanos has a national convention set for Aug 4, which is where the presidential alliance is decided. The Aug 5 deadline for naming running mates applies to Flávio and to Zema, and neither has a name settled. `
    + `IN THE OTHER MARKETS, impeachment of an [STF](/en/glossary#stf) justice was FLAT at 3.10% (vol USD 83,000) for a third session. In the Senate, the PL rose 0.50pp, to 72.50% (vol USD 259,000), and the MDB FELL to 21.35%, dropping out of the 24.65% to 26.65% range in which the panel published it yesterday, in a book of USD 8,000 that does not support a reading. In inflation, the modal band remains 5.00% to 5.49%, at 38.20%, and the 4.50% to 4.99% band rose 0.30pp, to 34.00%, in a book of USD 81,000. `
    + `${TRAVA_EN} Total accumulated volume in the presidential market at USD 117.52M.`,
}

const es = {
  subtitle: `ACTUALIZACIÓN 1 de agosto, 13:49 BRT, a 64 días de la [primera vuelta](/es/glossary#primeiro-turno). SEGUNDO DÍA SEGUIDO DE TECHO NUEVO. Lula subió 1,00pp y fue a 65,50% (vol USD 7,82M), máximo de la serie del AFOS, que va del 14 de abril a hoy. Flávio Bolsonaro subió 0,40pp, a 24,75% (vol USD 7,79M), y aun así la brecha se ABRIÓ de +40,15pp a +40,75pp, también máximo de la serie que tiene los dos nombres, que empieza el 3 de mayo. Los dos récords fueron rotos el 31 de julio y rotos de nuevo hoy, y en ambas veces con el adversario subiendo junto: el movimiento es de demanda por el favorito y no de deterioro del otro lado. ${RENAN_ES} TODO EL PELOTÓN ENCOGIÓ: Caiado cayó 0,25pp, a 1,35% (vol USD 5,24M), Jair Bolsonaro cayó 0,30pp, a 0,55%, Alckmin cayó 0,10pp, a 0,35%, y CAMILO SANTANA devolvió todo lo que había ganado la víspera, cayendo 0,90pp a 0,45% (vol USD 4,19M), que es su menor valor en la serie del AFOS, por debajo del 0,50% del 30 de julio. ${TARCISIO_ES} EN LOS BOOKS DE COLOCACIÓN, Flávio subió 1,00pp en el segundo lugar de la primera vuelta, a 79,50%, mientras Renan cedió 0,80pp, a 8,55%, y en el tercer lugar Caiado SE DESPLOMÓ 5,00pp, de 27,50% a 22,50% (vol USD 37.000), deshaciendo en una rueda el alza que el panel registró ayer. ${PORTAS_ES} EN EL EJE JUDICIAL, André Mendonça autorizó en la tarde del 31 de julio una SEGUNDA investigación sobre Fábio Luís Lula da Silva, conocido como Lulinha, esta vez sobre su actuación ante Dataprev, tras la primera, sobre el Ministerio de Salud, autorizada el 30 de julio. La encuesta nacional sigue siendo la Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, 95% de confianza, BR-01084/2026), sin ronda nacional nueva desde entonces. Volumen total acumulado en el presidencial en USD 117,52M. ${TRAVA_ES}`,
  'candidates[0].header': 'Polymarket 65,50% (alza de 1,00pp, vol USD 7,82M acumulado), a 64 días de la elección, en el MÁXIMO de la serie del AFOS por segundo día seguido. La brecha sobre Flávio se abre a +40,75pp, también máximo de la serie. Sin encuesta nacional nueva: la última sigue siendo la Vox Brasil del 31 de julio (n=2.100), con 40,5% en la [primera vuelta](/es/glossary#primeiro-turno) y 47,5% x 41,1% en la [segunda vuelta](/es/glossary#segundo-turno).',
  'candidates[0].fortes[0]': 'SUPERÓ su propio techo por segundo día seguido, yendo de 64,50% a 65,50%, el mayor valor de la serie del AFOS, que va del 14 de abril a hoy.',
  'candidates[0].fracos[0]': 'La brecha de +40,75pp es máximo de la serie, pero se abrió en un día en que Flávio TAMBIÉN subió 0,40pp, lo que descarta la lectura de deterioro del adversario.',
  'candidates[0].analise': 'Su día repitió el de ayer y fue más lejos. El contrato de ganador SUBIÓ 1,00pp y fue a 65,50% (vol USD 7,82M), segundo techo de serie en dos ruedas, y la brecha se ABRIÓ a +40,75pp, también máximo. En los dos días el movimiento vino con Flávio subiendo junto, lo que describe demanda por el favorito y no deterioro del otro lado. SIN ENCUESTA NUEVA. Ninguna nacional se publicó desde la Vox Brasil del 31 de julio, así que el precio se movió 2,00pp en dos ruedas sin ninguna lectura de intención de voto para acompañar. Es la quinta rueda en nueve días en que eso ocurre, y el panel registra la asimetría sin explicarla. EN SU CAMPO, el mercado deshizo el movimiento de la víspera: Camilo Santana devolvió 0,90pp y fue a 0,45%, su menor valor en la serie del AFOS, por debajo del 0,50% del 30 de julio, y Alckmin cedió 0,10pp, a 0,35%. La lectura fácil sería ligar eso al apoyo del PCdoB de ayer, y el panel no lo hace: el apoyo formal sigue valiendo y el precio volvió al punto de partida en 24 horas. EN EL CALENDARIO PARTIDARIO, el PT oficializa su candidatura en convención nacional este domingo, 2 de agosto, tras convenciones estatales en Ceará el 31 de julio y en Bahía hoy. Y su campo recibió un hecho judicial nuevo: en la tarde del 31 de julio, André Mendonça autorizó una SEGUNDA investigación sobre Lulinha, ahora sobre su actuación ante Dataprev, un día después de la primera. Una investigación no es condena y el panel no la trata como tal.',
  'candidates[1].header': 'Polymarket 24,75% (alza de 0,40pp, vol USD 7,79M acumulado), pero la brecha se ABRE a +40,75pp porque Lula subió más. SUBE 1,00pp en el segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), a 79,50%, y CAE a 4,95% en el tercer lugar. Sigue SIN vice a cuatro días del plazo del 5 de agosto, tras la negativa del PP.',
  'candidates[1].fortes[0]': 'SUBE 0,40pp en el contrato de ganador, a 24,75%, sexta rueda seguida sin caída en ese contrato.',
  'candidates[1].fortes[3]': 'SUBE 1,00pp en el book de segundo lugar de la primera vuelta, a 79,50%, su mayor marca en ese contrato en el seguimiento del panel.',
  'candidates[1].fracos[0]': 'SUBIÓ en el contrato de ganador y aun así vio la brecha ABRIRSE de +40,15pp a +40,75pp, porque Lula subió 1,00pp en la misma rueda.',
  'candidates[1].fracos[3]': 'Sigue SIN vice a cuatro días del plazo del 5 de agosto. Tereza Cristina lamentó el fin de la articulación tras la negativa del PP y él afirma que negocia con otros partidos, sin nombre nuevo anunciado.',
  'candidates[1].analise': `Su señal hoy es de alza en el precio y de aprieto en el arreglo político, y las dos cosas no se anulan. SUBE 0,40pp en el contrato de ganador, a 24,75% (vol USD 7,79M), sexta rueda seguida sin caída, y aun así VE LA BRECHA ABRIRSE a +40,75pp, porque Lula subió más. En los books de colocación SUBE 1,00pp en el segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), a 79,50% (vol USD 216.000), su mayor marca ahí en el seguimiento del panel, y cede en el tercer lugar, a 4,95%. Sumados, los dos movimientos dicen que su posición de [segunda vuelta](/es/glossary#segundo-turno) quedó más consolidada, no menos. ${PORTAS_ES} El panel registra además, como cobertura y no como número, que la prensa atribuye parte de la resistencia del Centrão a su exposición al caso Master, sin que exista medida de mercado para eso. En la encuesta, la lectura más reciente sigue siendo la Vox Brasil del 31 de julio, con 31,2% en la primera vuelta y 41,1% en la segunda.`,
  'candidates[2].header': 'Polymarket 7,60% en el contrato de ganador (baja de 0,55pp, vol USD 8,72M acumulado), su menor valor desde el 14 de mayo. La caída es de secuencia: 12,00% el 23 de julio, con 4,40pp cedidos en nueve rondas. En el segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno) CAE 0,80pp, a 8,55%, y en el tercer lugar queda ESTABLE en 61,50%.',
  'candidates[2].fortes[0]': 'Queda ESTABLE en 61,50% en el book de tercer lugar de la primera vuelta, y la holgura sobre Caiado AUMENTÓ, porque el adversario cayó 5,00pp ahí.',
  'candidates[2].fortes[1]': 'Mantiene el mayor volumen acumulado entre los nombres competitivos del presidencial, USD 8,72M, por encima de Lula y de Flávio.',
  'candidates[2].fracos[0]': 'CAE 0,55pp en el contrato de ganador, a 7,60%, su menor valor desde el 14 de mayo y la quinta rueda seguida de caída.',
  'candidates[2].fracos[1]': 'Cedió 4,40pp en nueve rondas, de 12,00% el 23 de julio a 7,60% hoy, con alza en apenas una de ellas.',
  'candidates[2].fracos[3]': 'CAE 0,55pp en el contrato de ganador, a 7,60%, la quinta rueda seguida de caída en ese contrato.',
  'candidates[2].analise': `${RENAN_ES} Y el movimiento de hoy resuelve, por un lado, la contradicción que el panel registró ayer. El 30 de julio el dinero le quitó la chance de [segunda vuelta](/es/glossary#segundo-turno), derribando el book de segundo lugar de 11,70% a 6,10%; el 31 de julio devolvió buena parte, llevándolo a 9,35%; hoy quitó de nuevo 0,80pp, a 8,55%. Tres direcciones en tres ruedas en el mismo book, con el contrato de ganador cayendo en todas. La lectura que sobrevive es la del ganador, que es donde está el volumen: USD 8,72M, el mayor entre los nombres competitivos. En el tercer lugar quedó ESTABLE en 61,50% y la holgura sobre Caiado aumentó, porque el adversario se desplomó 5,00pp ahí. Sobre la encuesta, nada cambió: la última nacional sigue siendo la Vox Brasil del 31 de julio, que le dio 3,0%. Con el precio ahora en 7,60%, la distancia entre mercado y encuesta se ESTRECHÓ de 5,15pp a 4,60pp, y se estrechó por el lado del precio, no de la encuesta.`,
  'candidates[3].header': 'Polymarket: Caiado 1,35% (baja de 0,25pp, vol USD 5,24M), Jair 0,55% (baja de 0,30pp), Camilo Santana 0,45% (baja de 0,90pp, mínimo de la serie), Alckmin 0,35% (baja de 0,10pp), Zema 0,35% (estable), Haddad 0,25%, Michelle 0,25%, Tereza Cristina 0,25%, Tarcísio 0,05%. Todo el pelotón cedió o quedó parado, y ningún nombre pasa de 1,35%.',
  'candidates[3].subtitle': '1 de agosto, a 64 días: todo el pelotón encogió, y esa es la diferencia respecto a la víspera, cuando las señales eran cruzadas. Caiado cedió en el ganador y se desplomó 5,00pp en el book de tercer lugar, deshaciendo en una rueda el alza del día anterior. Camilo Santana devolvió 0,90pp y fue a su menor valor en la serie. Jair Bolsonaro y Alckmin también cedieron. Zema quedó estable, interrumpiendo cuatro caídas seguidas. Ningún nombre del pelotón pasa de 1,35%.',
  'candidates[3].caiado.label': 'CAIADO (PSD), Poly presidencial 1,35% (baja de 0,25pp, vol USD 5,24M) | tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno) 22,50% (baja de 5,00pp, vol USD 37.000) | segundo lugar 1,00% | candidato oficializado el 26 de julio, con Kassab de vice | última nacional: Vox Brasil 31 de julio, primera vuelta 5,5%',
  'candidates[3].caiado.fortes': 'La mejor encuesta nacional del recorte sigue siendo suya, el 5,5% de la Vox Brasil del 31 de julio, por encima del 5% de PoderData del 30 de julio y bien por encima del 3,1% de AtlasIntel del 29 de julio. En el book de tercer lugar de la primera vuelta mantiene la segunda posición, con 22,50%, detrás solo de Renan Santos. Y la divergencia entre institutos sobre él sigue abierta en CUATRO niveles dentro del mismo mes, 6% en Nexus, 5,5% en Vox, 5% en PoderData y 3,1% en AtlasIntel.',
  'candidates[3].caiado.fracos': 'El contrato de ganador CAYÓ 0,25pp, a 1,35%, y el de tercer lugar SE DESPLOMÓ 5,00pp, de 27,50% a 22,50%, deshaciendo en una sola rueda toda el alza que el panel registró la víspera. La salvedad de serie es obligatoria y no describe colapso: su mínimo en la serie del AFOS es 0,90%, del 9 de julio, así que 1,35% sigue por encima del piso, aunque por debajo de la franja de 1,80% a 2,40% en que osciló entre el 22 y el 30 de julio. Lo que queda es que la reasignación de ayer, de ganador a tercer lugar, se deshizo en 24 horas, y ahora cede en los dos books al mismo tiempo.',
  'candidates[3].haddad.label': 'HADDAD (PT), Poly presidencial 0,25% (estable) | segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno) 1,00% | no testeado por Vox Brasil en ningún escenario, porque disputa el gobierno de São Paulo',
  'candidates[3].haddad.fortes': 'Queda ESTABLE en 0,25% en el contrato de ganador y mantiene 1,00% en el book de segundo lugar de la primera vuelta, interrumpiendo la racha de alza sin ceder.',
  'candidates[3].zema.label': 'ZEMA (Novo), Poly presidencial 0,35% (estable, vol USD 4,61M) | tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno) 4,60% | Vox Brasil 31 de julio: primera vuelta 3,2% | oficializado por el Novo el 27 de julio, todavía SIN vice, plazo hasta el 5 de agosto',
  'candidates[3].zema.fortes': 'En la encuesta se mantiene estable: el 3,2% de la Vox del 31 de julio es prácticamente el mismo 3% de PoderData del 30 de julio y queda por encima del 2,8% de AtlasIntel del 29 de julio. SUBE a 4,60% en el book de tercer lugar de la primera vuelta, por delante de todo el pelotón excepto Caiado, e interrumpe cuatro ruedas seguidas de caída en el contrato de ganador, quedando estable en 0,35%. Sigue oficializado por el Novo desde el 27 de julio.',
  'candidates[3].zema.fracos': 'Sigue SIN vice definida, con el plazo del 5 de agosto a cuatro días, y el Novo descartó a Barbosa para la vacante. Salvedad de serie, y es grande: su máximo en la serie del AFOS es 10,10%, del 26 de abril, así que 0,35% es menos de un veinteavo de aquel nivel y movimientos en esta franja tienen valor informativo casi nulo.',
  'candidates[3].analise': `Todo el pelotón encogió, y esa es la diferencia respecto a ayer, cuando las señales eran cruzadas. CAIADO cayó 0,25pp en el contrato de ganador, a 1,35% (vol USD 5,24M), y SE DESPLOMÓ 5,00pp en el book de tercer lugar, de 27,50% a 22,50% (vol USD 37.000), deshaciendo en una rueda exactamente el alza que el panel registró ayer. La salvedad de serie cabe y no es de colapso: su mínimo es 0,90%, del 9 de julio, así que 1,35% está por encima del piso, aunque por debajo de la franja de 1,80% a 2,40% en que osciló entre el 22 y el 30 de julio. CAMILO SANTANA devolvió 0,90pp y fue a 0,45%, su menor valor en la serie, por debajo del 0,50% del 30 de julio: en dos ruedas subió desde el mínimo y volvió por debajo de él. JAIR BOLSONARO cayó 0,30pp, a 0,55%, y ALCKMIN cedió 0,10pp, a 0,35%. ZEMA quedó ESTABLE en 0,35%, interrumpiendo cuatro ruedas de caída, y subió a 4,60% en el book de tercer lugar. TEREZA CRISTINA subió 0,05pp, a 0,25%, al día siguiente del veto del PP, en un contrato que mide quién gana la presidencia y no quién ocupa la vacante de vice. ${TARCISIO_ES}`,
  'candidates[3].fortes[0]': 'Caiado sigue con la mejor encuesta nacional del recorte, el 5,5% de la Vox Brasil del 31 de julio, por encima del 5% de PoderData y del 3,1% de AtlasIntel.',
  'candidates[3].fortes[1]': 'Caiado mantiene la segunda posición en el book de tercer lugar de la primera vuelta, con 22,50%, detrás solo de Renan Santos.',
  'candidates[3].fortes[2]': 'Tereza Cristina subió 0,05pp, a 0,25%, al día siguiente del veto del PP a su candidatura a vice, en un contrato que mide la presidencia y no la vacante de vice.',
  'candidates[3].fracos[0]': 'Caiado CAYÓ 0,25pp en el contrato de ganador, a 1,35%, y SE DESPLOMÓ 5,00pp en el book de tercer lugar, de 27,50% a 22,50%, deshaciendo en una rueda el alza de la víspera.',
  'candidates[3].fracos[1]': 'Ningún nombre del pelotón pasa de 1,35% en el contrato presidencial, contra 65,50% del favorito.',
  'candidates[3].fracos[4]': 'Camilo Santana devolvió 0,90pp y fue a 0,45%, su menor valor en la serie del AFOS, por debajo del 0,50% del 30 de julio, deshaciendo en una rueda el alza de la víspera.',
  'quadroComparativo[0].p': 'SIN ENCUESTA NUEVA. La última nacional sigue siendo la Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, 95% de confianza, BR-01084/2026), con 40,5% en la [primera vuelta](/es/glossary#primeiro-turno) y 47,5% x 41,1% en la [segunda vuelta](/es/glossary#segundo-turno). La encuesta del día es estatal y por eso no entra aquí: la Datafolha de Pernambuco le da 57% en el estado.',
  'quadroComparativo[0].m': '65,50% (vol USD 7,82M acumulado)',
  'quadroComparativo[0].t': 'SUBIÓ 1,00pp y fue a 65,50%, MÁXIMO de la serie del AFOS por segundo día seguido. La brecha sobre Flávio se ABRIÓ de +40,15pp a +40,75pp, también máximo de la serie.',
  'quadroComparativo[0].s': '64 días de la elección. El precio se movió 2,00pp en dos ruedas SIN ninguna encuesta nacional en el intervalo, y el panel registra la asimetría sin afirmar causa, porque no hay lectura de intención de voto para acompañar el movimiento. Polymarket en vivo 1 de agosto, 16:49 UTC.',
  'quadroComparativo[1].p': 'Vox Brasil del 31 de julio: 31,2% en la primera vuelta y 41,1% en la segunda contra 47,5% de Lula. La diferencia de 6,4pp en la segunda vuelta queda fuera de los dos márgenes sumados, así que esta lectura NO describe empate técnico. Sin encuesta nacional nueva desde entonces.',
  'quadroComparativo[1].m': '24,75% (vol USD 7,79M acumulado)',
  'quadroComparativo[1].t': 'SUBE 0,40pp a 24,75% y aun así ve la brecha ABRIRSE, porque el favorito subió más. SUBE 1,00pp en el segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), a 79,50%, y cede a 4,95% en el tercer lugar.',
  'quadroComparativo[1].s': 'Subir en el ganador y ver la brecha abrirse al mismo tiempo es el registro del día, y la explicación es aritmética: el favorito subió más. En lo político, sigue sin vice a cuatro días del plazo, y la convención del Republicanos que decide alianza presidencial es solo el 4 de agosto.',
  'quadroComparativo[2].p': 'La Vox del 31 de julio dio 3,0% y cerró la secuencia: TRES institutos seguidos lo recortaron, de 7,8% en AtlasIntel el 29 de julio a 4% en PoderData el 30 de julio y 3,0% ahora. Sin encuesta nueva desde entonces. Con el precio en 7,60%, la distancia entre mercado y encuesta se ESTRECHÓ de 5,15pp a 4,60pp, y se estrechó por el lado del precio.',
  'quadroComparativo[2].m': '7,60% (vol USD 8,72M acumulado)',
  'quadroComparativo[2].t': 'CAE 0,55pp, a 7,60%, su menor valor desde el 14 de mayo, en la quinta rueda seguida de caída. Cede 0,80pp en el segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), a 8,55%, y queda ESTABLE en 61,50% en el tercer lugar.',
  'quadroComparativo[2].s': 'Es el nombre que más se movió en el recorte, y siempre hacia abajo: 4,40pp cedidos en nueve rondas desde el 23 de julio. La distancia entre mercado y encuesta, que el panel vio cuadruplicarse, empezó a cerrarse, y se cerró porque el precio cayó, no porque la encuesta subiera.',
  'quadroComparativo[3].p': 'La Vox del 31 de julio dio 5,5%, su mejor encuesta nacional del recorte, por encima del 5% de PoderData y bien por encima del 3,1% de AtlasIntel. Sin encuesta nueva desde entonces, y la divergencia entre institutos sobre él sigue abierta en cuatro niveles dentro del mismo mes.',
  'quadroComparativo[3].m': '1,35% (vol USD 5,24M)',
  'quadroComparativo[3].t': 'CAE 0,25pp en el contrato de ganador, a 1,35%, y SE DESPLOMA 5,00pp en el book de tercer lugar, de 27,50% a 22,50%, deshaciendo en una rueda el alza de la víspera. Su mínimo de serie es 0,90%, del 9 de julio.',
  'quadroComparativo[3].s': 'La reasignación que el panel registró la víspera, de ganador a tercer lugar, se deshizo en 24 horas: ahora cede en los dos books al mismo tiempo. La salvedad de serie cabe y no describe colapso, porque su mínimo es 0,90%, del 9 de julio.',
  'quadroComparativo[4].p': 'Vox Brasil del 31 de julio: 3,2% en la primera vuelta, prácticamente el mismo 3% de PoderData y por encima del 2,8% de AtlasIntel. Sin encuesta nueva desde entonces.',
  'quadroComparativo[4].m': '0,35% (vol USD 4,61M)',
  'quadroComparativo[4].t': 'ESTABLE en 0,35%, interrumpiendo cuatro ruedas seguidas de caída, y SUBE a 4,60% en el book de tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno).',
  'quadroComparativo[4].s': 'La encuesta lo mantiene estable en torno al 3% y el precio dejó de caer tras cuatro ruedas. Salvedad de serie, y es grande: su máximo en la serie del AFOS es 10,10%, del 26 de abril, así que movimientos en esta franja tienen valor informativo casi nulo. Sigue sin vice, con plazo el 5 de agosto.',
  'quadroComparativo[5].t': 'ESTABLE en 3,10% por tercera rueda, sin variación en las lecturas de las dos rondas de la traba de hoy.',
  'quadroComparativo[5].s': 'Día sin hecho institucional nuevo que toque el objeto de este contrato, que mide la remoción de un MINISTRO del STF. El eje judicial sí produjo hecho, la segunda investigación sobre Lulinha, pero apunta a un particular y no a un integrante de la Corte. Con USD 83.000 de volumen acumulado contra USD 117,52M del presidencial, precio parado ante hechos que no tocan el objeto es el comportamiento esperado.',
  cruzamento: `EL CRUCE DEL 1 DE AGOSTO tiene un solo eje en el mercado y es el mismo de ayer, ahora repetido. Lula SUBIÓ 1,00pp y fue a 65,50% (vol USD 7,82M), MÁXIMO de la serie del AFOS, que va del 14 de abril a hoy, por segundo día seguido. Flávio Bolsonaro SUBIÓ 0,40pp, a 24,75% (vol USD 7,79M), y aun así la brecha se ABRIÓ de +40,15pp a +40,75pp, también máximo de la serie que tiene los dos nombres, que empieza el 3 de mayo. En los dos días el récord vino con el adversario subiendo junto, lo que describe demanda por el favorito y no deterioro del otro lado. `
    + `Y hay una asimetría que vale registrar sin explicar: el precio se movió 2,00pp en dos ruedas SIN ninguna encuesta nacional nueva. La última sigue siendo la Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, 95% de confianza, BR-01084/2026), que dio Lula 40,5% x Flávio 31,2% en la [primera vuelta](/es/glossary#primeiro-turno) y 47,5% x 41,1% en la [segunda vuelta](/es/glossary#segundo-turno). El panel no atribuye causa al movimiento y no tiene cómo: no hubo lectura de intención de voto en el intervalo. `
    + `${RENAN_ES} Y el movimiento de hoy resuelve, por un lado, la contradicción registrada ayer: el 30 de julio el dinero le quitó la chance de segunda vuelta, el 31 de julio devolvió buena parte, y hoy quitó de nuevo 0,80pp en el book de segundo lugar, que va a 8,55%. Tres direcciones en tres ruedas, con el contrato de ganador cayendo en todas. Con el precio en 7,60% y la encuesta en 3,0%, la distancia entre mercado y encuesta se ESTRECHÓ de 5,15pp a 4,60pp, y se estrechó por el lado del precio. `
    + `TODO EL PELOTÓN ENCOGIÓ, y es la diferencia respecto a ayer, cuando las señales eran cruzadas. CAIADO cayó 0,25pp en el contrato de ganador, a 1,35% (vol USD 5,24M), y SE DESPLOMÓ 5,00pp en el book de tercer lugar, de 27,50% a 22,50% (vol USD 37.000), deshaciendo en una rueda el alza de la víspera; la salvedad de serie cabe y no describe colapso, porque su mínimo es 0,90%, del 9 de julio. CAMILO SANTANA devolvió 0,90pp y fue a 0,45% (vol USD 4,19M), su menor valor en la serie, por debajo del 0,50% del 30 de julio: subió desde el mínimo y volvió por debajo de él en dos ruedas. Jair Bolsonaro cayó 0,30pp, a 0,55%, Alckmin cedió 0,10pp, a 0,35%, y Zema quedó ESTABLE en 0,35%, interrumpiendo cuatro caídas seguidas. ${TARCISIO_ES} `
    + `${PORTAS_ES} Tereza Cristina aparece en 0,25% en el contrato PRESIDENCIAL, alza de 0,05pp, y la distinción importa: ese contrato mide quién gana la presidencia, no quién ocupa la vacante de vice. `
    + `EN EL EJE JUDICIAL, el hecho nuevo es del campo del gobierno. En la tarde del 31 de julio, André Mendonça autorizó una SEGUNDA investigación de la Policía Federal sobre Fábio Luís Lula da Silva, conocido como Lulinha, esta vez respecto de su actuación ante Dataprev, un día después de autorizar la primera, sobre el Ministerio de Salud. Nada de eso es condena y el panel no lo trata como tal: son dos investigaciones abiertas. En el caso Master, el Novo protocolizó la representación contra el senador Jaques Wagner en el Consejo de Ética, dando seguimiento al pedido anunciado la víspera, y el PT oficializó su nombre en la convención estatal de Bahía este sábado. `
    + `EN EL CALENDARIO, el PT oficializa la candidatura de Lula en convención nacional el 2 de agosto, y el Republicanos tiene convención nacional marcada para el 4 de agosto, que es donde se decide la alianza presidencial. El plazo del 5 de agosto para definir vices vale para Flávio y para Zema, y ninguno de los dos tiene nombre cerrado. `
    + `EN LOS DEMÁS MERCADOS, el impeachment de ministro del [STF](/es/glossary#stf) quedó ESTABLE en 3,10% (vol USD 83.000) por tercera rueda. En el Senado, el PL subió 0,50pp, a 72,50% (vol USD 259.000), y el MDB CAYÓ a 21,35%, saliendo de la franja de 24,65% a 26,65% en que el panel lo publicó ayer, en un book de USD 8.000 que no sostiene lectura. En inflación, la franja modal sigue en 5,00% a 5,49%, con 38,20%, y la de 4,50% a 4,99% subió 0,30pp, a 34,00%, en un book de USD 81.000. `
    + `${TRAVA_ES} Volumen total acumulado en el presidencial en USD 117,52M.`,
}

construir('analysis-criteriosa', 'en', en)
construir('analysis-criteriosa', 'es', es)
