/**
 * Mapa EN da ERRATA de serie de 11/Ago para analysis-criteriosa.json.
 * Restaura o topo do Flavio (34,40% em 13/Mai) e o piso do Renan (6,80% em 06/Ago),
 * que a rodada de fechamento havia trocado por valores de fecho-do-dia.
 */
import { construir } from '../build-locale-json'

construir('analysis-criteriosa', 'en', {
  'candidates[1].analise':
    "HIS DAY HOLDS THE BEST AND THE WORST DATA POINT OF THE WINDOW, AND THE TWO CAME OUT TOGETHER. Gerp puts him ahead in the runoff, with 45% against 43%, and it is the first national poll of the period to do so; the release itself treats the 2pp difference as a statistical tie within the margin. On the same day CNT/MDA puts him nine points behind, with 39% against 48%. Futura sits in the middle, with 44% against 46.5%. IN THE FIRST ROUND THE DISTANCE IS EQUALLY LARGE: 28.7% at CNT/MDA and 38% at Gerp, 9.3 points between two readings from the same day. HIS SPREAD IN THE WINDOW REACHED 11.3pp, against 6pp for the leader, and the 28.7% opened a new floor. Choosing one of the three is choosing the conclusion, and that is why the panel publishes the set. IN THE PRICE THE DAY WAS A ROUND TRIP AND ENDED AT ZERO: he fell to 26.95% in the 16:27 reading and closed at 27.25%, exactly where he stood on Aug 10. In the 90-day series, 25 had a value equal to or above it, with a peak of 34.40% on May 13 and a floor of 22.00% on Jul 3. REJECTION REMAINS HIGH: 47.1% at Futura, in a statistical tie with the leader's 45.9%. ON THE BOARD, he stated on Aug 11 that he will attend the debates and that he owes no explanations about the Master case, recorded a campaign broadcast with Michelle Bolsonaro asserting that Moraes is his opponent's operator, and floated ending re-election as a way to attract parties. 📌 His campaign slogan came out on Aug 10, not today.",
  'candidates[2].fortes[1]':
    "He closed 0.10pp above Aug 10, and in the 90-day series 78 had a value equal to or above it, with a floor of 6.80% on Aug 6.",
  'candidates[2].analise':
    "HE WAS THE ONLY NAME TO REALLY MOVE ALL DAY, AND THE MOVE WAS A ROUND TRIP. In the 16:27 reading he marked 8.40%, a rise of 0.75pp; in the closing reading, at 18:22, he stood at 7.75%, that is, 0.10pp above Aug 10. ⚠️ BOTH READINGS WERE CONFIRMED, each by two captures taken eight minutes apart, so neither is wrong: the day simply kept going after the first one. The panel publishes the close and records the path, because hiding the path would make a 1.4pp swing look like a flat day. In the 90-day series, 78 had a value equal to or above 7.75%, with a peak of 17.90% on Jun 9 and a floor of 6.80% on Aug 6. IN THE POLLING Gerp gives him 5% in the first round, behind only the 10% Palver measured online on Aug 10, and CNT/MDA and Futura did not publish the full field. THE METHOD EFFECT REMAINS THE CENTRAL READING ON HIM: the same name runs from 4% to 10% depending on the interview setting, and the caveat is not this panel's, it was declared by Palver itself, which stated that it is testing approaches to reduce the effect in online polls. ⚠️ THE PANEL ATTRIBUTES NEITHER END OF THAT SWING TO THE PUBLIC DISCUSSION ABOUT METHOD that the press ran on Aug 10 and 11. There is no measurement linking the two. He still holds the largest cumulative volume in the book among the names above 1%, with USD 9.44M.",
})
