/**
 * Correção do caso Master de 30/Jul, EN e ES.
 * Só os 3 campos que mudaram; o resto vem da memória por texto de origem.
 */
import { construir } from '../build-locale-json'

const G = (l: 'en' | 'es', id: string, txt: string) => `[${txt}](/${l}/glossary#${id})`

const EN: Record<string, string> = {
  'cards.bancoMaster.text1': `Thursday brought the biggest development in the Master case since the inquiry was opened, and it reaches the campaign directly. The Federal Police is CONSIDERING asking Interpol to include Flávio Bolsonaro and Daniel Vorcaro in what is known as a silver notice, an instrument used to locate assets and funds abroad and which is NOT an arrest order, unlike a red notice. The stated aim is to trace the money behind the film Dark Horse, about Jair Bolsonaro's career, which is said to have received R$ 61 million from Vorcaro's Banco Master. The verb matters and the panel will not force it: the Federal Police is CONSIDERING, it has not filed the request, and Interpol has decided nothing (O Globo, InfoMoney, Gazeta do Povo, Jul 30). The measure rests on the inquiry opened on Jul 23 by André Mendonça and, according to the reporting, was prompted by audio released by The Intercept Brasil in which Jair Bolsonaro's son presses Vorcaro for funds earmarked for the film.`,

  'cards.bancoMaster.conclusao': `The three fronts of the Master case remain on separate tracks and should not be added together, but on Thursday the criminal one reached the campaign. The Federal Police is CONSIDERING asking Interpol to include Flávio Bolsonaro and Vorcaro in a silver notice to trace abroad the money behind the film Dark Horse, and PT members of Congress asked the Federal Police to investigate alleged favouritism by Flávio towards Vorcaro's bank (O Globo, Jul 30). The asset front remains in the Rio courts, with freezes, and the legislative one remains stalled for more than four months in Kassio Nunes Marques's chambers. The only market touching the case, impeachment of an ${G('en', 'stf', 'STF')} justice, pulled back 0.25pp and stands at 3.10%, in a book of USD 83,000 that cannot support a reading of risk repricing in either direction, and which on Thursday moved in the OPPOSITE direction to the institutional accumulation.`,

  'cards.stf.mendonca': `He remains rapporteur of the inquiry opened on Jul 23 into Vorcaro's transfers for the film about Jair Bolsonaro, and it is that inquiry which underpins the day's development: the Federal Police is CONSIDERING asking Interpol to include Flávio Bolsonaro and Daniel Vorcaro in a silver notice, which locates assets abroad and is not an arrest order. The Federal Police is considering, it has not filed the request, and Interpol has decided nothing (O Globo, InfoMoney, Gazeta do Povo, Jul 30). On the overseas asset tracing already authorized, the two corrections of record still hold: the decision was signed in MAY and only became public on Jul 28, and the reporting stopped being single-sourced as of Jul 29.`,
}

const ES: Record<string, string> = {
  'cards.bancoMaster.text1': `El jueves trajo el mayor hecho del caso Master desde la apertura de la investigación, y alcanza directamente a la campaña. La Policía Federal EVALÚA pedir a la Interpol la inclusión de Flávio Bolsonaro y de Daniel Vorcaro en la llamada difusión plateada, instrumento que sirve para localizar bienes y recursos en el exterior y que NO es orden de detención, a diferencia de la difusión roja. El objetivo declarado es rastrear el dinero de la película Dark Horse, sobre la trayectoria de Jair Bolsonaro, que habría recibido R$ 61 millones del Banco Master de Vorcaro. El verbo importa y el panel no lo fuerza: la Policía Federal EVALÚA, no pidió, y la Interpol no decidió nada (O Globo, InfoMoney, Gazeta do Povo, 30 de julio). La medida se apoya en la investigación abierta el 23 de julio por André Mendonça y, según los reportajes, fue motivada por un audio divulgado por The Intercept Brasil en el que el hijo de Jair Bolsonaro le reclama a Vorcaro recursos destinados a la película.`,

  'cards.bancoMaster.conclusao': `Los tres frentes del caso Master siguen en carriles separados y no deben sumarse, pero este jueves el criminal alcanzó a la campaña. La Policía Federal EVALÚA pedir a la Interpol la inclusión de Flávio Bolsonaro y de Vorcaro en la difusión plateada para rastrear en el exterior el dinero de la película Dark Horse, y diputados del PT acudieron a la Policía Federal para investigar un supuesto favorecimiento de Flávio al banco de Vorcaro (O Globo, 30 de julio). El patrimonial sigue en la Justicia de Rio, con bloqueos, y el legislativo sigue detenido hace más de cuatro meses en el despacho de Kassio Nunes Marques. El único mercado que toca el caso, el de impeachment de ministro del ${G('es', 'stf', 'STF')}, retrocedió 0,25pp y está en 3,10%, en un book de USD 83.000 que no sostiene lectura de revaluación de riesgo en ninguna dirección, y que este jueves anduvo en la dirección OPUESTA a la de la acumulación institucional.`,

  'cards.stf.mendonca': `Sigue como relator de la investigación abierta el 23 de julio sobre las transferencias de Vorcaro para la película sobre Jair Bolsonaro, y es esa investigación la que sostiene el hecho del día: la Policía Federal EVALÚA pedir a la Interpol la inclusión de Flávio Bolsonaro y de Daniel Vorcaro en la difusión plateada, que localiza bienes en el exterior y no es orden de detención. La Policía Federal evalúa, no pidió, y la Interpol no decidió (O Globo, InfoMoney, Gazeta do Povo, 30 de julio). Sobre el rastreo patrimonial ya autorizado, los dos ajustes de registro siguen valiendo: la decisión fue firmada en MAYO y solo se hizo pública el 28 de julio, y la investigación dejó de ser fuente única a partir del 29 de julio.`,
}

construir('analysis-data', 'en', EN)
construir('analysis-data', 'es', ES)
