/**
 * Mapa EN de analysis-data.json — /atualizar 25/Jul/2026.
 *
 * Convenções travadas: ponto decimal e vírgula de milhar; "pesquisa" é poll,
 * nunca research; "urna" é polling/ballot box, nunca exit poll. Termo brasileiro
 * sem equivalente fica em português com link de glossário na própria expressão,
 * só na PRIMEIRA ocorrência de cada termo por campo.
 */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/en/glossary#${id})`

construir('analysis-data', 'en', {
  'cards.sentimento.text1':
    `With 71 days to the ${G('first round', 'primeiro-turno')}, the polling drought is over and the answer is clear: stability. ${G('Datafolha', 'datafolha')}, which had been registered but not released as of yesterday's capture, came out on the evening of Jul 24 (n=2,004, fieldwork Jul 22 to 24, 2pp margin, 95% confidence, ${G('TSE', 'tse')} filing BR-01166/2026). In the first round, Lula 40% and Flávio Bolsonaro 32%, against 41% and 31% in the June Datafolha. In the head-to-head runoff, Lula 48% and Flávio 43%, against 47% and 43%. The two readings each moved one point in OPPOSITE directions, both inside the margin: the first round narrowed, the runoff widened. When two cuts of the same poll move in opposite directions and both fit inside the margin, the correct reading is sampling noise, not a trend.`,
  'cards.sentimento.text2':
    `The market, on the same day, did the opposite of standing still. Lula rose 1.00pp and closed the capture at 62.50% (vol USD 7.64M), breaking through the 61.50% that had been the ceiling of the entire AFOS series, a base covering 99 days since Apr 14. Flávio fell 0.10pp to 22.85% (vol USD 7.65M), less than 1pp above the 22.00% floor the same series records on Jul 3. The gap went to +39.65pp and passed the previous peak of +39.50pp, from Jul 3, becoming the widest of the 99 days available. The window is stated on purpose: the AFOS public history API caps queries at 90 days, so any superlative checked through it measures 90 days and calls it a cycle. This check was run directly against the database, and what the database does not prove is what happened before Apr 14.`,
  'cards.sentimento.text3':
    `The day's context was dense and it intersects with the market, without allowing any attribution of cause. The ${G('PL', 'pl')} formalized Flávio's candidacy in São Paulo, with an AI-generated video of Jair Bolsonaro, backing from Michelle and a roughly 30-minute speech by Argentine president Javier Milei, who asked for votes to stop Lula and called Alexandre de Moraes "bald garbage" (Folha de S.Paulo, O Globo, CartaCapital, Metrópoles). In parallel, it emerged that Itamaraty denied visas to two US State Department officials, assistant secretary Riley M. Barnes and deputy assistant secretary Samuel Samson, who applied on Jul 20 and intended to discuss the Brazilian electoral system (Washington Post, Correio Braziliense, Estadão, SBT News). Lula answered at a ${G('PT', 'pt')} convention that anyone coming from abroad to meddle in the Brazilian election "will take a beating." The market capture is from 3:51pm and the gap had been widening since Jul 20, when it stood at +33.60pp: the coincidence of dates is recorded and no cause is asserted.`,
  'cards.sentimento.direita':
    `Flávio had the whole day working for him on the calendar and the price did not follow: it fell 0.10pp to 22.85% on the very session of the convention that formalized his candidacy, with a foreign head of state on the platform. The polling, measured BEFORE the event, is his good news, at 32% in the first round, one point above June. But the number that did not move is the one that weighs most: 48% rejection in the Datafolha, identical to June and the highest among all names tested. He reached the launch WITHOUT a running mate, after Tereza Cristina declined the invitation, and with the União Progressista federation neutral since Jul 22. The gain showed up in one place only, second place in the first round, which rose 2.50pp to 76.50% in a book worth just USD 202 thousand.`,
  'cards.sentimento.esquerda':
    `Lula broke the series ceiling and closed at 62.50% (up 1.00pp, vol USD 7.64M), his highest price across the 99 days in the AFOS base. In the polling, Datafolha keeps him ahead in all three runoffs tested: 48% x 43% against Flávio, 47% x 40% against Caiado and 48% x 40% against Zema. Personal approval came in at 49% against 48% disapproval, with the two ends swapping places relative to June, when it was 48% x 49%, a 1pp move in a survey with a 2pp margin, meaning a statistical tie in both rounds and not a reversal. The caveat that remains: the assessment of the ADMINISTRATION, which is a different question from personal approval, is still negative, with 38% rating it poor or terrible against 32% excellent or good.`,
  'cards.sentimento.terceiraVia':
    `Datafolha gave the chasing pack its most complete measurement in weeks and the result is a clear ceiling: Caiado 4%, Zema 3%, Renan Santos 3% and Augusto Cury 2%. In the runoffs tested, Lula beats Caiado 47% to 40% and Zema 48% to 40%, margins WIDER than the 5pp against Flávio, which cuts against the thesis that a centrist name would be the more competitive opponent. The figure supporting the opposite reading, and which has to come alongside, is rejection: Caiado 12% and Zema 13%, against 48% for Flávio and 46% for Lula. In the book, the day brought broad gains, with Caiado at 1.90% (up 0.15pp), Michelle at 1.15% (up 0.30pp), Jair at 1.25% (up 0.20pp) and Haddad at 0.65% (up 0.30pp), Zema being the only one to fall, 0.20pp to 0.75%.`,
  'cards.sentimento.polymarket':
    `Lula 62.50% (up 1.00pp, vol USD 7.64M), Flávio 22.85% (down 0.10pp, vol USD 7.65M), Renan 10.35% (down 1.40pp, vol USD 8.50M), Caiado 1.90% (up 0.15pp, vol USD 5.12M), Jair 1.25% (up 0.20pp, vol USD 5.24M), Michelle 1.15% (up 0.30pp, vol USD 9.25M), Zema 0.75% (down 0.20pp, vol USD 4.53M), Haddad 0.65% (up 0.30pp, vol USD 6.35M), Tarcísio 0.15%. Lula's gap over Flávio at +39.65pp. Total accumulated volume in the presidential market at USD 115.79M. Capture Jul 25, 6:51pm UTC, confirmed by a double reading 8 minutes apart.`,

  'cards.inss.text1':
    `With 71 days to the election, the fiscal agenda is still bottled up: the Senate went into recess without voting the government's priority bills and Alcolumbre kept the promulgation of the ${G('pauta-bomba', 'pauta-bomba')} on hold pending a conversation with Lula. The theme that took over the day, however, was a different one and it is external: the new round of US tariffs, which according to the government hits 47.3% of Brazilian exports to that country, with the CNI calculating that the double tariff of 37.5% reaches almost 4,000 products and R$ 55 billion in exports (Folha de S.Paulo). The government is weighing a WTO filing and cites the Reciprocity Law to strengthen its negotiating position.`,
  'cards.inss.text2':
    `The market did not price fiscal risk against Lula: he rose. The 1.00pp gain, to 62.50%, came without a single item of the fiscal agenda being resolved, and on a day when the dominant theme in the business press was the loss of competitiveness of Brazilian exports. Datafolha allows the effect of the tariffs on opinion to be measured, and the answer is that there was none: the government's ratings were stable, with approval at 49% against 48% disapproval, and the coverage itself recorded that stability as the main finding (Folha de S.Paulo, O Globo, Correio Braziliense, InfoMoney).`,
  'cards.inss.text3':
    `The ${G('STF', 'stf')} impeachment market was virtually flat at 3.50% (down 0.05pp, vol USD 83 thousand), neither giving back nor extending the 0.60pp rise of Jul 24. The usual methodological caveat applies, and today it matters more than the number: with USD 83 thousand in accumulated volume, against USD 115.79M in the presidential market, this book is orders of magnitude smaller and movement in it does not support a narrative. What is worth recording is the opposite of movement: the price stood still on the same day a foreign head of state called a Supreme Court justice "bald garbage" from a Brazilian campaign platform. Real money went on pricing friction, not rupture.`,
  'cards.inss.text4':
    `On the electoral front, the polling returned and the reading is stability. The Datafolha of Jul 24 (n=2,004, fieldwork Jul 22 to 24, BR-01166/2026) showed Lula at 40% and Flávio at 32% in the first round and 48% x 43% in the runoff, with the two readings moving one point in opposite directions against June, both inside the 2pp margin. Rejection did not move for either name. Renan Santos was measured at 3%, which puts three of the four recent national polls at that level and isolates the 9% from Real Time on Jul 21. The market answered the same day by knocking 1.40pp off his price, to 10.35%.`,
  'cards.inss.impactoLula':
    `The Jul 24 Datafolha is now the highest-weight approval reading in the set: Lula's personal approval at 49% against 48% disapproval, with 3% who do not know. In the previous round it was the reverse, 48% x 49%. The two ends swapped places by 1pp in a survey with a 2pp margin, which is a statistical tie in both rounds and not a reversal, and the honest reading is stability. The earlier ones: PoderData Jul 22 with personal approval 46% x 47%, Indexa Jul 21 at 49% x 48%, Real Time Jul 21 at 46% x 50%, Genial/${G('Quaest', 'quaest')} Jul 15 at 48% x 47% and PoderData/Aya Jul 16 at 42% x 51%.`,
  'cards.inss.impactoGestao':
    `The assessment of the ADMINISTRATION is a different question from personal approval, and the distance between the two is the figure that matters: in the Jul 24 Datafolha, 38% consider the government poor or terrible, 32% excellent or good and 28% fair. In other words, voters approve of the person more than they approve of the administration. On inflation, the market keeps the modal band at 5.00% to 5.49%, priced at 39.15%, followed by the 4.50% to 4.99% band at 26.25% and the 5.50% to 5.99% band at 12.20% (${G('Polymarket', 'polymarket')}). The centre of the distribution remains above the target ceiling, with the whole book totalling USD 80 thousand in volume.`,
  'cards.inss.conclusao':
    `With 71 days to the election, the polling came back and said nothing had changed, while the market said the race is at its most lopsided point in the whole available series. Datafolha measured stability in vote intention, in rejection and in government ratings, including after the new US tariffs. Polymarket, over the same interval, took Lula to 62.50%, above the 61.50% ceiling the 99-day base carried, and opened the gap to +39.65pp, above the previous peak of +39.50pp from Jul 3. Both things were measured in the same week and they do not point the same way. Recording that divergence, without picking a side, is what this panel is for.`,

  'cards.bancoMaster.text1':
    `The ${G('Banco Master', 'banco-master')} case gained a ruling with a figure and named parties on Jul 25: the Rio de Janeiro courts ordered accounts frozen at Banco Master, Trustee DTVM, Axor Asset and two partners, Alexandre Marchesani Canata and Felipe Mota Separovic Rodrigues, capped at R$ 135 million (Agência Brasil, Gazeta do Povo, Band, Revista Oeste). The ruling is by judge Wladimir Hungria, of the Public Treasury Court, and grants a request by the state and by Rioprevidência.`,
  'cards.bancoMaster.text2':
    `The origin is a R$ 150 million contribution that Rioprevidência made to the Texas i Fia fund between Jul 4 and Aug 8, 2025, with the portfolio almost entirely exposed to Ambipar shares. The fall in those shares cut the balance by almost R$ 15 million, and the judge pointed to evidence of irregularity and possible coordinated action by those involved. This is a separate track from the inquiry authorized by André Mendonça on Jul 23, which deals with Daniel Vorcaro's transfers for the film about Jair Bolsonaro and carries a corruption and money-laundering scope.`,
  'cards.bancoMaster.text3':
    `In the market, neither track produced an identifiable price response. Flávio fell only 0.10pp, to 22.85%, and the drop is far too small to be read as a reaction to a procedural fact, all the more so on a day when the dominant event on his agenda was his own convention. The STF impeachment market stayed at 3.50%, essentially flat. Estadão reported that the bench linked to Master is losing members in the pre-campaign, which is an electoral consequence of the case, not a new procedural fact.`,
  'cards.bancoMaster.conclusao':
    `The Master case now runs on two fronts that should not be confused or added together: the criminal one, at the STF, with the inquiry authorized by Mendonça on Jul 23 into Vorcaro's transfers, carrying a corruption and money-laundering scope, and the asset one, in the Rio courts, with the freeze of up to R$ 135 million decided on Jul 23 over Rioprevidência's losses. The second has a figure and named defendants, the first is still under investigation. What real money says about both is the same thing it has been saying: almost nothing. Flávio moved 0.10pp and the justice-impeachment market stood still, in a book of USD 83 thousand that cannot support a reading.`,

  'cards.stf.toffoli':
    'Toffoli remains isolated on the Court after the Master crisis, with no new individual ruling captured during the day.',
  'cards.stf.moraes':
    `He was the day's named target without having taken any new action: Javier Milei called him "bald garbage" from the platform of the PL convention in São Paulo, for not having authorized his visit to Jair Bolsonaro under house arrest, a decision dated Jul 18 (Folha de S.Paulo, CartaCapital, O Globo). Bolsonaro's defence appealed the ban on circulating political manifestos and argues the restriction reaches freedom of thought (Folha de S.Paulo).`,
  'cards.stf.gilmar':
    `No individual ruling by Gilmar during the day. The recent joint vote stands, with Dino, Moraes and Zanin, which loosened restrictions on ${G('penduricalhos', 'penduricalhos')}.`,
  'cards.stf.dino':
    'No individual ruling by Dino during the day. He remains a target of the Bolsonarist camp and the recent joint vote on judicial perks stands. O Globo reports that the Court faces a second round in the budget dispute.',
  'cards.stf.mendonca':
    'Still the justice of the moment in the Master case. As rapporteur of the Vorcaro case, he authorized the Federal Police on Jul 23 to open an inquiry into the banker’s transfers for the film about Jair Bolsonaro, with a corruption and money-laundering scope disclosed on Jul 24. No new individual ruling captured on Jul 25.',
  'cards.stf.nexo':
    `The day's connecting thread shifted from fiscal to sovereignty. The Court still leans toward ruling for the government and blocking the pauta-bomba passed by the Senate, with Alcolumbre holding back promulgation pending a conversation with Lula. But the institutional axis that took the day was external interference: Itamaraty denied visas to two US State Department officials who intended to come and discuss the Brazilian electoral system, a request filed on Jul 20 and denied on Jul 24, and on the same day a foreign president attacked a justice of the Court by name from a platform in São Paulo. Lula answered that anyone coming from abroad to meddle in the election will take a beating, noting that 157 million voters decide the outcome.`,
  'cards.stf.analise':
    `The STF impeachment market stood at 3.50% (down 0.05pp, vol USD 83 thousand), essentially flat, neither giving back nor extending the 0.60pp rise recorded on Jul 24. The methodological caveat matters more than the number: with USD 83 thousand in accumulated volume, against USD 115.79M in the presidential market, this book is orders of magnitude smaller and movement in it does not support a narrative. What is worth recording today is precisely the absence of movement. On the day a foreign head of state called a Supreme Court justice "bald garbage" at a campaign event in Brazil, and on which the Brazilian government denied visas to US envoys who wanted to question the voting machines, the market that prices the removal of a justice did not budge. Real money went on treating the picture as institutional friction, not as risk of rupture.`,
})
