/**
 * Mapas EN e ES do analysis-data.json para a publicação de 30/Jul 17:08.
 * Tradução feita NA SESSÃO. Convenções: EN usa ponto decimal e vírgula de
 * milhar; ES mantém vírgula decimal e ponto de milhar, como o pt.
 */
import { construir } from '../build-locale-json'

const G = (l: 'en' | 'es', id: string, txt: string) => `[${txt}](/${l}/glossary#${id})`

// ── blocos repetidos, iguais aos do pt ──
const PODER_EN = 'PoderData/Aya of Jul 30 (n=2,400, field Jul 26 to 29, 2pp margin, 95% confidence, BR-07845/2026, telephone on mobile and landline, 677 municipalities across the 27 states)'
const PODER_ES = 'PoderData/Aya del 30 de julio (n=2.400, campo del 26 al 29 de julio, margen de 2pp, 95% de confianza, BR-07845/2026, telefónica en celular y fijo, 677 municipios en los 27 estados)'

const REGUA_EN = `The comparison that counts is PoderData against itself, and there the ${G('en', 'primeiro-turno', 'first-round')} gap did NOT move: it was 6pp on Jul 16 (40% to 34%) and it is 6pp now (41% to 35%), with the top two each gaining 1pp, inside the 2pp margin. The tightening only shows up if the ruler is swapped mid-measurement, comparing today's PoderData with yesterday's AtlasIntel, which gave 9.1pp. That is a house effect, not movement, and the panel does not add the two together.`
const REGUA_ES = `La comparación que vale es la de PoderData contra sí misma, y allí la brecha de la ${G('es', 'primeiro-turno', 'primera vuelta')} NO se movió: eran 6pp el 16 de julio (40% x 34%) y son 6pp ahora (41% x 35%), con los dos primeros subiendo 1pp, dentro del margen de 2pp. El estrechamiento solo aparece si se cambia de regla en medio de la medición, comparando la PoderData de hoy con la AtlasIntel de ayer, que dio 9,1pp. Eso es efecto de casa, no movimiento, y el panel no suma las dos.`

const TRAVA_EN = 'The double-reading capture guard ran once and APPROVED with no divergence at all across the five books it covers, which had not happened since Jul 28: it blocked on both of the previous rounds. Every price goes in FIRM, with no declared range.'
const TRAVA_ES = 'La traba de doble lectura corrió una vez y APROBÓ sin ninguna divergencia en los cinco books cubiertos, lo que no ocurría desde el 28 de julio: en las dos rondas anteriores bloqueó. Todos los precios entran FIRMES, sin franja declarada.'

const EN: Record<string, string> = {
  'cards.sentimento.text1': `With 66 days to the ${G('en', 'primeiro-turno', 'first round')}, Thursday brought a national poll and it came from PoderData. ${PODER_EN} has Lula at 41% against Flávio Bolsonaro at 35% in the first round, with Ronaldo Caiado at 5%, Renan Santos at 4%, Romeu Zema at 3% and Augusto Cury at 3%, plus 5% blank or void and 4% who did not answer. In the ${G('en', 'segundo-turno', 'runoff')}, Lula 46% to Flávio 43%, a 3pp difference that fits inside the two margins added together and is therefore a statistical tie. The round also brings Lula's personal approval at 43% against 49% disapproval, government rating at 44% to 50%, and TIED rejection: 49% for Lula and 49% for Flávio.`,

  'cards.sentimento.text2': `The day's crossing repeats Jul 28 and it is what organizes the reading: the price moved a full point and the polling, read properly, is flat. Lula RISES 1.00pp and returns to 63.50%, with the gap over Flávio widening from +38.55pp to +39.55pp. ${REGUA_EN} The temptation was to write that the polling tightened, because 6pp against yesterday's AtlasIntel 9.1pp looks like tightening. It is not. It is the same level difference between the two houses that the panel has been recording since Jul 16, when PoderData contradicted Genial/Quaest with Lula IDENTICAL in both and the whole disagreement concentrated on Flávio.`,

  'cards.sentimento.text3': `In the market, Lula rose 1.00pp and returned to 63.50% (vol USD 7.74M), a level that TIES the top of the AFOS series for the third time, set on Jul 26, Jul 28 and now Jul 30, without exceeding it on any of the three. The +39.55pp gap sits 0.25pp below the series maximum, the +39.80pp of Jul 26. Flávio was FLAT at 23.95% (vol USD 7.71M), breaking a run of four straight daily closes on the rise, and the distinction matters: the gap widened by movement on one side only, so there was no repricing of his candidacy today. Renan Santos fell 0.25pp, to 8.45% (vol USD 8.59M), below every daily close of the past week, but his movement is not in the winner book. Caiado rose 0.20pp, to 2.55% (vol USD 5.20M), adding up to 0.65pp over two sessions, from 1.90% on Jul 28. Zema fell 0.20pp, to 0.55%, Haddad fell 0.10pp, to 0.15%, and Jair stayed put at 1.05%. Total accumulated volume in the presidential market adds up to USD 116.58M.`,

  'cards.sentimento.direita': `Flávio was FLAT at 23.95% (vol USD 7.71M) and the run of four straight daily gains, which had come from 22.90% on Jul 25, stopped without a fall. The one who widened the gap today was Lula. In the sub-markets he ROSE 0.50pp in the ${G('en', 'primeiro-turno', 'first-round')} second-place book, which moves to 79.00% in a contract of USD 215,000, his highest mark there in the panel's tracking, and stayed put at 6.25% in the third-place book. The counterpart to that rise is Renan Santos collapsing in the same book: the market is concentrating in Flávio the probability of taking the second ${G('en', 'segundo-turno', 'runoff')} slot. In the polling, PoderData puts him at 35% in the first round, against 34% from the same house on Jul 16, and at 43% in the runoff, the same value as the institute's two previous rounds. The news is rejection: 49%, TIED with Lula's, when yesterday's AtlasIntel gave 52.9% against 49.4%. In every recent national poll, with the exception of Gerp on Jul 22, his rejection had come in equal to or above Lula's. One reading does not undo the series, but it is on the record. In Thursday's state polls, he leads Rio Grande do Sul in both rounds, 32% to 30% and 40% to 35%, and sits second in Goiás with 27%. The Aug 5 deadline for naming a running mate still stands.`,

  'cards.sentimento.esquerda': `Lula rose 1.00pp and returned to 63.50% (vol USD 7.74M), tying the top of the AFOS series for the third time without exceeding it. It is the third day out of seven in which the price moves a full point, and the pattern the panel keeps recording is that these moves do not coincide with movement in the polling. In Thursday's PoderData he has 41% in the ${G('en', 'primeiro-turno', 'first round')} and 46% to 43% in the ${G('en', 'segundo-turno', 'runoff')}, and inside the house itself the first-round gap has been flat at 6pp since Jul 16. What moved in the round was not voting intention, it was evaluation: personal approval falls to 43% against 49% disapproval, and the GOVERNMENT MANAGEMENT rating gets sharply worse, with poor or terrible at 47%, up 10pp against the institute's Jul 22 round. It is the worst management number in the window, and it lands 24 hours after AtlasIntel measured approval RISING 1.7pp on the same kind of question. Two houses, two opposite signals in the same week. In Thursday's Genial/Quaest state polls, he loses Rio Grande do Sul in both rounds, wins Ceará 55% to 22% and comes THIRD in Goiás with 23%. In his own camp's calendar, the PSB formalized Alckmin as running mate on Jul 29, and the PT national convention that formalizes him is set for Aug 2, in São Paulo.`,

  'cards.sentimento.terceiraVia': `The chasing pack produced the day's most informative movement, and it is a RECLASSIFICATION of Renan Santos. In the winner book he gave up little, 0.25pp, to 8.45% (vol USD 8.59M). In the ${G('en', 'primeiro-turno', 'first-round')} second-place book he COLLAPSED from 11.70% to 6.10%, a fall of 5.60pp in a contract of USD 1.09M. And in the third-place book he ROSE 0.50pp, to 62.00% in a contract of USD 164,000. Added up, the three say the same thing: the money did not take him out of the election, it took away his chance of reaching the ${G('en', 'segundo-turno', 'runoff')} and settled him into third place. And the polling went the same way. PoderData has him at 4%, against 6% from the same house on Jul 16, a 2pp fall that is the round's largest individual swing. That UNDOES yesterday's finding, when the panel recorded the distance between price and polling narrowing to 0.90pp based on AtlasIntel's 7.8%: today it REOPENS to 4.45pp. Convergence measured against a single survey is not a trend, and the spread between institutes still runs six points wide within the same month, between 7.8% and 3%. CAIADO went the other way and is the only name where price and polling rose together: 5% at PoderData, up 1pp inside the house, and 2.55% in the market (vol USD 5.20M), up 0.20pp, adding to 0.65pp over two sessions, from 1.90% on Jul 28. The divergence about him did not close and still stands at three levels: 6% at Nexus, 5% at PoderData, 3.1% at AtlasIntel. The state figure of the day is the sharpest mismatch of the round: Genial/Quaest has him LEADING Goiás with 33%, ahead of Flávio (27%) and Lula (23%), in the same survey where disapproval of his state government is 59%. ZEMA fell on both measures, from 4% to 3% in the polling and 0.20pp in the market, to 0.55%.`,

  'cards.sentimento.polymarket': `Lula 63.50% (up 1.00pp, vol USD 7.74M), Flávio 23.95% (flat, vol USD 7.71M), Renan Santos 8.45% (down 0.25pp, vol USD 8.59M), Caiado 2.55% (up 0.20pp, vol USD 5.20M), Jair 1.05% (flat), Zema 0.55% (down 0.20pp), Michelle 0.45%, Haddad 0.15% (down 0.10pp). Lula's gap over Flávio at +39.55pp, against +38.55pp on Jul 29, sitting 0.25pp below the series maximum. Total accumulated volume in the presidential market at USD 116.58M. Sub-markets: ${G('en', 'primeiro-turno', 'first-round')} second place with Flávio 79.00% (up 0.50pp, vol USD 215,000) and Renan Santos 6.10% (DOWN 5.60pp, vol USD 1.09M); third place with Renan 62.00% (up 0.50pp, vol USD 164,000), Caiado 25.50% (flat, vol USD 37,000), Flávio 6.25% (flat) and Zema 4.50%; impeachment of an ${G('en', 'stf', 'STF')} justice at 3.10% (down 0.25pp, vol USD 83,000); Senate with PL 65.50% (DOWN 5.50pp, vol USD 258,000) and MDB 18.20% (up 0.60pp); inflation with the 5.00% to 5.49% band at 38.30%, the 4.50% to 4.99% band at 32.50% (down 2.40pp) and the 5.50% to 5.99% band at 5.80% (up 1.70pp). ${TRAVA_EN} Live capture Jul 30, 20:08 UTC.`,

  'cards.inss.text1': `The fiscal agenda entered a fourth day with no fresh development: the Senate in recess, priority bills stalled and the promulgation of the ${G('en', 'pauta-bomba', 'pauta-bomba')} still held back by Davi Alcolumbre, with the Budget as the next front of friction between the Senate presidency and the government. The day's economic axis came from abroad and by statement, not by measure: Lula said nobody is going to stick their nose into Brazil's elections, a criticism aimed at the United States and Argentina, and the government kept treating the extension of the American national emergency over Brazil, signed on Jul 28, as possible preparation for new sanctions. No new measure was announced on Thursday, and the panel records the absence.`,

  'cards.inss.text2': `The market did today what it had already done on Jul 28, and the repetition is more informative than the move on its own. The favourite's price rose 1.00pp, to 63.50%, and the day's polling, read inside the house itself, is flat. ${REGUA_EN} For the third time in seven days the price moves a full point without the polling evidence following. The panel records the pattern and does not assert cause, because it has no clear triggering event to attribute it to.`,

  'cards.inss.text3': `The market on impeachment of an ${G('en', 'stf', 'STF')} justice FELL 0.25pp to 3.10% (vol USD 83,000), undoing part of the previous day's 0.55pp rise. Here the point is size, not direction: 0.55pp up and 0.25pp down across two sessions, in a book of USD 83,000 against USD 116.58M in the presidential market, is noise. The day carried real institutional accumulation, with the PT filing at the ${G('en', 'tse', 'TSE')} a petition of more than 200 pages against a network of profiles using artificial intelligence, and the price went the OTHER WAY. That, by itself, says nothing: in a book that size, direction does not carry enough weight to become a reading.`,

  'cards.inss.text4': `Two thin books moved a lot today and both deserve the same caveat. In the Senate, the PL FELL 5.50pp, from 71.00% to 65.50%, and the MDB rose 0.60pp, to 18.20%, in a market totalling USD 292,000, with USD 258,000 concentrated in the PL contract itself. In inflation, the modal band is still 5.00% to 5.49%, at 38.30%, but the 4.50% to 4.99% band fell from 34.90% to 32.50% and the 5.50% to 5.99% band rose from 4.10% to 5.80%, in a book of USD 81,000 that is NOT covered by the double-reading capture guard. A large move in a small book is a record, not a signal, and the panel writes the numbers without turning them into a reading.`,

  'cards.inss.impactoLula': `A new reading, and it comes with two opposite signals in the same week. PoderData/Aya of Jul 30 (field Jul 26 to 29, n=2,400, telephone, 2pp margin, BR-07845/2026) has Lula's personal approval at 43% against 49% disapproval, down 3pp and up 2pp against the institute's own Jul 22 round, and the GOVERNMENT rating at 44% against 50%. Twenty-four hours earlier, AtlasIntel of Jul 29 (n=5,021, 1pp margin) measured 47.6% against 51.2%, with approval RISING 1.7pp against its own Jul 1 round. The two houses therefore point in opposite directions on the same kind of question, in the same week. The panel keeps showing AtlasIntel on the gauge, by the criterion it published on Jul 29, the largest sample and the smallest margin in the window, and records PoderData here without arbitrating which is right. Adding up the week's readings, Lula's approval sits in a band between 43% and 49%, wider than the 47% to 49% band the panel recorded yesterday, and it is PoderData that widens it from below.`,

  'cards.inss.impactoGestao': `Here is the round's harshest number. On the GOVERNMENT MANAGEMENT rating, which is a different question from personal approval, PoderData of Jul 30 brings 34% good or very good, 16% fair and 47% poor or terrible, with poor or terrible up 10pp against the institute's Jul 22 round. It is a big jump for two weeks. AtlasIntel of Jul 29 measured 49.3% poor or terrible, BTG/Nexus of Jul 27 measured 43% and Datafolha of Jul 24 measured 38%. PoderData's 47% level sits inside that band; what draws attention is the SIZE of the jump inside the house itself. The four institutes still agree on what matters most here: management is rated worse than the person, and the distance between the two indicators persists.`,

  'cards.inss.conclusao': `With 66 days to the election, the day repeats Jul 28. The favourite's price rose 1.00pp, returned to 63.50% and tied the top of the AFOS series for the third time without exceeding it, with the gap widening to +39.55pp, 0.25pp below the maximum. And the day's polling, read inside the house itself, is flat. ${REGUA_EN} What changed in the round was not voting intention, it was evaluation: personal approval at 43%, management with 47% poor or terrible, up 10pp, and rejection TIED at 49% for Lula and for Flávio, when yesterday AtlasIntel gave 49.4% against 52.9%. The asymmetry the panel had been calling a structural constraint on Flávio's candidacy did not show up in this reading, and one round does not undo the series, but it is on the record. The panel does not claim the price rose because of anything: there is no clear triggering event in the day, and three full-point moves in seven days with no matching polling is a pattern the panel would rather record than explain.`,

  'cards.bancoMaster.text1': `Thursday brought no fresh development in the Master case, and the absence is the record. The criminal front remains at the ${G('en', 'stf', 'STF')} under André Mendonça, with the overseas asset tracing of Daniel Vorcaro's holdings authorized in a decision signed in MAY and made public on Jul 28, already confirmed by more than one newsroom since Jul 29. No new order appeared on Thursday. Word circulated that the Federal Police had appealed to the AGU after decisions by Mendonça, but it appeared in a single source of low editorial quality, and so the panel does NOT incorporate it: it records that it saw the claim and could not confirm it in an independent second source.`,

  'cards.bancoMaster.text2': `On the legislative front, the news is still the absence of a decision. The writ of mandamus disputing the installation of the Banco Master CPI has sat for more than four months in Kassio Nunes Marques's chambers, and the request by four senators to remove him from the case was rejected. With the Senate in recess and the August agenda still contested between Alcolumbre and the government, there is no deadline in sight. The panel records the elapsed time because it is the fact: four months without a decision on installing a CPI is, in itself, a decision about installing it.`,

  'cards.bancoMaster.text3': `On price, the record comes with the exact number and with the caveat ahead of the reading: the market on impeachment of an ${G('en', 'stf', 'STF')} justice FELL 0.25pp to 3.10%, in a book of USD 83,000. Yesterday it had risen 0.55pp. Across two sessions, therefore, the net move is 0.30pp up, and in a volume that size that is noise. The panel does NOT attribute the move to any specific event, and underlines that the day carried relevant institutional accumulation in the OPPOSITE direction to the price, with the PT filing at the ${G('en', 'tse', 'TSE')} a petition against a network of profiles using artificial intelligence. When the accumulation and the price point in different directions in a small book, the honest reading is that the book is not big enough to answer the accumulation.`,

  'cards.bancoMaster.conclusao': `The three fronts of the Master case remain on separate tracks and should not be added together: the criminal one, at the ${G('en', 'stf', 'STF')} under Mendonça, with overseas asset tracing in a decision signed in May and revealed on Jul 28; the asset one, in the Rio courts, with freezes; and the legislative one, stalled for more than four months in Nunes Marques's chambers. None of them produced a new act on Thursday. The only market touching the case, impeachment of an STF justice, pulled back 0.25pp and stands at 3.10%, in a book of USD 83,000 that cannot support a reading of risk repricing in either direction.`,

  'cards.stf.toffoli': `Toffoli remains isolated at the ${G('en', 'stf', 'STF')} after the Master crisis, with no fresh individual act captured on Thursday.`,

  'cards.stf.moraes': `No new order from Moraes captured on Thursday. The front he opened is still live: on Jul 28 he gave Jair Bolsonaro's defence 48 hours to explain the video generated by artificial intelligence carrying the former president's image and voice, setting out TWO mutually exclusive hypotheses, and on Jul 29 the defence replied that he did NOT authorize the use of his own image, adding that it does not object to relatives producing that kind of content, a practice it called well known and continuous. It is a defence against breach of precautionary measures, and its effect is to shift exposure from the father to the son and to the party, by way of the deep fake barred under electoral law. The deadline Moraes set has expired and the panel is waiting for the next decision.`,

  'cards.stf.dino': `No new act on Thursday. Still running is the 10-day deadline he set on Jul 29 for the government and Congress to specify the responsibility of members of Congress over parliamentary earmarks, with the signal that a legislator can be punished for failing to oversee an earmark they themselves designated.`,

  'cards.stf.mendonca': `He remains rapporteur of the inquiry opened on Jul 23 into Vorcaro's transfers for the film about Jair Bolsonaro. On the overseas asset tracing, the two corrections of record still hold: the decision was signed in MAY and only became public on Jul 28, and the reporting stopped being single-sourced as of Jul 29. No new act on Thursday.`,

  'cards.stf.nexo': `Thursday's connecting thread is the same as the two previous days, artificial intelligence in campaigning, but this time the move came from a PARTY and not from a justice. The Brazil of Hope Federation, which brings together PT, PCdoB and PV, filed at the ${G('en', 'tse', 'TSE')} a petition of more than 200 pages against a network of 31 profiles that, ACCORDING TO THE FEDERATION'S CLAIM, uses artificial intelligence to attack Lula. The figures in the petition, all attributed to the federation and not independently verified by the panel, are 1,464,245 combined followers, 23,828 posts and an estimated reach of 10 million accounts, with boosting attributed to Flávio Bolsonaro and other politicians. The requests are for removal of URLs, lifting the anonymity of those responsible and suspension of monetization (Metrópoles, CNN Brasil, Migalhas). It is the third consecutive day in which the panel's institutional axis is the use of artificial intelligence in campaigning, and the structural novelty is that the dispute is no longer only between the STF and a defence: a party is now the petitioner at the TSE.`,

  'cards.stf.analise': `The market on impeachment of an ${G('en', 'stf', 'STF')} justice before 2027 FELL 0.25pp to 3.10% (vol USD 83,000), undoing part of yesterday's 0.55pp rise. The methodological caveat comes before the reading and it is the usual one: 0.25pp in a book of USD 83,000, against USD 116.58M in the presidential market, is very little money, and does not license talk of risk repricing in either direction. With the caveat made, what matters is the MISMATCH. The day carried relevant institutional accumulation, with a party filing at the ${G('en', 'tse', 'TSE')} a petition of more than 200 pages on the use of artificial intelligence in campaigning, and the price went the other way. On Jul 29 the panel recorded the price direction following the accumulation; today it contradicts it. Two days, two directions, a net move of 0.30pp up. The honest reading is that this book is not big enough to respond to institutional news, and that trying to read cause into it in either direction would be building narrative on noise. The panel records the numbers and stops there.`,
}

const ES: Record<string, string> = {
  'cards.sentimento.text1': `A 66 días de la ${G('es', 'primeiro-turno', 'primera vuelta')}, el jueves trajo encuesta nacional y vino de PoderData. ${PODER_ES} da a Lula 41% contra 35% de Flávio Bolsonaro en la primera vuelta, con Ronaldo Caiado 5%, Renan Santos 4%, Romeu Zema 3% y Augusto Cury 3%, además de 5% de blanco o nulo y 4% que no respondieron. En la ${G('es', 'segundo-turno', 'segunda vuelta')}, Lula 46% x Flávio 43%, una diferencia de 3pp que cabe dentro de los dos márgenes sumados y por eso es empate técnico. La ronda trae además la aprobación personal de Lula en 43% contra 49% de desaprobación, evaluación del gobierno en 44% x 50%, y rechazo EMPATADO: 49% para Lula y 49% para Flávio.`,

  'cards.sentimento.text2': `El cruce del día repite el del 28 de julio y es lo que organiza la lectura: el precio se movió un punto entero y la encuesta, leída correctamente, está quieta. Lula SUBE 1,00pp y vuelve a 63,50%, con la brecha sobre Flávio abriéndose de +38,55pp a +39,55pp. ${REGUA_ES} La tentación era escribir que la encuesta se estrechó, porque 6pp contra los 9,1pp de la AtlasIntel de ayer parece estrechamiento. No lo es. Es la misma diferencia de nivel entre las dos casas que el panel registra desde el 16 de julio, cuando PoderData contradijo a Genial/Quaest con Lula IDÉNTICO en ambas y todo el desacuerdo concentrado en Flávio.`,

  'cards.sentimento.text3': `En el mercado, Lula subió 1,00pp y volvió a 63,50% (vol USD 7,74M), valor que IGUALA por tercera vez el techo de la serie del AFOS, marcado el 26, el 28 y ahora el 30 de julio, sin superarlo en ninguna de las tres. La brecha de +39,55pp queda a 0,25pp del máximo de la serie, los +39,80pp del 26 de julio. Flávio quedó ESTABLE en 23,95% (vol USD 7,71M), interrumpiendo cuatro cierres diarios seguidos al alza, y la distinción importa: la brecha se abrió por movimiento de un solo lado, así que no hubo revaluación de su candidatura hoy. Renan Santos cayó 0,25pp, a 8,45% (vol USD 8,59M), por debajo de todo cierre diario de la última semana, pero su movimiento no está en el book de ganador. Caiado subió 0,20pp, a 2,55% (vol USD 5,20M), acumulando 0,65pp en dos ruedas, de 1,90% el 28 de julio. Zema cayó 0,20pp, a 0,55%, Haddad cayó 0,10pp, a 0,15%, y Jair quedó quieto en 1,05%. El volumen total acumulado en el presidencial suma USD 116,58M.`,

  'cards.sentimento.direita': `Flávio quedó ESTABLE en 23,95% (vol USD 7,71M) y la racha de cuatro alzas diarias, que venía de 22,90% el 25 de julio, se detuvo sin caída. Quien abrió la brecha hoy fue Lula. En los submercados SUBIÓ 0,50pp en el book de segundo lugar de la ${G('es', 'primeiro-turno', 'primera vuelta')}, que pasa a 79,00% en un contrato de USD 215.000, su mayor marca allí en el seguimiento del panel, y quedó quieto en 6,25% en el de tercer lugar. La contrapartida de esa alza es el desplome de Renan Santos en el mismo book: el mercado está concentrando en Flávio la probabilidad de ocupar el segundo lugar de la ${G('es', 'segundo-turno', 'segunda vuelta')}. En la encuesta, PoderData lo trae en 35% en la primera vuelta, ante 34% de la propia casa el 16 de julio, y en 43% en la segunda vuelta, el mismo valor de las dos rondas anteriores del instituto. La novedad es el rechazo: 49%, EMPATADO con el de Lula, cuando la AtlasIntel de ayer daba 52,9% contra 49,4%. En todas las nacionales recientes, con excepción de Gerp del 22 de julio, su rechazo venía igual o por encima. Una lectura no deshace la serie, pero queda registrado. En las estatales de este jueves, lidera Rio Grande do Sul en las dos vueltas, 32% x 30% y 40% x 35%, y queda segundo en Goiás, con 27%. El plazo del 5 de agosto para definir vice sigue vigente.`,

  'cards.sentimento.esquerda': `Lula subió 1,00pp y volvió a 63,50% (vol USD 7,74M), igualando por tercera vez el techo de la serie del AFOS sin superarlo. Es el tercer día en siete en que el precio se mueve un punto entero, y el patrón que el panel viene registrando es que esos movimientos no coinciden con movimiento de encuesta. En la PoderData de este jueves tiene 41% en la ${G('es', 'primeiro-turno', 'primera vuelta')} y 46% x 43% en la ${G('es', 'segundo-turno', 'segunda vuelta')}, y dentro de la propia casa la brecha de la primera vuelta está quieta en 6pp desde el 16 de julio. Lo que se movió en la ronda no fue la intención de voto, fue la evaluación: la aprobación personal cae a 43% contra 49% de desaprobación, y la evaluación de la GESTIÓN empeora fuerte, con mala o pésima en 47%, un alza de 10pp contra la ronda del 22 de julio del instituto. Es el peor número de gestión del recorte, y llega 24 horas después de que AtlasIntel midiera la aprobación SUBIENDO 1,7pp por el mismo tipo de pregunta. Dos casas, dos señales opuestas en la misma semana. En las estatales de Genial/Quaest de este jueves, pierde Rio Grande do Sul en las dos vueltas, gana Ceará por 55% x 22% y aparece TERCERO en Goiás, con 23%. En el calendario de su propio campo, el PSB formalizó el 29 de julio la indicación de Alckmin como vice, y la convención nacional del PT que lo formaliza está marcada para el 2 de agosto, en São Paulo.`,

  'cards.sentimento.terceiraVia': `El pelotón tuvo el movimiento más informativo del día, y es una RECLASIFICACIÓN de Renan Santos. En el book de ganador cedió poco, 0,25pp, a 8,45% (vol USD 8,59M). En el de segundo lugar de la ${G('es', 'primeiro-turno', 'primera vuelta')} se DESPLOMÓ de 11,70% a 6,10%, una caída de 5,60pp en un contrato de USD 1,09M. Y en el de tercer lugar SUBIÓ 0,50pp, a 62,00% en un contrato de USD 164.000. Sumados, los tres dicen lo mismo: el dinero no lo sacó de la elección, le quitó la chance de disputar la ${G('es', 'segundo-turno', 'segunda vuelta')} y lo consolidó como tercer colocado. Y la encuesta fue en la misma dirección. PoderData lo da en 4%, contra 6% de la propia casa el 16 de julio, una caída de 2pp que es la mayor variación individual de la ronda. Eso DESHACE el hallazgo de ayer, cuando el panel registró la distancia entre precio y encuesta cayendo a 0,90pp con base en los 7,8% de AtlasIntel: hoy REABRE a 4,45pp. Convergencia medida contra un único levantamiento no es tendencia, y la dispersión entre institutos sigue con seis puntos de amplitud en el mismo mes, entre 7,8% y 3%. CAIADO fue en dirección opuesta y es el único nombre en que precio y encuesta subieron juntos: 5% en PoderData, alza de 1pp dentro de la casa, y 2,55% en el mercado (vol USD 5,20M), alza de 0,20pp, acumulando 0,65pp en dos ruedas, de 1,90% el 28 de julio. La divergencia sobre él no cerró y sigue en tres niveles: 6% en Nexus, 5% en PoderData, 3,1% en AtlasIntel. El dato estatal del día es el desajuste más nítido de la ronda: Genial/Quaest lo da LIDERANDO Goiás con 33%, por delante de Flávio (27%) y de Lula (23%), en el mismo levantamiento en que la desaprobación de su gobierno estatal es de 59%. ZEMA cayó en las dos medidas, de 4% a 3% en la encuesta y 0,20pp en el mercado, a 0,55%.`,

  'cards.sentimento.polymarket': `Lula 63,50% (alza 1,00pp, vol USD 7,74M), Flávio 23,95% (estable, vol USD 7,71M), Renan Santos 8,45% (caída 0,25pp, vol USD 8,59M), Caiado 2,55% (alza 0,20pp, vol USD 5,20M), Jair 1,05% (estable), Zema 0,55% (caída 0,20pp), Michelle 0,45%, Haddad 0,15% (caída 0,10pp). Brecha de Lula sobre Flávio en +39,55pp, contra +38,55pp el 29 de julio, a 0,25pp del máximo de la serie. Volumen total acumulado en el presidencial en USD 116,58M. Submercados: segundo lugar de la ${G('es', 'primeiro-turno', 'primera vuelta')} con Flávio 79,00% (alza 0,50pp, vol USD 215.000) y Renan Santos 6,10% (CAÍDA de 5,60pp, vol USD 1,09M); tercer lugar con Renan 62,00% (alza 0,50pp, vol USD 164.000), Caiado 25,50% (estable, vol USD 37.000), Flávio 6,25% (estable) y Zema 4,50%; impeachment de ministro del ${G('es', 'stf', 'STF')} en 3,10% (caída 0,25pp, vol USD 83.000); Senado con PL 65,50% (CAÍDA de 5,50pp, vol USD 258.000) y MDB 18,20% (alza 0,60pp); inflación con la franja de 5,00% a 5,49% en 38,30%, la de 4,50% a 4,99% en 32,50% (caída 2,40pp) y la de 5,50% a 5,99% en 5,80% (alza 1,70pp). ${TRAVA_ES} Captura en vivo 30 de julio, 20:08 UTC.`,

  'cards.inss.text1': `La agenda fiscal entró en su cuarto día sin hecho nuevo: Senado en receso, proyectos prioritarios detenidos y la promulgación de la ${G('es', 'pauta-bomba', 'pauta-bomba')} todavía retenida por Davi Alcolumbre, con el Presupuesto como próximo frente de fricción entre la presidencia del Senado y el gobierno. El eje económico del día vino de afuera y por declaración, no por medida: Lula dijo que nadie va a meterse en las elecciones brasileñas, en crítica dirigida a Estados Unidos y Argentina, y el gobierno siguió tratando la prórroga de la emergencia estadounidense sobre Brasil, firmada el 28 de julio, como posible preparación para nuevas sanciones. Ninguna medida nueva fue anunciada este jueves, y el panel registra la ausencia.`,

  'cards.inss.text2': `El mercado hizo hoy lo que ya había hecho el 28 de julio, y la repetición es más informativa que el movimiento aislado. El precio del favorito subió 1,00pp, a 63,50%, y la encuesta del día, leída dentro de la propia casa, está quieta. ${REGUA_ES} Por tercera vez en siete días el precio se mueve un punto entero sin que la evidencia de encuesta acompañe. El panel registra el patrón y no afirma causa, porque no tiene evento disparador claro al cual atribuirlo.`,

  'cards.inss.text3': `El mercado de impeachment de ministro del ${G('es', 'stf', 'STF')} CAYÓ 0,25pp y fue a 3,10% (vol USD 83.000), deshaciendo parte del alza de 0,55pp de la víspera. Aquí el registro es de tamaño, no de dirección: 0,55pp hacia arriba y 0,25pp hacia abajo en dos ruedas, en un book de USD 83.000 contra USD 116,58M del presidencial, es ruido. El día tuvo acumulación institucional relevante, con el PT presentando en el ${G('es', 'tse', 'TSE')} una representación de más de 200 páginas contra una red de perfiles que usa inteligencia artificial, y el precio fue hacia el LADO CONTRARIO. Eso, por sí solo, no dice nada: en un book de ese tamaño, la dirección no tiene respaldo suficiente para volverse lectura.`,

  'cards.inss.text4': `Dos books finos se movieron mucho hoy y merecen la misma salvedad. En el Senado, el PL CAYÓ 5,50pp, de 71,00% a 65,50%, y el MDB subió 0,60pp, a 18,20%, en un mercado que suma USD 292.000 en total, con USD 258.000 concentrados en el propio PL. En inflación, la franja modal sigue en 5,00% a 5,49%, con 38,30%, pero la de 4,50% a 4,99% cayó de 34,90% a 32,50% y la de 5,50% a 5,99% subió de 4,10% a 5,80%, en un book de USD 81.000 que NO está cubierto por la traba de doble lectura. Movimiento grande en book pequeño es registro, no señal, y el panel escribe los números sin transformarlos en lectura.`,

  'cards.inss.impactoLula': `Lectura nueva y viene con dos señales opuestas en la misma semana. La PoderData/Aya del 30 de julio (campo del 26 al 29 de julio, n=2.400, telefónica, margen de 2pp, BR-07845/2026) da la aprobación personal de Lula en 43% contra 49% de desaprobación, una caída de 3pp y un alza de 2pp contra la ronda del 22 de julio del propio instituto, y la evaluación del GOBIERNO en 44% contra 50%. Veinticuatro horas antes, la AtlasIntel del 29 de julio (n=5.021, margen de 1pp) medía 47,6% contra 51,2%, con la aprobación SUBIENDO 1,7pp contra su propia ronda del 1 de julio. Las dos casas, por lo tanto, apuntan hacia lados opuestos por el mismo tipo de pregunta, en la misma semana. El panel sigue exhibiendo AtlasIntel en el medidor, por el criterio que publicó el 29 de julio, la mayor muestra y el menor margen del recorte, y registra PoderData aquí, sin arbitrar cuál está en lo cierto. Sumando las lecturas de la semana, la aprobación de Lula está en una franja entre 43% y 49%, más ancha que la franja de 47% a 49% que el panel registró ayer, y es PoderData la que la ensancha por abajo.`,

  'cards.inss.impactoGestao': `Aquí está el número más duro de la ronda. En la evaluación de la GESTIÓN, que es pregunta distinta de la aprobación personal, la PoderData del 30 de julio trae 34% de óptima o buena, 16% de regular y 47% de mala o pésima, con la mala o pésima subiendo 10pp contra la ronda del 22 de julio del instituto. Es un salto grande para dos semanas. La AtlasIntel del 29 de julio medía 49,3% de mala o pésima, la BTG/Nexus del 27 de julio medía 43% y la Datafolha del 24 de julio medía 38%. El nivel de 47% de PoderData queda dentro de esa franja; lo que llama la atención es el TAMAÑO del salto dentro de la propia casa. Los cuatro institutos siguen coincidiendo en lo que más importa aquí: la gestión es evaluada peor que la persona, y la distancia entre los dos indicadores persiste.`,

  'cards.inss.conclusao': `A 66 días de la elección, el día repite el 28 de julio. El precio del favorito subió 1,00pp, volvió a 63,50% e igualó por tercera vez el techo de la serie del AFOS sin superarlo, con la brecha abriéndose a +39,55pp, a 0,25pp del máximo. Y la encuesta del día, leída dentro de la propia casa, está quieta. ${REGUA_ES} Lo que cambió en la ronda no fue la intención de voto, fue la evaluación: aprobación personal en 43%, gestión con 47% de mala o pésima, alza de 10pp, y rechazo EMPATADO en 49% para Lula y para Flávio, cuando ayer AtlasIntel daba 49,4% contra 52,9%. La asimetría que el panel venía llamando restricción estructural de la candidatura de Flávio no apareció en esta lectura, y una ronda no deshace la serie, pero queda registrado. El panel no afirma que el precio subió por causa de nada: no hay evento disparador claro en el día, y tres movimientos de un punto entero en siete días sin encuesta correspondiente es un patrón que el panel prefiere registrar a explicar.`,

  'cards.bancoMaster.text1': `El jueves no trajo hecho nuevo en el caso Master, y la ausencia es el registro. El frente criminal sigue en el ${G('es', 'stf', 'STF')} bajo relatoría de André Mendonça, con el rastreo patrimonial en el exterior de bienes de Daniel Vorcaro autorizado en decisión firmada en MAYO y hecha pública el 28 de julio, ya confirmada por más de una redacción desde el 29 de julio. Ningún despacho nuevo apareció este jueves. Circuló una información de que la Policía Federal habría recurrido a la AGU tras decisiones de Mendonça, pero apareció en fuente única y de baja calidad editorial, y por eso el panel NO la incorpora: registra que la vio y que no logró confirmarla en una segunda fuente independiente.`,

  'cards.bancoMaster.text2': `En el frente legislativo, la novedad sigue siendo la ausencia de decisión. El mandato de seguridad que discute la instalación de la CPI del Banco Master lleva más de cuatro meses en el despacho de Kassio Nunes Marques, y el pedido de cuatro senadores para apartarlo de la relatoría fue rechazado. Con el Senado en receso y la agenda de agosto todavía en disputa entre Alcolumbre y el gobierno, no hay plazo a la vista. El panel registra el tiempo transcurrido porque es el hecho: cuatro meses sin decisión sobre la instalación de una CPI es, en sí, una decisión sobre su instalación.`,

  'cards.bancoMaster.text3': `Sobre el precio, el registro viene con el número exacto y con la salvedad antes de la lectura: el mercado de impeachment de ministro del ${G('es', 'stf', 'STF')} CAYÓ 0,25pp y fue a 3,10%, en un book de USD 83.000. Ayer había subido 0,55pp. En dos ruedas, por lo tanto, el movimiento neto es de 0,30pp hacia arriba, y en un volumen de ese tamaño eso es ruido. El panel NO atribuye el movimiento a ningún evento específico, y subraya que el día tuvo acumulación institucional relevante en la dirección OPUESTA a la del precio, con el PT presentando en el ${G('es', 'tse', 'TSE')} una representación contra una red de perfiles con inteligencia artificial. Cuando la acumulación y el precio apuntan hacia lados distintos en un book pequeño, la lectura honesta es que el book no tiene tamaño para responder a la acumulación.`,

  'cards.bancoMaster.conclusao': `Los tres frentes del caso Master siguen en carriles separados y no deben sumarse: el criminal, en el ${G('es', 'stf', 'STF')} bajo relatoría de Mendonça, con rastreo patrimonial en el exterior en decisión firmada en mayo y revelada el 28 de julio; el patrimonial, en la Justicia de Rio, con bloqueos; y el legislativo, detenido hace más de cuatro meses en el despacho de Nunes Marques. Ninguno de ellos produjo acto nuevo este jueves. El único mercado que toca el caso, el de impeachment de ministro del STF, retrocedió 0,25pp y está en 3,10%, en un book de USD 83.000 que no sostiene lectura de revaluación de riesgo en ninguna dirección.`,

  'cards.stf.toffoli': `Toffoli sigue aislado en el ${G('es', 'stf', 'STF')} tras la crisis del Master, sin acto individual nuevo capturado este jueves.`,

  'cards.stf.moraes': `Sin despacho nuevo de Moraes capturado este jueves. El frente abierto por él sigue vigente: el 28 de julio dio 48 horas a la defensa de Jair Bolsonaro para explicar el video generado por inteligencia artificial con la imagen y la voz del expresidente, montando DOS hipótesis excluyentes, y el 29 de julio la defensa respondió que él NO autorizó el uso de su propia imagen, aclarando que no se opone a que familiares produzcan ese tipo de contenido, práctica que calificó de notoria y continua. Es defensa contra incumplimiento de medidas cautelares, y su efecto es desplazar la exposición del padre hacia el hijo y hacia el partido, por la vía del deep fake vedado por la legislación electoral. El plazo dado por Moraes venció y el panel aguarda la decisión siguiente.`,

  'cards.stf.dino': `Sin acto nuevo este jueves. Sigue corriendo el plazo de 10 días que dio el 29 de julio para que gobierno y Congreso especifiquen la responsabilidad de parlamentarios sobre enmiendas parlamentarias, con la señal de que un parlamentario puede ser sancionado por no fiscalizar una enmienda que él mismo indicó.`,

  'cards.stf.mendonca': `Sigue como relator de la investigación abierta el 23 de julio sobre las transferencias de Vorcaro para la película sobre Jair Bolsonaro. Sobre el rastreo patrimonial en el exterior, los dos ajustes de registro siguen valiendo: la decisión fue firmada en MAYO y solo se hizo pública el 28 de julio, y la investigación dejó de ser fuente única a partir del 29 de julio. Ningún acto nuevo este jueves.`,

  'cards.stf.nexo': `El nexo del jueves es el mismo de los dos días anteriores, inteligencia artificial en campaña, pero ahora el movimiento partió de un PARTIDO y no de un ministro. La Federación Brasil de la Esperanza, que reúne a PT, PCdoB y PV, presentó en el ${G('es', 'tse', 'TSE')} una representación de más de 200 páginas contra una red de 31 perfiles que, SEGÚN ALEGA LA FEDERACIÓN, usa inteligencia artificial para atacar a Lula. Los números de la petición, todos atribuidos a la federación y no verificados de forma independiente por el panel, son 1.464.245 seguidores sumados, 23.828 publicaciones y un alcance estimado en 10 millones de cuentas, con impulso atribuido a Flávio Bolsonaro y a otros políticos. Los pedidos son de remoción de URL, levantamiento del anonimato de los responsables y suspensión de la monetización (Metrópoles, CNN Brasil, Migalhas). Es el tercer día consecutivo en que el eje institucional del panel es el uso de inteligencia artificial en campaña, y la novedad estructural es que la disputa dejó de ser solo entre el STF y una defensa: ahora hay un partido como autor en el TSE.`,

  'cards.stf.analise': `El mercado de impeachment de ministro del ${G('es', 'stf', 'STF')} antes de 2027 CAYÓ 0,25pp y fue a 3,10% (vol USD 83.000), deshaciendo parte del alza de 0,55pp de ayer. La salvedad de método viene antes de la lectura y es la de siempre: 0,25pp en un book de USD 83.000, contra USD 116,58M del presidencial, es poquísimo dinero, y no autoriza a hablar de revaluación de riesgo en ninguna dirección. Hecha la salvedad, lo que interesa es el DESAJUSTE. El día tuvo acumulación institucional relevante, con un partido presentando en el ${G('es', 'tse', 'TSE')} una representación de más de 200 páginas sobre uso de inteligencia artificial en campaña, y el precio anduvo hacia el lado contrario. El 29 de julio el panel registró la dirección del precio acompañando la acumulación; hoy la contraría. Dos días, dos direcciones, movimiento neto de 0,30pp hacia arriba. La lectura honesta es que este book no tiene tamaño para responder al noticiario institucional, y que intentar leer causa en él en cualquiera de las dos direcciones sería construir narrativa sobre ruido. El panel registra los números y se detiene ahí.`,
}

construir('analysis-data', 'en', EN)
construir('analysis-data', 'es', ES)
