/** Mapa ES da correção de data — analysis-data.json e polls-data.json, 02/Ago/2026. */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/es/glossary#${id})`

construir('analysis-data', 'es', {
  'cards.sentimento.text2':
    `El cruce del día invierte el mecanismo de los dos anteriores. Lula quedó ESTANCADO en 65,50% y la brecha se ABRIÓ de +40,75pp a +40,95pp, pero se abrió porque FLÁVIO CAYÓ 0,20pp, y no porque el favorito subiera. En las dos jornadas anteriores el récord venía con el rival subiendo también; hoy es al revés, y la diferencia importa para la lectura. El techo de la serie quedó atrás y la ventana debe decirse entera: el máximo es 66,50%, del cierre del 1/Ago, y la brecha máxima es +41,80pp del mismo día, ambos por encima de lo que el panel muestra hoy. La serie del AFOS cubre del 14/Abr a hoy, 108 días, y fue verificada directamente contra la base de datos. RENAN SANTOS es el movimiento del día: SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M), INTERRUMPIENDO una racha de caídas que duraba nueve rondas. NO hubo evento suyo en la fecha: Missão oficializó la candidatura el 20/Jul, en convención adelantada, e hizo el evento de lanzamiento de campaña el 1/Ago. El alza de hoy es movimiento de mercado sin hecho nuevo que acompañar.`,
  'cards.sentimento.direita':
    `Flávio CAYÓ 0,20pp hasta 24,55% (vol USD 7,82M), interrumpiendo seis jornadas sin caída, y fue su caída la que ABRIÓ la brecha hasta +40,95pp, porque Lula quedó quieto. En los submercados la señal va al revés, y el panel no elige entre las dos: SUBE 1,00pp en el segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, hasta 80,50% (vol USD 217 mil), su mayor marca en ese contrato en el seguimiento del panel, y queda prácticamente quieto en el tercer lugar, en 4,90%. Cede en la probabilidad de ganar y sube en la de llegar a la ${G('segunda vuelta', 'segundo-turno')}, en la misma jornada. En el armado de la fórmula, sigue SIN candidato a vice a tres días del plazo del 5/Ago. Valor Econômico registra que él y Lula llegaron al tramo final de las convenciones sin ampliar alianzas, con el ${G('Centrão', 'centrao')} todavía neutral, y la convención nacional de ${G('Republicanos', 'republicanos')}, que decide la alianza presidencial, es el 4/Ago. HOY FUE A PARAÍBA: estuvo en la convención ESTATAL del ${G('PL', 'pl')} en João Pessoa, que lanzó a Efraim Filho al gobierno y a Marcelo Queiroga al Senado, en una estrategia declarada de ampliar su presencia en el Nordeste, que es el reducto histórico del adversario. El 1/Ago, en la convención del PL en Santa Catarina, había pedido votos antes del plazo legal, que solo se abre el 16/Ago.`,
  'cards.sentimento.esquerda':
    `Lula quedó ESTANCADO en 65,50% (vol USD 7,90M) el día en que el ${G('PT', 'pt')} oficializó su candidatura. La brecha se ABRIÓ hasta +40,95pp por caída del rival, y no por alza propia, lo que cambia el mecanismo respecto de las dos jornadas anteriores. El precio de hoy está 1,00pp POR DEBAJO del techo de la serie, que es 66,50%, del cierre del 1/Ago. La convención nacional del PT, en el Expo Center Norte de São Paulo, homologó la fórmula con Alckmin como vice y reunió a SIETE partidos (PT, PCdoB, PV, PSB, PDT, PSOL y Rede), la mayor coalición de izquierda y centroizquierda desde 1989, en la octava vez que Lula es candidato a la presidencia y en la búsqueda del cuarto mandato. Según Folha de S.Paulo, dijo que no quiere ser el presidente del Bolsa Família y prometió disputar las enmiendas con el Congreso. El pedido de votos antes del plazo legal fue el 1/AGO, en la convención de Bahía, y Flávio hizo lo mismo el mismo día, en Santa Catarina. En su campo el mercado subió: Camilo Santana ganó 0,20pp hasta 0,65%, y Haddad ganó 0,05pp hasta 0,30%. Alckmin quedó estancado en 0,35%. En el eje judicial, las dos investigaciones sobre Lulinha agudizaron la tensión entre Mendonça y la Policía Federal, su abogado acusa a sectores de la ${G('PF', 'pf')} de intentar interferir en la elección, y Roberta Luchsinger pidió que se investigue una filtración de conversaciones. Una investigación no es una condena.`,
  'cards.inss.text1':
    `La agenda fiscal no tuvo novedad este domingo, y el Congreso vuelve esta semana, junto con el regreso del ${G('STF', 'stf')} y el plazo final de las fórmulas el 5/Ago. El día político fue de la CONVENCIÓN NACIONAL DEL ${G('PT', 'pt')}. El partido oficializó a Lula en São Paulo, en el Expo Center Norte, con Alckmin como vice y SIETE partidos en la coalición (PT, PCdoB, PV, PSB, PDT, PSOL y Rede), la mayor de la izquierda y del centroizquierda desde 1989, en su octava candidatura a la presidencia. Flávio Bolsonaro estuvo en la convención ESTATAL del ${G('PL', 'pl')} en Paraíba, en João Pessoa, que lanzó a Efraim Filho al gobierno y a Marcelo Queiroga al Senado, en una estrategia declarada de ampliar su presencia en el Nordeste. Missão había lanzado a Renan Santos el 1/Ago, y en ese mismo 1/Ago Lula y Flávio pidieron votos antes del plazo legal, que solo se abre el 16/Ago, y el registro es de los dos, no de uno. Valor Econômico resume el saldo del ciclo de convenciones: los dos llegaron al tramo final sin ampliar alianzas, y el ${G('Centrão', 'centrao')} sigue neutral.`,
  'cards.inss.text2':
    `El mercado invirtió el mecanismo de las dos jornadas anteriores. Lula quedó ESTANCADO en 65,50% y la brecha se ABRIÓ hasta +40,95pp, pero se abrió por caída de Flávio, que cedió 0,20pp y fue a 24,55%, interrumpiendo seis jornadas sin caída. En los dos días anteriores la brecha se abría con el rival subiendo también, y hoy es al revés. El techo de la serie quedó atrás: el máximo es 66,50%, del cierre del 1/Ago, y el precio de hoy está 1,00pp por debajo. RENAN SANTOS SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M), interrumpiendo nueve rondas de caída, y sin evento suyo en la fecha: la convención que lo oficializó fue el 20/Jul y el lanzamiento de campaña el 1/Ago. El pelotón se dividió: Camilo Santana y Jair Bolsonaro subieron, Caiado y Zema cayeron. La asimetría del día es la misma de la víspera: nada de esto tuvo encuesta nacional para acompañarlo, y la última sigue siendo la de Vox Brasil del 31/Jul.`,
  'cards.inss.conclusao':
    `A 63 días de la elección, el día fue de la convención nacional del ${G('PT', 'pt')} y de inversión de mecanismo en el mercado. El favorito quedó quieto en 65,50% y la brecha se abrió hasta +40,95pp porque el rival cayó, al contrario de las dos jornadas anteriores, en que la brecha se abría con los dos subiendo. El techo de la serie quedó atrás, y es de ayer: 66,50%. El movimiento del día fue de Renan Santos, que subió 0,35pp e interrumpió nueve rondas de caída SIN evento suyo en la fecha, porque la convención que lo oficializó fue el 20/Jul y el lanzamiento de campaña el 1/Ago. En la política, el PT oficializó a Lula con Alckmin en São Paulo, reuniendo a siete partidos, y Flávio fue a la convención estatal del ${G('PL', 'pl')} en Paraíba. El pedido de votos antes del plazo legal, de los dos, fue el 1/Ago. Flávio y Zema siguen sin vice a tres días del plazo. Ninguna de estas lecturas se atribuye a una causa, y en el caso de Renan no hay ni coincidencia de fechas que registrar: el precio se movió en un día en que no hubo encuesta ni evento suyo.`,
  'cards.stf.moraes':
    `Sin resolución nueva de Moraes capturada este domingo. Permanece el cuadro de restricciones sobre la comunicación de Jair Bolsonaro en prisión domiciliaria, que ya alcanzaba la divulgación de manifiestos político-electorales por terceros. En el plano personal de la familia, autorizó a la cuñada a cuidar de Jair Bolsonaro mientras Michelle pasaba por exámenes en Brasilia.`,
  'cards.stf.nexo':
    `El nexo de este domingo es la CONVENCIÓN NACIONAL DEL ${G('PT', 'pt')}, y el eje judicial entra por la fricción institucional. El partido oficializó a Lula con Alckmin en São Paulo, reuniendo a SIETE partidos (PT, PCdoB, PV, PSB, PDT, PSOL y Rede), la mayor coalición de izquierda y centroizquierda desde 1989. Flávio Bolsonaro estuvo en la convención ESTATAL del ${G('PL', 'pl')} en Paraíba, en João Pessoa, en una estrategia declarada de ampliar su presencia en el Nordeste. Missão había lanzado a Renan Santos el 1/Ago, y en ese mismo 1/Ago Lula y Flávio pidieron votos antes del plazo legal, que se abre el 16/Ago. Flávio y Zema siguen sin vice a tres días del plazo del 5/Ago, y la convención nacional de ${G('Republicanos', 'republicanos')}, que trata la alianza presidencial, es el 4/Ago. En el eje judicial, lo que se extiende desde el 31/Jul es la tensión entre Mendonça y la Policía Federal en torno a las investigaciones sobre Lulinha, con su abogado acusando a sectores de la ${G('PF', 'pf')} de intentar interferir en la elección.`,
})

construir('polls-data', 'es', {
  'polymarketComparison.note':
    `Cruce del 2/Ago, captura trabada de las 19:42 UTC: la brecha se abrió por el OTRO lado. Lula quedó ESTANCADO en 65,50% (vol USD 7,90M) y la brecha sobre Flávio se ABRIÓ hasta +40,95pp, frente a +40,75pp en la captura publicada el 1/Ago, pero se abrió porque FLÁVIO CAYÓ 0,20pp, y no porque el favorito subiera. En las dos jornadas anteriores la brecha se abría con el rival subiendo también; hoy es al revés. EL TECHO DE LA SERIE QUEDÓ ATRÁS: el máximo de Lula es 66,50% y el de la brecha es +41,80pp, ambos del CIERRE del 1/Ago, y ambos por encima de lo que este panel publica hoy. La serie cubre del 14/Abr al 2/Ago, 108 días, verificada directamente contra la base. RENAN SANTOS es el movimiento del día: SUBIÓ 0,35pp hasta 7,95% (vol USD 8,82M), INTERRUMPIENDO nueve rondas de caída, y SIN evento suyo en la fecha: Missão oficializó la candidatura el 20/Jul e hizo el lanzamiento de campaña el 1/Ago. Con su encuesta quieta en 3,0%, la distancia entre mercado y encuesta VOLVIÓ A ABRIRSE, de 4,60pp a 4,95pp, por el lado del precio. El pelotón se DIVIDIÓ: Camilo Santana, Jair Bolsonaro y Haddad subieron, mientras Caiado, Zema, Michelle y Tereza Cristina cayeron. CAIADO tocó el piso de la serie dentro del propio día, con 0,90% en la recolección de las 11:30 UTC, que iguala el menor valor desde el 14/Abr, y 1,15% en la captura trabada. SIN ENCUESTA NUEVA: la última nacional sigue siendo la de Vox Brasil del 31/Jul (n=2.100, campo del 26 al 28/Jul, margen de 2,15pp, BR-01084/2026), y cuatro nacionales publican entre el 3 y el 5/Ago. En el día político, el ${G('PT', 'pt')} oficializó a Lula con Alckmin en São Paulo, reuniendo a siete partidos, mientras Flávio estuvo en la convención ESTATAL del ${G('PL', 'pl')} en Paraíba. El pedido de votos antes del plazo legal, de los dos, fue el 1/Ago, y los dos siguen sin ampliar alianzas, con el ${G('Centrão', 'centrao')} neutral. La traba de doble lectura APROBÓ la ronda sin ningún motivo de bloqueo. Todos los precios entran firmes, sin rango declarado. Captura en vivo del 2/Ago a las 19:42 UTC.`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `La de Vox Brasil del 31/Jul (n=2.100, campo del 26 al 28/Jul, margen de 2,15pp, BR-01084/2026) lo trae en 31,2% en la ${G('primera vuelta', 'primeiro-turno')} y 41,1% en la ${G('segunda vuelta', 'segundo-turno')}. Los 6,4pp que lo separan de Lula quedan fuera del margen sumado, lo que descarta la lectura de ${G('empate técnico', 'empate-tecnico')} que PoderData sostenía el 30/Jul. Sin encuesta nacional nueva desde entonces, con cuatro en campo y publicación declarada entre el 3 y el 5/Ago. En el armado de la fórmula, sigue SIN vice a tres días del plazo del 5/Ago, después de que el PP declarara neutralidad y vetara la fórmula con Tereza Cristina, y Valor Econômico registra que él y Lula llegaron al tramo final de las convenciones sin ampliar alianzas, con el ${G('Centrão', 'centrao')} todavía neutral. La convención nacional de ${G('Republicanos', 'republicanos')}, que decide la alianza presidencial, es el 4/Ago. Este domingo estuvo en la convención ESTATAL del ${G('PL', 'pl')} en Paraíba, en João Pessoa, que lanzó a Efraim Filho al gobierno y a Marcelo Queiroga al Senado, en una estrategia declarada de ampliar su presencia en el Nordeste. El 1/Ago, en la convención del PL en Santa Catarina, había pedido votos antes del plazo legal, que solo se abre el 16/Ago.`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `TRES institutos seguidos lo recortaron, y es la secuencia lo que importa, no el número aislado: 7,8% en AtlasIntel del 29/Jul, 4% en PoderData del 30/Jul y 3,0% en Vox Brasil del 31/Jul. No hubo encuesta nacional nueva desde entonces, pero el precio se movió: con el mercado ahora en 7,95%, la distancia entre mercado y encuesta VOLVIÓ A ABRIRSE, de 4,60pp a 4,95pp, y se abrió por el lado del precio, del mismo modo en que se había cerrado. El 29/Jul este panel registró esa misma distancia en 0,90pp y la llamó convergencia; se cuadruplicó, retrocedió y ahora vuelve a abrirse, y queda registrado que la lectura del 29/Jul no se sostuvo. Missão oficializó su candidatura el 20/Jul e hizo el evento de lanzamiento de campaña el 1/Ago, cuando atacó a Lula y a Flávio, llamó vasallo a Moro, dijo que va a sacar a Flávio de la ${G('segunda vuelta', 'segundo-turno')} y prometió matar a quien robe.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `SUBE 0,35pp hasta 7,95% (vol USD 8,82M), INTERRUMPIENDO una racha de caídas que duraba nueve rondas. NO hubo evento suyo en la fecha: Missão oficializó la candidatura el 20/Jul, en convención adelantada, e hizo el evento de lanzamiento de campaña el 1/Ago. El alza de hoy es movimiento de mercado sin hecho nuevo que acompañar. El alza fue general en sus tres libros: 0,20pp en el segundo lugar de la ${G('primera vuelta', 'primeiro-turno')}, hasta 8,75%, y 2,00pp en el tercer lugar, hasta 63,50%, donde es favorito aislado. El giro NO deshace el arco: venía de 12,00% el 23/Jul y tocó 7,10% en el cierre del 1/Ago. No es mínimo de serie, que es 5,30%, del 26/Abr, ni máximo, que es 17,90%, del 9/Jun.`,
})
