/** Mapa EN da correção de data — analysis-data.json, 02/Ago/2026. */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/en/glossary#${id})`

construir('analysis-data', 'en', {
  'cards.sentimento.text2':
    `Today's cross-reading inverts the mechanism of the two before it. Lula held FLAT at 65.50% and the gap WIDENED from +40.75pp to +40.95pp, but it widened because FLÁVIO FELL 0.20pp, not because the favourite rose. In the two previous sessions the record came with the rival rising alongside; today it is the opposite, and the difference matters for the reading. The series high is now behind us, and the window has to be stated in full: the maximum is 66.50%, from the Aug 1 close, and the maximum gap is +41.80pp from that same day, both above what the panel shows today. The AFOS series runs from Apr 14 to today, 108 days, and was checked straight against the database. RENAN SANTOS is the move of the day: UP 0.35pp to 7.95% (vol USD 8.82M), BREAKING a losing streak that had lasted nine rounds. There was NO event of his on the date: Missão confirmed the candidacy on Jul 20, at a convention brought forward, and held the campaign launch event on Aug 1. Today's rise is market movement with no fresh fact to track.`,
  'cards.sentimento.direita':
    `Flávio FELL 0.20pp to 24.55% (vol USD 7.82M), breaking six sessions without a decline, and it was his fall that WIDENED the gap to +40.95pp, because Lula stood still. In the sub-markets the signal runs the other way, and the panel does not pick between them: he is UP 1.00pp in second place in the ${G('first round', 'primeiro-turno')}, at 80.50% (vol USD 217K), his highest mark in that contract over the panel's coverage, and effectively flat in third place, at 4.90%. He gives ground on the chance of winning and gains on the chance of reaching the ${G('runoff', 'segundo-turno')}, in the same session. On the ticket, he still has NO running mate three days from the Aug 5 deadline. Valor Econômico records that he and Lula reached the final stretch of the convention season without broadening alliances, with the ${G('Centrão', 'centrao')} still neutral, and the ${G('Republicanos', 'republicanos')} national convention, which decides the presidential alliance, is on Aug 4. TODAY HE WENT TO PARAÍBA: he attended the ${G('PL', 'pl')} STATE convention in João Pessoa, which launched Efraim Filho for governor and Marcelo Queiroga for the Senate, in a stated strategy of widening his presence in the Northeast, the rival's historic stronghold. On Aug 1, at the PL convention in Santa Catarina, he had asked for votes ahead of the legal window, which only opens on Aug 16.`,
  'cards.sentimento.esquerda':
    `Lula held FLAT at 65.50% (vol USD 7.90M) on the day the ${G('PT', 'pt')} formally launched his candidacy. The gap WIDENED to +40.95pp through the rival's fall, not his own rise, which changes the mechanism relative to the two previous sessions. Today's price is 1.00pp BELOW the series high, which is 66.50%, from the Aug 1 close. The PT national convention, at the Expo Center Norte in São Paulo, formally approved the ticket with Alckmin as running mate and brought together SEVEN parties (PT, PCdoB, PV, PSB, PDT, PSOL and Rede), the largest left and centre-left coalition since 1989, in Lula's eighth run for the presidency and his bid for a fourth term. According to Folha de S.Paulo, he said he does not want to be the Bolsa Família president and promised to fight Congress over earmarks. The request for votes ahead of the legal window was on AUG 1, at the Bahia convention, and Flávio did the same on the same day, in Santa Catarina. In his camp the market rose: Camilo Santana gained 0.20pp to 0.65%, and Haddad gained 0.05pp to 0.30%. Alckmin held at 0.35%. On the judicial axis, the two inquiries into Lulinha sharpened the tension between Mendonça and the Federal Police, his lawyer accuses parts of the ${G('PF', 'pf')} of trying to interfere in the election, and Roberta Luchsinger asked for an investigation into leaked conversations. An inquiry is not a conviction.`,
  'cards.inss.text1':
    `The fiscal agenda had no fresh news this Sunday, and Congress returns this week, alongside the ${G('STF', 'stf')} coming back from recess and the Aug 5 deadline for ticket registration. The political day belonged to the ${G('PT', 'pt')} NATIONAL CONVENTION. The party formally launched Lula in São Paulo, at the Expo Center Norte, with Alckmin as running mate and SEVEN parties in the coalition (PT, PCdoB, PV, PSB, PDT, PSOL and Rede), the largest on the left and centre-left since 1989, in his eighth run for the presidency. Flávio Bolsonaro attended the ${G('PL', 'pl')} STATE convention in Paraíba, in João Pessoa, which launched Efraim Filho for governor and Marcelo Queiroga for the Senate, in a stated strategy of widening his presence in the Northeast. Missão had launched Renan Santos on Aug 1, and on that same Aug 1 Lula and Flávio asked for votes ahead of the legal window, which only opens on Aug 16, and the record covers both, not one. Valor Econômico sums up the balance of the convention season: the two reached the final stretch without broadening alliances, and the ${G('Centrão', 'centrao')} remains neutral.`,
  'cards.inss.text2':
    `The market inverted the mechanism of the two previous sessions. Lula held FLAT at 65.50% and the gap WIDENED to +40.95pp, but it widened through Flávio's fall, as he gave up 0.20pp to 24.55%, breaking six sessions without a decline. In the two days before, the gap widened with the rival rising alongside; today it is the reverse. The series high is now behind us: the maximum is 66.50%, from the Aug 1 close, and today's price is 1.00pp below it. RENAN SANTOS ROSE 0.35pp to 7.95% (vol USD 8.82M), breaking nine rounds of decline, and with no event of his on the date: the convention that confirmed him was on Jul 20 and the campaign launch on Aug 1. The chasing pack split: Camilo Santana and Jair Bolsonaro rose, Caiado and Zema fell. The asymmetry of the day is the same as yesterday's: none of it had national polling to track it, and the most recent remains Vox Brasil of Jul 31.`,
  'cards.inss.conclusao':
    `With 63 days to the election, the day belonged to the ${G('PT', 'pt')} national convention and to an inverted mechanism in the market. The favourite stood still at 65.50% and the gap widened to +40.95pp because the rival fell, unlike the two previous sessions, when the gap widened with both rising. The series high is now behind us, and it belongs to yesterday: 66.50%. The move of the day was Renan Santos, up 0.35pp and breaking nine rounds of decline WITH no event of his on the date, because the convention that confirmed him was on Jul 20 and the campaign launch on Aug 1. In politics, the PT launched Lula with Alckmin in São Paulo, bringing together seven parties, and Flávio went to the ${G('PL', 'pl')} state convention in Paraíba. The request for votes ahead of the legal window, by both, was on Aug 1. Flávio and Zema still have no running mates three days from the deadline. None of these readings is assigned a cause, and in Renan's case there is not even a coincidence of dates to record: the price moved on a day with neither polling nor an event of his.`,
  'cards.stf.moraes':
    `No new ruling from Moraes captured this Sunday. The framework of restrictions on Jair Bolsonaro's communications under house arrest remains in place, already covering the circulation of political and electoral manifestos by third parties. On the family's personal front, he allowed the sister-in-law to care for Jair Bolsonaro while Michelle underwent tests in Brasília.`,
  'cards.stf.nexo':
    `This Sunday's thread is the ${G('PT', 'pt')} NATIONAL CONVENTION, with the judicial axis entering through institutional friction. The party formally launched Lula with Alckmin in São Paulo, bringing together SEVEN parties (PT, PCdoB, PV, PSB, PDT, PSOL and Rede), the largest left and centre-left coalition since 1989. Flávio Bolsonaro attended the ${G('PL', 'pl')} STATE convention in Paraíba, in João Pessoa, in a stated strategy of widening his presence in the Northeast. Missão had launched Renan Santos on Aug 1, and on that same Aug 1 Lula and Flávio asked for votes ahead of the legal window, which opens on Aug 16. Flávio and Zema still have no running mates three days from the Aug 5 deadline, and the ${G('Republicanos', 'republicanos')} national convention, which deals with the presidential alliance, is on Aug 4. On the judicial axis, what carries over from Jul 31 is the tension between Mendonça and the Federal Police around the inquiries into Lulinha, with his lawyer accusing parts of the ${G('PF', 'pf')} of trying to interfere in the election.`,
})
