/** Mapa EN da correção de data — polls-data.json, 02/Ago/2026. */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/en/glossary#${id})`

construir('polls-data', 'en', {
  'polymarketComparison.note':
    `Cross-reading of Aug 2, locked capture at 19:42 UTC: the gap widened from the OTHER side. Lula held FLAT at 65.50% (vol USD 7.90M) and the gap over Flávio WIDENED to +40.95pp, against +40.75pp in the capture published on Aug 1, but it widened because FLÁVIO FELL 0.20pp, not because the favourite rose. In the two previous sessions the gap widened with the rival rising alongside; today it is the reverse. THE SERIES HIGH IS NOW BEHIND US: Lula's maximum is 66.50% and the gap maximum is +41.80pp, both from the Aug 1 CLOSE, and both above what this panel publishes today. The series runs from Apr 14 to Aug 2, 108 days, checked straight against the database. RENAN SANTOS is the move of the day: UP 0.35pp to 7.95% (vol USD 8.82M), BREAKING nine rounds of decline, and with NO event of his on the date: Missão confirmed the candidacy on Jul 20 and held the campaign launch on Aug 1. With his polling stuck at 3.0%, the distance between market and polling WIDENED AGAIN, from 4.60pp to 4.95pp, on the price side. The chasing pack SPLIT: Camilo Santana, Jair Bolsonaro and Haddad rose, while Caiado, Zema, Michelle and Tereza Cristina fell. CAIADO touched the series floor within the day itself, with 0.90% in the 11:30 UTC collection, matching the lowest value since Apr 14, and 1.15% in the locked capture. NO FRESH POLLING: the most recent national poll remains Vox Brasil of Jul 31 (n=2,100, fieldwork Jul 26 to 28, 2.15pp margin, BR-01084/2026), and four national polls publish between Aug 3 and Aug 5. On the political day, the ${G('PT', 'pt')} formally launched Lula with Alckmin in São Paulo, bringing together seven parties, while Flávio attended the ${G('PL', 'pl')} STATE convention in Paraíba. The request for votes ahead of the legal window, by both, was on Aug 1, and both remain without broader alliances, with the ${G('Centrão', 'centrao')} neutral. The double-reading lock PASSED the round with no blocking reason at all. All prices enter firm, with no declared range. Live capture Aug 2 at 19:42 UTC.`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `Vox Brasil of Jul 31 (n=2,100, fieldwork Jul 26 to 28, 2.15pp margin, BR-01084/2026) has him at 31.2% in the ${G('first round', 'primeiro-turno')} and 41.1% in the ${G('runoff', 'segundo-turno')}. The 6.4pp separating him from Lula fall outside the combined margin, which rules out the ${G('statistical tie', 'empate-tecnico')} reading PoderData supported on Jul 30. No fresh national polling since then, with four in the field and publication declared between Aug 3 and Aug 5. On the ticket, he still has NO running mate three days from the Aug 5 deadline, after the PP declared neutrality and vetoed the ticket with Tereza Cristina, and Valor Econômico records that he and Lula reached the final stretch of the convention season without broadening alliances, with the ${G('Centrão', 'centrao')} still neutral. The ${G('Republicanos', 'republicanos')} national convention, which decides the presidential alliance, is on Aug 4. This Sunday he attended the ${G('PL', 'pl')} STATE convention in Paraíba, in João Pessoa, which launched Efraim Filho for governor and Marcelo Queiroga for the Senate, in a stated strategy of widening his presence in the Northeast. On Aug 1, at the PL convention in Santa Catarina, he had asked for votes ahead of the legal window, which only opens on Aug 16.`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `THREE institutes in a row cut him, and it is the sequence that matters, not the isolated figure: 7.8% in AtlasIntel of Jul 29, 4% in PoderData of Jul 30 and 3.0% in Vox Brasil of Jul 31. There has been no fresh national polling since then, but the price moved: with the market now at 7.95%, the distance between market and polling WIDENED AGAIN, from 4.60pp to 4.95pp, and it widened on the price side, the same way it had closed. On Jul 29 this panel recorded that same distance at 0.90pp and called it convergence; it quadrupled, receded and is now widening again, and it is on record that the Jul 29 reading did not hold. Missão confirmed his candidacy on Jul 20 and held the campaign launch event on Aug 1, when he attacked Lula and Flávio, called Moro a vassal, said he will knock Flávio out of the ${G('runoff', 'segundo-turno')} and promised to kill whoever steals.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `RISES 0.35pp to 7.95% (vol USD 8.82M), BREAKING a losing streak that had lasted nine rounds. There was NO event of his on the date: Missão confirmed the candidacy on Jul 20, at a convention brought forward, and held the campaign launch event on Aug 1. Today's rise is market movement with no fresh fact to track. The rise was general across all three of his books: 0.20pp in second place in the ${G('first round', 'primeiro-turno')}, to 8.75%, and 2.00pp in third place, to 63.50%, where he is the outright favourite. The turn does NOT undo the arc: he came from 12.00% on Jul 23 and touched 7.10% at the Aug 1 close. It is not a series low, which is 5.30%, from Apr 26, nor a high, which is 17.90%, from Jun 9.`,
})
