/**
 * Limpeza EN de 04/Ago: tira o relato de falha da máquina do texto de leitor.
 * Regra do André, de 03/Ago, que eu quebrei em 04/Ago ao justificar por que o
 * preço era de ontem. "Os preços são da leitura de 03/Ago" basta.
 */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/en/glossary#${id})`
const NEXUS = G('BTG/Nexus', 'nexus-btg')
const STF = G('STF', 'stf')
const NOVO = G('Novo', 'novo')
const PF = G('Federal Police', 'pf')

construir('analysis-criteriosa', 'en', {
  subtitle:
    `UPDATE Aug 4, 18:30, 61 days from the first round. ⚠️ THE POLLING SIDE IS FROM TODAY, THE MARKET SIDE IS FROM YESTERDAY: the prices on this page come from the Aug 3 reading, at 19:11 UTC, and each one is marked. The polling is from today. THE FRESH DATA IS APPROVAL: ${NEXUS} released today, from the same round as yesterday, 47% government approval against 48% disapproval, and approval has been stuck at 47% for three rounds of the house. On the board, ZEMA ANNOUNCED HIS RUNNING MATE, Senator Eduardo Girão of the ${NOVO} party, and FLÁVIO TOOK TWO REFUSALS, from Republicanos and Podemos, leaving him without one.`,
  'candidates[0].header':
    `Price from Aug 3: ${G('Polymarket', 'polymarket')} 65.50% (vol USD 7.92M accumulated), from the 19:11 UTC reading. There is no fresh market reading on Aug 4. Today's data point is APPROVAL: 47% against 48% disapproval in ${NEXUS}, stuck at 47% for three rounds of the house.`,
  'candidates[0].analise':
    `His day is one of fresh approval data and an unpublished price, and the two things need to be said separately. THE APPROVAL came out today, from the same ${NEXUS} round as yesterday (n=2,002, fieldwork Jul 31 to Aug 2, BR-02874/2026): 47% approve of the government and 48% disapprove. The finding is not the level, it is the STILLNESS: inside the house itself, approval stands at 47% across the last three rounds, Jul 13, Jul 27 and now, and what oscillated was disapproval, from 47% to 49% and back to 48%, always inside the 2pp margin. A series that does not move across three readings describes a divided and stable electorate, not a trend. On ADMINISTRATION RATINGS, which is a different question and does not mix with approval, it is 37% excellent or good, 18% average and 43% poor or terrible, against 36% and 43% on Jul 27. Also still. ⚠️ The panel CHANGED SOURCE on this field, which through yesterday carried the Jul 29 reading, and therefore publishes no variation against it: comparing different houses would be changing the yardstick mid-measurement. PoderData/Aya of Jul 30, the other recent reading, gives a considerably harsher picture, 43% x 49%. The two keep pointing different ways. THE PRICE DOES NOT ENTER TODAY: what the panel publishes is the Aug 3 reading, with him at 65.50% and a gap of +40.05pp. In his camp, the ${PF} had a full day: Dino AUTHORISED the third inquiry into Lulinha and opened an investigation into leaks, and Lula himself told an aide to explain a loan taken from a friend of Lulinha under investigation. The panel records the facts and attributes no electoral effect.`,
  'candidates[1].header':
    `Price from Aug 3: ${G('Polymarket', 'polymarket')} 25.45% (vol USD 7.86M accumulated), from the 19:11 UTC reading. On Aug 4 he took TWO alliance refusals, from Republicanos and Podemos, and remains without a running mate eleven days from the deadline he himself declared.`,
  'candidates[1].analise':
    `His day was one of party isolation, and that is a recorded fact, not a reading. REPUBLICANOS confirmed neutrality in the election and refused to join the ticket, and Folha de S.Paulo describes the move as widening his isolation. Podemos then also refused support and decided to stay neutral, after resisting the nomination of its own president, Renata Abreu, as running mate. He remains WITHOUT A RUNNING MATE and said the decision will come by August 15, which gives eleven days. Michelle Bolsonaro called Ciro Nogueira to press for Tereza Cristina in the slot, and Daniella Marques, the previous bet, will stay on the campaign as an adviser after Republicanos withheld its approval. IN THE POLLING HE IS STILL THE MOVE OF THE WEEK: ${NEXUS} of Aug 3 took him from 33% to 37% in the first round, a 4pp rise that is double the margin, and from 43% to 45% in the runoff, 1pp behind Lula. But the house caveat still holds: the other three national polls since Jul 29 give gaps of 6pp to 9.3pp, against 4pp here. THE PRICE DOES NOT ENTER TODAY. What the panel publishes is the Aug 3 reading, with him at 25.45%. The crossing left open for tomorrow is exactly this one: he rose in the polling and lost two parties at the same time, and neither has yet passed through a confirmed price.`,
  'candidates[3].header':
    `Prices from Aug 3: Caiado 1.15% (vol USD 5.30M), Zema 0.25% (vol USD 4.66M) and Haddad 0.15% (vol USD 6.64M). ⚠️ THIS IS PRECISELY WHERE the price moves most on Aug 4, and that is why this round publishes no fresh figure for them.`,
  'candidates[3].analise':
    `The third way had its busiest day of the cycle, and that is where the price moves most, which is no coincidence. ZEMA ANNOUNCED HIS RUNNING MATE: Senator Eduardo Girão of the ${NOVO} party, confirmed by Folha, O Globo and G1. He is the first of the three to close a ticket, and he closes it inside his own party, without depending on an alliance. CAIADO, formally nominated yesterday, appears today as the name whose price moves most, and this round publishes no fresh figure for him. Worth recording what that means as method: a book moving like that is being repriced right now, and publishing a snapshot of it would be publishing an instant, not a price. HADDAD remains at 0.15% and remains a non-candidate, so that contract prices a replacement scenario. IN THE POLLING, ${NEXUS} of Aug 3 gives Caiado 5% and Zema 3%, and Lula beats both in the runoff, 46% x 42% and 46% x 40%. THE CROSSING THAT MATTERS: the third-way space gained party definition today, with Zema closing a ticket and with Republicanos and Podemos stepping off Flávio's platform, and none of it has yet passed through a price the panel can publish. That is what tomorrow's round will measure.`,
  'quadroComparativo[0].t':
    `⚠️ NO FRESH READING ON Aug 4. What stands is the Aug 3 reading, 19:11 UTC, with a gap of +40.05pp.`,
  'quadroComparativo[1].t':
    `⚠️ NO FRESH READING ON Aug 4. A series caveat that still holds: his peak is 45.20% on May 7 and his floor is 22.00% on Jul 3.`,
  'quadroComparativo[2].t':
    `⚠️ NO FRESH READING ON Aug 4. In yesterday's he had fallen 0.50pp, undoing the previous day's rise.`,
  'quadroComparativo[3].t':
    `⚠️ HE IS THE NAME WHOSE PRICE MOVES MOST on Aug 4, and that is why this round publishes no fresh figure for him.`,
  'quadroComparativo[4].t':
    `⚠️ NO FRESH READING ON Aug 4. His price had been rising through the day, and this round does not publish a figure that is not confirmed.`,
  'quadroComparativo[5].t':
    `⚠️ NO FRESH READING ON Aug 4. It was at 3.10% in yesterday's.`,
  cruzamento:
    `THIS ROUND PUBLISHES HALF THE CROSSING, AND SAYS WHICH HALF. The POLLING side is from today. The MARKET side is from yesterday, from the Aug 3 reading at 19:11 UTC. The third way is where the price moved most on Aug 4, and that is where this round publishes no fresh figure: AFOS only publishes a price that two independent readings confirm. --- THE FRESH DATA OF THE DAY IS APPROVAL, and it came from yesterday's round. ${NEXUS} released, in the Aug 4 coverage and from the SAME round BR-02874/2026, government approval at 47% against 48% disapproval. ⚠️ The panel corrects here a statement it published yesterday: the entry for that round said it had carried no approval figures, and it had. The correction is declared in the entry itself, rather than rewritten in silence. --- THE FINDING IS NOT THE LEVEL, IT IS THE STILLNESS. Inside ${NEXUS} itself, approval stands at 47% across the LAST THREE rounds: 47% x 47% on Jul 13, 47% x 49% on Jul 27 and 47% x 48% now. What oscillated was disapproval, and it oscillated 2pp up and 1pp down, inside the margin both times. Three readings without movement describe a divided and stable electorate, not a trend. Administration ratings tell the same story: 37% excellent or good against 43% poor or terrible, versus 36% and 43% on Jul 27. ⚠️ And the panel CHANGED SOURCE on this field, which through yesterday carried the Jul 29 reading, so it publishes no variation against it: comparing different houses is changing the yardstick mid-measurement. PoderData/Aya of Jul 30 still gives a considerably harsher picture, 43% x 49%, and the two houses keep pointing different ways. --- THE PARTY BOARD MOVED MORE THAN THE POLLING DID. ZEMA announced his running mate, Senator Eduardo Girão of the ${NOVO} party, and is the first of the three third-way names to close a ticket, and inside his own party at that. FLÁVIO took TWO refusals on the same day, from Republicanos and Podemos, both confirming neutrality, and remains WITHOUT A RUNNING MATE eleven days from the deadline he himself declared, August 15. That is the combination tomorrow will measure: he gained 4pp in the ${NEXUS} polling and lost two parties in the same week, and neither has yet passed through a price this panel can publish. --- ON THE JUDICIAL AXIS, yesterday's request became today's decision: DINO AUTHORISED the third inquiry into Lulinha and opened an investigation into leaks. The panel recorded yesterday that the ${PF} had REQUESTED it, and keeps the distinction between requesting and opening, because that is what separates the news from the fact. Lula told an aide to explain a loan taken from a friend of Lulinha under investigation. With no confirmed price today, there is no way to measure whether the market priced any of it, and the panel says so rather than estimating.`,
})
