/**
 * Mapa EN de 15/Ago para polls-data.json.
 * Convenções: ponto decimal, vírgula de milhar, datas no formato "Aug 15".
 */
import { construir } from '../build-locale-json'

const NOVO = 'confirmed reading of Aug 15, 13:33 BRT (16:33 UTC)'
const SEM = 'THERE IS NO NEW CONFIRMED READING FOR HIM ON Aug 15. The value displayed is that of the last confirmed reading, from Aug 14, 14:46 BRT'

construir('polls-data', 'en', {
  'polls[0].method': `In person, 120 municipalities`,
  'polls[0].note':
    `Genial/Quaest national poll released Aug 14 at 21:00 (G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, Correio Braziliense). First round Lula 38% x Flávio Bolsonaro 31%, a distance of 7pp. Runoff Lula 43% x Flávio 40%, 3pp, with a 2pp margin. ⭐ THE COMPARISON THAT COUNTS IS WITH THE HOUSE ITSELF, AND IT IS SYMMETRICAL: against Quaest of Aug 5, the first round went from 39% x 30% to 38% x 31% and the runoff went from 44% x 39% to 43% x 40%. In both rounds Lula gave up 1 point and Flávio gained 1 point, and each distance narrowed by 2pp. Same house, same in-person method and same sample. REJECTION separated for the first time in the window: Flávio 54%, Lula 52% and Caiado 35%, the last with high non-recognition declared by the house. GOVERNMENT APPROVAL at 46% against 48% disapproval, a technical tie by the margin. ⚠️ The TSE records fieldwork as Aug 10 to Aug 13 and the house published Aug 10 to Aug 12; the panel displays the registered period.`,
  'polls[0].source':
    `Genial/Quaest via G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney and Correio Braziliense, Aug 14`,

  'approvalData.note':
    `NEW NATIONAL POLL ON Aug 14, released at 21:00. Genial/Quaest: 46% approve and 48% disapprove of the Lula government, a net 2pp negative and a technical tie by the 2pp margin, against 43% x 50% from PoderData/Aya of Aug 13, which was the pair in force. ⚠️ THAT IS TWO HOUSES TWO DAYS APART WITH 5 POINTS OF DIFFERENCE IN THE NET, and the panel does not choose between them: the distance between houses is the finding. REJECTION in Quaest: Flávio Bolsonaro 54%, Lula 52% and Ronaldo Caiado 35%, the last with high non-recognition declared by the house. It is the first national poll of the window to SEPARATE the top two on that indicator, after PoderData had tied them at 48%. Still in the table are Gerp of Aug 11 with 53% disapproval, BTG/Nexus of Aug 10 with 46% x 49%, Palver from the same day with 45% x 55% and Genial/Quaest of Aug 5 with 48% x 47%. WHAT THE SET SHOWS: across nine readings over ten days, disapproval runs from 47% to 55%, a spread of 8pp between houses, and the net runs from 1pp positive to 10pp negative. No house changed sides. ⚠️ PROVENANCE DECLARED: approval and disapproval are from Genial/Quaest of Aug 14 (fieldwork Aug 10 to Aug 13, n=2,004, in person, margin 2pp, registration BR-06773/2026), as the most recent national reading; the remaining 6% is the arithmetic residue between the two published values. The government-performance breakdown, at 36% positive, 26% average and 36% negative, is still the one from Genial/Quaest of Aug 5, because the new round did not publish that full breakdown in the reports captured. The panel prefers to declare the mix rather than hide it.`,
  'approvalData.source':
    `Approval and disapproval: Genial/Quaest Aug 14, 2026 (fieldwork Aug 10 to Aug 13, n=2,004, in person across 120 municipalities, margin 2.0pp, TSE registration BR-06773/2026), released by G1, CNN Brasil, Estadão, Correio Braziliense and Poder360. Rejection: same round, via G1, Poder360, InfoMoney and O Globo. Government-performance breakdown (very good/good, average, bad/very bad): Genial/Quaest Aug 5, 2026, because the Aug 14 round did not carry that breakdown in the reports captured.`,

  'polymarketComparison.note':
    `UPDATE OF Aug 15. THE CROSSING OF THE DAY POINTS IN OPPOSITE DIRECTIONS. In the polls, Quaest released on Aug 14 at 21:00 shows both distances NARROWING against the house's own previous round: the first round went from 9pp to 7pp and the runoff from 5pp to 3pp, with a symmetrical movement of 1 point on each side in both cases. On price the opposite happened: the distance WIDENED, from 35.65pp to 36.35pp, because the leader rose 1.00pp and the runner-up rose 0.30pp. ⭐ The two instruments moved over the same pair of days and in opposite directions, and that divergence is the finding. The leader broke through 63.50%, where he had stood since Aug 9, and returned to the level of Aug 8. ⛔ No superlative: among the 174 points recorded since May 18, 17 had a value equal to or above 64.50%, and among the 88 days with a recorded gap, 32 had a distance equal to or greater than 36.35pp, with a peak of 41.80pp on Aug 1. For Renan Santos, for the trailing pack and for the second and third place contracts, the Senate one and the STF impeachment one there is no new confirmed reading on Aug 15. Quaest separated the top two on REJECTION for the first time in the window, at 54% and 52%, and the candidate registration deadline closes today, Aug 15.`,

  'polymarketComparison.sources':
    `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm. On Aug 15 there is a new confirmed reading for the leader and for the runner-up, at 13:33 BRT (16:33 UTC). For Renan Santos, for the trailing pack and for the second and third place contracts, the Senate one and the STF impeachment one there is no new reading on Aug 15, and the values displayed are those of the last confirmed reading, at 14:46 BRT on Aug 14. ✅ NEW NATIONAL POLL ON Aug 14: Genial/Quaest, n=2,004, registration BR-06773/2026, fieldwork Aug 10 to Aug 13, released at 21:00. Also in force are PoderData/Aya BR-06868/2026 of Aug 13, CNT/MDA BR-06935/2026, Gerp BR-08045/2026 and Futura Inteligência BR-08109/2026, all from Aug 11, plus Palver BR-06596/2026 and BTG/Nexus BR-08428/2026, from Aug 10, and Meio/Ideia BR-04579/2026, from Aug 5. Next national polls in the queue: Nexus (n=2,000, BR-03317/2026) on Aug 17 and Real Time Big Data (n=1,600, BR-05423/2026) on Aug 19.`,

  'polymarketComparison.candidates[0].polymarket': `64.50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `NEW NATIONAL POLL ON Aug 14, released at 21:00. Genial/Quaest (n=2,004, in person, fieldwork Aug 10 to Aug 13, BR-06773/2026): 38% in the first round and 43% x 40% in the runoff. ⭐ AGAINST THE HOUSE ITSELF THE MOVEMENT IS SYMMETRICAL: on Aug 5 it was 39% x 30% in the first round and 44% x 39% in the runoff, so he gave up 1 point and his opponent gained 1 point in each round, and both distances narrowed by 2pp. The 38% is the FLOOR of the nine national polls since Aug 5, whose range runs from 38% to 44%. REJECTION at 52%, BELOW his opponent's 54%, and this is the first national poll of the window to separate the two on that indicator. GOVERNMENT APPROVAL at 46% against 48%, his best net since Aug 5.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `NEW CONFIRMED READING ON Aug 15, ${NOVO}. At 64.50% (vol USD 8.29M cumulative). The price went from 63.50% on Aug 14 to 64.50% now, up 1.00pp, and BROKE through a level it had held since Aug 9, returning to that of Aug 8. SERIES CAVEAT, measured over all recorded points and not over the last point of each day: among the 174 points since May 18, 17 had a value equal to or above 64.50%, with a peak of 66.50% on Aug 1 and a floor of 39.50% on May 26. ⚠️ The distance to the runner-up WIDENED, from 35.65pp to 36.35pp, over the same pair of days in which the polls narrowed it.`,

  'polymarketComparison.candidates[1].polymarket': `28.15%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `NEW NATIONAL POLL ON Aug 14. Genial/Quaest gives him 31% in the first round and 40% in the runoff, 3pp from the leader with a 2pp margin. ⭐ IT IS THE FIRST NATIONAL POLL TO SHOW HIM NARROWING BOTH ROUNDS against the house itself: on Aug 5 it was 30% and 39%, so he gained 1 point in each. REJECTION at 54%, the HIGHEST on the board and above the leader's 52%, and it is the first time in the window that a house separates the two on that indicator. Across the nine national polls since Aug 5 he runs from 28.7% to 38% in the first round, and the spread between houses on the same question remains above 8pp.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `NEW CONFIRMED READING ON Aug 15, ${NOVO}. At 28.15% (vol USD 8.23M cumulative). The price went from 27.85% on Aug 14 to 28.15% now, up 0.30pp and a SECOND STRAIGHT DAY of gains. ⚠️ And even rising he ended up FURTHER from the leader, because the leader rose 1.00pp: the distance widened from 35.65pp to 36.35pp. SERIES CAVEAT, measured over all recorded points: among the 172 points since May 18, 23 had a value equal to or above 28.15%, with a peak of 33.20% on Jun 2 and a floor of 22.00% on Jul 3.`,

  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `Genial/Quaest of Aug 14 keeps him at 4% in the first round, EXACTLY the same value the house gave him on Aug 5, that is, nine days without any gain against the same ruler. The 5% from Gerp, the 4% from BTG/Nexus, the 4.7% from Meio/Ideia and the 10% from Palver online all still stand. In PoderData of Aug 13 he is the ONLY one of the four tested whom the leader beats in the runoff, while the other three tie. The method effect remains the reading on him: the same name runs from 4% to 10% depending on the interview environment, and the caveat was declared by Palver itself.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `${SEM}, at 7.15% (vol USD 9.59M cumulative). He keeps the largest cumulative volume in the presidential book among names above 1%. The price remains BETWEEN the two polling methods, above the 4% of telephone and in-person and below the 10% of online.`,

  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `Genial/Quaest of Aug 14 gives him 4% in the first round, the same as Aug 5, and brings the data point that was missing about him: REJECTION at 35%, against 54% and 52% for the top two, with high non-recognition declared by the house itself. ⚠️ Low rejection with high non-recognition is NOT acceptance: it means most of the electorate has not yet formed an opinion, and an unformed opinion can go either way. He continues to tie with the leader in the runoff of PoderData of Aug 13, his second tie in four days.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `${SEM}, at 1.05% (vol USD 5.70M cumulative). ⚠️ HIS CONTRAST REMAINS THE LARGEST ON THE PANEL: 4% to 5.7% of declared intention in the first round against a little over 1% of winning price, and a tie with the leader in the runoff of a national poll. Tying in the runoff and winning the election are different questions, and the panel does not add them together.`,

  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `${SEM}, at 0.05% (vol USD 13.91M cumulative), below the 0.5% cutoff the panel uses to separate price from noise. It remains the largest cumulative volume in the whole presidential book, with the price at the floor. High volume with probability at the floor is conviction already priced in, not movement.`,

  'polymarketComparison.candidates[5].tendenciaPesquisa':
    `Genial/Quaest of Aug 14 keeps him at 2% in the first round, the same value as Aug 5. The 2% from Gerp, the 3% from BTG/Nexus and the 2.6% from Meio/Ideia all still stand. He ties with the leader in the runoff of PoderData of Aug 13. He is the only one in the pack with a candidacy registration already filed with the TSE, done on Aug 6, and for that reason the deadline closing on Aug 15 does not press him.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `${SEM}, at 0.35% (vol USD 5.07M cumulative), below the 0.5% cutoff the panel uses to separate price from noise.`,

  'polymarketComparison.candidates[6].tendenciaPesquisa':
    `Genial/Quaest of Aug 14 does not test him in a presidential scenario, and no national poll of the window includes him. The underlying caveat remains and must be stated clearly: he is NOT a presidential candidate, he is running for the governorship of São Paulo, and any scenario that includes him is a polling hypothesis, not a candidacy under way.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `${SEM}, at 0.15% (vol USD 7.06M cumulative), below the 0.5% cutoff. A variation in this band has no informational value.`,
})
