/**
 * Mapa ES de 15/Ago para polls-data.json.
 * Convenções: vírgula decimal e ponto de milhar, como no pt-BR. Datas "15 de ago".
 */
import { construir } from '../build-locale-json'

const NOVO = 'lectura confirmada del 15 de ago, 13:33 BRT (16:33 UTC)'
const SEM = 'NO HAY LECTURA CONFIRMADA NUEVA PARA ÉL EL 15 DE AGO. El valor exhibido es el de la última lectura confirmada, del 14 de ago, 14:46 BRT'

construir('polls-data', 'es', {
  'polls[0].method': `Presencial, 120 municipios`,
  'polls[0].note':
    `Encuesta nacional Genial/Quaest divulgada el 14 de ago a las 21:00 (G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, Correio Braziliense). Primera vuelta Lula 38% x Flávio Bolsonaro 31%, una distancia de 7pp. Balotaje Lula 43% x Flávio 40%, 3pp, con margen de 2pp. ⭐ LA COMPARACIÓN QUE VALE ES CON LA PROPIA CASA, Y ES SIMÉTRICA: contra la Quaest del 5 de ago, la primera vuelta pasó de 39% x 30% a 38% x 31% y el balotaje pasó de 44% x 39% a 43% x 40%. En ambas vueltas Lula cedió 1 punto y Flávio ganó 1 punto, y cada distancia se estrechó 2pp. Misma casa, mismo método presencial y misma muestra. RECHAZO separado por primera vez en la ventana: Flávio 54%, Lula 52% y Caiado 35%, este último con alto desconocimiento declarado por la casa. APROBACIÓN DEL GOBIERNO en 46% contra 48% de desaprobación, empate técnico por el margen. ⚠️ El TSE registra el campo del 10 al 13 de ago y la casa publicó del 10 al 12 de ago; el panel exhibe el período registrado.`,
  'polls[0].source':
    `Genial/Quaest vía G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney y Correio Braziliense, 14 de ago`,

  'approvalData.note':
    `ENCUESTA NACIONAL NUEVA EL 14 DE AGO, divulgada a las 21:00. Genial/Quaest: 46% aprueban y 48% desaprueban el gobierno de Lula, un saldo de 2pp negativos y empate técnico por el margen de 2pp, contra 43% x 50% de PoderData/Aya del 13 de ago, que era el par vigente. ⚠️ SON DOS CASAS EN DOS DÍAS CON 5 PUNTOS DE DIFERENCIA EN EL SALDO, y el panel no elige entre ellas: la distancia entre casas es el hallazgo. RECHAZO en la Quaest: Flávio Bolsonaro 54%, Lula 52% y Ronaldo Caiado 35%, este último con alto desconocimiento declarado por la casa. Es la primera nacional de la ventana en SEPARAR a los dos primeros en ese indicador, después de que la PoderData los empatara en 48%. Siguen en el cuadro la Gerp del 11 de ago con 53% de desaprobación, BTG/Nexus del 10 de ago con 46% x 49%, Palver del mismo día con 45% x 55% y Genial/Quaest del 5 de ago con 48% x 47%. LO QUE MUESTRA EL CONJUNTO: en nueve lecturas de diez días la desaprobación va de 47% a 55%, una distancia de 8pp entre casas, y el saldo va de 1pp positivo a 10pp negativo. Ninguna casa cambió de lado. ⚠️ PROCEDENCIA DECLARADA: aprobación y desaprobación son de Genial/Quaest del 14 de ago (campo del 10 al 13 de ago, n=2.004, presencial, margen 2pp, registro BR-06773/2026), por ser la lectura nacional más reciente; el 6% restante es el residuo aritmético entre los dos valores publicados. La evaluación de la gestión, con 36% positiva, 26% regular y 36% negativa, sigue siendo la de Genial/Quaest del 5 de ago, porque la ronda nueva no publicó esa apertura completa en las notas capturadas. El panel prefiere declarar la mezcla que esconderla.`,
  'approvalData.source':
    `Aprobación y desaprobación: Genial/Quaest 14 de ago de 2026 (campo del 10 al 13 de ago, n=2.004, presencial en 120 municipios, margen 2,0pp, registro TSE BR-06773/2026), divulgada por G1, CNN Brasil, Estadão, Correio Braziliense y Poder360. Rechazo: misma ronda, vía G1, Poder360, InfoMoney y O Globo. Evaluación de la gestión (óptimo/bueno, regular, malo/pésimo): Genial/Quaest 5 de ago de 2026, porque la ronda del 14 de ago no trajo esa apertura en las notas capturadas.`,

  'polymarketComparison.note':
    `ACTUALIZACIÓN DEL 15 DE AGO. EL CRUCE DEL DÍA APUNTA HACIA LADOS OPUESTOS. En las encuestas, la Quaest divulgada el 14 de ago a las 21:00 muestra las dos distancias ESTRECHÁNDOSE contra la propia casa: la primera vuelta pasó de 9pp a 7pp y el balotaje de 5pp a 3pp, con un movimiento simétrico de 1 punto de cada lado en ambos casos. En el precio ocurrió lo contrario: la distancia se AMPLIÓ, de 35,65pp a 36,35pp, porque el líder subió 1,00pp y el segundo subió 0,30pp. ⭐ Los dos instrumentos se movieron en el mismo par de días y en sentidos opuestos, y esa divergencia es el hallazgo. El líder rompió el 63,50%, donde estaba desde el 9 de ago, y volvió al nivel del 8 de ago. ⛔ Sin superlativo: entre los 174 puntos registrados desde el 18 de may, 17 tuvieron un valor igual o superior a 64,50%, y entre los 88 días con distancia registrada, 32 tuvieron una distancia igual o mayor a 36,35pp, con un pico de 41,80pp el 1 de ago. Para Renan Santos, para el pelotón y para los contratos de segundo y tercer lugar, el del Senado y el de impeachment en el STF no hay lectura confirmada nueva el 15 de ago. La Quaest separó a los dos primeros en el RECHAZO por primera vez en la ventana, con 54% y 52%, y el plazo de registro de candidaturas termina hoy, 15 de ago.`,

  'polymarketComparison.sources':
    `Precios de Polymarket vía proxy AFOS, y el panel solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen. El 15 de ago hay lectura confirmada nueva para el líder y para el segundo, a las 13:33 BRT (16:33 UTC). Para Renan Santos, para el pelotón y para los contratos de segundo y tercer lugar, el del Senado y el de impeachment en el STF no hay lectura nueva el 15 de ago, y los valores exhibidos son los de la última lectura confirmada, a las 14:46 BRT del 14 de ago. ✅ ENCUESTA NACIONAL NUEVA EL 14 DE AGO: Genial/Quaest, n=2.004, registro BR-06773/2026, campo del 10 al 13 de ago, divulgada a las 21:00. Siguen vigentes la PoderData/Aya BR-06868/2026 del 13 de ago, la CNT/MDA BR-06935/2026, la Gerp BR-08045/2026 y la Futura Inteligência BR-08109/2026, todas del 11 de ago, más la Palver BR-06596/2026 y la BTG/Nexus BR-08428/2026, del 10 de ago, y la Meio/Ideia BR-04579/2026, del 5 de ago. Próximas nacionales en la fila: Nexus (n=2.000, BR-03317/2026) el 17 de ago y Real Time Big Data (n=1.600, BR-05423/2026) el 19 de ago.`,

  'polymarketComparison.candidates[0].polymarket': `64,50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `ENCUESTA NACIONAL NUEVA EL 14 DE AGO, divulgada a las 21:00. Genial/Quaest (n=2.004, presencial, campo del 10 al 13 de ago, BR-06773/2026): 38% en la primera vuelta y 43% x 40% en el balotaje. ⭐ CONTRA LA PROPIA CASA EL MOVIMIENTO ES SIMÉTRICO: el 5 de ago eran 39% x 30% en la primera vuelta y 44% x 39% en el balotaje, es decir, cedió 1 punto y su adversario ganó 1 punto en cada vuelta, y ambas distancias se estrecharon 2pp. El 38% es el PISO de las nueve nacionales desde el 5 de ago, cuyo rango va de 38% a 44%. RECHAZO en 52%, POR DEBAJO del 54% de su adversario, y es la primera nacional de la ventana en separar a los dos en ese indicador. APROBACIÓN DEL GOBIERNO en 46% contra 48%, su mejor saldo desde el 5 de ago.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `LECTURA CONFIRMADA NUEVA EL 15 DE AGO, ${NOVO}. En 64,50% (vol USD 8,29M acumulado). El precio pasó de 63,50% el 14 de ago a 64,50% ahora, un alza de 1,00pp, y ROMPIÓ un nivel en el que estaba desde el 9 de ago, volviendo al del 8 de ago. SALVEDAD DE SERIE, medida sobre todos los puntos registrados y no sobre el último de cada día: entre los 174 puntos desde el 18 de may, 17 tuvieron un valor igual o superior a 64,50%, con un máximo de 66,50% el 1 de ago y un piso de 39,50% el 26 de may. ⚠️ La distancia hacia el segundo se AMPLIÓ, de 35,65pp a 36,35pp, en el mismo par de días en que las encuestas la estrecharon.`,

  'polymarketComparison.candidates[1].polymarket': `28,15%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `ENCUESTA NACIONAL NUEVA EL 14 DE AGO. La Genial/Quaest le da 31% en la primera vuelta y 40% en el balotaje, a 3pp del líder con margen de 2pp. ⭐ ES LA PRIMERA NACIONAL QUE LO MUESTRA ESTRECHANDO LAS DOS VUELTAS contra la propia casa: el 5 de ago eran 30% y 39%, así que ganó 1 punto en cada una. RECHAZO de 54%, el MAYOR del cuadro y por encima del 52% del líder, y es la primera vez en la ventana que una casa separa a los dos en ese indicador. En las nueve nacionales desde el 5 de ago va de 28,7% a 38% en la primera vuelta, y la amplitud entre casas sobre la misma pregunta sigue por encima de 8pp.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `LECTURA CONFIRMADA NUEVA EL 15 DE AGO, ${NOVO}. En 28,15% (vol USD 8,23M acumulado). El precio pasó de 27,85% el 14 de ago a 28,15% ahora, un alza de 0,30pp y SEGUNDO DÍA SEGUIDO de subida. ⚠️ Y aun subiendo quedó MÁS LEJOS del líder, porque el líder subió 1,00pp: la distancia se amplió de 35,65pp a 36,35pp. SALVEDAD DE SERIE, medida sobre todos los puntos registrados: entre los 172 puntos desde el 18 de may, 23 tuvieron un valor igual o superior a 28,15%, con un máximo de 33,20% el 2 de jun y un piso de 22,00% el 3 de jul.`,

  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `La Genial/Quaest del 14 de ago lo mantiene en 4% en la primera vuelta, EXACTAMENTE el mismo valor que la casa le dio el 5 de ago, es decir, nueve días sin avance contra la misma regla. Siguen el 5% de la Gerp, el 4% de BTG/Nexus, el 4,7% de Meio/Ideia y el 10% de Palver por internet. En la PoderData del 13 de ago él es el ÚNICO de los cuatro probados al que el líder vence en el balotaje, mientras los otros tres empatan. El efecto de método sigue siendo la lectura sobre él: el mismo nombre va de 4% a 10% según el ambiente de la entrevista, y la salvedad fue declarada por la propia Palver.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `${SEM}, en 7,15% (vol USD 9,59M acumulado). Mantiene el mayor volumen acumulado del libro presidencial entre los nombres por encima de 1%. El precio sigue ENTRE los dos métodos de las encuestas, por encima del 4% del teléfono y del presencial y por debajo del 10% de internet.`,

  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `La Genial/Quaest del 14 de ago le da 4% en la primera vuelta, lo mismo que el 5 de ago, y trae el dato que faltaba sobre él: RECHAZO de 35%, contra 54% y 52% de los dos primeros, con alto desconocimiento declarado por la propia casa. ⚠️ Rechazo bajo con desconocimiento alto NO es aceptación: significa que la mayor parte del electorado aún no formó opinión, y una opinión no formada puede ir hacia cualquier lado. Sigue empatando con el líder en el balotaje de la PoderData del 13 de ago, su segundo empate en cuatro días.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `${SEM}, en 1,05% (vol USD 5,70M acumulado). ⚠️ SU CONTRASTE SIGUE SIENDO EL MAYOR DEL PANEL: de 4% a 5,7% de intención declarada en la primera vuelta contra poco más de 1% de precio de victoria, y un empate con el líder en el balotaje de una nacional. Empatar en el balotaje y ganar la elección son preguntas distintas, y el panel no las suma.`,

  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `${SEM}, en 0,05% (vol USD 13,91M acumulado), por debajo del corte de 0,5% que el panel usa para separar precio de ruido. Sigue siendo el mayor volumen acumulado de todo el libro presidencial, con el precio en el piso. Volumen alto con probabilidad en el piso es convicción ya descontada, no movimiento.`,

  'polymarketComparison.candidates[5].tendenciaPesquisa':
    `La Genial/Quaest del 14 de ago lo mantiene en 2% en la primera vuelta, el mismo valor del 5 de ago. Siguen el 2% de la Gerp, el 3% de BTG/Nexus y el 2,6% de Meio/Ideia. Empata con el líder en el balotaje de la PoderData del 13 de ago. Es el único del pelotón con registro de candidatura ya presentado ante el TSE, hecho el 6 de ago, y por eso el plazo que termina el 15 de ago no lo presiona.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `${SEM}, en 0,35% (vol USD 5,07M acumulado), por debajo del corte de 0,5% que el panel usa para separar precio de ruido.`,

  'polymarketComparison.candidates[6].tendenciaPesquisa':
    `La Genial/Quaest del 14 de ago no lo prueba en escenario presidencial, y ninguna nacional de la ventana lo incluye. La salvedad de fondo permanece y debe decirse con claridad: él NO es candidato a la Presidencia, compite por la gobernación de São Paulo, y cualquier escenario que lo incluya es hipótesis de encuesta, no candidatura en curso.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `${SEM}, en 0,15% (vol USD 7,06M acumulado), por debajo del corte de 0,5%. Una variación en esta franja no tiene valor informativo.`,
})
