/**
 * Mapas EN e ES do polls-data.json para a publicação de 31/Jul 17:33.
 */
import { construir } from '../build-locale-json'

const G = (l: 'en' | 'es', id: string, txt: string) => `[${txt}](/${l}/glossary#${id})`
const T1_EN = G('en', 'primeiro-turno', 'first round')
const T1a_EN = G('en', 'primeiro-turno', 'first-round')
const T2_EN = G('en', 'segundo-turno', 'runoff')
const T1_ES = G('es', 'primeiro-turno', 'primera vuelta')
const T2_ES = G('es', 'segundo-turno', 'segunda vuelta')
const STF_EN = G('en', 'stf', 'STF')
const STF_ES = G('es', 'stf', 'STF')

const VOX_EN = 'Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, 2.15pp margin, BR-01084/2026)'
const VOX_ES = 'Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, BR-01084/2026)'

const EN: Record<string, string> = {
  'polls[0].source': 'Vox Brasil via Metrópoles, Revista Fórum, Contracs Jul 31',
  'polls[0].note': `Vox Brasil national poll published Jul 31 (Metrópoles, Revista Fórum, Contracs). First round Lula 40.5% x Flávio 31.2% (gap +9.3pp), with Caiado 5.5%, Zema 3.2% and Renan Santos 3.0%. Runoff Lula 47.5% x Flávio 41.1% (gap +6.4pp), a difference that falls OUTSIDE the two margins added together and therefore is NOT a statistical tie, unlike PoderData of Jul 30, which gave 3pp. Field Jul 26-28, n=2,100, 2.15pp margin, 95% confidence, registration BR-01084/2026. THE WEEK HAS THREE FIRST-ROUND GAP READINGS AND THEY DO NOT AGREE: 9.1pp at AtlasIntel of Jul 29, 6pp at PoderData of Jul 30 and 9.3pp here. The outlier is PoderData, not Vox. RENAN SANTOS at 3.0% closes the sequence of THREE consecutive institutes cutting him: 7.8% at AtlasIntel, 4% at PoderData and 3.0% now. With the price at 8.15%, the distance between market and polling reaches 5.15pp, the widest in the window, against the 0.90pp the panel recorded on Jul 29. CAIADO at 5.5% has here his BEST national polling of the window, above PoderData's 5% and AtlasIntel's 3.1%, on the same day his price fell 0.80pp. The institute also reports that, between May and July, Lula gained 7.3pp and Flávio lost 2.7pp within its own series, reversing a lead that had belonged to the senator; the panel reproduces this as the institute's claim, because it is an internal comparison of theirs. This round did NOT publish approval or rejection.`,

  'polymarketComparison.note': `Crossing of Jul 31: the front-runner did not move and almost everything else did. Lula FLAT at 63.50% (vol USD 7.77M) for a second session, and the gap narrows from +39.55pp to +39.20pp because Flávio ROSE 0.35pp, reaching 24.30% (vol USD 7.76M). THE POLLING: ${VOX_EN} gives Lula 40.5% x Flávio 31.2% in the ${T1_EN} and 47.5% x 41.1% in the ${T2_EN}, and the runoff's 6.4pp fall OUTSIDE the two margins added together, which rules out the statistical-tie reading of the previous day. THE WEEK HAS THREE FIRST-ROUND GAPS AND THEY DO NOT AGREE: 9.1pp at AtlasIntel, 6pp at PoderData and 9.3pp at Vox. The outlier is PoderData. THE FINDING IS RENAN SANTOS, and it is a sequence: THREE consecutive institutes cut him, from 7.8% to 4% and now 3.0%, and with the price at 8.15% the distance between market and polling reaches 5.15pp, the widest in the window, against the 0.90pp this panel called convergence on Jul 29. That reading did not hold. And the market contradicted itself: on the same day, his ${T1a_EN} second-place book ROSE 3.25pp, from 6.10% to 9.35%, handing back two thirds of what had been taken the previous day. CAIADO gave it all back: he fell 0.80pp, to 1.75%, undoing in one session the gain of two days, and rose 1.00pp in third place, moving to 26.50%, on the same day Vox gave him 5.5%, his best national polling of the window. The series caveat says 1.75% is his normal range since Jul 22 and that what the series recorded on Jul 30, 2.55%, was the upward deviation. CAMILO SANTANA rose to 2.20% and ALCKMIN to 1.10%, on the day the PCdoB formalized support for the Lula-Alckmin ticket, and the panel records the coincidence without asserting cause; on Camilo, the 2.20% sits BELOW his series maximum, which is 4.10% from May 3, and the move is a recovery from the series minimum, 0.50%, set the day before. IN THE OTHER MARKETS: impeachment of an ${STF_EN} justice FLAT at 3.10% (vol USD 83,000), with no variation across the guard's four readings; in the Senate the PL rose 6.50pp, reaching 72.00% (vol USD 258,000), and the MDB enters as a declared RANGE of 25.20% to 26.60%; in inflation the 4.50% to 4.99% band rose 1.20pp, to 33.70%. CAPTURE NOTE: the double-reading capture guard FAILED both of today's rounds, which is why the range rule applies. The only divergent book was the MDB in the Senate, which swung between 25.20% and 26.60% across three readings. The full presidential contract repeated across ALL FOUR readings, so the headline figure is firm. Total accumulated volume in the presidential market at USD 117.03M.`,

  'polymarketComparison.sources': 'Polymarket via AFOS proxy (live capture Jul 31, 20:33 UTC, degraded false, failedCount 0, scripts/capture-guard.ts across TWO rounds, both failed; the only divergent book was senate:MDB, published as a range; the presidential book repeated across all four readings) + Vox Brasil Jul 31 (BR-01084/2026, n=2,100, field Jul 26-28, 2.15pp margin, latest national poll) + PoderData/Aya Jul 30 (BR-07845/2026, n=2,400) + AtlasIntel/Bloomberg Jul 29 (BR-08602/2026, n=5,021, largest sample in the window) + BTG/Nexus Jul 27 (BR-01489/2026) + Datafolha Jul 24 (BR-01166/2026) + Gerp Jul 22 (BR-05026/2026) + Indexa Jul 21 (BR-02904/2026) + Real Time Big Data Jul 21 (BR-09247/2026) + PoderData/Aya Jul 16 (BR-00059/2026) + Genial/Quaest Jul 15 (BR-07181/2026) + Futura/Apex Jul 14 (BR-07294/2026) + AtlasIntel Jul 1 (BR-04582/2026). AFOS series checked with scripts/check-superlativo.ts, straight against Neon, with no window cap: Camilo Santana peak at 4.10% (May 3) and trough at 0.50% (Jul 30); Caiado range since Jul 22 between 1.80% and 2.10%; Zema peak at 10.10% (Apr 26).',

  'polymarketComparison.candidates[0].tendenciaPesquisa': `${VOX_EN} gives 40.5% in the ${T1_EN} and 47.5% x 41.1% in the ${T2_EN}. The 6.4pp lead in the runoff falls OUTSIDE the two margins added together, so this reading does NOT describe a statistical tie, unlike PoderData of Jul 30, which gave 3pp. The record that organizes the week: THREE houses measured the first-round gap at 9.1pp (AtlasIntel, Jul 29), 6pp (PoderData, Jul 30) and 9.3pp (Vox, today). Two agree around 9pp and the one that departs is PoderData. This round published neither approval nor rejection.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'FLAT at 63.50% for a second consecutive session, holding the value that ties the top of the AFOS series, set on Jul 26, Jul 28 and Jul 30. The gap over Flávio narrowed from +39.55pp to +39.20pp, and it narrowed by the opponent\'s movement, not his. Two sessions with no variation at all in the winner contract, in a week when the rest of the book moved a good deal, and the price did not react to any of the three national polls published in the last three days.',

  'polymarketComparison.candidates[1].polymarket': '24.30%',
  'polymarketComparison.candidates[1].tendenciaPesquisa': `${VOX_EN} brings him to 31.2% in the ${T1_EN} and 41.1% in the ${T2_EN}. The 6.4pp separating him from Lula fall outside the two margins added together, which rules out the statistical-tie reading PoderData supported the previous day. His day, however, was about ticket-building and it has THREE versions of the same fact: he said Tereza Cristina had accepted the running-mate slot, the senator said there had been a conversation and that the decision depends on the PL and the PP-União, and the PP leadership assesses that she accepted knowing the party would block it. The Aug 5 deadline is less than a week away.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `RISES 0.35pp and reaches 24.30% (vol USD 7.76M), and it is he who narrows the gap, which moves to +39.20pp. In the sub-markets the signal is CROSSED: he gives up 1.00pp in the ${T1a_EN} second-place book, which moves to 78.00% in a contract of USD 216,000, and gives up 0.60pp in the third-place book, which moves to 5.65%. Rising in the chance of winning while giving ground in both placing books is an unusual combination, and the counterpart to the fall in the second-place book is Renan Santos rising 3.25pp in that same contract, which suggests internal reallocation rather than a fresh reading on the ${T2_EN}.`,

  'polymarketComparison.candidates[2].polymarket': '8.15%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': 'THREE consecutive institutes cut him, and it is the sequence that matters, not the isolated number: 7.8% at AtlasIntel of Jul 29, 4% at PoderData of Jul 30 and 3.0% at Vox Brasil of Jul 31. With the price at 8.15%, the distance between market and polling reaches 5.15pp, the widest in the window. On Jul 29 this panel recorded that same distance at 0.90pp and called it convergence; three institutes later it has quadrupled, and it is on the record that the earlier reading did not hold. The spread between houses has stopped being a spread: the three most recent readings are also the three lowest, which describes a downward trend.',
  'polymarketComparison.candidates[2].tendenciaPolymarket': `FALLS 0.30pp and reaches 8.15% (vol USD 8.63M), a fourth consecutive session of decline in the winner contract. But the day's move is the opposite in the placing book: it RISES 3.25pp in the ${T1a_EN} second-place book, from 6.10% to 9.35% in a contract of USD 1.09M, recovering two thirds of what it lost the previous day, and stays FLAT at 62.00% in third place. Yesterday the panel recorded that the money had reclassified him, removing his ${T2_EN} chance; today the same money handed much of it back, on the day polling cut him for a third consecutive time. Both directions are on the record and neither is arbitrated. He holds, in this capture, the largest accumulated volume among the competitive names in the presidential market, USD 8.63M.`,

  'polymarketComparison.candidates[3].polymarket': '1.75%',
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${VOX_EN} gives him 5.5% in the ${T1_EN}, his BEST national reading of the window, above PoderData's 5% of Jul 30 and well above AtlasIntel's 3.1% of Jul 29. The divergence between institutes about him remains open at FOUR levels within the same month: 6% at Nexus, 5.5% at Vox, 5% at PoderData and 3.1% at AtlasIntel, and today's reading is the highest of the four.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `FALLS 0.80pp and reaches 1.75% (vol USD 5.22M), giving back in a single session the whole gain accumulated over two days. The series caveat is mandatory and it cuts both ways: 1.75% sits inside his normal range since Jul 22, when the AFOS series recorded 1.80%, and what the series recorded on Jul 30, 2.55%, was the upward deviation. There was no collapse, there was the giving back of a deviation. And the signal is crossed, because in the ${T1a_EN} third-place book he RISES 1.00pp, moving to 26.50% in a contract of USD 37,000. The reading that holds is one of reallocation: the market moves him from candidate-to-win to candidate-for-third, and the polling does not follow, because it gave him his best mark of the window on this very day.`,

  'polymarketComparison.candidates[4].tendenciaPesquisa': 'Vox Brasil of Jul 31 does not test him in any presidential scenario. On Jul 28 he released allies and base mayors to back Caiado\'s candidacy, reiterating that his own candidate is still Flávio.',
  'polymarketComparison.candidates[4].tendenciaPolymarket': 'FLAT at 0.15%, with the highest accumulated volume in the presidential book in this capture, USD 13.68M. It is the legacy anomaly that serves as a permanent reminder of method: volume measures traded history, not current conviction. The contract accumulated that figure over months in which he was treated as a likely candidate, and today\'s price says the market no longer considers him in the race.',

  'polymarketComparison.candidates[5].polymarket': '0.45%',
  'polymarketComparison.candidates[5].tendenciaPesquisa': `${VOX_EN} brings him to 3.2% in the ${T1_EN}, essentially the same 3% as PoderData of Jul 30 and above AtlasIntel's 2.8% of Jul 29. In the polling he is stable. On the party front the day was bad: Marcelo Aro left his Senate ticket to run for the government of Minas Gerais, a move Zema publicly called betrayal, and Novo ruled out Barbosa as running mate, heading for a single-party ticket. He still has NO running mate, with the Aug 5 deadline less than a week away.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `FALLS 0.10pp and reaches 0.45% (vol USD 4.58M), in a THIRD consecutive session of decline in the winner contract, and stays at 4.45% in the ${T1a_EN} third-place book. A caveat on the series, and it is a big one: his maximum in the AFOS series is 10.10%, from Apr 26, so 0.45% is less than a twentieth of that level, and 0.10pp moves in that range carry almost no information.`,

  'polymarketComparison.candidates[6].polymarket': '0.30%',
  'polymarketComparison.candidates[6].tendenciaPesquisa': `Vox Brasil of Jul 31 does NOT test him in any scenario, neither ${T1_EN} nor ${T2_EN}, so he has no new polling in this round, and the absence of a test in a national poll is information the panel records rather than repeating the previous day's figure as if it were new. The caveat stands and needs saying plainly: he is NOT a presidential candidate, he is running for governor of São Paulo, and the scenario that favours him is a polling hypothesis and not a candidacy in progress.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `RISES 0.15pp and reaches 0.30%, doubling the previous day's value, and reaches 1.00% in the ${T1a_EN} second-place book, in a second consecutive session of gains in that contract. The scale caveat is mandatory: at a price of 0.30%, a 0.15pp rise carries almost no information, and the move is recorded only because it is the second straight day in the same direction.`,
}

const ES: Record<string, string> = {
  'polls[0].source': 'Vox Brasil vía Metrópoles, Revista Fórum, Contracs 31 de julio',
  'polls[0].note': `Vox Brasil nacional publicada el 31 de julio (Metrópoles, Revista Fórum, Contracs). Primera vuelta Lula 40,5% x Flávio 31,2% (brecha +9,3pp), con Caiado 5,5%, Zema 3,2% y Renan Santos 3,0%. Segunda vuelta Lula 47,5% x Flávio 41,1% (brecha +6,4pp), diferencia que queda FUERA de los dos márgenes sumados y por eso NO es empate técnico, a diferencia de PoderData del 30 de julio, que daba 3pp. Campo 26-28 de julio, n=2.100, margen de 2,15pp, 95% de confianza, registro BR-01084/2026. LA SEMANA TIENE TRES LECTURAS DE BRECHA EN LA PRIMERA VUELTA Y NO CONCUERDAN: 9,1pp en AtlasIntel del 29 de julio, 6pp en PoderData del 30 de julio y 9,3pp aquí. La fuera de la curva es PoderData, no Vox. RENAN SANTOS con 3,0% cierra la secuencia de TRES institutos seguidos recortándolo: 7,8% en AtlasIntel, 4% en PoderData y 3,0% ahora. Con el precio en 8,15%, la distancia entre mercado y encuesta llega a 5,15pp, la mayor del recorte, contra los 0,90pp que el panel registró el 29 de julio. CAIADO con 5,5% tiene aquí su MEJOR encuesta nacional del recorte, por encima del 5% de PoderData y del 3,1% de AtlasIntel, el mismo día en que su precio cayó 0,80pp. El instituto informa además que, entre mayo y julio, Lula creció 7,3pp y Flávio retrocedió 2,7pp en su propia serie, invirtiendo una ventaja que era del senador; el panel lo reproduce como afirmación del instituto, porque es comparación interna suya. Esta ronda NO publicó aprobación ni rechazo.`,

  'polymarketComparison.note': `Cruce del 31 de julio: el favorito no se movió y casi todo el resto sí. Lula ESTABLE en 63,50% (vol USD 7,77M) por segunda rueda, y la brecha retrocede de +39,55pp a +39,20pp porque Flávio SUBIÓ 0,35pp, llegando a 24,30% (vol USD 7,76M). LA ENCUESTA: ${VOX_ES} da Lula 40,5% x Flávio 31,2% en la ${T1_ES} y 47,5% x 41,1% en la ${T2_ES}, y los 6,4pp de la segunda vuelta quedan FUERA de los dos márgenes sumados, lo que descarta la lectura de empate técnico de la víspera. LA SEMANA TIENE TRES BRECHAS DE PRIMERA VUELTA Y NO CONCUERDAN: 9,1pp en AtlasIntel, 6pp en PoderData y 9,3pp en Vox. La fuera de la curva es PoderData. EL HALLAZGO ES RENAN SANTOS, y es de secuencia: TRES institutos seguidos lo recortaron, de 7,8% a 4% y ahora 3,0%, y con el precio en 8,15% la distancia entre mercado y encuesta llega a 5,15pp, la mayor del recorte, contra los 0,90pp que este panel llamó convergencia el 29 de julio. Aquella lectura no se sostuvo. Y el mercado se contradijo: el mismo día, su book de segundo lugar de la ${T1_ES} SUBIÓ 3,25pp, de 6,10% a 9,35%, devolviendo dos tercios de lo que había sido quitado la víspera. CAIADO devolvió todo: cayó 0,80pp, a 1,75%, deshaciendo en una rueda el alza de dos días, y subió 1,00pp en el tercer lugar, pasando a 26,50%, el mismo día en que Vox le dio 5,5%, su mejor encuesta nacional del recorte. La salvedad de serie dice que 1,75% es su franja normal desde el 22 de julio y que lo que la serie registró el 30 de julio, 2,55%, era la desviación al alza. CAMILO SANTANA subió a 2,20% y ALCKMIN a 1,10%, el día en que el PCdoB formalizó apoyo a la fórmula Lula-Alckmin, y el panel registra la coincidencia sin afirmar causa; sobre Camilo, los 2,20% quedan POR DEBAJO del máximo de su serie, que es 4,10% del 3 de mayo, y el movimiento es recuperación del mínimo de la serie, 0,50%, marcado la víspera. EN LOS DEMÁS MERCADOS: impeachment de ministro del ${STF_ES} ESTABLE en 3,10% (vol USD 83.000), sin variación en las cuatro lecturas de la traba; en el Senado el PL subió 6,50pp, llegando a 72,00% (vol USD 258.000), y el MDB entra como FRANJA declarada de 25,20% a 26,60%; en inflación la franja de 4,50% a 4,99% subió 1,20pp, a 33,70%. NOTA DE CAPTURA: la traba de doble lectura REPROBÓ las dos rondas de hoy, y por eso vale la regla de franja. El único book divergente fue el del MDB en el Senado, que osciló entre 25,20% y 26,60% en tres lecturas. El contrato presidencial entero se repitió en las CUATRO lecturas, así que el dato principal está firme. Volumen total acumulado en el presidencial en USD 117,03M.`,

  'polymarketComparison.sources': 'Polymarket vía proxy AFOS (captura en vivo 31 de julio, 20:33 UTC, degraded false, failedCount 0, scripts/capture-guard.ts en DOS rondas, ambas reprobadas; el único book divergente fue senate:MDB, publicado como franja; el presidencial se repitió en las cuatro lecturas) + Vox Brasil 31 de julio (BR-01084/2026, n=2.100, campo 26-28 de julio, margen de 2,15pp, última nacional) + PoderData/Aya 30 de julio (BR-07845/2026, n=2.400) + AtlasIntel/Bloomberg 29 de julio (BR-08602/2026, n=5.021, mayor muestra del recorte) + BTG/Nexus 27 de julio (BR-01489/2026) + Datafolha 24 de julio (BR-01166/2026) + Gerp 22 de julio (BR-05026/2026) + Indexa 21 de julio (BR-02904/2026) + Real Time Big Data 21 de julio (BR-09247/2026) + PoderData/Aya 16 de julio (BR-00059/2026) + Genial/Quaest 15 de julio (BR-07181/2026) + Futura/Apex 14 de julio (BR-07294/2026) + AtlasIntel 1 de julio (BR-04582/2026). Serie del AFOS verificada con scripts/check-superlativo.ts, directo en Neon, sin límite de ventana: techo de Camilo Santana en 4,10% (3 de mayo) y mínimo en 0,50% (30 de julio); franja de Caiado desde el 22 de julio entre 1,80% y 2,10%; techo de Zema en 10,10% (26 de abril).',

  'polymarketComparison.candidates[0].tendenciaPesquisa': `${VOX_ES} da 40,5% en la ${T1_ES} y 47,5% x 41,1% en la ${T2_ES}. La ventaja de 6,4pp en la segunda vuelta queda FUERA de los dos márgenes sumados, así que esta lectura NO describe empate técnico, a diferencia de PoderData del 30 de julio, que daba 3pp. El registro que organiza la semana: TRES casas midieron la brecha de la primera vuelta en 9,1pp (AtlasIntel, 29 de julio), 6pp (PoderData, 30 de julio) y 9,3pp (Vox, hoy). Dos concuerdan en torno a 9pp y la que se aparta es PoderData. Esta ronda no publicó aprobación ni rechazo.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'ESTABLE en 63,50% por segunda rueda consecutiva, manteniendo el valor que iguala el techo de la serie del AFOS, marcado el 26, el 28 y el 30 de julio. La brecha sobre Flávio retrocedió de +39,55pp a +39,20pp, y retrocedió por movimiento del adversario, no suyo. Dos ruedas sin ninguna variación en el contrato de ganador, en una semana en que el resto del book se movió bastante, y el precio no reaccionó a ninguna de las tres encuestas nacionales publicadas en los últimos tres días.',

  'polymarketComparison.candidates[1].polymarket': '24,30%',
  'polymarketComparison.candidates[1].tendenciaPesquisa': `${VOX_ES} lo trae en 31,2% en la ${T1_ES} y 41,1% en la ${T2_ES}. Los 6,4pp que lo separan de Lula quedan fuera de los dos márgenes sumados, lo que descarta la lectura de empate técnico que PoderData sostenía la víspera. Su día, sin embargo, fue de formación de fórmula y tiene TRES versiones del mismo hecho: él afirmó que Tereza Cristina aceptó ser vice, la senadora dijo que hubo conversación y que la decisión depende del PL y del PP-União, y la cúpula del PP evalúa que ella aceptó sabiendo que el partido lo bloquearía. El plazo del 5 de agosto está a menos de una semana.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `SUBE 0,35pp y llega a 24,30% (vol USD 7,76M), y es él quien estrecha la brecha, que pasa a +39,20pp. En los submercados la señal es CRUZADA: cede 1,00pp en el book de segundo lugar de la ${T1_ES}, que pasa a 78,00% en un contrato de USD 216.000, y cede 0,60pp en el de tercer lugar, que pasa a 5,65%. Subir en la chance de ganar y ceder en los dos de colocación es combinación inusual, y la contrapartida de la caída en el book de segundo lugar es el alza de 3,25pp de Renan Santos en ese mismo contrato, lo que sugiere reasignación interna y no lectura nueva sobre la ${T2_ES}.`,

  'polymarketComparison.candidates[2].polymarket': '8,15%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': 'TRES institutos seguidos lo recortaron, y es la secuencia lo que importa, no el número aislado: 7,8% en AtlasIntel del 29 de julio, 4% en PoderData del 30 de julio y 3,0% en Vox Brasil del 31 de julio. Con el precio en 8,15%, la distancia entre mercado y encuesta llega a 5,15pp, la mayor del recorte. El 29 de julio este panel registró esa misma distancia en 0,90pp y la llamó convergencia; tres institutos después se cuadruplicó, y queda registrado que aquella lectura no se sostuvo. La dispersión entre casas dejó de ser dispersión: las tres lecturas más recientes son también las tres más bajas, lo que describe tendencia de caída.',
  'polymarketComparison.candidates[2].tendenciaPolymarket': `CAE 0,30pp y llega a 8,15% (vol USD 8,63M), cuarta rueda consecutiva de baja en el contrato de ganador. Pero el movimiento del día es el opuesto en el book de colocación: SUBE 3,25pp en el de segundo lugar de la ${T1_ES}, de 6,10% a 9,35% en un contrato de USD 1,09M, recuperando dos tercios de lo que perdió la víspera, y queda ESTABLE en 62,00% en el de tercer lugar. Ayer el panel registró que el dinero lo había reclasificado, quitándole la chance de ${T2_ES}; hoy el mismo dinero le devolvió buena parte de ella, el día en que la encuesta lo recortó por tercera vez seguida. Las dos direcciones quedan registradas y ninguna es arbitrada. Mantiene, en esta captura, el mayor volumen acumulado entre los nombres competitivos del presidencial, USD 8,63M.`,

  'polymarketComparison.candidates[3].polymarket': '1,75%',
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${VOX_ES} le da 5,5% en la ${T1_ES}, su MEJOR lectura nacional del recorte, por encima del 5% de PoderData del 30 de julio y bastante por encima del 3,1% de AtlasIntel del 29 de julio. La divergencia entre institutos sobre él sigue abierta en CUATRO niveles dentro del mismo mes: 6% en Nexus, 5,5% en Vox, 5% en PoderData y 3,1% en AtlasIntel, y la lectura de hoy es la más alta de las cuatro.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': `CAE 0,80pp y llega a 1,75% (vol USD 5,22M), devolviendo en una sola rueda toda el alza acumulada en dos días. La salvedad de serie es obligatoria y corta para los dos lados: 1,75% está dentro de su franja normal desde el 22 de julio, cuando la serie del AFOS registró 1,80%, y lo que la serie registró el 30 de julio, 2,55%, era la desviación al alza. No hubo colapso, hubo devolución de una desviación. Y la señal es cruzada, porque en el book de tercer lugar de la ${T1_ES} SUBE 1,00pp, pasando a 26,50% en un contrato de USD 37.000. La lectura que se sostiene es de reasignación: el mercado lo mueve de candidato a ganador hacia candidato a tercer lugar, y la encuesta no acompaña, porque le dio su mejor marca del recorte justamente hoy.`,

  'polymarketComparison.candidates[4].tendenciaPesquisa': 'La Vox Brasil del 31 de julio no lo testea en ningún escenario presidencial. El 28 de julio liberó a aliados y alcaldes de la base para apoyar la candidatura de Caiado, reiterando que su candidato sigue siendo Flávio.',
  'polymarketComparison.candidates[4].tendenciaPolymarket': 'ESTABLE en 0,15%, con el mayor volumen acumulado del book presidencial en esta captura, USD 13,68M. Es la anomalía de legado que sirve de recordatorio permanente de método: el volumen mide historia negociada y no convicción actual. El contrato acumuló ese valor a lo largo de meses en que era tratado como candidato probable, y el precio de hoy dice que el mercado ya no lo considera en la disputa.',

  'polymarketComparison.candidates[5].polymarket': '0,45%',
  'polymarketComparison.candidates[5].tendenciaPesquisa': `${VOX_ES} lo trae en 3,2% en la ${T1_ES}, prácticamente el mismo 3% de PoderData del 30 de julio y por encima del 2,8% de AtlasIntel del 29 de julio. En la encuesta está estable. En el frente partidario el día fue malo: Marcelo Aro dejó su fórmula al Senado para disputar el gobierno de Minas Gerais, movimiento que Zema llamó públicamente traición, y el Novo descartó a Barbosa como vice, encaminándose a una fórmula de un solo partido. Sigue SIN vice, con el plazo del 5 de agosto a menos de una semana.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': `CAE 0,10pp y llega a 0,45% (vol USD 4,58M), en la TERCERA rueda consecutiva de baja en el contrato de ganador, y queda en 4,45% en el book de tercer lugar de la ${T1_ES}. Salvedad de serie, y es grande: su máximo en la serie del AFOS es 10,10%, del 26 de abril, así que 0,45% es menos de un veinteavo de aquel nivel, y movimientos de 0,10pp en esa franja tienen valor informativo casi nulo.`,

  'polymarketComparison.candidates[6].polymarket': '0,30%',
  'polymarketComparison.candidates[6].tendenciaPesquisa': `La Vox Brasil del 31 de julio NO lo testea en ningún escenario, ni de ${T1_ES} ni de ${T2_ES}, así que no tiene encuesta nueva en esta ronda, y la ausencia de test en una nacional es información que el panel registra en vez de repetir el dato de la víspera como si fuera nuevo. La salvedad permanece y necesita decirse con claridad: él NO es candidato a la Presidencia, disputa el gobierno de São Paulo, y el escenario que lo favorece es hipótesis de encuesta y no candidatura en curso.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `SUBE 0,15pp y llega a 0,30%, duplicando el valor de la víspera, y llega a 1,00% en el book de segundo lugar de la ${T1_ES}, en la segunda rueda consecutiva de alza en ese contrato. La salvedad de escala es obligatoria: en un precio de 0,30%, un alza de 0,15pp tiene valor informativo casi nulo, y el movimiento solo se registra porque es el segundo día seguido en la misma dirección.`,
}

construir('polls-data', 'en', EN)
construir('polls-data', 'es', ES)
