/**
 * Mapa ES de 14/Ago para polls-data.json.
 * Convenções: vírgula decimal e ponto de milhar, como no pt-BR. Datas "14 de ago".
 */
import { construir } from '../build-locale-json'

const NOVO = 'lectura confirmada del 14 de ago, 14:46 BRT (17:46 UTC)'
const VELHO = 'última lectura confirmada, del 12 de ago, 16:41 BRT'
const SEM = `NO HAY LECTURA NUEVA PARA ÉL EL 14 DE AGO. El valor exhibido es el de la ${VELHO}`

construir('polls-data', 'es', {
  'approvalData.note':
    `LA NACIONAL MÁS RECIENTE SIGUE SIENDO LA DEL 13 DE AGO, porque la Quaest del 14 de ago aún no tenía resultado publicado en esta captura. PoderData/Aya: 43% aprueban y 50% desaprueban el trabajo de Lula, un saldo de 7pp negativos, contra 47,3% x 49,9% de Futura Inteligência del 11 de ago, que era el par vigente hasta ayer. ⚠️ SON DOS PREGUNTAS DISTINTAS EN EL MISMO DÍA, y el panel no las suma: la Revista Oeste informó 51% de desaprobación DEL GOBIERNO en el mismo relevamiento, número que no es el mismo que el 50% de desaprobación del TRABAJO DE LULA publicado por Poder360, CNN Brasil y Rádio Itatiaia. RECHAZO empatado en 48% para Lula y 48% para Flávio Bolsonaro. Siguen en el cuadro la Gerp del 11 de ago con 53% de desaprobación, BTG/Nexus del 10 de ago con 46% x 49%, Palver del mismo día con 45% x 55% y Genial/Quaest del 5 de ago con 48% x 47%. LO QUE MUESTRA EL CONJUNTO: en ocho lecturas de nueve días la desaprobación va de 47% a 55%, una distancia de 8pp entre casas, y el saldo va de 1pp positivo a 10pp negativo. Ninguna casa cambió de lado, y la nueva entra dentro del rango que ya existía. ⚠️ PROCEDENCIA DECLARADA: aprobación y desaprobación son de PoderData/Aya del 13 de ago (campo del 9 al 12 de ago, n=2.400, telefónica, margen 2pp, registro BR-06868/2026), por ser la lectura nacional más reciente; el 7% restante es el residuo aritmético entre los dos valores publicados, y no un número que la casa haya divulgado con esa etiqueta. La evaluación de la gestión, con 36% positiva, 26% regular y 36% negativa, sigue siendo la de Genial/Quaest del 5 de ago, porque ninguna casa posterior publicó esa apertura completa. El panel prefiere declarar la mezcla que esconderla.`,

  'polymarketComparison.note':
    `ACTUALIZACIÓN DEL 14 DE AGO. HAY LECTURA DE PRECIO NUEVA PARA EL MERCADO PRESIDENCIAL Y EL HECHO MAYOR DEL DÍA ES INSTITUCIONAL. En el precio, el líder está en 63,50% por sexto día consecutivo en la serie registrada, el segundo subió 0,20pp hasta 27,85% y fue el único nombre por encima de 1% que subió, Renan Santos cayó 0,30pp hasta 7,15% y Caiado subió 0,10pp hasta 1,05%. La distancia entre los dos primeros se estrechó de 35,85pp a 35,65pp, y todo el movimiento vino del segundo. Para los contratos de segundo y tercer lugar, para el Senado y para el impeachment en el STF no hay lectura nueva el 14 de ago, y los valores exhibidos son los del 12 de ago, 16:41 BRT. En las encuestas nada cambió: Quaest divulga hoy una nacional con 13 candidatos y los resultados no estaban publicados al momento de esta captura, así que sigue vigente la PoderData/Aya del 13 de ago. ⭐ EN LA NOCHE DEL 13 DE AGO EL TSE SUSPENDIÓ EL PROCESAMIENTO DE NUEVAS AFILIACIONES en el sistema Filia, tras la inclusión indebida del segundo en Missão y un intento contra la afiliación del líder que no llegó a concretarse, según Gazeta do Povo y Brasil de Fato. El tribunal declaró que NO hubo hackeo, sino uso indebido de la herramienta por parte de alguien que tenía las credenciales del partido. La candidatura presidencial del segundo fue registrada horas después de la decisión, según Brasil de Fato el 14 de ago. El plazo de registro termina el 15 de ago.`,

  'polymarketComparison.sources':
    `Precios de Polymarket vía proxy AFOS, y el panel solo publica precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen. El 14 de ago hay lectura confirmada nueva para el mercado presidencial, a las 14:46 BRT (17:46 UTC). Para los contratos de segundo y tercer lugar, para el Senado y para el impeachment en el STF no hay lectura nueva el 14 de ago, y los valores exhibidos son los de la última lectura confirmada, a las 16:41 BRT del 12 de ago. ✅ ENCUESTAS: Quaest divulga el 14 de ago una nacional con 13 candidatos probados (n=2.004, BR-06773/2026) y los resultados no estaban publicados al momento de esta captura, así que sigue vigente la PoderData/Aya del 13 de ago, n=2.400, registro BR-06868/2026, campo del 9 al 12 de ago. Siguen vigentes la CNT/MDA BR-06935/2026, la Gerp BR-08045/2026 y la Futura Inteligência BR-08109/2026, todas del 11 de ago, más la Palver BR-06596/2026 y la BTG/Nexus BR-08428/2026, del 10 de ago, y la Genial/Quaest BR-06591/2026 y la Meio/Ideia BR-04579/2026, del 5 de ago. Próximas nacionales en la fila: Quaest (n=2.004, BR-06773/2026), con publicación prevista para el 14 de ago y aún sin resultado divulgado al momento de esta captura, Nexus (n=2.000, BR-03317/2026) el 17 de ago y Real Time Big Data (n=1.600, BR-05423/2026) el 19 de ago.`,

  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 14 DE AGO HASTA EL MOMENTO DE ESTA CAPTURA. Quaest divulga hoy una nacional con 13 candidatos probados, y los resultados aún no estaban publicados. Sigue vigente la PoderData/Aya del 13 de ago (n=2.400, telefónica, campo del 9 al 12 de ago, BR-06868/2026): 41% en la primera vuelta y 46% x 45% en el balotaje contra Flávio Bolsonaro. Su hallazgo sigue siendo válido y separa las dos vueltas: en la primera vuelta la distancia no se movió en cuatro semanas, fueron 6pp el 16 de jul, 6pp el 30 de jul y son 6pp ahora; en el balotaje la distancia cayó de 3pp a 1pp en el mismo intervalo. RECHAZO en 48%, empatado con el de su adversario. APROBACIÓN PERSONAL en 43% contra 50% de desaprobación. Sumando las ocho nacionales desde el 5 de ago va de 38% a 44% en la primera vuelta.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `LECTURA NUEVA EL 14 DE AGO, ${NOVO}. En 63,50% (vol USD 8,25M acumulado), el MISMO valor de la lectura del 12 de ago. La serie registrada muestra 63,50% en todos los días del 9 al 14 de ago, seis días sin variación. SALVEDAD DE SERIE, medida sobre todos los puntos registrados y no sobre el último de cada día: entre los puntos desde el 16 de may el máximo es 66,50%, el 1 de ago a las 23:00, y el piso es 39,50%, el 26 de may. La distancia hacia el segundo se estrechó 0,20pp desde el 12 de ago, y el movimiento fue enteramente del adversario.`,

  'polymarketComparison.candidates[1].polymarket': `27,85%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 14 DE AGO HASTA EL MOMENTO DE ESTA CAPTURA. Sigue vigente la PoderData/Aya del 13 de ago, que le da 35% en la primera vuelta y 45% en el balotaje, a 1pp del líder, dentro del margen de 2pp. Contra su propia casa NO se movió en la primera vuelta, repitiendo el 35% del 30 de jul, pero ESTRECHÓ EL BALOTAJE de 43% a 45%. RECHAZO en 48%, exactamente igual al del líder. En las ocho nacionales desde el 5 de ago va de 28,7% a 38% en la primera vuelta, y la amplitud entre casas sobre la misma pregunta sigue por encima de 9pp, el doble de la medida sobre el líder.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `LECTURA NUEVA EL 14 DE AGO, ${NOVO}. En 27,85% (vol USD 8,20M acumulado). El precio pasó de 27,65% el 12 de ago a 27,85% ahora, un alza de 0,20pp. ⭐ Fue el ÚNICO nombre por encima de 1% que subió en esta lectura, y toda la reducción de la distancia hacia el líder vino de él. SALVEDAD DE SERIE, medida sobre todos los puntos registrados: entre los puntos desde el 16 de may, 51 tuvieron un valor igual o superior a 27,85%, con un máximo de 33,20% el 2 de jun a las 19:30 y un piso de 22,00% el 3 de jul a las 01:00. ⚠️ El alza cae en la misma ventana en que se removió el obstáculo registral a su candidatura, y el panel registra el orden sin afirmar causa.`,

  'polymarketComparison.candidates[2].polymarket': `7,15%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `Sus porcentajes de primera vuelta no aparecieron en las notas sobre la PoderData del 13 de ago, así que la lectura más reciente sobre él sigue siendo la del 11 de ago. Siguen valiendo el 5% de la Gerp, el 4% de Genial/Quaest y de BTG/Nexus, el 4,7% de Meio/Ideia y el 10% de Palver por internet. En el escenario de balotaje de la PoderData él es el ÚNICO de los cuatro probados al que el líder vence, según Bnews, mientras los otros tres empatan. El efecto de método sigue siendo la lectura sobre él: el mismo nombre va de 4% a 10% según el ambiente de la entrevista, y la salvedad fue declarada por la propia Palver.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `LECTURA NUEVA EL 14 DE AGO, ${NOVO}. En 7,15% (vol USD 9,59M acumulado). El precio pasó de 7,45% el 12 de ago a 7,15% ahora, una caída de 0,30pp. Fue la MAYOR CAÍDA entre los nombres por encima de 1% en esta lectura. Mantiene el mayor volumen acumulado del libro presidencial entre los nombres por encima de 1%. El precio sigue posicionado ENTRE los dos métodos de las encuestas, por encima del 4% a 5% del teléfono y del presencial y por debajo del 10% de internet.`,

  'polymarketComparison.candidates[3].polymarket': `1,05%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `Sigue vigente la PoderData del 13 de ago, que lo pone en EMPATE con el líder en el balotaje, según CNN Brasil y Bnews, junto a Flávio Bolsonaro y a Zema. Sus porcentajes de primera vuelta en esa ronda no aparecieron en las notas capturadas, y siguen valiendo el 4% de la Gerp y de Genial/Quaest, el 5,7% de Meio/Ideia y el 5% de BTG/Nexus. El empate en el balotaje es el segundo suyo en cuatro días, después del de BTG/Nexus del 10 de ago.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `LECTURA NUEVA EL 14 DE AGO, ${NOVO}. En 1,05% (vol USD 5,70M acumulado). El precio pasó de 0,95% el 12 de ago a 1,05% ahora, un alza de 0,10pp. Es el único del pelotón con lectura nueva en esta ronda, porque los demás están por debajo del corte de 0,5% que el panel usa para separar precio de ruido. ⚠️ SU CONTRASTE SIGUE SIENDO EL MAYOR DEL PANEL: empata con el líder en el balotaje de una nacional y está valorado en poco más de 1% para ganar la elección. Empatar en el balotaje y ganar la elección son preguntas distintas, y el panel no las suma.`,

  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `${SEM}, en 0,05% (vol USD 13,91M acumulado), por debajo del corte de 0,5% que el panel usa para separar precio de ruido. Sigue siendo el mayor volumen acumulado de todo el libro presidencial, con el precio en el piso. Volumen alto con probabilidad en el piso es convicción ya descontada, no movimiento, y las variaciones en esta franja tienen un valor informativo casi nulo.`,

  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `${SEM}, en 0,35% (vol USD 5,07M acumulado), por debajo del corte de 0,5% que el panel usa para separar precio de ruido. ⚠️ SU CONTRASTE PERMANECE: empata con el líder en el balotaje de la PoderData del 13 de ago y está valorado en 0,35% para ganar la elección.`,

  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `${SEM}, en 0,15% (vol USD 7,06M acumulado), por debajo del corte de 0,5%. Una variación en esta franja no tiene valor informativo, y la salvedad de fondo permanece: él NO es candidato a la Presidencia y compite por la gobernación de São Paulo.`,
})
