/**
 * Mapa EN de 16/Ago para polls-data.json.
 * Convenções: ponto decimal e vírgula de milhar.
 */
import { construir } from '../build-locale-json'

const CAR = 'confirmed reading of Aug 16, 4:56 pm BRT (7:56 pm UTC)'

construir('polls-data', 'en', {
  'polls[0].note':
    `Genial/Quaest national poll released Aug 14 at 9:00 pm (G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, Correio Braziliense). First round Lula 38% x Flávio Bolsonaro 31%, a gap of 7pp, with Renan Santos and Ronaldo Caiado at 4% and Augusto Cury and Romeu Zema at 2%. Runoff Lula 43% x Flávio 40%, 3pp, with a margin of 2pp. ⭐ THE COMPARISON THAT COUNTS IS AGAINST THE HOUSE ITSELF, AND IT IS SYMMETRICAL: against the Quaest of Aug 5, the first round moved from 39% x 30% to 38% x 31% and the runoff moved from 44% x 39% to 43% x 40%. In both rounds Lula gave up 1 point and Flávio gained 1 point, and each gap narrowed by 2pp. Same house, same in-person method and same sample. REJECTION broken out for the first time in this window: Flávio 54%, Lula 52% and Caiado 35%, the last with high unfamiliarity declared by the house. GOVERNMENT ASSESSMENT: 46% approve and 48% disapprove; on the excellent/good, fair and poor/terrible scale, it is 36% positive, 25% fair and 37% negative, according to InfoMoney and UOL. ⭐ CROSSTABS RELEASED LATER, ON AUG 15 AND 16: how firm the vote is, with 77% of Lula's voters calling the decision final and 22% saying they could still change, and Zema's electorate emerging as the least convinced in the field, according to G1; and behaviour among independents, a segment where Flávio marks 35% against 29% for Lula in the runoff, according to O Globo. ⚠️ The electoral court records the field as Aug 10 to 13 and the house published Aug 10 to 12; the panel displays the registered period.`,
  'polls[0].source':
    `Genial/Quaest via G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, UOL and Correio Braziliense, Aug 14 to 16`,

  'approvalData.note':
    `NO NEW NATIONAL POLL ON AUG 16. The Genial/Quaest of Aug 14, released at 9:00 pm, remains in force: 46% approve and 48% disapprove of the Lula government, a negative balance of 2pp and a statistical tie given the 2pp margin, against 43% x 50% from the PoderData/Aya of Aug 13. ⚠️ THAT IS TWO HOUSES IN TWO DAYS WITH 5 POINTS OF DIFFERENCE IN THE BALANCE, and the panel does not pick between them: the distance between houses is the finding. On the excellent/good, fair and poor/terrible scale, the Quaest brings 36% positive, 25% fair and 37% negative, according to InfoMoney and UOL. REJECTION in the same poll: Flávio Bolsonaro 54%, Lula 52% and Ronaldo Caiado 35%, the last with high unfamiliarity declared by the house. ⭐ A crosstab released on Aug 15 adds the FIRMNESS of the vote, a different dimension from its level: among Lula's voters, 77% say the decision is final and 22% say they could still change, and the least convinced electorate in the field belongs to Romeu Zema, according to G1. 📅 Nexus publishes on Aug 17 and Real Time Big Data on Aug 19, both with fieldwork under way.`,

  'polymarketComparison.note':
    `UPDATE OF AUG 16, FIRST DAY OF THE OFFICIAL CAMPAIGN. THE ENTIRE MOVE OF THE DAY SITS IN THE PRICE, because no new national poll came out. The leader rose 2.00pp and closed at 66.50%, a value that MATCHES the top of a 174-point series running since May 19, with no point above it. The runner-up rose 1.30pp and closed at 29.45%, a third straight day of gains, and even so the gap between them WIDENED, from 36.35pp to 37.05pp. ⚠️ CAUSATION, and the panel states this before any reading: the points that produced the rise were recorded at 5:01 am BRT, BEFORE the campaign rallies of the day. The price moved going into the first day of campaigning, and NOT in reaction to the rallies. ⛔ No undue superlative: the 37.05pp gap is ordinary in the series, with 30 of the 89 days recording an equal or larger value and a peak of 41.80pp on Aug 1. ⭐ THE FINDING IS ABOUT CONTRACTS, NOT LEVELS. The chasing pack's leader fell to 4.70% on VICTORY, a third straight lower close since the 8.00% close of Aug 11, and in the THIRD-PLACE contract stands at 53.00%, still the highest probability in that book but falling from the 65.00% of Aug 9. Ronaldo Caiado fell 0.45pp on victory and ROSE 6.50pp on placing, with third place going from 31.00% at the Aug 12 close to 37.50%. ⛔ Finishing third and winning the election are different questions, and the panel does not add them together. ⭐ IN THE POLLING THE NEWS IS ABOUT FIRMNESS: a Quaest crosstab released on Aug 15 shows 77% of the leader's voters calling the decision final and points to Romeu Zema's electorate as the least convinced in the field, according to G1. 📌 The panel records that both instruments separated the same two groups in this window, and recording the coincidence is not asserting that one explains the other.`,
  'polymarketComparison.sources':
    `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm. On Aug 16 there is a new confirmed reading for EVERY tracked contract, at 4:56 pm BRT (7:56 pm UTC): presidential, runner-up, third place, Senate and Supreme Court impeachment. Polls registered with the electoral court and released by the houses, with reporting from G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, UOL, O Globo and Correio Braziliense.`,

  'polymarketComparison.candidates[0].polymarket': `66.50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON AUG 16. The Genial/Quaest of Aug 14 still stands with 38% in the first round and 43% in the runoff, and that 38% is the FLOOR of the nine national polls since Aug 5, whose range runs from 38% to 44%. Rejection of 52%, below his rival's 54%. ⭐ NEW CROSSTAB RELEASED ON AUG 15, and it measures FIRMNESS rather than level: among his voters, 77% say the decision to vote for him is final and 22% say they could still change, according to G1. It is the first time the panel records the hardness of the intention, a different dimension from its size.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `⭐ UP 2.00pp ON AUG 16, from 64.50% to 66.50% (vol USD 8.40M cumulative), ${CAR}. The value MATCHES THE TOP OF THE SERIES: among the 174 points recorded since May 19 NONE sits above 66.50%, and the only other day at that level was Aug 1. ⛔ The panel says matches, not beats. The gap to the runner-up WIDENED, from 36.35pp to 37.05pp. ⚠️ CAUSATION: the point was recorded at 5:01 am BRT, BEFORE the campaign rallies of the day, so the move precedes the rallies and is not a reaction to them.`,

  'polymarketComparison.candidates[1].polymarket': `29.45%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON AUG 16. The Genial/Quaest of Aug 14 still stands with 31% in the first round and 40% in the runoff, having gained 1 point in each against the house's own Aug 5 reading, and it is the first national poll to show him narrowing both rounds. REJECTION of 54%, the highest in the field. ⭐ In the crosstabs released afterwards: the vote for him ranks among the two most settled in the field, according to G1, and among independent voters he marks 35% against 29% for the leader in the runoff, according to O Globo.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `UP 1.30pp ON AUG 16, from 28.15% to 29.45% (vol USD 8.34M cumulative), ${CAR}, on a third straight day of gains. ⚠️ Even while rising he ended up FURTHER from the leader, because the leader gained 2.00pp and the gap widened to 37.05pp. ⛔ No superlative: of the 173 points since May 19, 4 were higher, and the top remains 33.20%, from Jun 2. He keeps 87.00% in the first-round runner-up contract, the highest value in that book.`,

  'polymarketComparison.candidates[2].polymarket': `4.70%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON AUG 16. The Genial/Quaest of Aug 14 keeps him at 4% in the first round, exactly the same value as Aug 5, that is, nine days without progress against the house's own yardstick. Gerp's 5%, BTG/Nexus's 4%, Meio/Ideia's 4.7% and Palver's 10% by internet still stand. The method effect remains the reading on him: the same name runs from 4% to 10% depending on the interview setting, and the caveat was declared by Palver itself.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `🔴 DOWN 2.45pp ON AUG 16, to 4.70% (vol USD 9.77M cumulative), ${CAR}, with a BREAK BELOW 5% on the third straight lower close, since the 8.00% close of Aug 11. ⭐ And the PLACING contract tells another story: in first-round third place he stands at 53.00%, still the highest probability in that book, but ALSO FALLING, because it was 65.00% on Aug 9, that is, 12.00pp lost in seven days. He loses ground on both questions at once, and the panel does not add them together. He keeps the largest cumulative volume in the presidential book among names above 1%.`,

  'polymarketComparison.candidates[3].polymarket': `0.60%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON AUG 16. The Genial/Quaest of Aug 14 gives him 4% in the first round, the same as Aug 5, and REJECTION of 35%, the lowest in the field, against the 54% and 52% of the top two. ⚠️ Low rejection with high unfamiliarity is NOT acceptance: it means most of the electorate has not yet formed an opinion, and an unformed opinion can go either way. He still ties with the leader in the runoff of the PoderData of Aug 13.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `⭐ THE CONTRACT CROSSING OF THE DAY. In the VICTORY price he fell 0.45pp on Aug 16, from 1.05% to 0.60% (vol USD 5.92M cumulative), ${CAR}, brushing the 0.5% cutoff the panel uses to separate price from noise. In the PLACING contract he ROSE: first-round third place went from 31.00%, at the Aug 12 close, to 37.50%, a 6.50pp gain with four straight higher closes. ⛔ Finishing third and winning the election are different questions, and the panel neither adds them nor treats one as a rebuttal of the other.`,

  'polymarketComparison.candidates[4].tendenciaPesquisa':
    `No national poll in the window tests him in a presidential scenario, and the absence of a test is information the panel records instead of repeating old data. ⭐ On Aug 16 he opened a campaign for RE-ELECTION as governor of São Paulo, which settles the question by public act rather than by inference.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `FLAT AT 0.05% on Aug 16 (vol USD 13.92M cumulative), ${CAR}, below the 0.5% cutoff. It remains the largest cumulative volume in the entire presidential book, with the price at the floor, which is conviction already priced in rather than movement. ⭐ The panel's caveat became a DATED PUBLIC ACT: on Aug 16 he formally opened his campaign for RE-ELECTION as governor of São Paulo, in Osasco, according to O Globo and Folha de S.Paulo, and without the presence of the presidential candidate backed by the same camp.`,

  'polymarketComparison.candidates[5].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON AUG 16. The Genial/Quaest of Aug 14 keeps him at 2% in the first round, the same value as Aug 5. Gerp's 2%, BTG/Nexus's 3% and Meio/Ideia's 2.6% still stand. 🔴 NEW CROSSTAB RELEASED ON AUG 15: he has the LEAST CONVINCED electorate in the field, according to G1, which speaks to how solid the support is rather than how large it is.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `DOWN 0.20pp on Aug 16, from 0.35% to 0.15% (vol USD 5.49M cumulative), ${CAR}, below the 0.5% cutoff. In the first-round third-place contract he has 5.00%, far behind the 53.00% of the chasing pack's leader. He opened the campaign with a mass in Montes Claros, in northern Minas Gerais, promising a maximum-security prison and criticising Supreme Court justices, according to Folha de S.Paulo and Valor Econômico.`,

  'polymarketComparison.candidates[6].tendenciaPesquisa':
    `No national poll in the window includes him in a presidential scenario. ⭐ On Aug 16 he opened a campaign for the GOVERNORSHIP OF SÃO PAULO and spoke at the president's opening rally in the ABC region, according to O Globo and Times Brasil, which confirms by a dated public act that he is not running for President.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `DOWN 0.10pp on Aug 16, from 0.15% to 0.05% (vol USD 7.09M cumulative), ${CAR}, below the 0.5% cutoff, and variation in that band carries no informational value. ⭐ The panel's caveat became a DATED PUBLIC ACT: on Aug 16 he formally opened a campaign for the GOVERNORSHIP OF SÃO PAULO and spoke at the president's opening rally in the ABC region, according to O Globo and Times Brasil. He is not a presidential candidate, and a presidential scenario that includes him is a polling hypothesis.`,
})
