/**
 * Mapa ES de polls-data.json — /atualizar-brz 03/Ago/2026.
 *
 * Convenções travadas do ES: vírgula decimal e ponto de milhar, iguais ao pt-BR.
 * `pesquisa` é `encuesta`; `estadual` é `estatal`; `parado` (sem movimento) é
 * `quieto` ou `estancado`, nunca `parado`, que em ES é desempregado; o verbo de
 * mercado é `descontar`, nunca `precificar`.
 */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/es/glossary#${id})`

construir('polls-data', 'es', {
  'polls[0].note':
    `Encuesta nacional ${G('BTG/Nexus', 'nexus-btg')} divulgada el 03/Ago, 8ª ronda de la serie, y la primera de las cuatro nacionales que el registro del ${G('TSE', 'tse')} preveía entre el 03 y el 05/Ago. 1ª vuelta Lula 41% x Flávio 37%, con Caiado en 5%, Renan Santos en 4% y Zema en 3%. 2ª vuelta Lula 46% x Flávio 45%, diferencia de 1pp que queda DENTRO del margen de 2pp y por eso es ${G('empate técnico', 'empate-tecnico')}. Trabajo de campo del 31/Jul al 02/Ago, n=2.002, telefónica, margen 2pp, 95% de confianza, registro BR-02874/2026. LO QUE CAMBIA LA SEMANA ES LA COMPARACIÓN CON LA PROPIA CASA: la diferencia de la 1ª vuelta CAYÓ DE 9pp A 4pp en una sola ronda, contra el 42% x 33% del 27/Jul. Y el movimiento viene casi todo de un lado, porque LULA CEDIÓ 1pp y FLÁVIO SUBIÓ 4pp. En la 2ª vuelta el ajuste es aún más fuerte, de 4pp a 1pp, con Lula pasando de 47% a 46% y Flávio de 43% a 45%. Las otras 2ª vueltas de la ronda: Lula 46% x Caiado 42%, Lula 46% x Zema 40% y Lula 47% x Renan Santos 37%. FRENTE A LAS OTRAS CASAS, entre las cuatro nacionales divulgadas desde el 29/Jul esta es la que muestra la 1ª vuelta más ajustada: 4pp aquí, contra 6pp en PoderData del 30/Jul, 9,1pp en ${G('AtlasIntel', 'atlasintel')} del 29/Jul y 9,3pp en Vox Brasil del 31/Jul. La distancia entre la lectura más alta y la más baja llega a 5,3pp y es mayor que cualquier movimiento de precio del período. ⚠️ RECHAZO NO PUBLICADO POR ESTE PANEL: las fuentes secundarias DISCREPAN. Poder360, CNN Brasil y Correio Braziliense reportan 49% para cada uno de los dos; Money Times reporta 50% para Lula y 51% para Flávio. La nota de divulgación del instituto no trae el dato, así que no se pudo cerrar en fuente primaria y el número queda fuera, con la discrepancia declarada aquí. Esta ronda tampoco publicó aprobación ni desaprobación del gobierno.`,
  'polls[0].source':
    `BTG/Nexus vía el sitio del propio instituto (nexus.fsb.com.br), Folha de S.Paulo, Estadão, CNN Brasil, JOTA, CartaCapital, Poder360, VEJA, Exame, Correio Braziliense y Money Times 03/Ago. Registro TSE BR-02874/2026.`,
  'polymarketComparison.note':
    `Cruce del 03/Ago, captura trabada de las 19:11 UTC, aprobada solo en el TERCER intento: los dos primeros fueron BLOQUEADOS por el libro de 2º lugar, que osciló 0,50pp entre lecturas separadas por ocho minutos. El día trae un cruce raro, porque las DOS mediciones se movieron hacia el MISMO LADO y por el MISMO MOTIVO. ${G('BTG/Nexus', 'nexus-btg')} publicó hoy y su diferencia de 1ª vuelta cayó de 9pp a 4pp contra la propia ronda del 27/Jul, con Lula cediendo 1pp y Flávio subiendo 4pp. En el mercado, la diferencia se cerró de +40,95pp a +40,05pp, y se cerró exactamente del mismo modo: LULA QUEDÓ QUIETO en 65,50% (vol USD 7,92M) y FLÁVIO SUBIÓ 0,90pp, hasta 25,45% (vol USD 7,86M). En la serie diaria, la diferencia no quedaba por debajo de eso desde el 30/Jul, cuando marcó +39,50pp. Conviene registrar lo que esto NO es: convergencia de NIVEL. El mercado paga 65,50% de probabilidad de victoria y la encuesta mide 41% de intención de voto en 1ª vuelta, y esas dos magnitudes ni se restan ni se comparan en nivel. Lo que coincidió fue DIRECCIÓN y CAUSA, ambas ajustándose por el avance del mismo nombre. EL TECHO DE LA SERIE SIGUE ATRÁS: el máximo de Lula es 66,50% y el de la diferencia es +41,80pp, ambos del cierre del 01/Ago. El techo de Flávio en la serie es bastante más antiguo y bastante más alto, 45,20% el 07/May, y el piso es 22,00% el 03/Jul, así que el 25,45% de hoy es recuperación dentro de un nivel rebajado, no retorno al nivel anterior. RENAN SANTOS cayó 0,50pp hasta 7,45% (vol USD 8,86M), deshaciendo la subida de ayer, y su encuesta en la ronda de Nexus dio 4%, lo que deja la distancia entre precio y encuesta en 3,45pp. CAIADO está en 1,15% (vol USD 5,30M) el día en que fue oficializado candidato en convención y prometió amnistiar a Bolsonaro. HADDAD cayó de 0,30% a 0,15%. El contrato de 2º lugar tiene a Flávio en 80,50% y el de 3º lugar tiene a Renan en 60,50% contra Caiado en 25,00%.`,
  'polymarketComparison.sources':
    `${G('Polymarket', 'polymarket')} vía el proxy de AFOS, captura trabada de las 19:11 UTC del 03/Ago (scripts/capture-guard.ts, 2 lecturas separadas por 8 minutos con tolerancia de 0,20pp). Encuesta BTG/Nexus del 03/Ago, registro TSE BR-02874/2026, vía nexus.fsb.com.br. Serie de mercado verificada en dos ventanas, por el techo de 1.000 puntos de la ruta de histórico.`,
  'polymarketComparison.candidates[0].pesquisaRange': `41-46%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `ENCUESTA NUEVA Y SE AJUSTÓ. ${G('BTG/Nexus', 'nexus-btg')} del 03/Ago (n=2.002, campo del 31/Jul al 02/Ago, telefónica, margen 2pp, BR-02874/2026) da 41% en 1ª vuelta, contra 42% en la propia ronda del 27/Jul, y 46% en la 2ª vuelta contra Flávio, contra 47% antes. Las dos caídas son de 1pp y quedan dentro del margen, es decir, aisladas no son movimiento. Lo que sí es movimiento es el otro lado: Flávio subió 4pp en 1ª vuelta y 2pp en la 2ª en la misma ronda, y por eso la diferencia cayó de 9pp a 4pp y la 2ª vuelta se volvió ${G('empate técnico', 'empate-tecnico')} de 1pp. Entre las cuatro nacionales divulgadas desde el 29/Jul, esta es la que muestra la 1ª vuelta más ajustada: 4pp aquí, 6pp en PoderData del 30/Jul, 9,1pp en ${G('AtlasIntel', 'atlasintel')} del 29/Jul y 9,3pp en Vox Brasil del 31/Jul.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `QUIETO en 65,50% (vol USD 7,92M), por segunda rueda seguida, en la captura trabada de las 19:11 UTC. La diferencia sobre Flávio se cerró 0,90pp y fue a +40,05pp, pero se cerró SIN que el favorito cediera: el movimiento entero es del rival. En la serie diaria, la diferencia no quedaba por debajo de eso desde el 30/Jul, cuando marcó +39,50pp. El techo de la serie sigue siendo 66,50%, del cierre del 01/Ago.`,
  'polymarketComparison.candidates[1].pesquisaRange': `31-45%`,
  'polymarketComparison.candidates[1].polymarket': `25,45%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `EL MOVIMIENTO DEL DÍA ES SUYO. ${G('BTG/Nexus', 'nexus-btg')} del 03/Ago da 37% en 1ª vuelta, contra 33% en la ronda del 27/Jul de la misma casa, subida de 4pp que es el DOBLE del margen de 2pp y por lo tanto no se explica por ruido muestral. En la 2ª vuelta pasa de 43% a 45% y queda a 1pp de Lula, dentro del margen, lo que caracteriza ${G('empate técnico', 'empate-tecnico')}. La lectura necesita contexto de casa: las otras tres nacionales desde el 29/Jul dan diferencias de 6pp a 9,3pp en 1ª vuelta, así que esta es la más favorable a él, y la distancia entre la lectura más alta y la más baja llega a 5,3pp.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `SUBIÓ 0,90pp hasta 25,45% (vol USD 7,86M), el movimiento más fuerte de la rueda entre los dos primeros. Se movió en el MISMO SENTIDO que la encuesta y el mismo día, algo raro en este panel. Salvedad de serie, y importa: su techo es 45,20% del 07/May y su piso es 22,00% del 03/Jul, así que 25,45% es recuperación dentro de un nivel rebajado, no retorno al nivel anterior. En el contrato de 2º lugar está en 80,50%.`,
  'polymarketComparison.candidates[2].polymarket': `7,45%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `${G('BTG/Nexus', 'nexus-btg')} del 03/Ago da 4%, contra 5% en la ronda del 27/Jul de la misma casa. Sigue en la franja de 3% a 4% que los institutos vienen midiendo desde fines de julio, tras el 7,8% de ${G('AtlasIntel', 'atlasintel')} del 29/Jul. En la 2ª vuelta contra Lula es la peor de las cuatro simulaciones de la ronda: 47% x 37%.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `CAYÓ 0,50pp hasta 7,45% (vol USD 8,86M), deshaciendo la subida de 0,35pp de ayer, que había interrumpido nueve ruedas seguidas de baja. Con la encuesta en 4%, la distancia entre precio y encuesta queda en 3,45pp. Su volumen acumulado, de USD 8,86M, está por encima del de Lula, que tiene USD 7,92M, aunque el precio sea un octavo. Es el favorito del contrato de 3º lugar, con 60,50%.`,
  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `${G('BTG/Nexus', 'nexus-btg')} del 03/Ago da 5% en 1ª vuelta, contra 6% en la ronda del 27/Jul de la misma casa. En la 2ª vuelta contra Lula, 46% x 42%. Entre las nacionales desde el 29/Jul, queda solo detrás del 5,5% de Vox Brasil del 31/Jul.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `En 1,15% (vol USD 5,30M), por encima del piso de 0,90% que la serie tocó dentro del día 02/Ago. El nivel se sostiene el día en que fue oficializado candidato en convención, prometió amnistiar a Bolsonaro y a los condenados del 8 de Enero, y disputó con Flávio el voto del agronegocio. Es el segundo nombre del contrato de 3º lugar, con 25,00%.`,
  'polymarketComparison.candidates[6].polymarket': `0,15%`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `RETROCEDIÓ 0,15pp y está en 0,15% (vol USD 6,64M). Él no es candidato y el contrato descuenta un escenario de sustitución, así que el nivel habla de percepción de riesgo sobre la fórmula del ${G('PT', 'pt')}, no de una disputa en curso.`,
})
