/**
 * Mapas EN e ES do polls-data.json para a publicação de 30/Jul 17:08.
 *
 * approvalData.note e .source são PREFIXO NOVO + texto de ontem. Em vez de
 * retraduzir o texto de ontem, este mapa LÊ a tradução já publicada e a compõe
 * com o prefixo novo. Precisa ler ANTES do construir(), que sobrescreve o arquivo.
 */
import { readFileSync } from 'fs'
import { construir } from '../build-locale-json'

const velhoEN = JSON.parse(readFileSync('public/polls-data.en.json', 'utf-8'))
const velhoES = JSON.parse(readFileSync('public/polls-data.es.json', 'utf-8'))

const G = (l: 'en' | 'es', id: string, txt: string) => `[${txt}](/${l}/glossary#${id})`
const T1_EN = G('en', 'primeiro-turno', 'first round')
const T1a_EN = G('en', 'primeiro-turno', 'first-round')
const T2_EN = G('en', 'segundo-turno', 'runoff')
const T1_ES = G('es', 'primeiro-turno', 'primera vuelta')
const T2_ES = G('es', 'segundo-turno', 'segunda vuelta')
const STF_EN = G('en', 'stf', 'STF')
const STF_ES = G('es', 'stf', 'STF')
const TSE_EN = G('en', 'tse', 'TSE')
const TSE_ES = G('es', 'tse', 'TSE')

const PODER2_EN = 'PoderData/Aya of Jul 30 (n=2,400, field Jul 26 to 29, 2pp margin, BR-07845/2026, telephone, 677 municipalities across the 27 states)'
const PODER2_ES = 'PoderData/Aya del 30 de julio (n=2.400, campo del 26 al 29 de julio, margen de 2pp, BR-07845/2026, telefónica, 677 municipios en los 27 estados)'
const PODER_EN = 'PoderData/Aya of Jul 30 (n=2,400, field Jul 26 to 29, 2pp margin, 95% confidence, BR-07845/2026, telephone on mobile and landline, 677 municipalities across the 27 states)'
const PODER_ES = 'PoderData/Aya del 30 de julio (n=2.400, campo del 26 al 29 de julio, margen de 2pp, 95% de confianza, BR-07845/2026, telefónica en celular y fijo, 677 municipios en los 27 estados)'

const REGUA_EN = `The comparison that counts is PoderData against itself, and there the ${T1a_EN} gap did NOT move: it was 6pp on Jul 16 (40% to 34%) and it is 6pp now (41% to 35%), with the top two each gaining 1pp, inside the 2pp margin. The tightening only shows up if the ruler is swapped mid-measurement, comparing today's PoderData with yesterday's AtlasIntel, which gave 9.1pp. That is a house effect, not movement, and the panel does not add the two together.`
const REGUA_ES = `La comparación que vale es la de PoderData contra sí misma, y allí la brecha de la ${T1_ES} NO se movió: eran 6pp el 16 de julio (40% x 34%) y son 6pp ahora (41% x 35%), con los dos primeros subiendo 1pp, dentro del margen de 2pp. El estrechamiento solo aparece si se cambia de regla en medio de la medición, comparando la PoderData de hoy con la AtlasIntel de ayer, que dio 9,1pp. Eso es efecto de casa, no movimiento, y el panel no suma las dos.`

const TRAVA_EN = 'The double-reading capture guard ran once and APPROVED with no divergence at all across the five books it covers, which had not happened since Jul 28: it blocked on both of the previous rounds. Every price goes in FIRM, with no declared range.'
const TRAVA_ES = 'La traba de doble lectura corrió una vez y APROBÓ sin ninguna divergencia en los cinco books cubiertos, lo que no ocurría desde el 28 de julio: en las dos rondas anteriores bloqueó. Todos los precios entran FIRMES, sin franja declarada.'

const PREFIXO_APROV_EN = `TWO HOUSES, TWO OPPOSITE SIGNALS IN THE SAME WEEK. PoderData/Aya of Jul 30 (field Jul 26-29, n=2,400, telephone, 2pp margin, BR-07845/2026) has Lula's personal approval at 43% against 49% disapproval, down 3pp and up 2pp against the institute's own Jul 22 round, and the GOVERNMENT rating at 44% against 50%. Twenty-four hours earlier, AtlasIntel measured approval RISING 1.7pp. The panel CONTINUES to show AtlasIntel on the gauge, by the criterion it published on Jul 29, the largest sample and the smallest margin in the window, and records the divergence here without arbitrating which of the two is right. Adding up the week's readings, Lula's approval sits in a band between 43% and 49%, wider than the 47% to 49% recorded on Jul 29, and it is PoderData that widens it from below. On MANAGEMENT, PoderData brings 34% good or very good, 16% fair and 47% poor or terrible, with poor or terrible up 10pp against Jul 22, a big jump for two weeks. And its REJECTION reading TIES Lula and Flávio at 49%, when AtlasIntel of Jul 29 gave 49.4% against 52.9%: the asymmetry the panel had been recording as a structural constraint on Flávio's candidacy did not appear in this reading. --- `
const PREFIXO_APROV_ES = `DOS CASAS, DOS SEÑALES OPUESTAS EN LA MISMA SEMANA. La PoderData/Aya del 30 de julio (campo 26-29 de julio, n=2.400, telefónica, margen de 2pp, BR-07845/2026) da la aprobación personal de Lula en 43% contra 49% de desaprobación, una caída de 3pp y un alza de 2pp contra la ronda del 22 de julio del propio instituto, y la evaluación del GOBIERNO en 44% contra 50%. Veinticuatro horas antes, AtlasIntel medía la aprobación SUBIENDO 1,7pp. El panel SIGUE exhibiendo AtlasIntel en el medidor, por el criterio que publicó el 29 de julio, la mayor muestra y el menor margen del recorte, y registra aquí la divergencia sin arbitrar cuál de las dos está en lo cierto. Sumando las lecturas de la semana, la aprobación de Lula está en una franja entre 43% y 49%, más ancha que la de 47% a 49% registrada el 29 de julio, y es PoderData la que la ensancha por abajo. En la GESTIÓN, PoderData trae 34% de óptima o buena, 16% de regular y 47% de mala o pésima, con la mala o pésima subiendo 10pp contra el 22 de julio, un salto grande para dos semanas. Y su RECHAZO EMPATA a Lula y a Flávio en 49%, cuando la AtlasIntel del 29 de julio daba 49,4% contra 52,9%: la asimetría que el panel venía registrando como restricción estructural de la candidatura de Flávio no apareció en esta lectura. --- `

const PREFIXO_SRC_EN = 'PoderData/Aya (Jul 30, 2026, field Jul 26-29, n=2,400, telephone, 2pp margin, BR-07845/2026, approve 43% x disapprove 49%, government 44% x 50%, management 34% good/very good x 47% poor/terrible x 16% fair, rejection Lula 49% and Flávio 49%, sources Poder360, CNN Brasil, Metrópoles, Gazeta do Povo) + '
const PREFIXO_SRC_ES = 'PoderData/Aya (30 de julio de 2026, campo 26-29 de julio, n=2.400, telefónica, margen de 2pp, BR-07845/2026, aprueba 43% x desaprueba 49%, gobierno 44% x 50%, gestión 34% óptima/buena x 47% mala/pésima x 16% regular, rechazo Lula 49% y Flávio 49%, fuentes Poder360, CNN Brasil, Metrópoles, Gazeta do Povo) + '

const EN: Record<string, string> = {
  'polls[0].method': 'Telephone (mobile and landline)',
  'polls[0].source': 'PoderData/Aya via Poder360, CNN Brasil, Metrópoles, Gazeta do Povo Jul 30',
  'polls[0].note': `PoderData/Aya national poll published Jul 30 (Poder360, CNN Brasil, Metrópoles, Gazeta do Povo). First round Lula 41% x Flávio 35% (gap +6pp), with Caiado 5%, Renan Santos 4%, Zema 3% and Augusto Cury 3%, plus 5% blank or void and 4% who did not answer. Runoff Lula 46% x Flávio 43% (gap +3pp), a statistical tie by the 2pp margin. Field Jul 26-29, n=2,400, telephone on mobile and landline, 677 municipalities across the 27 states, 2pp margin, 95% confidence, registration BR-07845/2026. THE COMPARISON THAT COUNTS IS WITH THE HOUSE ITSELF, and there the first-round gap did NOT move: it was 6pp on Jul 16 (40% x 34%) and it is 6pp now (41% x 35%), with the top two each gaining 1pp, inside the margin. Against AtlasIntel of Jul 29, which gave 9.1pp, the difference is 3.1pp, but comparing different houses published a day apart and calling that a tightening is swapping rulers mid-measurement: it is a house effect, the same one the panel recorded on Jul 16, when PoderData contradicted Quaest with Lula IDENTICAL in both and the whole disagreement on Flávio. RENAN SANTOS FALLS from 6% to 4% inside the house itself, the round's largest individual swing, and that UNDOES the convergence the panel recorded on Jul 29 based on AtlasIntel's 7.8%: the distance between price (8.45%) and polling reopens from 0.90pp to 4.45pp. CAIADO rises from 4% to 5%. ZEMA falls from 4% to 3%. APPROVAL personal 43% x 49% disapproval (it was 46% x 47% in the institute's Jul 22 round, down 3pp and up 2pp) and GOVERNMENT rating 44% x 50%. MANAGEMENT 34% good or very good, 16% fair and 47% poor or terrible, with poor or terrible up 10pp against Jul 22, a big jump for two weeks. REJECTION: Lula 49% and Flávio 49%, TIED, when AtlasIntel of Jul 29 gave 49.4% x 52.9%. The institute also reported statistical ties in the runoff against Zema and against Caiado, but the panel does NOT record those numbers because it could not verify them in a primary source.`,
  'approvalData.note': PREFIXO_APROV_EN + velhoEN.approvalData.note,
  'approvalData.source': PREFIXO_SRC_EN + velhoEN.approvalData.source,

  'polymarketComparison.note': `Crossing of Jul 30: the price rose and the polling did not move. Lula RISES 1.00pp and returns to 63.50% (vol USD 7.74M), tying the top of the AFOS series for the third time (Jul 26, Jul 28 and Jul 30) without exceeding it, and the gap over Flávio, FLAT at 23.95% (vol USD 7.71M), widens from +38.55pp to +39.55pp, 0.25pp below the series maximum. Recording that the gap widened by movement on one side only is mandatory: there was no repricing of Flávio's candidacy today, and his run of four daily gains was broken without a fall. THE POLLING: ${PODER_EN} has Lula 41% x Flávio 35% in the ${T1_EN} and 46% x 43% in the ${T2_EN}. ${REGUA_EN} THE METHOD FINDING IS RENAN SANTOS, and it UNDOES yesterday's. On Jul 29 the panel recorded the distance between price and polling falling to 0.90pp, with AtlasIntel giving 7.8%. PoderData gives 4% and the distance REOPENS to 4.45pp. Inside PoderData itself he falls from 6% to 4%, the round's largest individual swing, and the market went the same way in the place where it matters: the ${T1a_EN} second-place book COLLAPSED from 11.70% to 6.10%, a fall of 5.60pp (vol USD 1.09M), while the third-place book ROSE 0.50pp, to 62.00% (vol USD 164,000). The money did not eliminate him, it reclassified him. Convergence measured against a single survey is not a trend, and the spread between institutes still runs six points wide within the same month: 7.8%, 6%, 5%, 4% and 3%. CAIADO is the only name where price and polling rose together: 5% at PoderData, up 1pp inside the house, and 2.55% in the market (vol USD 5.20M), up 0.20pp. The divergence about him did not close and still stands at three levels. THE MARKET IN DETAIL: Lula 63.50% (up 1.00pp), Flávio 23.95% (flat), Renan Santos 8.45% (down 0.25pp, vol USD 8.59M), Caiado 2.55% (up 0.20pp), Jair 1.05% (flat), Zema 0.55% (down 0.20pp), Haddad 0.15% (down 0.10pp). INSTITUTIONAL: impeachment of an ${STF_EN} justice FELL 0.25pp, to 3.10% (vol USD 83,000), on the day the Brazil of Hope Federation filed at the ${TSE_EN} a petition of more than 200 pages against a network of profiles that, according to its claim, uses artificial intelligence against Lula. Price and accumulation went in opposite directions, and in a book of USD 83,000 that is noise, not signal. TWO THIN BOOKS moved a lot: the PL fell 5.50pp in the Senate, to 65.50% (vol USD 258,000), and in inflation the 4.50% to 4.99% band fell 2.40pp, to 32.50%, in a book of USD 81,000 not covered by the capture guard. CAPTURE NOTE: ${TRAVA_EN} Total accumulated volume in the presidential market at USD 116.58M.`,

  'polymarketComparison.sources': 'Polymarket via AFOS proxy (live capture Jul 30, 20:08 UTC, degraded false, failedCount 0, scripts/capture-guard.ts in one round, APPROVED with no divergence across the five books it covers) + PoderData/Aya Jul 30 (BR-07845/2026, n=2,400, field Jul 26-29, 2pp margin, latest national poll) + AtlasIntel/Bloomberg Jul 29 (BR-08602/2026, n=5,021, field Jul 22-27, 1pp margin, largest sample in the window) + BTG/Nexus Jul 27 (BR-01489/2026, n=2,004) + Datafolha Jul 24 (BR-01166/2026, n=2,004) + Gerp Jul 22 (BR-05026/2026) + Indexa Jul 21 (BR-02904/2026) + Real Time Big Data Jul 21 (BR-09247/2026) + PoderData/Aya Jul 16 (BR-00059/2026) + Genial/Quaest Jul 15 (BR-07181/2026) + Futura/Apex Jul 14 (BR-07294/2026) + AtlasIntel Jul 1 (BR-04582/2026). State polls of Jul 30 cited as context and outside the national scope: Genial/Quaest in ten states, with Rio Grande do Sul, Ceará and Goiás used in the panel. AFOS series checked with scripts/check-superlativo.ts, straight against Neon, with no window cap: coverage from Apr 14 to Jul 30, Lula peak at 63.50% (Jul 26, Jul 28 and Jul 30) and largest gap at +39.80pp (Jul 26).',

  'polymarketComparison.candidates[0].polymarket': '63.50%',
  'polymarketComparison.candidates[0].tendenciaPesquisa': `NEW POLLING: ${PODER_EN} gives Lula 41% in the ${T1_EN} against 35% for Flávio, and 46% x 43% in the ${T2_EN}. ${REGUA_EN} What moved in the round was not voting intention, it was evaluation: personal approval falls to 43% against 49% disapproval, and the MANAGEMENT rating gets sharply worse, with poor or terrible at 47%, up 10pp against the institute's Jul 22 round. Rejection TIES at 49% with Flávio's.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'RISES 1.00pp and returns to 63.50% (vol USD 7.74M), a level that TIES the top of the AFOS series for the third time, set on Jul 26, Jul 28 and now Jul 30, without exceeding it on any of the three. The gap over Flávio widens from +38.55pp to +39.55pp and sits 0.25pp below the series maximum, the +39.80pp of Jul 26. It is the third day out of seven in which the price moves a full point, and on all three the polling evidence, read inside the same house, was flat. The panel records the pattern and does not assert cause: there was no clear triggering event on Thursday.',

  'polymarketComparison.candidates[1].tendenciaPesquisa': `${PODER2_EN} brings him to 35% in the ${T1_EN}, against 34% from the house itself on Jul 16, and to 43% in the ${T2_EN} against Lula's 46%, a 3pp difference that fits inside the two margins added together and constitutes a statistical tie. THE NEWS is REJECTION: 49%, TIED with Lula's, when AtlasIntel of Jul 29 gave 52.9% against 49.4%. In every recent national poll, with the exception of Gerp of Jul 22, his rejection had come in equal to or above Lula's, and the panel had been treating that asymmetry as a structural constraint on the candidacy. One reading does not undo the series, but it did not appear in this one.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `FLAT at 23.95% (vol USD 7.71M), breaking without a fall four consecutive daily closes on the rise, which had come from 22.90% on Jul 25. The gap against him widened 1.00pp on the day, to +39.55pp, by movement of his opponent and not his own: recording that is mandatory, because a gap that widens on one side only is not a repricing of the candidacy. In the sub-markets, he RISES 0.50pp in the ${T1a_EN} second-place book, which moves to 79.00% in a contract of USD 215,000, his highest mark there in the panel's tracking, and stays flat at 6.25% in the third-place one. The rise in the second-place book has a direct counterpart in Renan Santos collapsing in the same contract: the market is concentrating in him the second ${T2_EN} slot.`,

  'polymarketComparison.candidates[2].polymarket': '8.45%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': `${PODER2_EN} has him at 4%, against 6% from the house itself on Jul 16. That 2pp fall is the round's strongest individual swing and, because it is inside the SAME house and the same method, it is the comparison that counts. It UNDOES what the panel recorded on Jul 29, when AtlasIntel's 7.8% had narrowed the distance between price and polling to 0.90pp: with 4% polling and an 8.45% price, the distance REOPENS to 4.45pp. The method lesson is that convergence measured against a single survey is not a trend. The spread between institutes still has not resolved and runs six points wide within the same month: 7.8% at AtlasIntel, 6% at Nexus, 5% at Indexa, 4% at PoderData and 3% at Datafolha.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `FALLS 0.25pp in the winner contract, to 8.45% (vol USD 8.59M), below every daily close of the past week. But the day's move is not there: it is in the ${T1a_EN} second-place book, which COLLAPSED from 11.70% to 6.10%, a fall of 5.60pp in a contract of USD 1.09M, and it is the largest single move of the day anywhere in the panel. In the same session, the third-place book ROSE 0.50pp and moves to 62.00% in a contract of USD 164,000. Added together, the three say the same thing: the money did not take him out of the election, it RECLASSIFIED him, removing his chance of contesting the ${T2_EN} and consolidating him as the third-placed name. He holds, in this capture, the largest accumulated volume among the competitive names in the presidential market, USD 8.59M, above Lula and Flávio.`,

  'polymarketComparison.candidates[3].polymarket': '2.55%',
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${PODER2_EN} returns him to 5%, up 1pp inside the house itself against the Jul 16 round, and that comes 24 hours after AtlasIntel had cut him to 3.1%, half the 6% at BTG/Nexus. The divergence about him therefore did NOT close in favour of the low reading: 6%, 5% and 3.1% are all still live. Thursday's state figure is the sharpest mismatch of the round: Genial/Quaest has him LEADING Goiás with 33%, ahead of Flávio (27%) and Lula (23%), in the same survey where disapproval of his state government is 59%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': 'RISES 0.20pp in the winner contract, to 2.55% (vol USD 5.20M), adding up to 0.65pp over two sessions, from 1.90% on Jul 28. He is the ONLY name in the panel where price and polling rose together today. He stays FLAT at 25.50% in the first-round third-place book (vol USD 37,000), meaning the rise did not show up in the contract where he actually contests position, and Renan Santos rose 0.50pp there in the same session. He rises 0.30pp in the second-place book, to 0.90%. The caveat on size comes before any reading: 5% of polling with a 2pp margin and a 2.55% price are different quantities measuring different things, and matching direction is not confirmation.',

  'polymarketComparison.candidates[4].tendenciaPesquisa': 'He does not appear in the presidential scenarios of the national polls and PoderData of Jul 30 does not test him. On Jul 28 he released allies and base mayors to back Caiado\'s candidacy, reiterating that his own candidate is still Flávio.',
  'polymarketComparison.candidates[4].tendenciaPolymarket': 'FLAT at 0.15% in the presidential market, with the highest accumulated volume in the presidential book in this capture, USD 13.66M. It is the legacy anomaly that serves as a permanent reminder of method: volume measures traded history, not current conviction. The contract accumulated that figure over months in which he was treated as a likely candidate, and today\'s price says the market no longer considers him in the race.',

  'polymarketComparison.candidates[5].polymarket': '0.55%',
  'polymarketComparison.candidates[5].tendenciaPesquisa': `${PODER2_EN} cuts him from 4% to 3% inside the house itself. It is the second institute in a row to measure him below 3%, after the 2.8% from AtlasIntel of Jul 29, which additionally had him losing the national ${T2_EN} to Lula 48.6% to 39.6%. He has been official for Novo since Jul 27 and still has NO running mate, with the Aug 5 deadline less than a week away.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': 'FALLS 0.20pp in the presidential contract, to 0.55% (vol USD 4.57M), giving back exactly what he had gained the day before, and stands at 4.50% in the first-round third-place book. He is the only name in the panel that fell on BOTH measures on the same day, polling and price. A caveat on the series, and it is a big one: his maximum in the AFOS series is 10.10%, from Apr 26, so 0.55% sits at a little over a twentieth of that level, and 0.20pp moves in that range carry very little information.',

  'polymarketComparison.candidates[6].tendenciaPesquisa': `PoderData of Jul 30 does NOT test him in any scenario, neither ${T1_EN} nor ${T2_EN}, so he has no new polling in this round, and the absence of a test in a national poll is information the panel records rather than repeating the previous day's figure as if it were new. His most recent favourable reading is still AtlasIntel of Jul 29, in one of the two runoff scenarios WITHOUT Lula, where he appears with 44.3% against 43.7% for Flávio, a statistical tie inside the 1pp margin. The caveat stands and needs saying plainly: he is NOT a presidential candidate, he is running for governor of São Paulo.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `FALLS in both contracts where he appears: 0.10pp in the winner book, to 0.15%, and 0.30pp in the ${T1a_EN} second-place book, to 0.85%. It is the inversion of the crossed signal the panel recorded on Jul 29, when he had risen in the placing book and stayed flat in the winner one. Falling in both is a coherent signal, and here the coherent direction is down.`,
}

const ES: Record<string, string> = {
  'polls[0].method': 'Telefónico (celular y fijo)',
  'polls[0].source': 'PoderData/Aya vía Poder360, CNN Brasil, Metrópoles, Gazeta do Povo 30 de julio',
  'polls[0].note': `PoderData/Aya nacional publicada el 30 de julio (Poder360, CNN Brasil, Metrópoles, Gazeta do Povo). Primera vuelta Lula 41% x Flávio 35% (brecha +6pp), con Caiado 5%, Renan Santos 4%, Zema 3% y Augusto Cury 3%, además de 5% de blanco o nulo y 4% que no respondieron. Segunda vuelta Lula 46% x Flávio 43% (brecha +3pp), empate técnico por el margen de 2pp. Campo 26-29 de julio, n=2.400, telefónico en celular y fijo, 677 municipios en los 27 estados, margen de 2pp, 95% de confianza, registro BR-07845/2026. LA COMPARACIÓN QUE VALE ES CON LA PROPIA CASA, y allí la brecha de la primera vuelta NO se movió: eran 6pp el 16 de julio (40% x 34%) y son 6pp ahora (41% x 35%), con los dos primeros subiendo 1pp, dentro del margen. Contra la AtlasIntel del 29 de julio, que dio 9,1pp, la diferencia es de 3,1pp, pero comparar casas distintas publicadas con un día de intervalo y llamar a eso estrechamiento es cambiar de regla en medio de la medición: es efecto de casa, el mismo que el panel registró el 16 de julio, cuando PoderData contradijo a Quaest con Lula IDÉNTICO en ambas y todo el desacuerdo en Flávio. RENAN SANTOS CAE de 6% a 4% dentro de la propia casa, la mayor variación individual de la ronda, y eso DESHACE la convergencia que el panel registró el 29 de julio con base en los 7,8% de AtlasIntel: la distancia entre precio (8,45%) y encuesta reabre de 0,90pp a 4,45pp. CAIADO sube de 4% a 5%. ZEMA cae de 4% a 3%. APROBACIÓN personal 43% x 49% de desaprobación (era 46% x 47% en la ronda del 22 de julio del instituto, una caída de 3pp y un alza de 2pp) y evaluación del GOBIERNO 44% x 50%. GESTIÓN 34% de óptima o buena, 16% regular y 47% de mala o pésima, con la mala o pésima subiendo 10pp contra el 22 de julio, un salto grande para dos semanas. RECHAZO: Lula 49% y Flávio 49%, EMPATADOS, cuando la AtlasIntel del 29 de julio daba 49,4% x 52,9%. El instituto también reportó empates técnicos en la segunda vuelta contra Zema y contra Caiado, pero el panel NO registra esos números porque no logró verificarlos en fuente primaria.`,
  'approvalData.note': PREFIXO_APROV_ES + velhoES.approvalData.note,
  'approvalData.source': PREFIXO_SRC_ES + velhoES.approvalData.source,

  'polymarketComparison.note': `Cruce del 30 de julio: el precio subió y la encuesta no se movió. Lula SUBE 1,00pp y vuelve a 63,50% (vol USD 7,74M), igualando por tercera vez el techo de la serie del AFOS (26, 28 y 30 de julio) sin superarlo, y la brecha sobre Flávio, ESTABLE en 23,95% (vol USD 7,71M), se abre de +38,55pp a +39,55pp, a 0,25pp del máximo de la serie. Registrar que la brecha se abrió por movimiento de un solo lado es obligatorio: no hubo revaluación de la candidatura de Flávio hoy, y su racha de cuatro alzas diarias se interrumpió sin caída. LA ENCUESTA: ${PODER_ES} da a Lula 41% x Flávio 35% en la ${T1_ES} y 46% x 43% en la ${T2_ES}. ${REGUA_ES} EL HALLAZGO DE MÉTODO ES RENAN SANTOS, y DESHACE el de ayer. El 29 de julio el panel registró la distancia entre precio y encuesta cayendo a 0,90pp, con AtlasIntel dando 7,8%. PoderData da 4% y la distancia REABRE a 4,45pp. Dentro de la propia PoderData cae de 6% a 4%, la mayor variación individual de la ronda, y el mercado fue en la misma dirección en el lugar donde eso importa: el book de segundo lugar de la ${T1_ES} se DESPLOMÓ de 11,70% a 6,10%, una caída de 5,60pp (vol USD 1,09M), mientras el de tercer lugar SUBIÓ 0,50pp, a 62,00% (vol USD 164.000). El dinero no lo eliminó, lo reclasificó. Convergencia medida contra un único levantamiento no es tendencia, y la dispersión entre institutos sigue con seis puntos de amplitud en el mismo mes: 7,8%, 6%, 5%, 4% y 3%. CAIADO es el único nombre en que precio y encuesta subieron juntos: 5% en PoderData, un alza de 1pp dentro de la casa, y 2,55% en el mercado (vol USD 5,20M), un alza de 0,20pp. La divergencia sobre él no cerró y sigue en tres niveles. EL MERCADO EN DETALLE: Lula 63,50% (alza 1,00pp), Flávio 23,95% (estable), Renan Santos 8,45% (caída 0,25pp, vol USD 8,59M), Caiado 2,55% (alza 0,20pp), Jair 1,05% (estable), Zema 0,55% (caída 0,20pp), Haddad 0,15% (caída 0,10pp). INSTITUCIONAL: el impeachment de ministro del ${STF_ES} CAYÓ 0,25pp, a 3,10% (vol USD 83.000), el día en que la Federación Brasil de la Esperanza presentó en el ${TSE_ES} una representación de más de 200 páginas contra una red de perfiles que, según alega, usa inteligencia artificial contra Lula. Precio y acumulación fueron hacia lados opuestos, y en un book de USD 83.000 eso es ruido, no señal. DOS BOOKS FINOS se movieron mucho: el PL cayó 5,50pp en el Senado, a 65,50% (vol USD 258.000), y en inflación la franja de 4,50% a 4,99% cayó 2,40pp, a 32,50%, en un book de USD 81.000 no cubierto por la traba. NOTA DE CAPTURA: ${TRAVA_ES} Volumen total acumulado en el presidencial en USD 116,58M.`,

  'polymarketComparison.sources': 'Polymarket vía proxy AFOS (captura en vivo 30 de julio, 20:08 UTC, degraded false, failedCount 0, scripts/capture-guard.ts en una ronda, APROBADA sin divergencia en los cinco books cubiertos) + PoderData/Aya 30 de julio (BR-07845/2026, n=2.400, campo 26-29 de julio, margen de 2pp, última nacional) + AtlasIntel/Bloomberg 29 de julio (BR-08602/2026, n=5.021, campo 22-27 de julio, margen de 1pp, mayor muestra del recorte) + BTG/Nexus 27 de julio (BR-01489/2026, n=2.004) + Datafolha 24 de julio (BR-01166/2026, n=2.004) + Gerp 22 de julio (BR-05026/2026) + Indexa 21 de julio (BR-02904/2026) + Real Time Big Data 21 de julio (BR-09247/2026) + PoderData/Aya 16 de julio (BR-00059/2026) + Genial/Quaest 15 de julio (BR-07181/2026) + Futura/Apex 14 de julio (BR-07294/2026) + AtlasIntel 1 de julio (BR-04582/2026). Estatales del 30 de julio citadas como contexto y fuera del recorte nacional: Genial/Quaest en diez estados, con Rio Grande do Sul, Ceará y Goiás usados en el panel. Serie del AFOS verificada con scripts/check-superlativo.ts, directo en Neon, sin límite de ventana: cobertura del 14 de abril al 30 de julio, techo de Lula en 63,50% (26, 28 y 30 de julio) y mayor brecha en +39,80pp (26 de julio).',

  'polymarketComparison.candidates[0].polymarket': '63,50%',
  'polymarketComparison.candidates[0].tendenciaPesquisa': `ENCUESTA NUEVA: ${PODER_ES} da a Lula 41% en la ${T1_ES} contra 35% de Flávio, y 46% x 43% en la ${T2_ES}. ${REGUA_ES} Lo que se movió en la ronda no fue la intención de voto, fue la evaluación: la aprobación personal cae a 43% contra 49% de desaprobación, y la evaluación de la GESTIÓN empeora fuerte, con mala o pésima en 47%, un alza de 10pp contra la ronda del 22 de julio del instituto. El rechazo EMPATA en 49% con el de Flávio.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'SUBE 1,00pp y vuelve a 63,50% (vol USD 7,74M), valor que IGUALA por tercera vez el techo de la serie del AFOS, marcado el 26, el 28 y ahora el 30 de julio, sin superarlo en ninguna de las tres. La brecha sobre Flávio se abre de +38,55pp a +39,55pp y queda a 0,25pp del máximo de la serie, los +39,80pp del 26 de julio. Es el tercer día en siete en que el precio se mueve un punto entero, y en los tres la evidencia de encuesta, leída dentro de la misma casa, estaba quieta. El panel registra el patrón y no afirma causa: no hubo evento disparador claro este jueves.',

  'polymarketComparison.candidates[1].tendenciaPesquisa': `${PODER2_ES} lo trae en 35% en la ${T1_ES}, ante 34% de la propia casa el 16 de julio, y en 43% en la ${T2_ES} contra 46% de Lula, una diferencia de 3pp que cabe en los márgenes sumados y caracteriza empate técnico. LA NOVEDAD es el RECHAZO: 49%, EMPATADO con el de Lula, cuando la AtlasIntel del 29 de julio daba 52,9% contra 49,4%. En todas las lecturas nacionales recientes, con excepción de Gerp del 22 de julio, su rechazo venía igual o por encima del de Lula, y el panel venía tratando esa asimetría como restricción estructural de la candidatura. Una lectura no deshace la serie, pero no apareció en esta.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket': `ESTABLE en 23,95% (vol USD 7,71M), interrumpiendo sin caída cuatro cierres diarios seguidos al alza, que venían de 22,90% el 25 de julio. La brecha contra él se abrió 1,00pp en el día, a +39,55pp, por movimiento del adversario y no propio: registrar eso es obligatorio, porque una brecha que se abre por un solo lado no es revaluación de la candidatura. En los submercados, SUBE 0,50pp en el book de segundo lugar de la ${T1_ES}, que pasa a 79,00% en un contrato de USD 215.000, su mayor marca allí en el seguimiento del panel, y queda quieto en 6,25% en el de tercer lugar. El alza en el book de segundo lugar tiene contrapartida directa en el desplome de Renan Santos en el mismo contrato: el mercado está concentrando en él el segundo lugar de la ${T2_ES}.`,

  'polymarketComparison.candidates[2].polymarket': '8,45%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': `${PODER2_ES} lo da en 4%, contra 6% de la propia casa el 16 de julio. Esa caída de 2pp es la variación individual más fuerte de la ronda y, por ser dentro de la MISMA casa y del mismo método, es la comparación que vale. DESHACE lo que el panel registró el 29 de julio, cuando los 7,8% de AtlasIntel habían estrechado la distancia entre precio y encuesta a 0,90pp: con 4% de encuesta y 8,45% de precio, la distancia REABRE a 4,45pp. La lección de método es que convergencia medida contra un único levantamiento no es tendencia. La dispersión entre institutos sigue sin resolverse y tiene seis puntos de amplitud en el mismo mes: 7,8% en AtlasIntel, 6% en Nexus, 5% en Indexa, 4% en PoderData y 3% en Datafolha.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket': `CAE 0,25pp en el contrato de ganador, a 8,45% (vol USD 8,59M), por debajo de todo cierre diario de la última semana. Pero el movimiento del día no está ahí: está en el book de segundo lugar de la ${T1_ES}, que se DESPLOMÓ de 11,70% a 6,10%, una caída de 5,60pp en un contrato de USD 1,09M, y es el mayor movimiento aislado del día en todo el panel. En la misma rueda, el book de tercer lugar SUBIÓ 0,50pp y pasa a 62,00% en un contrato de USD 164.000. Sumados, los tres dicen lo mismo: el dinero no lo sacó de la elección, lo RECLASIFICÓ, quitándole la chance de disputar la ${T2_ES} y consolidándolo como tercer colocado. Mantiene, en esta captura, el mayor volumen acumulado entre los nombres competitivos del presidencial, USD 8,59M, por encima de Lula y de Flávio.`,

  'polymarketComparison.candidates[3].polymarket': '2,55%',
  'polymarketComparison.candidates[3].tendenciaPesquisa': `${PODER2_ES} lo devuelve a 5%, un alza de 1pp dentro de la propia casa contra la ronda del 16 de julio, y eso llega 24 horas después de que AtlasIntel lo hubiera cortado a 3,1%, la mitad de los 6% de BTG/Nexus. La divergencia sobre él, por lo tanto, NO cerró a favor de la lectura baja: siguen vigentes 6%, 5% y 3,1%. El dato estatal de este jueves es el desajuste más nítido de la ronda: Genial/Quaest lo da LIDERANDO Goiás con 33%, por delante de Flávio (27%) y de Lula (23%), en el mismo levantamiento en que la desaprobación de su gobierno estatal es de 59%.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket': 'SUBE 0,20pp en el contrato de ganador, a 2,55% (vol USD 5,20M), acumulando 0,65pp en dos ruedas, de 1,90% el 28 de julio. Es el ÚNICO nombre del panel en que precio y encuesta subieron juntos hoy. Queda QUIETO en 25,50% en el book de tercer lugar de la primera vuelta (vol USD 37.000), es decir, el alza no apareció en el contrato en que él de hecho disputa posición, y Renan Santos subió 0,50pp allí en la misma rueda. Sube 0,30pp en el book de segundo lugar, a 0,90%. La salvedad de tamaño viene antes de cualquier lectura: 5% de encuesta con margen de 2pp y 2,55% de precio son magnitudes distintas midiendo cosas distintas, y coincidencia de dirección no es confirmación.',

  'polymarketComparison.candidates[4].tendenciaPesquisa': 'No aparece en los escenarios presidenciales de las nacionales y la PoderData del 30 de julio no lo testea. El 28 de julio liberó a aliados y alcaldes de la base para apoyar la candidatura de Caiado, reiterando que su candidato sigue siendo Flávio.',
  'polymarketComparison.candidates[4].tendenciaPolymarket': 'ESTABLE en 0,15% en el presidencial, con el volumen acumulado más alto del book presidencial en esta captura, USD 13,66M. Es la anomalía de legado que sirve de recordatorio permanente de método: el volumen mide historia negociada y no convicción actual. El contrato acumuló ese valor a lo largo de meses en que era tratado como candidato probable, y el precio de hoy dice que el mercado ya no lo considera en la disputa.',

  'polymarketComparison.candidates[5].polymarket': '0,55%',
  'polymarketComparison.candidates[5].tendenciaPesquisa': `${PODER2_ES} lo corta de 4% a 3% dentro de la propia casa. Es el segundo instituto seguido en medirlo por debajo de 3%, tras los 2,8% de AtlasIntel del 29 de julio, que además lo puso perdiendo la ${T2_ES} nacional ante Lula por 48,6% a 39,6%. Sigue oficializado por el Novo desde el 27 de julio y SIN vice, con el plazo del 5 de agosto a menos de una semana.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket': 'CAE 0,20pp en el contrato presidencial, a 0,55% (vol USD 4,57M), devolviendo exactamente lo que había subido la víspera, y queda en 4,50% en el book de tercer lugar de la primera vuelta. Es el único nombre del panel que cayó en las DOS medidas el mismo día, encuesta y precio. Salvedad de serie, y es grande: su máximo en la serie del AFOS es 10,10%, del 26 de abril, así que 0,55% está a poco más de un veinteavo de aquel nivel, y movimientos de 0,20pp en esa franja tienen bajísimo valor informativo.',

  'polymarketComparison.candidates[6].tendenciaPesquisa': `La PoderData del 30 de julio NO lo testea en ningún escenario, ni de ${T1_ES} ni de ${T2_ES}, así que no tiene encuesta nueva en esta ronda, y la ausencia de test en una nacional es información que el panel registra en vez de repetir el dato de la víspera como si fuera nuevo. Su lectura favorable más reciente sigue siendo la de AtlasIntel del 29 de julio, en uno de los dos escenarios de segunda vuelta SIN Lula, donde aparece con 44,3% contra 43,7% de Flávio, empate técnico dentro del margen de 1pp. La salvedad permanece y necesita decirse con claridad: él NO es candidato a la Presidencia, disputa el gobierno de São Paulo.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket': `CAE en los dos contratos en que aparece: 0,10pp en el de ganador, a 0,15%, y 0,30pp en el book de segundo lugar de la ${T1_ES}, a 0,85%. Es la inversión de la señal cruzada que el panel registró el 29 de julio, cuando había subido en el book de colocación y quedado quieto en el de ganador. Caer en los dos es señal coherente, y aquí lo coherente es hacia abajo.`,
}

construir('polls-data', 'en', EN)
construir('polls-data', 'es', ES)
