/**
 * Mapa ES de 10/Ago para polls-data.json.
 * Convenções: vírgula decimal e ponto de milhar. "encuesta", nunca "investigación".
 */
import { construir } from '../build-locale-json'

const G = (t: string, id: string) => `[${t}](/es/glossary#${id})`
const PRECIO = 'lectura confirmada del 9/Ago, 17:34 UTC'

construir('polls-data', 'es', {
  'institutes[20].note':
    `Estreno nacional el 10/Ago/2026, cuestionario por internet. El propio instituto declara un efecto del formato digital sobre un candidato con base activa en línea.`,

  'polls[0].method': `Online, cuestionario por internet`,
  'polls[0].note':
    `ESTRENO DE PALVER en el panel, publicada el 10/Ago, con n=5.000, la mayor muestra entre las nacionales publicadas en agosto. En la ventana de 30 días la AtlasIntel del 29/Jul fue mayor, con n=5.021. Primera vuelta Lula 44% x Flávio 40%, con Renan Santos aislado en tercer lugar, con 10%. Segunda vuelta Lula 46% x Flávio 46%, empate en el número. Margen 3pp, 95% de confianza, registro BR-06596/2026. EL REGISTRO DEL TSE DECLARA CAMPO DEL 3 AL 9/Ago Y LA DIVULGACIÓN INFORMA DEL 3 AL 7/Ago, y el panel registra las dos fechas en lugar de elegir una. EL PUNTO DE MÉTODO VIENE DEL PROPIO INSTITUTO, no de este panel: Palver evaluó que el formato digital pudo haber impulsado el desempeño de Renan Santos, que mantiene una base activa en ese entorno, e informó que prueba enfoques para reducir ese efecto en encuestas online. Con eso, el mismo nombre aparece en 4% y 4,7% en las rondas por teléfono y presencial del 5/Ago, en 4% en la BTG/Nexus por teléfono de hoy, y en 10% aquí, por internet. RECHAZO con Lula en 52% y Flávio en 51%. APROBACIÓN del gobierno en 45% contra 55% de desaprobación, el saldo más negativo entre las casas de la ventana, en la que la Genial/Quaest del 5/Ago marcó 48% x 47% y la BTG/Nexus de hoy marcó 46% x 49%.`,
  'polls[0].source':
    `Palver divulgada el 10/Ago por Folha de S.Paulo, CNN Brasil, UOL, Exame, JOTA y CartaCapital. Registro TSE BR-06596/2026.`,

  'polls[1].note':
    `BTG/Nexus nacional publicada el 10/Ago, 9ª ronda de la serie. Primera vuelta Lula 40% x Flávio 35%, con Caiado 5%, Renan Santos 4% y Zema 3%. La diferencia de 5pp queda FUERA del margen de 2pp. Segunda vuelta Lula 47% x Flávio 44%, diferencia de 3pp que la propia divulgación trata como empate técnico, y la ronda también apunta a un empate de Lula con Caiado en la segunda vuelta. Campo del 7 al 9/Ago, n=2.001, telefónica, margen 2pp, 95% de confianza, registro BR-08428/2026. LA COMPARACIÓN DENTRO DE LA CASA INVIERTE LO QUE MOSTRABA LA RONDA ANTERIOR: el 3/Ago la diferencia de la primera vuelta había CAÍDO de 9pp a 4pp, y ahora se abrió de nuevo, a 5pp. En la segunda vuelta el movimiento es mayor, de 1pp a 3pp. Y los dos cedieron en la primera vuelta, Lula de 41% a 40% y Flávio de 37% a 35%, es decir, la diferencia se abrió porque el segundo colocado cayó más, no porque el líder subiera. APROBACIÓN en 46% contra 49% de desaprobación, frente a 47% x 48% en la propia ronda del 3/Ago. RECHAZO con Flávio en 50% y Lula en 48%, y esta vez el dato salió con fuente cerrada, a diferencia de la ronda anterior, en la que las fuentes secundarias discrepaban y el panel dejó el número fuera.`,
  'polls[1].source':
    `BTG/Nexus divulgada el 10/Ago por Folha de S.Paulo, Estadão, Poder360, CNN Brasil, UOL, JOTA, CartaCapital, VEJA, Metrópoles, GZH, Money Times y Revista Fórum. Registro TSE BR-08428/2026.`,

  'approvalData.note':
    `DOS LECTURAS NUEVAS EL 10/Ago, y amplían la dispersión en lugar de reducirla. BTG/Nexus del 10/Ago: 46% aprueban y 49% desaprueban, saldo de 3pp negativos, frente a 47% x 48% en la propia ronda del 3/Ago. Palver del 10/Ago, online: 45% aprueban y 55% desaprueban, saldo de 10pp negativos. Siguen en el cuadro la Genial/Quaest del 5/Ago, con 48% x 47% y saldo positivo de 1pp, y la Meio/Ideia de la misma ventana, con 48,5% x 49%. LO QUE MUESTRA EL CONJUNTO: en cinco lecturas de ocho días el saldo va de 1pp positivo a 10pp negativo, y la desaprobación aislada va de 47% a 55%, una distancia de 8pp entre casas. Antes el signo del saldo ya dependía de la casa; ahora el tamaño también depende. LOS NÚMEROS DE ESTA TARJETA TIENEN PROCEDENCIAS DISTINTAS Y ESO TIENE QUE QUEDAR DICHO: aprobación y desaprobación son de la BTG/Nexus del 10/Ago, elegida por ser la serie telefónica más larga en curso y comparable con sus propias rondas anteriores; la evaluación de la gestión, con 36% positiva, 26% regular y 36% negativa, sigue siendo la de la Genial/Quaest del 5/Ago, porque ninguna de las dos rondas de hoy publicó esa apertura con fuente cerrada. El panel prefiere declarar la mezcla a esconderla.`,
  'approvalData.source':
    `Aprobación y desaprobación: BTG/Nexus 10/Ago/2026 (campo del 7 al 9/Ago, n=2.001, telefónica, margen 2pp, BR-08428/2026), divulgada por Folha de S.Paulo, Estadão, CNN Brasil, UOL, Poder360, JOTA y Metrópoles. Segunda lectura del día: Palver 10/Ago/2026 (n=5.000, online, margen 3pp, BR-06596/2026), vía Folha, CNN Brasil, UOL, Exame, JOTA y CartaCapital. Evaluación de la gestión: Genial/Quaest 5/Ago/2026 (campo del 31/Jul al 3/Ago, n=2.004, presencial, 120 municipios, margen 2pp, contratante Banco Genial, BR-06591/2026). Meio/Ideia 5/Ago vía Estadão, mantenida en el texto como cuarta casa de la ventana.`,

  'polymarketComparison.candidates[0].pesquisaRange': `39-44%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `DOS NACIONALES NUEVAS EL 10/Ago. BTG/Nexus (n=2.001, telefónica, campo del 7 al 9/Ago, margen 2pp, BR-08428/2026): 40% en la primera vuelta, con la diferencia de 5pp sobre el segundo colocado FUERA del margen, y 47% x 44% en la segunda. Palver, estreno en el panel (n=5.000, cuestionario por internet, margen 3pp, BR-06596/2026): 44% en la primera vuelta y EMPATE en 46% x 46% en la segunda, el peor escenario de segunda vuelta que cualquier nacional le ha dado en la ventana. Sumando las cuatro rondas desde el 5/Ago, va de 39% a 44%, un rango de 5pp, y lidera la primera vuelta en todas. DENTRO DE LA CASA, BTG/Nexus muestra lo inverso de la semana pasada: la diferencia de la primera vuelta había caído de 9pp a 4pp el 3/Ago y ahora se ABRIÓ a 5pp, con los dos cediendo y el adversario cediendo más. LA APROBACIÓN empeoró en las dos lecturas de hoy, 46% x 49% en Nexus y 45% x 55% en Palver, y en cinco lecturas de ocho días el saldo va de 1pp positivo a 10pp negativo. El porcentaje usado en el gráfico es el de BTG/Nexus, elegida por ser la serie telefónica más larga en curso.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `[${PRECIO}] En 63,50% (vol USD 8,18M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago, y por eso esta línea no registra variación en el día. Hasta la lectura del 9/Ago la diferencia sobre Flávio venía estrechándose, cayendo en SEIS de las SIETE últimas jornadas, de +38,90pp el 3/Ago a +36,55pp. En la serie de 88 días, del 13/May al 10/Ago, su techo es 66,50%, del 1/Ago, y 14 de los 88 días tuvieron un valor igual o superior al actual, así que el nivel no es extremo.`,

  'polymarketComparison.candidates[1].pesquisaRange': `30-40%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `EL RANGO ES EL DATO, NO EL PUNTO. En las cuatro nacionales desde el 5/Ago aparece con 30% en Genial/Quaest, 35% en Meio/Ideia, 35% en la BTG/Nexus de hoy y 40% en la Palver de hoy, una amplitud de 10pp, el DOBLE que la del primer colocado. En la segunda vuelta la distancia entre los dos va de 0pp, en Palver, a 5,5pp, en Meio/Ideia. PALVER LE DIO EL MEJOR ESCENARIO DE LA VENTANA, con 40% en la primera vuelta y empate en 46% x 46%, y es la primera vez que una nacional no apunta a una derrota suya en la segunda vuelta. EN BTG/NEXUS el movimiento fue contrario: cayó de 37% el 3/Ago a 35%, y es esa caída la que abre la diferencia de la primera vuelta de 4pp a 5pp. RECHAZO de 50% en Nexus, el más alto de la ronda, y de 51% en Palver. El porcentaje usado en el gráfico es el de BTG/Nexus, la misma casa de referencia que el primer colocado.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `[${PRECIO}] En 26,95% (vol USD 8,09M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago. El valor confirmado del 9/Ago cerraba el tercer día en el mismo nivel, y en el contrato de segundo lugar el último valor confirmado es 81,50%. No es extremo: 26 de los 88 días de la serie tuvieron un valor igual o superior, con un techo de 34,40% el 13/May y un piso de 22,00% el 3/Jul.`,

  'polymarketComparison.candidates[2].pesquisaRange': `4-10%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `EL EFECTO DE MÉTODO DE LA SEMANA ESTÁ AQUÍ, Y QUIEN LO DECLARÓ FUE EL INSTITUTO QUE LO MIDIÓ ALTO. Aparece con 4% en Genial/Quaest presencial del 5/Ago, 4,7% en Meio/Ideia por teléfono del mismo día, 4% en BTG/Nexus por teléfono del 10/Ago, y 10% en Palver por internet, también del 10/Ago. PALVER EVALUÓ que el formato digital pudo haber impulsado su desempeño, ya que mantiene una base activa en ese entorno, e informó que prueba enfoques para reducir ese efecto en encuestas online. En su ronda queda aislado en tercer lugar. El panel repite la declaración de la casa en lugar de juzgar el número. El porcentaje usado en el gráfico es el de BTG/Nexus, para mantener la misma casa de referencia que los demás, y el rango completo está declarado arriba.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `[${PRECIO}] En 7,80% (vol USD 9,27M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago. LO QUE HACE EL PRECIO CONFIRMADO ES QUEDAR ENTRE LOS DOS MÉTODOS: por encima del 4% a 4,7% del teléfono y del presencial, por debajo del 10% de internet. Y al mismo tiempo cerca del PISO de su propia historia: en la serie de 88 días, 84 de ellos tuvieron un valor igual o superior, con un máximo de 17,90% el 9/Jun y un mínimo de 6,80% el 6/Ago. Techo en la encuesta y piso en el precio, en la misma semana. Mayor volumen acumulado del libro presidencial entre los nombres por encima de 1%.`,

  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `SU DATO NUEVO ESTÁ EN LA SEGUNDA VUELTA: la BTG/Nexus del 10/Ago apunta a un EMPATE de Lula con él, en la misma ronda en la que el líder vence al segundo colocado por 47% x 44%. Es el único nombre fuera de los dos primeros que lo consigue en la ventana. En la primera vuelta tiene 5% en Nexus, por delante de Renan Santos, con 4%, y de Zema, con 3%. Siguen valiendo los 4% de Genial/Quaest y los 5,7% de Meio/Ideia, del 5/Ago, y en Ideia es el adversario que más se acerca en la segunda vuelta, con 40% contra 48,5%. PALVER NO LO PRUEBA en el escenario publicado, y el panel registra la ausencia en lugar de repetir dato antiguo como si fuera nuevo.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `[${PRECIO}] En 1,25% (vol USD 5,60M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago. El valor confirmado del 9/Ago cerraba el tercer día seguido de caída en los dos libros, con 25,50% en el de tercer lugar. ES EL NOMBRE CON LA MAYOR DISTANCIA ENTRE ENCUESTA Y PRECIO DEL PELOTÓN: de 4% a 5,7% de intención declarada contra 1,25% de probabilidad descontada. El panel registra la distancia sin restar una magnitud de la otra, porque la encuesta mide intención ahora y el contrato mide probabilidad de ganar al final.`,

  'polymarketComparison.candidates[4].tendenciaPesquisa':
    `Ninguna de las dos rondas del 10/Ago lo prueba en algún escenario presidencial, de primera o de segunda vuelta, y lo mismo vale para las dos del 5/Ago. La ausencia de prueba es información que el panel registra, en lugar de repetir dato antiguo como si fuera nuevo. Disputa la REELECCIÓN en la gobernación de São Paulo, oficializada por Republicanos el 1/Ago.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `[${PRECIO}] En 0,05% (vol USD 13,87M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago. EL CONTRASTE QUE VALE REGISTRAR: este es el MAYOR volumen acumulado de todo el libro presidencial, con USD 13,87M, y el precio está en el piso. Volumen alto con probabilidad en el piso es convicción ya descontada, no movimiento, y el nivel es lo bastante bajo para que las variaciones en esta franja tengan un valor informativo casi nulo.`,

  'polymarketComparison.candidates[5].pesquisaRange': `2-3%`,
  'polymarketComparison.candidates[5].tendenciaPesquisa':
    `La BTG/Nexus del 10/Ago le da 3% en la primera vuelta. Palver no lo prueba en el escenario publicado. Siguen valiendo los 2% de Genial/Quaest y los 2,6% de Meio/Ideia, del 5/Ago, con segundas vueltas de 34% contra 46% y de 37% contra 48,5%. Registró su candidatura ante el ${G('TSE', 'tse')} el 6/Ago, declarando R$ 178,7 millones de patrimonio, con el vice Girão informando R$ 34,1 millones, y sigue siendo el único del pelotón con registro presentado, en un plazo que va hasta el 15/Ago.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `[${PRECIO}] En 0,45% (vol USD 5,02M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago. El valor confirmado está POR DEBAJO del corte de 0,5% que el panel usa para separar precio de ruido, y la lectura sobre él queda suspendida mientras esté en esa franja. Salvedad de serie que sigue valiendo: su máximo fue 10,10%, el 26/Abr.`,

  'polymarketComparison.candidates[6].tendenciaPesquisa':
    `Ninguna de las dos rondas del 10/Ago lo prueba en algún escenario, ni de primera ni de segunda vuelta, y lo mismo valía para las dos del 5/Ago, así que sigue sin encuesta. El agravante permanece y necesita decirse con claridad: NO es candidato a la Presidencia, disputa la gobernación de São Paulo, y cualquier escenario que lo incluya es una hipótesis de encuesta, no una candidatura en curso.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `[${PRECIO}] En 0,05% (vol USD 6,78M acumulado). NO HAY LECTURA DE PRECIO NUEVA EL 10/Ago, y el valor confirmado está en el piso que el mercado descuenta. Una variación en esta franja no tiene valor informativo.`,

  'polymarketComparison.note':
    `LOS PRECIOS DE ESTA SECCIÓN SON DE LA LECTURA CONFIRMADA DEL 9/Ago, DE LAS 17:34 UTC, y no hay lectura de precio nueva el 10/Ago. AFOS solo publica un precio que dos lecturas independientes confirmen, tomadas con ocho minutos de intervalo. EL DÍA TRAJO ENCUESTAS: dos nacionales fueron publicadas, la BTG/Nexus (n=2.001, telefónica) con 40% x 35% en la primera vuelta y 47% x 44% en la segunda, y el estreno de Palver (n=5.000, por internet) con 44% x 40% y empate en 46% x 46%. TRES CRUCES SALEN DE AHÍ. El primero es de amplitud: en las cuatro nacionales desde el 5/Ago el segundo colocado varía 10pp, de 30% a 40%, contra 5pp del primero, y en la segunda vuelta la distancia entre ellos va de 0pp a 5,5pp según la casa. El segundo es de método, y fue declarado por el propio instituto: Renan Santos aparece con 4% y 4,7% por teléfono y presencial y con 10% por internet, y Palver evaluó que el formato digital pudo haber impulsado su desempeño, informando que prueba enfoques para reducir el efecto. Su precio confirmado, 7,80%, queda entre los dos métodos, y al mismo tiempo cerca del piso de su propia serie, con 84 de los 88 días en un valor igual o superior. El tercero es de dirección: hasta la lectura del 9/Ago la diferencia de mercado se había estrechado en seis de las siete últimas jornadas, de +38,90pp a +36,55pp, mientras la diferencia de BTG/Nexus se abrió dentro de su propia casa, de 4pp a 5pp en la primera vuelta y de 1pp a 3pp en la segunda. Los dos instrumentos se movieron en sentidos opuestos sobre la misma disputa y en la misma ventana, y el panel registra el cruce sin decir cuál está en lo cierto.`,
})
