/**
 * Mapa EN de polls-data.json — /atualizar-brz 03/Ago/2026.
 *
 * Só os campos que mudaram hoje entram aqui; as notas das pesquisas antigas são
 * reaproveitadas pela memória por texto de origem. Convenções travadas: ponto
 * decimal e vírgula de milhar; "pesquisa" é poll; "urna" é polling.
 */
import { construir } from '../build-locale-json'

const G = (termo: string, id: string) => `[${termo}](/en/glossary#${id})`

construir('polls-data', 'en', {
  'polls[0].note':
    `${G('BTG/Nexus', 'nexus-btg')} national poll released Aug 3, the 8th round in the series, and the first of the four national polls the ${G('TSE', 'tse')} filing had scheduled between Aug 3 and Aug 5. First round Lula 41% x Flávio 37%, with Caiado at 5%, Renan Santos at 4% and Zema at 3%. Runoff Lula 46% x Flávio 45%, a 1pp difference that falls WITHIN the 2pp margin and is therefore a ${G('statistical tie', 'empate-tecnico')}. Fieldwork Jul 31 to Aug 2, n=2,002, telephone, 2pp margin, 95% confidence, filing BR-02874/2026. WHAT CHANGES THE WEEK IS THE COMPARISON WITH THE INSTITUTE'S OWN PREVIOUS ROUND: the first-round gap FELL FROM 9pp TO 4pp in a single round, against the 42% x 33% of Jul 27. And the move comes almost entirely from one side, because LULA GAVE UP 1pp and FLÁVIO GAINED 4pp. In the runoff the tightening is sharper still, from 4pp to 1pp, with Lula going from 47% to 46% and Flávio from 43% to 45%. The round's other runoffs: Lula 46% x Caiado 42%, Lula 46% x Zema 40% and Lula 47% x Renan Santos 37%. AGAINST THE OTHER HOUSES, among the four national polls released since Jul 29 this is the one showing the tightest first round: 4pp here, against 6pp in PoderData of Jul 30, 9.1pp in ${G('AtlasIntel', 'atlasintel')} of Jul 29 and 9.3pp in Vox Brasil of Jul 31. The distance between the highest and the lowest reading reaches 5.3pp and is larger than any price move in the period. ⚠️ REJECTION NOT PUBLISHED BY THIS PANEL: the secondary sources DISAGREE. Poder360, CNN Brasil and Correio Braziliense report 49% for each of the two; Money Times reports 50% for Lula and 51% for Flávio. The institute's release note does not carry the figure, so it could not be settled against a primary source and the number stays out, with the disagreement declared here. This round also did not publish government approval or disapproval.`,
  'polls[0].source':
    `BTG/Nexus via the institute's own site (nexus.fsb.com.br), Folha de S.Paulo, Estadão, CNN Brasil, JOTA, CartaCapital, Poder360, VEJA, Exame, Correio Braziliense and Money Times Aug 3. TSE filing BR-02874/2026.`,
  'polymarketComparison.note':
    `Cross-reading of Aug 3, capture locked at 19:11 UTC, cleared only on the THIRD attempt: the first two were BLOCKED by the second-place book, which swung 0.50pp between readings eight minutes apart. The day carries a rare cross-reading, because BOTH measurements moved the SAME WAY and for the SAME REASON. ${G('BTG/Nexus', 'nexus-btg')} published today and its first-round gap fell from 9pp to 4pp against the institute's own Jul 27 round, with Lula giving up 1pp and Flávio gaining 4pp. In the market, the gap closed from +40.95pp to +40.05pp, and it closed in exactly the same way: LULA STOOD STILL at 65.50% (vol USD 7.92M) and FLÁVIO ROSE 0.90pp, to 25.45% (vol USD 7.86M). In the daily series, the gap had not been below that since Jul 30, when it marked +39.50pp. Worth recording what this is NOT: convergence in LEVEL. The market pays 65.50% probability of victory and the polling measures 41% of first-round voting intention, and those two quantities neither subtract from nor compare with each other in level. What coincided was DIRECTION and CAUSE, both tightening on the advance of the same name. THE SERIES PEAK IS STILL BEHIND US: Lula's maximum is 66.50% and the gap's is +41.80pp, both from the Aug 1 close. Flávio's peak in the series is far older and far higher, 45.20% on May 7, and the floor is 22.00% on Jul 3, so today's 25.45% is recovery inside a lowered range, not a return to the previous range. RENAN SANTOS fell 0.50pp to 7.45% (vol USD 8.86M), undoing yesterday's rise, and his polling in the Nexus round came in at 4%, which leaves the distance between price and polling at 3.45pp. CAIADO is at 1.15% (vol USD 5.30M) on the day he was formally nominated at his party convention and promised to pardon Bolsonaro. HADDAD fell from 0.30% to 0.15%. The second-place contract has Flávio at 80.50% and the third-place contract has Renan at 60.50% against Caiado at 25.00%.`,
  'polymarketComparison.sources':
    `${G('Polymarket', 'polymarket')} via the AFOS proxy, capture locked at 19:11 UTC on Aug 3 (scripts/capture-guard.ts, 2 readings 8 minutes apart with a 0.20pp tolerance). BTG/Nexus poll of Aug 3, TSE filing BR-02874/2026, via nexus.fsb.com.br. Market series checked across two windows, because of the 1,000-point ceiling on the history route.`,
  'polymarketComparison.candidates[0].pesquisaRange': `41-46%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `FRESH POLLING AND IT TIGHTENED. ${G('BTG/Nexus', 'nexus-btg')} of Aug 3 (n=2,002, fieldwork Jul 31 to Aug 2, telephone, 2pp margin, BR-02874/2026) gives 41% in the first round, against 42% in the institute's own Jul 27 round, and 46% in the runoff against Flávio, against 47% before. Both declines are 1pp and fall within the margin, meaning that in isolation they are not movement. What is movement is the other side: Flávio gained 4pp in the first round and 2pp in the runoff in the same round, and that is why the gap fell from 9pp to 4pp and the runoff became a 1pp ${G('statistical tie', 'empate-tecnico')}. Among the four national polls released since Jul 29, this is the one showing the tightest first round: 4pp here, 6pp in PoderData of Jul 30, 9.1pp in ${G('AtlasIntel', 'atlasintel')} of Jul 29 and 9.3pp in Vox Brasil of Jul 31.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `STANDING STILL at 65.50% (vol USD 7.92M), for a second straight session, in the capture locked at 19:11 UTC. The gap over Flávio closed 0.90pp and went to +40.05pp, but it closed WITHOUT the front-runner giving ground: the entire move belongs to the challenger. In the daily series, the gap had not been below that since Jul 30, when it marked +39.50pp. The series peak is still 66.50%, from the Aug 1 close.`,
  'polymarketComparison.candidates[1].pesquisaRange': `31-45%`,
  'polymarketComparison.candidates[1].polymarket': `25.45%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `THE MOVE OF THE DAY IS HIS. ${G('BTG/Nexus', 'nexus-btg')} of Aug 3 gives 37% in the first round, against 33% in the institute's own Jul 27 round, a 4pp rise that is DOUBLE the 2pp margin and therefore not explained by sampling noise. In the runoff he goes from 43% to 45% and sits 1pp behind Lula, within the margin, which qualifies as a ${G('statistical tie', 'empate-tecnico')}. The reading needs house context: the other three national polls since Jul 29 give first-round gaps of 6pp to 9.3pp, so this is the most favourable to him, and the distance between the highest and the lowest reading reaches 5.3pp.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `ROSE 0.90pp to 25.45% (vol USD 7.86M), the strongest move of the session among the top two. It moved in the SAME DIRECTION as the polling and on the same day, which is rare on this panel. A series caveat that matters: his peak is 45.20% on May 7 and his floor is 22.00% on Jul 3, so 25.45% is recovery inside a lowered range, not a return to the previous range. In the second-place contract he stands at 80.50%.`,
  'polymarketComparison.candidates[2].polymarket': `7.45%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `${G('BTG/Nexus', 'nexus-btg')} of Aug 3 gives 4%, against 5% in the institute's own Jul 27 round. He stays in the 3% to 4% band that institutes have been measuring since the end of July, after the 7.8% of ${G('AtlasIntel', 'atlasintel')} on Jul 29. In the runoff against Lula it is the worst of the round's four simulations: 47% x 37%.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `FELL 0.50pp to 7.45% (vol USD 8.86M), undoing yesterday's 0.35pp rise, which had broken nine straight sessions of decline. With polling at 4%, the distance between price and polling stands at 3.45pp. His accumulated volume, at USD 8.86M, sits above Lula's, which is USD 7.92M, even though the price is one eighth of it. He is the favourite in the third-place contract, at 60.50%.`,
  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `${G('BTG/Nexus', 'nexus-btg')} of Aug 3 gives 5% in the first round, against 6% in the institute's own Jul 27 round. In the runoff against Lula, 46% x 42%. Among the national polls since Jul 29, he trails only the 5.5% of Vox Brasil on Jul 31.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `At 1.15% (vol USD 5.30M), above the 0.90% floor the series touched intraday on Aug 2. The level holds on the day he was formally nominated at his party convention, promised to pardon Bolsonaro and those convicted over Jan 8, and contested the agribusiness vote with Flávio. He is the second name in the third-place contract, at 25.00%.`,
  'polymarketComparison.candidates[6].polymarket': `0.15%`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `PULLED BACK 0.15pp and stands at 0.15% (vol USD 6.64M). He is not a candidate and the contract prices a replacement scenario, so the level speaks to perceived risk around the ${G('PT', 'pt')} ticket, not to a race under way.`,
})
