/** Tradução do rebaseline das 19:25 — polls-data. */
import { construir } from '../build-locale-json'

const TRAVA_EN = 'The double-reading capture guard ran FOUR rounds today and failed all of them. The third failed precisely because Lula was in transit from 63.50% to 64.50%; the fourth repeated the entire presidential contract and failed a single book, the MDB in the Senate. That is why the presidential market goes in FIRM, including the 64.50%, and the MDB goes in as a declared RANGE of 24.65% to 26.65%. Live capture Jul 31, 22:25 UTC.'
const TRAVA_ES = 'La traba de doble lectura corrió CUATRO rondas hoy y reprobó todas. La tercera reprobó justamente porque Lula estaba en tránsito de 63,50% a 64,50%; la cuarta repitió el contrato presidencial entero y reprobó un solo book, el del MDB en el Senado. Por eso el presidencial entra FIRME, incluidos los 64,50%, y el MDB entra como FRANJA declarada de 24,65% a 26,65%. Captura en vivo 31 de julio, 22:25 UTC.'

const en = {
  'polymarketComparison.note': `Cross-reading of Jul 31, 19:25 capture: the front-runner BROKE the series top. Lula ROSE 1.00pp to 64.50% (vol USD 7.77M), passing for the first time since Apr 14 the 63.50% the AFOS series had been matching without exceeding on Jul 26, 28, 30 and 31. Flávio ROSE 0.40pp, to 24.35% (vol USD 7.76M), and even so the gap WIDENED from +39.55pp to +40.15pp, the widest in the series that holds both names, which begins on May 3, and the first reading above 40pp. THE POLL: Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, margin of 2.15pp, BR-01084/2026) gives Lula 40.5% x Flávio 31.2% in the [first round](/en/glossary#primeiro-turno) and 47.5% x 41.1% in the [runoff](/en/glossary#segundo-turno), and the 6.4pp of the runoff fall outside the two margins added together, so this reading does not describe a statistical tie. Renan Santos was cut by THREE consecutive institutes, 7.8%, 4% and 3.0%, and with the price at 8.15% the distance between market and poll reaches 5.15pp, against the 0.90pp this panel called convergence on Jul 29. On the day, Flávio lost the PP, which announced neutrality and vetoed the ticket with Tereza Cristina, and Republicanos called a convention for Aug 4 heading toward the same refusal. ${TRAVA_EN}`,
  'polymarketComparison.sources': 'Polymarket via AFOS proxy (live capture Jul 31, 22:25 UTC, degraded false, failedCount 0, scripts/capture-guard.ts across FOUR rounds, all failed; in the last one the only divergent book was senate:MDB, published as a range of 24.65% to 26.65%, and the entire presidential contract repeated, including Lula at 64.50%) + Vox Brasil Jul 31 (BR-01084/2026, n=2,100, field Jul 26-28, margin 2.15pp, latest national) + PoderData/Aya Jul 30 (BR-07845/2026, n=2,400) + AtlasIntel/Bloomberg Jul 29 (BR-08602/2026, n=5,021, largest sample of the window) + BTG/Nexus Jul 27 (BR-01489/2026) + Datafolha Jul 24 (BR-01166/2026) + Gerp Jul 22 (BR-05026/2026) + Indexa Jul 21 (BR-02904/2026) + Real Time Big Data Jul 21 (BR-09247/2026) + PoderData/Aya Jul 16 (BR-00059/2026) + Genial/Quaest Jul 15 (BR-07181/2026) + Futura/Apex Jul 14 (BR-07294/2026) + AtlasIntel Jul 1 (BR-04582/2026). AFOS series checked with scripts/check-superlativo.ts, directly against Neon, with no window cap: Camilo Santana maximum at 4.10% (May 3) and minimum at 0.50% (Jul 30); Caiado band between Jul 22 and Jul 30 of 1.80% to 2.40%, with series minimum at 0.90% (Jul 9); Zema maximum at 10.10% (Apr 26).',
  'polymarketComparison.candidates[0].polymarket': '64.50%',
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'ROSE 1.00pp to 64.50% (vol USD 7.77M), passing for the first time since Apr 14 the 63.50% the AFOS series had been matching without exceeding on Jul 26, 28, 30 and 31. The gap over Flávio WIDENED from +39.55pp to +40.15pp, the widest in the series that holds both names, which begins on May 3 and whose previous maximum was +39.80pp on Jul 26, and the first reading above 40pp. The gap widened with the opponent ALSO rising, which describes demand for the front-runner and not deterioration on the other side.',
  'polymarketComparison.candidates[1].polymarket': '24.35%',
  'polymarketComparison.candidates[1].tendenciaPolymarket': 'RISES 0.40pp to 24.35% (vol USD 7.76M), a fifth consecutive session without a fall, and even so SEES THE GAP WIDEN to +40.15pp, because Lula rose more in the same session. In the sub-markets the signal is CROSSED: he gives up 0.50pp in the [first-round](/en/glossary#primeiro-turno) second-place book, which goes to 78.50% in a contract of USD 216,000, and stays at 5.65% in the third-place book. The counterpart to the fall in the second-place book is Renan Santos rising 3.25pp in that same contract, which suggests internal reallocation rather than a fresh reading on the [runoff](/en/glossary#segundo-turno).',
  'polymarketComparison.candidates[2].tendenciaPolymarket': 'FALLS 0.30pp to 8.15% (vol USD 8.63M), a fourth consecutive session of decline in the winner contract. But the move of the day is the opposite in the placing book: it RISES 3.25pp in the [first-round](/en/glossary#primeiro-turno) second-place book, from 6.10% to 9.35% in a contract of USD 1.09M, recovering two thirds of what it had lost the day before, and stays at 61.50% in the third-place book. On Jul 30 the panel recorded that the money had reclassified him, taking away his [runoff](/en/glossary#segundo-turno) chance; today the same money gave much of it back, on the day the polling cut him for the third consecutive time. Both directions are recorded and neither is arbitrated. He holds, in this capture, the largest accumulated volume among the competitive names in the presidential market, USD 8.63M.',
  'polymarketComparison.candidates[3].polymarket': '1.60%',
  'polymarketComparison.candidates[3].tendenciaPolymarket': 'FALLS 0.95pp against the 2.55% of Jul 30 and goes to 1.60% (vol USD 5.22M), giving back more than the gain accumulated over two days. The series caveat is mandatory and cuts both ways: 1.60% is his lowest value since Jul 22 and sits BELOW the 1.80% to 2.40% band in which he traded over that period, but it remains well above the series minimum, 0.90%, from Jul 9. The 2.55% of Jul 30 was an upward deviation, and the price gave that deviation back and also lost its recent floor. And the signal is crossed, because in the [first-round](/en/glossary#primeiro-turno) third-place book he RISES 2.00pp, going to 27.50% in a contract of USD 37,000. The reading that holds is reallocation: the market moves him from candidate to win to candidate to finish third, and the polling does not follow, because it gave him precisely today the best mark of the window.',
  'polymarketComparison.candidates[5].polymarket': '0.35%',
  'polymarketComparison.candidates[5].tendenciaPolymarket': 'FALLS 0.20pp to 0.35% (vol USD 4.59M), in the FOURTH consecutive session of decline in the winner contract, and stays at 4.45% in the [first-round](/en/glossary#primeiro-turno) third-place book. A series caveat, and it is a large one: his maximum in the AFOS series is 10.10%, from Apr 26, so 0.35% is less than a twentieth of that level, and moves of 0.20pp in that range carry almost no informational value.',
  'polymarketComparison.candidates[6].polymarket': '0.25%',
  'polymarketComparison.candidates[6].tendenciaPolymarket': 'RISES 0.10pp to 0.25%, and stays at 1.00% in the [first-round](/en/glossary#primeiro-turno) second-place book. The scale caveat is mandatory: at a price of 0.25%, a rise of 0.10pp carries almost no informational value, and the move is recorded only because it is the third day in the same direction.',
}

const es = {
  'polymarketComparison.note': `Cruce del 31 de julio, captura de las 19:25: el favorito ROMPIÓ el techo de la serie. Lula SUBIÓ 1,00pp a 64,50% (vol USD 7,77M), superando por primera vez desde el 14 de abril el 63,50% que la serie del AFOS venía igualando sin sobrepasar el 26, 28, 30 y 31 de julio. Flávio SUBIÓ 0,40pp, a 24,35% (vol USD 7,76M), y aun así la brecha se ABRIÓ de +39,55pp a +40,15pp, la más ancha de la serie que tiene los dos nombres, que empieza el 3 de mayo, y la primera lectura por encima de 40pp. LA ENCUESTA: Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, BR-01084/2026) da Lula 40,5% x Flávio 31,2% en la [primera vuelta](/es/glossary#primeiro-turno) y 47,5% x 41,1% en la [segunda vuelta](/es/glossary#segundo-turno), y los 6,4pp de la segunda vuelta quedan fuera de los dos márgenes sumados, así que esta lectura no describe empate técnico. Renan Santos fue recortado por TRES institutos seguidos, 7,8%, 4% y 3,0%, y con el precio en 8,15% la distancia entre mercado y encuesta llega a 5,15pp, contra los 0,90pp que este panel llamó convergencia el 29 de julio. En el día, Flávio perdió al PP, que anunció neutralidad y vetó la fórmula con Tereza Cristina, y el Republicanos convocó convención para el 4 de agosto encaminando la misma negativa. ${TRAVA_ES}`,
  'polymarketComparison.sources': 'Polymarket vía proxy AFOS (captura en vivo 31 de julio, 22:25 UTC, degraded false, failedCount 0, scripts/capture-guard.ts en CUATRO rondas, todas reprobadas; en la última el único book divergente fue senate:MDB, publicado como franja de 24,65% a 26,65%, y el presidencial entero repitió, incluidos los 64,50% de Lula) + Vox Brasil 31 de julio (BR-01084/2026, n=2.100, campo 26-28 de julio, margen 2,15pp, última nacional) + PoderData/Aya 30 de julio (BR-07845/2026, n=2.400) + AtlasIntel/Bloomberg 29 de julio (BR-08602/2026, n=5.021, mayor muestra del recorte) + BTG/Nexus 27 de julio (BR-01489/2026) + Datafolha 24 de julio (BR-01166/2026) + Gerp 22 de julio (BR-05026/2026) + Indexa 21 de julio (BR-02904/2026) + Real Time Big Data 21 de julio (BR-09247/2026) + PoderData/Aya 16 de julio (BR-00059/2026) + Genial/Quaest 15 de julio (BR-07181/2026) + Futura/Apex 14 de julio (BR-07294/2026) + AtlasIntel 1 de julio (BR-04582/2026). Serie del AFOS verificada con scripts/check-superlativo.ts, directo en Neon, sin tope de ventana: máximo de Camilo Santana en 4,10% (3 de mayo) y mínimo en 0,50% (30 de julio); franja de Caiado entre el 22 y el 30 de julio de 1,80% a 2,40%, con mínimo de la serie en 0,90% (9 de julio); máximo de Zema en 10,10% (26 de abril).',
  'polymarketComparison.candidates[0].polymarket': '64,50%',
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'SUBIÓ 1,00pp a 64,50% (vol USD 7,77M), superando por primera vez desde el 14 de abril el 63,50% que la serie del AFOS venía igualando sin sobrepasar el 26, 28, 30 y 31 de julio. La brecha sobre Flávio se ABRIÓ de +39,55pp a +40,15pp, la más ancha de la serie que tiene los dos nombres, que empieza el 3 de mayo y cuyo máximo anterior era +39,80pp del 26 de julio, y la primera lectura por encima de 40pp. La brecha se abrió con el adversario TAMBIÉN subiendo, lo que describe demanda por el favorito y no deterioro del otro lado.',
  'polymarketComparison.candidates[1].polymarket': '24,35%',
  'polymarketComparison.candidates[1].tendenciaPolymarket': 'SUBE 0,40pp a 24,35% (vol USD 7,76M), quinta rueda seguida sin caída, y aun así VE LA BRECHA ABRIRSE a +40,15pp, porque Lula subió más en la misma rueda. En los submercados la señal es CRUZADA: cede 0,50pp en el book de segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), que pasa a 78,50% en un contrato de USD 216.000, y queda en 5,65% en el de tercer lugar. La contrapartida de la caída en el book de segundo lugar es el alza de 3,25pp de Renan Santos en ese mismo contrato, lo que sugiere reasignación interna y no lectura nueva sobre la [segunda vuelta](/es/glossary#segundo-turno).',
  'polymarketComparison.candidates[2].tendenciaPolymarket': 'CAE 0,30pp a 8,15% (vol USD 8,63M), cuarta rueda seguida de caída en el contrato de ganador. Pero el movimiento del día es el opuesto en el book de colocación: SUBE 3,25pp en el de segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), de 6,10% a 9,35% en un contrato de USD 1,09M, recuperando dos tercios de lo que había perdido 24 horas antes, y queda en 61,50% en el de tercer lugar. El 30 de julio el panel registró que el dinero lo había reclasificado, quitándole la chance de [segunda vuelta](/es/glossary#segundo-turno); hoy el mismo dinero devolvió buena parte de ella, el día en que la encuesta lo recortó por tercera vez seguida. Las dos direcciones quedan registradas y ninguna es arbitrada. Mantiene, en esta captura, el mayor volumen acumulado entre los nombres competitivos del presidencial, USD 8,63M.',
  'polymarketComparison.candidates[3].polymarket': '1,60%',
  'polymarketComparison.candidates[3].tendenciaPolymarket': 'CAE 0,95pp contra el 2,55% del 30 de julio y va a 1,60% (vol USD 5,22M), devolviendo más que el alza acumulada en dos días. La salvedad de serie es obligatoria y corta para los dos lados: 1,60% es su menor valor desde el 22 de julio y queda POR DEBAJO de la franja de 1,80% a 2,40% en que osciló en ese período, pero sigue bien por encima del mínimo de la serie, 0,90%, del 9 de julio. El 2,55% del 30 de julio era una desviación hacia arriba, y el precio devolvió esa desviación y además perdió el piso reciente. Y la señal es cruzada, porque en el book de tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno) SUBE 2,00pp, pasando a 27,50% en un contrato de USD 37.000. La lectura que se sostiene es de reasignación: el mercado lo mueve de candidato a ganar a candidato a terminar tercero, y la encuesta no acompaña, porque le dio justamente hoy la mejor marca del recorte.',
  'polymarketComparison.candidates[5].polymarket': '0,35%',
  'polymarketComparison.candidates[5].tendenciaPolymarket': 'CAE 0,20pp a 0,35% (vol USD 4,59M), en la CUARTA rueda seguida de caída en el contrato de ganador, y queda en 4,45% en el book de tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno). Salvedad de serie, y es grande: su máximo en la serie del AFOS es 10,10%, del 26 de abril, así que 0,35% es menos de un veinteavo de aquel nivel, y movimientos de 0,20pp en esa franja tienen valor informativo casi nulo.',
  'polymarketComparison.candidates[6].polymarket': '0,25%',
  'polymarketComparison.candidates[6].tendenciaPolymarket': 'SUBE 0,10pp a 0,25%, y queda en 1,00% en el book de segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno). La salvedad de escala es obligatoria: en un precio de 0,25%, un alza de 0,10pp tiene valor informativo casi nulo, y el movimiento solo se registra porque es el tercer día en la misma dirección.',
}

construir('polls-data', 'en', en)
construir('polls-data', 'es', es)
