/**
 * Mapa EN de 14/Ago para polls-data.json.
 * Convenções: ponto decimal, vírgula de milhar, datas no formato "Aug 14".
 */
import { construir } from '../build-locale-json'

const NOVO = 'confirmed reading of Aug 14, 14:46 BRT (17:46 UTC)'
const VELHO = 'last confirmed reading, from Aug 12, 16:41 BRT'
const SEM = `THERE IS NO NEW READING FOR HIM ON Aug 14. The value displayed is that of the ${VELHO}`

construir('polls-data', 'en', {
  'approvalData.note':
    `THE MOST RECENT NATIONAL POLL IS STILL THE ONE FROM Aug 13, because the Quaest poll of Aug 14 had no published result at the time of this capture. PoderData/Aya: 43% approve and 50% disapprove of Lula's work, a net 7pp negative, against 47.3% x 49.9% from Futura Inteligência on Aug 11, which was the pair in force until yesterday. ⚠️ THESE ARE TWO DIFFERENT QUESTIONS ON THE SAME DAY, and the panel does not add them together: Revista Oeste reported 51% disapproval OF THE GOVERNMENT in the same survey, a figure that is not the same as the 50% disapproval of LULA'S WORK published by Poder360, CNN Brasil and Rádio Itatiaia. REJECTION tied at 48% for Lula and 48% for Flávio Bolsonaro. Still in the table are Gerp from Aug 11 with 53% disapproval, BTG/Nexus from Aug 10 with 46% x 49%, Palver from the same day with 45% x 55% and Genial/Quaest from Aug 5 with 48% x 47%. WHAT THE SET SHOWS: across eight readings over nine days, disapproval runs from 47% to 55%, a spread of 8pp between houses, and the net runs from 1pp positive to 10pp negative. No house changed sides, and the new one falls inside the range that already existed. ⚠️ PROVENANCE DECLARED: approval and disapproval are from PoderData/Aya of Aug 13 (fieldwork Aug 9 to Aug 12, n=2,400, telephone, margin 2pp, registration BR-06868/2026), as the most recent national reading; the remaining 7% is the arithmetic residue between the two published values, not a figure the house released under that label. The government-performance breakdown, at 36% positive, 26% average and 36% negative, is still the one from Genial/Quaest of Aug 5, because no later house published that full breakdown. The panel prefers to declare the mix rather than hide it.`,

  'polymarketComparison.note':
    `UPDATE OF Aug 14. THERE IS A NEW PRICE READING FOR THE PRESIDENTIAL MARKET AND THE BIGGER FACT OF THE DAY IS INSTITUTIONAL. On price, the leader is at 63.50% for the sixth consecutive day in the recorded series, the runner-up rose 0.20pp to 27.85% and was the only name above 1% to rise, Renan Santos fell 0.30pp to 7.15% and Caiado rose 0.10pp to 1.05%. The distance between the top two narrowed from 35.85pp to 35.65pp, and all of the movement came from the runner-up. For the second and third place contracts, for the Senate and for the STF impeachment contract there is no new reading on Aug 14, and the values displayed are those of Aug 12, 16:41 BRT. In the polls nothing changed: Quaest releases a national poll today with 13 candidates and the results were not published at the time of this capture, so PoderData/Aya of Aug 13 remains in force. ⭐ THE TSE SUSPENDED THE PROCESSING OF NEW PARTY AFFILIATIONS nationwide, after the false registration of the runner-up in Missão and an identified attempt against the leader's affiliation, according to G1, O Globo, Gazeta do Povo, CartaCapital and Money Times. The candidate registration deadline closes on Aug 15.`,

  'polymarketComparison.sources':
    `Polymarket prices via the AFOS proxy, and the panel only publishes a price that two independent readings, taken eight minutes apart, confirm. On Aug 14 there is a new confirmed reading for the presidential market, at 14:46 BRT (17:46 UTC). For the second and third place contracts, for the Senate and for the STF impeachment contract there is no new reading on Aug 14, and the values displayed are those of the last confirmed reading, at 16:41 BRT on Aug 12. ✅ POLLS: Quaest releases on Aug 14 a national poll with 13 candidates tested (n=2,004, BR-06773/2026) and the results were not published at the time of this capture, so PoderData/Aya of Aug 13 remains in force, n=2,400, registration BR-06868/2026, fieldwork Aug 9 to Aug 12. Also in force are CNT/MDA BR-06935/2026, Gerp BR-08045/2026 and Futura Inteligência BR-08109/2026, all from Aug 11, plus Palver BR-06596/2026 and BTG/Nexus BR-08428/2026, from Aug 10, and Genial/Quaest BR-06591/2026 and Meio/Ideia BR-04579/2026, from Aug 5. Next national polls in the queue: Quaest (n=2,004, BR-06773/2026), scheduled for publication on Aug 14 and still without a released result at the time of this capture, Nexus (n=2,000, BR-03317/2026) on Aug 17 and Real Time Big Data (n=1,600, BR-05423/2026) on Aug 19.`,

  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON Aug 14 UP TO THE TIME OF THIS CAPTURE. Quaest releases a national poll today with 13 candidates tested, and the results had not yet been published. PoderData/Aya of Aug 13 remains in force (n=2,400, telephone, fieldwork Aug 9 to Aug 12, BR-06868/2026): 41% in the first round and 46% x 45% in the runoff against Flávio Bolsonaro. Its finding still holds and it separates the two rounds: in the first round the distance has not moved in four weeks, 6pp on Jul 16, 6pp on Jul 30 and 6pp now; in the runoff the distance fell from 3pp to 1pp over the same span. REJECTION at 48%, tied with his opponent's. PERSONAL APPROVAL at 43% against 50% disapproval. Adding up the eight national polls since Aug 5 he runs from 38% to 44% in the first round.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `NEW READING ON Aug 14, ${NOVO}. At 63.50% (vol USD 8.25M cumulative), the SAME value as the reading of Aug 12. The recorded series shows 63.50% on every day from Aug 9 to Aug 14, six days without variation. SERIES CAVEAT, measured over all recorded points and not over the last point of each day: among the points since May 16 the peak is 66.50%, on Aug 1 at 23:00, and the floor is 39.50%, on May 26. The distance to the runner-up narrowed by 0.20pp since Aug 12, and the movement was entirely the opponent's.`,

  'polymarketComparison.candidates[1].polymarket': `27.85%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `NO NEW NATIONAL POLL ON Aug 14 UP TO THE TIME OF THIS CAPTURE. PoderData/Aya of Aug 13 remains in force, giving him 35% in the first round and 45% in the runoff, 1pp from the leader, inside the 2pp margin. Against his own house he did NOT move in the first round, repeating the 35% of Jul 30, but he NARROWED THE RUNOFF from 43% to 45%. REJECTION at 48%, exactly equal to the leader's. Across the eight national polls since Aug 5 he runs from 28.7% to 38% in the first round, and the spread between houses on the same question remains above 9pp, double the spread measured on the leader.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `NEW READING ON Aug 14, ${NOVO}. At 27.85% (vol USD 8.20M cumulative). The price went from 27.65% on Aug 12 to 27.85% now, a rise of 0.20pp. ⭐ He was the ONLY name above 1% to rise in this reading, and the entire narrowing of the distance to the leader came from him. SERIES CAVEAT, measured over all recorded points: among the points since May 16, 51 had a value equal to or above 27.85%, with a peak of 33.20% on Jun 2 at 19:30 and a floor of 22.00% on Jul 3 at 01:00. ⚠️ The rise falls in the same window in which the registry obstacle to his candidacy was removed, and the panel records the order without asserting cause.`,

  'polymarketComparison.candidates[2].polymarket': `7.15%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `His first-round percentages did not appear in the reports on PoderData of Aug 13, so the most recent reading on him remains the one from Aug 11. The 5% from Gerp, the 4% from Genial/Quaest and from BTG/Nexus, the 4.7% from Meio/Ideia and the 10% from Palver online all still stand. In PoderData's runoff scenario he is the ONLY one of the four tested whom the leader beats, according to Bnews, while the other three tie. The method effect remains the reading on him: the same name runs from 4% to 10% depending on the interview environment, and the caveat was declared by Palver itself.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `NEW READING ON Aug 14, ${NOVO}. At 7.15% (vol USD 9.59M cumulative). The price went from 7.45% on Aug 12 to 7.15% now, a fall of 0.30pp. It was the LARGEST FALL among names above 1% in this reading. He keeps the largest cumulative volume in the presidential book among names above 1%. The price remains BETWEEN the two polling methods, above the 4% to 5% of telephone and in-person and below the 10% of online.`,

  'polymarketComparison.candidates[3].polymarket': `1.05%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `PoderData of Aug 13 remains in force, placing him TIED with the leader in the runoff, according to CNN Brasil and Bnews, alongside Flávio Bolsonaro and Zema. His first-round percentages in that round did not appear in the reports captured, and the 4% from Gerp and from Genial/Quaest, the 5.7% from Meio/Ideia and the 5% from BTG/Nexus still stand. The runoff tie is his second in four days, after the BTG/Nexus one of Aug 10.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `NEW READING ON Aug 14, ${NOVO}. At 1.05% (vol USD 5.70M cumulative). The price went from 0.95% on Aug 12 to 1.05% now, a rise of 0.10pp. He is the only one in the pack with a new reading in this round, because the others are below the 0.5% cutoff the panel uses to separate price from noise. ⚠️ HIS CONTRAST REMAINS THE LARGEST ON THE PANEL: he ties with the leader in the runoff of a national poll and is priced at a little over 1% to win the election. Tying in the runoff and winning the election are different questions, and the panel does not add them together.`,

  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `${SEM}, at 0.05% (vol USD 13.91M cumulative), below the 0.5% cutoff the panel uses to separate price from noise. It remains the largest cumulative volume in the whole presidential book, with the price at the floor. High volume with probability at the floor is conviction already priced in, not movement, and variations in this band have almost no informational value.`,

  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `${SEM}, at 0.35% (vol USD 5.07M cumulative), below the 0.5% cutoff the panel uses to separate price from noise. ⚠️ HIS CONTRAST REMAINS: he ties with the leader in the runoff of PoderData of Aug 13 and is priced at 0.35% to win the election.`,

  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `${SEM}, at 0.15% (vol USD 7.06M cumulative), below the 0.5% cutoff. A variation in this band has no informational value, and the underlying caveat remains: he is NOT a presidential candidate and is running for the governorship of São Paulo.`,
})
