/**
 * Mapa ES de 16/Ago para polls-data.json.
 * Convenções: vírgula decimal e ponto de milhar, como no pt-BR.
 */
import { construir } from '../build-locale-json'

const CAR = 'lectura confirmada del 16 de ago, 16:56 BRT (19:56 UTC)'

construir('polls-data', 'es', {
  'polls[0].note':
    `Encuesta nacional Genial/Quaest difundida el 14 de ago a las 21:00 (G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, Correio Braziliense). Primera vuelta Lula 38% x Flávio Bolsonaro 31%, una distancia de 7pp, con Renan Santos y Ronaldo Caiado en 4% y Augusto Cury y Romeu Zema en 2%. Balotaje Lula 43% x Flávio 40%, 3pp, con margen de 2pp. ⭐ LA COMPARACIÓN QUE VALE ES CON LA PROPIA CASA, Y ES SIMÉTRICA: contra la Quaest del 5 de ago, la primera vuelta pasó de 39% x 30% a 38% x 31% y el balotaje pasó de 44% x 39% a 43% x 40%. En las dos vueltas Lula cedió 1 punto y Flávio ganó 1 punto, y cada distancia se achicó 2pp. Misma casa, mismo método presencial y misma muestra. RECHAZO separado por primera vez en esta ventana: Flávio 54%, Lula 52% y Caiado 35%, este último con alto desconocimiento declarado por la casa. EVALUACIÓN DEL GOBIERNO: 46% aprueban y 48% desaprueban; en la escala de excelente/bueno, regular y malo/pésimo, son 36% positivos, 25% regular y 37% negativos, según InfoMoney y UOL. ⭐ CRUCES DIFUNDIDOS DESPUÉS, EL 15 Y EL 16 DE AGO: la firmeza del voto, con 77% de los electores de Lula llamando definitiva a la decisión y 22% diciendo que todavía pueden cambiar, y el electorado de Zema apareciendo como el menos convencido del cuadro, según G1; y el comportamiento entre independientes, franja en la que Flávio marca 35% contra 29% de Lula en el balotaje, según O Globo. ⚠️ La justicia electoral registra el campo del 10 al 13 de ago y la casa publicó del 10 al 12 de ago; el panel exhibe el período registrado.`,
  'polls[0].source':
    `Genial/Quaest vía G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, UOL y Correio Braziliense, del 14 al 16 de ago`,

  'approvalData.note':
    `SIN NACIONAL NUEVA EL 16 DE AGO. Sigue vigente la Genial/Quaest del 14 de ago, difundida a las 21:00: 46% aprueban y 48% desaprueban el gobierno de Lula, saldo de 2pp negativos y empate técnico por el margen de 2pp, contra 43% x 50% de la PoderData/Aya del 13 de ago. ⚠️ SON DOS CASAS EN DOS DÍAS CON 5 PUNTOS DE DIFERENCIA EN EL SALDO, y el panel no elige entre ellas: la distancia entre casas es el dato. En la escala de excelente/bueno, regular y malo/pésimo, la Quaest trae 36% positivos, 25% regular y 37% negativos, según InfoMoney y UOL. RECHAZO en la misma encuesta: Flávio Bolsonaro 54%, Lula 52% y Ronaldo Caiado 35%, este último con alto desconocimiento declarado por la casa. ⭐ Un cruce difundido el 15 de ago agrega la FIRMEZA del voto, dimensión distinta del nivel: entre los electores de Lula, 77% dicen que la decisión es definitiva y 22% dicen que todavía pueden cambiar, y el electorado menos convencido del cuadro es el de Romeu Zema, según G1. 📅 Nexus publica el 17 de ago y Real Time Big Data el 19 de ago, las dos con campo en curso.`,

  'polymarketComparison.note':
    `ACTUALIZACIÓN DEL 16 DE AGO, PRIMER DÍA DE LA CAMPAÑA OFICIAL. EL MOVIMIENTO ENTERO DEL DÍA ESTÁ EN EL PRECIO, porque no salió ninguna encuesta nacional nueva. El líder subió 2,00pp y cerró en 66,50%, valor que IGUALA el máximo de una serie de 174 puntos desde el 19 de may, sin ningún punto por encima. El segundo subió 1,30pp y cerró en 29,45%, tercer día seguido de alza, y aun así la distancia entre los dos se AMPLIÓ, de 36,35pp a 37,05pp. ⚠️ CAUSACIÓN, y el panel declara esto antes de cualquier lectura: los puntos que produjeron el alza se registraron a las 05:01 BRT, ANTES de los actos de campaña del día. El precio se movió al entrar el primer día de campaña, y NO en reacción a los actos. ⛔ Sin superlativo indebido: la distancia de 37,05pp es ordinaria en la serie, con 30 de los 89 días registrando un valor igual o mayor y un pico de 41,80pp el 1 de ago. ⭐ EL HALLAZGO ES DE CONTRATO, NO DE NIVEL. El primero del pelotón cayó a 4,70% en la VICTORIA, tercer cierre seguido en baja desde el 8,00% del cierre del 11 de ago, y en el contrato de TERCER LUGAR está en 53,00%, todavía la mayor probabilidad de ese book pero cayendo desde el 65,00% del 9 de ago. Ronaldo Caiado cayó 0,45pp en la victoria y SUBIÓ 6,50pp en la posición, con el tercer lugar pasando de 31,00% en el cierre del 12 de ago a 37,50%. ⛔ Terminar tercero y ganar la elección son preguntas distintas, y el panel no las suma. ⭐ EN LAS ENCUESTAS LA NOVEDAD ES DE FIRMEZA: un cruce de la Quaest difundido el 15 de ago muestra 77% de los electores del líder llamando definitiva a la decisión y señala al electorado de Romeu Zema como el menos convencido del cuadro, según G1. 📌 El panel registra que los dos instrumentos separaron a los mismos dos grupos en esta ventana, y registrar la coincidencia no es afirmar que uno explica al otro.`,
  'polymarketComparison.sources':
    `Precios de Polymarket vía el proxy de AFOS, y el panel solo publica un precio que dos lecturas independientes, tomadas con ocho minutos de intervalo, confirmen. El 16 de ago hay lectura confirmada nueva para TODOS los contratos seguidos, a las 16:56 BRT (19:56 UTC): presidencial, segundo lugar, tercer lugar, Senado e impeachment en el Supremo. Encuestas registradas ante la justicia electoral y difundidas por las casas, con reporteo de G1, CNN Brasil, Folha de S.Paulo, Valor Econômico, Estadão, Poder360, VEJA, InfoMoney, UOL, O Globo y Correio Braziliense.`,

  'polymarketComparison.candidates[0].polymarket': `66,50%`,
  'polymarketComparison.candidates[0].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 16 DE AGO. La Genial/Quaest del 14 de ago sigue vigente con 38% en la primera vuelta y 43% en el balotaje, y ese 38% es el PISO de las nueve nacionales desde el 5 de ago, cuyo rango va de 38% a 44%. Rechazo de 52%, por debajo del 54% de su rival. ⭐ CRUCE NUEVO DIFUNDIDO EL 15 DE AGO, y mide FIRMEZA y no nivel: entre sus electores, 77% dicen que la decisión de votarlo es definitiva y 22% dicen que todavía pueden cambiar, según G1. Es la primera vez que el panel registra la dureza de la intención, dimensión distinta de su tamaño.`,
  'polymarketComparison.candidates[0].tendenciaPolymarket':
    `⭐ ALZA DE 2,00pp EL 16 DE AGO, de 64,50% a 66,50% (vol USD 8,40M acumulado), ${CAR}. El valor IGUALA EL MÁXIMO DE LA SERIE: entre los 174 puntos registrados desde el 19 de may NINGUNO está por encima de 66,50%, y el único otro día en ese nivel fue el 1 de ago. ⛔ El panel dice iguala, no supera. La distancia hacia el segundo se AMPLIÓ, de 36,35pp a 37,05pp. ⚠️ CAUSACIÓN: el punto se registró a las 05:01 BRT, ANTES de los actos de campaña del día, así que el movimiento antecede a los actos y no es reacción a ellos.`,

  'polymarketComparison.candidates[1].polymarket': `29,45%`,
  'polymarketComparison.candidates[1].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 16 DE AGO. La Genial/Quaest del 14 de ago sigue vigente con 31% en la primera vuelta y 40% en el balotaje, habiendo ganado 1 punto en cada una contra la propia casa del 5 de ago, y es la primera nacional que lo muestra acortando las dos vueltas. RECHAZO de 54%, el más alto del cuadro. ⭐ En los cruces difundidos después: el voto por él aparece entre los dos más consolidados del cuadro, según G1, y entre electores independientes marca 35% contra 29% del líder en el balotaje, según O Globo.`,
  'polymarketComparison.candidates[1].tendenciaPolymarket':
    `ALZA DE 1,30pp EL 16 DE AGO, de 28,15% a 29,45% (vol USD 8,34M acumulado), ${CAR}, en el tercer día seguido de alza. ⚠️ Aun subiendo quedó MÁS LEJOS del líder, porque el líder subió 2,00pp y la distancia se amplió a 37,05pp. ⛔ Sin superlativo: de los 173 puntos desde el 19 de may, 4 fueron mayores, y el máximo sigue en 33,20%, del 2 de jun. Mantiene 87,00% en el contrato de segundo lugar de la primera vuelta, el valor más alto de ese book.`,

  'polymarketComparison.candidates[2].polymarket': `4,70%`,
  'polymarketComparison.candidates[2].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 16 DE AGO. La Genial/Quaest del 14 de ago lo mantiene en 4% en la primera vuelta, exactamente el mismo valor del 5 de ago, es decir, nueve días sin avance contra la propia regla de la casa. Siguen el 5% de Gerp, el 4% de BTG/Nexus, el 4,7% de Meio/Ideia y el 10% de Palver por internet. El efecto de método sigue siendo la lectura sobre él: el mismo nombre va de 4% a 10% según el ambiente de la entrevista, y la salvedad fue declarada por la propia Palver.`,
  'polymarketComparison.candidates[2].tendenciaPolymarket':
    `🔴 CAÍDA DE 2,45pp EL 16 DE AGO, a 4,70% (vol USD 9,77M acumulado), ${CAR}, con RUPTURA HACIA ABAJO DEL 5% en el tercer cierre seguido en baja, desde el 8,00% del cierre del 11 de ago. ⭐ Y el contrato de POSICIÓN cuenta otra cosa: en el tercer lugar de la primera vuelta está en 53,00%, todavía la mayor probabilidad de ese book, pero TAMBIÉN EN CAÍDA, porque eran 65,00% el 9 de ago, es decir, 12,00pp perdidos en siete días. Pierde terreno en las dos preguntas a la vez, y el panel no las suma. Mantiene el mayor volumen acumulado del book presidencial entre los nombres por encima de 1%.`,

  'polymarketComparison.candidates[3].polymarket': `0,60%`,
  'polymarketComparison.candidates[3].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 16 DE AGO. La Genial/Quaest del 14 de ago le da 4% en la primera vuelta, el mismo del 5 de ago, y RECHAZO de 35%, el más bajo del cuadro, contra el 54% y el 52% de los dos primeros. ⚠️ Rechazo bajo con desconocimiento alto NO es aceptación: significa que la mayor parte del electorado todavía no formó opinión, y una opinión no formada puede ir para los dos lados. Sigue empatando con el líder en el balotaje de la PoderData del 13 de ago.`,
  'polymarketComparison.candidates[3].tendenciaPolymarket':
    `⭐ EL CRUCE DE CONTRATO DEL DÍA. En el precio de VICTORIA cayó 0,45pp el 16 de ago, de 1,05% a 0,60% (vol USD 5,92M acumulado), ${CAR}, rozando el corte de 0,5% que el panel usa para separar precio de ruido. En el contrato de POSICIÓN SUBIÓ: el tercer lugar de la primera vuelta pasó de 31,00%, en el cierre del 12 de ago, a 37,50%, un alza de 6,50pp con cuatro cierres seguidos en alza. ⛔ Terminar tercero y ganar la elección son preguntas distintas, y el panel no las suma ni trata una como desmentido de la otra.`,

  'polymarketComparison.candidates[4].tendenciaPesquisa':
    `Ninguna nacional de la ventana lo prueba en escenario presidencial, y la ausencia de prueba es información que el panel registra en vez de repetir un dato viejo. ⭐ El 16 de ago abrió campaña a la REELECCIÓN al gobierno de São Paulo, lo que cierra la duda por acto público y no por inferencia.`,
  'polymarketComparison.candidates[4].tendenciaPolymarket':
    `ESTABLE EN 0,05% el 16 de ago (vol USD 13,92M acumulado), ${CAR}, por debajo del corte de 0,5%. Sigue siendo el mayor volumen acumulado de todo el book presidencial, con el precio en el piso, lo que es convicción ya descontada y no movimiento. ⭐ La salvedad del panel se volvió ACTO PÚBLICO FECHADO: el 16 de ago abrió formalmente campaña a la REELECCIÓN al gobierno de São Paulo, en Osasco, según O Globo y Folha de S.Paulo, y sin la presencia del candidato a la Presidencia apoyado por el mismo campo.`,

  'polymarketComparison.candidates[5].tendenciaPesquisa':
    `SIN NACIONAL NUEVA EL 16 DE AGO. La Genial/Quaest del 14 de ago lo mantiene en 2% en la primera vuelta, el mismo valor del 5 de ago. Siguen el 2% de Gerp, el 3% de BTG/Nexus y el 2,6% de Meio/Ideia. 🔴 CRUCE NUEVO DIFUNDIDO EL 15 DE AGO: tiene el ELECTORADO MENOS CONVENCIDO del cuadro, según G1, dato sobre la solidez del apoyo y no sobre su tamaño.`,
  'polymarketComparison.candidates[5].tendenciaPolymarket':
    `CAÍDA DE 0,20pp el 16 de ago, de 0,35% a 0,15% (vol USD 5,49M acumulado), ${CAR}, por debajo del corte de 0,5%. En el contrato de tercer lugar de la primera vuelta tiene 5,00%, muy por detrás del 53,00% del primero del pelotón. Abrió la campaña con una misa en Montes Claros, en el norte de Minas Gerais, con promesa de una cárcel de máxima seguridad y críticas a ministros del Supremo, según Folha de S.Paulo y Valor Econômico.`,

  'polymarketComparison.candidates[6].tendenciaPesquisa':
    `Ninguna nacional de la ventana lo incluye en escenario presidencial. ⭐ El 16 de ago abrió campaña al GOBIERNO DE SÃO PAULO y habló en el acto de apertura del presidente, en el ABC, según O Globo y Times Brasil, lo que confirma por acto público fechado que no disputa la Presidencia.`,
  'polymarketComparison.candidates[6].tendenciaPolymarket':
    `CAÍDA DE 0,10pp el 16 de ago, de 0,15% a 0,05% (vol USD 7,09M acumulado), ${CAR}, por debajo del corte de 0,5%, y una variación en esa franja no tiene valor informativo. ⭐ La salvedad del panel se volvió ACTO PÚBLICO FECHADO: el 16 de ago abrió formalmente campaña al GOBIERNO DE SÃO PAULO y habló en el acto de apertura del presidente, en el ABC, según O Globo y Times Brasil. No es candidato a la Presidencia, y un escenario presidencial que lo incluya es hipótesis de encuesta.`,
})
