/** Tradução do /atualizar-brz de 01/Ago 13:49 — polls-data. */
import { construir } from '../build-locale-json'

const TRAVA_EN = 'The double-reading capture guard failed the first round, with Renan Santos in transit from 7.15% to 7.60% and Caiado\'s third-place book between 22.00% and 22.50%, and APPROVED the second. All prices go in firm, with no declared range. Live capture Aug 1, 16:49 UTC.'
const TRAVA_ES = 'La traba de doble lectura reprobó la primera ronda, con Renan Santos en tránsito de 7,15% a 7,60% y el tercer lugar de Caiado entre 22,00% y 22,50%, y APROBÓ la segunda. Todos los precios entran firmes, sin franja declarada. Captura en vivo 1 de agosto, 16:49 UTC.'

const RENAN_EN = 'RENAN SANTOS fell 0.55pp to 7.60% (vol USD 8.72M), his lowest value since May 14, and the fall is one of sequence: 12.00% on Jul 23, with 4.40pp given up across nine sessions. Before May 14 the series records lower values, which is why the window is declared.'
const RENAN_ES = 'RENAN SANTOS cayó 0,55pp a 7,60% (vol USD 8,72M), su menor valor desde el 14 de mayo, y la caída es de secuencia: 12,00% el 23 de julio, con 4,40pp cedidos en nueve ruedas. Antes del 14 de mayo la serie registra valores menores, por eso la ventana se declara.'

const en = {
  'polymarketComparison.note': `Cross-reading of Aug 1, 13:49 capture: a second consecutive day of a new top. Lula ROSE 1.00pp to 65.50% (vol USD 7.82M), the MAXIMUM of the AFOS series, which runs from Apr 14 to today. Flávio ROSE 0.40pp, to 24.75% (vol USD 7.79M), and even so the gap WIDENED from +40.15pp to +40.75pp, also the maximum of the series that holds both names, which begins on May 3. On both days the record came with the opponent rising too. NO NEW POLL: no national poll has been published since Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, margin of 2.15pp, BR-01084/2026), so the price moved 2.00pp across two sessions with no voting-intention reading in between, and the panel asserts no cause. ${RENAN_EN} With his polling at 3.0%, the distance between market and poll NARROWED from 5.15pp to 4.60pp, and it narrowed from the price side. The whole chasing pack shrank: Caiado at 1.35%, with a 5.00pp fall in the third-place book, and Camilo Santana at 0.45%, his lowest value in the series. Politically, Flávio remains without a running mate four days from the Aug 5 deadline, and Republicanos made Tarcísio's re-election bid in São Paulo official, leaving the presidential-alliance decision for the national convention on Aug 4. ${TRAVA_EN}`,
  'polymarketComparison.sources': 'Polymarket via AFOS proxy (live capture Aug 1, 16:49 UTC, degraded false, failedCount 0, scripts/capture-guard.ts across TWO rounds: the first failed, with Renan Santos in transit from 7.15% to 7.60% and Caiado\'s third place between 22.00% and 22.50%, and the second APPROVED, with every book within 0.20pp) + Vox Brasil Jul 31 (BR-01084/2026, n=2,100, field Jul 26-28, margin 2.15pp, latest national) + PoderData/Aya Jul 30 (BR-07845/2026, n=2,400) + AtlasIntel/Bloomberg Jul 29 (BR-08602/2026, n=5,021, largest sample of the window) + BTG/Nexus Jul 27 (BR-01489/2026) + Datafolha Jul 24 (BR-01166/2026) + Gerp Jul 22 (BR-05026/2026) + Indexa Jul 21 (BR-02904/2026) + Real Time Big Data Jul 21 (BR-09247/2026) + PoderData/Aya Jul 16 (BR-00059/2026) + Genial/Quaest Jul 15 (BR-07181/2026) + Futura/Apex Jul 14 (BR-07294/2026) + AtlasIntel Jul 1 (BR-04582/2026). AFOS series checked with scripts/check-superlativo.ts, directly against Neon, with no window cap: Lula maximum at 65.50% (Aug 1) and gap maximum at +40.75pp (Aug 1); Renan Santos at 7.60% today, his lowest since May 14, with a maximum of 17.90% on Jun 9; Camilo Santana maximum at 4.10% (May 3) and minimum now at 0.45% (Aug 1); Caiado minimum at 0.90% (Jul 9); Zema maximum at 10.10% (Apr 26). For Tarcísio de Freitas the series holds only three days, between Apr 28 and May 14, and for that reason no superlative is asserted about him.',
  'polymarketComparison.candidates[0].polymarket': '65.50%',
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'ROSE 1.00pp to 65.50% (vol USD 7.82M), the MAXIMUM of the AFOS series for a second consecutive day. The gap over Flávio WIDENED from +40.15pp to +40.75pp, also the maximum of the series that holds both names, which begins on May 3. On both days the record came with the opponent rising too, which describes demand for the front-runner and not deterioration on the other side. And the price moved 2.00pp across two sessions with NO national poll in between, an asymmetry the panel records without asserting cause.',
  'polymarketComparison.candidates[1].polymarket': '24.75%',
  'polymarketComparison.candidates[1].tendenciaPesquisa': 'Vox Brasil of Jul 31 (n=2,100, field Jul 26 to 28, margin of 2.15pp, BR-01084/2026) has him at 31.2% in the [first round](/en/glossary#primeiro-turno) and 41.1% in the [runoff](/en/glossary#segundo-turno). The 6.4pp separating him from Lula fall outside the two margins added together, which moves away from the statistical-tie reading PoderData supported on Jul 30. No new national poll since then. On ticket-building, the PP announced NEUTRALITY and with that blocked the ticket that would have had Tereza Cristina as running mate; she publicly regretted the end of the arrangement, saying that what happened is settled, and he thanked her and said he is negotiating with other parties. On Saturday, Republicanos made official Tarcísio de Freitas\'s bid for RE-ELECTION as governor of São Paulo, with him present on the platform, but the party\'s national convention, which decides the presidential alliance, is only on Aug 4. The Aug 5 deadline still has the running mate undefined.',
  'polymarketComparison.candidates[1].tendenciaPolymarket': 'RISES 0.40pp to 24.75% (vol USD 7.79M), a sixth consecutive session without a fall, and even so SEES THE GAP WIDEN to +40.75pp, because Lula rose more. In the sub-markets the signal favoured him: he RISES 1.00pp in the [first-round](/en/glossary#primeiro-turno) second-place book, which goes to 79.50% in a contract of USD 216,000, his highest mark there in the panel\'s tracking, and gives way to 4.95% in the third-place book. The [runoff](/en/glossary#segundo-turno) position became more consolidated, not less. Politically, he remains WITHOUT a running mate four days from the Aug 5 deadline.',
  'polymarketComparison.candidates[2].polymarket': '7.60%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': 'THREE consecutive institutes cut him, and it is the sequence that matters, not the isolated figure: 7.8% at AtlasIntel on Jul 29, 4% at PoderData on Jul 30 and 3.0% at Vox Brasil on Jul 31. There has been no new national poll since then, but the price moved: with the market now at 7.60%, the distance between market and poll NARROWED from 5.15pp to 4.60pp, and it narrowed from the price side, not the polling side. On Jul 29 this panel recorded that same distance at 0.90pp and called it convergence; it went on to quadruple and is now receding, and it is on the record that the Jul 29 reading did not hold. The dispersion between houses stopped being dispersion: the three most recent readings are also the three lowest, which describes a downward trend.',
  'polymarketComparison.candidates[2].tendenciaPolymarket': 'FALLS 0.55pp to 7.60% (vol USD 8.72M), his lowest value since May 14, in a fifth consecutive session of decline. The fall is one of sequence, not of a single session: on Jul 23 he stood at 12.00% and has since given ground in eight of nine rounds, adding up to 4.40pp. Before May 14 the series records lower values, which is why the window is declared. In the [first-round](/en/glossary#primeiro-turno) second-place book he gives up 0.80pp, to 8.55%, a third direction in three sessions in that contract, and stays FLAT at 61.50% in third place. With the polling at 3.0%, the distance between market and poll NARROWED from 5.15pp to 4.60pp, from the price side.',
  'polymarketComparison.candidates[3].polymarket': '1.35%',
  'polymarketComparison.candidates[3].tendenciaPolymarket': 'FALLS 0.25pp to 1.35% (vol USD 5.24M), and COLLAPSES 5.00pp in the [first-round](/en/glossary#primeiro-turno) third-place book, from 27.50% to 22.50% in a contract of USD 37,000, undoing in a single session the entire gain the panel recorded the day before. The series caveat is mandatory and does not describe a collapse: his minimum in the AFOS series is 0.90%, from Jul 9, so 1.35% remains above the floor, even if below the 1.80% to 2.40% band in which he traded between Jul 22 and Jul 30. Yesterday\'s reallocation, from winner to third place, was undone within 24 hours, and he now gives way in both books at the same time.',
  'polymarketComparison.candidates[4].polymarket': '0.05%',
  'polymarketComparison.candidates[4].tendenciaPolymarket': 'Goes to 0.05%, with the largest accumulated volume in the presidential book, USD 13.69M. It is the legacy anomaly that serves as a permanent reminder of method: volume measures traded history, not current conviction. On Saturday, Republicanos made official his bid for RE-ELECTION as governor of São Paulo. The panel records the level and does NOT claim it is his lowest: the AFOS series holds only three days for this name, between Apr 28 and May 14, and does not support a superlative.',
  'polymarketComparison.candidates[5].tendenciaPolymarket': 'Stays FLAT at 0.35% (vol USD 4.61M), interrupting four consecutive sessions of decline in the winner contract, and RISES to 4.60% in the [first-round](/en/glossary#primeiro-turno) third-place book. A series caveat, and it is a large one: his maximum in the AFOS series is 10.10%, from Apr 26, so 0.35% is less than a twentieth of that level and moves in this range carry almost no informational value. He remains WITHOUT a running mate, with the Aug 5 deadline four days away.',
  'polymarketComparison.candidates[6].tendenciaPolymarket': 'Stays FLAT at 0.25% and holds 1.00% in the [first-round](/en/glossary#primeiro-turno) second-place book, interrupting the run of gains without giving ground. The scale caveat still applies: at this price level, a move of 0.05pp or 0.10pp carries almost no informational value, and the panel records the level, not the swing.',
}

const es = {
  'polymarketComparison.note': `Cruce del 1 de agosto, captura de las 13:49: segundo día seguido de techo nuevo. Lula SUBIÓ 1,00pp a 65,50% (vol USD 7,82M), MÁXIMO de la serie del AFOS, que va del 14 de abril a hoy. Flávio SUBIÓ 0,40pp, a 24,75% (vol USD 7,79M), y aun así la brecha se ABRIÓ de +40,15pp a +40,75pp, también máximo de la serie que tiene los dos nombres, que empieza el 3 de mayo. En los dos días el récord vino con el adversario subiendo también. SIN ENCUESTA NUEVA: ninguna nacional se publicó desde la Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, BR-01084/2026), así que el precio se movió 2,00pp en dos ruedas sin lectura de intención de voto en el intervalo, y el panel no afirma causa. ${RENAN_ES} Con su encuesta en 3,0%, la distancia entre mercado y encuesta se ESTRECHÓ de 5,15pp a 4,60pp, y se estrechó por el lado del precio. Todo el pelotón encogió: Caiado en 1,35%, con caída de 5,00pp en el book de tercer lugar, y Camilo Santana en 0,45%, su menor valor en la serie. En lo político, Flávio sigue sin vice a cuatro días del plazo del 5 de agosto, y el Republicanos oficializó la candidatura de Tarcísio a la reelección en São Paulo, dejando la decisión de alianza presidencial para la convención nacional del 4 de agosto. ${TRAVA_ES}`,
  'polymarketComparison.sources': 'Polymarket vía proxy AFOS (captura en vivo 1 de agosto, 16:49 UTC, degraded false, failedCount 0, scripts/capture-guard.ts en DOS rondas: la primera reprobada, con Renan Santos en tránsito de 7,15% a 7,60% y el tercer lugar de Caiado entre 22,00% y 22,50%, y la segunda APROBADA, con todos los books dentro de 0,20pp) + Vox Brasil 31 de julio (BR-01084/2026, n=2.100, campo 26-28 de julio, margen 2,15pp, última nacional) + PoderData/Aya 30 de julio (BR-07845/2026, n=2.400) + AtlasIntel/Bloomberg 29 de julio (BR-08602/2026, n=5.021, mayor muestra del recorte) + BTG/Nexus 27 de julio (BR-01489/2026) + Datafolha 24 de julio (BR-01166/2026) + Gerp 22 de julio (BR-05026/2026) + Indexa 21 de julio (BR-02904/2026) + Real Time Big Data 21 de julio (BR-09247/2026) + PoderData/Aya 16 de julio (BR-00059/2026) + Genial/Quaest 15 de julio (BR-07181/2026) + Futura/Apex 14 de julio (BR-07294/2026) + AtlasIntel 1 de julio (BR-04582/2026). Serie del AFOS verificada con scripts/check-superlativo.ts, directo en Neon, sin tope de ventana: máximo de Lula en 65,50% (1 de agosto) y máximo de la brecha en +40,75pp (1 de agosto); Renan Santos en 7,60% hoy, su menor desde el 14 de mayo, con máximo de 17,90% el 9 de junio; máximo de Camilo Santana en 4,10% (3 de mayo) y mínimo ahora en 0,45% (1 de agosto); mínimo de Caiado en 0,90% (9 de julio); máximo de Zema en 10,10% (26 de abril). Para Tarcísio de Freitas la serie tiene apenas tres días, entre el 28 de abril y el 14 de mayo, y por eso no se afirma ningún superlativo sobre él.',
  'polymarketComparison.candidates[0].polymarket': '65,50%',
  'polymarketComparison.candidates[0].tendenciaPolymarket': 'SUBIÓ 1,00pp a 65,50% (vol USD 7,82M), MÁXIMO de la serie del AFOS por segundo día seguido. La brecha sobre Flávio se ABRIÓ de +40,15pp a +40,75pp, también máximo de la serie que tiene los dos nombres, que empieza el 3 de mayo. En los dos días el récord vino con el adversario subiendo también, lo que describe demanda por el favorito y no deterioro del otro lado. Y el precio se movió 2,00pp en dos ruedas SIN ninguna encuesta nacional en el intervalo, asimetría que el panel registra sin afirmar causa.',
  'polymarketComparison.candidates[1].polymarket': '24,75%',
  'polymarketComparison.candidates[1].tendenciaPesquisa': 'Vox Brasil del 31 de julio (n=2.100, campo del 26 al 28 de julio, margen de 2,15pp, BR-01084/2026) lo trae en 31,2% en la [primera vuelta](/es/glossary#primeiro-turno) y 41,1% en la [segunda vuelta](/es/glossary#segundo-turno). Los 6,4pp que lo separan de Lula quedan fuera de los dos márgenes sumados, lo que aleja la lectura de empate técnico que PoderData sostenía el 30 de julio. Sin encuesta nacional nueva desde entonces. En la formación de fórmula, el PP anunció NEUTRALIDAD y con eso bloqueó la fórmula que tendría a Tereza Cristina como vice; ella lamentó públicamente el fin de la articulación, diciendo que lo que fue está puesto, y él agradeció y afirmó que negocia con otros partidos. Este sábado el Republicanos oficializó la candidatura de Tarcísio de Freitas a la REELECCIÓN en el gobierno de São Paulo, con él presente en el palco, pero la convención nacional del partido, que decide la alianza presidencial, es solo el 4 de agosto. El plazo del 5 de agosto sigue con la vice indefinida.',
  'polymarketComparison.candidates[1].tendenciaPolymarket': 'SUBE 0,40pp a 24,75% (vol USD 7,79M), sexta rueda seguida sin caída, y aun así VE LA BRECHA ABRIRSE a +40,75pp, porque Lula subió más. En los submercados la señal le fue favorable: SUBE 1,00pp en el book de segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), que pasa a 79,50% en un contrato de USD 216.000, su mayor marca ahí en el seguimiento del panel, y cede a 4,95% en el de tercer lugar. La posición de [segunda vuelta](/es/glossary#segundo-turno) quedó más consolidada, no menos. En lo político, sigue SIN vice a cuatro días del plazo del 5 de agosto.',
  'polymarketComparison.candidates[2].polymarket': '7,60%',
  'polymarketComparison.candidates[2].tendenciaPesquisa': 'TRES institutos seguidos lo recortaron, y es la secuencia lo que importa, no el número aislado: 7,8% en AtlasIntel el 29 de julio, 4% en PoderData el 30 de julio y 3,0% en Vox Brasil el 31 de julio. No hubo encuesta nacional nueva desde entonces, pero el precio se movió: con el mercado ahora en 7,60%, la distancia entre mercado y encuesta se ESTRECHÓ de 5,15pp a 4,60pp, y se estrechó por el lado del precio, no de la encuesta. El 29 de julio este panel registró esa misma distancia en 0,90pp y la llamó convergencia; llegó a cuadruplicarse y ahora retrocede, y queda registrado que la lectura del 29 de julio no se sostuvo. La dispersión entre casas dejó de ser dispersión: las tres lecturas más recientes son también las tres más bajas, lo que describe tendencia de caída.',
  'polymarketComparison.candidates[2].tendenciaPolymarket': 'CAE 0,55pp a 7,60% (vol USD 8,72M), su menor valor desde el 14 de mayo, en la quinta rueda seguida de caída. La caída es de secuencia, no de una rueda: el 23 de julio estaba en 12,00% y desde entonces cedió en ocho de nueve rondas, sumando 4,40pp. Antes del 14 de mayo la serie registra valores menores, por eso la ventana se declara. En el book de segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno) cede 0,80pp, a 8,55%, tercera dirección en tres ruedas en ese contrato, y queda ESTABLE en 61,50% en el de tercer lugar. Con la encuesta en 3,0%, la distancia entre mercado y encuesta se ESTRECHÓ de 5,15pp a 4,60pp, por el lado del precio.',
  'polymarketComparison.candidates[3].polymarket': '1,35%',
  'polymarketComparison.candidates[3].tendenciaPolymarket': 'CAE 0,25pp a 1,35% (vol USD 5,24M), y SE DESPLOMA 5,00pp en el book de tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno), de 27,50% a 22,50% en un contrato de USD 37.000, deshaciendo en una sola rueda toda el alza que el panel registró la víspera. La salvedad de serie es obligatoria y no describe colapso: su mínimo en la serie del AFOS es 0,90%, del 9 de julio, así que 1,35% sigue por encima del piso, aunque por debajo de la franja de 1,80% a 2,40% en que osciló entre el 22 y el 30 de julio. La reasignación de ayer, de ganador a tercer lugar, se deshizo en 24 horas, y ahora cede en los dos books al mismo tiempo.',
  'polymarketComparison.candidates[4].polymarket': '0,05%',
  'polymarketComparison.candidates[4].tendenciaPolymarket': 'Va a 0,05%, con el mayor volumen acumulado del book presidencial, USD 13,69M. Es la anomalía de legado que sirve de recordatorio permanente de método: el volumen mide historia negociada y no convicción actual. Este sábado el Republicanos oficializó su candidatura a la REELECCIÓN en el gobierno de São Paulo. El panel registra el nivel y NO afirma que sea el menor suyo: la serie del AFOS tiene apenas tres días para este nombre, entre el 28 de abril y el 14 de mayo, y no sostiene superlativo.',
  'polymarketComparison.candidates[5].tendenciaPolymarket': 'Queda ESTABLE en 0,35% (vol USD 4,61M), interrumpiendo cuatro ruedas seguidas de caída en el contrato de ganador, y SUBE a 4,60% en el book de tercer lugar de la [primera vuelta](/es/glossary#primeiro-turno). Salvedad de serie, y es grande: su máximo en la serie del AFOS es 10,10%, del 26 de abril, así que 0,35% es menos de un veinteavo de aquel nivel y movimientos en esta franja tienen valor informativo casi nulo. Sigue SIN vice, con el plazo del 5 de agosto a cuatro días.',
  'polymarketComparison.candidates[6].tendenciaPolymarket': 'Queda ESTABLE en 0,25% y mantiene 1,00% en el book de segundo lugar de la [primera vuelta](/es/glossary#primeiro-turno), interrumpiendo la racha de alza sin ceder. La salvedad de escala sigue valiendo: en este nivel de precio, un movimiento de 0,05pp o 0,10pp tiene valor informativo casi nulo, y el panel registra el nivel, no la oscilación.',
}

construir('polls-data', 'en', en)
construir('polls-data', 'es', es)
