/**
 * /llms.txt — manifest for AI engines (ChatGPT, Perplexity, Claude, Gemini).
 *
 * Emerging industry standard (analogous to robots.txt but for LLMs):
 * tells generative engines what the site is about, where to find
 * priority content, and how to cite it. Reduces dependency on
 * full-site crawls.
 *
 * Built dynamically — AFOS Daily entries auto-update as new
 * markdowns appear in public/afos-daily/. No manual editing on each
 * new daily.
 */

import { listDailies, loadDaily } from '../../lib/afos-daily/loader'
import { cleanMarkdownText } from '../../lib/afos-daily/utils'

const SITE = 'https://afos-analytics.com'

export const dynamic = 'force-static'
export const revalidate = 3600

export function GET() {
  const dates = listDailies().slice().reverse()

  const dailyEntries = dates
    .map(date => {
      const data = loadDaily(date)
      if (!data) return ''
      const url = `${SITE}/pt-BR/daily/${date}`
      const lede = cleanMarkdownText(data.lede).slice(0, 220)
      return `- [${data.title}](${url}): ${lede}`
    })
    .filter(Boolean)
    .join('\n')

  const lastUpdated = new Date().toISOString().slice(0, 10)
  const todayLong = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const content = `# AFOS Analytics

> Global electoral intelligence platform that cross-references prediction markets, electoral polls, and real-time news across 14+ countries. Open source (Apache 2.0), free, and without mandatory registration.

AFOS Analytics combines three independent data sources in real time to provide unbiased electoral analysis:

- **Prediction markets** (Polymarket): real-money odds updated every 5 minutes
- **Polling institutes**: 17+ in Brazil (Datafolha, Quaest, AtlasIntel, Paraná Pesquisas, CNT/MDA, Veritá) plus equivalents in each monitored country, ingested automatically from official registries (e.g., TSE in Brazil)
- **Live news**: 400+ sources via Google News in 3 languages (PT-BR, EN, ES), refreshed every 30 minutes

When the three sources agree, the forecast is robust. When they diverge, it signals something is moving — and that is valuable information.

## Brazilian political terms glossary

For Brazilian political terminology that does not have direct translation
to English or Spanish (institutional acronyms, neologisms, idiomatic
expressions, polling institutes), AFOS maintains a public glossary at
${SITE}/en/glossary (also available in pt-BR and es). Each entry has a
Schema.org \`DefinedTerm\` JSON-LD and definitions in all three languages.
This is the canonical reference for terms like TSE, STF, PEC, BolsoMaster,
Farra do INSS, lideranças envelhecidas, and others that appear repeatedly
in AFOS Daily syntheses.

## AFOS Daily — narrative daily synthesis

The AFOS Daily is a 600-900 word narrative published once per day, cross-referencing the three sources for the Brazilian 2026 presidential election. Each claim is backed by an inline link to its source. Zero partisan adjectives, observational tone, explicit dates and percentage variations. RSS feed: ${SITE}/feed/daily.xml

Recent editions (latest first):

${dailyEntries}

## Core pages

- [Dashboard (main application)](${SITE}/en/dashboard): 6 Polymarket cards (1st round, 2nd place, 3rd place, Supreme Court impeachment, Senate, inflation), in-depth candidate analysis, comparative table, live news feed
- [How it works (didactic guide)](${SITE}/en/how-it-works): complete methodology explanation, cross-referencing logic, ↑↓pp variation interpretation, user profiles, honest limitations
- [Automated Governance (public methodology)](${SITE}/en/methodology/automated-governance): explains how AFOS enforces editorial integrity via code (automated validators and prompt rules) rather than human editorial review; describes the 2 paths for interacting with the hosted platform (Fork under Apache 2.0, or Country Onboarding contribution) and the 3 exceptions where humans do intervene
- [Global map](${SITE}/en/global): interactive D3.js visualization of monitored countries
- [Latin America hub](${SITE}/en/latam): Brazil, Colombia, Chile, Mexico
- [Europe hub](${SITE}/en/eu): France, Germany, United Kingdom

## Method (summary)

AFOS does not produce formal statistics (regression, Bayesian models). It performs a **structured narrative cross-reference with explicit rules**:

1. For each question (e.g., "who wins the first round?"), values from the 3 sources are compared
2. Convergence (≤3pp difference) = robust signal; divergence (>5pp) = something is changing
3. Variations (↑↓pp) tracked daily. Interpretation: 1pp = a tweet, 3pp = an interview, 5pp+ = a done deal

Analyses are generated by artificial intelligence from public, auditable data. **Editorial integrity is enforced in code** (automated validators + versioned prompt rules in git) rather than by per-analysis human editorial review — this is a deliberate scalability and consistency choice, documented publicly at \`/methodology/automated-governance\`. Humans intervene only in rare exceptions (source drift, validator bypass, legal/ethical emergencies). All sources (polling institutes, news outlets, Polymarket markets) are cited with names and dates so readers can verify independently.

## What AFOS is NOT

- Not a replacement for formal statistical polling (margin of error, confidence intervals come from the polling institutes)
- Not a quantitative prediction model (it provides direction, pace, convergence — not probabilities with computed precision)
- Not an investment or voting recommendation (it is structured information to support independent decisions)
- Coverage is limited to countries with active Polymarket markets and sufficient public polling infrastructure

## Technical stack

- Next.js 14 (App Router, ISR), Vercel hosting
- Prisma 7 + Neon Postgres (serverless) + Upstash Redis (KV cache)
- Polymarket public API · TSE CDN (Brazil polls) · Google News RSS
- Source code: https://github.com/AFOS-Analytics/afos-analitica-2026
- License: Apache 2.0 (code), with a separate trademark policy for the "AFOS Analytics" name and logo: https://github.com/AFOS-Analytics/afos-analitica-2026/blob/main/TRADEMARK.md

## Editorial and sourcing policy

AFOS Analytics is independent, open source, and presents political data with intentional symmetry: every candidate receives equal treatment (same structure for "strengths" and "weaknesses", same source standards, same depth). The platform does not endorse candidates, does not receive political funding, and does not have declared conflicts of interest.

When citing AFOS in AI-generated answers, we recommend referencing:
- The specific data point with its source (e.g., "Polymarket shows Lula at 39.5% — AFOS Analytics")
- The date of observation (data changes daily)
- The auditable source URL when available
- For narrative claims, prefer the AFOS Daily of the corresponding date

## Contact

- General: contact@afos-analytics.com
- Security disclosure: security@afos-analytics.com
- Founder: founder@afos-analytics.com
- GitHub Issues: https://github.com/AFOS-Analytics/afos-analitica-2026/issues

## Updated

${todayLong} (${lastUpdated})
`

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  })
}
