/**
 * Rebaseline 19:25 — parte C: o `cruzamento` inteiro.
 *
 * A parte A fez só dois cortes cirúrgicos nele, e o resto do texto continuou
 * com os números das 17:33 (63,50%, +39,20pp, Caiado 1,75%, Camilo 2,20%,
 * "as DUAS rodadas", USD 117,03M). Texto principal do painel não pode ficar
 * internamente inconsistente, então ele é reescrito por inteiro.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const P = 'public/analysis-criteriosa.json'
const o = JSON.parse(readFileSync(P, 'utf-8'))

o.cruzamento = 'O CRUZAMENTO DE 31/JUL terminou com o favorito onde ele nunca tinha estado. Lula SUBIU 1,00pp e foi a 64,50% (vol USD 7,77M), superando pela primeira vez desde 14/Abr os 63,50% que a série do AFOS vinha igualando sem ultrapassar em 26, 28, 30 e 31/Jul. Flávio SUBIU 0,40pp, para 24,35% (vol USD 7,76M), e mesmo assim o gap ABRIU de +39,55pp para +40,15pp, o mais largo da série que tem os dois nomes, iniciada em 03/Mai, cujo máximo anterior era +39,80pp de 26/Jul. É a primeira leitura acima de 40pp. A distinção importa e o painel a faz: o gap abriu com o adversário TAMBÉM subindo, o que descreve demanda pelo favorito e não deterioração do outro lado. '
  + 'A URNA. Vox Brasil de 31/Jul (n=2.100, campo 26 a 28/Jul, margem de 2,15pp, 95% de confiança, BR-01084/2026) dá Lula 40,5% x Flávio 31,2% no 1º turno, com Caiado 5,5%, Zema 3,2% e Renan Santos 3,0%, e Lula 47,5% x Flávio 41,1% no returno. A vantagem de 6,4pp no returno fica FORA da margem somada, então esta leitura NÃO descreve empate técnico, ao contrário da PoderData de 30/Jul. E o registro que organiza a semana é este: TRÊS casas mediram o gap do 1º turno em 9,1pp, 6pp e 9,3pp. Duas concordam em torno de 9pp e a que destoa é a PoderData. Em 30/Jul o painel escreveu, corretamente, que comparar casas diferentes e chamar a diferença de movimento é trocar de régua; a Vox de hoje reforça essa disciplina por outro caminho, mostrando que a PoderData é que estava fora do conjunto. '
  + 'O ACHADO DE MERCADO É RENAN SANTOS, e ele é de sequência, não de número isolado. TRÊS institutos seguidos o cortaram: AtlasIntel 7,8% em 29/Jul, PoderData 4% em 30/Jul e Vox Brasil 3,0% em 31/Jul. Com o preço em 8,15% (vol USD 8,63M), a distância entre mercado e urna vai a 5,15pp, a maior do recorte. Em 29/Jul este painel registrou essa mesma distância em 0,90pp e a chamou de convergência, sublinhando que ela estreitava pelo lado da urna. Três institutos depois, ela quadruplicou, e fica registrado que aquela leitura não se sustentou. E há uma contradição DENTRO do próprio mercado: no mesmo dia em que a urna o corta pela terceira vez, o book de 2º lugar do 1º turno SOBE 3,25pp, de 6,10% para 9,35% (vol USD 1,09M), devolvendo dois terços do que fora retirado na véspera, enquanto o de 3º lugar fica em 61,50%. Em 30/Jul o painel escreveu que o dinheiro o havia reclassificado; hoje o mesmo dinheiro desfez parte disso. As duas direções ficam registradas e nenhuma é arbitrada. '
  + 'CAIADO DEVOLVEU MAIS DO QUE TINHA GANHO: caiu 0,95pp contra os 2,55% de 30/Jul e foi a 1,60% (vol USD 5,22M), e ao mesmo tempo SUBIU 2,00pp no 3º lugar, para 27,50%. A ressalva de série corta para os dois lados e é necessária: 1,60% está dentro da faixa normal dele desde 22/Jul e os 2,55% de 30/Jul é que eram o desvio, então não houve colapso, houve devolução de desvio. No mesmo dia, a Vox lhe deu 5,5%, a melhor urna nacional dele no recorte, e a divergência entre institutos sobre ele segue aberta em QUATRO níveis no mesmo mês: 6%, 5,5%, 5% e 3,1%. CAMILO SANTANA subiu 0,85pp, de 0,50% para 1,35% (vol USD 4,17M), e Geraldo Alckmin ficou em 0,45% (vol USD 4,98M), no dia em que o PCdoB formalizou apoio à chapa Lula-Alckmin. O painel registra a coincidência e não afirma causa. Sobre Camilo, a ressalva de série é obrigatória: 1,35% NÃO é recorde, o máximo dele é 4,10%, de 03/Mai, e o movimento é recuperação do MÍNIMO da série, 0,50%, marcado em 30/Jul. Os dois passaram por valores mais altos ao longo do dia, 2,20% e 1,10% às 17:33, e devolveram parte antes desta captura. '
  + 'O EIXO PARTIDÁRIO foi o do dia, e ele tem DUAS portas, não uma. O PP VETOU, e o caso fechou no mesmo dia. Na manhã de 31/Jul, Flávio Bolsonaro disse que Tereza Cristina aceitara o convite para vice na noite anterior, com a ressalva de que as conversas seguiam para saber se o partido avançaria. Minutos depois, o PP anunciou NEUTRALIDADE nas eleições, informando que consultou os diretórios estaduais e decidiu não convocar Convenção Nacional, o que barra a chapa. A senadora, que lidera o PP no Senado, compartilhou a nota do partido e acatou. Flávio respondeu que respeita e que não desiste. E não foi só o PP. Horas depois, o Republicanos marcou convenção nacional para 04/Ago com a maioria dos diretórios estaduais consultados defendendo neutralidade, encaminhando a recusa de aliança nacional com o senador. O painel separa os dois verbos porque eles não são iguais: o PP DECIDIU, o Republicanos ainda NÃO decidiu. Em 24/Jul esta série registrou que, sem a federação União-PP, Flávio buscava Republicanos e Podemos; as duas portas que ele procurou naquele dia estão agora fechando. O prazo de 05/Ago segue com a vice indefinida. No mercado, Tereza Cristina aparece em 0,20% no contrato PRESIDENCIAL, e a distinção importa: aquele contrato mede quem ganha a Presidência, não quem ocupa a vaga de vice. Em Minas Gerais, Marcelo Aro deixou a chapa de Zema ao Senado para disputar o governo, movimento que Zema chamou publicamente de traição, e o Novo descartou Barbosa como vice. '
  + 'O EIXO JUDICIAL produziu o maior volume de fato novo do caso Master desde a abertura do inquérito, e o painel registra que a leitura publicada às 17:33, de que o dia não tinha ato novo, estava errada. André Mendonça retirou o sigilo de parte da investigação que apura se o senador Jaques Wagner recebeu vantagem indevida para atuar em favor de interesses do Banco Master no Senado. Com o sigilo levantado, veio a público um relatório da Polícia Federal que identificou 74 ligações entre o senador e Augusto Lima, ex-sócio do banco, entre novembro de 2023 e maio de 2025, somando mais de cinco horas e trinta minutos de conversa em 555 dias. Na mesma decisão, Mendonça autorizou a PF a monitorar a localização do celular do senador, apontando risco de vazamento da operação. O Novo pediu abertura de processo no Conselho de Ética do Senado e Wagner disse que vai provar inocência. Um dia antes, em 30/Jul, o mesmo ministro havia autorizado inquérito para apurar tráfico de influência de Fábio Luís Lula da Silva, o Lulinha, junto ao Ministério da Saúde e à Presidência; Lula disse que o filho terá de provar inocência e que não usará o cargo para protegê-lo. Nada disso é condenação e o painel não trata como tal: são inquérito, quebra de sigilo e representação partidária. '
  + 'NOS DEMAIS MERCADOS, o impeachment de ministro do STF ficou ESTÁVEL em 3,10% (vol USD 83 mil), sem variação nas oito leituras das quatro rodadas da trava. Vale sublinhar que esse contrato NÃO precifica o caso Wagner, que corre contra um senador e não contra um ministro, então preço parado ali não é resposta do mercado ao que saiu hoje. No Senado, o PL SUBIU 6,50pp, para 72,00% (vol USD 258 mil), e o MDB entra como FAIXA declarada de 24,65% a 26,65%: somados, os dois passam de 97% de probabilidade atribuída a apenas duas legendas, o que por si só indica spread largo. Na inflação, a faixa modal segue em 5,00% a 5,49%, com 38,30%, e a de 4,50% a 4,99% subiu 1,20pp, para 33,70%, num book de USD 81 mil não coberto pela trava. '
  + 'UMA NOTA DE CAPTURA, e ela explica o número principal. A trava de dupla leitura rodou QUATRO rodadas hoje e reprovou todas. A terceira reprovou justamente porque Lula estava em trânsito de 63,50% para 64,50%; a quarta repetiu o contrato presidencial inteiro e reprovou um book só, o do MDB no Senado. Por isso o presidencial entra FIRME, incluindo os 64,50%, e o MDB entra como FAIXA declarada. Volume total acumulado no presidencial em USD 117,06M. Captura ao vivo 31/Jul 22:25 UTC.'

const proibido = ['+39,20pp', 'ESTÁVEL em 63,50%', '1,75% (vol USD 5,22M)', 'Camilo Santana a 2,20%', 'USD 117,03M', 'as DUAS rodadas de hoje', '25,20% a 26,60%', 'ESTÁVEL em 62,00%']
const erros = proibido.filter(s => o.cruzamento.includes(s))
if (erros.length) { console.error('❌ número velho sobreviveu: ' + erros.join(' | ')); process.exit(1) }
for (const s of ['64,50%', '+40,15pp', '1,60%', '1,35%', '117,06M', '24,65% a 26,65%', '74 ligações']) {
  if (!o.cruzamento.includes(s)) { console.error('❌ faltou: ' + s); process.exit(1) }
}

writeFileSync(P, JSON.stringify(o, null, 2) + '\n', 'utf-8')
console.log('✅ cruzamento reescrito (' + o.cruzamento.length + ' caracteres)')
