import { readFileSync, readdirSync, existsSync, statSync } from 'fs'
import { join } from 'path'
import matter from 'gray-matter'
import type { AfosDailyData } from '../../app/components/AfosDailyTemplate'

const DAILY_DIR = join(process.cwd(), 'public', 'afos-daily')
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/

export const SUPPORTED_LOCALES = ['pt-BR', 'en', 'es'] as const
export type SupportedLocale = typeof SUPPORTED_LOCALES[number]

export function isValidLocale(loc: string): loc is SupportedLocale {
  return (SUPPORTED_LOCALES as readonly string[]).includes(loc)
}

export function isValidDate(date: string): boolean {
  if (!DATE_RE.test(date)) return false
  // Defensively validate that the date is a real calendar date
  // (the regex alone allows things like "2026-13-45" or "2026-02-30").
  const [y, m, d] = date.split('-').map(Number)
  if (m < 1 || m > 12 || d < 1 || d > 31) return false
  const probe = new Date(Date.UTC(y, m - 1, d))
  return (
    probe.getUTCFullYear() === y &&
    probe.getUTCMonth() === m - 1 &&
    probe.getUTCDate() === d
  )
}

// Memoize listDailies for 60s. The directory only changes when a new daily
// is committed (manual op). 60s TTL means worst case 60s of stale list,
// but eliminates readdirSync from the hot path of /api/afos-daily/latest.
// Empty results get a shorter TTL (5s) so newly-published dailies post-deploy
// are picked up quickly during launch-day rapid validation.
const LIST_TTL_MS = 60 * 1000
const LIST_TTL_EMPTY_MS = 5 * 1000
let listCache: { list: string[]; expiresAt: number } | null = null

export function listDailies(): string[] {
  const now = Date.now()
  if (listCache && now < listCache.expiresAt) return listCache.list

  if (!existsSync(DAILY_DIR)) {
    listCache = { list: [], expiresAt: now + LIST_TTL_EMPTY_MS }
    return []
  }
  try {
    const list = readdirSync(DAILY_DIR)
      .filter(f => f.endsWith('.md'))
      .map(f => f.replace('.md', ''))
      .filter(isValidDate)
      .sort()
    const ttl = list.length > 0 ? LIST_TTL_MS : LIST_TTL_EMPTY_MS
    listCache = { list, expiresAt: now + ttl }
    return list
  } catch (err) {
    console.error('[afos-daily] Failed to list dailies:', err)
    return []
  }
}

/**
 * Reads only the `status` field from frontmatter without full markdown parse.
 * Fast path for listPublishedDailies() and isVisibleInProduction().
 *
 * Defaults to 'draft' (fail-safe): if frontmatter is malformed, missing,
 * or status field is absent, the file is hidden from production until
 * an explicit `status: published` is set. Existing dailies (22-30/Abr +
 * 01/Mai) were migrated to have explicit status; new files generated by
 * /afos-daily skill must include it.
 *
 * The case-insensitive match accepts: published, draft, archived (future).
 * Any other value (typo, weird state) is treated as draft.
 */
const STATUS_RE = /^status:\s*([a-z]+)\s*$/im
const VALID_STATUSES = new Set(['published', 'draft', 'archived'])

// Memoize per (date, mtime) — sitemap, feed, llms.txt all call this 3× per
// rebuild. At 100 dailies that's 300 file reads each cold build; index
// short-circuits the second and third caller.
const statusCache = new Map<string, { mtime: number; status: string }>()

function readStatusFast(date: string): string {
  const path = join(DAILY_DIR, `${date}.md`)
  if (!existsSync(path)) return 'draft'
  let mtime = 0
  try {
    mtime = statSync(path).mtimeMs
  } catch {
    return 'draft'
  }
  const cached = statusCache.get(date)
  if (cached && cached.mtime === mtime) return cached.status
  try {
    const head = readFileSync(path, 'utf-8').slice(0, 500)
    const m = head.match(STATUS_RE)
    if (!m) {
      statusCache.set(date, { mtime, status: 'draft' })
      return 'draft'
    }
    const status = m[1].toLowerCase()
    const final = VALID_STATUSES.has(status) ? status : 'draft'
    statusCache.set(date, { mtime, status: final })
    return final
  } catch {
    return 'draft'
  }
}

/**
 * Returns only dates where frontmatter status is 'published'. Used by
 * sitemap, RSS feed, and getLatestDate to prevent drafts from leaking
 * to public surfaces (Google, RSS subscribers, default daily redirect).
 */
export function listPublishedDailies(): string[] {
  return listDailies().filter(d => readStatusFast(d) === 'published')
}

/**
 * Production-visibility gate for the [date]/page.tsx. Drafts are 404 in
 * production but render normally on Vercel preview deploys (so the user
 * can review before flipping status to published).
 */
export function isVisibleInProduction(date: string): boolean {
  return readStatusFast(date) === 'published'
}

/**
 * True when the locale-specific markdown for `date` exists on disk. PT-BR
 * uses bare `{date}.md`; EN/ES use `{date}.{locale}.md`. Used for hreflang
 * truthfulness — only declare alternates that actually resolve.
 */
export function dailyExists(date: string, locale: string): boolean {
  const filename = locale === 'pt-BR' ? `${date}.md` : `${date}.${locale}.md`
  return existsSync(join(DAILY_DIR, filename))
}

export function getLatestDate(): string | null {
  // Only published dailies count as "latest" — drafts must not become the
  // page that /[locale]/daily/ redirects to.
  const all = listPublishedDailies()
  return all.length ? all[all.length - 1] : null
}

/**
 * Returns the YYYY-MM-DD adjacent to the given date in the sorted list of
 * available dailies. Used for prev/next navigation on the synthesis page.
 * Filters drafts so prev/next never lands on an unpublished page.
 */
export function getAdjacentDates(date: string): { previous?: string; next?: string } {
  const all = listPublishedDailies()
  const idx = all.indexOf(date)
  if (idx === -1) return {}
  return {
    previous: idx > 0 ? all[idx - 1] : undefined,
    next: idx < all.length - 1 ? all[idx + 1] : undefined,
  }
}

function str(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback
}

function coerceDate(value: unknown, fallback: string): string {
  if (value instanceof Date) return value.toISOString().slice(0, 10)
  if (typeof value === 'string') return value
  return fallback
}

// Matches the "sources cited" line label in any supported locale.
const SOURCES_LABEL_RE = /\*\*(?:Fontes citadas|Sources cited|Fuentes citadas):?\*\*/i

// Extracts the comma-separated sources list from the sources-cited line.
function extractSources(rawBody: string): string {
  const m = rawBody.match(new RegExp(SOURCES_LABEL_RE.source + /\s*([^\n]+)/.source, 'i'))
  return m ? m[1].trim().replace(/\.$/, '') : ''
}

// Removes elements that the template renders separately (date heading, subline,
// lede blockquote, sources/method footer) so the body only contains article sections.
// HR pattern accepts `---`, `***`, `___` (markdown standard) AND `—` (em-dash) which
// Haiku 4.5 sometimes substitutes during translation, breaking the original separator.
const HR_PATTERN = `(?:---|\\*\\*\\*|___|—)`
function stripTemplateArtifacts(rawBody: string): string {
  const sourcesFooter = new RegExp(`\\n+${HR_PATTERN}\\n+${SOURCES_LABEL_RE.source}[\\s\\S]*$`, 'i')
  return rawBody
    .replace(sourcesFooter, '')
    .replace(/^# .+?\n+/, '')
    .replace(/^\*\*Polymarket × (?:Pesquisas|Polls|Encuestas) × (?:Notícias|News|Noticias)\*\*[^\n]*\n+/m, '')
    .replace(/^> [^\n]+(?:\n> [^\n]+)*\n+/m, '')
    .trim()
}

export function loadDaily(date: string, locale?: string): AfosDailyData | null {
  if (!isValidDate(date)) return null
  // Try {date}.{locale}.md first; fall back to canonical {date}.md (PT-BR).
  const canonical = join(DAILY_DIR, `${date}.md`)
  const localized = locale && locale !== 'pt-BR' && isValidLocale(locale)
    ? join(DAILY_DIR, `${date}.${locale}.md`)
    : null
  const path = localized && existsSync(localized) ? localized : existsSync(canonical) ? canonical : null
  if (!path) return null

  let fm: Record<string, unknown>
  let rawBody: string
  try {
    const parsed = matter(readFileSync(path, 'utf-8'))
    fm = parsed.data as Record<string, unknown>
    rawBody = parsed.content
  } catch (err) {
    console.error(`[afos-daily] Failed to read or parse ${date}.md:`, err)
    return null
  }

  // Required fields must be present in the frontmatter so the page doesn't
  // render skeleton content. If any is missing, return null so the caller
  // (page or API) can decide how to handle (notFound, fallback, etc).
  const lede = str(fm.lede)
  if (!lede || !fm.date || !fm.title) {
    console.warn(`[afos-daily] ${path} missing required frontmatter (lede/date/title)`)
    return null
  }

  const dateStr = coerceDate(fm.date, date)

  return {
    date: dateStr,
    updatedAt: str(fm.updatedAt),
    title: str(fm.title, `AFOS Daily — ${dateStr}`),
    locale: str(fm.locale, 'pt-BR'),
    status: str(fm.status, 'draft'), // Fail-safe: missing field => draft (hidden from prod)
    lede,
    body: stripTemplateArtifacts(rawBody),
    sources: extractSources(rawBody),
  }
}
